### ISSUE TITLE
Build fails without any information when use my own image on Amazon ECR

### ISSUE THREAD

**Issue by monteirobrena** [aws-amplify/amplify-console#100]
**Describe the bug**
I created an image on Amazon ECR and I'm trying to use it to deploy my React application on AWS Amplify but the build fails after success provision.

I would like to know how to show the provision details and how to start and see the build phase.

Also in the download of the log, nothing has been shown, too.

Thank you!

**To Reproduce**
1. Go to **Build settings**
2. Click on **Edit** in **Build image settings** box
3. Paste the link of ECR image on **Build image**
4. Save
5. Run the deploy

**Expected behavior**
It should show the status of failure on the build but not has been showed. Only the **Provision** box is visible.

**Sample code**
Dockerfile                                                                                                                                                                                  

```
FROM alpine:latest
MAINTAINER XXX

# Install dependencies
RUN apk update
RUN apk add --update --no-cache curl git openssl-dev nodejs nodejs-npm python3 python3-dev gcc libc-dev

# Update pip
RUN pip3 install --upgrade pip 

# Install awscli
RUN pip3 install awscli && rm -rf /var/cache/apk/*

# Install SAM CLI
RUN pip3 install aws-sam-cli

# Install AWS Amplify CLI
RUN npm install -g @aws-amplify/cli@1.7.2

# Node and NPM version
RUN node -v
RUN npm -v

ENTRYPOINT [ "bash", "-c" ]
```
<img width="1328" alt="Screen Shot 2019-09-04 at 15 19 17" src="https://user-images.githubusercontent.com/184617/64306833-72bd4380-cf6a-11e9-9712-f1819393c0b1.png">
<img width="640" alt="Screen Shot 2019-09-04 at 15 21 21" src="https://user-images.githubusercontent.com/184617/64306834-72bd4380-cf6a-11e9-87fd-a9023608f9fc.png">

**Comment by nimacks** [comment]
@monteirobrena, Alpine Linux has issues executing precompiled binaries and is currently not supported when using the custom build image feature.

**Comment by butaca** [comment]
I am having the same issue with an Alpine image but hosted on Docker Hub. Since Alpine Linux isn't an option, which is the smallest environment supported to write custom images? Thanks! :)

**Comment by nimacks** [comment]
@monteirobrena , did you try another image as recommended by @butaca ? Let us know if this works for you as well. Also, feel free to open this issue if you need any further assistance.

**Comment by monteirobrena** [comment]
@nimacks I don't. I'll try after but know I'm using the current image available on Amplify.
