### ISSUE TITLE
Need help on running my server api setup

### ISSUE THREAD

**Issue by ericpapasit** [aws-amplify/amplify-console#1000]
Hi folks,

Appreciate your insights!

I have a vue js app which act as an API endpoint which I successfully run locally through npm run start...
The structure of package.json is as follow:
{
  "name": "API server",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "nodemon app.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "async": "^3.2.0",
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "jsonwebtoken": "^8.5.1",
    "moment": "^2.27.0",
    "mongoose": "^5.9.13",
    "multer": "^1.4.2",
    "node-geocoder": "^3.27.0",
    "nodemon": "^2.0.3",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0"
  }
}

The app is already in github repo and also link to amplify console, my yml looks as:
version: 1
frontend:
  phases:
    # IMPORTANT - Please verify your build commands
    preBuild:
      commands: 
      - yarn install
    build:
      commands: 
      - yarn run start
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths: 
    - node_modules/**/*

But all of this when building, it fails and it always stucked with 'nodemon app.js', please help I'm desperately need this running, thanks a lot...

**Comment by hsspain** [comment]
@ericpapasit 

Amplify hosts API's a bit differently than what you have configured.

https://docs.amplify.aws/lib/graphqlapi/create-or-re-use-existing-backend/q/platform/js

Please view the linked documentation and let us know if you run into an issue deploying your API that way.

**Comment by ericpapasit** [comment]
@hsspain yes I understand, but I'm not trying to use the API of amazon, the thing is, we already created the API already, which is running in our local node js server perfectly, by invoking the command of 'npm run start', so we are thinking that it is running as a standalone app itself, so we are wondering if there is a way in aws amplify console to run this app and we can't find a reason why it should not, looking into the docs you gave, it seems that we will reconstruct the way our API works so that would be not we wanted.

Thanks for your reply buddy...

**Comment by hsspain** [comment]
@ericpapasit Unfortunately, we don't support hosting custom Node apps within Amplify. Other AWS services can potentially fit your use case, but you will need to use the supported methods to host an API with Amplify.
