### ISSUE TITLE
Can't "see" AWS Amplify environment variables

### ISSUE THREAD

**Issue by pjamieson** [aws-amplify/amplify-console#1001]
I have a React/Gatsby client with GitHub source control and continuous build/deployment enabled with a webhook. All builds and works fine, until the client needs to use an environment variable. (All works as expected from my local dev environment.)

I have the variables in the Environment variables section of the Amplify console. I've also added them under both env: variables: and build: commands: in the amplify.yaml file. The variables are apparently not compiled into the code, and console.log() reveals the variables are undefined at run time.

Source is at https://github.com/pjamieson/blake-dot-art

I don't think it should matter, but previously the site was hosted as a static site in an S3 bucket. That bucket is not longer configured for hosting. The site was moved to Amplify several weeks ago when it had external calls added to it.

Help! (And thanks!)

**Comment by hsspain** [comment]
@pjamieson Can you please provide your AppID and region you are hosting in?  Thanks.

**Comment by pjamieson** [comment]
AppID? Is that different from the App ARN?

App ARN: arn:aws:amplify:us-east-2:846179201391:apps/dd50y66k2av5i

Region: us-east-2

Thanks!

**Comment by hsspain** [comment]
That is perfect, thank you. We are investigating now.

**Comment by hsspain** [comment]
It appears that your buildspec.yml file in your repository does not include those environment variables and that is the build spec that the app uses during build/deployment. 

Try updating that, or removing it to use the Console saved settings.

Here is some documentation surrounding our build process:

https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html

**Comment by pjamieson** [comment]
Thanks for getting back so quickly. I think you nailed it identifying that buildspec.yml that was left behind from when the site was on S3. Makes sense that that's what's causing the problem.

So again, thank you VERY MUCH!

**Comment by pjamieson** [comment]
Removing the unwanted buildspec.yml from the repository, and prepending GATSBY_ to the variable names in the console (and changing the variable names to match where used in the code), made it all work. Thanks!
