### ISSUE TITLE
Domain activation is Failed -  One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by genert** [aws-amplify/amplify-console#1002]
**App Id**: d12vwpfgp9fawb
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
After configuring a domain for Amplify Console app, I get a following error:
> Error message: One or more of the CNAMEs you provided are already associated with a different resource.

When I check the CNAME records in Route53, there exists only 1 record value that was created by Amplify Console process.

When I remove, and retry, still same error appears.

**Error message**

> Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
AWS Amplify Console:
<img width="942" alt="Screenshot 2020-08-25 at 17 28 02" src="https://user-images.githubusercontent.com/1218788/91187003-5a54b480-e6f8-11ea-82db-47e7e742e571.png">

Route53 records:
<img width="1330" alt="Screenshot 2020-08-25 at 17 28 53" src="https://user-images.githubusercontent.com/1218788/91187199-91c36100-e6f8-11ea-9131-50fe67498753.png">

**Comment by hsspain** [comment]
We are looking into this now.

The error message suggests that your domain mydomain.pl or www.mydomain.pl are already associated with a CloudFront distribution through another app. If you have done that yourself, you will need to remove that association to use with another Amplify app.

**Comment by hsspain** [comment]
We don't see any record of www.mydomain.pl or mydomain.pl being associated with your app. 

It does look like the domain you are attempting to activate is associated with another CloudFront distribution, however. That domain will need to be removed from the other distribution before you can associate it with your app.
