### ISSUE TITLE
Deployment of  nextjs project served by a server.js is taking forever

### ISSUE THREAD

**Issue by shweta-codeprism** [aws-amplify/amplify-console#1006]
<img width="914" alt="Capture" src="https://user-images.githubusercontent.com/25504208/91277835-ff2acc80-e7a0-11ea-8d56-ea8c78226841.PNG">

**Comment by hsspain** [comment]
@shweta-codeprism Can you please provide us with your region and App ID?  The App ID is found in App settings > General
