### ISSUE TITLE
SSL configuration is Running - Cant verify R 53 domain name, even though other R 53 domain name worked

### ISSUE THREAD

**Issue by bill-medved** [aws-amplify/amplify-console#1007]
**App Id**: d1g1hnr0xrme76
**Region**: us-west-2
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.
I have a R53 domain name.  I tried to associate this amplify application to the domain name, and it was stuck in "SSL Configuration" for more than 8 hours, which I was surprised as the R 53 integration with Amplify works flawlessly in another AWS account.  I checked the R 53 records and they were correct (i.e. they had the appropriate Amplify records).  I searched the blogs and saw that one person had a similar problem, which they resolved by deleting the hosted zone in R53 for the domain, and then recreated it.  It seemed to solve their problem.  I did attempt to do so, though the results are the same.
**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by bill-medved** [comment]
As an aside, I needed to get this Amplify app live, so I attached a 2nd domain name that I had in R53 that was available.  This worked fine, though it is less then ideal as it is not the ultimate domain name I prefer to use.  I left the original domain name pending verification--it seems like the platform (Amplify?  R 53?) can't verify ownership even though the R53 domain verification (Amplify) records are correct (verified again).

**Comment by hsspain** [comment]
@bill-medved Please try removing the custom domain association from the Amplify app and re-adding it. Depending on the order of operations, Amplify uses a slightly different process for Route 53 domains.

**Comment by bill-medved** [comment]
I did remove the Amplify domain name association from the Amplify app, and
re-adding it.  Same result.

**Comment by hsspain** [comment]
@bill-medved The DNS propagation can sometimes take up to 24 hours. Please give it some time and let us know if it still is not verified after that time period.

**Comment by bill-medved** [comment]
Ok - I let it run for about 12 hours yesterday.

I just removed it and added it back again after your last email.

It is odd that I was able to register two amplify - R 53 domains name in 30
minutes though this one R 53 domain name does not work.  I would understand
if the domain name I was trying to register was not being managed by R 53,
though this is not the case.

Thank you for your assistance - I will check after 24 hours and report back.

Bill

**Comment by bill-medved** [comment]
Hello,
It has been more than 24 hours and the Amplify is still not verifying the
domain name.  Should I send you the domain name?
Thank you
Bill

**Comment by bill-medved** [comment]
Hello - do you have a status on this?  I have now connected 3 Route 51
Amplify sites w/o any issues.

I have invested in this domain name from a band name equity perspective,
and I still can't use it.

Please advise

Thank you

**Comment by garrettpinto** [comment]
Having the same issue, any update on resolving this issue?

**Comment by bill-medved** [comment]
I removed the hosted domain again - had R 53 create it again, and it still
can't find it...

**Comment by garrettpinto** [comment]
Did you verify the servers are the same by using this link?

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#my-domain-hosted-with-amazon-route-53-is-stuck-in-the-pending-verification-state

"My domain hosted with Amazon Route 53 is stuck in the Pending Verification state"

**Comment by bill-medved** [comment]
That did it.  Thank you for your assistance.

Please note the last time I tried to add the domain, a new message appeared
(attached to the email).  I hadn't seen this message before.  The "Fix this
for me" button did not correct the problem, though when I manually updated
the name servers Amplify was able to find the domain.

Thank you - Please close the ticket.
[image: Screen Shot 2020-09-15 at 7.14.28 AM.png]
