### ISSUE TITLE
Deploy fails without info

### ISSUE THREAD

**Issue by bronwynwoods** [aws-amplify/amplify-console#101]
**Describe the bug**
I have a Hugo site that builds fine locally. When deploying in Amplify, it builds successfully but then fails on the Deploy step, with the only information at the end of the logs being

`2019-09-05T22:28:30` [INFO]: Updating Edge config
2019-09-05T22:28:30 [ERROR]: Failed to deploy
2019-09-05T22:28:30 [INFO]: Deployment finished.`

**To Reproduce**
Trigger a build either from the console or with a commit to GitLab. The Provision, Cloning, and Frontend steps complete successfully. Deploy fails.

App ARN: arn:aws:amplify:us-east-1:XXXXXX:apps/d227os60tiw2zf

**Additional context**
The site is image heavy, so I'm wondering if the issues is something about artifact size, but I haven't been able to actually find anything to point at a cause. Even ideas on where to find any indication of what's going wrong would be appreciated.

**Comment by nimacks** [comment]
@bronwynwoods, did this just start happening or have you been able to build in the past with the same size of images?

**Comment by nimacks** [comment]
@bronwynwoods , from my end it looks like your build succeeded. See logs below.
Even though it displayed that the build failed, could you check your app to see if your updates are actually visible?
```
2019-09-05T22:24:44.690Z [INFO]: # Build artifact is: 1266MB 
2019-09-05T22:24:44.876Z [INFO]: # Uploading build artifact '__artifactsHash.zip'... 
2019-09-05T22:24:45.142Z [INFO]: # Build artifact is: 1267MB 
2019-09-05T22:24:45.142Z [INFO]: # Uploading build artifact '__artifacts.zip'... 
2019-09-05T22:25:09.832Z [INFO]: # Build artifact upload completed 
2019-09-05T22:25:09.924Z [INFO]: # Starting environment caching... 
# Nothing to write to env cache 
2019-09-05T22:25:09.924Z [INFO]: # Environment caching completed 
 
 2019/09/05 22:25:10 Phase complete: BUILD State: SUCCEEDED 
 2019/09/05 22:25:10 Phase context status code:  Message:  
 2019/09/05 22:25:10 Entering phase POST_BUILD 
 2019/09/05 22:25:10 Phase complete: POST_BUILD State: SUCCEEDED 
2019/09/05 22:25:10 Phase context status code:  Message:  
```

**Comment by bronwynwoods** [comment]
Nothing changed dramatically in terms of size between the last successful deploy and when it stopped working. But it started failing several months ago and I didn't get around to trying to fix it again until recently.

I double checked that changes are not appearing (changed some text in the last push to GitLab, the Deploy step failed as before, the site is unchanged).

**Comment by nimacks** [comment]
There’s a bug we identified have with the size of deployments. We are prioritizing a fix for this and will keep you updated when it is ready. In the meantime here’s a workaround you could try:

If you have feature branches or any branches that aren't being actively used, you can disconnect those branches which should be able to unblock you.

**Comment by desertmonkey** [comment]
We just started seeing this same issue about an hour ago.

**Comment by kununguaq** [comment]
AWS amplify console completes provision & build stages, but fails at deploy without giving a reason... The last 3 lines of my deployment log:

**2019-09-23T22:56:23 [INFO]: Updating Edge config
2019-09-23T22:56:23 [ERROR]: Failed to deploy
2019-09-23T22:56:23 [INFO]: Deployment finished.**

The crazy thing is i can't even re-deploy a previously stable build. What's up ?
My App ARN: arn:aws:amplify:eu-west-1:352247527096:apps/d1p38jyf52tcwc

**Comment by swaminator** [comment]
@kununguaq @desertmonkey we rolled out a fix so your app should deploy fine. @bronwynwoods can you check your app as well?

**Comment by desertmonkey** [comment]
Thank you @swaminator! We'll check out the fix soon against the one branch that kept failing to build. Our main branches (master, stage) do build, however (and have been since before your fix).

**Comment by bronwynwoods** [comment]
Thanks @swaminator! It looks like deployment is now working for my app.

**Comment by rkul** [comment]
Hello guys,

What about rolling this fix to other customers? We're faced with the same issue recently after enabling Previews feature.

![image](https://user-images.githubusercontent.com/5493637/69070062-9572da80-0a38-11ea-939f-4ca9b5fbfbb6.png)

We have 9 PRs opened and deployment fails randomly now with the same message as above:
```2019-11-18T13:19:48 [INFO]: Updating Edge config
2019-11-18T13:19:48 [ERROR]: Failed to deploy
2019-11-18T13:19:48 [INFO]: Deployment finished.```

Application ARN is `arn:aws:amplify:us-east-1:044883579400:apps/d2lwxktxnpxork`
