### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by vidhyasagarj** [aws-amplify/amplify-console#1010]
**App Id**: d3rg9crrppu2tu
**Region**: ap-southeast-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by hsspain** [comment]
@vidhyasagarj SSL configuration can take up to 24 hours to complete. Please see the linked documentation and let us know if you still do not have an associated domain in that time frame.

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html
