### ISSUE TITLE
Use different css for each instance connected with different branch of same repository

### ISSUE THREAD

**Issue by ParulSharma2622** [aws-amplify/amplify-console#1012]
**Is your feature request related to a problem? Please describe.**
I have created multiple amplify app's which are connected to a different branch foreg : **frontend-development** and **frontend-development-new** of same repository say **my-frontend-app**.

Now what I want to do is to have different styles for each instance. To overcome this problem I added a file which returns a json object having information regarding which css file will be loaded for that particular branch and it's working as expected. I am getting desired output when I switch between branches on my local. 

But when I push on github and it deploy latest code on amplify then it shows same css for both instances (latest one). I debug it by doing a console to know which file is exactly loading and found there's nothing wrong with file names as I am getting correct file names on both instances.

**Describe the solution you'd like**
I simply want to load different css for each different branch.

**Comment by hsspain** [comment]
@Shivishika Can you provide your App ID and region? This sounds like a caching issue but we can help to debug.

**Comment by Shivishika** [comment]
@hsspain 

here is the : 

app id : d1uka8klqzvprn

region : ap-southeast-2

URl 1 : https://frontend-development-new.d1uka8klqzvprn.amplifyapp.com/

URL 2 : https://frontend-development.d1uka8klqzvprn.amplifyapp.com/

**Comment by Shivishika** [comment]
can somebody look into this and help me to find a better solution to achieve this requirement.

**Comment by gwryssekk** [comment]
Hi @Shivishika.  I am looking into this.  Can you help me better understand the issue?  I noticed that both branches return identical css files (static/css/main.7ff68380.chunk.css) with identical contents.  Is the expected behavior that each branch should have a different css file or should it be the same file but have different contents, or something else?

**Comment by Shivishika** [comment]
yes, it's expected behaviour that each branch should have different css  i.e.. each instance will have identical functionalities but UI will be different. So I will create multiple amplify apps with each branch. 

When I checkout different branches on my local then it works perfectly fine and shows desired output but when it's deployed to amplify then it doesn't. 

Do I need to setup some build settings ??

You can suggest better solution to implement this functionality. it will be really appreciated.

**Comment by gwryssekk** [comment]
@Shivishika .  Thanks for the info.  I'm still having a bit of an issue understanding the use case.  You mention:

_Now what I want to do is to have different styles for each instance. To overcome this problem I added a file which returns a json object having information regarding which css file will be loaded for that particular branch and it's working as expected. I am getting desired output when I switch between branches on my local._

Is there a reason why each branch cannot have different css rules?  If not, can you explain the logic behind the json object you mentioned?

**Comment by ParulSharma2622** [comment]
The reason for having different css rules for each branch is I am developing an application which can be used by multiple brands and each brand will have their own style i.e.. css but functionality remains same across all the domains. 

To achieve this functionality, I decided following workflow : 

1. Suppose I have 3 brands i.e.. brand A, brand B, and brand C
2. I will create three different branches from master (master will always have latest code but I will not use master to deploy on production due to some reasons). So now I have three branches i.e.. branch_a, branch_b and branch_c. I used these three branches to create amplify apps. that means, I have three amplify apps.
3. As, I have created all the three branches from master so I have same functionality already added in all my branches.
4. The only thing I have to change is their styles. so I have created a platformConfig.js. 
5. In homepage component, I imported this file and check for the correct stylesheet file to be loaded.

So this workflow works perfectly when I switch branches on my local but when I deploy on amplify then it doesn't.

here is the snippet from platformConfig.js : 

const platformConfig = {
    "stylesheet_name": "new.css",
    "dynamo_affiliate_id": "random_id"
};
export default platformConfig;

Here is the snippet from Homepage Component, where I imported this file and trying to load styles based on above configuration : 

export default class HomePage extends React.Component {
    componentDidMount() {
        console.log(platformConfig.stylesheet_name);
        require('../styles/' + platformConfig.stylesheet_name);
    }

    render() {
        return (
            <div className="App" >
                <header className="App-header">
                    <img src={logo} className="App-logo" alt="logo" />
                    <p>
                        Edit <code>src/App.js</code> and save to reload.
                    </p>
                    <button onClick={checkAPI}>Check API without login</button>
                    let's check if different styles work or not
                </header>
            </div>
        );
    }
}

I have decided this workflow as per my knowledge. If you have a better solution then you can share. I will really appreciate.

Thanks
Shivani

**Comment by ParulSharma2622** [comment]
Why this issue has been marked as CLOSED. I haven't get any solution yet. @swaminator
