### ISSUE TITLE
Failed to Deploy

### ISSUE THREAD

**Issue by brenofrodrigues** [aws-amplify/amplify-console#1013]
** Please describe which feature you have a question about? **
Guys, We get this error on deploy. 

2020-08-25T16:11:15 [INFO]: Updating Edge config
2020-08-25T16:11:16 [ERROR]: Failed to deploy
2020-08-25T16:11:16 [INFO]: Deployment finished.

I try increase BUILD_TIMEOUT, but no success. 

** Provide additional details**

**Comment by hsspain** [comment]
@brenofrodrigues There is an open bug currently which occurs when a total number of files for an app exceeds an internal limit. 

We are actively working towards a solution for this and should have a fix live in the next few weeks.

**Comment by Athena96** [comment]
Closing this issue as the fix for this bug is being tracked here #115 
Please feel free to re-open if you think you are experiencing a separate issue. Thanks!
