### ISSUE TITLE
nextjs gatsby app amplify build error : aws-exports.js .gitignore

### ISSUE THREAD

**Issue by ywroh** [aws-amplify/amplify-console#1015]
**Describe the bug**
I am currently developing an ecommerce application with nextjs and gatsby. When deployed to amplify, the build fails with "Module not found: Can't resolve'../aws-exports' in ~" during the build process, because .gitignore is processed.

**To Reproduce**
Commenting out the aws-exports.js file in the .gitignore file really builds.

Please refer to it when working.

**Comment by hsspain** [comment]
@ywroh Can you provide your App ID and region? We will look into this for you.

**Comment by ywroh** [comment]
Thank you for your interest in the issues I have registered.

I am wondering if there will be any security issues with the app ID and region information.

First of all, the region is ap-northeast-2.

**Comment by swaminator** [comment]
@ywroh you have two choices:

1. Commit the `awsexports.js` file to your repo. 
2. Add the backend phase to the buildspec: https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#frontend-with-backend

**Comment by ywroh** [comment]
Thank you for answer. Let's work well with reference.
