### ISSUE TITLE
I have deleted amplify project from console but environment URL is still active

### ISSUE THREAD

**Issue by daghanacay** [aws-amplify/amplify-console#1016]
** Please describe which feature you have a question about? **
I have deleted Amplify console pipeline and created a new on on a same code base. older test branch URL was test.d3defgifiyxueg.amplifyapp.com new test environment URL is https://test.d2pa5dvahxqepk.amplifyapp.com/ 

they are both responding, how can I force remove service worker on client side after I move URL or the amplify application?

** Provide additional details**
Ping fails to test.d3defgifiyxueg.amplifyapp.com
After I delete the service worker manually on the browser web page no longer responds (expected)

**Comment by hsspain** [comment]
@daghanacay I am sorry to hear that you are having issues. The delete process is not immediate and may take a bit to complete.  Are you still seeing the same behavior?

**Comment by swaminator** [comment]
@daghanacay test.d3defgifiyxueg.amplifyapp.com can no longer be accessed.

**Comment by daghanacay** [comment]
Hi @swaminator,

Yes the environment is fine. Thanks for checking. My question still exist though. Is there a way to uninstall service workers in client browsers. 

Problem is, although the URL doors but exist, workers continue to work offline and provide the old content to the users. I want the workers associated to that domain to be uninstalled as well. If it is at all possible.
