### ISSUE TITLE
Domain activation is Failed  (Was originally connected to firebase)

### ISSUE THREAD

**Issue by eincs** [aws-amplify/amplify-console#1017]
**App Id**: dsgpreubdr89w
**Region**: ap-northeast-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.
```
I added custom domain to amplify application, but ti fails and retry fails also.
I checked route53 configuration but I couldn't found any errors.
(The domain was connected to firebase originally but we are trying to move website to amplify)
```

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 
```
Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
```

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
```
(Nope)
```

**Comment by hsspain** [comment]
@eincs I am sorry to hear you are having problems. It looks like the domain you are trying to add has already been associated with another CloudFront distribution. This could be another Amplify app or something outside of Amplify.

If you can, remove the association from the other distribution before you add the domain to your Amplify app.

**Comment by eincs** [comment]
Thank you!
