### ISSUE TITLE
Domain activation is Failed - CNAMEs already associated

### ISSUE THREAD

**Issue by xavierraffin** [aws-amplify/amplify-console#1018]
**App Id**: d1w6ukzxsonliz
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
After removing a previous cloudfront distribution I still cannot associate the domain to AWS Amplify console.
I did the change on Friday and retrying today still failed.
I deleted the CF distribution and other CNAMES (and even the A record pointing to the CF)

**Error message**
```
Error message: One or more of the CNAMEs you provided are already associated with a different resource. 
```

**Additional information**
The SSL certs steps worked

**Comment by xavierraffin** [comment]
Solved

**Comment by 719media** [comment]
Sooo, care to enlighten anyone with what the solution was?

**Comment by xavierraffin** [comment]
I had to delete domain association and recreate it from the beginning in Amplify console. The retry button was not enough
