### ISSUE TITLE
404 Rewrite returns XML Access Denied page. 404 Redirect works properly.

### ISSUE THREAD

**Issue by bvirlet** [aws-amplify/amplify-console#1019]
Hello,

We want to display a 404 page without changing the URL if someone tries to access a non-existent URL. To achieve this, we thought we could rely on 404 Rewrite rules.

As our last redirect rule we have set up a 404 rewrite rule:

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/792706/91853368-60034a80-ec62-11ea-9952-56408c8e96ff.png">

This breaks and returns an XML Access Denied page when users try to access a non-existent page.

If we switch to a 404 redirect, our 404 page is properly displayed.

How can we fix this to be able to use a 404 Rewrite?

Thanks!

App ID: d3b21b977rb7wd, branch master.

**Comment by gwryssekk** [comment]
Hi @bvirlet.  Sorry you are running into this.  I'll take a look and get back to you.

**Comment by bvirlet** [comment]
Thanks

**Comment by bvirlet** [comment]
Hi @gwryssekk,

Do you have any update on this?

Thanks!
Bruno

**Comment by swaminator** [comment]
@bvirlet do you have a `404.html` file at the root?

**Comment by Athena96** [comment]
Hi @bvirlet to achieve this, you need to use a 404 Redirect, not Rewrite:
https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html
Thanks!

**Comment by bvirlet** [comment]
@Athena96 if I use a redirect the URL will change, correct?

**Comment by edaemon** [comment]
This is also affecting us. With this rule in place:

```
[
    {
        "source": "/<*>",
        "target": "/404.html",
        "status": "404-200",
        "condition": null
    }
]
```

Accessing a URL that doesn't exist yields a `403`. Changing the redirect type to a plain `404` -- "404 (Redirect)" -- a proper 404 is displayed but the URL changes.

**Comment by adam-nygate** [comment]
Any update on this?

**Comment by abhi7cr** [comment]
Is your `404` page nested under a `404` folder, something along these lines: `404/index.html` ?  If so, could you change the rewrite rule to be:

```
[
    {
        "source": "/<*>",
        "target": "/404/index.html",
        "status": "404-200",
        "condition": null
    }
]
```

**Comment by bvirlet** [comment]
No, the 404 page isn't nested.

**Comment by ganipcanot** [comment]
@bvirlet Did you change your app since you last deployed?  Looking at your latest deployment I see a folder structure like `/404/index.html` relative to the root of the application.  If that's the case then the above rule should work.

**Comment by Athena96** [comment]
Closing this as there has been no response, please feel free to re-open if you are still facing the issue. Thanks!

**Comment by bvirlet** [comment]
Hi @Athena96 ,

No, we haven't changed our folder structure. The issue still persists:

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/792706/105009191-7c99f680-5a3a-11eb-9d16-07ccd925e5e7.png">

We've temporarily fixed it by changing our redirection rule from a 404 rewrite to a 404 redirect, but it's not ideal :

<img width="958" alt="image" src="https://user-images.githubusercontent.com/792706/105009290-976c6b00-5a3a-11eb-82d2-e9a11cc6aaac.png">
