### ISSUE TITLE
Domain activation is Failed - [Failing with error: One or more of the CNAMEs you provided are already associated with a different resource.]

### ISSUE THREAD

**Issue by abhinavsinghvi** [aws-amplify/amplify-console#102]
**App Id**: d2qvxn6grv8k28
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Domain activation is failing with error: Failing with error: One or more of the CNAMEs you provided are already associated with a different resource. Though in my route 53 I don't see same CNAME entries pointing to something else. Earlier it was pointing to some other cloudfront but that was deleted almost 12 hours back but still it is an issue.  On accessing the page using the domain used above it throws following error:
403 ERROR
The request could not be satisfied.
Bad request. 
Generated by cloudfront (CloudFront)
Request ID: vTz27C67CsfALFq_oj7qblpgCXQCB7rXvGpr_Z1RII1Cv_3P40wH1A==

**Error message**
It throws following error:
Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by nimacks** [comment]
@abhinavsinghvi , our records indicate that the app with Id `usezenden.com` has a succeeded in setting up the custom domain. The current status is `available`. Are you not able to view your site with the domain?

**Comment by abhinavsinghvi** [comment]
Yes it has worked in second attempt, in first attempt it has made entries in route 53 but never worked and then we have deleted the entries and tried again then it has worked almost after 8 hours.

It took more effort and time then we expected to deploy with AWS amplify, not sure what went wrong during first deployment and what took so long during second deployment and due to these issues our website was down for almost a day.

**Comment by nimacks** [comment]
Glad this is working for you now.
