### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by raveendradarsi** [aws-amplify/amplify-console#1020]
**App Id**: d3921pv3pvowra
**Region**: us-west-2
**Step**: SSL configuration
**Status**: Running

Domain Activation is taking very long time

**Comment by gwryssekk** [comment]
Hi @raveendradarsi.  I see that the domain associated with this app resolves.  Are you still experiencing issues?

If you haven't already done so, please check out our troubleshooting guide for custom domain issues: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
