### ISSUE TITLE
Auto-build failing

### ISSUE THREAD

**Issue by christodupreez** [aws-amplify/amplify-console#1022]
I started getting build failures with the message below:

**There was an issue connecting to your repo provider, click "Re-authenticate app" in General Settings, and then try your build again.**

I re-authenticated the app but still no luck.

The cloning repository log shows the following and hangs for long before failing:

```
Resolving deltas: 100% (1034/1034), done.
2020-09-03T12:03:40.582Z [INFO]: # Switching to commit: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2020-09-03T12:03:43.302Z [INFO]: Git SSH Key acquired
2020-09-03T12:03:43.341Z [INFO]: Agent pid 142
```

Any other suggestions?

**Comment by gwryssekk** [comment]
Hi @christodupreez.  Sorry you are experiencing this.  Has anything changed in your amplify.yml recently?  Also, can you provide me with your application ID and region so that I can take a look at the app?

**Comment by christodupreez** [comment]
Hi @gwryssekk, I recently updated my Amplify CLI.

My amplify.yml file has not changed as far as I know.

I have two apps doing the same, their ids are d3fzcbhjzhy0vx and dalkyjjnj26u4, the region is eu-west-2
