### ISSUE TITLE
Amplify CI does not build front end

### ISSUE THREAD

**Issue by tom-huguenard** [aws-amplify/amplify-console#1024]
** Please describe which feature you have a question about? **
![image](https://user-images.githubusercontent.com/20403116/92177100-7564aa00-ee05-11ea-9316-86f4d867514e.png)

** Provide additional details**
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - pwd
        - npm ci
    build:
      commands:
        - pwd
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

**Comment by swaminator** [comment]
@tom-huguenard there's sometimes a UI bug that occurs. Can you try refreshing hte page or clicking on the URL for the site?
