### ISSUE TITLE
Domain activation is Failed - [Error message: One or more of the CNAMEs you provided are already associated with a different resource]

### ISSUE THREAD

**Issue by divya12391** [aws-amplify/amplify-console#1025]
**App Id**: d3inwlgcgg1zwo
**Region**: ap-south-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by gwryssekk** [comment]
Hi @divya12391 .  This error occurs when you are attempting to associate a domain to a cloudfront distribution when it is already tied to another distribution.  Do you have other cloudwatch distributions associated with this domain name?

**Comment by nimacks** [comment]
@divya12391 is this still an issue?

**Comment by divya12391** [comment]
No it is resolved. Thank you.
