### ISSUE TITLE
Hosted woff2 fonts have wrong content type 

### ISSUE THREAD

**Issue by paya-cz** [aws-amplify/amplify-console#1027]
I use Amplify managed hosting for my Angular project. The project assets include a .woff2 fonts that are deployed together with the app.

Amplify hosting serves the font with `application/octet-stream` content-type, while the correct content type is `font/woff2`.

I don't see a way in the console to change the content type of individual files or files based on extension. The only workaround is to use my own S3/CloudFront hosting.

Can you fix the content-type sniffing?

**Comment by gwryssekk** [comment]
Hi @paya-cz .  We have an update in progress of some of our hosting functionality and it has upgraded the way content-type is set.  I will verify that the upcoming process handles .woff2 fonts correctly.

**Comment by argok2sper** [comment]
Hi, I'm experiencing the same problem, but it's showing `content-type: text/html` for `font/woff2`. What is the current status of this issue?

**Comment by Voice-ux-lab** [comment]
This was an issue for me to.  I ended up converting my font files to a different format but it would be nice if I didn't have to do that!

**Comment by ganipcanot** [comment]
Resolving due to age - please re-open if you are still experiencing issues.
