### ISSUE TITLE
Use different css for each instance connected with different branch of same repository

### ISSUE THREAD

**Issue by ParulSharma2622** [aws-amplify/amplify-console#1032]
Is your feature request related to a problem? Please describe.
I have created multiple amplify app's which are connected to a different branch foreg : frontend-development and frontend-development-new of same repository say my-frontend-app.

Now what I want to do is to have different styles for each instance. To overcome this problem I added a file which returns a json object having information regarding which css file will be loaded for that particular branch and it's working as expected. I am getting desired output when I switch between branches on my local.

But when I push on github and it deploy latest code on amplify then it shows same css for both instances (latest one). I debug it by doing a console to know which file is exactly loading and found there's nothing wrong with file names as I am getting correct file names on both instances.

here is the :

app id : d1uka8klqzvprn

region : ap-southeast-2

URl 1 : https://frontend-development-new.d1uka8klqzvprn.amplifyapp.com/

URL 2 : https://frontend-development.d1uka8klqzvprn.amplifyapp.com/

Describe the solution you'd like
I simply want to load different css for each different branch.

**Comment by ParulSharma2622** [comment]
anyone looking into this.?

**Comment by nimacks** [comment]
@ParulSharma2622 can you provide details of the file returning a JSON object for switching? Also, describe how you are switching between local branches locally.

**Comment by ParulSharma2622** [comment]
To achieve this functionality, I decided following workflow :

1. Suppose I have 3 brands i.e.. brand A, brand B, and brand C
2. I will create three different branches from master (master will always have latest code but I will not use master to deploy on production due to some reasons). So now I have three branches i.e.. branch_a, branch_b and branch_c. I used these three branches to create amplify apps. that means, I have three amplify apps.
3. As, I have created all the three branches from master so I have same functionality already added in all my branches. The only thing I have to change is their styles. so I have created a platformConfig.js.
4. In homepage component, I imported this file and check for the correct stylesheet file to be loaded.

So this workflow works perfectly when I switch branches (using git checkout command to switch branches on local) on my local but when I deploy on amplify then it doesn't.

here is the snippet from platformConfig.js :

const platformConfig = {
"stylesheet_name": "new.css",
"dynamo_affiliate_id": "random_id"
};
export default platformConfig;

Here is the snippet from Homepage Component, where I imported this file and trying to load styles based on above configuration :

import React from 'react';
import platformConfig from '../platformConfig';

require('../styles/' + platformConfig.stylesheet_name);

export default class HomePage extends React.Component {

render() {
    return (
        <div className="App" >
            <header className="App-header">
                <img src={logo} className="App-logo" alt="logo" />
                <p>
                    Edit <code>src/App.js</code> and save to reload.
                </p>
                <button onClick={checkAPI}>Check API without login</button>
                let's check if different styles work or not
            </header>
        </div>
    );
}
}

I have decided this workflow as per my knowledge. If you have a better solution then you can share. I will really appreciate.

Thanks
Parul

**Comment by swaminator** [comment]
@ParulSharma2622 this is something specific to your app. You can use config within your application to determine which css to load. We cannot provide a recommendation on a specific workflow.
