### ISSUE TITLE
Can't connect custom subdomain with amplify application

### ISSUE THREAD

**Issue by Oscarsgc** [aws-amplify/amplify-console#1033]
**App Id**: d35aybm0j2pzux
**Region**: us-east-1
**Step**:
**Status**: Available

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
The configuration has been completed in both Amplify and 3rd party dns service(Namecheap) but the redirection is not getting complete, I have created two subdomains but none of them seems to be working.

As you can see in the screen shot, there are no errors but would like to know if we are missing something. The configuration in the 3rd party domain is reported to be completed.

<img width="1357" alt="Screen Shot 2020-09-07 at 10 21 08 AM" src="https://user-images.githubusercontent.com/4324370/92397888-8bb88180-f0f5-11ea-808b-9d903bfed398.png">

Also I removed the redirect from configurations as I saw in other issues:
![Screen Shot 2020-09-07 at 10 33 10 AM](https://user-images.githubusercontent.com/4324370/92397932-9e32bb00-f0f5-11ea-9b5c-1e27e9dea56d.png)

It's an Angular 8 Application, amplify url is working fine but I need to associate my custom domain

**Comment by nimacks** [comment]
Thanks for reporting this issue, we're investigating and will update this ticket shortly
