### ISSUE TITLE
Amplify Console is blank all of a sudden

### ISSUE THREAD

**Issue by dragosiordachioaia** [aws-amplify/amplify-console#1034]
I have a few projects all running fine on Amplify, but for one of them, about a week ago, the main console view started showing a blank page. 

All of the other projects work completely fine.

All of the sub-pages on the problem project also work fine (General, Domain Management, Previews etc) if I navigate to them directly, but they do also break depending on what sequence of pages I go through. There are also console errors showing (displayed below). Sometimes it even crashes to the point that I have to restart the page.

<img width="523" alt="Screenshot 2020-09-09 at 13 30 11" src="https://user-images.githubusercontent.com/21035153/92598951-78e2b000-f2a1-11ea-9ee3-bdacc755a83b.png">
<img width="526" alt="Screenshot 2020-09-09 at 13 30 37" src="https://user-images.githubusercontent.com/21035153/92598956-7b450a00-f2a1-11ea-8de1-f619e6950248.png">
<img width="1440" alt="Screenshot 2020-09-09 at 13 32 54" src="https://user-images.githubusercontent.com/21035153/92598960-7bdda080-f2a1-11ea-90aa-9caba47fae5a.png">

**Comment by dragosiordachioaia** [comment]
After further investigation, it turns out that the problem was caused by the YAML file uploaded to the "build settings" section, which had a duplicated section. This happened because when doing Cmd+a in the editor, and then "paste", "delete" or really anything else, it doesn't actually delete the selected content, it just ignores it.

This highlights 2 things:
1) Having an error with the YAML file should actually be highlighted in the UI, not just in the console.
2) The Amplify Console itself should not just crash, without feedback to the user.

**Comment by nimacks** [comment]
@dragosiordachioaia we're working on fixing this.

**Comment by fsids** [comment]
I saw this error today as well.  deleted the yaml from the build settings. project has a amplify.yaml in the code.  This resolved the blank console error

🙏🏼

**Comment by dragosiordachioaia** [comment]
Deleting the file is not the solution, catching the validation error and handling it appropriately is.

**Comment by fsids** [comment]
agree...   just sharing that this thread was helpful

**Comment by Athena96** [comment]
Hello all, thank you for your patience. We have deployed a fix for this, so it should no longer be an issue. Feel free to re-open this ticket if you continue to face this or related issues. Thank you!
