### ISSUE TITLE
Domain activation is Failed - CNAME associated elsewhere.

### ISSUE THREAD

**Issue by Jattwood90** [aws-amplify/amplify-console#1035]
**App Id**: dwskx68os089p
**Region**: eu-west-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Repeated failure of domain activation.

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Domain name was originally associated with an S3 bucket for a Flask app that I have since deleted. I have tried deleting my amplify app, and have deleted all the CNAME records associated with the domain (devattwood.co.uk). I can't seem to find where this CNAME record is associated to elsewhere, so have no idea why this is failing.

**Comment by Jattwood90** [comment]
Just to add to this, I have checked my Cloudfront distribution settings and there is nothing there. I have deleted the CNAME records again and still nothing appears to change.

**Comment by nimacks** [comment]
Hi @Jattwood90, I've located the CloudFront Distribution associated with the domain. Please look out for an email with this information.

**Comment by Jattwood90** [comment]
Thanks @nimacks. The details you provided me in the email relate to my account, but I am still unable to find the distribution you refer to, on my console. According to my account I have no Cloudfront distributions set up.

I've noticed that I have the exact same problem as this issue that was raised: https://github.com/aws-amplify/amplify-console/issues/797 - which didn't have a solution rather suggesting an updated console solved the problem.

Is there a way I can search via the distribution number you sent me, so I can ensure everything from my previous app has been deleted?

Thanks!

**Comment by Jattwood90** [comment]
Right, progress. Have found a way of identifying the distribution - resource-groups/tag-editor/find-resources - this gave me the ability to search by the number.

Solved one problem and found another... Having tried to delete the CF Distribution, I'm prompted with the response that the delete failed: 
"Deleting RestApi auvccspw0k failed. Please remove all base path mappings related to the RestApi in your domains: devattwood.co.uk".

I've tried searching for resources online to assist in this, but the general responses appear to be along the lines that this is a bug. Does anyone have any ideas where I should go from here?

**Comment by Jattwood90** [comment]
Further progress but still no resolutions. I'm still prompted with the fact that the domain is linked to another distribution. However on the AWS CLI when I search: list-distributions, I get nothing in response. Annoyingly there's a certificate from my old app, that I can't delete for this reason. It responds saying I need to remove the association before removing the certificate.

**Comment by niknokseyer** [comment]
Were you able to get this resolved @Jattwood90?

**Comment by ganipcanot** [comment]
Have you since delete the app/domain?  I can't find this record (`dwskx68os089p`) on our side

**Comment by Jattwood90** [comment]
So I managed to delete the app, via the AWS CLI. Every command I was running told me it no longer existed, so in my mind there shouldn't have been a confliction.

However, when I tried the process of linking the domain to the new app I still received an error message. I have a feeling it's something to do with the security certificate that still appears to be linked to the previous app. Numerous attempts at deleting that certificate failed, both in the GUI and CLI so I have up and purchased a new domain.

Sorry everyone, no fix!

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
