### ISSUE TITLE
Speed up deploying to test Content Security Policies

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-console#1037]
Via the build settings in de AWS Amplify Console you can set Content Security Policy Headers in the customer headers section.

But setting and testing headers is sometimes trail and error. To deploy each time takes 10 minutes approx. Is there a way to speed this up?

**Comment by Athena96** [comment]
Hi @rpostulart, when you say "sometimes trail and error" are you experiencing any build/deployment failures or are you referring more to the time it takes to deploy each time you want to update your custom headers? Thanks!

**Comment by rpostulart** [comment]
No failures. Indeed the second. When adjusting the headers and to validate if the settings are correct, I have to do a full deployment which takes approx 10 minutes over and over again.

**Comment by ganipcanot** [comment]
We are working on some optimizations to the deployment which should hopefully bring the time down you can track the updates [here](https://github.com/aws-amplify/amplify-console/issues/115)

**Comment by rpostulart** [comment]
ok looking forward to this!

**Comment by litwicki** [comment]
This will be addressed with #115
