### ISSUE TITLE
Amplify behind Cloudfront

### ISSUE THREAD

**Issue by travispaxton** [aws-amplify/amplify-console#1038]
** Please describe which feature you have a question about? **

I'm trying to use an Amplify app as an origin for Cloudfront. I'm aware that there are issues with using Cloudfront in front of other Cloudfront/API Gateway setups when you try to pass headers like Host to the origin. In my case, I'm not passing any headers whatsoever. When I visit the Cloudfront domain (e.g. example.com), the URL is redirected to something like `https://example.com/tvzRVU9pSxH8G2tHFQzmYT9cH3FKutbwOy3Lrp7uMg/` instead of proxying the content from the origin.

** Provide additional details**

I know I can add multiple custom domains to the Amplify app, but this is an experiment for an app where customers can set up their own Cloudfront/reverse proxies that point to my app using domains that I don't control.

**Comment by Athena96** [comment]
Hi @travispaxton thanks for reaching out. Can you please share more info on your setup. It's not possible to have an Amplify app be an origin for another CloudFront distribution. https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/DownloadDistS3AndCustomOrigins.html

Would you be able to achieve a similar result by using subdomains?
