### ISSUE TITLE
Any time I redirect to the same URL, there is an Access Denied

### ISSUE THREAD

**Issue by liuhantao9** [aws-amplify/amplify-console#104]
** Please describe which feature you have a question about? **
The Rewrite and Redirect

** Provide additional details**
I have a website which has specific id for every blog, an example for a blog URL will be like https://master.d135sel40baxm.amplifyapp.com/blog/5d732f3f93c5040004a9df19
I simply just want to direct to this URL, so I deleted any redirect on my console. Now it is showing me that I have an Access Denied.

**Comment by swaminator** [comment]
When you run it from `localhost`, are you able to navigate to that path?

**Comment by liuhantao9** [comment]
> When you run it from `localhost`, are you able to navigate to that path?

yes!

**Comment by nimacks** [comment]
@liuhantao9 , I'm able to navigate to https://master.d135sel40baxm.amplifyapp.com/blog/5d77579dd6ffe40004492c07 without being shown any access denied message. Is this still an issue?

**Comment by liuhantao9** [comment]
It is fixed. Just do the SAP redirect and it is all good.

**Comment by zhichunl** [comment]
Hi
