### ISSUE TITLE
Query parameters being removed and redirected

### ISSUE THREAD

**Issue by chris** [aws-amplify/amplify-console#1040]
** Please describe which feature you have a question about? **
This likely falls under the Rewrites category...

** Provide additional details**
I have a Nuxt app that has a page that can accept query parameters. This page works fine if it gets navigated to from another page within the app (e.g. I do this: `this.$router.push({ path: '/somepage', query: { someparam: somevalue } })` . But if I directly paste a URL with a query parameter into the browser, I get a 301 redirect from S3/Cloudfront, where it strips off the query parameters and redirects to the page.  e.g. if I directly navigated to: `https://example.com/somepage?someparam=foo`, that will result in a 301 redirect to `https://example.com/somepage/`. Is there may be some kind of rewrite rule I need to setup to allow this in my Amplify deploy, or are query parameters not allowed to be directly navigated to for an Amplify app?

**Comment by swaminator** [comment]
@chris currently this is not supported. However we have a workaround as mentioned here: https://github.com/aws-amplify/amplify-console/issues/886#issuecomment-668249281

**Comment by chris** [comment]
@swaminator I can't get path based pages to work either - does Amplify not work with ANY dynamic pages? e.g. if I change the above to be https://example.com/somepage/somevalue/ (where `somevalue` is the dynamic part), that seems to always give me an access denied error (I get an HTTP 403 response).

**Comment by chris** [comment]
I've abandoned the path params, as ultimately that doesn't work with static sites either (for a generic any value path param). 
As mentioned in #97 but also in #792 , a workaround for this is to put a trailing slash after the page name, and before the query params, e.g.:  `/somepage/?param=value`.

**Comment by swaminator** [comment]
@chris we just launched support for this: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#query-strings-and-path-parameters. Let us know if this works for you.

**Comment by pranavbadami** [comment]
> As mentioned in #97 but also in #792 , a workaround for this is to put a trailing slash after the page name, and before the query params, e.g.: `/somepage/?param=value`.

Thanks so much for this @chris , just helped us out. Still seeing this issue as of July 2022.

**Comment by chinmaysoni2904** [comment]
> I've abandoned the path params, as ultimately that doesn't work with static sites either (for a generic any value path param). As mentioned in #97 but also in #792 , a workaround for this is to put a trailing slash after the page name, and before the query params, e.g.: `/somepage/?param=value`.

It Worked for me.
