### ISSUE TITLE
Issue in connecting feature branch to Amplify

### ISSUE THREAD

**Issue by SFaraji** [aws-amplify/amplify-console#1042]
I'm trying to add a new feature branch to our amplify project, but when I'm trying to "Add repository branch" it failed and return a Failed to load resource: the server responded with a status of 404 () and doesn't allow us to add any branches, but our limit for adding branches is the default 50.

Please advise what to do.

![image](https://user-images.githubusercontent.com/6940197/92987299-a8452700-f504-11ea-9605-582353a6b20d.png)
![image](https://user-images.githubusercontent.com/6940197/92987303-b8f59d00-f504-11ea-82e5-029e2ceabdad.png)

**Comment by Athena96** [comment]
Hi @SFaraji can you please share your appId and also if possible the number of branches in your repo. Thanks!

**Comment by SFaraji** [comment]
Hi Athena96, here is the Amplify App ID: d4i8d52zi6kcj and we got 3 branches for this repo.

**Comment by SFaraji** [comment]
@Athena96, any solution?

**Comment by SFaraji** [comment]
This bug is very annoying and causes integration manually.

**Comment by Athena96** [comment]
Hi, @SFaraji are you still facing this issue? If so can you provide any additional repro steps, I have not been able to repro on my end. Thanks!

**Comment by SFaraji** [comment]
Hi @Athena96, yes I'm still facing this issue. 

Here the repro steps:
1. Click connect branch 
2. Select the Repository service provider, in my case is "Gitlab" and click Next button 
3. The screen will be locked and if you open from inspect element you can see `Failed to load resource: the server responded with a status of 404 ()`

Please advise what to do.

**Comment by SFaraji** [comment]
What is going on? Why no one responsible to solve this issue. This is causing a huge issue for us for not allowing us to create any branch from the console.
cc: @abhi7cr @Athena96 @ericclemmons @hyandell

**Comment by arturocanalda** [comment]
Same issue here. Actually in my case I could manage to connect branches from the console until I had to migrate my repo and update the link of my Amplify App (which btw, can only be done from the command line). It seems from the Console Amplify tries to read Github's branches by using the old OAuth token.  

Amplify has great things but also horrible ones that make you easily feel like loosing control of your project.

**Comment by SFaraji** [comment]
Exactly right @arturocanalda, Amplify is so great for managing web apps but this bug regarding managing multiple branches for prod, sandbox, and pre-release make it annoying to use the command line in order to connect a new branch.

I'm looking forward they will fix this issue ASAP 🤞

**Comment by SFaraji** [comment]
Please look over the issue with the wrong GitLab id which is used in amplify and that stops us from connecting our branches. So annoying.

**Comment by UniLu419** [comment]
Same issue here. As I found by adding fetch breakpoint(url contains gitlab), the url sent to gitlab is using number 1 as projectid in the url and that's the reason why it is returning 404

**Comment by SFaraji** [comment]
@abhi7cr @Athena96 @arturocanalda @abhi7cr @UniLu419, I have contacted AWS tech support and they finally found the issue which is causing if there is a number at the start of the group/username URL (e.g. 1abc should be abc) otherwise Amplify will take the number as the projectId.

**Comment by abhi7cr** [comment]
Yup @SFaraji that’s correct. We had an issue with the way we parsed the repository namespace(_username/response_ _groupname/reponame_) when it starts with a number. We have a fix ready, and will update this thread once it’s deployed 🙂

**Comment by Athena96** [comment]
Hello, the fix has been fully deployed, closing the issue. 
Please feel free to re-open if it persists for you. Thanks you!

**Comment by Michaelmw17** [comment]
I have a single branch and no errors on localhost but am seeing this same error on my site, sometimes it only appears once running lighthouse  then the URL will add a``/``  to the end like so : ``https://www.jdpelectrical.com.au/About/`` 

I see the error : 
``Failed to load resource: the server responded with a status of 404 () www.jdpelectrical.com.au/:1 ```

Original URL: ``https://www.jdpelectrical.com.au/About``

WEBSITE:
https://www.jdpelectrical.com.au/About/
 Github service worker registration :
https://github.com/Michaelmw17/computing-machine/blob/main/src/serviceWorkerRegistration.js

**Comment by Michaelmw17** [comment]
Reference : https://github.com/aws-amplify/amplify-console/issues/1042#issuecomment-925434086 

I have a single branch and no errors on localhost but when pushed to AWS Amplify am seeing this same error on my Live site, sometimes it only appears once running lighthouse then the URL will add a ```/```  to the end like so : ```https://www.jdpelectrical.com.au/About/```

I see the error :
```Failed to load resource: the server responded with a status of 404 () www.jdpelectrical.com.au/:1 ```

Original URL: https://www.jdpelectrical.com.au/About 

WEBSITE:
https://www.jdpelectrical.com.au/About

Github service worker registration :
https://github.com/Michaelmw17/computing-machine/blob/main/src/serviceWorkerRegistration.js
