### ISSUE TITLE
Amplify Tutorial: Error while deploying build using AWS Amplify Console

### ISSUE THREAD

**Issue by SandeepKoparde** [aws-amplify/amplify-console#1043]
[AmplifyError.txt](https://github.com/aws-amplify/amplify-console/files/5213868/AmplifyError.txt)

I am trying to execute the tutorial at:
https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/

I am able to get through first 2 modules and most of module 3,
I am able to run the app locally after adding the auth module.

However, after committing the code to GitHub, the automated build fails in AWS Amplify Console.
Please advice

**Comment by Kyohey-Kondo** [comment]
I'm also suffered from that error.

**Comment by Kyohey-Kondo** [comment]
I also suffered from this error.
In my case, the error caused when the additional code as
```
mport config from './aws-exports';
```
added in the module 3 of the tutorial.

The error text in amplify console is 
```
2020-09-13T15:19:35.544Z [INFO]: Failed to compile.
2020-09-13T15:19:35.544Z [INFO]: ./src/index.js
                                 Cannot find file './aws-exports' in './src'.
2020-09-13T15:19:35.563Z [WARNING]: error Command failed with exit code 1.
2020-09-13T15:19:35.563Z [INFO]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2020-09-13T15:19:35.568Z [ERROR]: !!! Build failed
2020-09-13T15:19:35.568Z [ERROR]: !!! Non-Zero Exit Code detected
2020-09-13T15:19:35.568Z [INFO]: # Starting environment caching...
2020-09-13T15:19:35.695Z [INFO]: # Environment caching completed
Terminating logging...
```

As mentioned in the text 'Cannot find file './aws-exports' in './src'.', it may the problem that the AWS amplify cannot find aws-exports.js folder although the folder exists in local environment.
The folder is negligible due to the .gitignore file.
I overcame the error to comment out the aws-exports in .gitignore file.
It is noted that I don't know this modification can be the essential answer.

**Comment by swaminator** [comment]
@Kyohey-Kondo  This is because you do not have the backend builds configured as part of your CI/CD. In order to get this to work you have 2 options:
1. Option 1: Commit the aws-exports that in gitignore
2. Option 2: Enable frontend+backend builds: https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#frontend-with-backend

**Comment by Kyohey-Kondo** [comment]
Thank you for your comment.
I,ll check my code again.

**Comment by SandeepKoparde** [comment]
> @Kyohey-Kondo This is because you do not have the backend builds configured as part of your CI/CD. In order to get this to work you have 2 options:
> 
> 1. Option 1: Commit the aws-exports that in gitignore
> 2. Option 2: Enable frontend+backend builds: https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#frontend-with-backend

Hi Nikhil,I will verify your suggestions in a couple of days and give you feedback.
However, I think this issue should not be closed unless the tutorial document is updated to reflect the points mentioned above,
There is no way for a user executing the tutorial to know about these two points.

**Comment by SandeepKoparde** [comment]
> I also suffered from this error.
> In my case, the error causes when the additional code as
> 
> ```
> import config from './aws-exports';
> ```
> 
> is added in the module 3 of the tutorial.
> 
> The error text in amplify console is
> 
> ```
> 2020-09-13T15:19:35.544Z [INFO]: Failed to compile.
> 2020-09-13T15:19:35.544Z [INFO]: ./src/index.js
>                                  Cannot find file './aws-exports' in './src'.
> 2020-09-13T15:19:35.563Z [WARNING]: error Command failed with exit code 1.
> 2020-09-13T15:19:35.563Z [INFO]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 2020-09-13T15:19:35.568Z [ERROR]: !!! Build failed
> 2020-09-13T15:19:35.568Z [ERROR]: !!! Non-Zero Exit Code detected
> 2020-09-13T15:19:35.568Z [INFO]: # Starting environment caching...
> 2020-09-13T15:19:35.695Z [INFO]: # Environment caching completed
> Terminating logging...
> ```
> 
> As mentioned in the text 'Cannot find file './aws-exports' in './src'.', it may the problem that the AWS amplify cannot find aws-exports.js folder although the folder exists in local environment.
> The folder is negligible due to the .gitignore file.
> I overcame the error to comment out the aws-exports in .gitignore file.
> It is noted that I don't know this modification can be the essential answer.

Hi @Kyohey-Kondo ,
I can verify that the error goes off when I comment the "aws-exports.js" entry in .gitignore file.
I was able to complete the entire tutorial, though I had to rectify a few more instructions.
Thanks for your help.

Hi @swaminator ,
I didn't quite understand your second option.
Request you to please let me know what should be exact contents of the amplify.yml file.
Should they be the exact same as that mentioned in the link?
Or should I download the existing amplify.yml from the amplify console and append the contents in the link to this downloaded file?
Sorry for bothering you.
Since I am still getting my hands wet on Amplify, I might some hand holding from senior resources.
Thanks for your help.

Regards
Sandeep Koparde

**Comment by SandeepKoparde** [comment]
> Thank you for your comment.
> I,ll check my code again.

@Kyohey-Kondo 
Please do let me know if you were able to get the tutorial working by following the "Option 2" mentioned by @swaminator 

Regards
Sandeep Koparde

**Comment by swaminator** [comment]
@SandeepKoparde @Kyohey-Kondo the tutorial has been updated: https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/

**Comment by amitvchaudhary** [comment]
@swaminator I went through the updated docs and my backend build is still failing. I also uncommented aws-exports.js file from .gitignore but still no luck. The build fails at the below step:

                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple

**Comment by sv1979** [comment]
For me it fails after this step:
`# Executing command: amplifyPush --simple
2021-05-25T06:15:04.662Z [INFO]: File project: data should NOT have additional properties: 'graphqltransformer'
2021-05-25T06:15:04.663Z [INFO]: JSONValidationError: File project: data should NOT have additional properties: 'graphqltransformer'`

**Comment by uferekalu** [comment]
> @swaminator I went through the updated docs and my backend build is still failing. I also uncommented aws-exports.js file from .gitignore but still no luck. The build fails at the below step:
> 
> ```
>                              # Starting phase: build
>                              # Executing command: amplifyPush --simple
> ```

I have exactly same issue. It fails at the backend build stage. I was even thinking that service role has a hand in its failing and I have created a service role and yet no luck...

**Comment by ThomasSalty** [comment]
I have the same error too. I went trough the steps a couple of times already but the build keeps failing in module 3.

I also tried to add auth without a backend and after `amplify configure`, I executed `amplify init` to initialize the project with the default configuration but the build still fails now in the "preBuild" phase of the frontend:

(Note: the app still works fine locally both ways...)


  ```
# Starting phase: preBuild
                                 # Executing command: npm install
ipts build`
                                    npm ERR! Exit status 1
                                    npm ERR!
                                    npm ERR! Failed at the amplifyapp@0.1.0 build script.
                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-01-04T14:14:44.355Z [HELP]: Outputting the npm debug log
                                 0 info it worked if it ends with ok
                                 1 verbose cli [
                                 1 verbose cli   '/root/.nvm/versions/node/v14.18.1/bin/node',
                                 1 verbose cli   '/root/.nvm/versions/node/v14.18.1/bin/npm',
                                 1 verbose cli   'run',
                                 1 verbose cli   'build'
                                 1 verbose cli ]
                                 2 info using npm@6.14.15
                                 3 info using node@v14.18.1
                                ...
                                 22 error amplifyapp@0.1.0 build: `react-scripts build`
                                 22 error Exit status 1
                                 23 error Failed at the amplifyapp@0.1.0 build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2022-01-04T14:14:44.358Z [ERROR]: !!! Build failed
```
