### ISSUE TITLE
Custom Domains Not Working - No Error

### ISSUE THREAD

**Issue by SunderApps** [aws-amplify/amplify-console#1045]
**App Id**: d2txrp5nj1jgzz
**Region**: us-east-2
**Step**:
**Status**:

**Issue/question**
Two of my Route53 domains aren't working after successfully adding them to Amplify projects.  I got no error message, but when I navigate to the url it can't be reached.  I don't think I've done anything different from my working domains.

Using whatsmydns.net, it looks like something went wrong with DNS propagation.

I've tried removing the domain and adding it again, deleting the project and starting the process over, and creating a completely new repository/project.  None of that has worked so far.

Thanks!

**Error message**
None

**Comment by vyasnikhil123** [comment]
Same issue i got

**Comment by vyasnikhil123** [comment]
Kindly tell me how can i solve this after adding my custom domain but it is not redirecting

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by brnmye** [comment]
We are going to close out this issue, but please feel free to re-open if you still need help.
