### ISSUE TITLE
Which IAM action is used with Amplify Push ?

### ISSUE THREAD

**Issue by maximelebastard** [aws-amplify/amplify-console#1046]
Hi 👋 

**Please describe which feature you have a question about?**

IAM with Amplify

**Provide additional details**

I'd like to restrict the ability to deploy an Amplify backend only to the environment matching the AWS Console username.
 For example, I'd like the aws user `johndoe` to only be able to do an `amplify push` on the environments called `johndoe`.
When I try to create an IAM policy for that, I can't find any action related to the push. 

What is the proper way to achieve that ?

![image](https://user-images.githubusercontent.com/6564357/93205795-b25f6380-f758-11ea-812e-f898d1883486.png)

**Comment by Athena96** [comment]
Hi @maximelebastard you should be able to achieve this using a "Condition" Statement in your IAM Policy:
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String

**Comment by maximelebastard** [comment]
Hi @Athena96, thanks. On which field should I add a condition ? Could you please provide a quick example of a such policy ?

**Comment by swaminator** [comment]
@maximelebastard can I understand a bit more about your scenario?
1. How many IAM users are you using?
2. Could you share how many Amplify backends you have? 
3. What are your build settings?

**Comment by maximelebastard** [comment]
Hi @swaminator, of course

1. How many IAM users are you using?
We are 3 users, but we plan to welcome a few more devs soon.

2. Could you share how many Amplify backends you have? 
We have three Amplify apps. Each developer has his own backend. We also have a production, an iso and a staging backend. And every PR preview has his own backend. 
So that makes between 6 and 12 backends per app, **18 to 36 backends in total.**

3. What are your build settings?

I'm not sure to understand that question, so I'll give some context. Sorry if it doesn't answer it.
We use most of the products: Hosting, GraphQL API, Auth, Functions and Storage

Our workflow is that each developer has his own backend where he can freely push things and develop new features.
When the feature is done, the developer creates a PR on Github. 
That PR triggers a PR Preview on Amplify and creates a temporary backend until the PR is closed.

When the PR is accepted, we merge it on our staging branch (deployed on the staging backend) and then on master branch  (master backend) which is replicated to our iso backend regularly.

The main need beneath my question is to secure our master backend (our production) from mistakes from a developer doing a `amplify env checkout master` for any reason and then pushing to it by mistake (which may lead to huge issues like data loss and an outage). 
Secondly, it would be safer for everyone in the team to know that whatever they do with the CLI, Amplify will never let him destroy anything outside his own environment.

The way I planned to achieve that is by enforcing that users cannot do a amplify push to an environment that isn't named as their user account.

**Comment by behrooziAWS** [comment]
We don't have a list of permissions or a managed policy that can help here at this time.  One thing you can do to reverse engineer the policy is to create a user with admin privileges and execute the amplify commands that you expect them to perform.  Then go to CloudTrail and filter by requests made by that user.  There is a 15-20 minute delay, so if you don't see the requests in cloudtrail immediately, wait a bit.  Using the apis invoked, create a policy for a second user.  Then test with the second user to make sure you can do the same action.  You can iterate using CloudTrail to help debug what requests were denied if it doesn't work.

**Comment by kperumal-bts** [comment]
Has there been any update on a managed policy to address this?
This seems to be a standard use case of any dev team.
