### ISSUE TITLE
One or more of the CNAMEs you provided are already associated with a different resource

### ISSUE THREAD

**Issue by aichnowski** [aws-amplify/amplify-console#1050]
**App Id**:
**Region**:
**Step**:
**Status**:

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
We encountered an issue creating a custom domain in the AWS amplify console. We ensured that the A record and CNAME record for the domain we are trying to create do not exist, as well as the CNAME record for the SSL certificate. When creating the custom domain, these records are all created successfully in Route53. We then get the below message each time we try to create the custom domain.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by swaminator** [comment]
Please review our troubleshooting guide: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
