### ISSUE TITLE
One of the connected branches suddenly stopped deploying the changes uploaded to github

### ISSUE THREAD

**Issue by servappgit** [aws-amplify/amplify-console#1051]
** Please describe which feature you have a question about? **
The frontend enviroment in which we deploy one of branches wasn't updating the changes we uploaded to github. 

** Provide additional details**
We got no errors, everything went smooth and we got green check boxes in the 4 stages (provision, build,deploy and verify). The github repository seems to be working fine, since we made sure that the changes were being uploaded correctly in the repository. The project works fine in local across all of our collaborators computers. We tried disconnecting the branch that is causing all of these issues and then plugin it again but now we get the following message: "Your app will appear here once you complete your first deployment.".... Any thoughts on what is causing this?

**Comment by Athena96** [comment]
Hi @servappgit can you please share you appId, region, and branch name.

**Comment by servappgit** [comment]
Hi Athena96,

heres the branch name: pre_produccion
Region:US-EAST-2
appid:arn:aws:amplify:us-east-2:305346604475:apps/d3le97war7ov3p

**Comment by Athena96** [comment]
Hi @servappgit thanks for the info. 
We've recently identified an issue related to what you described and have deployed a fix. Can you please try to build/deploy again and let us know if you're still facing the issue. Thanks!

**Comment by servappgit** [comment]
The issue has been resolved, thank you so much Athena96.

Have a good one !
