### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by prempal88niet** [aws-amplify/amplify-console#1052]
**App Id**: d2n9ovkj16exsm
**Region**: eu-west-2
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Athena96** [comment]
Hi @prempal88niet  you can find our docs for setting up custom domains here: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html

Please let us know if you are still facing issues, thanks!
