### ISSUE TITLE
Hanging up on SSL Configuration

### ISSUE THREAD

**Issue by sbaden** [aws-amplify/amplify-console#1055]
**App Id**: d36j8sy9a817hr
**Region**: us-west-1
**Step**: Domain Management
**Status**: SSL Configuration

**Issue/question**
I connected a react app from my github repo in Amplify.
I'm trying to connect my app with my custom domain that I registered in Route 53.
When I select my domain and start configuration the SSL Creation is successful but then it hangs up on SSL Configuration.

**Error message**
In order to verify domain ownership, configure the following CNAME record associated with your domain and verify that the CNAME record exists in your Domain Name Server (DNS) file.

It then displays info for the CNAME...

**Additional information**
When I look at the hosted zones section in Route 53 it shows that a record has been created for the CNAME.

![Screen Shot 2020-09-16 at 6 00 53 PM](https://user-images.githubusercontent.com/13071140/93407296-a94cc000-f846-11ea-91b0-3af9361520e6.png)

**Comment by ddspiff** [comment]
i am having this same issue im curious if you resolved it

**Comment by sbaden** [comment]
I haven't resolved the issue yet. After a few days the status changed to an error on the ssl configuration:  "Something went wrong. Please retry. Note: If retrying fails, please create an issue in our GitHub issue tracker." I've tried all week to get it to work without success.

**Comment by ddspiff** [comment]
ok i finally sat down and figure it out by following the steps in this article (https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#my-domain-hosted-with-amazon-route-53-is-stuck-in-the-pending-verification-state).  i deleted everything, created a hosted zone, changed the name servers for my registered domain to match the name servers from the hosted zone, and recreated the domain in the amplify console.  now im in business.  hope this helps!

**Comment by sbaden** [comment]
Thanks for the info @ddspiff ... I tried a few times and it finally worked.

**Comment by litwicki** [comment]
Please reopen this issue if you experience any further issues.
