### ISSUE TITLE
Setting Up Previews Fails Due To Private Github App

### ISSUE THREAD

**Issue by connor-minielly-north60** [aws-amplify/amplify-console#1056]
Hey there, this seems like the best spot I could find to submit this issue but I may still be barking up the wrong tree. In any case: I'm trying to add deploy previews to my production branch, which is deployed in ca-central-1. When I click the button in the console to install the github app I'm met with the message " AWS Amplify (ca-central-1) is a private GitHub App." and I'm not able to install in on the github repository. 

Not sure if this is a glitch on the console side, or if this is an error somewhere else in the AWS Amplify infrastructure, or even perhaps this feature isn't yet supported in ca-central-1 and it's simply not shown in the console?

Any help would be appreciated, thanks.

**Comment by Athena96** [comment]
Hi @connor-minielly-north60 I'm not able to repro this. Can you try signing out of your GitHub account and signing back in then try to setup Previews. I't possible your sign-in with github expired. Let us know if you continue to face the issue. Thanks!

**Comment by Athena96** [comment]
Resolving this issue, please feel free to re-open if you continue to face the issue. Thank you!
