### ISSUE TITLE
SSL configuration is Running - Unable to add subdomain 

### ISSUE THREAD

**Issue by djreddy316** [aws-amplify/amplify-console#1057]
**App Id**: dwui5g0031v6s
**Region**: ap-south-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
We are trying to assign a domain in the amplify . got struck at SSL configuration. tried all the docs but could not get a solution.

**Error message**
No Error message .. 

**Additional information**
We have added a subdomain successfully with same domain previously to another app in the amplify , but this time we are struck at SSL configuration. 
Please help

thanks

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by hsspain** [comment]
We are going to close this ticket.  Please let us know if you need further assistance.
