### ISSUE TITLE
Amplify deployed app giving 403

### ISSUE THREAD

**Issue by bishonbopanna** [aws-amplify/amplify-console#1058]
Getting 403 when accessing an app deployed through amplify console.

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>6AA95DB4D1B22951</RequestId>
<HostId>r23nQww4XWznAgV9MRYQM2305dafdsfadsfasdfacHgO3z1Bg98SGntCiqN6NG4p/Ogp1U=</HostId>
</Error>
```

Questions -
[1] Having added hosting service to the app, and pushing the changes from terminal using amplify push and amplify publish commands the app works _without_ issues. So are there any special permission to be given when the app is deployed through amplify console ? When accessing the web url, it gives a 302 and then a 403

[2] When app is deployed through amplify console where will the front end files be published ? Do not see any S3 bucket for the same.

[3] Where can i see the logs for the application ?

**Comment by Athena96** [comment]
Hi @bishonbopanna thanks for reaching out
1. can you please share your appId and any repro steps so re can try to repro the issue. 
2. our service manages the hosting, so the hosing resources won't be in your account.
3. you can view the access logs for your application by going to the Amplify Console then Your App / App settings / Access logs

**Comment by bishonbopanna** [comment]
thank you @Athena96 for the response, please find the response below 

1. appId : d11c3secxgd3oa
2. Steps to reproduce

  - Add hosting with Manual deployment (same problem when tried directly on the amplify console, with direct connection on the branch and custom domain name)

`~/source/wf » amplify add hosting                                                                                                                                     
? Select the plugin module to execute Hosting with Amplify Console (Managed hosting with custom domains, Continuous deployment)
? Choose a type Manual deployment

You can now publish your app using the following command:

Command: amplify publish`

- then access the app in the provided url - https://devuseasto.d11c3secxgd3oa.amplifyapp.com (this loads), click on any other link like "About" or "Login" you will see the Access Denied error.

3. Comment/Request on "our service manages the hosting, so the hosting resources won't be in your account", this makes it very difficult to see what has truly been deployed and takes away the ability for the app owners to check/modify individual files directly like you could when it is on S3 bucket - Please add a product request to make this to be uploaded to a S3 ( i do know there is a manual mode where you could, which is what i have tried and in the manual mode too the uploaded files are not in user's account)

4. Thanks for the access logs - does not give much except the "access" info, is there anyway to get in depth/debug level logs for the failures in the app ?

**Comment by bishonbopanna** [comment]
@Athena96 @swaminator any one from @aws-amplify-ops team, can you please respond ?

**Comment by Liguo-Ma** [comment]
Hi @bishonbopanna 
Did you find a solution?
I get the same error too.

**Comment by Liguo-Ma** [comment]
My app worked well 1 month ago.
But the environment was damaged.
So I set again.
After that, I get this error.
My site URL is https://prod.d3kb4db9ojlfvl.amplifyapp.com/
I cannot redirect the signin page. or any subdomain .
https://user-images.githubusercontent.com/59509767/93915886-e0cdd780-fd32-11ea-9136-9121c2a38681.png
I get like this error.
I think this is amplify version issue.

**Comment by finnhvman** [comment]
> My app worked well 1 month ago.
> But the environment was damaged.
> So I set again.
> After that, I get this error.
> My site URL is https://prod.d3kb4db9ojlfvl.amplifyapp.com/
> I cannot redirect the signin page. or any subdomain .
> https://user-images.githubusercontent.com/59509767/93915886-e0cdd780-fd32-11ea-9136-9121c2a38681.png
> I get like this error.
> I think this is amplify version issue.

We are having very similar issues since yesterday

**Comment by aaroncampos** [comment]
I am having a similar issue starting this morning with a new deploy of a Gatsby project that has been working fine up until this morning.

**Comment by bishonbopanna** [comment]
: ) well having waited for some time from amplify team to respond - which did _not_ happen till now, so the work around I took is as follows and also for these reasons 

- A : This issue, ofcourse
- B : with amplify hosting, the files are _not_ hosted in your account and hence there is no access to them. However the benefits are that with amplify hosting you would be able to connect to a repo+branch and get CI/CD and also you could do manual where you point to a zip. Read here : https://docs.amplify.aws/cli/hosting. But not having visibility to actual files that are served up for the front end of the app seems not very apt imo and hence the below.

So here is the alternative : S3AndCloudFront - PROD (S3 with CloudFront using HTTPS)
Steps:
1. Add S3AndCloudFront hosting from command line

`~/wf » amplify hosting add                                                                                                                                           

? Select the plugin module to execute Amazon CloudFront and S3
? Select the environment setup: PROD (S3 with CloudFront using HTTPS)
? hosting bucket name wildflower
Static webhosting is disabled for the hosting bucket when CloudFront Distribution is enabled.

You can now publish your app using the following command:
Command: amplify publish
`





-

**Comment by swaminator** [comment]
@bishonbopanna @aaroncampos @finnhvman  do you have a code sample that we can us to reprouce the 403?

**Comment by bishonbopanna** [comment]
@swaminator - yes, can it be emailed ?

**Comment by swaminator** [comment]
Yes. Please email aws-amplify-customer@amazon.com

**Comment by finnhvman** [comment]
> @bishonbopanna @aaroncampos @finnhvman do you have a code sample that we can us to reprouce the 403?

1. Take any SPA with dynamic routing enabled, for example a demo react app with react router.
2. Set the redirection rule below
```
[
   {
        "source": "/<*>",
        "target": "/index.html",
        "status": "404-200",
        "condition": null
    }
]
```
3. Open a new tab in your browser
4. Go to any non-root url, for example: `/example-folder`

This should produce the 403 error

**Comment by Liguo-Ma** [comment]
This is the exact rule we added

[
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]

**Comment by ganipcanot** [comment]
Are you doing a manual deployment via the console?  Have you checked [this documentation](https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html).

Specifically: `When you create the zip folder, make sure you zip the contents of your build output and not the top level folder. For example, if your build output generates a folder named “build” or “public”, first navigate into that folder, select all of the contents, and zip it from there. If you do not do this, you will see an “Access Denied” error because the site's root directory will not be initialized properly.`

**Comment by juanlucky** [comment]
hi there, I tried to publish a simple default Vue.js Hello World following the Amplify Vue.js tutorial (https://docs.amplify.aws/start/getting-started/hosting/q/integration/vue#add-hosting-to-your-app) and it fails at the last publishing step with this teminal output : 
Zipping artifacts completed.
× Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.  
An error occurred during the publish operation

Before trying to manually deploy the hosting service with Amplify CLI, I tried to connect via the Amplify Console the frontend with my Github dev branch for an automatic publishing workflow. After a successfull generation, I encounter the "permission denied" error reported in issue  #1058 
`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>A36D5FDCC407FA82</RequestId>
<HostId>uPMmy/cakASO4FS9JzO9+SP6ViK/Fs//Dv2drRB1DLuf2o7N2U7VauqmRYmz2FurL2zyWlVaMW8=</HostId>
</Error>`
I also tried to add the rewriting rules Linguo-Ma mentioned in the closed #5375 ticket but it doesn't help.

So I'm blocked with the both publishing procedure. 
Any help would be apreciated

**Comment by juanlucky** [comment]
hi again, I complete my previous post with new tests.
I created a completly new test webapp with simple default Vue.js Hello World following the Amplify Vue.js tutorial (without API, Auth).
I added a manual deployment hosting service ((https://docs.amplify.aws/start/getting-started/hosting/q/integration/vue#add-hosting-to-your-app) and in this case it worked fine and I could access to the deployed webapp without errors !
So this manual procedure is at least working from scratch, i.e when you do NOT target a frontend originally created by connecting a gitHub branch.

This ticket #1058 has a workaround but **should still be corrected** as it gives a bad first impression "at the end" which masks all the brilliant work done behind the scene by the AWS amplify team !
The promise to have a "working" automatic deployment with github branches connection is just fantastic

**Comment by juanlucky** [comment]
I found the origin of my "access denied" error...
My webapp is located in a root directory /xxx of my Git Repo so I'm in the case called "[Monorepo](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#monorepo-configuration)" in the Amplify documentation.
It is a little bit confusing (at least for me!) to work with the amplify CLI in the /xxx directory of my repo (running init, push add xxx cmds) and, for the hosting feature, generate it with an "amplify add hosting" executed within this /xxx directory, be redirected to the Amplify Console which do not target automatically the /xxx directory when connecting the repo. Maybe the terms "Monorepo" is not clear enough.
Anyway, it was completly an error from my side but I wanted to share it as it could help someone

**Comment by ganipcanot** [comment]
Closing for now please re-open if you are still experiencing issues.

**Comment by rmuellerjr** [comment]
FYI - I did notice a difference between setup through the console for backend/hosting, vs set up via CLI (amplify hosting add) for giving this 403 error. The CLI route had me switch to the console where I had to add a service role and several other steps. Did I skip these other steps with the initial Console setup? I don't know but somewhere it made the difference. After I get this project stood up, I'll try to test some more to provide guidance on either difference in implementation or critical steps that people may be missing.

**Comment by loafofpiecrust** [comment]
I created an Amplify app using solely Cloudformation, copying exactly the setup given in the [Amplify blog post announcing CloudFormation support](https://aws.amazon.com/blogs/mobile/deploy-a-vuejs-app-with-aws-amplify-console-using-cloudformation/). When I go to my site deployment, the index page works fine but the rest return 403 errors. I'm not using the Amplify CLI at all and don't plan to, as I want all deployments totally stateless through `serverless`. Is there anything I can do to fix or work around this?

**Comment by miguelaeh** [comment]
Hi guys,
Just in case it helps someone, I experienced the same issue and I solved it by setting the `homepage` at the  `package.json` to an empty string instead of my domain.
Setting a different `homepage` always shows a `403` error using the domain generated by Amplify. I guess because the expected domain is no the one where the application is running.

**Comment by zaefrul** [comment]
> Hi guys, Just in case it helps someone, I experienced the same issue and I solved it by setting the `homepage` at the `package.json` to an empty string instead of my domain. Setting a different `homepage` always shows a `403` error using the domain generated by Amplify. I guess because the expected domain is no the one where the application is running.

This one helps my problem!
