### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by mmomasters** [aws-amplify/amplify-console#1059]
**App Id**: d1x8cl62ighple
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Cannot add domain to amplify app (domain is available in route53)

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by niknokseyer** [comment]
Were you able to get yours resolved @abhi7cr?

**Comment by mmomasters** [comment]
Yes I had to contact AWS support for them to MANUALLY fix the issue
