### ISSUE TITLE
Domain Activation

### ISSUE THREAD

**Issue by developer0116** [aws-amplify/amplify-console#1062]
When I set up domain in Amplify, an error occurred like below.

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

I'd like you to mention which CNAME is conflicted.

Best

**Comment by swaminator** [comment]
Please review our troubleshooting guide: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
