### ISSUE TITLE
Build fails before it starts

### ISSUE THREAD

**Issue by olivoil** [aws-amplify/amplify-console#1065]
** Please describe which feature you have a question about? **

I'm trying to deploy an amplify app connected to a CodeCommit repository.
The provision phase clears, but the build phase fails before it starts, with no logs at all.

<img width="1723" alt="image" src="https://user-images.githubusercontent.com/264142/93797551-ff808100-fc01-11ea-93be-8c6194a88b43.png">

What could this be caused by? With no visible log output, how do I go about debugging and fixing it?

**Comment by garyleefight** [comment]
Looking

**Comment by Athena96** [comment]
closing, feel free to re-open if you are still facing this issue, thank you!
