### ISSUE TITLE
Builds are stalling - app cannot be updated

### ISSUE THREAD

**Issue by nhc-motosumo** [aws-amplify/amplify-console#1068]
We are unable to update our Amplify app.

Since yesterday, Amplify stopped building the branches properly. First, several branches would wait indefinitely in the "Verify" or "Deploy" phases, although the code would actually go live. Now our `master` branch and two other branches are stuck in "Provisioning" and no builds seem to be ongoing.

appId: d24qhuy0hwyih6
region: eu-west-1

**Comment by lettertwo** [comment]
We're seeing the same thing, and so are a number of others, check out https://github.com/aws-amplify/amplify-console/issues/115 (especially the most recent comments).

**Comment by swaminator** [comment]
@nhc-motosumo @lettertwo are both of you running tests?

**Comment by mads79** [comment]
Yes, we (colleague of @nhc-motosumo here) are running tests.
The major difference from https://github.com/aws-amplify/amplify-console/issues/115 is that it's not necessarily failing during deploy , it's now also failing after provision.

**Comment by nhc-motosumo** [comment]
Update: This seems closely related to #115 

I removed some of the branches that were stuck in "Deploy", and then I was able to "Redeploy" my main branch, which had been stuck in "Provision". My theory is that the branches stuck in "Deploy" are counted towards an account-wide maximum of 6 concurrent builds, so I freed up a slot by removing one.

The new build also got stuck in "Deploy", but it did get past "Provision" this time.

**Comment by kahdojay** [comment]
@nhc-motosumo @mads79 can you point me to the branch name and recent build number for d24qhuy0hwyih6 in eu-west-1 that is experiencing this behavior? I want to check whether it's affected by the same as recent comments in #115

@lettertwo please send the same details so I can check

**Comment by nhc-motosumo** [comment]
@kahdojay :

`develop` build 76 got stuck in "Provision", and so did `master` build 24.

`master` build 25 (made after I deleted some branches) got stuck in "Deploy". It did roll out the update, though, before getting stuck.

Hope that helps? Let me know if you need more details!

**Comment by lettertwo** [comment]
@kahdojay sorry for the delay, here are the details:

appId: d1nztlv1li5zxf
region: us-east-1

We are seeing all recent builds stall at the Deploy phase

**Comment by kahdojay** [comment]
@lettertwo it looks like your failures in us-east-1 were due to an unrelated reason to 115, but we've pushed a fix, can you give it another try and let us know if you're still setting the same behavior?

**Comment by kahdojay** [comment]
@nhc-motosumo it looks like your issue is the same as 115, can you give it another try in eu-west-1? 

Also let me know if you're still setting the stuck in provisioning issue after deleting the stuck branches, or if you need assistance there.

**Comment by talebbits** [comment]
@kahdojay I am working with @lettertwo 

We are getting this now
```
2020-09-23T18:34:53 [ERROR]: Caught error downloading artifacts
2020-09-23T18:34:53 [ERROR]: Deployment terminated unsuccessfully
```

**Comment by kahdojay** [comment]
@talebbits @lettertwo ok thanks for letting us know, we'll investigate a fix for this today

**Comment by nhc-motosumo** [comment]
Thanks for the fix @kahdojay !

Yes, we got out of the provisioning troubles by disconnecting branches with stalled builds. And your update seems to have made the builds complete again, so we are up and running.

One concern left: On my `develop` branch, build 73 is still marked as "Running", and cancelling it does nothing. Might this somehow come back to haunt us later (e.g. counted as one of our concurrent builds)? And is there a way for us to kill it without disconnecting that branch (which might be problematic)?

Thanks again - really appreciate your efforts!

**Comment by kahdojay** [comment]
@nhc-motosumo great to hear it! We made sure it doesn't count against your concurrent build limit, does it still show as running?

**Comment by nhc-motosumo** [comment]
Build 73 is now listed as "Cancelled". Thanks!

**Comment by Erlpil** [comment]
I also have this issue deploying the master branch in eu-north-1.

During the deploy phase:
`2020-09-25T09:03:05 [INFO]: Beginning deployment for application <appid>, branch:master, buildId 0000000028
2020-09-25T09:03:05 [INFO]: Got archive: 507204 bytes
2020-09-25T09:03:05 [INFO]: Archive unzipped: 18 files
2020-09-25T09:03:08 [ERROR]: Deployment terminated unsuccessfully`

Tried to cancel the build and redeploy. Same result

**Comment by kdorland** [comment]
I have the exact same error. Redeploy doesn't fix it. It gets stuck on Deploy.

**Comment by Erlpil** [comment]
I was able to deploy and redeploy the app in eu-central-1.
eu-north 1 is still unable to redeploy.

**Comment by tobiaslindulf** [comment]
I have the exact same error in region **eu-north-1**. Not able to deploy anything, just getting the following logs every time:
2020-09-25T09:54:03 [INFO]: Beginning deployment for application AppID, branch:master, buildId 0000000008
2020-09-25T09:54:03 [INFO]: Got archive: 4437068 bytes
2020-09-25T09:54:03 [INFO]: Archive unzipped: 70 files
2020-09-25T09:54:07 [ERROR]: Deployment terminated unsuccessfully

Then it just stalls.

**Comment by kahdojay** [comment]
@Erlpil @kdorland @tobiaslindulf can you provide your appid for the eu-north-1 app impacted? let us know about others as well. If you prefer you can email it to aws-amplify-customer@amazon.com.

**Comment by Erlpil** [comment]
@kahdojay Email sent 👍

**Comment by Erlpil** [comment]
@kahdojay For info, I was now able to redeploy the previously failed version the app in eu-north-1

**Comment by tobiaslindulf** [comment]
@kahdojay Email sent now. 
However, when I tested to deploy today in region eu-north-1 it worked, for several different apps.
Have you deployed a new version of Amplify in Sweden or have you done any other change during the weekend?

**Comment by kdorland** [comment]
@kahdojay It works again here as well.

**Comment by nhc-motosumo** [comment]
This problem has reappeared for us.

App id: dm197t2mo7xbv
Region: eu-west-1

Both `master` and `develop` seem to get stuck in "Deploy". Cancel button does not seem to react for minutes. Redeploying does not help. Pushing a new commit does not help.

**Comment by kahdojay** [comment]
@nhc-motosumo apologies for the delay here. I see your `master` and `develop` branches have recent job successes. Can you let us know if you're still seeing issues with your jobs?

**Comment by nhc-motosumo** [comment]
Builds are running at this time, but when we saw the issue, it stopped our development flow for 1-2 workdays.

Is there any hope that the UI will start providing reliable insights and controls into the components behind these breakdowns? We have an ongoing concern on whether Amplify is mature enough for our production systems because of this.

**Comment by kahdojay** [comment]
@nhc-motosumo absolutely, we have made some major changes in the last few months to our build/deploy architecture which have fixed a lot of the underlying issue we saw last year. We will continue our planned work to make build failures less frequent and more transparent so that you're not totally dependent on reaching out on GitHub. That being said, we'll keep doing our best to provide support whether via these issue threads or through AWS Support channels. 

Closing this issue for now, please feel free to re-open or open a new one.
