### ISSUE TITLE
Private submodule cloning with known public key

### ISSUE THREAD

**Issue by dougleville** [aws-amplify/amplify-console#1069]
** Please describe which feature you have a question about? **
First - I have already read topic #150 , I was able to get the build working using the private key -> environment variable method. I have a different question.

Bitbucket allows me to see the actual public key added to the access keys AWS Amplify for the main repository. I added said public key to the submodule repository's access keys and would have expected the build to work. 

** Provide additional details**
This is the access key configuration I'm talking about in Bitbucket:

![image](https://user-images.githubusercontent.com/30697943/93888932-3c09b680-fcae-11ea-83ed-1cd54a53c865.png)

After adding the auto-generated public key from the parent repo to the submodule repo, we still fail to authenticate:
`Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.`

**Comment by litwicki** [comment]
@dougleville are you still experiencing any issues here?

**Comment by dougleville** [comment]
> @dougleville are you still experiencing any issues here?

@litwicki I was never able to get this working so I fell back to the environment variable approach. Is this something that you'd expect to work in principle? If so I can go back and try it again.

**Comment by litwicki** [comment]
@dougleville no this would not be expected to work, so let's consider this closed and if you experience any similar issues please reopen

**Comment by dougleville** [comment]
@litwicki OK sure - with #150 closed, is there any guidance on how to clone private submodules with Amplify without adding encoded ssh keys as environment variables?
