### ISSUE TITLE
AccessDenied error appeared after deploy amplify project

### ISSUE THREAD

**Issue by Liguo-Ma** [aws-amplify/amplify-console#1073]
I am using the latest version amplify
Also, I have uploaded my amplify project.
https://prod.d3kb4db9ojlfvl.amplifyapp.com/
This is my site.
It works file and redirect to the signing page.
https://prod.d3kb4db9ojlfvl.amplifyapp.com/signin/
So this site works well.
But If I redirect this site so if I click F5 I get the "AccessDenied" error.
What is the solution for this error?

**Comment by finnhvman** [comment]
We had the same issue for one project yesterday, and for another project today

**Comment by Liguo-Ma** [comment]
So did you find solution?

**Comment by finnhvman** [comment]
We replaced the Rewrites and redirects

from `/<*>` 404 Rewrite

to this
https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa

**Comment by Liguo-Ma** [comment]
So it helped your issue?

**Comment by Liguo-Ma** [comment]
Could you let me know correctly what rule you added?

**Comment by Liguo-Ma** [comment]
If fact my program worked good in 1 month ago

**Comment by finnhvman** [comment]
Our deployment worked for years well with the 404 Rewrite

This is the exact rule we added

```
[
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]
```

**Comment by Liguo-Ma** [comment]
Oh perfect
Thanks  @finnhvman 
.

**Comment by adam-nygate** [comment]
It looks like the 404 Rewrite is broken. We were using for the 404 Rewrite for an alternate way to do SPA fallback (hybrid pre-rendered and SPA for different routes), but it looks like in a recent Amplify update, this has stopped working - 404 Redirect and 200 Rewrite are still working.

**Comment by aaroncampos** [comment]
I'm still having this problem and I've added the rule shown here:
https://github.com/aws-amplify/amplify-console/issues/1073#issuecomment-697174032

And it doesn't seem like any combination of 404 rewrite or redirect solves it.  Anyone else having any luck?  Perhaps, specifically with Gatsby sites?

**Comment by aaroncampos** [comment]
@finnhvman Have you applied any other change than the one listed above to get your apps back working again?  Thanks!

**Comment by finnhvman** [comment]
> @finnhvman Have you applied any other change than the one listed above to get your apps back working again? Thanks!

no other changes, but this will only work if you don't have any other static routes than index.html

**Comment by FelixRe0** [comment]
+1 

Using </^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/> 200 rewrite braks partially static generated SPA pages.

Until this is resolved we added for every page that should be served statically in addition to the redirect above a hard coded 200 redirect.
i.e.
 /  => /index.html  [200]
 /login/  => /login/index.html  [200]
</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/> [200]

_Note that trailing slashes are needed, the file location must be right and they should be above the regex rewrite._

[related](https://github.com/aws-amplify/amplify-console/issues/70#issuecomment-697405021)

**Comment by ganipcanot** [comment]
@Liguo-Ma could you share your `appId` and `region` please?  Also we had a fix for 404 re-writes that is deploying now but should be live in `eu-west-2` and `us-east-2` if you wanted to give it a try in one of those regions.
