### ISSUE TITLE
SSL configuration is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by yoshi-star** [aws-amplify/amplify-console#1074]
**App Id**: d1r2dfscbsxb7m
**Region**: ap-northeast-1
**Step**: SSL configuration
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by swaminator** [comment]
CLosing.. need more info.
