### ISSUE TITLE
Add ability to setup redirects from within an Amplify project

### ISSUE THREAD

**Issue by xavierraffin** [aws-amplify/amplify-console#1076]
**Is your feature request related to a problem? Please describe.**

AWS Amplify framework offers a clean way to store all the frontend and backend settings and code in one place: the git repo of a project.
**Deploying the project with the AWS Amplify console should not break that pattern.**
When a project requires redirects this redirect cannot be defined from within the project but only added manually (or declared in CloudFormation using a distinct source code repository).
This is a pain when working with multiple environment and team (with many Amplify env) because everyone needs to manually add the redirect and edit the redirect when there is a change.

**Describe the solution you'd like**

I like to have a file somewhere in an AWS Amplify project that the Amplify Console read to setup redirect rules.

**Additional context**

This is a bit sad, because when you deploy with the AWS Amplify CLI to a hosting S3AndCloudfront you don't have the problem. You can declare your redirections in the behavior of the Cloudfront distribution in the hosting CloudFormation files.
Since AWS AMplify console do not use hosting S3AndCloudfront definition, these settings are lost.

**Comment by swaminator** [comment]
@xavierraffin this is on our roadmap to support this year. Please track #18. Closing this as a dupe.
