### ISSUE TITLE
Define static headers on an App

### ISSUE THREAD

**Issue by xavierraffin** [aws-amplify/amplify-console#1078]
**Is your feature request related to a problem? Please describe.**

Today it is not possible to inject HTTP headers on an App deployed by the AWS Amplify console.
This is a problem because the Security best practices recommend to define several of them appropriately:

* Strict-Transport-Security
* Content-Security-policy
* X-Frame-Options
* X-XSS-Protection
* X-Content-Type-Options

_see [reference](https://infosec.mozilla.org/guidelines/web_security#HTTP_Strict_Transport_Security)_

Because of the missing headers [Modzilla Observatory](https://observatory.mozilla.org) is giving my [Amplify hosted project](https://master.dw8p5s05jola3.amplifyapp.com/) a F

**Describe the solution you'd like**

It would be nice to be able to define static headers on an App for an AWS Amplify Console app.

**Additional context**

On an Amplify project hosted by S3andCloudfront injecting the header is possible using Lambda@Edge

**Comment by kahdojay** [comment]
@xavierraffin if you're using Amplify Console to deploy a ci/cd app, you can set custom headers:
https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html

If you're using the Amplify CLI, you'll need to choose Amplify Console and ci/cd app as the hosting option: https://aws.amazon.com/blogs/aws/host-your-apps-with-aws-amplify-console-from-the-aws-amplify-cli/

We'll be adding support for custom headers for manual deploy apps soon, you can track that in #777 

Please let us know if this doesn't work for you or you have any questions or concerns.
