### ISSUE TITLE
query parameters are removed in url

### ISSUE THREAD

**Issue by developer0116** [aws-amplify/amplify-console#1079]
I set up the "Rewrites and redirects" settings like this.
Source address:  /<*>
Target address:   /index.html
Type:                   404 (Redirect)

But the query parameters are removed when the url is navigated.

So I updated the setting like this.
Source address:  /<*>
Target address:   /index.html
Type:                   404 (Rewrite)

the query parameters are not removed, but when refresh the page, it directs to index.html page automatically.

I am not sure how to fix this issue.

Thanks

Best

**Comment by kahdojay** [comment]
Hi again, this is a known issue with our redirects, please track the status here #97
