### ISSUE TITLE
Next.js page not overwritten by file in public/

### ISSUE THREAD

**Issue by adrian-kriegel** [aws-amplify/amplify-console#1080]
We replaced a file that was served through `pages/mypage.js` with a file that is served through `public/mypage`. According to [this thread](https://github.com/aws-amplify/amplify-console/issues/615), artifacts from the last 6 builds are restored on build unless specifically overwritten. When deploying the app, the old file `pages/mypage.js` is therefore still served instead of `public/mypage` because the new file does not overwrite the old one before the build. I think this is a bug, as the new file certainly overwrites the old file after the build as they use the same url.

**Comment by kahdojay** [comment]
Hi @adrian-kriegel can you provide region, appId, branchname, and example build number?

Also if you can provide a code sample with steps to repro it will help us investigate.

**Comment by swaminator** [comment]
@adrian-kriegel we have reverted the behavior of storing the last 6 builds based on a lot of complaints. This should work for you now.
