### ISSUE TITLE
AWS Amplify Console Silently Fails - Won't properly detect the selected monorepo folder,  Reconnect Repository, build failing.

### ISSUE THREAD

**Issue by superjose** [aws-amplify/amplify-console#1083]
**App Id**:
**us-east-2**:

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**

First of all, thank you very much for supporting Monorepos in Amplify 🤗. It's a very big deal, as we're able to optimize our applications in the best manner possible. 

I've been trying to deploy a monorepo application (2 separate create-react-app) using the amplify console via GitHub webhooks, and it's been awful. After 8 hours of constant back and forth, tweaking and drilling GitHub I was finally able to deploy both apps with success. 

The problem seems to lie in the amplify.yml. The file **must be** correctly formatted, otherwise, it will fail and it will display errors unrelated to it.

Some errors are:
- Reconnect repository issue (I spent hours thinking it was that problem and it wasn't).
- Not properly providing the repository (getting stuck in Provision - 1st stage).
- Not finding the folder inside the repository after specifying it in the connecting repository wizard (when you're creating a new app, you would write the proper folder name, but it would switch back to another one. This happens when your YAML file is valid but not properly indented).

 Improperly formatted examples:
- Not properly indenting the artifacts key (having it aligned with the phases one).
- Not including a supported key such as `frontend` or `backend`.

It would be best if Amplify could run a linter or an analyzer to check for amplify.yml and its invalid properties.

**Comment by swaminator** [comment]
@superjose thank you for your feedback. Sorry to hear about all the issues you're having with monorepos. We will work to make this better but need some input on you on how to action. Would you be willing to chat sometime? We are on Discord: https://discord.gg/Px5YVfQ and you find me with the same alias.

**Comment by superjose** [comment]
Absolutely!! I'll join the channel!

**Comment by swaminator** [comment]
@superjose please email aws-amplify-customer@amazon.com and I'll set up some time to chat.

**Comment by litwicki** [comment]
@superjose are you still experiencing any issues?

**Comment by ganipcanot** [comment]
Closing due to age - if you are still experiencing issues please feel free to re-open.
