### ISSUE TITLE
SSL configuration is Failed

### ISSUE THREAD

**Issue by sbaden** [aws-amplify/amplify-console#1086]
**App Id**: d36j8sy9a817hr
**Region**: us-west-1
**Step**: SSL configuration
**Status**: Failed

**Issue/question**
I've tried for two weeks now to get my amplify app linked to my domain and it keeps failing in the SSL Configuration. As far as I can tell I have the DNS and CNAME all set up correctly.

**Error message**
Something went wrong. Please retry.
Note: If retrying fails, please create an issue in our GitHub issue tracker.

**Comment by rajibganguly** [comment]
My custom domain name is https://w3earth.com which purchased from godaddy. When I typed w3earth in the URL it redirected to my amplify app, which is expected but I want to keep url as w3earth

**Comment by litwicki** [comment]
@rajibganguly If your domain is validated correctly, can you elaborate on what you believe is not working correctly?

**Comment by hsspain** [comment]
We are going to close this ticket.  Feel free to re-open this if you are still having issues and we will do what we can to help.
