### ISSUE TITLE
Domain activation is Failed - One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by niknokseyer** [aws-amplify/amplify-console#1089]
**App Id**: d16pigd2lbpnkk
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.
Just trying to verify the domain I set. Previously using a subdomain, I deleted it but still failing.

**Error message**
If there is an error message, please include it here. 
One or more of the CNAMEs you provided are already associated with a different resource.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by niknokseyer** [comment]
@nimacks any info on how to get this resolved?

**Comment by litwicki** [comment]
This error results when your CNAME is associated to another resource. Please check your Route53 hosted zones/records in any regions you have resources and verify that CNAME is not in use anywhere else.

**Comment by gwryssekk** [comment]
Closing for now as pending > 14 days. Please reopen if you are still experiencing this issue.
