### ISSUE TITLE
Domain activation is Failed - Retry Does not work

### ISSUE THREAD

**Issue by Vaaljan** [aws-amplify/amplify-console#1095]
**App Id**: d1y72dxyvas797
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Retry does not seem to work at all. If you click on Retry, it says retry in progress but it just fails afterwards.  So Now I need to remove the domain add it back again which changes the cloudfront url so then we have to update the cname again and if that takes to0 long then it fails again and we are back at square one. 

The ssl configuration had the same issue, Retry did not work, and it failed before we could add the cname record. 

So Now I have to remove the domain readd it and then the domain management needs to hopefully add the record in time before it fails again, Which is silly to be honest. 

Why does retry not work?

**Error message**
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem.

**Additional information**
View DNS Records is also disabled, So you cannot even see where to point the dns records to. Luckily I viewed the records before it failed so I think I know where it should point to. 
<img width="397" alt="Screenshot 2020-09-28 at 11 00 13" src="https://user-images.githubusercontent.com/15228175/94412484-20088800-017a-11eb-9976-7b31c84655eb.png">

Current Error
<img width="919" alt="Screenshot 2020-09-28 at 11 03 01" src="https://user-images.githubusercontent.com/15228175/94412606-43cbce00-017a-11eb-89f4-bb3336188c0a.png">
 Then You click retry
<img width="836" alt="Screenshot 2020-09-28 at 11 03 12" src="https://user-images.githubusercontent.com/15228175/94412954-b9d03500-017a-11eb-8d7a-3461df1d2261.png">

If you refresh the page then its back to the first screen where it says failed.

**Comment by garyleework** [comment]
Thanks for the report. We are investigating this issue

**Comment by Nxtra** [comment]
This happens when the previously configured CNAMEs are still active DNS records at your DNS provider.
You first need to delete the ACM CNAME record (the one that validates ownership) and the CNAME pointing towards your CloudFront distribution. Delete them at your DNS provider.

Then delete the domain in Amplify.
Next do again "Add Domain" and wait for the new CNAMEs to appear. 
Add the new CNAMEs add your DNS provider.

**Comment by Vaaljan** [comment]
@Nxtra I know why it happens. My problem is that it has a Retry button which should work or not be there at all. 

If you do not manage the dns yourself, its quite hard to get the cnames to point before the check fails and you have to start over again. 

If it failed and told you, delete and reconfigure the domain then great. But why but a retry button that does nothing?

**Comment by litwicki** [comment]
@Vaaljan Thanks for your insight; I agree that follow-up behavior is a bug that we'll work on fixing. Regarding the actual domain validation issue, are there any issues or are you all set now?

**Comment by heinrich-fresh** [comment]
@litwicki  Yes We sorted out the domain validation.  Thanks.

**Comment by shealan** [comment]
Connecting a domain name from a third-party DNS service is a terrible experience. After a LOT of trial and error we found the trick is to add the CNAMEs for the subdomains before you add the CNAME for the SSL validation. Click the "Actions" > "View DNS" to see them. Once they are added, you can add the SSL validation CNAME pair. That means everything is there before the final activation step, preventing the error.

I hope this tip helps someone else out there.

Crazy that something like this on a key AWS product needs a "trick", but here we find ourselves...
