### ISSUE TITLE
The deployed app is getting get blank white screen

### ISSUE THREAD

**Issue by anubnair** [aws-amplify/amplify-console#1096]
**Issue/question**
I have deployed my application and sometimes, after deployment I get blank screen. It happens sometimes after few days

**Comment by garyleework** [comment]
Can you give us the app arn and region? You can find it in the 'general' tab

**Comment by anubnair** [comment]
I found that it happens with "unhandled promise"

**Comment by nathanqueija** [comment]
I have the same issue here. Any workarounds?
