### ISSUE TITLE
Domain activation is Failed - Unable to point Amplify app to CloudFront

### ISSUE THREAD

**Issue by wenruiliau** [aws-amplify/amplify-console#1097]
**App Id**: d1cl1xglyjns4k
**Region**: ap-southeast-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
We are using CloudFront as our DNS provider. Initially, we tried to add our custom domain to Amplify (without the root domain) using this guide. https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-a-third-party-dns-provider.html

However, we were unable to get past the "Domain Activation" stage, the application could not get past that stage even after we added the DNS records specified (it was perpetually verifying Domain Activation).

After deleting the subdomain and trying again, we are now encountering the "Domain Activation" failed error message. We have another CNAME record that is pointing to a subdomain that is a Elastic beanstalk load-balancer if that helps. 
**Error message**
One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by litwicki** [comment]
@wenruiliau are you still experiencing any issues?

**Comment by wenruiliau** [comment]
Hi, 

We're still experiencing issues and in the interim, used netlify for our project needs. Will love to get this resolved so we can get back on AWS.

**Comment by litwicki** [comment]
@wenruiliau that error indicates the CNAME is already in use by another resource. For the domain to work on Amplify will need that CNAME record.

**Comment by ganipcanot** [comment]
Closing due to age - if you are still experiencing issues please feel free to re-open.
