### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by eduardoIST** [aws-amplify/amplify-console#1098]
**App Id**: d104907tkhn9nj
**Region**: us-east-2
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by litwicki** [comment]
If you continue to experience this issue, please reopen with the appropriate information.
