### ISSUE TITLE
custom domain is added with the cname record. domain is not activated

### ISSUE THREAD

**Issue by anubnair** [aws-amplify/amplify-console#1099]
**Region**: Singapore

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I have an application hosted with amplify. I need to add a custom domain. The custom domain I wanted is a subdomain, I added the subdomain to Route 53 "hosted zone". (note: I added the only subdomain to route 53) Then I went to amplify settings and the added hosted zone was available. Now the status is showing as "SSL configuration".  In order to verify domain ownership, I configure the CNAME record associated with the domain as well. That should verify the ownership. But it's not going further. Kinda stuck in "SSL configuration".

Anything wrong with what I am doing?

**Comment by bwinkers** [comment]
Checking here many of us are stuck
https://github.com/aws-amplify/amplify-console/issues
