### ISSUE TITLE
AWS-Amplify Failed at Deploy stage

### ISSUE THREAD

**Issue by syion-sayne** [aws-amplify/amplify-console#1100]
Good day AWS.

I'm trying to deploy our app in amplify, but it always fail at deploy stage, with no error.

![image](https://user-images.githubusercontent.com/26127793/94759674-1fb6f980-03d3-11eb-9590-ebd37c960ec0.png)

APP ARN: arn:aws:amplify:ap-southeast-1:XXXXXXXXXXXX:apps/dgh3g9t0tybkk

**Comment by garyleework** [comment]
Thanks for the report. We are currently looking for your issue

**Comment by syion-sayne** [comment]
hi @garyleework , we remove the amplify and tried to create another one hoping it will fix the issue., but still it failed. here's the arn:

arn:aws:amplify:ap-southeast-1:xxxxxxxxxxxx:apps/d3ipadc1vdghx1

**Comment by garyleework** [comment]
@syion-sayne Hi, I did some investigation yesterday. Looks like this is caused by network issue. Did you ever have a successful deploy for you repository?
