### ISSUE TITLE
Changing GitHub account

### ISSUE THREAD

**Issue by skoch** [aws-amplify/amplify-console#1101]
**Please describe which feature you have a question about?**
Choose a different GitHub account repository to connect to a new Amplify project.

**Provide additional details**
I'd developed a React application (CRA) on my personal account which was connected to an Amplify project. I have since migrated code to another GitHub account that on which I am a collaborator (client account).

I've created a new Amplify application and now would like to connect this codebase to the new Amplify application which is now on the client's GitHub account however when I attempt to _Select a repository_ I can only see the repositories from my personal account.

How can I get the client's repos to show in the list? 

I have access to the repo (via the org) and have pushed code recently.

**Comment by garyleework** [comment]
Hi, you have to ask the organization owner grant permission to amplify Oauth app. You can do this by re-authenticate your amplify app and submit a organization permission request during the oauth flow.

**Comment by skoch** [comment]
@garyleefight Thanks for the response. I'm struggling how to "re-authenticate [the] amplify app" to get the "organization permission request".

Is this something you do via the admin console or via CLI?

**Comment by skoch** [comment]
## Solved.

Steps to re-authorize provider as follows.
1. Navigate to personal Github account (or where auth has already been granted)
1. Settings -> Applications
1. You may see Amplify listed in the first tab however you are concerned with the `Authorized OAuth Apps` tab
1. From the `Authorized OAuth Apps` tab, Revoke access.
1. Navigate to your Amplify app and then click the `Reconnect repository` button
1. This will walk you through the steps where you can select the organization that you'd like to request which will then (once requested) send an email to the org owner for them to authorize the AWS Amplify app
1. You can continue from here and once they have approved the request you can...
1. Head on over to your Amplify app and (if needed refresh the page) to reconnect a repository where you will see your perso repos as well as any org repos that have been granted access.
