### ISSUE TITLE
Amplify build settings SAM CLI version

### ISSUE THREAD

**Issue by Hansesto** [aws-amplify/amplify-console#1102]
Hello,

The Amplify build settings guide the CICD integration with git branches. We would like to include our SAM deployment as a part of the backend build phase.
However, the SAM CLI version on the runner is :
```
Executing command: sam --version
2020-10-02T08:25:37.429Z [INFO]: SAM CLI, version 0.19.0
```
which does not support arguments: `--config-file` nor `--config-env` which are required by our environment dependent system. We need those arguments to deploy SAM with environment specific configurations.

**Describe the solution you'd like**
Is it possible to upgrade the SAM CLI tool on the Amplify build runner? If it is, how is done?
If it cannot be done manually by us, what is the roadmap for the Amplify build system? I.e. when would the SAM CLI tool be upgraded to at least 1.3.0, that introduced those needed arguments?

**Additional context**
Here are the [release notes for the SAM CLI version 1.3.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.3.0).

**Comment by garyleework** [comment]
Hi, you can manually add sam update commands in pre-build stage in the buildspec. You can revise the buildspec via `build settings` on the left panel.

**Comment by Hansesto** [comment]
Hello,

Thank you, updating the SAM CLI tool as a part of the prebuild phase worked, and the SAM deployment went through.
We updated the CLI tool with `pip3 install --user --upgrade aws-sam-cli`.
