### ISSUE TITLE
Custom domain configuration failed

### ISSUE THREAD

**Issue by aeflorezm** [aws-amplify/amplify-console#1103]
**App Id**: 
**Region**: us-east-1
**Step**:SSL configuration
**Status**:failed

>**Note**: 

**Issue/question**
Good day, I am trying to connect to a custom domain,  the DNS records were creaed properly and when I do the query to the DNS with DIG everything seems to be fine, however  Amplify has not been able to connect to it.

**Error message** We could not validate the CNAME record exists in your DNS file. Add the following record in your DNS provider to route all the traffic to your domain and try again. Visit our troubleshooting guide below to learn more about connecting your custom domain.
**Additional information** I have retry the process several times and waited around a week in case there was cache, but still not working.

**Comment by ganipcanot** [comment]
Could you please share the appId?  It can be found as part of the App ARN on the `General` tab under `App settings`.

![image](https://user-images.githubusercontent.com/21091073/95104264-792c6a80-06ea-11eb-802b-2a8105a7dd64.png)

**Comment by aeflorezm** [comment]
Sure, my apologies, I missed it before the id is: d1m6sqvqt0dsa5

**Comment by nimacks** [comment]
@aeflorezm is this still an issue?

**Comment by aeflorezm** [comment]
It was bue I just deleted it and created again a  few days ago. Thank you so much
