### ISSUE TITLE
Why is my build always 'Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.29.4...'

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-console#1104]
** Please describe which feature you have a question about? **
It seems @aws-amplify/cli is alway set by default to 1.12.0 with my builds. 

Ofcourse to override this I have my build set to always use the latest version of the amplify cli. 

But on every build it seems to want to use 1.12.0: 

```
2020-10-02T18:45:14.529Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2020-10-02T18:45:24.229Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.29.4...
```

Why does it keep doing this? I'm trying to get my build times down and this process unnecessarily adds 10 seconds...

**Comment by garyleework** [comment]
Sorry for the confusion. We don't install the default the image to the container on every build. We just update the dependency as you override at run time. We will release a new default amplify image and update the cli version.

**Comment by hisham** [comment]
Ok sounds good! Thx for the reply. The reason for my override is the amplify image was always installing 1.12.0 every time - and I wasn't sure why, there was no override from my part.

**Comment by garyleework** [comment]
So if you check the `build settings` -> `build image settings`, you should find a default override for latest version of amplify CLI.

**Comment by hisham** [comment]
Yes here's my settings. The only reason I have the Amplify CLI override is because without it, aws amplify console will use version 1.12.0 of the cli which is an awfully old version. 

<img width="346" alt="AWS Amplify Console 2020-10-02 17-45-36" src="https://user-images.githubusercontent.com/81853/94977688-16af5080-04d7-11eb-92c1-e01829a904b2.png">

**Comment by litwicki** [comment]
@hisham is there anything else we can help you with on this?

**Comment by hisham** [comment]
Yes. I'm just curious why my build image always defaults to 1.12.0 of the amplify cli each time?

**Comment by litwicki** [comment]
That's the version in place on the default image, but we are in the process of updating that within the next month or two in fact.
