### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by ashutosh-indusved** [aws-amplify/amplify-console#1105]
**App Id**: d1qzpt65x8lptb
**Region**: ap-southeast-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
I have already linked this domain in a different region with a different aws amplify resource. Is there any restriction on this ?

**Comment by ganipcanot** [comment]
Are you still having issues?  It looks like that domain is available and active.  Please re-open the ticket if you are still having issues!
