### ISSUE TITLE
Redirection for multilingual page

### ISSUE THREAD

**Issue by jngbng** [aws-amplify/amplify-console#1107]
** Please describe which feature you have a question about? **

Accept-Language based redirection instead of Region-based redirection.
custom Lambda@edge for redirection rule.
Origin URL for redirection.

** Provide additional details**

The same issue as https://github.com/aws-amplify/amplify-console/issues/700.
I have static Gastby site with multilingual support so that I wish to redirect English users to /en/ and Korean users to /ko/.
Region-based redirection, however, does not respect actual user's preference.
Better approach is to redirect based on 'Accept-Language' header.

At first, I tried to make an API Gateway for it which redirect to '/en/' or '/ko/' based on Accept-Language header.
But with `200 (redirect)` setting, 'accept-language' header is not proxied.
`302(redirect)` setting, api gateway address is exposed to user. (and users have to redirect two times..)
And both setting, there is no way to get original host from which users access.
Since my site has multiple domain names (due to legacy support), I cannot hard-code host name to target url.

a) Af far as I know, CloudFront Itself supports this feature using Lambda@edge.
Is there any way to set Lambda@edge for redirection rule for Amplify app?

b) Is there any other workaround for it?

**Comment by swaminator** [comment]
@jngbng we support custom headers: https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html

**Comment by Athena96** [comment]
closing, please feel free to re-open if you are still facing this issue

**Comment by jngbng** [comment]
@swaminator custom headers is to add a custom header to responses. I don't figure it out how that feature may solve my problem. More detailed description would be greatly appreciated.
I hope to branch on REQUEST header (Accept-Language header) on server-side, not to add custom header to response.

**Comment by jimmyn** [comment]
@swaminator I'm also interested in this feature, it would be nice to be able to redirect based on the language header or user location

**Comment by jngbng** [comment]
@jimmyn Redirecting based on user location is already supported. Please refer to https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#region-based-redirects

**Comment by matteoxplo** [comment]
@jngbng I'm trying to redirect based on user language without success, have you found a solution to this problem?

**Comment by StephaneBischoff** [comment]
I had an issue with my amplify not detecting the `accept-language` header on my home page. Figure out that it was because I was not letting CloudFront cache by that  `accept-language` header.  Just go to CloudFront Default route and add that header and the detection should work after that. 
See https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-headers-behavior

**Comment by PhilippS93** [comment]
> CloudFront Default route

How did you configure cloudfront on amplify? Seems that amplify is configuring cloudfront in the background?
