### ISSUE TITLE
Deployment failed! when running amplify publish

### ISSUE THREAD

**Issue by RobertVillalba** [aws-amplify/amplify-console#1108]
** Please describe which feature you have a question about? **
Amplify publish

** Provide additional details**
Hello I'm having an issue trying to follow the amplify tutorial https://docs.amplify.aws/start/getting-started/hosting/q/integration/react when it comes to the publishing step. The CLI just errors out and doesn't provide any additional information.

```
...
The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

√ Zipping artifacts completed.
× Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
An error occurred during the publish operation
```

App ARN
arn:aws:amplify:us-east-2:743583968586:apps/d32brpwi32pe77

**Comment by ganipcanot** [comment]
Looks like the app was successfully deployed here: `https://cameras.d32brpwi32pe77.amplifyapp.com/`.  Closing for now.  If you are still experiencing issues please re-open this ticket.

**Comment by msandeep79** [comment]
@RobertVillalba  were you able to figure out the issue? Is it also showing "add deployment queued" on the Console UI ?
