### ISSUE TITLE
Gatsby page always redirects to landing

### ISSUE THREAD

**Issue by tnorlund** [aws-amplify/amplify-console#1109]
**Description**
Whenever I send a link to someone, the Amplify app redirects to the landing page. I'm not sure how to handle the redirects (this is my first Amplify app). Here is what I have so far.

<img width="1470" alt="Screen Shot 2020-10-03 at 12 09 54 PM" src="https://user-images.githubusercontent.com/26452518/94999902-7b1eee00-0571-11eb-8c0f-fd169bc83325.png">

How should I change this so that I can send someone https://www.tylernorlund.com/resume and when they click it, it goes to the resume page?

**Repro**
Repository: https://github.com/tnorlund/Blog
Amplify link: https://www.tylernorlund.com/

**Comment by ganipcanot** [comment]
It looks like you were able to figure this out since the link is now working as far as I can tell.

If you are still experiencing issues please re-open this ticket and provide your `appId` and `region` (appId is part of your app ARN in the `General` tab under `App Settings`

**Comment by zoosissoos** [comment]
@tnorlund Do you have a solution to this available? I am currently having the same issue.

**Comment by tnorlund** [comment]
@zoosissoos I ended up committing my code again, and it fixed whatever it was. Make sure that your pages are uniquely identified in your `src/pages` and that the slug is declared in `Gatsby-node.js`.

**Comment by zoosissoos** [comment]
Ok thanks. Would it be possible to copy/paste your redirects config in the amplify console? 

Whenever I click a link within my deployed gatsby site, it will go to the correct page, but if I enter within the browser bar it goes to the root index.

```
[
    {
        "source": "/<*>",
        "target": "/index.html",
        "status": "404-200",
        "condition": null
    },
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]
```

**Comment by tnorlund** [comment]
I'm not using redirects.
