### ISSUE TITLE
Domain activation is Failed - Error message: One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by dbrunet73** [aws-amplify/amplify-console#111]
**App Id**: d23pfcn78e7nq7
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
When trying to deploy a domain, it keeps saying there is a duplicate cname, but none exist. 

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by swaminator** [comment]
@dbrunet73 thanks for the feedback. We don't always know which CF distribution it is associated with as you may be using the CNAME with a CF distro in another account.
