### ISSUE TITLE
Domain activation is Failed - when connecting an Amplify app

### ISSUE THREAD

**Issue by stmnk** [aws-amplify/amplify-console#1112]
**App Id**: d22dov8p356wvt
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I have already activated the same domain for a previous version of the same app (which is now removed). The domain activation keeps failing for the new app cannot be

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

I have followed the troubleshooting steps linked and removed the previous cloudFormation distribution

**Comment by ganipcanot** [comment]
It looks like this domain is active and available.  If you are still experiencing issues please re-open the ticket.

**Else you can try the following:**

- Is this domain connected to a different Amplify App that you own? If so, make sure you are not trying to reuse one of the hostnames.
- If you are using www.domain.com on the other app, you cannot use www.domain.com on this app
- You can use other hostnames, like blog.domain.com
- If you had this domain successfully connected to Amplify and then recently (within the last hour) deleted it, please wait and try again.
- Check the Cloudfront console to see if you have this domain deployed to any distributions
- If you are positive no CloudFront distribution exists (including in other accounts) using this domain, and only if it would not be disruptive to any currently running services, try deleting and recreating the hosted zone
