### ISSUE TITLE
Is the latest image hosted anywhere?

### ISSUE THREAD

**Issue by alexkates** [aws-amplify/amplify-console#1114]
I'd like to create a custom build image, but base it on the official latest image, e.g., I'd like to have the following code at the top of my custom dockerfile

`FROM amplify/build-image:latest`

Is this image built and hosted anywhere?

**Comment by ganipcanot** [comment]
Check here: https://github.com/aws-amplify/amplify-console/tree/master/images

Closing - please re-open if you have additional questions.
