### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by joshclawson** [aws-amplify/amplify-console#1115]
**App Id**: d117c2egjv0rin
**Region**: us-west-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is:

Attempting to add a custom domain to amplify is failing though I've ensured the correct configuration in Cloudflare multiple times. I've tried with proxy on and off. 

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: The status of this certificate request is "Failed". One or more domain names have failed validation due to a Certificate Authority Authentication error. Learn more: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-caa.html

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by litwicki** [comment]
@joshclawson are you still experiencing issues?

**Comment by hsspain** [comment]
We are going to close this ticket.  Please let us know if you need further assistance.
