### ISSUE TITLE
Easier access to pull request preview build results

### ISSUE THREAD

**Issue by elliottyates** [aws-amplify/amplify-console#1116]
**Is your feature request related to a problem? Please describe.**
From what I can tell, seeing github-linked preview build/test results is only possible by manually going to the Preview part of the Amplify console and clicking into one of the `pr-*` links.

**Describe the solution you'd like**
The reported github status for the build would also provide a link directly to the build results (not just the preview deploy URL).

Thanks!

**Comment by swaminator** [comment]
This is now provided by defautl.

**Comment by elliottyates** [comment]
@swaminator thanks for your reply -- I'm afraid I'm not seeing any change to the github side of this. Here's a screenshot:

<img width="1360" alt="Screen Shot 2021-12-08 at 5 09 11 PM" src="https://user-images.githubusercontent.com/8975317/145292420-750f2089-64be-49f1-80d9-4fafab71b21f.png">

The "View more details" link there only takes me to the preview. I'd like to see build results.
