### ISSUE TITLE
Configure build settings not editable on hosting creation

### ISSUE THREAD

**Issue by ibrahimcesar** [aws-amplify/amplify-console#1117]
** Please describe which feature you have a question about? **  
I'm using amplify hosting in order to make a CI/CD pipeline for NextJS apps. And works great! But every time I add a new env and need to edit the configure build settings on console, the edition is "disabled", and I need to change the default ".next" to "out".

** Provide additional details**  
- Only in the creation. After that I can edit. Mot something so serious since I was able to edit and build, but with that my first build always fail. 
- Also, worth mentioning that is said that "autodetected" my app setting but I define in previous steps on CLI other distribution directory:

```
? Enter a name for the project presente
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using react
? Source Directory Path:  src
? Distribution Directory Path: out
? Build Command:  npm run-script build
? Start Command: npm run-script start
Using default provider  awscloudformation
```
Which was what I had to edit, everytime.

**Comment by ganipcanot** [comment]
You should be able to add the build settings to your repository in the root directory.  Please see: https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html.

Namely: `Save the build settings in your repository - Download the amplify.yml file and add it to the root of your repository`

If you are still experiencing issues please re-open the ticket.

**Comment by ibrahimcesar** [comment]
But even if create a file, still not able to edit in the first run... so just reporting some kind of error in the UI of Amplify
