### ISSUE TITLE
Gatsby custom URL using Reach Router is being ignored

### ISSUE THREAD

**Issue by ilyador** [aws-amplify/amplify-console#1119]
this is my gatsby-node.js file:

```js
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions

  createPage({
    path: '/webinar/*',
    matchPath: '/webinar/:meetingId',
    component: path.resolve(`src/pages/webinar.js`)
  })
}
```

The paths should be configured in Reach Router, and this also works fine in Netlify.
In Amplify I get the "no permissions" page. Is there anything I should configure to get it working?

<img width="764" alt="Screen Shot 2020-10-07 at 17 00 28" src="https://user-images.githubusercontent.com/703551/95356476-9d40a500-08be-11eb-8910-55a41e076da0.png">

This is the app URL that should be working: https://www.codeforhumans.info/webinar/82848250919?price=89
And here is the Netlify version: https://ecstatic-ptolemy-9fb915.netlify.app/webinar/82848250919?price=89

**Comment by swaminator** [comment]
@ilyador this seems to be working now?

**Comment by ilyador** [comment]
Yes, I added the following 200 redirect in the Amplify console:

From '/webinar/<*>' to '/webinar/index.html'
