### ISSUE TITLE
Domain activation is Failed - DNS record points to another CloudFront distribution. 

### ISSUE THREAD

**Issue by p-bustos** [aws-amplify/amplify-console#1120]
**App Id**: d1wvmtd4svhkjn
**Region**: ca-central-1
**Step**: Domain activation
**Status**: Failed

when trying to setup a custom domain in amplify we get the error below, we look in our cloudfront distribution console and it is empty, we see no distributions at all, we would expect to see the previously setup environments

**Error message**
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by ganipcanot** [comment]
It looks like you still have an application associated to the domain in question under appId `d5chxq18wr8ul` in `us-east-2`.

**Comment by p-bustos** [comment]
where can I see that application? it does not show on our cloudfront? our cloudfront dashboard is empty

**Comment by p-bustos** [comment]
Found the deployments
