### ISSUE TITLE
Domain activation is Failed

### ISSUE THREAD

**Issue by jericopulvera** [aws-amplify/amplify-console#1121]
**App Id**: dptgqyo1az3e7
**Region**: ap-southeast-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Domain activation failed and I followed the steps correctly.

**Error message**
Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: The status of this certificate request is "Failed". One or more domain names have failed validation due to a Certificate Authority Authentication error. Learn more: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-caa.html

**Additional information**
Vercel is managing my dns.

**Comment by litwicki** [comment]
@jericopulvera are you still experiencing any issues?

**Comment by jericopulvera** [comment]
No.
