### ISSUE TITLE
Domain activation is stuck in pending state

### ISSUE THREAD

**Issue by okaluhina** [aws-amplify/amplify-console#1122]
**First App Id**: d31kllttcnaaf0
**Second App Id**: d2ecrnu0hed04n
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Pending

**Issue/question**
Due to some bureaucracy issues the CNAMES were added too late and now app is stuck in pending domain activation state. Is there some way to manually trigger aws to restart domain activation step?

**Additional information**
![image](https://user-images.githubusercontent.com/46973932/95434095-88651f80-0959-11eb-8ba7-c178c5a577fe.png)

**Comment by swaminator** [comment]
@okaluhina can you try to delete and readd the domain.

**Comment by okaluhina** [comment]
> @okaluhina can you try to delete and readd the domain.

@swaminator  I could, but the problem is that will change CNAMES, and bureaucracy is not going anywhere any time soon. So I would really hoping for another solution. Am I right, there is no such solution?

**Comment by anubnair** [comment]
You need to create NS records and that will resolve the problem

**Comment by litwicki** [comment]
Closing this issue as the NS records are the required solution. If this issue persists even with NS records please reopen.

**Comment by sf2288** [comment]
I have added CName earlier and then create NS records on AWS and added them to my Namecheap domain. But still, my Domain is still showing in "Activation" from the last 2 days.
![image](https://user-images.githubusercontent.com/18467042/149464415-957a6524-fb0a-4dad-b3ee-6375d8c1f292.png)
