### ISSUE TITLE
Redirection Rules

### ISSUE THREAD

**Issue by tscole** [aws-amplify/amplify-console#1125]
I am trying to use the Rewrites and Redirects section to add a large number of rules (around 11,000) via a JSON object in the text editor. When I click save the page hangs / nothing seems to happen.

Is there a limit to the number of rules I can have? Is there another (better) way for me to upload my redirect rules?

Thanks

**Comment by ganipcanot** [comment]
Currently this is a service limitation (a large number of rewrite/redirect rules). We have opened an internal ticket to track this item and treating it as a high priority. Unfortunately we cannot provide a time estimate to when this will be resolved.

**Comment by litwicki** [comment]
@tscole In addition to what @ganipcanot said above, there is an upper bound we will be working to define/publish for customers, but in the meantime if possible the workaround would be to publish a subset of the 11,000 rules which will work until you've hit that limit.

**Comment by tscole** [comment]
What is the current limit?

**Comment by litwicki** [comment]
We aren't certain yet what the exact number is, but are working on it. Can you ping aws-amplify-customer@amazon.com with your appId and we can see about your specific scenario?

**Comment by hsspain** [comment]
@tscole I am going to close this ticket, but please reach out if you need further assistance.

**Comment by tscole** [comment]
Have just hit this issue again - this time with may fewer rules. This is a series problem as I need these redirects for site that is awaiting launch
