### ISSUE TITLE
Sound Bug

### ISSUE THREAD

**Issue by 11grossmane** [aws-amplify/amplify-console#1126]
When I deploy my site on Amplify, my website doesn't have any sound.  When I run it locally, the sound is there.  When I build a production version locally, the sound is there, but when it gets deployed through Amplify something gets rid of it.  Here is my build file.

`
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 13.8.0
        - nvm use 13.8.0
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*`
`

**Comment by 11grossmane** [comment]
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 13.8.0
        - nvm use 13.8.0
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

**Comment by 11grossmane** [comment]
unfortunately, your system doesn't let me upload a yml file

**Comment by ganipcanot** [comment]
Could you please share your `appId` and `region` for this app?  The `appId` can be found as part of the `appArn` on the general settings page.

**Comment by 11grossmane** [comment]
arn:aws:amplify:us-east-2:187401640486:apps/d1oavtoprkpzct

region is ohio us east

also, I've now successfully deployed the app WITH sound on both firebase and heroku, so something must be different about the the way you guys build the app.

**Comment by obs-stanley** [comment]
I'm also running into this issue. When I deploy a site using Amplify, the website does not have sound. It does have sound when run locally. I note that the browser gets a response header of `content-type: text/html` when loading a `.mp3` file. 

Let me know if I should write this into a separate issue.

**Comment by FilipKaluza** [comment]
> When I deploy my site on Amplify, my website doesn't have any sound. When I run it locally, the sound is there. When I build a production version locally, the sound is there, but when it gets deployed through Amplify something gets rid of it. Here is my build file.
> 
> ` version: 0.1 frontend: phases: preBuild: commands: - nvm install 13.8.0 - nvm use 13.8.0 - npm ci build: commands: - npm run build artifacts: baseDirectory: build files: - '**/*' cache: paths: - node_modules/**/*`
> `

Did you find some solution ? I have same problem

**Comment by 11grossmane** [comment]
nope, switched to firebase hosting

**Comment by hamedhemmati** [comment]
I am having this issue as well.

**Comment by SterlingJS** [comment]
@hamedhemmati Experiencing the same issue and that fixed it!

**Comment by ganipcanot** [comment]
Closing based on discussion above - please feel free to re-open if still experiencing issues.
