### ISSUE TITLE
Quick Notes AI

### ISSUE THREAD

**Issue by admissionguidance** [aws-amplify/amplify-console#1127]
** Please describe which feature you have a question about? **
I am unable to deploy the react app based on the sample provided by AWS, Quick Notes AI cannot be deployed.

** Provide additional details**

**Comment by swaminator** [comment]
@admissionguidance what error are you getting?

**Comment by litwicki** [comment]
This has been resolved, please let us know if you continue to experience any issues.

Please see this for reference: https://github.com/aws-samples/aws-amplify-quick-notes/issues/3
