### ISSUE TITLE
How to combine separate repos into a single frontend build?

### ISSUE THREAD

**Issue by MatthewFrench** [aws-amplify/amplify-console#1128]
** Please describe which feature you have a question about? **
My website is separated into three repositories. I'd like the first to show up at web path /, the second to show up at path /forum/ and the third to show up at path /game/.
Is there a way I can have all the build artifacts go into the same website?

**Comment by ganipcanot** [comment]
You could host the 3 separate sites on 3 different amplify apps and have a main application which handles the redirection to the other two namely `/forum/` and `/game/`.

If you are interested in combining the 3 repositories under distinct folders (monorepo) we have support for that.  [Check this out](https://aws.amazon.com/blogs/mobile/set-up-continuous-deployment-and-hosting-for-a-monorepo-with-aws-amplify-console/) for more information about monorepos.

Closing for now - if you have any additional question please feel free to re-open the ticket.
