### ISSUE TITLE
YAMLException: non-printable characters with Hebrew letters in config file

### ISSUE THREAD

**Issue by Hadayo** [aws-amplify/amplify-console#1129]
I'm trying to deploy my Jekyll site that is present in a GitHub repository. It is working fine locally and I was running it for a few weeks on CloudCannon services with no problem. However when I'm importing the repo with the Amplify interface, I get the following error:

**There was an error detecting your build settings.**
YAMLException: the stream contains non-printable characters at line 4, column 39: ... ××× ×¤× 1×' â ×× ××× ^

The reason for this error is obvious to me: The title of the site in the config file (with many other parameters too) is in Hebrew. Here is an excerpt from the _config.yml file to demonstrate:
~~~
title: אינפי 1מ' – יד ביד
cover_img_path: "/figures/cover.png"
baseurl:
~~~

However, I cannot change the language of the site for obvious reasons as the site is meant to be used by certain people who speak a certain language.
Any advice on how can I solve this problem?

**Comment by ganipcanot** [comment]
Would you be able to share your `appId` and `region` please?  The `appId` can be found as part of the `appArn` on the general settings page.

**Comment by Hadayo** [comment]
I'm not sure I can find the `appId` as I was not able to create an app in the first place. This error occurred during the creation of the app so I could not finish the process. I might have understood you wrong regarding the meaning of `appId`. 
Also, the `region` I'm using is 'Frankfurt (eu-central-1)'.

I hope I gave you the right information, I'm new to AWS.

**Comment by ganipcanot** [comment]
Ah okay.  Would you be able to share your `_config.yml` file?  You can share it here or if you didn't want to share it here you can send it to `aws-amplify-customer@amazon.com` - please include the issue link (`https://github.com/aws-amplify/amplify-console/issues/1129`) in the email.

**Comment by Hadayo** [comment]
Just sent it to the mail.

**Comment by litwicki** [comment]
@Hadayo are you still experiencing any issues?

**Comment by Hadayo** [comment]
Hi, to be honest I switched to a different hosting service it is irrelevant now. Thanks anyway!
