### ISSUE TITLE
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by suhabe** [aws-amplify/amplify-console#113]
**App Id**: d1i81te6qozld5
**Region**: US West (Oregon)
**Step**: Domain Activation
**Status**: Failed

**Issue/question**
My domain is managed by Route 53 but owned by Godaddy. I set up the nameservers appropriately in Godaddy to match the Route 53 console. When I attach the domain to my amplify app, it fails in the "Domain activation" phase.

**Error message**
"We had issues connecting your custom domain: **** Please visit the Domain Management page for more information. Error message: One or more of the CNAMEs you provided are already associated with a different resource."

I tried deleting the app and recreating it, but it didn't help.

**Comment by suhabe** [comment]
Figured it out. I had another amplify app in another region that was using the domain.

**Comment by l0609890** [comment]
Hi suhabe, I am also facing the same problem. Did you have to delete the amplify application that is already using the domain, to connect it to the new amplify app?

**Comment by annaira** [comment]
Hi I have the same problem, I already deleted the running application a few hours ago. How long does it take until the error is resolved?
