### ISSUE TITLE
Production site suddenly 404'ing “x-cache: Error from cloudfront”

### ISSUE THREAD

**Issue by mrcoles** [aws-amplify/amplify-console#1130]
**App Id**: d32cgdvim65k7p
**Region**: us-east
**Step**: n/a
**Status**: n/a

**Issue/question**

My app suddenly started 404'ing. No code updates or configuration changes for over a week and it was working before.

The dev one is working fine: https://dev.d32cgdvim65k7p.amplifyapp.com 
The master (production) one is 404ing: https://gofullpage.com/ OR https://master.d32cgdvim65k7p.amplifyapp.com OR I even added an alternate domain and that’s failing too https://fullwebpagescreencapture.com/

**Error message**

When I request the page I get the response:

```
content-length: 0
date: Sun, 11 Oct 2020 23:06:58 GMT
server: CloudFront
status: 404
via: 1.1 6cfc86e6ccd19a4761a27f5f2d9c9a91.cloudfront.net (CloudFront)
x-amz-cf-id: 3jaeJ6HiQ8AhyFscaHTM3tgn1bgtl7cnyKX_l8KrpnCRzl-tIKY1xw==
x-amz-cf-pop: BOS50-C2
x-cache: Error from cloudfront
```

**Additional information**

Amplify doesn’t let me access S3 or Cloudfront, so I can’t debug this. I’ve tried redeploying, pushing some minor changes, and even adding an alternate custom domain, but none of these are fixing it.

I have drastically cut down my “Rewrites and redirects” to be just this:

```json
[
    {
        "source": "/redir-test",
        "target": "https://example.com/",
        "status": "302",
        "condition": null
    },
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json|webmanifest|mp4|webm)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]
```

with that change, I am seeing the following:

1. http://gofullpage.com/redir-test properly 302 redirects to https://example.com/ (so we’re at least hitting that part of the app)
2. https://gofullpage.com/privacy should 200 rewrite to /index.html, but still 404s
3. http://gofullpage.com/static/email/email-99-logo-tight@2x.png should be served directly without rewrites, but still 404s

I know these files exist, here’s a copy-paste from the “deploy” step of my last build/deploy:

```
2020-10-11T22:47:26 [INFO]: Starting Deployment
…
2020-10-11T22:47:29 [INFO]: Uploading index.html
…
2020-10-11T22:47:30 [INFO]: Skipping upload of existing file static/email/email-99-logo-tight@2x.png
…
2020-10-11T22:47:30 [INFO]: Updating Edge config
2020-10-11T22:47:30 [INFO]: Deployment finished.
```

*NOTE:* I’ve added temporary “200 rewrites” to a temporary page on another server for the core pages on my site to try and mitigate this issue while I am unable to solve it, but you can still see how cloudfront is unable to find my dist files with /privacy link above.

**Comment by litwicki** [comment]
@mrcoles we're investigating this now.

**Comment by mrcoles** [comment]
@litwicki thx! From reviewing my logs this looks like it started between 8–9AM EDT on Saturday October 10 and has been impacted since.

**Comment by abhi7cr** [comment]
@mrcoles Can you reload the app and check?

**Comment by litwicki** [comment]
@mrcoles I believe we have it resolved, but please let us know if there is anything else we can do.

**Comment by mrcoles** [comment]
@abhi7cr and @litwicki thanks! It looks like it’s working now.

However, one of my rewrite rules isn’t updating. https://gofullpage.com/connect is still showing the “Temporarily unavailable” page, even though I removed that rule and even went so far as to add an explicit rule for it to rewrite to /index.html?

```json
[
    {
        "source": "/redir-test",
        "target": "https://example.com/",
        "status": "302",
        "condition": null
    },
    {
        "source": "/connect",
        "target": "/index.html",
        "status": "200",
        "condition": null
    },
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json|webmanifest|mp4|webm)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]
```

It’s odd, because the other rewrite updated immediately, but just this one is sticking. Any ideas?

**Comment by abhi7cr** [comment]
@mrcoles, We noticed the `/connect` was being served through `cloudflare` cache first before hitting `cloudfront`:
 
Response header: `server: cloudflare`. 

Is it possible that route is cached in cloudflare?

**Comment by mrcoles** [comment]
@abhi7cr good question!

This is the file: https://mrcoles.com/media/fpsc/gofullpage-down-message/index.html

I already updated it, that above URL will show you “Loading…” while my non-updating page (https://gofullpage.com/connect?signin) still shows “Temporarily unavailable”

I previously tried purging files from my cloudflare cache (just in case) and told it to purge the following (just did it again now):

> https://mrcoles.com/media/fpsc/gofullpage-down-message/index.html
> https://mrcoles.com/media/fpsc/gofullpage-down-message/
> https://gofullpage.com/connect?signin
> https://gofullpage.com/connect

That didn’t seem to achieve anything.

Separately, given that I specified a new rule for that path in the app’s “Rewrites and redirects”, I would have thought that would overwrite how the Cloudfront cache handles that URL? (FWIW other URLs updated, just this one is not)

**Comment by mrcoles** [comment]
If I had access to the cloudfront instance, I would probably try to invalidate the files for those URLs? https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html Is this possible?

**Comment by hsspain** [comment]
@mrcoles We are still seeing CloudFlare responses when requesting https://gofullpage.com/connect

Other paths, such as https://gofullpage.com and https://gofullpage.com/demo-editor-inline do not have these same response headers.  Is is possibly that you are utilizing Page Rules or other mechanisms within CloudFlare?

**Comment by mrcoles** [comment]
gofullpage.com is an Amplify site.

Earlier today when everything was broken (see original post on this issue), I created a page on another site (mrcoles.com Cloudflare site) and I added it as a “200 rewrite” for the /connect path **for my Amplify site**, e.g.,

```
{
    "source": "/connect",
    "target": "https://mrcoles.com/media/fpsc/gofullpage-down-message/index.html",
    "status": "200",
    "condition": null
  }
```

I was able to edit and modify the underlying page and I would see it update when I loaded gofullpage.com/connect

when the original issue was fixed, I removed this rule, but I was seeing it still serving that temporary page. I then went and added an explicit rule for /connect to see if it would just serve my Amplify app’s /index.html file:

```
[
    {
        "source": "/connect",
        "target": "/index.html",
        "status": "200",
        "condition": null
    },
    {
        "source": "/connect?signin",
        "target": "/index.html",
        "status": "200",
        "condition": null
    },
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json|webmanifest|mp4|webm)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]
```

However, it’s still caching the old URL.

@hsspain I don’t understand your question. The issue appears to be that CloudFront has cached response and will not update. Shouldn’t it be possible to invalidate that URL in CloudFront and be done with it? Also, as seen in my previous responses, this CloudFlare URL is not stuck caching the old one (visit the URL directly and it’s different), but Cloudfront has it cached and keeps returning it for my Amplify URL.

**Comment by hsspain** [comment]
@mrcoles We have ensured that all cache is invalidated from your CloudFront distribution for the affected paths. 

CloudFlare has ways of changing behavior of specific pages or paths that could account for what we are seeing.  https://support.cloudflare.com/hc/en-us/articles/218411427-Is-there-a-tutorial-for-Page-Rules-#summary-of-page-rules-settings this link has an overview of some ways the old page could be potentially served. Can you verify that there are no other settings in CloudFlare that could possibly redirect the traffic to that specific path?

**Comment by mrcoles** [comment]
@hsspain what specific page PageRules are you looking for?

When I load the [url in question](https://gofullpage.com/connect) I am seeing an old version of the page that no longer exists on the Cloudflare server. **Also, nothing in my Amplify app’s rewrite & redirect rules references the Cloudflare site anymore.**

This experience suggests to me that CloudFront has cached the old, no-longer-available Cloudflare page and is ignoring any attempts to tell it to serve something different.

To answer your question, that page’s Cloudflare rules are these two from the screenshot which should have no effect and it has “Caching Level: Standard” and “Always Online: On”:

![image](https://user-images.githubusercontent.com/136651/95709257-4a534e80-0c2c-11eb-8146-9ae6626d57b2.png)

**Comment by hsspain** [comment]
@mrcoles I apologize for the confusion. In our logs we no longer see any redirects or rewrites to the mrcoles.com site. We do see requests to index.html when hitting the /connect path.  This should serve index.html for /connect similar to other paths. The only difference we are able to detect for the /connect path are the server response headers. When tracing the request to the /connect path, we get these headers:

cache-control: public, must-revalidate, max-age=0
cf-cache-status: DYNAMIC
cf-ray: 5e0d67194eaff555-SEA
cf-request-id: 05bc3ec3cb0000f5551f1e4200000001
content-encoding: gzip
content-type: text/html
date: Mon, 12 Oct 2020 06:01:14 GMT
etag: W/"8291526ab0d27502b91fb92aa83f6759"
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
last-modified: Mon, 12 Oct 2020 02:04:45 GMT
nel: {"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?lkg-colo=28&lkg-time=1602469867"}],"group":"cf-nel","max_age":604800}
server: cloudflare
status: 200
vary: Accept-Encoding
via: 1.1 3566cbcd49f71967b52a565888e4d272.cloudfront.net (CloudFront)
x-amz-cf-id: 0ng0mkX_48Vx83-hPtbFgW5yU3Pk4dl9LLiZQl1j_t6tfS0hZetADw==
x-amz-cf-pop: SFO5-C1
x-cache: RefreshHit from cloudfront

The server: cloudflare, cf-cache-status, cf-ray, and cf-request-id headers lead us to believe the request is being served by CloudFlare. The x-cache: RefreshHit from cloudfront header seems to affirm that we are not caching that content in CloudFront.

Can you possibly look at your DNS records and verify that they go directly to the CloudFront site?

**Comment by mrcoles** [comment]
The domain is in Route53. It has no CloudFlare references. This really looks like old cached content from the brief period of time in which I set an Amplify rewrite rule to proxy the mrcoles.com aka CloudFlare site.

The only other quirk with DNS, is that when I check the Amplify DNS records for gofullpage.com I see the following:

```
@      ANAME    d32cgdvim65k7p.amplifyapp.com
www    CNAME    d32cgdvim65k7p.amplifyapp.com
```

But when things were originally broken, I tried provisioning another domain (another one I have in Route53) to see if it would work, and when I did that it was given different DNS records, i.e.,

```
@      ANAME    d60tk959pf96o.cloudfront.net
www    CNAME    d60tk959pf96o.cloudfront.net
```

Is it possible when you cleared the cache or whatnot that you’re missing an extra layer from the *.amplifyapp.com URL?

**Comment by hsspain** [comment]
@mrcoles The issue appears to be resolved.  /connect now hosts the proper files. We will continue to investigate root cause. Please let us know if this looks resolved from your end.

**Comment by mrcoles** [comment]
@hsspain looks like it’s working now, thanks! CloudFront is returning the right content now. There’s still some local browser caching, but that’s fine and not on you guys.

I’d love to hear more about root cause, so I can make sure it doesn’t happen again. IDK if by being an older project (in Amplify terms) there are maybe some configuration things that caused my app to be impacted but not newer ones?

**Comment by swaminator** [comment]
@mrcoles we released a new deployment service to fix issues with deploy failures. Apologies for the issue. I'll reach out to you via email for more info.
