### ISSUE TITLE
AWS Amplify Deploy React App Error Access Denied

### ISSUE THREAD

**Issue by samvillasmith** [aws-amplify/amplify-console#1131]
>
**Issue/question**
I am following the tutorial for AWS Amplify, deploy a react app, and I continue receiving an error message for "access denied". I have done everything exactly as requested. 

**Error message**
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>(Omitted for Security Reasons) </RequestId>
<HostId> (Omitted for Security Reasons) </HostId>
</Error>

**Additional information**

I have the following redirects and rewrites:

[
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
] 

 Is this a known issue? I am able to locally deploy the code with no issues at all.

**Comment by swaminator** [comment]
@samvillasmith can you share your build settings as well as the AppID?

**Comment by samvillasmith** [comment]
> @samvillasmith can you share your build settings as well as the AppID?

For some context, there is no backend architecture at all, and no s3 buckets, I'm following the tutorial strictly. https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-one/

**Comment by swaminator** [comment]
@samvillasmith for your build settings go to, App settings > Build settings. Appid (or App ARN) can be found under App settings > General

**Comment by samvillasmith** [comment]
> @samvillasmith for your build settings go to, App settings > Build settings. Appid (or App ARN) can be found under App settings > General

Oh ok, in this case it is arn:aws:amplify:us-east-1:371892882034:apps/d1dtb9u45ep0au

**Comment by samvillasmith** [comment]
Everyone, I'm sorry, the issue was with my commits to github, I appreciate your time, also the rewrites helped. Thanks again.

**Comment by AzherAleem** [comment]
@samvillasmith where did you place the redirects and rewrites:? Or did you configure them via aws amplify console?
