### ISSUE TITLE
How to overcome JavaScript heap out of memory issue by using larger build server?

### ISSUE THREAD

**Issue by frankclaassen** [aws-amplify/amplify-console#1132]
** Please describe which feature you have a question about? **
Amplify console seems to use a small build server and my front-end app now keeps failing with JavaScript heap out of memory errors.

So how do I increase the build server size OR use CodePipeline to bo my Amplify builds / releases?  This issue is causing critical issues as we cannot update our production system

** Provide additional details**

**Comment by abhi7cr** [comment]
Hi @frankclaassen, 

Can you try adding an env variable `NODE_OPTIONS` with a higher value for Max_space _size

**Comment by frankclaassen** [comment]
@abhi7cr I did try setting NODE_OPTIONS as an environment variable which did not work. AWS Support advised to set NODE_OPTIONS as an export in the pre-build command which I have not tried yet.  I found that the problem was being caused by large source maps being generated and have turned these off by setting GENERATE_SOURCEMAP false as an environment variable which resolved the build issue
