### ISSUE TITLE
PR previews using CSP in settings instead of amplify.yml

### ISSUE THREAD

**Issue by eardenercruk** [aws-amplify/amplify-console#1134]
## Issue Description
PR previews are using the Content Security Policy from the build settings defined in the Console instead of amplify.yml file in root.

![image](https://user-images.githubusercontent.com/57360840/95854859-74e9f800-0d4f-11eb-90cc-20156b9a2df4.png)

## Application Details
arn:aws:amplify:eu-west-2:145300272324:apps/d9slrnc36kbq7

**Comment by abhi7cr** [comment]
Hi @eardenercruk,

Thanks for reaching out, will take a look and get back to you.

**Comment by lukehedger** [comment]
@abhi7cr Anyone update on this? We are still seeing the problem.

**Comment by hloriana** [comment]
A fix was deployed earlier this year that should resolve this issue. If you are still having this problem, feel free to re-open. Thank you!
