### ISSUE TITLE
App Load Problem

### ISSUE THREAD

**Issue by cmeans** [aws-amplify/amplify-console#1135]
I have a Vue app that builds fine (a few warnings), but will no longer render from amplifyapp.com.

It runs fine locally (yarn serve).

Browsers complain that the app is taking too long to load.

The app has gone through a lot of changes as I've been testing out new Components...is there some sort of a cache, server-side, that's maybe a bit polluted a this point? (One that can be cleared.)

**Comment by abhi7cr** [comment]
Hi @cmeans, can you share the region in which this app is deployed?

**Comment by cmeans** [comment]
I solved my problem...had an infinite render loop that just wasn't obvious.  Thanks.
