### ISSUE TITLE
Amplify Console failed to detect Framework after production branch change

### ISSUE THREAD

**Issue by AustinZhu** [aws-amplify/amplify-console#1138]
Hi! I am deploying a React SPA on Amplify. We connected the develop branch at first for testing. However, when I switched the production branch to master, the Framework description disappeared. Will it effect future integration with Amplify? I think even after changing the production branch, Amplify console should be able to redetect the Framework.

![image](https://user-images.githubusercontent.com/42071208/95935653-b2618a80-0e0e-11eb-988c-99d4e81257f6.png)

**Comment by abhi7cr** [comment]
Hi @AustinZhu,

Thanks for reaching out. I will investigate and get back to you.

**Comment by kunalkhadke01** [comment]
when i clicked on my Production branch URL i got blank page .fist i got my page but after some deploymen i got blank page.what should i do to get my web page back ?
production url:https://master.d3eby3l0g0a216.amplifyapp.com/
when you click on that url you will get blank page with url:https://master.d3eby3l0g0a216.amplifyapp.com/src/
(page target address is index.js )

**Comment by litwicki** [comment]
@kunalkhadke01 are you still experiencing this?

**Comment by kunalkhadke01** [comment]
No , I am not facing any issue now.
thank you
