### ISSUE TITLE
Domain activation is Failed - CNAMEs already associated

### ISSUE THREAD

**Issue by yahavb** [aws-amplify/amplify-console#114]
**App Id**: d3401w5eo6qy1h
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am trying to add a domain I have in my account. The DNS verification goes well but it fails with the error below

**Error message**
If there is an error message, please include it here. 
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
I had the domain connected to an amplify console app but I had to delete the app and recreate it.

**Comment by nimacks** [comment]
@yahavb, this error indicates that the domain you're tying to connect is already associated with another CloudFront Distribution. If you want to use that domain with your Amplify app, then you'll need to disassociate that domain with the existing CloudFront distribution. After this is done, you should be able to connect your custom domain to your app.

You can find more details in our troubleshooting guide. https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-troubleshoot-guide

**Comment by nimacks** [comment]
@yahavb, our records indicate that your app has been deleted. Please let us know if you're still facing issues with your custom domain by re-opening this ticket.
