### ISSUE TITLE
Gatsby redirects always going to root only. 

### ISSUE THREAD

**Issue by zoosissoos** [aws-amplify/amplify-console#1141]
** Please describe which feature you have a question about? **
Rewrites/Redirects

** Provide additional details**
I am having an issue with redirects within my gatsby site hosted in Amplify Console. 

If I navigate to https://master.d1rnnz8nwkatw5.amplifyapp.com/ , It shows the root page. If I click on the link to bring me to https://master.d1rnnz8nwkatw5.amplifyapp.com/page-2/ it works as expected. 

However if I type https://master.d1rnnz8nwkatw5.amplifyapp.com/page-2/ or https://master.d1rnnz8nwkatw5.amplifyapp.com/page-2 it goes directly to https://master.d1rnnz8nwkatw5.amplifyapp.com/

I am receiving a 304 in the network tab.

Below is my redirect config:
```
[
    {
        "source": "/<*>",
        "target": "/404.html",
        "status": "404-200",
        "condition": null
    },
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]
```

**Comment by zoosissoos** [comment]
It seems this was the setting for if I wanted a SPA. I removed the second rule and it seems to be working now.

**Comment by perdomofranklindev** [comment]
@zoosissoos and now is it work?
