### ISSUE TITLE
Hosting bucket is empty

### ISSUE THREAD

**Issue by piotrduszynski** [aws-amplify/amplify-console#1142]
There is a problem that the hosting bucket that should contain my front-end application is empty after I did deployment from Amplify Console. It is worth to mention, that S3 is populated with the frontend app when I do deployment from cli. However, the application is magically working in the amplifyapp.com domain, which is provided by Amplify Console. The bucket is even empty when I use the CloudFront configuration for hosting, which is production configuration. URL to CloudFront is not reachable. However, the application is still working somehow using the amplifyapp.com domain.

Is my application somewhere outside my account? How does it work? Why this CloudFront and bucket is created if it's not used? How we are charged for that? Or maybe I missed something, and I'm not aware of some functionalities?

**Comment by swaminator** [comment]
Amplify hosting is a fully managed solution which means we do not upload files into your own S3 account. This allows us to offer features such as instant deploys, custom headers, redirects, and more.
