### ISSUE TITLE
Strange 301 redirect behavior when checking against redirect tool

### ISSUE THREAD

**Issue by drake-smith** [aws-amplify/amplify-console#1144]
I have a deployed Gatsby website and have this redirect in Amplify:

Source: `/services/<*> `
Target: `/solutions/<*>`
301 Redirect

This redirect works and appears fine when I type in a URL in my browser and I see it redirect to the target URL. However, when I check the URL on a redirect tool like http://redirectcheck.com/index.php, I see that there is what looks to be essentially an infinite loop of 301s where the target path is appended to the end of the url until CloudFront responds with a 413 error to stop it. 

Below is an example. The url is `/services/property` which should redirect once to `/solutions/property`. 

`/solutions/property//solutions/property//solutions/property//solutions/property//solutions/property//solutions/property//solutions/property//solutions/property`

It continues to grow longer and longer until that 413 response error.

I fear this will have adverse affects on SEO.

I can provide App ID and actual URLs to test privately.

**Comment by litwicki** [comment]
@MarkAtwood without knowing how that tool operates it's difficult for us to take any actions on this. Can you give us a full URL example and we can dig into seeing if there's anything we can optimize on our end?
