### ISSUE TITLE
Import data from "file.csv" not showing in amplify, but ok locally or in s3 hosting

### ISSUE THREAD

**Issue by gregbkr** [aws-amplify/amplify-console#1145]
** Please describe which feature you have a question about? **
Import data from "file.csv" not showing in amplify, but ok locally or in s3 hosting

** Provide additional details**
The code is here: https://github.com/gregbkr/crypto-stats
- I deploy locally or via s3hosting: http://stats-test-gg-2.s3-website-eu-west-1.amazonaws.com/ , I can see 4 graphs with data.
- I deploy via amplify: https://stats.satoshi.tech/ The last 3 graphs have not data.

Not sure how to troubleshoot that... Issue is somewhere [here](https://github.com/gregbkr/crypto-stats/blob/6669a9bd02a9070fe8c5fc31cfea3eeec1ec203f/src/components/commodity.js#L120), data is empty, it is support to be importe from local csv file.

Thank you for your help.
Greg.

**Comment by litwicki** [comment]
@gregbkr anything that's part of your artifact directory will be hosted on amplify as the root directory. You'll need to point your app to the proper path, and make sure that file is part of your deployment artifact.

**Comment by gregbkr** [comment]
OK, thanks for your answer. You may close.
