### ISSUE TITLE
Domain activation is Failed - DNS records hidden

### ISSUE THREAD

**Issue by woodsae** [aws-amplify/amplify-console#1147]
**App Id**: d26qxrq0tb7jkb
**Region**: ap-southeast-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
When domain activation fails, the **View DNS Records** button is disabled, which makes it nearly impossible to try and debug.

**Error message**
The error message I received was:
> One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Comment by NikitaVr** [comment]
Having the same issue after creating a new app in amplify

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
