### ISSUE TITLE
Private Dns not resolving

### ISSUE THREAD

**Issue by sreejith421** [aws-amplify/amplify-console#1149]
**App Id**:
**Region**:Oregon
**Step**:
**Status**:

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I have amplify deployed in  Oregon region and all the backend apis are publicly exposed previously . Now i internalized publicly exposed api to internal aws alb but after that amlify frontend apps are not communicating to backend apis both are on same region . is there anything additional setup need to be done    ?
**Error message**

**Additional information**

**Comment by behrooziAWS** [comment]
We don't have VPC support at this time, resolving as a feature request.
