### ISSUE TITLE
Domain activation is Failed - One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by harvminhas** [aws-amplify/amplify-console#1151]
**App Id**: d3gqbnkjynanus
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

I have a domain registered on GoDaddy but I am using AWS DNS servers. My domain is in a hosted zone and api.mydomain is connected successfully to the AWS API gateway.

However, now I am trying to connect www.mydomain to the Amplify application. It throws an error during domain activiation. Before it throws the error it does add a CNAME record in the hosted zone. And, I made sure there were no CNAMEs before I started activation. I do have few A records that connect to auth.mydomain, api.mydomain and api-dev.mydomain

I am not sure why it is telling me that "One or more of the CNAMEs you provided are already associated with a different resource."  Any help would be greatly appreciated.

**Comment by behrooziAWS** [comment]
Have you followed the troubleshooting steps here to rule out the common causes?:

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error

**Comment by harvminhas** [comment]
Yes, I have followed the troubleshooting steps. 

I do not have  a cloudfront distribution using the domain.

Also, it does add 1 A Record and 2 CNAME Records before it errors out. Also, afterwards if I try to access the domain from the browser, it takes me to a 'hello world' page. I am not sure where this page is located.

**Comment by behrooziAWS** [comment]
I think its because www.<yourdomain> is bound to your apigateway cloudfront distribution.  You can remove the www when following the amplify steps, otherwise you need to disassociate www with your apigateway distribution first.  https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-amazon-route-53.html

**Comment by harvminhas** [comment]
That was it!
Thanks a lot.
