### ISSUE TITLE
PWA deployment errors 

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-console#1153]
Hi,

I have an "hello world" Angular app here (ng new app) :
https://github.com/rudyhadoux/pwa

I want to deploy the PWA files in the folder dist/essai with this very simple amplify.yml :
 version: 1
frontend:
  phases:
    preBuild:
      commands:
    build:
      commands:
  artifacts:
    baseDirectory: dist/essai
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

And there is a very strange thing. Some files are populated with the content of index.html like manifest.webmanifest (PWA configuration file). 
Why ? And how to fix that Amplify Console bug ?

The wrong result is here :
https://master.dwusr9lvds6ht.amplifyapp.com

**Comment by behrooziAWS** [comment]
To clarify your question, you are wondering why https://master.dwusr9lvds6ht.amplifyapp.com/manifest.webmanifest is populated with the content of index.html?

**Comment by behrooziAWS** [comment]
I've confirmed with a coworker, that we automatically apply this rule for single page webapps to send you back to index.html

https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa  I will make a note to update the docs.

**Comment by rudyhadoux** [comment]
Thanks for answers.
So, how to achieve the hosting of a PWA and SPA Angular app ?

**Comment by rudyhadoux** [comment]
I have deleted the two redirect rules ans the PWA works.

**Comment by david-wallace-croft** [comment]
I appended the .webmanifest filename extension to the list of extensions not redirect:
`</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json|_webmanifest_)$)([^.]+$)/>`

**Comment by rudyhadoux** [comment]
It is a good thing.
