### ISSUE TITLE
Unable to clone repository from code commit at BUILD step while deploying to AWS Amplify

### ISSUE THREAD

**Issue by Nirjhar100** [aws-amplify/amplify-console#1158]
Getting  error on build step for amplify while cloning

<img width="1002" alt="Screenshot 2020-09-20 at 2 05 29 PM" src="https://user-images.githubusercontent.com/22238902/93707246-59257480-fb4a-11ea-9970-260cbd01c74c.png">

I have created a react project repository in code commit and it was working fine with amplify in OHIO server but I had to change the location to us-east-1 and now I cant get it to deploy on amplify

Need help. Urgent!

**Comment by Athena96** [comment]
Hi @Nirjhar100 just so I understand you:
1. created an app in us-east-2 (OHIO) and a code-commit repo in us-east-2 (OHIO)
2. created a new code-commit repo in us-east-1 (N. Virginia) and a new app in us-east-1 (N. Virginia)
3. then when you tried to build your us-east-1 app you received the cloning error you shared above
Is this correct?

Also when you set-up your 2nd app, what option below did you choose when connecting your CodeCommit repo?

![Screen Shot 2020-11-03 at 5 21 05 PM](https://user-images.githubusercontent.com/14256844/98058418-8035be00-1df9-11eb-9f9b-fbce0c02f3f7.png)
