### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by MoPE-hub** [aws-amplify/amplify-console#1159]
**App Id**: d3pljl87b0jjgu
**Region**: us-east-2
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by behrooziAWS** [comment]
This process can take up to 24 hours to complete.  Can you follow the troubleshooting steps [here](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#how-do-i-verify-that-my-cname-resolves) and report back if you still have issues?

**Comment by jparkhurst3** [comment]
Hi - I'm having a similar issue, I've been stuck in the SSL configuration stage for over 24 hours and I've double checked that the records match. Any pointers?

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
