### ISSUE TITLE
SSL verification is Failed - trying to connect route53 domain with my Amplify App

### ISSUE THREAD

**Issue by codermeisje** [aws-amplify/amplify-console#116]
**App Id**: d2023g0wui2kx4
**Region**: us-east-1
**Step**: SSL verification
**Status**: Failed

**Issue/question**
I am trying to connect my domain to an Amplify App. The domain is registered with the same account with Route53.

**Error message**
If there is an error message, please include it here. 
Error message: The status of this certificate request is "Failed". One or more domain names have failed DNS validation. Please check your domain name validation routes and try re-adding the custom domain to your app. Learn more: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-troubleshoot-guide

**Additional information**
I have tried following the instructions, and could not get it to work.
As a side note - this domain was previously associated with an Amplify App.  I disconnected it and when I tried to add it to another new app, I got these error messages.

**Comment by nimacks** [comment]
@coder-gurl , can you try to remove and re-add your domain to your app? It's very likely that the removal of your previous domain had not fully propagated which might explain the error message you received.

**Comment by garyleefight** [comment]
Hi, I checked your DNS. The error message is: One or more domain names have failed DNS validation. This is caused by misconfiguration with Route53. We are glad to help you if you give us more information.

**Comment by codermeisje** [comment]
@garyleefight - what other information should I provide you with?  I didn't configure it - I used amplify to set it up.  It worked the first time (months ago) - but when I removed the domain and added it to a new project, it gave me these errors.  If you could let me know what information you need from me - then I will get it for you.
Thanks!

**Comment by Joycehao19** [comment]
@codermeisje can you share a screenshot of what you're seeing in the Domain management page? Are you seeing any associated error? We're trying to root cause this.

**Comment by Joycehao19** [comment]
@codermeisje Hello, did you update the CNAME/ANAME/Nameserver on your domain provider? 

https://docs.aws.amazon.com/amplify/latest/userguide/howto-third-party-domains.html

**Comment by codermeisje** [comment]
@Joycehao19 - I'm not using a third party domain provider.  My domain is registered with AWS and route53

**Comment by Joycehao19** [comment]
@codermeisje can you post a screenshot of your Route53 Hosted Zone settings. If you aren't comfortable sharing that here, please email aws-amplify-customer@amazon.com

**Comment by codermeisje** [comment]
@Joycehao19 - I just sent the screenshot to the email address provided.

**Comment by swaminator** [comment]
@codermeisje were you able to get your domain connected?
