### ISSUE TITLE
SSL configuration is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by rajibganguly** [aws-amplify/amplify-console#1162]
**App Id**: d1d3pjzug73mv2
**Region**: us-east-2
**Step**: SSL configuration
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by gwryssekk** [comment]
Hi @rajibganguly -- I see that there is an SSL certificate attached to your app.  Are you still experiencing this issue?
