### ISSUE TITLE
Custom .otf font does not load when deploying with amplify through GitHub continuous deployments

### ISSUE THREAD

**Issue by OmarKhattab** [aws-amplify/amplify-console#1163]
** Please describe which feature you have a question about? **
Custom font gives an error in my developer console: "Failed to decode downloaded font"
(index):1 Failed to decode downloaded font: https://master.d3nkhrlzri10v1.amplifyapp.com/static/media/SofiaProRegular.bd0a6d0d.otf

** Provide additional details**
My custom fonts show up on localhost when developing my react application.

**Comment by swaminator** [comment]
@OmarKhattab do you have your SPA rewrite in place: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa

**Comment by OmarKhattab** [comment]
Just saw your comment thanks for referencing the aws docs that was the solution but I figured it out from another source.

**Comment by SaileshKumar** [comment]
@OmarKhattab hey there! I'm having trouble following the link - where did you add this redirect?

**Comment by straightupjac** [comment]
hi @OmarKhattab I am also having this issue, could you explain your solution to this issue?

**Comment by zmays** [comment]
There is a redirect section in amplify settings that auto makes a rule that does not include the .otf file extension. Edit it to add otf to the list:
<img width="1152" alt="Screen Shot 2022-04-14 at 3 37 58 PM" src="https://user-images.githubusercontent.com/4370615/163471572-5f49ebf8-2c53-4086-97c0-1556b5734aec.png">
