### ISSUE TITLE
Build Successfully but Deployment Failed without any error on console

### ISSUE THREAD

**Issue by rikhiljain** [aws-amplify/amplify-console#1165]
My app was being deployed perfectly from last few months but suddenly my app changes were stopped getting reflected. After investigation, I noticed that build and deploy steps are successful but the deploy step does not have any log other than below 2 lines. 

2020-10-25T05:48:41 [INFO]: Starting Deployment
2020-10-25T05:48:42 [INFO]: Updating Edge config

My APP ARN - arn:aws:amplify:ap-south-1:982296987390:apps/dfxy851mo7q6u

**Comment by gaurav-agarwal27** [comment]
I am facing the exact issue. I tried reconnecting my branch and now it shows default Amplify's `Welcome page`. Redeploying from the amplify console deploys the expected result.

**Comment by litwicki** [comment]
@rikhiljain @gaurav-agarwal27 are you still experiencing this?

**Comment by nicoalonsop** [comment]
@litwicki, today start happening to me.

**Comment by litwicki** [comment]
@nicoalonsop are you in us-east-1? We are investigating elevated error rates in this region this morning.

**Comment by nicoalonsop** [comment]
@litwicki Yes, I am. I see it some minutes ago, thanks!

**Comment by hloriana** [comment]
If this issue occurs again please feel-free to re-open.
