### ISSUE TITLE
Domain activation is Failed 

### ISSUE THREAD

**Issue by jericopulvera** [aws-amplify/amplify-console#1168]
**App Id**: dptgqyo1az3e7
**Region**: ap-southeast-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Domain activation failed.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
N/A

**Comment by gwryssekk** [comment]
Hi @jericopulvera --- can you check to make sure your cname is not used elsewhere?

**Comment by gwryssekk** [comment]
If you provide the domain you are trying to add, I can check.  Also, please have a look here:  https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

**Comment by jericopulvera** [comment]
Sorry forgot to close the issue. This has been fixed. It was connected to a different account CloudFront distribution since the domain is transferred from one account to another.
