### ISSUE TITLE
Domain activation is Failed

### ISSUE THREAD

**Issue by kazdegroot** [aws-amplify/amplify-console#1169]
**App Id**: dil6asd0qqbfk
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Domain activation failed, even though all chosen domains point to cloud flare.

**Error message**
If there is an error message, please include it here. 
**Note** One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by gwryssekk** [comment]
Hi @kazdegroot.  Can you verify that the CNAME you are attempting to add does not exist elsewhere?

If you provide the domain you are trying to add, I can check. Also, please have a look here: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

**Comment by kazdegroot** [comment]
Found that FAQ article a bit after I submitted this; associates the CNAME mention in the error with R53, not with cloud front.

Deleting the conflicting cloud front distribution, waiting 24 hours and retrying still gave this error, but deleting and re-adding the custom domain seems to have solved it.

Thanks!
