### ISSUE TITLE
Domain activation is Failed

### ISSUE THREAD

**Issue by daannijkamp** [aws-amplify/amplify-console#117]
**App Id**: d2xdzjxsgfm9x3
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

**Issue**
Domain activation does not work because it says it incorrectly that my DNS record that points to another CloudFront distribution. 

Steps:
- Because I did not have direct access to the DNS, it took a long time to add the records to the DNS.
- The verification process timed out.
- And because the Retry button never works, I had to delete the domain and add it again
- After 5 attempts I could finally delete the domain.
- I cannot activate the desired subdomain name at this time, because there is probably a distribution somewhere that is not cleaned up.
- I am 100% sure that there is not somewhere a CloudFront distribution on our side. 

**Error message**
One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution.  

**Additional information**
- My Amplify App should only run on a subdomain, not the root.

**Comment by daannijkamp** [comment]
@swaminator @nimacks What can I do best to resolve this? 
I have sent several emails to aws-amplify-customer@amazon.com , never received an answer
I created this issue on Github
I have waited as [mentioned](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error) more than 6 hours.
Do I have to purchase technical support from AWS? While the Amplify Console is clearly not working?

**Comment by nimacks** [comment]
@daannijkamp , Sorry for the delay in getting back to you. Your account has two custom domains attached to it. The first one is active and I can confirm that I was able to visit the site without issue. Your second custom domain however is having issues and returns the message `CNAMEAlreadyExistsException`. Can you confirm that you were looking to setup two different domains to point to the same app?

**Comment by daannijkamp** [comment]
That's correct.
**amplifyapp.our-company-name.com** 
(For testing and portfolio purposes, active and and is currently working)

**amplifyapp.customers-company-name.com**
(customer's production environment, not working and returns the CNAMEAlreadyExistsException)

Do you think two different domains for the same app is the issue?

**Comment by garyleefight** [comment]
Hi, I searched your domain CNAME record. Looks like it's already attached to a CloudFront distribution: d1cvpwo3qmpa4m.cloudfront.net.
You could use whatsmydns tool to see details. 
Link: https://www.whatsmydns.net/#CNAME/${Your custom domain}
Please delete the domain in that app first and try to attach it again.

**Comment by daannijkamp** [comment]
@nimacks @swaminator @garyleefight As far as I understand now, I have found the potential problem. Tip, maybe you can make the following sentence red. Instead of in font size of 8px and light gray.

> Please wait till your domain status becomes AVAILABLE before updating your DNS provider

**Comment by garyleefight** [comment]
@daannijkamp Glad you figured it out. I contacted with CloudFront team. You have a "dangling" DNS record that points to a distribution that doesn't exist in CloudFront in this case. This is the solution: 
`If your DNS record points to a distribution that is not the distribution that you are creating or modifying, then you can't add the alternate domain name to your distribution. In this scenario, you must update your DNS at your DNS provider before you can add the domain name for your CloudFront distribution.`
For further information:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/troubleshooting-distributions.html
https://docs.amazonaws.cn/en_us/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-remove-domain
https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-erro

**Comment by daannijkamp** [comment]
@garyleefight Thanks for your help!
Some extra information to improve the user experience:
If the verification process gets stuck and the retry button does not work again, the only option is to delete the domain and add it again.
When you do this, you will see the same old cloudfront domain with "View DNS". 
That is why I assumed that the cloudfront domain was not going to change.
