### ISSUE TITLE
Builds getting stuck in deploy

### ISSUE THREAD

**Issue by mads79** [aws-amplify/amplify-console#1172]
Our builds suddenly started getting stuck in deploy for one of our projects.
Nothing significantly changed in that project, and the other project we have works fine.
Cancelling and restarting doesn't work.
Stopping all builds in all projects and restarting them one at a time doesn't help.

See: https://eu-west-1.console.aws.amazon.com/amplify/home?region=eu-west-1#/dm197t2mo7xbv/feature-video-connection-saga/9

This is holding back an important production release for us, please advice.

**Comment by gwryssekk** [comment]
Hi @mads79.  Sorry you are experiencing this.  We are looking into the issue and will update here with findings.

**Comment by mads79** [comment]
We have been experimenting by connecting and disconnecting branches (so the link provided above is gone now, but the problem persists in the project.). Nothing seems to help.

I've noticed some things that might or might not be useful: 
When you are on the detail page of a build it proceeds all the way to verify, and it gets marked as succeeded in the user interface, so it looks like the whole process is successful. We signed up for email notifications on builds, and we also get a "succeeded" mail. When you go back to the "general" page for the project, the UI marks the deploy stage as "ongoing". 
When you press the branch title and go back to the build details, the green checkmarks from the deploy and verify steps are gone, and it looks like the build got stuck in deploy again.

The build still seems to count against the limit of ongoing builds, even if it seems to have actually completed (?).

This might be an indication that the everything is actually working, but it's just that the persistence of the deploy and verify step states that doesn't work? (which is still very serious since it makes things count against the limit of ongoing builds).

**Comment by mads79** [comment]
We also save the build number in a static file, so we can verify that the deploy step has actually completed successfully, even if it's not reflected in your system.

**Comment by mads79** [comment]
Any timeframe for a fix?

**Comment by litwicki** [comment]
@mads79 you've summarized this correctly. We do not have a timeline yet, but we will be estimating this fix and hope to have a better idea as late as Monday.

**Comment by mads79** [comment]
The problem seems to have resolved itself, hopefully it won't pop up again :crossed_fingers:

**Comment by litwicki** [comment]
@mads79 Glad to hear it; I'll close this but if anything happens in the future please don't hesitate to reopen a new issue!
