### ISSUE TITLE
PR previews not being created

### ISSUE THREAD

**Issue by eardenercruk** [aws-amplify/amplify-console#1173]
## Issue Description
PR previews are no longer being generated for new branches since yesterday. This appears to be intermittent though no preview detection settings have been changed and our branches are created in the same way.

Note: We also have issue #1134 open.

## Application Details
arn:aws:amplify:eu-west-2:145300272324:apps/d9slrnc36kbq7

**Comment by gwryssekk** [comment]
Hi @eardenercruk -- we are looking into this.  I'll update with any findings.

**Comment by gwryssekk** [comment]
Hello.  I am unable to reproduce this issue -- PRs for new branches are being generated for my app. Are PRs working for existing branches?

**Comment by eardenercruk** [comment]
Our PR previews are working again now and will continue to monitor. Not sure what resolved the issue but we have cleared out some old closed branches as per recommendation.

**Comment by axelkry** [comment]
@garyleefight @garyleefight Im having the same issue and I wonder if the root cause is the same... But could you clarify if the issue was that there were too many branches in the repo or that there were too many branches where PR previews were enabled?
