### ISSUE TITLE
Domain activation is Failed on re-try after fixing cloudfront DNS  records

### ISSUE THREAD

**Issue by swnuk** [aws-amplify/amplify-console#1174]
**App Id**: d13i6q9t6hsp92
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
due to SSL validation timeout we have had to recreate custom domains records in AWS amplify. The CNAME records for previous domains already existed in the domain records. We have fixed the cloudfron dns name in the domain but the re-try for Domain Activation keeps failing.
In both case of both branches the nslookup resolves to correct cloudfront distribution DNS.

**Error message**
"com.amazonaws.services.cloudfront.model.CNAMEAlreadyExistsException: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions (Service: AmazonCloudFront; Status Code: 409; Error Code: CNAMEAlreadyExists; Request ID: d9bab2ca-1bbb-492d-a641-3d2b51925a86; Proxy: null)"

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by gwryssekk** [comment]
Thanks for reporting this.  We will investigate.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
