### ISSUE TITLE
502 ERROR The request could not be satisfied.

### ISSUE THREAD

**Issue by agrant-intix** [aws-amplify/amplify-console#1176]
I connected my Next JS app a while ago and was consistently getting an index.html not found cloudfront error.

About two weeks ago (I don't have a specific date and time) I started seeing a new error as below.

The Lambda function result failed validation: The function tried to add, delete, or change a read-only header. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.

If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Generated by cloudfront (CloudFront)
Request ID: CXFiCqleliQeYDJs16MpL2JTGWwDfZBqkpfp6_ljIXRjmMHmaGvSoA==

**Comment by gwryssekk** [comment]
Hi @agrant-intix -- can you provide your app Id and region?

**Comment by agrant-intix** [comment]
region: ap-southeast-2
appId: d2c0j3a5mbuogw

**Comment by deboboy** [comment]
Getting same error as agrant-intix trying to deploy my Next JS app from the Amplify console.

The Lambda function result failed validation: The function tried to add, delete, or change a read-only header. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: jXie0UlDadx2Nj-ujBDBIsIF5UwPSDYTVvMrLYRHo9dZKWfgpYS5PA==

**Comment by Hayden-Neilson** [comment]
I have the same error with my react app when deploying with amplify too. This has been my issue for the last couple days it was fine on tuesday but then it started happening wednesday for me.

502 ERROR

The request could not be satisfied.

The Lambda function result failed validation: The function tried to add, delete, or change a read-only header. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)

**Comment by SuddalaSurajachary** [comment]
I am facing the same issue with my Vue JS application when deploying with amplify. This is the case from last 6 days since i set it up for the first time.

502 ERROR

The request could not be satisfied.

The Lambda function result failed validation: The function tried to add, delete, or change a read-only header. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: maE4pJa_dMVT_StrQYspYPoBDSs4Vsmb4MUdDe9rBedepdYXS08k9Q==

**Comment by johanlantz** [comment]
Same here, pushed an existing react app (frontend only) to amplify and got this error.

**Comment by jasona7** [comment]
Also experiencing this issue.  Local render works but get the error below after pushing a Vue.js SPA with redirect type 404 (Rewrite)

**502 ERROR
The request could not be satisfied.**
The Lambda function result failed validation: The function tried to add, delete, or change a read-only header. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Generated by cloudfront (CloudFront)
Request ID: 8z9bEBtT4EdEpUwW4VGssatN0FEnXxPtasGUfsnE0ZUfegzw2n1aRg==`

**Comment by bvirlet** [comment]
Same issue on our apps as well. 

Generated by cloudfront (CloudFront)
Request ID: 2FJCpsdZXrf3FBrGJg2tHpEYFCj-FlvBJ-8hsyabGXUQ5qmldCXypQ==

**Comment by evanlarkin10** [comment]
I am having the same issue

**Comment by stephensander1161** [comment]
me too, just trying to get my little app on amplify

Generated by cloudfront (CloudFront)
Request ID: d2u8bOwtRrnLEvsXSVieZSzhIH1KmizsGpYCCu2O-P8mzVLIdHOXHQ==

**Comment by pendurthi05** [comment]
me too getting same error message.
502 ERROR
The request could not be satisfied.
The Lambda function result failed validation: The function tried to add, delete, or change a read-only header. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: YG3O7igxJr2pY7MqzBSep3H2GNZmg5fvvsFfiwVoEPqnvcA7OapLDQ==

**Comment by roykingtree** [comment]
I had this same issue, but solved it by fixing my build settings on the amplify console (editing the amplify.yml file in console). You need to make sure your build command is included and your baseDirectory is correct. Here is an example of what the yml file should look like, though your specific build commands and baseDirectory location may differ: https://gridsome.org/docs/deploy-to-amplify/

**Comment by drptbl** [comment]
When it comes to next.js - actually, it seems that `npm run build` should also include `next export` command and that is the issue.

If your `npm run build` has only `next build`, it's not enough.
You have to make `npm run build` to be `next build && next export`.
Also remember that `next export` output destination is `out`, so you have to change your `baseDirectory` to `out` in this case (not `.next`).

**Comment by bvirlet** [comment]
Hello @aws-amplify-ops,

We've been having this problem for quite some time now. Is there some ETA on a fix?

Thanks!
Bruno

**Comment by roldanreno** [comment]
Hi

I'm still having this issue. Is there any workaround?

**Comment by bvirlet** [comment]
I found that we had the issue because we had a 404 Rewrite instead of a 404 Redirect: 

<img width="942" alt="image" src="https://user-images.githubusercontent.com/792706/100336779-dea82380-2fd6-11eb-963d-70b06344e822.png">

Are 404 Rewrite brokens?

**Comment by husain3** [comment]
I had this issue as well, but what I noticed was that when I was trying to build a new project it was looking for my source code one folder above where my project was located. 

Amplify looking at: 'swagger-webpage/<react-js-contents>'

My actual code located at: 'swagger-webpage/swagger-webpage/<react-js-contents>'

The reason why my code was located there was because I created a repo called 'swagger-webpage' and generated a react app called 'swagger-webpage/' thus 'swagger-webpage/swagger-webpage/<react-js-contents>'.

SOLUTION:
I just moved the react js contents one folder up, i.e. 'swagger-webpage/<react-js-contents>', pushed the changes to my repo, and created a new connection from my app to amplify (using the default autogenerated build settings). All was working afterwards.

**Comment by vcs222** [comment]
I had the same problem, and @drptbl's fix worked for me.

set the following in your package.json:
`  "scripts": {
      "build": "next build && next export" },
`
...and go to Build settings in apliffy console and update the following:
`    baseDirectory: out
`

**Comment by kahdojay** [comment]
Aside from the misconfigured baseDirectory, there is an issue with attempting to rewrite to nonexistent files returning an unhelpful 502, we're working on a fix that will return a proper 404 that should be out in the next few weeks. In the meantime those affected by this specific issue can avoid the issue by ensuring that the rewrite goes to an existing path.

**Comment by kahdojay** [comment]
We've deployed a change that will handle the above-mentioned situation then writing to nonexistent files as well as other relative rare edge cases.

If you're still experiencing this issue, please re-open this issue and provide appId, region, and a sample url to the app that produces the error.

**Comment by juangaimaro** [comment]
Same problem here: 

appId: d1utcvwrr6tg1q
region: us-west-1
url: https://develop.d1utcvwrr6tg1q.amplifyapp.com
url: dev.client.hokali.co
