### ISSUE TITLE
SSL Configuration -- still shows verify ownership

### ISSUE THREAD

**Issue by rlmmuthukumar** [aws-amplify/amplify-console#1177]
I have created hosting zones in route 53 and configured aws-amplify for moonmart.net of website hosting but still the ssl ceritifcate is not working and also the cname i created in hosting zones are not propagating.

**Comment by jparkhurst3** [comment]
I'm having the same issue - I've double checked that my records match and it's been stuck in the "SSL Configuration" stage for over 24 hours.

**Comment by gwryssekk** [comment]
Sorry that you are running into this.  Can you please provide provide the appId and region for all impacted apps?
