### ISSUE TITLE
Domain activation is Failed - One or more of the CNAMEs you provided are already associated with a different resource

### ISSUE THREAD

**Issue by wsh-startup** [aws-amplify/amplify-console#1179]
**App Id**: dv97k1v3h2snr
**Region**: ap-southeast-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
We had issues connecting your custom domain: wesoarhigh.com

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Trying to connect an Amplify hosted application as a subdomain served on Netlify.
Followed the steps found [here](https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-godaddy.html).

**Comment by gwryssekk** [comment]
Hi @wsh-startup -- This means that the CNAME you are attempting to add is associated with another cloudfront resource.  Check out the following: 

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error
https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

**Comment by wsh-startup** [comment]
Hi @gwryssekk,

We will be checking the links you provided.
However, just to give context and background to what our setup is currently, please see the details below.

1. Domain name is bought from GoDaddy.
2. Landing page (static web app) is hosted via Netlify. Pointed domain details from GoDaddy to our Netlify account.
3. Our Web app (dynamic web app) is hosted at AWS.

What we want to achieve is that our subdomain (ie. platform.wesoarhigh.com) will be accessible from Netlify pointing to a URL hosted at AWS.

Is this setup possible?

**Comment by nimacks** [comment]
Our records indicate you no longer have a custom domain associated with this app. Re-open if you're still having issues.
