### ISSUE TITLE
SSL verification is Failed - Retry is not working

### ISSUE THREAD

**Issue by iewil** [aws-amplify/amplify-console#118]
**App Id**: d2f944gwwd9d4d/d3ewmde6xmkt6i
**Region**: ap-southeast-1
**Step**: SSL verification
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
SSL Verification retry is not working for 2 new domains

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by iewil** [comment]
@swaminator is there anything that we can do on our end to fix this for now?

**Comment by garyleefight** [comment]
@iewil Hi, I have checked your records. You domain failed in DNS validation, which means you DNS provider config is not correct. Please follow our troubleshooting guide: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-troubleshoot-guide
