### ISSUE TITLE
Custom Domain stuck in SSL Configuration for over 24 hours

### ISSUE THREAD

**Issue by jparkhurst3** [aws-amplify/amplify-console#1181]
**App Id**: dkpjqhk7788eq
**Region**: us-east
**Step**: Domain Management - Custom Domain
**Status**: SSL Configuration

>**Note**: I've double checked that the records match, my domain is managed by Route53 and appeared immediately when starting the process. I've also looked through the domain management troubleshooting guide.

**Issue/question**
It's been in the "SSL Configuration" step for over 24 hours. Should I keep waiting or assume something is wrong at this point?

**Error message**
No error message given 

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
N/A

**Comment by gwryssekk** [comment]
Hi @jparkhurst3 -- sorry you're running into this.  We'll take a look.

**Comment by litwicki** [comment]
@jparkhurst3 are you still experiencing issues with this?

**Comment by jparkhurst3** [comment]
Apologies for the lack of response here - my github notifications here were going to my spam folder so I'm just now seeing this. I still haven't been able to resolve, but now I'm getting a different error "One or more of the CNAMEs you provided are already associated with a different resource".

**Comment by jparkhurst3** [comment]
My domain name is joannaparkhurst.com and is managed by Route53

**Comment by jparkhurst3** [comment]
And it's working now after following these instructions: **https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error**

Thanks for the follow up!
