### ISSUE TITLE
Domain activation is Failed - One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by braytonstafford** [aws-amplify/amplify-console#1182]
**App Id**: d3e3pao7vhudul
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Custom domain activation is failing with Amplify. The domain DNS is managed at Route53 and I do see the subdomains being created in Route53 but the activation is still failing.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
I've tried deleting the custom domain and then verifying the Route53 records have been removed and then reading the custom domain but I'm getting the same error.
Domain Validation Screen
![image](https://user-images.githubusercontent.com/8881975/97656990-ce804100-1a36-11eb-8315-6ee4fbe50257.png)

DNS Records Created by Adding Custom Domain are Highlighted
![image](https://user-images.githubusercontent.com/8881975/97657355-ab09c600-1a37-11eb-99fd-7f8d6c8a7cbb.png)

**Comment by gwryssekk** [comment]
Hi @braytonstafford.  Thanks for reporting this issue.  We'll look into it.

**Comment by nimacks** [comment]
The error message says `One or more of the CNAMEs you provided are already associated with a different resource.` 
Check that you don't have that domain associated with an existing CloudFront domain.
Refer to https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error

**Comment by braytonstafford** [comment]
Thank you, I did find an existing Route 53 entry that i removed and then reactivated the custom domain and its working. Thanks for your help
