### ISSUE TITLE
Domain activation is Failed - CNAME Associated with different resource

### ISSUE THREAD

**Issue by zachary822** [aws-amplify/amplify-console#1184]
**App Id**: d2otjtlll6rgqh
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**

The domain is originally used in another cloudfront distribution. I have since deleted it, changed DNS records, and trying to reuse it with amplify. 

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by gwryssekk** [comment]
Hi @zachary822 -- are you able to share the domain you are attempting to add?

**Comment by zachary822** [comment]
thoughtbank.app
