### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by vishnuku** [aws-amplify/amplify-console#1185]
**App Id**: d2cgvtc9k0znfy
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Not able to activate the custom domain purchased with godaddy

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
I have added route 53 DNS to go daddy account

**Comment by nimacks** [comment]
Refer to our documentation to troubleshoot domain setup.

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by nimacks** [comment]
@vishnuku are you still having issues?

**Comment by hsspain** [comment]
We are going to close this ticket.  Please let us know if you need further assistance.
