### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by alexcamerondev** [aws-amplify/amplify-console#1188]
**App Id**: d2s8z7iw0zcj4i
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
When trying to add my domain, it fails and provides the error message below. I have removed all CNAMEs that would be relevant to this domain as it was recently setup in cloudfront/s3 prior to attempting to move to amplify 

**Error message**
Next to useless error message: Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by nimacks** [comment]
Refer to our documentation to troubleshoot domain setup.

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by nimacks** [comment]
@alexcameron1992, Is this still an issue?

**Comment by alexcamerondev** [comment]
@nimacks no longer an issue but the error messages could still be much better in that scenario to prevent wasted time.

**Comment by nimacks** [comment]
@alexcamerondev Can you share some insights so we can make this experience better? What problems did you run into?
