### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by jsumande** [aws-amplify/amplify-console#1195]
**App Id**: dewf4h09nwfx3
**Region**: us-east-2
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by nimacks** [comment]
Refer to our documentation to troubleshoot domain setup. https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

Let us know if you're still facing issues.

**Comment by nimacks** [comment]
@jsumande are you still having issues?

**Comment by hsspain** [comment]
We are going to close this ticket.  Please let us know if you need further assistance.
