### ISSUE TITLE
Your app does not have a role and you're attempting to interact with AWS resources

### ISSUE THREAD

**Issue by tmwlsh** [aws-amplify/amplify-console#1196]
I'm following the ['Build a full stack react application' tutorial](https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/?e=gs2020&p=build-a-react-app-two), and when i get to the end of Module 3, and push my code, i am seeing the following error:

```
Your app does not have a role and you're attempting to interact with AWS resources
In order for you to interact with AWS resources you need to attach a role to your app. This can be done in the General Settings page in the console
```

When i click 'Fix This':
![image](https://user-images.githubusercontent.com/16941984/97920401-4f9a4980-1d51-11eb-8201-d22964fec628.png)

i'm taken to the app general settings, but under the service role drop down, there is no options?
![image](https://user-images.githubusercontent.com/16941984/97920442-5e80fc00-1d51-11eb-9335-1dc031782812.png)

Any help would be greatly appreciated!

Thanks!

**Comment by swaminator** [comment]
@tmwlsh Please follow this: https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html

**Comment by tmwlsh** [comment]
thanks @swaminator, can this be added to the tutorial?
