### ISSUE TITLE
Domain activation is Failed - CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by rz-robsn** [aws-amplify/amplify-console#1199]
**App Id**: d8lvf17uysti1
**Region**: ca-central-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I've been trying to point my custom domain to my amplify app instance with no success. Even after deleting the domain on amplify and recreating it several times following the steps outlined in the [guide](https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-godaddy.html), I systematically get the same error.

My domain is with godaddy.

**Error message**

![AWS Amplify Console 2020-11-03 17-29-02](https://user-images.githubusercontent.com/968239/98047598-313c5880-1dfa-11eb-9d8d-8161b79ef5e9.png)

**Additional information**
Here is my godaddy domain config, if it helps : 

![Domain Manager 2020-11-03 17-32-56](https://user-images.githubusercontent.com/968239/98047894-baec2600-1dfa-11eb-83a9-17fb2634d656.png)

Thanks for your help ! 

let me know if you have any questions.

**Comment by nimacks** [comment]
The error says that the CNAME you provided is already associated with a different CloudFront distribution. 

Refer to our documentation to troubleshoot domain setup. Can you verify that you haven't used the domain/subdomain with another Amplify app or CloudFront distribution?

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error

Let us know if you're still facing issues.

**Comment by rz-robsn** [comment]
Thank you Sam for taking a look,

The troubleshooting documentation is not particularly useful for me as I’ve never used Cloudfront and so I don’t have any cloud front distributions. Also I don’t have any other amplify project aside from this one (this is my first amplify app). However I used to have a different domain name that pointed to this app.

Additionally as I’ve mentioned in the issue description I deleted and recreated the domain in the “domain management” section of the amplify console several times, each time after which I update the CNAME records in my GoDaddy DNS configuration settings for that domain.

No luck so far :-( .

Any ideas what can be causing this issue ?

**Comment by nimacks** [comment]
@rz-robsn the domain www.ac********e.ca configured for the app `d8lvf17uysti1` works for me. Can you confirm that this works for you now?

**Comment by rz-robsn** [comment]
@nimacks 

Yes the domain works but only partially. I essentially have 2 issues that are believe are related to each other :

1. I still get "domain activation failed" error on my amplify console.
1. For some reason any network call to my app redirects to `/index.html`. This is not something that I set up on my app. This systematically happens even though I don't get such behavior when developing locally. If you go to my domain now, regardless of the url path, you'll get redirected to a `/index.html` location which displays a 404 page because my frontend code does not handle this url path. I tweaked my frontend code so that it redirects to my homepage (which has a `/dashboard` path) when the `/index.html` route is requested, but that workaround is not good enough as I need to be able to handles other urls other than `/dashboard` without redirecting, so I removed it recently.

The reason why I believe those issues are related was I didn't have this problem when another one of my domains used to point this app.

To give you a better picture of what's happening with the redirection issues, here is a demo gif showing the different requests/responses :

![ezgif-1-1c90d0312294](https://user-images.githubusercontent.com/968239/99450996-8cd50e80-28ef-11eb-8710-a2ebf2bcad78.gif)


Any ideas what's happening there ? Let me know if you need any more info. 

Thanks for taking a look !

**Comment by nimacks** [comment]
Our records indicate that your app no longer exists. Re-open if you are still having issues getting setup.
