### ISSUE TITLE
Ability to provide void value in env variable override

### ISSUE THREAD

**Issue by dmudro** [aws-amplify/amplify-console#1202]
I want to provide a void value for a particular environmental variable for a particular. This is not possible in Amplify Console UI because the value field is required:

![image](https://user-images.githubusercontent.com/1648143/98124767-e717ad80-1eb3-11eb-9b4e-c89b90489b4b.png)

What is the feasibility of providing a UI control to "nullify" the value in the override?

**Comment by Athena96** [comment]
Hi @dmudro yes, env variables require some value. Could you provide a value of "null" and treat that as null in your app code?
Can you also explain your use case and we can consider a feature request for this. Thanks!

**Comment by dmudro** [comment]
Yes the "null" workaround is pretty much what we are doing. It's not a real _null_ obviously but stringify'd as env vars are always strings.

The use case is feature toggling. Let's say I want to enable a particular feature based on a presence of an ENV VAR, such as `API_URL=https://api.example.com/v1` in all branches but master / production.

So now to disable the new api dependent feature in production I have to define `API_URL=null` override and then do string comparison `process.env.API_URL === null` down in the app. Kinda works, just not as elegant. On that note, it could be whatever arbitrary value, e. g. `API_URL=0` and then `process.env.API_URL === 0` or `parseInt(process.env.API.URL, 10)`.

Using standard env var mechanism without AWS Amplify Console I'd just set it to nothing:

```
API_URL=
```

I could also set up a brand new env var just to do the feature toggling but that's just adding more noise to already slightly cumbersome env vars management UI.

While this feature request asks for eventually considering allowing empty values, I don't think
removing the required check from the field is the best solution; perhaps something more explicit in the Actions dropdown or other UI control could do the trick. 

Or maybe the whole env vars management is ready for an overhaul ;)
