### ISSUE TITLE
SSL configuration is Running - Error message: One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by ericmick** [aws-amplify/amplify-console#1204]
**App Id**: d2rex0if3gt493
**Region**: us-west-2
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
How do I migrate a custom domain from a regular cloudfront distribution to amplify?

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
My domain (www.ablehandsrepair.com) is served through a cloudfront distribution.  I'm trying to migrate it to amplify.  I get this error even when I remove the Alternate Domain Names (CNAMEs) from the old cloudfront distribution, which causes an outage.

**Comment by nimacks** [comment]
Refer to our documentation to troubleshoot domain setup.

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by nimacks** [comment]
@ericmick are you still having issues?

**Comment by ericmick** [comment]
If I'm reading that guide correctly, I need to wait 1 or possibly up to 6 hours. Meanwhile, I can't use cloudfront to serve that domain, so I would either need to have an outage, or temporarily migrate to some other hosting solution. Seems like something that ought to be documented or worked around.
