### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by tim-giblin** [aws-amplify/amplify-console#1208]
**App Id**: dxku4vtlhfebq
**Region**: eu-west-2
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Has been stuck on SSL configuration for over 24 hours. The SSL didn't renew so I removed the domain and re-added it but now the SSL won't configure.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Domain is in Route 53. SSL creation adds the records automatically and I've double checked that they are correct. Name servers are set to the Route 53 hosted zone.

**Comment by nimacks** [comment]
Can you provide more information regarding how the SSL didn't renew?

**Comment by tim-giblin** [comment]
The SSL had expired for a few days, I couldn't see a way of renewing it within AWS Amplify, I thought that it would do it automatically. As I couldn't find anything I removed the domain and re-added it from the App.

**Comment by nimacks** [comment]
Did re-adding the domain resolve your issue?

**Comment by tim-giblin** [comment]
No, it just hangs on SSL Configuration. It's been configuring for a few days now. I've tried it multiple times. I've even created a new app and added the domain to that to see if it works and that didn't do anything either.

**Comment by nimacks** [comment]
Looks like you got this working with a different app with Id: _d2beveju1oigg4.

**Comment by tim-giblin** [comment]
Yeah, the SSL configuration finally failed. I then re-added the domain and it worked.
