### ISSUE TITLE
Files with no extension are not working

### ISSUE THREAD

**Issue by janicduplessis** [aws-amplify/amplify-console#1209]
I'm trying to upload a `apple-app-site-association` file which needs to be at `/.well-known/apple-app-site-association` but instead of returning the file content it redirects to `/.well-known/apple-app-site-association/` and 404s. I have another file in the same directory with a .txt extension and it works properly.

App arn: arn:aws:amplify:us-west-2:087361454497:apps/dcfixisztquqr 

Problematic file: https://www.th3rdwave.coffee/.well-known/apple-app-site-association

Working file: https://www.th3rdwave.coffee/.well-known/apple-developer-domain-association.txt

**Comment by kulikala** [comment]
This happens to me too.

It seems "Trailing slashes and clean URLs" having troubles.
https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#trailing-slashes-and-clean-urls

| User inputs in browser | Expected redirects | Actual redirects |
|------------------------|--------------------|-----------------|
| `/about (when about.html returns 404)` | `/about/` | `/0000000001/about` |

`0000000001` is the branch's buildId.
If the build number is 2, the redirected URL become `/0000000002/about`.

**Comment by hdb** [comment]
I'm experiencing the same issue for urls without trailing slashes but strangely only for branches that contain a backslash in the branch name.

**Comment by saurabhj** [comment]
Experiencing the exact same issue as reported here: https://github.com/aws-amplify/amplify-console/issues/1209#issuecomment-723909578

**Comment by hsspain** [comment]
We are currently working to fix this issue and will provide an update as soon as we have one.

**Comment by janicduplessis** [comment]
@hsspain Awesome, any updates?

**Comment by hsspain** [comment]
@janicduplessis We do not have any updates yet, but will shortly.

**Comment by kahdojay** [comment]
We're working on a fix that should be deployed to all regions in the coming weeks

**Comment by kahdojay** [comment]
@janicduplessis  can you deploy `apple-app-site-association` to your site root and include the following custom rule:

```
[
    {
        "source": "/.well-known/apple-app-site-association",
        "target": "/apple-app-site-association",
        "status": "200",
        "condition": null
    }
]
```

and let us know if it gets served properly

**Comment by kahdojay** [comment]
Closing this for now, but please feel free to reopen if the above doesn't work.

**Comment by janicduplessis** [comment]
Thanks @kahdojay I can confirm it works.

**Comment by mobartapp** [comment]
> @janicduplessis can you deploy `apple-app-site-association` to your site root and include the following custom rule:
> 
> ```
> [
>     {
>         "source": "/.well-known/apple-app-site-association",
>         "target": "/apple-app-site-association",
>         "status": "200",
>         "condition": null
>     }
> ]
> ```
> 
> and let us know if it gets served properly

Where include this file and what the type of file ?

**Comment by Selenestica** [comment]
> @janicduplessis can you deploy `apple-app-site-association` to your site root and include the following custom rule:
> 
> ```
> [
>     {
>         "source": "/.well-known/apple-app-site-association",
>         "target": "/apple-app-site-association",
>         "status": "200",
>         "condition": null
>     }
> ]
> ```
> 
> and let us know if it gets served properly

Pardon the noob question, but where do we put this custom rule?

**Comment by rdoamaralsoares** [comment]
I have tried that solution, but in my case the error changed to ERR_TO_MANY_REDIRECTS

**Comment by angusho1** [comment]
I haven't been able to get this working. My rewrite rule is exactly as shown above and my `apple-app-site-association` file is in the root of my repository.

**Comment by tomharvey** [comment]
@Selenestica - Took me a minute too, thought I needed some amplify.json config file in my app. But it's all just done in the AWS console for the Amplify App.

Go to your Amplify Console, choose your app and go to App Settings > Rewrites and redirects.

Once you select "edit" you can add a new rule (to the top) as in the screenshot, or click on the "Open Text Editor" button at the top right to enter this with a JSON blob as described in the comment.

<img width="1999" alt="Screenshot 2021-11-30 at 21 52 48" src="https://user-images.githubusercontent.com/199734/144126423-4d6b852b-6bd0-44d6-9766-d40ce77aa6ed.png">

**Comment by Selenestica** [comment]
@tomharvey Thank you! I'll give this a shot as soon as I can.

**Comment by rvaneijk** [comment]
It worked for me.

Two remarks:

1. I had to redirect to a .txt instead of the file without an extension. Redirect
2. The order matters. The new roles should come first.

Below a screenshot of a related problem (setting up OpenPGP Web Key Directory WKD)

![image](https://user-images.githubusercontent.com/934041/147510776-638966a5-fabb-43ab-bacf-5f3ba3ef0fc7.png)
