### ISSUE TITLE
Custom domain: subdomains limit

### ISSUE THREAD

**Issue by matsuihidetoshi** [aws-amplify/amplify-console#1210]
** Please describe which feature you have a question about? **
- I built Nuxt.js application, and deployed it on AWS Amplify Console.
- I wanted to add subdomains which connect to the same application.
- I could do this, but I don't know the maximum number of subdomains.

** Provide additional details**
- I want to know if there is a limit of number of subdomains, or not.
- And if so, I want to know the maximum number of subdomains.
- And also want this document to be added descriptions about the limit.

**Comment by matsuihidetoshi** [comment]
## Maybe this records quota relates about this issue.
https://docs.aws.amazon.com/general/latest/gr/r53.html

**Comment by nimacks** [comment]
Refer to this document for limit information : https://docs.aws.amazon.com/general/latest/gr/amplify.html

**Comment by matsuihidetoshi** [comment]
@nimacks Thank you! I just wanted this information.
