### ISSUE TITLE
How to fire a post deploy onSuccess notification?

### ISSUE THREAD

**Issue by dmudro** [aws-amplify/amplify-console#1212]
Is there mechanism in AWS Amplify Console to trigger a custom action after the deployment is successful?

For example I want to fire a webhook notification after the deployment has been successfully completed.

I see 3 phases in the build section - `prebuild`, `build`, `postbuild`: https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html

I am after a `postDeploy`

**Comment by nimacks** [comment]
We currently do not have a postDeploy phase. However, I can provide an alternative approach.

### 1. Setup an email notification in the console

![image](https://user-images.githubusercontent.com/4107271/98737815-a27c8e00-235b-11eb-80ef-9c9f917b3e0e.png)

### 2. In your AWS account, Go to EventBridge. You'll see an eventbridge email rule created for your app.
![image](https://user-images.githubusercontent.com/4107271/98738025-f25b5500-235b-11eb-95fb-45d1dff668f1.png)

### 3. Add a new target (Lambda function to fire a webhook notification) to the rule.
![image](https://user-images.githubusercontent.com/4107271/98738246-4403df80-235c-11eb-996f-f3dc4d8382f9.png)

**Comment by nimacks** [comment]
Re-open if you need further information.
