### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by bjohn96i** [aws-amplify/amplify-console#1213]
**App Id**: d1m7hh10wmthal
**Region**: us-east-2
**Step**: SSL configuration
**Status**: Running

**Comment by nimacks** [comment]
Can you provide more details about what the issue here is? Is your custom domain hosted is Route53 or is it hosted in a 3rd party DNS provider?

**Comment by nimacks** [comment]
Refer to our documentation to troubleshoot domain setup. 

- https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
- https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error

Let us know if you're still facing issues.

**Comment by nimacks** [comment]
@bjohn96i are you still facing issues?

**Comment by bjohn96i** [comment]
No, thank you!
