### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by jhortale** [aws-amplify/amplify-console#1214]
**App Id**: dfgmxft5n21w7
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Why I cannot assign a custom sub domain to AWS Amplify?

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by nimacks** [comment]
Refer to our documentation to troubleshoot domain setup. 

- https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
- https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error

Let us know if you're still facing issues.

**Comment by jhortale** [comment]
Worked Thanks, there was a wildcard *.domainname.com and I just removed
