### ISSUE TITLE
No way to add customHttp.yml to AWS::Amplify::App CloudFormation

### ISSUE THREAD

**Issue by Alk3m1st** [aws-amplify/amplify-console#1218]
** Please describe which feature you have a question about? **
I've been using CloudFormation to automate the creation of Amplify Apps and with the recent change of shifting Custom headers out of the amplify.yml file and into customHttp.yml I wanted to find out how this can be done through CloudFormation now?

** Provide additional details**
There is a BuildSpec param currently documented here - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-app.html
There does not appear to be an equivalent CustomHttp param (or similar)

Apologies with this should be in another repository, I wasn't sure where the related CloudFormation repository lives.

**Comment by kahdojay** [comment]
Hi @Alk3m1st we'll be rolling out CloudFormation support for the new customHeaders field on the App resource in the next week, and the docs will be updated to reflect the new property.

**Comment by Alk3m1st** [comment]
Thanks @kahdojay looking forward to it.

**Comment by kahdojay** [comment]
@Alk3m1st https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-app.html

**Comment by Alk3m1st** [comment]
Just to add to finally, it would be useful to have an example in the CloudFormation documentation. It took some time and failed attempts to figure out that I needed to keep `customHeaders:` in the `CustomHeaders:` CFN property. I initially assumed it could be just the `- pattern:` if that makes sense.
