### ISSUE TITLE
Deployment failed! when running amplify publish

### ISSUE THREAD

**Issue by Arocmd17** [aws-amplify/amplify-console#1227]
** Please describe which feature you have a question about? **

** Provide additional details**
I have already published my app on amplify. Then I added some features and publish it but it is showing Deployment failed

ile sizes after gzip:

  224.68 KB  build\static\js\2.7dce62c6.chunk.js
  3.67 KB    build\static\js\main.7ef4b260.chunk.js
  1.4 KB     build\static\js\3.3f972b83.chunk.js
  1.17 KB    build\static\js\runtime-main.80fd4dbd.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

√ Zipping artifacts completed.
× Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
An error occurred during the publish operation

**Comment by nimacks** [comment]
@Arocmd17 , can you provide an appId?

**Comment by kahdojay** [comment]
@Arocmd17 in addition to appId can you provide the affected branch and example job number?

**Comment by hsspain** [comment]
We are going to close this ticket.  Please let us know if you need further assistance.
