### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by blackdevil22** [aws-amplify/amplify-console#1229]
**App Id**: dq2wes1kgdd48
**Region**: eu-central-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by nimacks** [comment]
Refer to our documentation to troubleshoot domain setup.

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by blackdevil22** [comment]
Hi. This domain:
is a fresh ( new )
not have record in route 53 ( except SOA and NS)

Error:
![image](https://user-images.githubusercontent.com/33642262/99309581-fa366000-2859-11eb-8813-18580e78eeb1.png)

**Comment by kahdojay** [comment]
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

These guides are helpful for getting started with custom domains, for existing domains there are number of steps that will need to be completed (as outlined in the docs above) depending on your current hosting and DNS providers.

A CNAME alias (mydomain.com, sub.mydomain.com) can only be associated with a single CloudFront distribution at a time, if you receive this error then the domain is already associated with another CF distribution (either within the same AWS account, or potentially in a different account) and must be disassociated from the previous distribution before the distribution created for you by Amplify Console will work, the docs help outline how to do this (and you may need to check more than one account if you or your organization owns multiple accounts)

Additionally, if you manage your domain through Route53, make sure to clean up any hosted zone CNAME or ALIAS records that point to the old distribution. After completing the above, I would remove the domain from Amplify Console and start the flow over.

For additional troubleshooting:

What this means: One of the hostnames you tried to connect (could be a subdomain, or the apex) is already deployed to a Cloudfront distribution.

How to fix this:

    Is this domain connected to a different Amplify App that you own? If so, make sure you are not trying to reuse one of the hostnames.
        If you are using www.domain.com on the other app, you cannot use www.domain.com on this app
        You can use other hostnames, like blog.domain.com
    If you had this domain successfully connected to Amplify and then recently (within the last hour) deleted it, please wait and try again.
    Check the Cloudfront console to see if you have this domain deployed to any distributions
    If you are positive no CloudFront distribution exists (including in other accounts) using this domain, and only if it would not be disruptive to any currently running services, try deleting and recreating the hosted zone

**Comment by hsspain** [comment]
We are going to close this ticket.  Please let us know if you need further assistance.
