### ISSUE TITLE
Can't create a project if the branch name contains "#"

### ISSUE THREAD

**Issue by mooser** [aws-amplify/amplify-console#123]
Amplify Console fails spectacularly if branch name includes a hash prefix (Ex: "#branch-name")

The most annoying part of this bug is the error message:

> There was an error detecting your build settings.
> undefined

To reproduce: 
1. Make a branch named "#whatever" in your project.
2. Try to connect that branch to a new project in Amplify Console
3. Feel pain

**Comment by swaminator** [comment]
@mooser we are aware of this and its due to the way we issue subdomains. Is this a blocker for you to continue?

**Comment by mooser** [comment]
@swaminator Thanks.  It's not blocking.
