### ISSUE TITLE
Blank screen after deployment

### ISSUE THREAD

**Issue by nathanqueija** [aws-amplify/amplify-console#1234]
Hi there,

Since this morning every new deployment of my app results in a blank screen.
All the stages succeed in Provision, Backend, Frontend, and deployment, but the result is a blank screen.
I see that the application is loading somehow because I see some API calls being sent, but other than that there is just a blank screen.
It was working normally and I didn't change anything in the build pipeline. I saw some tickets in the repo and on amplify-js as well about this issue, but none of the suggestions seemed to work for me.
Is this something known or are there any workarounds around it?

Thanks

**Comment by nimacks** [comment]
@nathanqueija  Can you provide an appId? Also, can you confirm that you didn't make any changes to code?

**Comment by nathanqueija** [comment]
I did some minor changes to the code that shouldn't cause any crashes. I tested them locally. They are really small so I don't see why this would cause this only after deployment. The app id is d21wf9h30kgumj

**Comment by kahdojay** [comment]
Hi @nathanqueija I looked through our logs and your builds/deploys seem to be working fine but when I visit both your staging and prod endpoints in the network tab I also see 200s for the js files but repeated 401s for requests being made to your api endpoint. It seems like something in your frontend code might be failing auth against your api and possibly preventing the rest of the js to execute?

**Comment by nathanqueija** [comment]
This api call fails on local env as well it was happening before the last deploys become blank, it's normal as it will be tried again. Locally it is tried again and then the app continues normally, even before failing I can see the application running locally. What is weird for me is that I can't see anything at all on the screen and it happens only on amplify deployment. I tried to upload the same build folder to another server and it works just fine.

**Comment by nathanqueija** [comment]
I tried three more times and now it works. 🤷🏼‍♂️ I'll close the issue as I don't quite understand yet where the problem is. I'll come back if I find the root.
