### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by thusnani** [aws-amplify/amplify-console#1235]
**App Id**: d2n2k94r3psfx7
**Region**: ca-central-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by kahdojay** [comment]
Hi, can you provide some more details and let us know which steps in the troubleshooting guide you've followed: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

**Comment by thusnani** [comment]
![image](https://user-images.githubusercontent.com/56053494/99429723-6060c880-28d6-11eb-98e0-efb6106250af.png)

**Comment by thusnani** [comment]
I get a problem that is not listed in that troubleshooting guide.
