### ISSUE TITLE
Amplify CLI rejecting build since CLI update

### ISSUE THREAD

**Issue by drclohite** [aws-amplify/amplify-console#1239]
Hi I have a customer live deployment prod and a dev. I upload to dev first to spot bugs, test etc. I write code and test first on my PC. I currently have a live prod and my pc, machine versions are different although both work fine. The dev works to a level uploaded about 10 days ago.

I have had occasional errors in the past where it did not like the code, that was a long time ago and the error message said on what file so I could fix it. Always minor issues easily remedied. 

The current error says it can find dev and successfully adds environment. Then says it is initialising then says there is a node error then says dev not found. I searched for this and found it to be an out of date node issue. I upgraded Node my end and all still works fine, although the same error when uploaded via github to the console persists. 

I saw someone else had this error and the advice suggested that I update the stack. I did that and it has drifted in two areas. I don't know how to fix the drifts. The error continues to persist. I did strip out all the changes to a version when it was pre the cli update and tried to upload that, to no avail. 

This is a live situation. I have live data and lambdas hanging off the app. I am on the edge of desperation. Clients are going to expect updates and I have new content to post, webinar video edits, and training for clients. 

I could set up another environment and potentially start from scratch this I think would lose me weeks and this makes it an expensive proposition. I could create a new environment just for the new videos. If I did this I am certain my clients (IT directors) would think the systems I am using are unreliable, which is what this event proves unfortunately if I cannot fix this easily and fast. 
[log (82).txt](https://github.com/aws-amplify/amplify-console/files/5556470/log.82.txt)

**Comment by kahdojay** [comment]
we're investigating, potentially related to https://github.com/aws-amplify/amplify-cli/issues/5862

**Comment by drclohite** [comment]
This may be of use. I am using amplify to run as dev on my pc, it is working with the data on AWS dynamoDb for sure. I changed the structure of my table and that operated correctly. There is no advice to upgrade anything. The only thing, and obviously critical thing that does not work is when I upload my source code to github. Github triggers amplify and then Amplify tries to install the code and fails.

**Comment by drclohite** [comment]
support is great when support is provided. Why is no one providing any useful support?

**Comment by drclohite** [comment]
I decided to run Amplify to see if there had been a cli update. There had been so I ran it, then tried to upload my files again. I got a different error, this time claiming a file was missing, report attached. I also found the file that was missing in place as expected. Also attached. 

[log (83).txt](https://github.com/aws-amplify/amplify-console/files/5598616/log.83.txt)
[local-env-info.txt](https://github.com/aws-amplify/amplify-console/files/5598622/local-env-info.txt)
had to convert the json to a text file for it to upload here.

**Comment by kahdojay** [comment]
looks like an issue with the latest amplify cli version - please see this thread for workaround and to track the fix:

https://github.com/aws-amplify/amplify-cli/issues/5931

closing this issue in favor of that thread, please report in that thread if the downgrade workaround doesn't resolve your issue
