### ISSUE TITLE
Amplify not getting deployed, stuck in some loop by detecting changes on its own.

### ISSUE THREAD

**Issue by poojakota17** [aws-amplify/amplify-console#1240]
I changed the build settings for backend and did redeploy this version. It got stuck somewhere, not even showing the progress bar of provision ,build and all. Continously detecting some undefined branch also and then changes to original branch and this loop is going on.

**Comment by kahdojay** [comment]
@poojakota17 can you share more details using our [bug report issue template](https://github.com/aws-amplify/amplify-console/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)? Apologies it wasn't in the issue template set of options, we'll fix that as well.

**Comment by behrooziAWS** [comment]
Closing due to missing app details.
