### ISSUE TITLE
Webhooks broken and SSL cert invalid in eu-west-2

### ISSUE THREAD

**Issue by joshm91** [aws-amplify/amplify-console#1241]
Hi,

The SSL certificate used for https://webhooks.amplify.eu-west-2.amazonaws.com appears to be invalid meaning I have to pass a `--insecure` flag to curl in order to post to the webhook. This obviously isn't ideal and seems to be an error since the webhook url for us-east-1 looks to be correct.

**Comment by joshm91** [comment]
In fact, POSTing to the webhook url displayed in the amplify console doesn't seem to work at all and returns this content:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Bad request.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: Bp4JlvjiAEK1VZD_nL4-Cabli2XTGUvrwvMp0WkQvV60lt5c-scvTw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**Comment by kahdojay** [comment]
Hi, thanks for reporting - we've pushed a fix and this should work now. Please re-open if you're still seeing issues.

**Comment by toroberts** [comment]
Thanks - will do.

Tom Roberts
Head of Digital Studio
t.roberts@dewynters.com<mailto:t.roberts@dewynters.com>

On 18 Nov 2020, at 21:23, Don J. Kahn <notifications@github.com> wrote:

﻿

Hi, thanks for reporting - we've pushed a fix and this should work now. Please re-open if you're still seeing issues.

**Comment by joshm91** [comment]
Great, thanks!
