### ISSUE TITLE
Domain activation is Failed - 2 Subdomains with the same error

### ISSUE THREAD

**Issue by florina-chesaru** [aws-amplify/amplify-console#1242]
**App Id**: d1ssmf0dotutno
**Region**: eu-central-1
**Step**: Domain activation
**Status**: Failed

**Issue**
I have 2 subdomains for 2 applications in Amplify: 

> x.bla.domain.com
> y.bla.domain.com

For these subdomains the CNAMEs have been added and the SSL configuration works, but the 3 step "Domain activation" is failing.

**Error message**
Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: The status of this certificate request is "Failed". One or more domain names have failed validation due to a Certificate Authority Authentication error. Learn more: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-caa.html

**Additional information**
I was configuring both subdomain only in Amplify. The main domain comes from a 3rd Party. The CNAMEs have been checked with an online tool and they are set up correctly. 
The CAA is set to: 

> issue "amazon.com"

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by brnmye** [comment]
We are going to close out this issue, but please feel free to re-open if you still need help.
