### ISSUE TITLE
Redeploy this version button not available in monorepo

### ISSUE THREAD

**Issue by dmudro** [aws-amplify/amplify-console#1247]
**Is your feature request related to a problem? Please describe.**
I am not able to rollback the application in a monorepo - the redeploy button is gone when I set appRoot in the yml config.

**Describe the solution you'd like**
Parity with non-monorepo application, i. e. the redeploy button should be visible:

![image](https://user-images.githubusercontent.com/1648143/99718739-a15e0600-2aab-11eb-8095-64ea1544f765.png)

**Additional context**
In addition the _Redeploy this version_ copy is slightly misleading as it **builds** and deploys from the given commit so perhaps it should be called something like _Rebuild and deploy this version_

**Comment by k-vamshi** [comment]
I am facing the same problem

**Comment by louisandkatherine** [comment]
Any update on this?

**Comment by k-vamshi** [comment]
- I guess there may be some temporary problem as the **monorepo** support has been recently introduced.
- I managed to build the applications by cd navigation into and out of the base location as the **yml** as a normal application.
- Maybe we shall expect an update from the **AWS** PM anytime sooner.

**Comment by khola** [comment]
Any update on this?

**Comment by dmudro** [comment]
While other new functionality has been added to Amplify Console, this piece is still broken.

Even worse, you can't trigger the build via webhook, see https://github.com/aws-amplify/amplify-console/issues/1140

Basically there is no easy way to roll back. As a result sadly we are considering leaving Amplify despite having all our infrastructure on AWS.

**Comment by khola** [comment]
I just went with `cd UI` in my job script but feels clumsy tbh.

**Comment by jasonrundell** [comment]
Can confirm also running into this issue currently. Once I add `appRoot: pro` to the amplify build settings, the button to redeploy disappears.

**Comment by mvsantos013** [comment]
+1

**Comment by JDHalm** [comment]
Also running into this bug

**Comment by nimacks** [comment]
We are aware of this issue and are working on a fix.

**Comment by victorccccc** [comment]
Hi, We've updated the monorepo feature, and you can see `Redeploy this version` button for Monorepo Apps now
