### ISSUE TITLE
Monorepo config best practice

### ISSUE THREAD

**Issue by dmudro** [aws-amplify/amplify-console#1248]
How should I structure the amplify.yml given I have two applications in my mono repo:
- should I provide one large amplify.yml with two appRoots as [described here ](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#monorepo-configuration)and mentioned in this [official guide](https://aws.amazon.com/blogs/mobile/set-up-continuous-deployment-and-hosting-for-a-monorepo-with-aws-amplify-console/)
- or should I split it and put one amplify.yml in each appRoot?

Amplify Console seems getting confused if I provide all appRoots in one file. It literally just broke our production.

In addition **does the yml file the console UI override the .yml checked in the source code**? It seems that the console does indeed take over the source.

**Comment by dmudro** [comment]
Just reading someone else's comment on https://aws.amazon.com/blogs/mobile/set-up-continuous-deployment-and-hosting-for-a-monorepo-with-aws-amplify-console/

_This doesn't work, we have two unique approots defined and it just deploys whichever is listed first, twice_

Please confirm and fix the docs.

**Comment by nkashyap** [comment]
@swaminator  It looks like the above article was written by you. please can you confirm if it used to work as mentioned in the article.

**Comment by dmudro** [comment]
Also the **slash** in appRoot as per doc does not seem to work, must be `package-a` and NOT `/package-a` in my experience: 

```
version: 1
applications:
 appRoot: /package-a # this will fail the build with 'No appRoot found'
  - frontend:
  ...
```

Please confirm.

**Comment by victorccccc** [comment]
Hi, we've updated Monorepo feature and you can specify `appRoot` via `AMPLIFY_MONOREPO_APP_ROOT` environment variable

Docs for reference: https://docs.aws.amazon.com/amplify/latest/userguide/monorepo-configuration.html

Feel free to reopen this if issue persists

**Comment by ryandagg** [comment]
> Hi, we've updated Monorepo feature and you can specify `appRoot` via `AMPLIFY_MONOREPO_APP_ROOT` environment variable
> 
> Docs for reference: https://docs.aws.amazon.com/amplify/latest/userguide/monorepo-configuration.html
> 
> Feel free to reopen this if issue persists

The documentation leads to a yml validation error in Amplify console. Please update the documentation.
