### ISSUE TITLE
Domain activation is Failed - Cloudfront alias error

### ISSUE THREAD

**Issue by bobhy** [aws-amplify/amplify-console#1251]
**App Id**: d163eh18wxq7or
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Issue seems to be the cloudfront alias for my app, and I'm not sure about the CNAME for blog.bobhy.com.  
The cloudfront distribution number changes each time I retry the registration process, and I can only see the DNS records *while* the process is running (if I look under `Actions`).  Once it fails and I get the error, the `dns records` link is disabled, as shown below:

![image](https://user-images.githubusercontent.com/1971300/99775357-06255a80-2ac4-11eb-9901-49ad89fcc288.png)

**Error message**
If there is an error message, please include it here. 
`Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions`

**Additional information**
*** DNS info for custom domain bobhy.com at Google Domains:
[removed]

*** CAA info

**Comment by kahdojay** [comment]
Hi, you'll need to first remove the CNAME and wait at least the duration of your ttl (1h in this case, and likely longer to be safe) before retrying otherwise that record will not have yet expired from DNS caches and CloudFront will return that error.
