### ISSUE TITLE
SSL configuration is Running - Stuck in SLL Configuration

### ISSUE THREAD

**Issue by sergiucurea** [aws-amplify/amplify-console#1252]
Hello, I have an app hosted on aws amplify with a custom domain, and the ssl certificate recently expired, I have reconfigured the custom domain in the domain management but it is stuck more than 8 hours in the "SLL configuration" step.

The message displayed reads as follows:

"We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue in our GitHub issue tracker."

**Comment by kahdojay** [comment]
@sergiucurea can you share the appid and region?

**Comment by kahdojay** [comment]
closing in favor of https://github.com/aws-amplify/amplify-console/issues/1254
