### ISSUE TITLE
SSL configuration is Running - Stuck in SSL Configuration

### ISSUE THREAD

**Issue by sergiucurea** [aws-amplify/amplify-console#1254]
**App Id**: d302bkns913825
**Region**: us-east-2
**Step**: SSL configuration
**Status**: Running

**Issue/question**
I have configured a custom domain for the an amplify hosted app, but the process is stuck on the SSL verification of domain ownership and doesn't move forward for more than 8 hours. The DNS Management is done by Route 53 and the process should not stall here.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by brnmye** [comment]
We are going to close out this issue, but please feel free to re-open if you still need help.
