### ISSUE TITLE
Pull Rate Limit Hit even after 12 hour break

### ISSUE THREAD

**Issue by jstanley70** [aws-amplify/amplify-console#1255]
**Describe the bug**
We keep running into the pull rate limit for pulling docker containers. Today it has become unmanageable.

**To Reproduce**
1. Set up for auto deploy of a env.
2. Deploy it, previously was not an issue but is now seemingly locked completely
[BUILD_CONTAINER_UNABLE_TO_PULL_IMAGE: Unable to pull customer's container image. CannotPullContainerError: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit]

To be a bit more clear:
last build was last night:11/19/2020, 8:46:51 PM
next attempt: 11/20/2020, 8:22:57 AM

error: You have reached your pull rate limit both times

**Expected behavior**
We expect the build to be able to provisioN

While aws amplify is updating to a private repo, is it possible that we can sign up with Docker to eliminate this error. I am unsure from the instructions I've been able to find how we would do this for an AWS account.

**Comment by kahdojay** [comment]
@jstanley70 can you provide your appid, region, and example job number?

**Comment by djensen47** [comment]
What fix? Nothing has happened for 3 months.

**Comment by jstanley70** [comment]
So the work around is to create your own private Amazon Elastic Container Service (ECS) and docker repo. It seems a bit excessive for the amplify target market but it works fine.
