### ISSUE TITLE
'amplify publish': An error occurred during the publish operation

### ISSUE THREAD

**Issue by kjaunslavietis** [aws-amplify/amplify-console#1259]
**Describe the bug**
On 'amplify publish' getting the following output:

> √ Zipping artifacts completed.
> × Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
> An error occurred during the publish operation

Meanwhile the automated build from github succeeds just fine.

**To Reproduce**
1. Run 'amplify publish'

**Expected behavior**
'amplify publish' works

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
App ID: d20qjn0cqfpz84
Region: eu-central-1
App frontend is React.

**Comment by joebernard** [comment]
Having the same problem. I was only able to work around it by creating a new environment connected to my GitHub branch and deploying that way. `amplify publish` doesn't work.

**Comment by ganipcanot** [comment]
Resolving due to age - please re-open if you are still experiencing issues.
