### ISSUE TITLE
Domain activation is Failed - Trying to reconnect a domain

### ISSUE THREAD

**Issue by aylesm** [aws-amplify/amplify-console#126]
**App Id**: d26pl6wgx1aa16
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Trying to connect a subdomain and it's causing pain.  I've disconnected from an old Amplify app and trying to reconnect.

**Error message**
The error message is Domain Validation failed.  Big red banner, but nothing else.

**Comment by nimacks** [comment]
@aylesm , according to our records this app has successfully activated the custom domain. I have been able to navigate to the app. Please re-open this issue if you're still having issues.
