### ISSUE TITLE
Missing point branch to environment option for previews feature

### ISSUE THREAD

**Issue by noobling** [aws-amplify/amplify-console#1260]
**Describe the bug**
Missing point branch to environment option for previews feature.  This is my arn arn:aws:amplify:ap-southeast-2:501501192460:apps/d21ryid21oxovg

**To Reproduce**
1. Go to amplify console
2. Click on previews
3. Click on preview settings
4. Select branch and click manage
5. This is what i see
![image](https://user-images.githubusercontent.com/23206864/99871819-6b8a6000-2c18-11eb-86de-0d04dad64af1.png)

**Expected behavior**

That I have the ability to select an environment to point my preview branches to

**Screenshots**

This is what I see when I manage my preview for a branch
![image](https://user-images.githubusercontent.com/23206864/99871753-f74fbc80-2c17-11eb-8bf6-ebe74c01b4d0.png)

This is what others see found from #558 
![image](https://user-images.githubusercontent.com/23206864/99871761-09c9f600-2c18-11eb-903b-bd85b0517923.png)

**Comment by ganipcanot** [comment]
Are you using a private git repository?  PR previews are only supported for private repos.

**Comment by hainessss** [comment]
I have this same problem. When I first set up previews for the development branch it rendered the below screen shot. Now it renders the above.  My repo is private. app arn: arn:aws:amplify:us-east-1:515731798434:apps/d9gev4d8akads
