### ISSUE TITLE
Browser cache not invalidated after a deployment

### ISSUE THREAD

**Issue by maximelebastard** [aws-amplify/amplify-console#1263]
**Describe the bug**
Expected bebavior: I deploy a new version of my frontend app for a project using Amplify. I go back to the app URL, the browser loads the new version of the frontend files.

Actual behavior: I deploy a new version of my frontend app for a project using Amplify. I go back to the app URL, the browser loads the previous version of the app (from cache). I have to manually refresh to get the new app version.

It may be related to Etag or If-Modified-Since headers - I didn't have the time to understand which header actually failed.

**To Reproduce**
- Create a React app, which is a Single page website
- Deploy it using amplify
- Set the rewrite rules to `[
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|json|jpg|js|png|txt|svg|woff|ttf)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]`
- Using Google Chrome, visit the app website
- Update something in your app, push it to redeploy
- Open a new tab, go to the app

The previous version of your app is loaded. You have to press Cmd+R or Cmd+Shift+R to get the latest version.

This is particularly anoying when updating a GraphQL query. It makes the app crash and errors being visible as the frontend is not sync anymore with the backend.

**Comment by swaminator** [comment]
@maximelebastard Amplify does not control the browser caching - you might have service workers running in your app or have client-specific ttl settings.

**Comment by mrafiqk** [comment]
@swaminator I feel the build folder is not cleared when deploy the new version. I removed my home screen and deployed with the new home screen but it still loads my old home page which is not in my latest code.
