### ISSUE TITLE
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by sorin-sabo** [aws-amplify/amplify-console#1264]
**Describe the bug**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
This already happens in range of more than 96 hours after removal of previous CNAME. (I retried multiple times in this time range)
Propagate of DNS takes a max of 48 hours so either the check done by AWS Amplify is completely off - or you actually check  if it was ever used or not - hopefully that's not the case...

**To Reproduce**
1. Go to Amplify Console
2. Click on Domain Management
3. Add domain (3rd party one - in my case GoDaddy)
4. Configure domain
5. Remove root
6. Add subdomain key
7. Save - and wait till step 2
8. Enter CNAME under GoDaddy DNS config
9. Step 2 completes successfully
10. Step 3 See error

**Expected behavior**
On step 3 waits until I add a new subdomain under GoDaddy and completes successfully.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by brnmye** [comment]
We are going to close out this issue, but please feel free to re-open if you still need help.

**Comment by brnmye** [comment]
We are going to close out this issue, but please feel free to re-open if you still need help.

**Comment by heightsInnov** [comment]
I couldn't find any distribution attached to my amplify app. None at all in the distribution of the cloudfront.
I need help.

**Comment by mark-hayward** [comment]
I think Amplify hosts your cloudfront in a different account - maybe an AWS one? and not your own. Which is why it wouldn't appear. However, I do also receive the same error as you. It seems to add an unknown cloudfront URL but gives an error : Error message: One or more of the CNAMEs you provided are already associated with a different resource.

This is despite amplify actually creating this record. Did you manage to resolve this?
