### ISSUE TITLE
Unable to connect a CodeCommit repository

### ISSUE THREAD

**Issue by ayotise** [aws-amplify/amplify-console#1268]
**Describe the bug**
We have been using the Amplify CI pipeline for a couple of months now. A team member of mine mistakenly disconnected the application on the amplify console and everytime i try to connect app with the same repository we had earlier, we keep getting the error when I try to connect an existing CodeCommit repository: 

**There was an error detecting your build settings.
SyntaxError: JSON Parse error: Unrecognized token '/'**

**To Reproduce**
1. disconnect the repository of an existing app on the amplify console
2. try to connect the same repository back.
3. You will see the error:
4. See error:
There was an error detecting your build settings.
SyntaxError: JSON Parse error: Unrecognized token '/'

**Expected behavior**
The repository should be connected and I should be allowed to go to the next stage "configure build settings"

**Screenshots**
<img width="742" alt="Screen Shot 2020-11-22 at 8 40 50 PM" src="https://user-images.githubusercontent.com/30660157/99923287-03fd0f00-2d03-11eb-8596-dcc85cea81cb.png">

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: Safari 14.0

**Comment by ganipcanot** [comment]
I tried creating a CodeCommit repository and connecting this app: https://github.com/aws-samples/aws-amplify-appsync-graphql-real-time-canvas

I was then able to disconnect and reconnect properly.

1. Did you modify your build settings at all between the time you disconnected and reconnected the repository?
2. Would you mind sharing your build settings?
3. Is this a [mono-repo](https://aws.amazon.com/blogs/mobile/set-up-continuous-deployment-and-hosting-for-a-monorepo-with-aws-amplify-console/) application?

**Comment by ayotise** [comment]
@ganipcanot Thanks for the prompt response.

1. Did you modify your build settings at all between the time you disconnected and reconnected the repository? **No**
2. Would you mind sharing your build settings?
[amplify.txt](https://github.com/aws-amplify/amplify-console/files/5594168/amplify.txt)
3. Is this a mono-repo application? **No**

**Update**: I had to create another CodeCommit repo, copy all the code into it, and configured amplify without any issues.
