### ISSUE TITLE
Erroneous dual domain build and deploy

### ISSUE THREAD

**Issue by 0luftballoons** [aws-amplify/amplify-console#127]
**Describe the bug**
Committing to GitHub repo branch causes Amplify to build and deploy the branch to two separate domains. One domain is reported via email in "AWS Notification Message", and the other domain is reported via AWS Amplify Console.  Both domains are active, and are identical in content. AWS Amplify Console has no knowledge of the domain reported in the email, clicking on the email link for "Go to \<the url\> to view details on your build" opens the Amplify page with a red error banner reading "App with id: \<the domain id\> not found"

**Expected behavior**
Email notification of the domain should be identical to the domain shown in AWS Amplify Console, and only one domain should be built and deployed.

**Additional context**

**Sample code**
You can manually rebuild and deploy the "dev" branch

**Comment by nimacks** [comment]
@0luftballoons , thanks for reaching out. We'll look into this issue.
