### ISSUE TITLE
Can't see all amplify backend environment in the UI. limit to 10 (We have more than 10 envs).

### ISSUE THREAD

**Issue by iuyt9003** [aws-amplify/amplify-console#1272]
**Describe the bug**

**To Reproduce**
1. Go to 'Amplify Dashboard'
2. Click on 'Specific amplify app with more than 10 backend environments, then click on backend environments'
3. Try to locate the backend environment which not found
4. You will not see it

**Expected behavior**
Pagination, filter, to see the backend env that not displayed. haven't check for the frontend but could be also.

**Screenshots**
Can't put a screenshot on what I can't see :) 

**Additional context**
I am using Chrome, not think this is the case but if it helps.

**Comment by Athena96** [comment]
Hi @iuyt9003 currently Amplify only displays a max of 10 backend environments. 
We are updating this to display all backend environments. I'll follow up once that change is deployed. Can you share your appId if possible, so I can notify you when we deploy to your region. Thank you

**Comment by Athena96** [comment]
Fix is deployed, closing this issue. Please feel free to re-open if you are still facing the issue. Thank you
