### ISSUE TITLE
Amplify deployed backend to a different region than frontend

### ISSUE THREAD

**Issue by jknapp25** [aws-amplify/amplify-console#1274]
** Please describe which feature you have a question about? **
AWS Amplify

** Provide additional details**
Amplify deployed my backend to a different region than my frontend. I now want to migrate the frontend to where the backend is...

us-east-1 -> us-west-2

I tried just deleting the existing frontend on the backend environment (no idea where that came from) and replacing it with the correct one, but there's no option to just "delete frontend environment". And I'm afraid that if I click "delete app", it will kill the backend with my api and all of the data I've created in S3 and dynamodb, etc.

I think it's kind of ridiculous that there isn't just a "migrate environment to a new region" feature. Also, the ability to just delete the frontend environment.

How can I consolidate my frontend and backend to one region?

**Comment by jknapp25** [comment]
Is this the correct place to ask this question? Or should I use a different forum?

**Comment by hsspain** [comment]
@jknapp25 Can I get the app ID which you had your backend deployed to a different region for?

**Comment by jknapp25** [comment]
I ended up deleting and recreating after saving my data via csv export. Closing this issue.
