### ISSUE TITLE
 Deploying build artifacts to the Amplify Console..Job Timeout before succeeded

### ISSUE THREAD

**Issue by au1120** [aws-amplify/amplify-console#1276]
**Describe the bug**
 `Deploying build artifacts to the Amplify Console..Job Timeout before succeeded.`
 This is the only message I receive with no verbose logging of what exactly occurred to cause a timeout

**To Reproduce**
`amplify publish`

This is a `Vue` application. 

using `yarn build` for my build script

**Comment by wpsystems** [comment]
I have the same problem with my react JS app.

amplify publish
...
√ Zipping artifacts completed.
| Deploying build artifacts to the Amplify Console..Job Timeout before succeeded
× Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at Object.publish (C:\Users\pangj\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-console-hosting\index.js:39:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by valgaze** [comment]
+1 similar error (```Cannot read property 'name' of undefined```) for vuejs app

- Node: v10.23.0

- Amplify CLI: 4.28.0 (same behavior on lower version before upgrading)

@wpsystems @au1120 Can you add your node & Amplify CLI versions?

Could also be part of broader service issue [11/25/2020], ex **https://status.aws.amazon.com**:

```
Increased Error Rates
Latest Update (9:06 PM PST): Over the past two hours, we have continued to bring more traffic in to Kinesis Data Streams, which is leading to gradual recovery of applications that use Kinesis directly, as well as dependent services within the US-EAST-1 Region. We are bringing traffic in more slowly than anticipated while we closely monitor each change to ensure continued stability. We expect that over the next few hours, we will complete restoring Kinesis Data Streams to normal operations.

CloudWatch metrics remain delayed in the US-EAST-1 Region. Once we have restored the throttles for Kinesis to previous levels, we will be restoring CloudWatch metrics functionality. We expect to see recovery of CloudWatch metrics at that stage for new incoming metrics, but the backlog of metrics may take additional time to populate.

We will continue to keep you updated on our progress.

Previous Update (6:23 PM PST): We’d like to provide an update on the issue affecting the Kinesis Data Streams API, and other dependent services, within the US-EAST-1 Region. We have now fully mitigated the impact to the subsystem within Kinesis that is responsible for the processing of incoming requests and are no longer seeing increased error rates or latencies. However, we are not yet taking the full traffic load and are working to relax request throttles on the service. Over the next few hours we expect to relax these throttles to previous levels. We expect customers to begin seeing recovery as these throttles are relaxed over this timeframe.

Currently Impacted Services: ACM, Amplify Console, AppStream2, AppSync, Athena, Batch, CodeArtifact, CodeGuru Profiler, CodeGuru Reviewer, CloudFormation, CloudMap, CloudTrail, Connect, Comprehend, DynamoDB, Elastic Beanstalk, EventBridge, GuardDuty, IoT Services, Lambda, LEX, Macie, Managed Blockchain, Marketplace, MediaLive, MediaConvert, Personalize, RDS Performance Insights, Rekognition, SageMaker, and Workspaces.
```

**Comment by wpsystems** [comment]
Published successfully this morning.  Looks like it was related to the outage yesterday.

**Comment by ganipcanot** [comment]
Closing for now - please re-open if you are still having issues.
