### ISSUE TITLE
Stuck at provisioning

### ISSUE THREAD

**Issue by alangodoi** [aws-amplify/amplify-console#1279]
**Describe the bug**
Just updated my React JS code at Github and Amplify got stuck at provisioning.
I've also tried to trigger it from curl and the same occurs.

**Screenshots**
[Build](https://imgur.com/a/GGyELrT)
[History](https://imgur.com/a/8Y64F6B)

I've created another build from a development branch and the same occurs.

**Comment by DannyMoerkerke** [comment]
I have this same problem!
I cannot even delete the branch nor the app, everything seems stuck.
I created a new app and the first deployment is also stuck at provisioning

**Comment by rbtool** [comment]
I have the same issue.  I have tried multiple ways to build my app and each is stuck in provisioning.  I can't delete through the web interface or CLI.  I need to get these deleted.

**Comment by qxzzxq** [comment]
Same issue too. Stuck at provisioning. I can't even cancel the build

**Comment by DannyMoerkerke** [comment]
I guess it's this issue: https://phd.aws.amazon.com/phd/home#/event-log?eventID=arn:aws:health:us-east-1::event/AMPLIFY/AWS_AMPLIFY_OPERATIONAL_ISSUE/AWS_AMPLIFY_OPERATIONAL_ISSUE_f2e47794-daa0-4522-a28d-90c0e479ac74&eventTab=details

**Comment by alangodoi** [comment]
It now moved to "Deploy". It's running more than 2 hours.

**Comment by rbtool** [comment]
> It now moved to "Deploy". It's running more than 2 hours.

How did you move to Deploy?

**Comment by DannyMoerkerke** [comment]
I just did a build and for me it's working again.

**Comment by DesoCT** [comment]
I am experiencing this issue currently :(

**Comment by alangodoi** [comment]
I removed all running build and started again. Now it's working.

**Comment by alangodoi** [comment]
I removed all running builds and started a new one. Now it's working.

**Comment by mauhdz** [comment]
Hi, still experiencing this issue. Any fix? These bugs make me feel so insecure about using Amplify as it is truly unreliable.
