### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by pedromrcosta** [aws-amplify/amplify-console#1286]
**App Id**: d328o013q3y8nz
**Region**: eu-west-2
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
 We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue in our GitHub issue tracker.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
![image](https://user-images.githubusercontent.com/11708947/100328701-b7485b00-2fc4-11eb-895f-885b6d44ac81.png)

**Comment by cslogan-red** [comment]
It looks like the most recent update on your domain is failed DNS verification, the easiest thing to do is to remove and re-add your custom domain and make sure the DNS records are entered correctly, it can take up to 24 hours for DNS validation to succeed: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-troubleshoot-guide

Please reopen if you're still experiencing issues after this
