### ISSUE TITLE
SSL configuration is Running - stuck on certificate verification

### ISSUE THREAD

**Issue by wglane** [aws-amplify/amplify-console#1291]
**App Id**: dh560tidatacw
**Region**: us-west-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Linking my domain is stuck on this step, and has been for at least 12 hours: `We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue in our GitHub issue tracker.`

**Comment by cslogan-red** [comment]
Looks like this app has since been deleted, if you're still having issues please re-open and provide latest app Id.
