### ISSUE TITLE
SSL configuration is Running - Status stuck

### ISSUE THREAD

**Issue by borisdayma** [aws-amplify/amplify-console#1292]
**App Id**: d1uqaeyzqpypj2
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
SSL configuration is stuck

**Error message**
If there is an error message, please include it here. 
![image](https://user-images.githubusercontent.com/715491/100373555-92f27b80-2fd0-11eb-8096-44cb0cf2b704.png)
 
**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by cslogan-red** [comment]
It looks like your domain has since completed verification and has been successfully created, please reopen if you're still experiencing issues.
