### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Gamedoper** [aws-amplify/amplify-console#1294]
**App Id**: d3e2xikkscic4d
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by cslogan-red** [comment]
It looks like the custom domain has since been removed, there are a number of reasons for the DNS error you encountered: https://docs.aws.amazon.com/amplify/latest/userguide/understanding-dns-terminology-and-concepts.html Please feel free to reopen if you're still experiencing an issue.
