### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Infantsabin** [aws-amplify/amplify-console#1296]
**App Id**: d23qh8upztegq2
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by cslogan-red** [comment]
It looks like the most recent update on your domain is failed DNS verification, the easiest thing to do is to remove and re-add your custom domain from the Console and make sure the DNS records are entered correctly, it can then take up to 24 hours for DNS validation to succeed: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-troubleshoot-guide

Please reopen if you're still experiencing issues after this
