### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by signaturexe** [aws-amplify/amplify-console#1297]
**App Id**: d2lshfjmo8jk27
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
**Verification of domain ownership is not resolved after 8 hours (as specified on Amplify Dashboard). CNAME records exists in the DNS file.**

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
![image](https://user-images.githubusercontent.com/8899447/100410658-60329c80-303d-11eb-98c6-cccd65985afb.png)

**Comment by cslogan-red** [comment]
It looks like your domain has since completed verification and has been successfully created, please reopen this if you're still having issues.
