### ISSUE TITLE
Automatically Enable notifications for all connected branches

### ISSUE THREAD

**Issue by kmfreas** [aws-amplify/amplify-console#13]
> ** Which Category is your question related to? **

Amplify Console

> ** What AWS Services are you utilizing? **

Auth/Storage/Console

I'm using amplify console as our CI/CD system but I'm having a hard time finding features in it that are available in other alternatives like CircleCI. My problem right now is trying to create a build complete/failed webhook for slack. It works ok for complete if I put it in frontend postBuild. But obviously if a step fails beforehand it never gets to that point.

So my question is how can I catch a build error and then run a bash command afterwards?

Thanks for looking into this!

**Comment by RyanHow** [comment]
Hey I just found this article here

Looks like there is a way to do it through cloudwatch?

https://medium.com/@dabit3/introducing-the-amplify-console-8-exciting-features-7e4075ff7b36

>8: Notifications
>Setup email notifications when your deployment succeeds or fails. Amplify Console submits build events to Amazon CloudWatch giving you a lot more capability to setup alarms and send events to services like Slack to notify users of changes.

**Comment by swaminator** [comment]
@RyanHow yes you can, it just requires you to configure it. Check out https://github.com/aws-amplify/amplify-console/issues/13#issuecomment-502240507

**Comment by mwarkentin** [comment]
@swaminator looks like that links back to this PR?

**Comment by mwarkentin** [comment]
@swaminator have you discussed amplify console notification support with the AWS chatbot team? That would be great. 😊

**Comment by adriencg** [comment]
@kmfreas I know this is late..but you can actually modify the event pattern that Amplify creates to notify your email about all branches (past, present, future) assuming you've created at least one notification via the Amplify console.

Go to the Amazon EventBridge console, under "Rules" find the rule for your app (should look like amplify-<appId>-<branch>-branch-notification). Modify the Event pattern by just deleting the "branches" array entirely (make sure to hit 'Update' at the bottom of the page after modifying the event pattern inline). You can quickly test by connecting a new branch.

This works b/c EventBridge treats a missing field as a wildcard, so by deleting the branches array you're telling the service to deliver events about all branches.

**Comment by swaminator** [comment]
@mwarkentin @kmfreas @RyanHow this feature is now available in the Console
