### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by manoj10101996** [aws-amplify/amplify-console#1300]
**App Id**: d2hzj6jgxc2xul
**Region**: ap-south-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Not able to verify with my google domain

**Error message**
**Note**: Be sure to check the message for sensitive information. 
Error message: Hard limit reached; unable to record function association
**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by dheeraj-allamaneni** [comment]
Have you found any solution for that ?

**Comment by cslogan-red** [comment]
It looks like your domain has since successfully verified and been created, please reopen this issue if you're still experiencing problems.
