### ISSUE TITLE
SSL configuration is Running - [for a very long time]

### ISSUE THREAD

**Issue by TrierHealth** [aws-amplify/amplify-console#1301]
**App Id**: d1t1u19ejwi4lu
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by cslogan-red** [comment]
It looks like this has since completed based on current status, please reopen this issue if you're still experiencing a problem.
