### ISSUE TITLE
ios deep linking in a react native - react native web app with Amplify

### ISSUE THREAD

**Issue by Bariah96** [aws-amplify/amplify-console#1303]
** Please describe which feature you have a question about? **
Amplify hosting

** Provide additional details**
i was trying to implement deep linking in my react native app (web and mobile) with amplify, and ios requires serving apple-app-site-association file in your web server, so i'm not sure where this file should be placed in case of serverless architectures, any ideas or suggestions ?

**Comment by kahdojay** [comment]
Please see https://github.com/aws-amplify/amplify-console/issues/713
