### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by ShubhamJain0** [aws-amplify/amplify-console#1304]
**App Id**: d12nyf05bcexrm
**Region**: ap-south-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
It has been more than 8 hours and still my domain isn't verified. It's stuck at SSL configuration.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by cslogan-red** [comment]
It looks like this has since successfully verified and been created, please reopen this issue if you're still experiencing a problem.
