### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by dheeraj-allamaneni** [aws-amplify/amplify-console#1306]
**App Id**: d2fkyl8f97cah2
**Region**: ap-south-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Unable to get domain activation done.

**Error message**
Hard limit reached; unable to record function association
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by loveshgrover** [comment]
@dheeraj-allamaneni did you find the solution? Facing the same issue

**Comment by manum176** [comment]
Same issue for me as well

**Comment by narayanshivansh49** [comment]
Same issue

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
