### ISSUE TITLE
Monorepo project builds & deploys on any change

### ISSUE THREAD

**Issue by dhoulker** [aws-amplify/amplify-console#1307]
I'm using the Amplify console to deploy a site. Originally this site was in its own githib repo, but i've just moved it into a monorepo. 

The application now live in the standard monorepo structure which is, for example `packages/app-a` next to a whole load of other packages.

I don't want to set up a new app in Amplify as i have lots of data. For this reason i have just clicked re-connect repo, but when i do this there is no monorepo checkbox.

I thought just moving the `amplify.yml` out to the root, and specifying an appRoot would work fine, and it does deploy the site on commits to the branches as expected, but *any* commit to the repo triggers a build. 

As i understand it should only build when the specific package has changed, is that right? 

```
version: 1
applications:
  - appRoot: packages/app-a
    backend:
``` 

Is there something else i need to do in order to get this working, or have i misunderstood how this should work?

Thanks!

**Comment by swaminator** [comment]
@dhoulker you need to first define the build settings in the amplify console, run a build, and then move it to the `amplify.yml`. Here's instructions: https://gist.github.com/swaminator/3f2e400675f3322ed76bad82a59b393b
