### ISSUE TITLE
SSL configuration is Running - Has Taken Longer Than 8 Hours

### ISSUE THREAD

**Issue by bajunkins** [aws-amplify/amplify-console#1308]
**App Id**: d10ki40i75xjy1
**Region**: us-east-2
**Step**: SSL configuration
**Status**: Running

**Issue/question**
Trying to use a custom domain for an Amplify app and the SSL configuration step has taken longer than 8 hours (13 now). Has this happened for other people? Should I just wait longer or is there a suggested fix.

**Error message**
It says " We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue in our GitHub issue tracker. " so that is what I am doing.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by brnmye** [comment]
We are going to close out this issue, but please feel free to re-open if you still need help.
