### ISSUE TITLE
SSL configuration is Running even after DNS verification

### ISSUE THREAD

**Issue by krishnakumar-git** [aws-amplify/amplify-console#1312]
**App Id**: d2rcjztg1r5tk1
**Region**: ap-south-1
**Step**: SSL configuration
**Status**: Running

**Message**:
"We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue"

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by brnmye** [comment]
We are going to close out this issue, but please feel free to re-open if you still need help.
