### ISSUE TITLE
Domain activation failed - Adding custom domain fails at "Domain Activation" stage

### ISSUE THREAD

**Issue by simondw** [aws-amplify/amplify-console#1315]
**App Id**: d2w0upzpxvfiml
**Region**: ap-southeast-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I am attempting to add a custom domain which is a sub domain **staging.mydomain.com** with no redirection from www. .

**Error message**
"We had issues connecting your custom domain" displays after going through SSL Creation & SSL Configuration stages successfully.

**Additional information**
I've retried several times and also deleted the Rout 53 created record and the Amplify record to start from scratch. Each time I'm hit with the same error (screen shot attached).

<img width="1121" alt="staging_dns_error" src="https://user-images.githubusercontent.com/14144450/100572637-13dfa900-332a-11eb-9559-98b52f91f549.png">

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by simondw** [comment]
Thanks @brnmye , I've found another app in another region that was using the same domain. Removing the duplicate app & domain resolved the issue.
