### ISSUE TITLE
Access Denied After Deploy

### ISSUE THREAD

**Issue by zhichunl** [aws-amplify/amplify-console#132]
** Please describe which feature you have a question about? **
After we try to deploy the app, it builds and deploys fine. However, going to this link https://master.dirypeghaf8kq.amplifyapp.com/ results in an Access Denied error. I have already configured the SPA rewrite. 

** Provide additional details**
project is built with webpack and the build is generated in the build/main.js

**Comment by Taelkir** [comment]
Don't suppose you remember what you did to fix this? I've had this problem and accidentally fixed it before - now I'm coming up against it again with no memory of what I did to fix it the first time
