### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by smajhi** [aws-amplify/amplify-console#1321]
**App Id**: d36ztmni2n0r01
**Region**: ap-south-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by hsspain** [comment]
@smajhi If you hare having issue with domain activation, one step to try would be to click the "Retry" button.  Another would be to remove the domain and try re-adding it.

Is there a specific error message that the UI shows?

**Comment by Athena96** [comment]
closing the issue, please let us know if you are still encountering it. Thanks!
