### ISSUE TITLE
Amplify console stuck at 'Retrieving deployment details'

### ISSUE THREAD

**Issue by Chuqing** [aws-amplify/amplify-console#1322]
I was adding a new environment and my initial deployment was pending. Then redeployment for my existing environment also remained pending. I have tried to redeploy but it did not work.

My app info:
ap-southeast-1:apps/dokyr610f0y0q

<img width="1267" alt="Screenshot 2020-12-01 at 11 07 44 PM" src="https://user-images.githubusercontent.com/4216435/100758129-20e3c180-342a-11eb-81c4-8bf30b42e7b3.png">

<img width="1054" alt="Screenshot 2020-12-01 at 11 15 25 PM" src="https://user-images.githubusercontent.com/4216435/100759041-22fa5000-342b-11eb-9ea3-ca7f6c90ab63.png">

**Comment by ganipcanot** [comment]
Are you doing a manual deployment?  If so how are you doing the manual deployment? 

1. Drag and drop folder (unzipped)?
2. Upload via a ZIP folder?
3. Upload ZIP to S3 bucket and deploy from there?
4. Specifying a source URL?

There is a known issue with a large number of files hanging for manual deployment - a workaround for now would be to upload a ZIP artifact to S3 and do a manual deployment from there.

**Comment by ganipcanot** [comment]
I went ahead and cancelled some pending jobs that got stuck - please try the workaround by zipping the files and uploading to an S3 bucket and deploying from there.

**Comment by Chuqing** [comment]
> I went ahead and cancelled some pending jobs that got stuck - please try the workaround by zipping the files and uploading to an S3 bucket and deploying from there.

Thank you so much. The problem is solved.
Previously I uploaded my files in S3 and got stuck.
