### ISSUE TITLE
Cannot deploy backend via console

### ISSUE THREAD

**Issue by subtlegiant** [aws-amplify/amplify-console#1323]
**Describe the bug**
Build step fails on GraphQL schema error when deploying backend. 
```
2020-12-02T01:49:46.669Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-12-02T01:49:46.669Z [WARNING]: ✖ There was an error initializing your environment.
2020-12-02T01:49:46.670Z [INFO]: init failed
2020-12-02T01:49:46.671Z [INFO]: { SchemaValidationError: Schema Errors:
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (8:44)
```

Here is the backend section taken from my amplify.yml

```
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple
```

I am able to push using the CLI/amplify push with no errors. If I include my aws-exports.js file in git and do not do the above built step, deployment works fine.

**To Reproduce**
Try to deploy app from console.

**Expected behavior**
To be able to deploy app.

**Comment by subtlegiant** [comment]
Was able to fix this issue by installing the latest version of amplify cli on install. 
```
backend:
  phases:
    build:
      commands:
        - amazon-linux-extras install python3.8
        - ln -fs /usr/bin/python3.8 /usr/bin/python3
        - pip3.8 install --user pipenv
        - npm install -g @aws-amplify/cli@4.32.1
        - amplifyPush --simple
```
Anyone know of a better way to set the cli version in the build envirionment?

**Comment by swaminator** [comment]
@subtlegiant please refer to https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates
