### ISSUE TITLE
How to apply custom headers to auth Login call Response?

### ISSUE THREAD

**Issue by mybNa** [aws-amplify/amplify-console#1326]
We are using AWS Amplify and Cognito framework for our application. We are trying to embed tableau dashboard in our application. And using Cognito as OpenID for SSO.

After signing into application when we try to connect to tableau server even though the login is successful (200 response), Cognito login call blocks the iframe with "x-frame-options: DENY" in call response.
We want to override this response header with "x-frame-options: SAMEORIGIN", what is the best way to achieve this?

Thank you.

**Comment by kahdojay** [comment]
closing in favor of discussion in this thread: https://github.com/aws-amplify/amplify-console/issues/1207
