### ISSUE TITLE
An error occurred during the publish operation

### ISSUE THREAD

**Issue by benwainwright** [aws-amplify/amplify-console#1329]
**Describe the bug**
Attempting to run `amplify publish` I get the following error message

```
✖ Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
An error occurred during the publish operation
```
**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6 - Also ubuntu-latest Github Action

I don't want to use the build in CI, but I might have to go back to it because any attempt to use `amplify publish` just fails.

**Comment by SSAT** [comment]
Having the same issue on latest Ubuntu OS

**Comment by hsspain** [comment]
@benwainwright @SSAT Can I get your app ID and region? Also are there any other errors in information in your logs to help further debug this issue?

**Comment by benwainwright** [comment]
@hsspain I'm going to be honest; the Amplify development experience has been so awful over the last few months that I took the decision to rip it out of my application shortly after I posted this issue and I'm now using the CDK for everything. So I'm going to close this issue.
