### ISSUE TITLE
Overwite env var results in duplicates that cannot be removed

### ISSUE THREAD

**Issue by ben-elsen** [aws-amplify/amplify-console#133]
**Describe the bug**
When I take the action 'variable override' for an environment variable via the Amplify console, I get 1 input line to define the value and branch. When I save, I get a confirmation message but the override appears 2 times. 

When I enter the manage variables again and try to remove one of the doubles, everythings seems to go ok but the 2 overrides keep appearing in the overview. When I try to add another environment variable, I get the error that I cannot have duplicate overrides.. 

**To Reproduce**
1. Go to manage variables
2. Add an override for a variable
3. Press save

1. Go to manage variables
2. Remove a duplicate of the override
3. Press save

**Expected behavior**
Only one override should appear. 

** Screenshot**
![Schermafdruk 2019-09-19 12 24 03](https://user-images.githubusercontent.com/29061657/65236857-bb800b00-dad9-11e9-99e1-df8c720da809.png)

**Comment by nimacks** [comment]
@ben-elsen, we're actively looking into this issue for you and hope to give you an update soon.

**Comment by ben-elsen** [comment]
@nimacks Ok thanks!

**Comment by garyleefight** [comment]
@ben-elsen Hi, the fix was pushed. We will schedule a deployment to resolve the issue.

**Comment by ben-elsen** [comment]
Hi @ garyleefight Thanks! Do you have an idea when the deployment is sheduled yet?

**Comment by hzhenmin** [comment]
@ben-elsen
 
You can try again and it will work.
 
If there are any other questions please let us know.
