### ISSUE TITLE
Front-end build not using provisioned node version

### ISSUE THREAD

**Issue by cabernal** [aws-amplify/amplify-console#1338]
We have a front-end configured to provision node to version `$VERSION_NODE_10`, which is set to `10.16.10`.

The front-end has been deploying successfully for many months now, but has been failing on the build step in our latest deployment this morning.

The error logs show the following:

```
Failed to compile.
2020-12-05T19:11:07.973Z [INFO]: ./src/theme/index.scss
                                 Error: Missing binding /codebuild/output/src255649265/src/<redacted>/node_modules/node-sass/vendor/linux-x64-72/binding.node
                                 Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x
                                 Found bindings for the following environments:
                                 - Linux 64-bit with Node.js 10.x
                                 This usually happens because your environment has changed since running `npm install`.
                                 Run `npm rebuild node-sass` to download the binding for your current environment.
```

I find it odd that the logs indicate the current environment to be using **Node 12.x**, given that our provision logs show:
```
ENV VERSION_NODE_DEFAULT=$VERSION_NODE_10
...
$PATH" >> ~/.bashrc && \
    echo export GEM_PATH="/usr/local/rvm/gems/ruby-${VERSION_RUBY_DEFAULT}" >> ~/.bashrc && \
    echo "nvm use ${VERSION_NODE_DEFAULT} 1> /dev/null" >> ~/.bashrc

ENTRYPOINT [ "bash", "-c" ]
```
Is there a new method to configure the node version in the build step that we're missing?

**Comment by abhi7cr** [comment]
Hi @cabernal,
We recently updated the default image which includes using node v12 as the default. Are you using the default image? If you want to continue using node v10, you can set it using nvm use $VERSION_NODE_10 in the build commands, or if you want to use node 12, you can run: npm rebuild node-sass to update the sass bindings for node 10. The dockerfile shown under the provisioning step is still the old one, we are going to update it early next week. 

Let me know if you have any questions.

**Comment by cabernal** [comment]
Hi @abhi7cr, 

We're using the default image, but it looks like the provision step is already setting the node version to ` $VERSION_NODE_10`.

**Comment by abhi7cr** [comment]
yes the above DOCKER file (_seen under Provision tab_) doesn't reflect the latest file used in the build.  We are going to update the above to the latest early next week.

**Comment by cabernal** [comment]
@abhi7cr I see. Is it possible to specify the node version for the build step in the amplify.yml spec file under `Build setting` via nvm?

**Comment by abhi7cr** [comment]
@cabernet  yup, in the build settings -> amplify.yml -> build -> commands,  you can set node v10 using the below command:
`nvm use $VERSION_NODE_10`

**Comment by NomanGul** [comment]
any update on this?

**Comment by huphtur** [comment]
Switching back to older node versions does not work, [see error log](https://gist.github.com/huphtur/c9d2a4929bd14180e77e6508b827b9e5).

We have multiple sites that can not be build now. Any help with this please?

**Comment by abhi7cr** [comment]
@huphtur,

Could you run `npm rebuild node-sass` In the preBuild step in amplify.yml file under build settings ?

**Comment by huphtur** [comment]
negative @abhi7cr, still getting build errors. used the following build script: 
```yml
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - npm rebuild node-sass
        - bundle install
        - yarn
    build:
      commands:
        - nvm use $VERSION_NODE_10
        - if [ "${AWS_BRANCH}" = "master" ]; then yarn production; fi
        - if [ "${AWS_BRANCH}" = "staging" ]; then yarn staging; fi
  artifacts:
    baseDirectory: _site
    files:
      - '**/*'
  cache:
    paths: []
```

**Comment by abhi7cr** [comment]
Okay couple of things you can try:
1. If you want to use node 10,  you can move the `nvm use $VERSION_NODE_10` command to preBuild section before the yarn install command. 
2. If you want to use node 12, you won’t need the nvm use command. You can keep the  `node rebuild sass` command in the preBuild section, but define it after the yarn install command.

**Comment by huphtur** [comment]
Tried several scenarios, all of them failing. Was worried it was a problem with our repo, but things build fine locally and on Netlify. 

```yml
    preBuild:
      commands:
        - nvm use $VERSION_NODE_10
        - bundle install
        - yarn
        - npm rebuild node-sass
```

and

```yml
    preBuild:
      commands:
        - bundle install
        - yarn
        - npm rebuild node-sass
```

always errors as such:

```
2020-12-08T21:36:19.542Z [INFO]: # Executing command: yarn
2020-12-08T21:36:20.107Z [INFO]: yarn install v1.22.0
2020-12-08T21:36:20.180Z [INFO]: [1/4] Resolving packages...
2020-12-08T21:36:20.469Z [INFO]: [2/4] Fetching packages...
2020-12-08T21:36:30.437Z [INFO]: info fsevents@1.2.7: The platform "linux" is incompatible with this module.
2020-12-08T21:36:30.439Z [INFO]: info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
2020-12-08T21:36:30.448Z [INFO]: [3/4] Linking dependencies...
2020-12-08T21:36:36.317Z [INFO]: [4/4] Building fresh packages...
2020-12-08T21:37:57.771Z [WARNING]: error /codebuild/output/src908321045/src/amplify-collaboratesoftware.com/node_modules/node-sass: Command failed.
                                    Exit code: 1
                                    Command: node scripts/build.js
                                    Arguments:
                                    Directory: /codebuild/output/src908321045/src/amplify-collaboratesoftware.com/node_modules/node-sass
etc 
etc
```

It errors out before node-sass rebuild even?

**Comment by abhi7cr** [comment]
@huphtur can you share your appId ? Will look at the logs on our side.

**Comment by huphtur** [comment]
@abhi7cr d12hr921eys2px (us-west-2)

**Comment by abhi7cr** [comment]
@huphtur not sure what version of node-sass is installed in your build, but could you try installing the latest version of `node-sass` ? https://www.npmjs.com/package/node-sass. Looks like any version equal or above`4.12` should be compatible with node v12.

**Comment by gaochenyue** [comment]
The same issue here.

**Comment by gaochenyue** [comment]
The following preBuild commands work for me
`frontend:
  phases:
    preBuild:
      commands:
        - nvm use $VERSION_NODE_10
        - npm install
        - npm rebuild node-sass        
    build:`

**Comment by cabernal** [comment]
Yeah, adding `nvm use $VERSION_NODE_10` before installing dependencies is the way we worked around this.

**Comment by huphtur** [comment]
Ugh, so I kept editing the build settings in the Amplify Console Web UI, not realizing there was an `amplify.yml` file in the root of the repo, which takes precedence. Added `nvm use $VERSION_NODE_10` to that file and everything is building as expected now. 

![embarrassed](https://media4.giphy.com/media/njPdRtrrdyoVO/giphy.gif)

Thanks @abhi7cr and @gaochenyue for the assists.
