### ISSUE TITLE
SSL configuration is Running - Currently stuck in Domain Activation for 48 hours now

### ISSUE THREAD

**Issue by abbysudario** [aws-amplify/amplify-console#1339]
**App Id**: d33lhfk33ox87d
**Region**: us-west-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Trying to connect a third party domain and is stuck on Domain Activation

**Error message**
No Error so far from the AWS Amplify UI

**Additional information**
Checked my DNS and it is propagating correctly.

**Comment by hsspain** [comment]
@abbysudario Please ensure that the proper CNAME records are present in the domain you are trying to verify.

You can also try to remove and re-add the domain to restart the verification process.

**Comment by quiquegarcia** [comment]
> 
> 
> @abbysudario Please ensure that the proper CNAME records are present in the domain you are trying to verify.
> 
> You can also try to remove and re-add the domain to restart the verification process.

Remove and re-add the domain was the solution for me a few months ago

**Comment by Athena96** [comment]
closing the issue, please let us know if you are still encountering it. Thanks!
