### ISSUE TITLE
Custom domain: can domain ownership CNAME record be deleted?

### ISSUE THREAD

**Issue by 0luftballoons** [aws-amplify/amplify-console#134]
**App Id**:
**Region**:
**Step**:
**Status**:

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
We have successfully added a custom domain through Amplify, but want to know if we can remove the verification CNAME record that was used to verify domain ownership prior to generation of the SSL cert?

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by hzhenmin** [comment]
@0luftballoons No, it cannot be removed. It will be used for auto certificate renewal.
