### ISSUE TITLE
Source Repository field keeps flipping from real repo to an undefined repo

### ISSUE THREAD

**Issue by harenadata** [aws-amplify/amplify-console#1343]
**Describe the bug**
I created an amplify application on my dev account for AWS.  I pointed it to a repo on github.  I have used this same repo on my production account, where it worked.  Now, instead of building, it just flips between the repo URL and some undefined repo.

I have a video of this happening.  I let it run on an app for a couple hours, hoping it would fix itself.  I then deleted that amplify app and created a new one.

**To Reproduce**
1. create frontend application on github repo
2. use default settings
3. choose a branch from that repo (in this case, development)
4. finish wizard
5. watch build screen

**Expected behavior**
The app should start to build

**Screenshots**
<img width="993" alt="Screen Shot 2020-12-06 at 4 00 14 PM" src="https://user-images.githubusercontent.com/41688309/101292395-3451ac80-37dd-11eb-88d4-0d9eca7149ff.png">

<img width="993" alt="Screen Shot 2020-12-06 at 4 03 42 PM" src="https://user-images.githubusercontent.com/41688309/101292402-3ae02400-37dd-11eb-82be-952117caf328.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7 (19H15)
 - Browser Chrome Version 86.0.4240.198 (Official Build) (x86_64)

**Comment by harenadata** [comment]
@duaneenterprises, FYI

**Comment by harenadata** [comment]
I deleted the webhook from my repo, removed Amplify access from github, and deleted all amplify apps.  I recreated this on the original account, and it still does not work.  The "source repository" keeps disappearing.  You can see the "source repository" change on the build screen and on the app settings screen.

**Comment by hsspain** [comment]
@harenadata We are working on a fix for this.  We will keep you updated as we find a solution.

**Comment by harenadata** [comment]
did the syntax for the amplify.yml change?  I deleted it and added the default and now it works again:


diff --git a/amplify.yml b/amplify.yml
index 7cd392f..36fab73 100644
--- a/amplify.yml
+++ b/amplify.yml
@@ -1,17 +1,16 @@
 version: 1
-applications:
-  - frontend:
-      phases:
-        build:
-          commands:
-            - echo build
-            - yarn install --frozen-lockfile
-            - yarn build
-      artifacts:
-        baseDirectory: build
-        files:
-          - '**/*'
-      cache:
-        paths: 
-          - node_modules
-    appRoot:
+frontend:
+  phases:
+    preBuild:
+      commands:
+        - yarn install
+    build:
+      commands:
+        - yarn run build
+  artifacts:
+    baseDirectory: build
+    files:
+      - '**/*'
+  cache:
+    paths:
+      - node_modules/**/*
(END)

**Comment by swaminator** [comment]
@ghost we fixed this issue. Are you still seeing the same?

**Comment by mabdullahabid** [comment]
I'm facing the same issue!

**Comment by Shen-Zen** [comment]
same case for me

**Comment by katakatataan** [comment]
I'm facing the same issue, too!

**Comment by duaneenterprises** [comment]
@hsspain I never saw the fix actually work.  The only thing that corrected it was to change the amplify build file as shown above.

**Comment by cchalfan1** [comment]
Still seeing this issue. Happens on all us-west-1 apps, but not on us-west-2 app. Haven't moved the apps to see if there's a direct relationship.

**Comment by uwin** [comment]
I'm facing the same issue, too!

**Comment by navodzoysa** [comment]
I'm facing the same issue!

**Comment by kahdojay** [comment]
We'd rolled out a fix for this but forgot to update this ticket, closing for now but please re-open if you're still experiencing this issue.
