### ISSUE TITLE
Removing backend envs for app d10q5ulfqk56ws failed

### ISSUE THREAD

**Issue by cardeol** [aws-amplify/amplify-console#1344]
**Describe the bug**

**To Reproduce**
1. Select your application
2. Click on the Dropdown 'Actions' located at the top and select 'Delete app'
4. See error: 'Removing backend envs for app d10q5ulfqk56ws failed'

**Expected behavior**
The application should be deleted

**Desktop (please complete the following information):**
 - OS: [Mac OSX 10.15 - Catalina]
 - Browser [Chrome]
 - Version [Removing backend envs for app d10q5ulfqk56ws failed]

**Additional context**
Tried disconnecting repo, removed all used resources one by one, but still getting the error

**Comment by hsspain** [comment]
@cardeol Can you please provide the region in which this app exists?

**Comment by amanas** [comment]
Hi, I am having exactly the same problem. Frankfurt region. Any idea why this is happening?

**Comment by cardeol** [comment]
Of course, the region is us-east-1. rgs

**Comment by swaminator** [comment]
@cardeol @amanas while we work on a fix, please try this workaround: https://github.com/aws-amplify/amplify-console/issues/1330#issuecomment-740632418.

**Comment by amanas** [comment]
Worked for me. Thanks @swaminator.

**Comment by swaminator** [comment]
CLosing this to to track in #1330
