### ISSUE TITLE
JSONValidationError for the graphqltransformer preventing build from completing

### ISSUE THREAD

**Issue by AntonioJacksonII** [aws-amplify/amplify-console#1345]
**Describe the bug**
I am receiving `File project: data should NOT have additional properties: 'graphqltransformer'` and `File project: data should NOT have additional properties: 'graphqltransformer'` errors when attempting to complete the build at the end of Module 3 of the [Build a Full-Stack React Application](https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/?e=gs2020&p=build-a-react-app-two) tutorial.

**To Reproduce**
1. Follow the Build a Full-Stack React Application tutorial through the *Deploy the changes to the live environment* step in Module 3.
2. The application will correctly provision and clone the repository; however, the build will fail at the *Backend* stage.
3. In the AWS Amplify Console, click on the failed build icon.
4. View the error in the *Backend* section of the build.

**Expected behavior**
The build should complete and successfully deploy the updated application to AWS Amplify.

**Screenshots**
Here is a screenshot of the error received during the build:  
<img width="1332" alt="Screen Shot 2020-12-07 at 10 28 33 AM" src="https://user-images.githubusercontent.com/61103957/101384115-3d8f5780-3877-11eb-9599-c47ada9f77aa.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.0.1
 - Browser: Chrome 
 - Version: 87.0.4280.88 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
- Smartphone not used

**Additional context**
The [Build a Full-Stack React Application](https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/) tutorial was followed step-by-step up to the *Deploy the changes to the live environment* step in Module 3, where the build error was encountered. The rest of the tutorial was completed and the application is fully functioning locally; however, the build fails and the application cannot be deployed to AWS Amplify.

**Comment by TLaue** [comment]
I am facing the same problem with a project which did build till yesterday. Any ideas what might be the source of this problem?

**Comment by TLaue** [comment]
I have just found the solution to this issue in [Amplify-CLI repo](https://github.com/aws-amplify/amplify-cli/issues/6117).You have to set an package override for the Amplify CLI.

![image](https://user-images.githubusercontent.com/36646404/101613295-e2db3480-3a0b-11eb-862d-824ae31ab606.png)

**Comment by murvinlai** [comment]
change Amplify console version: go to Amplify console -> app settings -> build settings.  scroll down to  "Build Image Settings" section and click Edit

Change Amplify CLI to latest or specific version. :)

**Comment by bjwyse** [comment]
Still fails to build for me, even with version set to latest:

```
2020-12-20T10:15:18.113Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2020-12-20T10:15:22.523Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 4.40.0...
aching...
2020-12-20T10:16:12.878Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by murvinlai** [comment]
> Still fails to build for me, even with version set to latest:
> 
> ```
> 2020-12-20T10:15:18.113Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
> 2020-12-20T10:15:22.523Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 4.40.0...
> aching...
> 2020-12-20T10:16:12.878Z [INFO]: # Environment caching completed
> Terminating logging...
> ```

you may try to match your version with the one in Amplify.  See if it works.

**Comment by aam198** [comment]
I had the same issue, switched Amplify CLI version from latest to my current version and still received build error. I then had a new notification about service role. I added a service role by following: [https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html](https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html) and Voila! it works now! 

p.s. I switched the Amplify CLI version back to latest instead of my most recent version and still getting successful builds.

**Comment by ccdaniele** [comment]
Yeah this is the solution. I have both problems. With this https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html  I fixed my role situation, and changing to the latest version I could build. Thank you very much
