### ISSUE TITLE
Domain activation is Failed - Activation domain failed

### ISSUE THREAD

**Issue by leandrodamascena** [aws-amplify/amplify-console#1346]
**App Id**: d1qmctt2zb9igg
**Region**: sa-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I can't activate the custom domain to simplexr.bugaboostudio.com.br. I don't want to use the www/@ (apex) and I just created the subdomain "simplex.bugaboostudio.com.br.". Amplify successfully completes steps 1 and 2 (SSL Creation / SSL Configuration) but fails to attempt the third step: Domain Activation. Please let me know what I'm doing wrong.

**Error message**
Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
My DNS Server doesn't support ANAME/ALIAS.
![image](https://user-images.githubusercontent.com/4295173/101399178-05176a00-38c7-11eb-9a44-7b5762708c64.png)

Thank you in advance.

**Comment by hsspain** [comment]
@leandrodamascena It appears that the domain you are attempting to associate with this application is already associated with another CloudFront distribution.  You or whoever associated that will need to remove it from that distribution before you can associated with this app.

**Comment by leandrodamascena** [comment]
Thank you my friend! I don't know what's happened, but the application was deployed in ap-northeast-1 and we don't use this! I removed the app and now I think it's working.

Thank you so much.
