### ISSUE TITLE
No Github Repos Appear In AWS Amplify "Add repository branch" Page

### ISSUE THREAD

**Issue by mrubin-cornell** [aws-amplify/amplify-console#1347]
When starting a new AWS Amplify project, no Github repos qppear in the AWS Amplify "Add repository branch" page.

**To Reproduce**
1. Go to the AWS Console Amplify page https://us-west-2.console.aws.amazon.com/amplify
2. Click on Deliver\Host your web app\Get Started
3. In the "Host your web app" page, in "From your existing code" select "Github" , the Continue
4. Follow authentication instructions
5. See "GitHub authorization was successful" message
6. "Recently updated repositories" contains no repos

**Expected behavior**
"Recently updated repositories" contains 20 repos

**Comment by hsspain** [comment]
@mrubin-cornell Can you verify that the Github account your are currently logged into is the same account that houses the repositories you are expecting in the Amplify console?

**Comment by mrubin-cornell** [comment]
Verified.

Michael Rubin
Data Architect
Cornell Pump Company | Clackamas, OR 97015 | 503.653.0330

________________________________

**Comment by mrubin-cornell** [comment]
This issue has been open a long time, and it's fairly pressing.
When can I expect some assistance?

**Comment by hsspain** [comment]
@mrubin-cornell We are actively looking into this and have been unable to reproduce the behavior so far. 

One way to possible work around the issue would be to log in using your browser in Incognito mode.  Can you try that and let us know if it then works?

You can email aws-amplify-customer@amazon.com with any GitHub repository details that could help use further help if possible.

**Comment by mrubin-cornell** [comment]
This turns out to be an AWS Amplify Console issue, and I've updated a ticket with that service.
I'll close the issue.

Thanks

**Comment by rafaelfaria** [comment]
I am having similar issues, with the main difference being i can see all my branches except `development`. 
Note: this branch was connected before and i disconnected it. Now i can't connect it again.

**Comment by Decentrana1** [comment]
Having same issue today

**Comment by hloriana** [comment]
Hi @Decentrana1 and @rafaelfaria  👋🏽 thanks for reaching out. Can you try reconnecting Amplify to your GitHub account? in GitHub, navigate to settings -> applications -> Authorized OAuth Apps and revoke permissions. You should then be prompted to grant access again once you try to create a new app.
