### ISSUE TITLE
Missing Favicon

### ISSUE THREAD

**Issue by wbeyda** [aws-amplify/amplify-console#1348]
**Describe the bug**
favicon.ico not showing up in browsers. If I inspect the element and open in new tab it opens the favicon location with a trailing forward slash. 

**To Reproduce**
1. Go to 'www.fullstackcheatcodes.com'
2. Look at browser. No favicon image
3. inspect element Line 32  <link rel="shortcut icon" href="favicon.ico" type="image/jpg">
4. Right click on the link and open in a new tab
5.URL is directed to https://www.fullstackcheatcodes.com/favicon.ico/
6. try URL without trailing slash https://www.fullstackcheatcodes.com/favicon.ico
7. Still redirected

**Expected behavior**
Site has Favicon on localhost

**Screenshots**
localhost has favicon
![Screenshot from 2020-12-07 14-58-02](https://user-images.githubusercontent.com/3403342/101410517-b523ad80-389c-11eb-8008-22ecea478b6d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.02
 - Browser Firefox
 - Version [e.g. 83]

**Comment by hsspain** [comment]
@wbeyda This can happen if somehow the favicon was not included in your build.

However, when navigating to https://www.fullstackcheatcodes.com/favicon.ico, I see the favicon loaded.  Can you verify the behavior still persists from your end?

**Comment by wbeyda** [comment]
I still can't go to that URL. It
![Screenshot from 2020-12-07 16-21-22](https://user-images.githubusercontent.com/3403342/101417037-48161500-38a8-11eb-954f-ca868292c85e.png)
 just redirects me with a trailing forward slash to https://www.fullstackcheatcodes.com/favicon.ico/

**Comment by hsspain** [comment]
@wbeyda Can you clear your browser cache and try again?  It may have a cached a response that redirects to the forward slash.

**Comment by wbeyda** [comment]
Okay that was it. I didn't clear my cache. Thank you. We can close this issue.
