### ISSUE TITLE
Module not found '../aws-exports'

### ISSUE THREAD

**Issue by masapasa** [aws-amplify/amplify-console#1349]
Module not found: Can't resolve '../aws-exports' in '/codebuild/output/src240068493/src/nnews/next/pages'
build:
commands:
echo Amplify build...
amplifyPush --simple
While deploying through the console with an ECR image
Can someone please help?

**Comment by masapasa** [comment]
@sammartinez I did. The first deployment works. Then I change something and git push. Amplify automatically starts to build. During frontend build I see this error. Any hints?

**Comment by ericclemmons** [comment]
Can you share your full `amplify.yaml`?  This looks like a Next.js site, so I assume you're using `next build && next export` to build?

**Comment by masapasa** [comment]
@ericclemmons I am trying to deploy this https://github.com/jkahn117/aws-news/blob/master/amplify.yml
The first deployment works. Then `amplify env pull` and change something and `git push` then amplify builds both backend and frontend automatically. Then I get this error

**Comment by nimacks** [comment]
@masapasa are you still facing issues here?

**Comment by medelman17** [comment]
Linking to related issue for tracking purposes: https://github.com/aws-amplify/docs/issues/503

**Comment by swaminator** [comment]
Please refer to this https://aws.amazon.com/blogs/mobile/complete-guide-to-full-stack-ci-cd-workflows-with-aws-amplify/ improvement we've made. You can now connect a frontend to a backend without checking in the aws-exports.

**Comment by pencilcheck** [comment]
https://stackoverflow.com/questions/27502608/resolving-require-paths-with-webpack

I used the answer
```
var req = require.context('../../mydir/', true)
// true here is for use subdirectories, you can also specify regex as third param

return req('./myfile.js')
```
