### ISSUE TITLE
Automatic building fails due to @model(subscriptions: { level: public })

### ISSUE THREAD

**Issue by nookale** [aws-amplify/amplify-console#135]
**Describe the bug**
"subscriptions: { level: public }" works fine with my development environment (manually amplify pushing the backend from the command prompt), but it actually fails during the building phase of the test environment where I am using Amplify Console and GitHub for automating the process. This is part of the output generated by Amplify Console during the building:

2: @model(subscriptions: { level: public })
^
3: @key(
Field "level" is not defined by type ModelSubscriptionMap.
GraphQL request (143:26)
142: }
143: subscriptions: { level: public }
^
144: )
at GraphQLTransform.transform (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/GraphQLTransform.js:191:19)
at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js💯49
at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:43:23)
at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:24:53)
at fulfilled (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:15:58) name: 'SchemaValidationError' }
2019-09-20T02:52:06.165Z [ERROR]: !!! Build failed
2019-09-20T02:52:06.165Z [ERROR]: !!! Non-Zero Exit Code detected

**To Reproduce**
- Create react app.
- Amplify init, environment name "dev"
- Amplify add env "test".
- Amplify add api to "dev" => graphQL.
- Init git repository with branches "dev" and "test".
- Connect app in amplify console and add branch test
- Create schema.graphql (see **Sample Code** below) at amplify branch "dev"
- push branch "dev" (amplify push). It should work correctly.
- Git add and commit changes and git push to git branch "dev".
- Git checkout "test" branch, git merge "dev", git push origin test
- Check in the amplify console whether the build fails. 

**Expected behavior**
Amplify console builds and deploys correctly the environment

**Additional context**
Amplify documentation seems to be outdated (https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js) since it asks for using uppercases in "PUBLIC". However lowercases seems to be the correct way to go (as per: https://github.com/aws-amplify/amplify-cli/pull/2177).

Moreover, it seems that "identityClaim" could have a documentation-implementation problem too. It appears in the documentation (https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js) but it fails too in Amplify Console during the building process <<Field "identityClaim" is not defined by type AuthRule; Did you mean identityField?>>

**Sample code**
type Cars
    @model(subscriptions: { level: public })
    @key(
        name: "ByDesigner"
        fields: ["designerId", "createdAt"]
        queryField: "carsByDesigner"
    )
    @auth(
        rules: [
            { allow: owner, ownerField: "designerId" }
        ]
    ) {
    id: ID!
    designerId: String
    name: String!
    description: String
    createdAt: String
}

**Comment by swaminator** [comment]
@nookale can you try using the latest version of the CLI at build time? https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates

**Comment by nookale** [comment]
@swaminator Yes! It worked! Thank!
