### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by fennean1** [aws-amplify/amplify-console#1350]
**App Id**: dj787nksbarkg
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by hsspain** [comment]
@fennean1 Are you having issues setting up a custom domain?  This process can take a while.  Ensure your CNAMEs are configured properly and your domains should be verified in time.

**Comment by fennean1** [comment]
This is what I'm getting after all the CNAMEs are configured properly.

[image: Screen Shot 2020-12-08 at 2.19.10 PM.png]

So far I've tried creating a CAA record for the domain in Route 53 and
requesting a certificate. My certificate was denied for the same reason
shown above.

- Andrew

**Comment by hsspain** [comment]
@fennean1 I am sorry, but the screen shot did not come through.  What errors are you seeing?

**Comment by fennean1** [comment]
It reads:

The status of this certificate request is Failed. One or more domain names
have failed validation due to Certificate Authority Authentication Error.

I've connected all the DNS/CNAME files and the SSL configuration succeeds.
It's the domain activation that doesn't work.

Not sure what the issue is, I had no trouble hosting this on heroku with
the same custom domain.

- Andrew

**Comment by hsspain** [comment]
@fennean1 Can you try removing the custom domain and re-adding?

**Comment by fennean1** [comment]
Yes I have tried that many many many times.

**Comment by hsspain** [comment]
@fennean1 You may be running into issue due to using that domain with a different provider in the past.  Ensure that you follow the docs as linked here:

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html

The SSL certificates should be automatically created for you through our process.
