### ISSUE TITLE
Update item via GraphQL API appends to array of strings instead of replaces

### ISSUE THREAD

**Issue by jknapp25** [aws-amplify/amplify-console#1351]
**Describe the bug**
When I update an array of strings field ([String]) on one of my tables via my AppSync GraphQL API. The field is appending items to the array instead of replacing the array. This was not happening before yesterday though, I made no changes to the specific field in the schema.

**To Reproduce**
1. Update an array of strings field
2. See appended additions

**Expected behavior**
What was happening was when I called updateConfiguration it was replacing the array with the updated one. Which is desired. Now it's appending.

**Screenshots**
Request:
<img width="409" alt="Screen Shot 2020-12-08 at 10 06 31 AM" src="https://user-images.githubusercontent.com/3934326/101523291-42b6da00-393d-11eb-84ab-dcff505aa77b.png">

Response:
<img width="524" alt="Screen Shot 2020-12-08 at 10 08 29 AM" src="https://user-images.githubusercontent.com/3934326/101523539-96c1be80-393d-11eb-99ff-9ef5b7b63f8e.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: 86.0.4240.198

**Smartphone (please complete the following information):**
Not using a smartphone

**Comment by swaminator** [comment]
@jknapp25 could you please post here instead: https://forums.aws.amazon.com/forum.jspa?forumID=280.
