### ISSUE TITLE
Error updating repository (e.g. Gitlab repo to Github repo)

### ISSUE THREAD

**Issue by quiquegarcia** [aws-amplify/amplify-console#1352]
**Describe the bug**
I created an App with a Gitlab repository, added backend functionality and months later want to change my Git provider to Github.

Tried re connecting branch from the AWS console web and only branches in Gitlab were detected, so I tried via AWS Cli and repository was updated, but now I cannot update my app or access to re connect my new branch. 

**To Reproduce**
1. Create an app and connect a repository with Gitlab
2. Create a personal token on Github (new repository provider) with repo permissions
3. Update repository with command: ```aws amplify update-app --repository git@github.com:example/repo.git --access-token token```
4. Try to update the app with a commit or go to AWS Amplify Console and try to re connect branch

**Expected behavior**
Making new pushes to master branch updates the app automatically or access the AWS Amplify console to re connect another branch on Github without re create the backend resources previously created.

**Screenshots**
New repository updated via AWS Cli:
![image](https://user-images.githubusercontent.com/286159/101525874-8582ad00-3951-11eb-8e76-aeb8d3a86c79.png)

Cannot re connect branch from AWS Amplify console:
![image](https://user-images.githubusercontent.com/286159/101526881-dfd03d80-3952-11eb-8f83-d9292fc0b0b0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, macOS
 - Browser: Chrome, Firefox
 - Version: 87.0.4280.88, 84.0.b8 (developer) respectively

**Comment by hsspain** [comment]
@quiquegarcia We are currently investigating this issue and will update you as we reproduce and track down a solution.

**Comment by swaminator** [comment]
@quiquegarcia we do not currently support this workflow.
