### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by keanthai** [aws-amplify/amplify-console#1354]
**App Id**: d2x8tcretx2z4u
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by hsspain** [comment]
@keanthai It can sometimes take a while to verify your custom domain with Amplify. 

If you are having issue with adding a custom domain to your app, clicking "Retry" after a failure or removing and re-adding the domain can sometimes get around issues.  Please let us know if you are seeing a specific error.
