### ISSUE TITLE
Amplify codegen api (appsync) does not create aws_appsync_* settings in aws-exports.js from Console

### ISSUE THREAD

**Issue by icecog** [aws-amplify/amplify-console#1355]
Hi,
I have imported an AppSync api (GraphQL) and everything works fine locally.
But when I push the code to the cloud I am getting the error "No graphql endpoint provided." in the chrome console.

On further inspection (export everything from build through amplify.yml) I see that aws_appsync_ settings are missing in aws-exports.js.

I have been having major issues with all kinds of things, so I may be shooting myself in the foot here without realizing it.
I have imported a Cognito User pool, and am using federatedsingin. [This creates a problem in AmplifyPush --simple as described here.](https://github.com/aws-amplify/amplify-console/issues/1341#issuecomment-739532719)

So now I have a modified AmplifyPush script and so it might be at fault here, but there is no way for me to know. I've tried looking at the amplify-cli code, but its gibberish to my eyes.

Thoughts?

Using Amplify version 4.38.2 locally and in the Console via _LIVE_UPDATE environment variable.

(Of course, it works when I manually set the aws_appsync_ config in code, but that is not a solution imho)

**Comment by ganipcanot** [comment]
Closing due to age - please re-open if you are still experiencing issues.
