### ISSUE TITLE
Amplify unable to pull backend after importing existing storage

### ISSUE THREAD

**Issue by ayotise** [aws-amplify/amplify-console#1359]
I imported an existing storage by following the instructions [here](https://aws.amazon.com/blogs/mobile/use-an-existing-s3-bucket-for-your-amplify-project/). It works fine locally, but the build pipeline fails when i pushed the code.

1. Follow the 'Import an existing S3 bucket into your Amplify project' instructions on [here](https://aws.amazon.com/blogs/mobile/use-an-existing-s3-bucket-for-your-amplify-project/)
2. push the code to your branch already setup for the amplify CI/CD.
3. build fails with the below error:
`2020-12-10T14:48:44.753Z [WARNING]: ✖ There was an error initializing your environment.
2020-12-10T14:48:44.754Z [INFO]: [31mFailed to pull the backend.[39m
2020-12-10T14:48:44.756Z [INFO]: [31mstorage headless is missing the following inputParams bucketName, region[39m
2020-12-10T14:48:44.759Z [INFO]: [0mError: storage headless is missing the following inputParams bucketName, region[0m
                                 [0m    at ensureHeadlessParameters (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/import/import-s3.ts:443:11)[0m
                                 [0m    at headlessImport (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/import/import-s3.ts:392:40)[0m
                                 [0m    at exports.importedS3EnvInit (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/import/import-s3.ts:294:18)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/index.js:84:72)[0m
                                 [0m    at /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/index.js:147:22[0m
2020-12-10T14:48:44.775Z [ERROR]: !!! Build failed
2020-12-10T14:48:44.775Z [ERROR]: !!! Non-Zero Exit Code detected`

**Expected behavior**
build should not fail

**Screenshots**
<img width="1026" alt="Screen Shot 2020-12-10 at 10 37 02 AM" src="https://user-images.githubusercontent.com/30660157/101793329-a96dfc00-3ad3-11eb-87ef-f35661c84d2d.png">

**Comment by hsspain** [comment]
@ayotise The fix for this issue has been identified and is currently being rolled out to all regions.  We will update this thread as the roll out completes.

**Comment by stleon** [comment]
The same bug, do you have any updates?

**Comment by hsspain** [comment]
To resolve this error please add the following variables to your environment variables in your build:

AMPLIFY_STORAGE_BUCKET_NAME
AMPLIFY_STORAGE_REGION

These values should correlate to the bucket name and region for your imported storage.

This documentation will guide you to the right page to add these settings:

https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html

Please let us know if there are further issues.

**Comment by ayotise** [comment]
Works fine after adding the environment variables! Thank you so much!

**Comment by ddotx** [comment]
But not work for me when import dynamo and build,

**Comment by ncyaodi** [comment]
Also have the same error, added variables to environment variables as suggested, 
![image](https://user-images.githubusercontent.com/12124635/112088530-3b62b780-8b4d-11eb-81f9-4cf0894faa52.png)

but still has the same error
![image](https://user-images.githubusercontent.com/12124635/112088647-74029100-8b4d-11eb-875d-3cbb741e1492.png)

The difference is this is my first build, with new backend initiated. Not sure that's the reason.

Please help.

**Comment by darellchua2** [comment]
I am also facing the same issue. even after adding the params. it doesnt work. do we need to add in something to the build settings?

**Comment by JuarezCout** [comment]
Still having this issue. Created the environment variables but still returning the same message.
