### ISSUE TITLE
Amplify CLI (Cloudfront) Hosting in Amplify Console

### ISSUE THREAD

**Issue by MartinPindel** [aws-amplify/amplify-console#136]
** Please describe which feature you have a question about? **
Cloudfront (+S3) Hosting

If I add Hosting in the Amplify CLI, a S3-bucket and Cloudfront will be generated and it is visible in the AWS Console.
If I add this project to the Amplify Console (via CodeCommit repository), these objects will be still generated, but the domain leads to an Amplify hosted website.

**Is it possible to lead to the Cloudfront distribution created by Amplify CLI? Or edit the Amplify Console Cloudfront distribution?**

** Provide additional details**
Angular project with API, Auth, Hosting and Storage
CodeCommit Repository

Greetings
_Martin_

**Comment by swaminator** [comment]
Currently the hosting options available in the Amplify Console and CLI are different. Amplify Console offers fully managed hosting with features such as instant cache invalidation, atomic deploys, easy custom domain setup, and redirects. The CLI offers hosting with S3 and CloudFront. To view those resources please visit the CloudFront and S3 consoles respectively.
