### ISSUE TITLE
Cannot delete orphaned app (arn:aws:amplify:us-east-2:185474005990:apps/di7uniydin0nj)

### ISSUE THREAD

**Issue by slingle** [aws-amplify/amplify-console#1361]
**Describe the bug**
Am unable to delete app after deleting stack from CloudFormation 

**To Reproduce**
1. Create app with backend (i.e "dev")
2. Delete environment's stack manually from CloudFormation console
3. Attempt to delete app from Amplify console using Action > Delete App
4. Deletion failed with message "Removing backend envs for app di7uniydin0nj failed"

**Expected behavior**
The app would be removed from the console

**Additional context**
1. This app is in region us-east-2
2. Per Attempted (Per [#1330](https://github.com/aws-amplify/amplify-console/issues/1330)) using the cli with `aws amplify delete-backend-environment --app-id di7uniydin0nj --environment-name dev` but received `An error occurred (NotFoundException) when calling the DeleteBackendEnvironment operation: App di7uniydin0nj not found`

**Comment by swaminator** [comment]
@slingle can you try again?

**Comment by marlonmarcello** [comment]
I have the exact same issue. Made sure the region and profile were set and correct as well when running the cli command.

**Comment by slingle** [comment]
Good morning, 

Sorry.   I should have closed this but it skipped my mind.  The problem turned out to be an S3 bucket still associated with the app.  I deleted it (after making sure 8 times that it was the right bucket) and was then able to delete the 'stale' app through the Console.  

Cheers, 
Scott
