### ISSUE TITLE
Conditional front end and back end builds

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-console#1367]
**Is your feature request related to a problem? Please describe.**
Wasting time and resources building back end when there are no changes to the back end, only front end and vice versa.

**Describe the solution you'd like**
Ability to check the commits file changes for a directory and decide based on results which build to run. 

For example, using create react app. If all the changes are in the src directory then only run the front end build. If all the changes are in amplify directory only run back end build. If changes are both in amplify and src directories then run both back end and front end builds

**Comment by VictorCcccc** [comment]
Hi @kldeb , Thanks for reaching out. Sorry, Currently we don't support this feature. However, I'll note this as a feature request.

**Comment by swaminator** [comment]
@kldeb we added support conditional backend builds: https://docs.aws.amazon.com/amplify/latest/userguide/conditional-backends.html
