### ISSUE TITLE
Problem loading application

### ISSUE THREAD

**Issue by kontrol-debug** [aws-amplify/amplify-console#137]
Hi,

I launched my react web application using amplify, everything was success, my domain and all everything was verified. When i open the url. I get this error. 
"""
The page isn’t redirecting properly
An error occurred during a connection to www.kontrol.ai.
This problem can sometimes be caused by disabling or refusing to accept cookies.
"""
Please provide guidance

**Comment by hzhenmin** [comment]
@kontrol-debug Can you check if www.kontrol.ai/index.html is a valid path? By default we redirect all error page to /index.html. If /index.html is also an error page, it will cause loop in redirect. If you do not want this default settings, you can delete in rewrites and redirects page.

**Comment by kontrol-debug** [comment]
HI, @hzhenmin I have changed the redirects also. But my web application still doesn't runs.

**Comment by garyleefight** [comment]
Hi, @kontrol-debug. Looks like your site is available. Do you still have problems?

**Comment by kontrol-debug** [comment]
NO there was some issue with redirects. Thankyou. 
You can close this issue.
