### ISSUE TITLE
Domain activation is Failed - Amplify fails in the domain activation stage.

### ISSUE THREAD

**Issue by ehcloninger** [aws-amplify/amplify-console#1370]
**App Id**: d3qu1a8apcj4sd
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Amplify fails in the domain activation stage.

**Error message**

One or more of the CNAMEs you provided are already associated with a different resource. 

**Additional information**

The domain is registered in Route53. When I started the domain management task, there were 3 entries in the record set
* NS entry
* SOA entry
* CNAME entry for the staging site (staging.mydomain.com) that's stored in S3. This subdomain is not one of the 2 that were part of the request. Those were mydomain.com (A) and www.mydomain.com (CNAME). The entries are created in Route53, but it appears that the build results do not end up there.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by brnmye** [comment]
We are going to close out this issue, but please feel free to re-open if you still need help.
