### ISSUE TITLE
Connecting Amplify backend to database hosted on AWS RDS - Oracle engine

### ISSUE THREAD

**Issue by dattnguyen** [aws-amplify/amplify-console#1372]
I'm trying to connect the backend of an app deployed on Amply to the database hosted on AWS RDS with this end-point (cis550proj.cfot25rjb5mg.us-east-1.rds.amazonaws.com/jeopardy). I can't seem to find a guide on how to do that. I'd appreciate some guidance! 

App ARN
arn:aws:amplify:us-east-2:013572940482:apps/d2wl5rf10nvk8w

**Comment by siegerts** [comment]
Hi @dattnguyen, you can connect relational DBs via the Amplify CLI - https://docs.amplify.aws/cli/graphql-transformer/relational

> The Amplify CLI currently supports importing serverless Amazon Aurora MySQL 5.6 databases running in the us-east-1 region. The following instruction show how to create an Amazon Aurora Serverless database, import this database as a GraphQL data source and test it.

Or, you can connect to your DB via a [Lambda Function created by Amplify](https://docs.amplify.aws/cli/function) using a client library, for example, in Python or Nodejs. This functionality is not in Amplify out-of-the-box and would require some custom logic.

Hope that this helps!
