### ISSUE TITLE
App not in Console

### ISSUE THREAD

**Issue by Haga14** [aws-amplify/amplify-console#1373]
**Describe the bug**

I created a Vue Amplify project a few months ago and I just published it a few days ago. The app publishes fine and every thing works perfectly at the web address provided by the Amplify CLI. However, the app isn't listed in the Amplify console and when I run amplify console the address console takes me to doesn't include the app region. When the amplify console opens it throws an error: "App with id: ******* not found"

 I've been told this usually happens this usually happens when the current region and the region of the app console is attempting to open aren't the same. This isn't my case. The region I'm and what's listed in the aws-exports match

Furthermore, the artifact bucket exists in S3.

For security reasons, I've sent the app id and the link generated by the amplify console command in a private message to Rene Brandel.

I'm not sure how this would be reproduced as I'm not sure what's causing the error.

Additionally, I believe this is specific to my current project as I've succesfuly created and deployed apps that are currently listed on the Amplify console.

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by kaustavghosh06** [comment]
@Haga14 Do you know when you'd created this app using the CLI? Was it prior to 2019 December? Also, if you go to Amplify Console in the correct region to which the CLI project is deployed, do you see the app listed? You can find the deployed region locally in your `amplify/backend/amplify-meta.json` file.

**Comment by Haga14** [comment]
> @Haga14 Do you know when you'd created this app using the CLI? Was it prior to 2019 December? Also, if you go to Amplify Console in the correct region to which the CLI project is deployed, do you see the app listed? You can find the deployed region locally in your `amplify/backend/amplify-meta.json` file.

No, it doesn't appear in the region listed in the file you mentioned here.

I created the project around September/October 2020

**Comment by swaminator** [comment]
@Haga14 can you send the appId located in in amplify/backend/amplify-meta.json or amplify/team-provider-info.json

**Comment by kaustavghosh06** [comment]
<img width="880" alt="Screen Shot 2020-12-17 at 9 04 33 AM" src="https://user-images.githubusercontent.com/7247658/102519119-f22f3300-4046-11eb-9fe9-515d049442ad.png">
The amplify-meta.json would look like the above and the AmplifyAppId is the appId which we're requesting for. If you observe it also has 'Region'.

**Comment by Haga14** [comment]
> @Haga14 can you send the appId located in in amplify/backend/amplify-meta.json or amplify/team-provider-info.json

Yes, I already sent it to Rene Brandel on discord.

I can send it privately again if you can provide me with an email though

**Comment by Haga14** [comment]
Any updates on this?
