### ISSUE TITLE
Domain activation is Failed - Issues Registering a Domain Name with Third Party

### ISSUE THREAD

**Issue by maczamora** [aws-amplify/amplify-console#1374]
**App Id**: d23hqgatm5w7hr
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I've attempted to register three different domain name with the following format dev.***.***.com = dev environment, staging.***.***.com staging environment and transfer.***.com = prod each mapping to a particular environment to keep releases simple.

The first domain name for dev worked flawlessly with no issues, staging had an issue domain activation at some point. It turns out the retry activation ends up issuing a new cloudfront id which I read about somewhere else in AWS documentation. Finally to fix staging I removed the domain name from AWS Amplify and also worked with our DNS team to remove it from our DNS system. Afterwards I went ahead and registered it first on the Amplify side and about a day or so later had the DNS team copy of the DNS record information and it worked find.

I think I I might be hitting the same problem with out production domain name but it's just really odd that our staging and prod domain name ran into these issues but the dev domain name worked fine.

**Error message**
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem.

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by maczamora** [comment]
Hi @brnmye! No issues, I guess the documentation is literal when it comes down to the setup for the domain name. You actually have to wait for the domain activation to go through before you even register the domain with your third party domain provider. It would be great to make that text a little bit bigger or make a note about the domain activation succeeding first before registering. I think the text is in small grey print for the official documentation.
