### ISSUE TITLE
Domain activation is Failed

### ISSUE THREAD

**Issue by tparigi** [aws-amplify/amplify-console#1375]
**App Id**: d1zzhxo7z7xvoc
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

I'm trying to activate a domain (swimfire.com) from a recently transferred domain that was at GoDaddy and is now at Route53.  I only have the www subdomain.  It fails at Domain Activation after SSL has been configured.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
![image](https://user-images.githubusercontent.com/5421477/102154816-cee66700-3e3f-11eb-9e28-47428e58edbb.png)

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by hsspain** [comment]
It looks like swimfire.com is already use for another AWS resource.  You will need to remove it from the other resource to add to an Amplify app. We are going to close this issue.  Please let us know if you need further assistance.
