### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by martinriafy** [aws-amplify/amplify-console#1378]
**App Id**: d1lxf1wbkd51eu
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Not able to activate the domain

**Error message**
Activation failed/ Screenshot attaching with the case 

 

**Additional information**
It was pointed to cloud front distribution and was a s3 hosting . we have moved the hosting to amplify. While adding the custom domain I am getting this issue  

![image](https://user-images.githubusercontent.com/68897237/102215509-d0776400-3eff-11eb-879b-dafc6445515f.png)

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by hsspain** [comment]
We are going to close this issue.  Please let us know if you need further assistance.
