### ISSUE TITLE
SSL configuration is Running - [More than 8 hours]

### ISSUE THREAD

**Issue by rlele10** [aws-amplify/amplify-console#1381]
**App Id**: d19lms38rip60s
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Application is stuck in SSL configuration for more than 8 hours. we are using google domain to host our application and CNS records has been updated and verified at google side.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

<img width="1196" alt="Screen Shot 2020-12-16 at 10 21 06 AM" src="https://user-images.githubusercontent.com/66637568/102383105-6e167600-3f88-11eb-9f42-d1c2158059cc.png">

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by brnmye** [comment]
We are going to close out this issue, but please feel free to re-open if you still need help.
