### ISSUE TITLE
Domain activation is Failed - [Remove domain from one app and add to another one]

### ISSUE THREAD

**Issue by Preejith-Ponneth-Bose** [aws-amplify/amplify-console#1382]
**App Id**: d1m62pook84kga
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Trying to update the domain
A clear and concise description of what the issue/question is.

**Error message**
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by 0xR** [comment]
same issue, how did you solve it?
