### ISSUE TITLE
Amplify Stuck at Deploy Step ("Updating edge config")

### ISSUE THREAD

**Issue by lijingshanxi** [aws-amplify/amplify-console#1387]
My amplify has been running ok, but when I add test stage, deploy will get stuck, the last log is: "Updating Edge config";
Is the artifacts file too large due to add the test phase;
My region is "eu-central-1";
![image](https://user-images.githubusercontent.com/13703027/102581379-65b26c80-413b-11eb-95fa-8459aaa19e70.png)
![image](https://user-images.githubusercontent.com/13703027/102581413-7b279680-413b-11eb-8125-a0c2b8f5673a.png)

Is there any way to workaroud it, thanks

**Comment by garyleefight** [comment]
Can you share your appId?

**Comment by lijingshanxi** [comment]
> Can you share your appId?

Hi, myappid is d2x1on421alk5v, the error is in Build 51;
![image](https://user-images.githubusercontent.com/13703027/102692034-c4ffa200-424b-11eb-8bda-3cff3ea86024.png)
![image](https://user-images.githubusercontent.com/13703027/102692042-ce890a00-424b-11eb-9d15-897a5af7c14a.png)

Sorry for my bad english;

Thanks a lot;

**Comment by lijingshanxi** [comment]
> Can you share your appId?

Hi, 
Now my issue is run away, thanks a lot;
