### ISSUE TITLE
[Access Control] Cannot exclude branches from global password.

### ISSUE THREAD

**Issue by namhong2001** [aws-amplify/amplify-console#1394]
**Describe the bug**
https://docs.aws.amazon.com/amplify/latest/userguide/access-control.html states setting branches exclusively from a global password but cannot set.

**To Reproduce**
1. Go to "Access Control"
2. Set "Apply a global password" on
3. Cannot set access setting "publicly viewable" for individual branch.

**Expected behavior**
Can set "publicly viewable" for individual branch when global password on

**Screenshots**
![image](https://user-images.githubusercontent.com/8140278/102738966-1795a700-438f-11eb-9d07-20e5ce6c9826.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: chrome
 - Version: Version 87.0.4280.88 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
None

**Comment by hsspain** [comment]
@namhong2001 Thank you for bringing this to our attention. We are updating our docs to reflect the way this feature works. You currently cannot override the global access controls at a branch level when global password is on.

I am closing this ticket, but please feel free to re-open if you have further questions.
