### ISSUE TITLE
Getting 403 error loading data when app is deployed

### ISSUE THREAD

**Issue by KhanDoors** [aws-amplify/amplify-console#1398]
Getting 403 error loading data when app is deployed. 
This is usually what i see when an S3 bucket is not configured correctly.
How does that facture in here? 
What setting do I have to change in order to load data when deployed? 
I have no authentication, Cognito is not being used. 

This is not an issue when running the app locally. 
This happens when the app is deployed thru github but not when i upload the build file directly. 

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>D555AFCA2124EBDC</RequestId>
<HostId>4cxFFMe7Ur6YfrApt7664EJR6sbXAz9kaz2HEAA1ReyfUg9KiwnhyjfK6Deh4xwSVcomhJ1xBOE=</HostId>
</Error>`

**Comment by 9037568** [comment]
Isn't this the same as #1403 ?

**Comment by KhanDoors** [comment]
yeah they got duped somehow
