### ISSUE TITLE
Getting AccessDenied 403 error loading data when app is deployed

### ISSUE THREAD

**Issue by KhanDoors** [aws-amplify/amplify-console#1403]
Getting 403 error loading data when app is deployed.
This is usually what i see when an S3 bucket is not configured correctly.
How does that facture in here?
What setting do I have to change in order to load data when deployed?
I have no authentication, Cognito is not being used.

This is not an issue when running the app locally.
This happens when the app is deployed thru github but not when i upload the build file directly.

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>D555AFCA2124EBDC</RequestId>
<HostId>4cxFFMe7Ur6YfrApt7664EJR6sbXAz9kaz2HEAA1ReyfUg9KiwnhyjfK6Deh4xwSVcomhJ1xBOE=</HostId>
</Error>`

**Comment by KhanDoors** [comment]
tried this but didnt work. what I did:
1. I manually ran npm run build to make sure there was a build directory
2. i pushed to github
3. once i deployed to github it triggered an Amplify redeploy. 
4. same result <Code>AccessDenied</Code> in the deployed version.

the app deploys fine but the data from the backend doesnt load, i get that `Failed to load resource: the server responded with a status of 403 ()`

the data loads fine from the backend locally `http://localhost:3000/`

a little confused about this??

**Comment by 9037568** [comment]
I can confirm this. Getting the same thing after pushing new routes/pages to codecommit.

**Comment by uncodable** [comment]
@KhanDoors @9037568 Can you share your `amplify.yml` and maybe a tree to show how your app is structured.

**Comment by 9037568** [comment]
Where would amplify.yml be? I don't seem to have one...

**Comment by 9037568** [comment]
Here's the top level directory listing, if that's what you mean by "tree". If not, what does "tree" mean here?

````
01/02/2021  09:36 AM    <DIR>          .
01/02/2021  09:36 AM    <DIR>          ..
12/23/2020  04:16 PM               703 .browserslistrc
12/23/2020  04:16 PM               274 .editorconfig
01/01/2021  03:52 PM                10 .eslintignore
12/23/2020  10:39 PM               991 .gitignore
01/02/2021  09:36 AM               380 .graphqlconfig.yml
12/23/2020  09:55 PM    <DIR>          .vscode
01/02/2021  11:56 AM    <DIR>          amplify
12/23/2020  04:16 PM             3,543 angular.json
12/23/2020  04:16 PM    <DIR>          e2e
12/23/2020  04:16 PM             1,424 karma.conf.js
12/29/2020  01:01 PM    <DIR>          node_modules
12/29/2020  12:47 PM           646,471 package-lock.json
12/29/2020  01:18 PM             1,342 package.json
12/23/2020  04:16 PM             1,016 README.md
01/02/2021  09:36 AM    <DIR>          src
12/24/2020  09:48 AM               293 tsconfig.app.json
12/23/2020  04:16 PM               458 tsconfig.json
12/23/2020  04:16 PM               333 tsconfig.spec.json
12/23/2020  04:16 PM             3,185 tslint.json
````

**Comment by kahdojay** [comment]
@KhanDoors @9037568 (and others experiencing the same issue) can you provide your appId, region, and example job number(s)?

Also a repro would be helpful, whether it's just a url where it's currently happening or a sample repo we can deploy into a test app for ourselves.

**Comment by 9037568** [comment]
@kahdojay Here's a URL that's showing the error:
https://staging.d3i6qq3wkx2032.amplifyapp.com/models/

Also happy to supply a reproducible scenario if you can tell me how to copy/package/send it...

**Comment by kahdojay** [comment]
@9037568 you can share it with me on Github and email details to aws-amplify-customer@amazon.com

**Comment by 9037568** [comment]
>For the link you shared, did you attempt to deploy models/index.html?

Why would I? There's no need for it. When I run the app locally, it works.
So it's not "happening because the file doesn't exist". Amplify is doing something wrong with the way it's handling things in the deployed application.

>If you still need to send details 

What details do you want to see? Everything is stored in AWS; is there no way for you to just dig into it?

**Comment by kahdojay** [comment]
@9037568 if you wanted to send the repro scenario but the url you shared is fine. Can you try adding the SPA redirect rule since you have an Angular app:

https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa

@KhanDoors also let us know if you're still experiencing the issue, if so please provide appId and example URL

**Comment by 9037568** [comment]
> @9037568 if you wanted to send the repro scenario but the url you shared is fine. Can you try adding the SPA redirect rule since you have an Angular app:
> https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa

Yes, I have done that, and it does work around the problem. But isn't the point that it shouldn't be necessary? Angular apps deployed to non-AWS systems don't require this, do they?
