### ISSUE TITLE
SSL configuration is Running - We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain.

### ISSUE THREAD

**Issue by ravishwetha** [aws-amplify/amplify-console#1404]
**App Id**: dgsm7ukbj14z0
**Region**: ap-southeast-1
**Step**: SSL configuration
**Status**: Running

**Issue/question**
Verifying ownership of domain is taking ore than 8 hours after updating DNS records.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by hsspain** [comment]
We are going to close out this issue, but please re-open if you still need assistance.
