### ISSUE TITLE
AWS Amplify publish problem

### ISSUE THREAD

**Issue by BranislavBogicevic** [aws-amplify/amplify-console#1408]
After amplify push command I try to execute amplify publish but in the end I got error:
An error occurred during the publish operation: User: arn:aws:sts::742600464877:assumed-role/us-west-2_NnLrZVKpP_Full-access/amplifyadmin is not authorized to perform: amplify:ListJobs on resource: arn:aws:amplify:us-west-2:742600464877:apps/d8qiqh93bcyjm/branches/dmgdevbbn/jobs/*

**Comment by tiago165** [comment]
I am having exactly the same issue for a while, unable to publish any Amplify project. I also tried with simple apps and get the same issue. I thought it was IAM issue and tried "amplify configure", created new IAM user, gave all admin permissions and the permissions documented [here](https://docs.amplify.aws/cli/usage/iam). I also tested the "amplify:ListJobs" policy and it is allowed but still facing the same issue. Unable to develop anything on Amplify.

Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
An error occurred during the publish operation: User: arn:aws:sts::033870858721:assumed-role/us-east-2_HsLadv6Y1_Full-access/amplifyadmin is not authorized to perform: amplify:ListJobs on resource: arn:aws:amplify:us-east-2:033870858721:apps/d2doxkl2ny58tj/branches/staging/jobs/*

**Comment by tiago165** [comment]
I solved the problem using this command:  `amplify configure project`

Got this trick from #1369
