### ISSUE TITLE
Domain activation is Failed - One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by marcschroeter** [aws-amplify/amplify-console#141]
**App Id**: d9kq0ggl8z9ty
**Region**: eu-central-1
**Step**: Domain activation
**Status**: Failed

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Notes**
We used the domain before for a CloudFront distribution but we deleted everything.

**Comment by garyleefight** [comment]
@marcschroeter I have checked the records. Looks like the domain status is available now. Free free to contact us if you still have problems.
