### ISSUE TITLE
Get 403 for deployed app

### ISSUE THREAD

**Issue by ggmon** [aws-amplify/amplify-console#1412]
** Please describe which feature you have a question about? **
I am  following the amplify tutorial  and it runs fine locally, I added hosting to it and then run amplify publish

** Provide additional details**
https://dev.dj0zfysg7ego3.amplifyapp.com/

I am getting 403 for main.bundle.js

**Comment by Athena96** [comment]
Hi @ggmon are you still facing this issue? I am able to load main.bundle.js for your site on my end:
![Screen Shot 2021-01-05 at 11 53 11 AM](https://user-images.githubusercontent.com/14256844/103692496-b05e2200-4f4c-11eb-913e-4012b57037c6.png)

**Comment by Athena96** [comment]
closing the issue, please let us know if you are still encountering it. Thanks!
