### ISSUE TITLE
Failed to set custom headers when deploying from S3

### ISSUE THREAD

**Issue by jeremyc11** [aws-amplify/amplify-console#1415]
I failed to set custom headers for my amplify frontend when deploying the frontend from S3. The deploy worked and it is written in the log: "Found customHttp.yml, applying custom headers..." but when checking the "App Settings -> Custom headers", the displayed customHttp.yml file is empty.

**To Reproduce**
1. Create the customHttp.yml file with security headers:
![image](https://user-images.githubusercontent.com/69188912/103417707-711e8280-4b94-11eb-9df2-7f4f328f3eec.png)

2. Set customHttp.yml file in the frontend zip file:
![image](https://user-images.githubusercontent.com/69188912/103416844-0586e600-4b91-11eb-8178-67a9fa9784e8.png)

3. Upload the zip file to S3
4. Deploy the frontend environment using "aws amplify start-deployment" command when the source url is the zip file in S3.
5. Go to: App Settings -> Custom headers, the displayed customHttp.yml file is empty.
![image](https://user-images.githubusercontent.com/69188912/103417272-b8a40f00-4b92-11eb-9cd5-a3eb252d2729.png)

Note: when editing manually the customHttp.yml file in the console, it worked.

**Comment by swaminator** [comment]
@jeremyc11 you need to be using Amplify Hosting to deploy your code *not* S3. https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html
