### ISSUE TITLE
Deployments Stuck: Updating Edge Config

### ISSUE THREAD

**Issue by mgurtzweiler** [aws-amplify/amplify-console#1417]
App Id: d14aghuo0noisk

Initial deployment after I hooked up to GitLab worked fine. All deployments since that initial one just get stuck on Deploy.

2021-01-01T20:19:24 [INFO]: Starting Deployment
2021-01-01T20:19:25 [INFO]: Updating Edge config

I had ONE deployment that failed with this error:

2021-01-01T19:44:15 [INFO]: Beginning deployment for application d14aghuo0noisk, branch:master, buildId 0000000004
2021-01-01T19:44:48 [ERROR]: Caught error downloading artifacts

The site is pretty large (3GB - lots of PDF's...) but I haven't seen any size limit or size error.

**Comment by mgurtzweiler** [comment]
Ok, cleaned up the repo and got the deploy down to 1.23GB and it seems to be deploying now.

Is there any way to exclude the `.git` folder from the deployment package? The site is only 600MB but since git keeps a copy of all objects in .git the "deployment" is currently double the size of the site.

**Comment by Athena96** [comment]
Hi @mgurtzweiler the `.git` folder doesn't need to be deployed. Is it being committed to your remote repo? The `.git` folder only needs to exist locally

**Comment by Athena96** [comment]
closing the issue, please let us know if you are still encountering it. Thanks!

**Comment by ryanbagwell** [comment]
I encountered this problem today. From the deploy phase log:

```
2021-01-12T16:00:05 [INFO]: Beginning deployment for application d2lnj6dcs32j7m, branch:master, buildId 0000000133
2021-01-12T16:01:10 [ERROR]: Caught error downloading artifacts
```

The build was stuck as "running" despite the fatal error, which prevented subsequent builds from starting too.

**Comment by ryanbagwell** [comment]
@Athena96 can you reopen this issue? Seems like it's continuing to occur intermittently.
