### ISSUE TITLE
Admin UI improperly handles the AWSDateTime type

### ISSUE THREAD

**Issue by 9037568** [aws-amplify/amplify-console#1419]
**Describe the bug**

The Admin UI improperly handles the AWSDateTime type:

* The user is only allowed to enter hours and minutes
![image](https://user-images.githubusercontent.com/9916473/103464625-3c7d0900-4d03-11eb-97ba-dbdd691e7af3.png)

* When the data is saved, the entered time is recorded as UTC time
![image](https://user-images.githubusercontent.com/9916473/103464647-6b937a80-4d03-11eb-89d6-5af02330a2a5.png)

**Expected behavior**
The user should be able to enter a full time string, in any of the supported formats.
* hh:mm:ss.sssZ
* hh:mm:ssZ
* hh:mmZ
* hh:mm:ss.sss±hh:mm:ss
* hh:mm±hh:mm
* etc.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 84.0.1

**Comment by uncodable** [comment]
Please share the issue on the Admin UI repo, https://github.com/aws-amplify/amplify-adminui

**Comment by 9037568** [comment]
Copied to Admin UI repo
