### ISSUE TITLE
Rewrite to Gatsby pre-rendered markup for pages

### ISSUE THREAD

**Issue by hotgazpacho** [aws-amplify/amplify-console#142]
** Please describe which feature you have a question about? **
I'm trying to set up my Gatsby site in the Amplify Console such that if I go directly to a page, say `https://redacted.dev/my-page`, it will serve up the pre-rendered html in `https://redacted.dev/my-page/index.html` that `gastby build` generates. 

Here's my current redirect setup:

```json
[
    {
        "source": "https://www.redacted.dev",
        "target": "https://redacted.dev",
        "status": "200",
        "condition": null
    },
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|woff2|ttf|map|json)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]
```

As it stands right now, accessing `https://redacted.dev/my-page` completely rewrites the url to `https://redacted.dev/`

_note: `redacted.dev` is not the actual domain name_

**Comment by hotgazpacho** [comment]
If I change my redirect setup as per below, then `https://redacted.dev/my-page/` works. However, if I omit the trailing slash (`https://redacted.dev/mypage`), it results in the 404.html being rendered.

```json
[
    {
        "source": "https://www.redacted.dev",
        "target": "https://redacted.dev",
        "status": "200",
        "condition": null
    },
    {
        "source": "/<*>",
        "target": "/404.html",
        "status": "404-200",
        "condition": null
    }
]
```

I think now I just need gatsby to render `/my-page.html` and not `/my-page/index.html`

**Comment by garyleefight** [comment]
@hotgazpacho Hi, could you clarify your question more clear? From your description, I think you do have content on /my-page/index.html and no content is rendered on /my-page.html. That's why your second rewrite rule rewrite /my-page.html to 404.
If you wants to rewrite /my-page.html to /my-page/index.html, you can simply write something like 
```json
{
        "source": "/my-page",
        "target": "/my-page/index.html",
        "status": "200",
        "condition": null
    }
```

**Comment by hotgazpacho** [comment]
Thinking about this some more, I think I’d really rather have Gatsby prerender it’s pages to `componentname.html`, instead of what it does by default: `componentname/index.html`, so that I can access any page by `/componentname`, without having to include the trailing slash. I was hoping I could accomplish this via a rewrite rule, for *all pages*.

**Comment by garyleefight** [comment]
@hotgazpacho Hi, 
```json
{
        "source": "/<path>",
        "target": "/<path>/index.html",
        "status": "200",
        "condition": null
}
```
This will help you match any path name with only one level. 
If you have multiple level path, you have to set the rules level by level.

**Comment by hotgazpacho** [comment]
@garyleefight Thanks! This is progress. However, it is now blocking access to javascript assets and web manifests. I think I need to tweak this a bit.

**Comment by swaminator** [comment]
@hotgazpacho were you able to figure this out?

**Comment by hotgazpacho** [comment]
I ended up adding [gastby-plugin-remove-trailing-slashes](https://www.gatsbyjs.org/packages/gatsby-plugin-remove-trailing-slashes/), and that solved some of my issues, around what makes the link “current”, but not the redirects. I probably need to add a Lambda@Edge function to rewrite the request before it hits S3.
