### ISSUE TITLE
Building page shows duplicated tabs in Japanese and English at the same time, and the labels in English do not work.

### ISSUE THREAD

**Issue by makies** [aws-amplify/amplify-console#1421]
**Describe the bug**

**To Reproduce**

1. Go to Amplify console
2. Select Japanese from footer
3. See duplicated tabs and English tabs do not work

**Expected behavior**
Shows only clickable tabs in Japanese

**Screenshots**
![image](https://user-images.githubusercontent.com/83250/103475384-079ab000-4df0-11eb-9e7d-d0a3de557fd6.png)

**Desktop (please complete the following information):**
 - OS: Mac 
 - Browser chrome
 - Version 87.0.4280.88（Official Build） （x86_64）

**Additional context**
Reproduce in languages other than English

**Comment by watilde** [comment]
This issue seems to be fixed per https://twitter.com/shn/status/1356115553488756739 :)

**Comment by abhi7cr** [comment]
Yup we fixed it 🙂. It’s still pending deployment to certain new regions which will be complete by today. I will update this ticket once complete.
