### ISSUE TITLE
Stuck on "Your build is being queued. If your build has not started in over a minute, click the button below."

### ISSUE THREAD

**Issue by gveldhuis** [aws-amplify/amplify-console#1426]
**Describe the bug**
When I deploy my React application through Amplify, the screen is indefinitely stuck on "Your build is being queued. If your build has not started in over a minute, click the button below." Clicking the "Run build" button also does nothing. My App ID is d1dqs9x46plfx2.

**To Reproduce**
1. Go to 'Host Web App'
2. Click on 'GitHub', select repo
3. Click on "Save and Deploy"

**Expected behavior**
App homepage should show various steps of deployment process and then deploy.

**Desktop (please complete the following information):**
 - macOS Catalina
 -

**Comment by caseyplummer4haliontech** [comment]
You may wish to commit a file and see if it triggers the job.

Otherwise, I was able to start my build using AWS console commands.

Get the app ID:
aws amplify list-apps

Start the job:
aws amplify start-job --app-id APPIDGOESHERE --branch-name main --job-type RELEASE

**Comment by makrmark** [comment]
I'm having this same problem - stuck on deployment.

I tried the console solution proposed but my user didn't have permission. I added an Amplify CLI policy per:
https://docs.amplify.aws/cli/usage/iam

However this still does not seem to enable the required permissions to StartJob - and that's where I'm stuck currently.

**Comment by Athena96** [comment]
Hi @gveldhuis are you still facing the issue? I see several successful builds yesterday for 'd1dqs9x46plfx2'

**Comment by makrmark** [comment]
Hi @gveldhuis - per my update I resolved this using CLI (after a number of failed attempts via the console). 
After issuing the command it immediately started build and completed successfully.

**Comment by moaazassali** [comment]
I am getting the same issue. Is there any solution yet?

**Comment by gveldhuis** [comment]
@Athena96 This ended up being a permissions issue, which we have since fixed. Thank you!
