### ISSUE TITLE
how to use gzip with aws amplify console

### ISSUE THREAD

**Issue by Eric-ett** [aws-amplify/amplify-console#1429]
I have a question, I am using aws amplify console link gitlab to run a Vue App 

My app is built and running well, But there is a js file that is very large。

I want to reduce the bundle size, So I set up gzip in webpack ,When I execute npm run build, the dist folder successfully generated the *.js.gz file。But when I submit the code to gitlab and deploy it through aws amplify, the .js.gz file cannot be downloaded and used，and the deployed webpage cannot be opened

I saw some answers on the Internet to solve this problem through cloudfount or S3, but in my project I only used aws amplify console to link gitlab, and did not use cloudfount and S3。

So i want to know how to force to serve only the .js.gz (gzipped version of the js) instead of the plain js version.

Thanks in advance,

**Comment by hsspain** [comment]
@zhouxy1989 Can you provide your app ID and region so we can better help?

**Comment by zhouxy1989** [comment]
Sorry, I am not sure where to look up the app id.
App ARN:arn:aws:amplify:ap-northeast-1:952178321851:apps/dqtktmc6f03bn
Is 'dqtktmc6f03bn' an appid?
region:ap-northeast-1

**Comment by hspain** [comment]
@zhouxy1989 Yes, that's it.  We will look at this issue and let you know what we find.

**Comment by hsspain** [comment]
@zhouxy1989 Yes, that is is. We will look into the issue and let you know what we find.

**Comment by calavera** [comment]
@Eric-ett can you check that you have `.gz` in the expression that redirects to your SPA? If you don't have it, we might be trying to download the index file instead of the javascript file:

This expression should include `gz` to avoid the redirect:
```
</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json|mp4)$)([^.]+$)/>
```

**Comment by calavera** [comment]
I'm going to close this issue. Don't hesitate to let me know if you still have trouble and I'll be happy to reopen it.
