### ISSUE TITLE
[ERROR]: Failed to deploy

### ISSUE THREAD

**Issue by dominicjameskelly** [aws-amplify/amplify-console#143]
**App name**
bmfonline-co-uk

**App ARN**
arn:aws:amplify:eu-west-2:832288167450:apps/d25nk29cstjqrf

**Region:**
eu-west-2

I can no longer build from my master branch. I cannot see any build errors in the Amplify logs.

**Comment by butaca** [comment]
Same bug here.

**App ARN**
arn:aws:amplify:us-east-2:970150125456:apps/d1sstkga163z5f

The only relevant info I found in the logs is:

2019-09-23T18:59:00 [INFO]: Updating Edge config
2019-09-23T18:59:00 [ERROR]: Failed to deploy
2019-09-23T18:59:00 [INFO]: Deployment finished.

**Comment by garyleefight** [comment]
@dominicjameskelly @butaca Thanks for the reporting. We are looking at the issue.

**Comment by kununguaq** [comment]
AWS amplify console completes provision & build stages, but fails at deploy without giving a reason... The last 3 lines of my deployment log:

**2019-09-23T22:56:23 [INFO]: Updating Edge config
2019-09-23T22:56:23 [ERROR]: Failed to deploy
2019-09-23T22:56:23 [INFO]: Deployment finished.**

The crazy thing is i can't even re-deploy a previously stable build. What's up ?
My App ARN: arn:aws:amplify:eu-west-1:352247527096:apps/d1p38jyf52tcwc

**Comment by garyleefight** [comment]
@dominicjameskelly @butaca @kununguaq Hi, we have located the bug and pushed the code. The deployment will be completed as soon as possible

**Comment by swaminator** [comment]
#146

**Comment by butaca** [comment]
@garyleefight builds are deploying ok for me now. Any insight about what happened would be much appreciated.

**Comment by swaminator** [comment]
Can you try now? A fix has been rolled out.

**Comment by dominicjameskelly** [comment]
@swaminator Fixed, thanks!
