### ISSUE TITLE
Redirection from https://mydomain.com to https://www.mydomain.com doesn't work

### ISSUE THREAD

**Issue by tandrimab** [aws-amplify/amplify-console#1433]
I have a react app deployed on AWS Amplify. I have configured a custom domain for this app managed by a third party domain provider. I have configured it to redirect from https://mydomain.com to https://www.mydomain.com under rewrite and redirect section. I have added A type record set as suggested but still if I go to https://www.mydomain.com it redirects to the app but if I navigate https://mydomain.com I get "this site cannot be reached" error. 

The record set for my app in route 53 is attached herewith. Any help would be greatly appreciated.
![Screenshot (13)](https://user-images.githubusercontent.com/60216565/103877408-0bce1280-50fb-11eb-9e6b-192538c8dcf5.png)

**Comment by gdavidvm193** [comment]
did you manage to fix it?
