### ISSUE TITLE
You must have pipenv installed and available on your path - when running Amplify Push

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-console#1434]
I have added an Amplify function (Pyhton) locally. When I am running Amplify push I get this error:

**You must have pipenv installed and available on your path** 

I am running zsh om Mac and these versions:
Python 3.8.7

Amplify CLI version
4.41.0

**Comment by Senejohnny** [comment]
You are getting this, as you might be asking for python in amplify backend services, e.g lambda. You need to make sure that pythonV3.8 is installed and then pip/pip3 install pipenv and make sure pipenv can be called from terminal. If command not found, add python 3.8 to your $PATH!

**Comment by rpostulart** [comment]
which python gives me:
/usr/local/bin/python

python --version
Python 3.8.7

pip -V
pip 20.3.1 from /Users/user/Library/Python/2.7/lib/python/site-packages/pip (python 2.7)

pip3 -V
pip 20.2.3 from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)

echo $path
 /Users/user/Library/Frameworks/Python.framework/Versions/3.8/bin /Library/Frameworks/Python.framework/Versions/3.8/bin  /Users/ramon/Library/Python/3.8/


So it seems like it is there. What am I missing?

**Comment by Senejohnny** [comment]
Your $PATH is not fully as it should be! It should end by /bin like below 
-bash: /Library/Frameworks/Python.framework/Versions/3.8/bin/:  .....

**Comment by rpostulart** [comment]
This is in my .zprofile file

export PYTHONPATH="/Library/Frameworks/Python.framework/Versions/3.8/bin:${PYTHONPATH}"

export PATH="/Library/Frameworks/Python.framework/Versions/3.8/bin:${PATH}"

export PATH=/Users/user/bin:/Users/user/Library/Frameworks/Python.framework/Versions/3.8/bin:$PATH

**Comment by Senejohnny** [comment]
Have a look at this [video](https://www.youtube.com/watch?v=PUIE7CPANfo)
