### ISSUE TITLE
Domain activation is Failed - CNAMEs provided already associated but CloudFront distributions is empty

### ISSUE THREAD

**Issue by artcad** [aws-amplify/amplify-console#1438]
**App Id**: d1n32urc42e9mq
**Region**: eu-west-3
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Root domain activation failed with Amplify App. The problem only concern root domain. Domain activation work with subdomains (if I exclude root).

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
I have actually no CloudFront distribution.
<img width="1437" alt="Capture d’écran 2021-01-08 à 12 11 05" src="https://user-images.githubusercontent.com/30954074/104009570-95d5b400-51ab-11eb-8098-96f3130095f3.png">

I have tried to manually register CNAME domain in AWS Route 53, to my Amplify app (xxx.cloudfront.net), and I have this error message : (InvalidChangeBatch 400: RRSet of type CNAME with DNS name <my_domain>.com. is not permitted at apex in zone <my_domain>.com.)
![2](https://user-images.githubusercontent.com/30954074/104010211-73906600-51ac-11eb-95b1-2a9bb813f017.jpg)

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by artcad** [comment]
I have already checked this doc. This is why I specified: "I have actually no CloudFront distribution" with a screenshot.
My CloudFront distribution list is empty, so my domain is not deployed to any other distribution.
I am still facing the same issue.

**Comment by hsspain** [comment]
@artcad It is possible that another account has associated that domain. It is also possible that another service outside of Amplify which uses CloudFront has that domain associated with it.

Are you using that domain for any other services?

**Comment by artcad** [comment]
Problem solved.

I had to remove API Gateway domain association.
