### ISSUE TITLE
Multiple Amplify preview build checks on single repo?

### ISSUE THREAD

**Issue by dnalbach** [aws-amplify/amplify-console#1441]
** Please describe which feature you have a question about? **
I would like to know if it is possible to have multiple simultaneous preview build checks on a single Github repo. I have two separate Amplify instances that are each in different AWS accounts and both connected to the same Github repo. The two Amplify apps are identical in most ways, with only domain and some environment variables different between them. One is for staging, and one is for production.

Both build preview builds correctly that work, however, only the production Amplify app shows up in PRs under the checks section. Clicking on it (or details) goes to the Checks page, where there is only one check that links to the production Amplify app console url in the `View more details on AWS Amplify (us-east-1) ` link. 

I can't find any difference between the two Amplify apps, so before I waste a lot of time on this, I'd like to confirm whether the Amplify preview Github check actually supports multiple Amplify apps, or if the first/last one registered is always going to be the only one listed?

** Provide additional details**

**Comment by hsspain** [comment]
@dnalbach We support your use case, but will need to look into why your PR build check is not showing for your staging branch.  Can you provide your app ID?

**Comment by dnalbach** [comment]
The staging ARN is:
`arn:aws:amplify:us-east-1:663349387396:apps/dekwdhq95dqhd`

**Comment by ganipcanot** [comment]
Resolving due to age - please re-open if you are still experiencing issues.

**Comment by dburles** [comment]
Ran into this same issue. @hsspain you mentioned it is supported, can you explain how it should function? I am seeing the same issue as @dnalbach originally described. I have two amplify applications with previews configured to build from a single repo. One application builds the app itself, while another builds Storybook. However, I am seeing a single instance of "AWS Amplify Console Web Preview" in the PR checks section. The bot comment posts twice, a URL for each preview, so I am sure that it's configured correctly.

Ideally I would like to see both deployments appear in the checks, they should be tagged with the amplify application name. So they can be easily differentiated. `AWS Amplify Console Web Preview -  <App name>` E.g:

```
AWS Amplify Console Web Preview - my-app
AWS Amplify Console Web Preview - my-app-storybook
```
