### ISSUE TITLE
Amplify points to main branch, but still looks for master

### ISSUE THREAD

**Issue by mattups** [aws-amplify/amplify-console#1443]
I'm setting an AWS Amplify app connected to a GitHub repository.

After completing the configuration, in which I specify to take my repository. on the `main` branch, configuration is successfull. Build unfortunately seems to be stuck in a `pending` state. As I look in the general tab I see that it automatically refreshing beetwen two state (look at the repo URL)

![image](https://user-images.githubusercontent.com/26442835/104102682-4cb25c80-529e-11eb-9fd4-a129b4adc9df.png)
![image](https://user-images.githubusercontent.com/26442835/104102703-5f2c9600-529e-11eb-8fb1-c454c6e2b105.png)

As you can see, Amplify seems to "lost connection" to my repository. In the settings I specified that I want to build the `main` branch. But seems that Amplify is still looking for `master` somehow.

Indeed, I have another Amplify webapp connected to a Github repository which eventually has the `master` branch instead of `main`

**To Reproduce**
1. Create a new app on AWS Amplify
2. Connect to a Github repo with a `main` branch
3. Confirm the deployment
4. See that is remains in `pending` build status

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/26442835/104102682-4cb25c80-529e-11eb-9fd4-a129b4adc9df.png)
![image](https://user-images.githubusercontent.com/26442835/104102703-5f2c9600-529e-11eb-8fb1-c454c6e2b105.png)
![image](https://user-images.githubusercontent.com/26442835/104102803-eb3ebd80-529e-11eb-83c1-08a30c6ec2ab.png)
![image](https://user-images.githubusercontent.com/26442835/104102822-07425f00-529f-11eb-90a8-30760aab1b60.png)

**Additional context**

**Comment by hsspain** [comment]
@mattups We are looking into this issue now.

**Comment by hsspain** [comment]
Can you provide the region this app is created in?

**Comment by EChebelyon** [comment]
@hsspain  I have a similar issue, the app is created in US-East-1
