### ISSUE TITLE
Update github repository credentials

### ISSUE THREAD

**Issue by aheadxnet** [aws-amplify/amplify-console#1445]
** Please describe which feature you have a question about? **
I have created an AWS Amplify App with an Angular frontend and a DynamoDB backend. The code repository is hosted by github, and I am using CD/CI which all works fine.

Due to a change in the github policy I want to change the credentials for the github repository using a "personal access token". I created this token in my github account, change my account to use 2FA and even change my account password.

As I didn't find any point in the AWS Console to edit the github repository credentials I tried to "reconnect repository" in the App settings:General section - but I don't get asked for new credentials. And the AWS Amplify App even grabs new commits (in my develop branch, but it will also work on the main branch I guess). Did I miss any thing? Do I have to delete the App and recreate it? I would like to avoid that.

Kind regards,
Stefan.

** Provide additional details**

**Comment by hsspain** [comment]
@aheadxnet Once your repository is connected, you will not have to reconnect when credentials change.

I will close this ticket, but feel free to re-open if you have further questions.
