### ISSUE TITLE
Amplify CI/CD auto branch detection no longer auto-connects to backend environment

### ISSUE THREAD

**Issue by aheadxnet** [aws-amplify/amplify-console#1446]
**Describe the bug**
Amplify CI/CD auto branch detection no longer auto-connect to backend environment (settings are: "Create new backend environment for every connected branch").

**To Reproduce**
1. Setup branch autodetection with pattern "feature/**"
2. Select "Create new backend environment for every connected branch"
3. Save
4. In your connected source repository push a new feature branch "feature/my-new-feature
5. See new frontend environment "my-new-feature" starts deployment
6. Build step failes with "Error: File at path: '/codebuild/output/srcXXXXXXXX/src/<project-name>/amplify/.config/local-env-info.json' does not exist" (see full log attached)
7. A backend environment (robinetta in this case) gets created but seems not to be connected to the frontend environment, feature/my-new-feature simply shows "Continuous deploys set up (Edit)" instead of mentioning the backend environment, as in "Continuous deploys set up with dev backend (Edit)" for my develop frontend, for example.
8. Manually connecting a backend to the frontend does not help - during deployment the build step still fails with the same error.

[build.log](https://github.com/aws-amplify/amplify-console/files/5792514/build.log)

**Expected behavior**
I would have expected the created backend environment to be automatically connected to the feature branch frontend.

**Screenshots**
n.a.

**Desktop (please complete the following information):**
n.a.

**Smartphone (please complete the following information):**
n.a.

**Additional context**
I first noticed this on January 9th, 2021, when I built my first release this way (im using the pattern "feature/\*\*,release/\*\*" in fact, I just simplified the steps above). Previously I only had used feature branches. So I thought it had to do with the release branch. But today I created my first feature branch for the next release and it also failed.

I removed the configuration for the branch autodetection completly (and even created a new feature branch to see no environment gets created - that worked!) and restored the branch autodetection part and replayed the scenario - it still failed to connect the newly created backend environment to the frontend.

What I observed before: to save resources I have also configured branch auto-disconnection. The frontend environments get deleted when deleting the branch, the backend environments don't. I manually deleted backend environments, that did not help, either.

**Comment by aheadxnet** [comment]
I looked into my last feature branch creations - the last successfully detected feature branch with working auto deployment (connected to auto-created backend) was created on Dec. 27th, 2020.

**Comment by nimacks** [comment]
We are investigating this issue.

**Comment by nimacks** [comment]
There is a known issue regarding  this `Error: File at path: '/codebuild/output/srcXXXXXXXX/src//amplify/.config/local-env-info.json' does not exist` that is being tracked in the Amplify CLI https://github.com/aws-amplify/amplify-cli/issues/5931.
The team is working on this.

**Comment by swaminator** [comment]
The issue was fixed. Let us know if you're still facing any problems.

**Comment by aheadxnet** [comment]
During the last month I developed a script creating a matching backend when starting a feature or release branch (and deleting the backend when finishing either). So currently I don't use the feature of auto connecting branches anymore.
I took the chance to develop the script which is matching my needs better than the original feature - so I call it "good luck" the feature was broken.
