### ISSUE TITLE
Adding new route53 domain stuck on SSL configuration

### ISSUE THREAD

**Issue by moshe** [aws-amplify/amplify-console#1448]
**App Id**: d13y846pby4yi9
**Region**: us-east-1
**Step**: 
**Status**: SSL configuration

**Issue/question**
I'm trying to set up a custom domain from Route53 to my Amplify application but getting stuck on SSL configuration. I've added that domain from Route53 UI (Hosted Zones -> Create hosted zone -> domain name `preview.example.com`, Private hosted zone, chose a VPC in us-east-1
After adding the zone, it appeared in the domain dropdown and choosing it do create some CNAME records but immediately get stuck on `SSL configuration`

**Error message**
No error

**Additional information**
curl to `https://preview.example.com` produce an error from cloudfront
```
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Bad request.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
```
Thanks!

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by brnmye** [comment]
We are going to close out this issue, but please feel free to re-open if you still need help.

**Comment by Joaker4** [comment]
@brnmye Same thing is happening to us when creating Custom Domains with VPC attached Hosted Zones. Tried all the troubleshoot and configuration steps with no luck.

**Comment by harryxp** [comment]
In case somebody is still trying to figure this out, you could try to update the name servers of the registered domain to be the same as the name servers of the hosted zone NS record.
