### ISSUE TITLE
Get Build activity without logging in aws console

### ISSUE THREAD

**Issue by talebbits** [aws-amplify/amplify-console#145]
**Is your feature request related to a problem? Please describe.**

Get `Build activity` when tigger a build by web hook without logging in aws console.
We can see build activity in aws amplify console but is there any way to to get this info without logging in to console. maybe through API ?

**Describe the solution you'd like**

webhook response has something like this, 
`'{"SendMessageResponse":"ResponseMetadata":{"RequestId":"<RequestId>"}}'`
so maybe we can make another request to get activity about that request by

`https://webhooks.amplify.us-east-1.amazonaws.com/prod/webhooks?id=<ID>&token=<TOKEN>&requestid=<RequestId>&operation=`**getactivity**

**Comment by swaminator** [comment]
Are you referring to the build logs? or the history of builds?

**Comment by talebbits** [comment]
I think both
1) We want to know if there is active build and if there is what is the status (Provision|Build|Deploy|Verify)
2) What is the status of all previous Jobs.

**Comment by swaminator** [comment]
1. https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Amplify.html#getJob-property
2. You can use the same API to fetch status of previous jobs
