### ISSUE TITLE
Domain activation is Failed - AWS Amplify Custom Domain Register

### ISSUE THREAD

**Issue by lustercr** [aws-amplify/amplify-console#1451]
**App Id**: dr9v9qf2l501
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Trying to register the amplify custom domain keeps on throwing errors, it says the CNAMEs are already associated with a different resource. which is not correct. 

however there is a wildcard for the same domain pointing to a different cloudfront, will that be a issue ?

by basic design is:

wildcard point to cloudfront A.

and this other custom domain ( a different react app ) points to a different cloudfront.

Example

*.domain.com -> cloudfrontA ( not amplify resource)
specific.domain.com -> cloudfrontB ( amplify resource that its failing to register the domain)

**Error message**

One or more of the CNAMEs you provided are already associated with a different resource.

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
I have tried manually removing the records myself, deleted the custom domain, and starting over, still getting the same error.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by brnmye** [comment]
We are going to close out this issue, but please feel free to re-open if you still need help.
