### ISSUE TITLE
Waiting to deploy Your deployment is being queued...

### ISSUE THREAD

**Issue by sandeepgupta246** [aws-amplify/amplify-console#1455]
till uploading the zip file it is working fine , and after I save and deploy it says 👍 

Waiting to deploy
Your deployment is being queued...

and this is the screen forever, can anyone help me what exactly is the issue.
![screenshot](https://user-images.githubusercontent.com/69807635/104551376-c8285b00-565c-11eb-862e-c99a38ec884b.png)

**Comment by hsspain** [comment]
@sandeepgupta246 Can you provide your app ID and region? This behavior can mean that you are hitting the 5 concurrent build limit and any new build requests at that point are queued. We can look into this for you.

**Comment by ganipcanot** [comment]
Closing for now since no response - if you're still experiencing an issue please re-open the ticket.

**Comment by dennisja** [comment]
A similar thing is happening for me, and looks like the URL amplify generates begins with a `.` for me which kind of looks abnormal to me. Here is a screenshot having the app details.
<img width="1433" alt="Screenshot 2021-02-27 at 21 27 28" src="https://user-images.githubusercontent.com/13004199/109399379-ced80c80-7942-11eb-9002-b44d41ffe78f.png">

**Comment by oj-m** [comment]
Same issue.  No logs.  No errors.  No deploy.  Just a production URL with a dot in front of it and _"Your deployment is being queued."_

**Comment by khanveerr** [comment]
Same issue.
**Your deployment is being queued...**

What is the solution for below issue?
I have both `AdministratorAccess-Amplify` and `AmazonS3FullAccess` to my IAM user. Still facing the same issue.
What other permission or role required to make this deployment work?

![image](https://user-images.githubusercontent.com/13793680/121140842-f00c9b00-c857-11eb-9b24-fd2eed001f55.png)
