### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by jnk-keynoty** [aws-amplify/amplify-console#1456]
**App Id**: d37u6m3z2s07mu
**Region**: ap-northeast-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by hsspain** [comment]
@jnk-keynoty Please ensure you have the proper CNAME records for your domain. https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html.

If you feel you have done everything correctly, try removing and re-adding the domain.

Let us know if you have specific problems setting up custom domains.

**Comment by brnmye** [comment]
We are going to close out this issue, but please feel free to re-open if you still need help.
