### ISSUE TITLE
Build successful, but deployment & re-deployment fails

### ISSUE THREAD

**Issue by kununguaq** [aws-amplify/amplify-console#146]
AWS amplify console completes provision & build stages, but fails at deploy without giving a reason... The last 3 lines of my deployment log:

**2019-09-23T22:56:23 [INFO]: Updating Edge config
2019-09-23T22:56:23 [ERROR]: Failed to deploy
2019-09-23T22:56:23 [INFO]: Deployment finished.**

The crazy thing is i can't even re-deploy a previously stable build. What's up ?
My App ARN: arn:aws:amplify:eu-west-1:352247527096:apps/d1p38jyf52tcwc

**Comment by swaminator** [comment]
@kununguaq we are aware of this issue and rolling out a fix today. Will notify you on a fix.

**Comment by swaminator** [comment]
Can you try now? A fix has been rolled out.
