### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by iReivax1** [aws-amplify/amplify-console#1460]
**App Id**: d2sqf23vpad2u0
**Region**: ap-southeast-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
What action is needed to be done to rectify.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
*Previously used it for SES and workmail

**Comment by hsspain** [comment]
@iReivax1 You will not be able to use a domain that is already associated with another CloudFront distribution. You will either need to remove that domain association from other applications or use a different domain for your Amplify app. I will close this ticket, but feel free to re-open if you have further issues.
