### ISSUE TITLE
Domain activation is Failed - Domain already associated with a different resource

### ISSUE THREAD

**Issue by garethleonard** [aws-amplify/amplify-console#1468]
**App Id**: d9xrv9s8wrb9f
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Unable to activate a custom domain for an application in AWS Amplify. I deleted the resource it is referring to over 24 hours ago now, and still getting the same error.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by hsspain** [comment]
@garethleonard The domain may be associated with a CloudFront distribution that is not an Amplify app. Can you check other resources in your account?

**Comment by garethleonard** [comment]
I have no CloudFront distributions - I removed the one that was associated with the CNAME over 24 hours ago

**Comment by hsspain** [comment]
Can you try removing and re-adding the domain to your Amplify application? If you could send use the domain name you are attempting to associate, we may be able to help more.

**Comment by garethleonard** [comment]
I tried removing and adding with no luck. The domain is capstoneqa.com

**Comment by hsspain** [comment]
@garethleonard We can see that the domain is associated with an Amplify app. Can you check all of your apps in all regions to ensure that it is not already associated with another application?

**Comment by garethleonard** [comment]
🤦‍♂️ Thank you. That's the issue.
