### ISSUE TITLE
Increasing the 5 Custom Domains Limit of AWS Amplify

### ISSUE THREAD

**Issue by thibauld** [aws-amplify/amplify-console#1471]
**Is your feature request related to a problem? Please describe.**

We provide an investment portal app for our customers.
We have a 100% AWS-based serverless stack and relying on AWS Amplify.
Each of our customers app has its own custom domain.
We have 1 single codebase for our app, so, for each new customer, we add a custom domain to our Amplify app.
Amplify currently limits the number of custom domain to 5 per App.
The workaround is to create multiple Amplify apps but it's a PITB.

**Describe the solution you'd like**
It would be great if you guys could increase the limit of 5 custom domains per AWS Amplify app so that we can scale and serve more and more customers easily using AWS Amplify, without having to create a new app each time we hit the very restrictive 5 custom domain limit.

**Additional context**
This is a follow-up on issue #927 which had been closed.

**Comment by hsspain** [comment]
@thibauld Please contact us at aws-amplify-customer@amazon.com to request a limit increase.

**Comment by hloriana** [comment]
If you need to request a limit increase for the number of domains allowed for your application please use this link: https://console.aws.amazon.com/servicequotas/home/services/amplify/quotas/L-AD277529
