### ISSUE TITLE
PR Preview cannot be enabled on branches

### ISSUE THREAD

**Issue by noahgorstein** [aws-amplify/amplify-console#1473]
** Please describe which feature you have a question about? **

Hi all - I've deployed my front end app just fine on Amplify. When I've gone to enable "Previews" on my branches, I am prompted to install the required integration for my Github repository. I install the integration, return to the Amplify console and when I attempt to enable the previews, nothing actually gets updated after toggling the switch. I was thinking that maybe this may be a permissions error but I am not being notified of any lack of privileges. I see a blue pop up at the top of the window for a brief second when I save after toggling the switch to enable previews but its so brief I cannot even read it before it goes away. 

Does this issue sound familiar at all? 

** Provide additional details**

**Comment by siegerts** [comment]
Hi @noahgorstein , is this still an issue?  Does this still occur after new PRs are opened after enabling Previews?

**Comment by noahgorstein** [comment]
@siegerts thanks for following up. I was able to resolve this basically by having a higher privileged user enable previews. Do you know if there are permissions associated with enabling previews? There weren't any error messages that I could see.

**Comment by ganipcanot** [comment]
Closing due to age - please re-open if still experiencing issues.
