### ISSUE TITLE
Domain activation is Failed - CNAME issue

### ISSUE THREAD

**Issue by DanielWFrancis** [aws-amplify/amplify-console#148]
**App Id**: d5mx54nkosktu
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**:Tried to create a domain and it failed, deleted that and tried again, now I get the error message below.

**Issue/question**
Getting issues from AWS about connecting my third-party custom domain for Amplify. Previously had it somehow connected to the URL given when using the Amplify CLI, but upon switching to the console I realized the domain given by AWS was different so I'm trying to migrate.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by garyleefight** [comment]
@DanielWFrancis The domain status is available. Feel free to contact us if you still have issue.
