### ISSUE TITLE
Issue deploying basic app on amplify

### ISSUE THREAD

**Issue by bkandaris** [aws-amplify/amplify-console#1483]
When trying to deploy the app the webpage that shows where the app is supposed to be deployed is as follows: 
I expected the React App to deploy

**Screenshots**

I am seeing this in place of where the app should be hosted:
![image](https://user-images.githubusercontent.com/52390565/105567817-de8c8180-5d02-11eb-9545-4b01ad46b96c.png)

Is there something wrong with my build commands?
![image](https://user-images.githubusercontent.com/52390565/105567870-39be7400-5d03-11eb-89f5-ad2727ba699c.png)

 - OS: Windows
 - Browser chrome

**Comment by abhi7cr** [comment]
Hello @bkandaris , could you share the appId and region so that I can take a look at the logs ?

**Comment by jo-elbdev** [comment]
shouldn't it be `node_modules/**/* `?
