### ISSUE TITLE
Amplify Publish Failing

### ISSUE THREAD

**Issue by truimagz** [aws-amplify/amplify-console#1487]
**Describe the bug**
Unable to complete amplify publish

**To Reproduce**
run amplify publish

**Expected behavior**
It to finish and deploy the code

Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
An error occurred during the publish operation

Seems like it's timing out

**Comment by abhi7cr** [comment]
Hello @truimagz, could you provide appId and region so that I can take a look at the logs ?

**Comment by hloriana** [comment]
Closing. If you're still running into this issue, please feel free to re-open and add your App ID and region. Thank you!
