### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by iReivax1** [aws-amplify/amplify-console#1488]
**App Id**: d2sqf23vpad2u0
**Region**: ap-southeast-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
What is the next course of action

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**

https://protectmi2.com | main | https://www.protectmi2.com
-- | -- | --
https://www.protectmi2.com | main | -

Domain of protectmi2 is hosted in us-east-1 but Amplify uses ap-southeast-1

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
