### ISSUE TITLE
AWS Amplify Console, a deleted App shows an error of not being found only in MS Edge

### ISSUE THREAD

**Issue by tsondreal** [aws-amplify/amplify-console#1490]
**Describe the bug**
AWS Amplify Console, a deleted App shows an error of not being found only in MS Edge.  This can't be reproduced in Chrome or Chrome

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**

**Screenshots**

**Amplify CLI Version (if issue tied to Amplify CLI) **
You can use `amplify -v` to check the amplify cli version on your system
 - CLI Version
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system
 - Browser type (e.g. Google Chrome/ Firefox)

**Additional context**

**Comment by calavera** [comment]
I could not reproduce this problem with MS Edge. Let us know if you're still bumping into it and we'll investigate further.
