### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by SandeepKumarYaramchitti** [aws-amplify/amplify-console#1491]
**App Id**: d2qwqmz5kprk4w
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am trying to deploy my Angular frontend to a Route53 domain. In the past, i have used amplify app to do this but looks like i could not see the old amplify app, so had to create a new one. However, while deploying to custom domain - it is failed with an error message. 

Error message: One or more of the CNAMEs you provided are already associated with a different resource.

How should i retrieve the old amplify app and disassociate it from this domain or allow my new amplify app to my domain - 

https://codebysandeep.io

**Error message** 

Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by SandeepKumarYaramchitti** [comment]
@brnmye I did go through the documentation. However, it does not mention anything about lets say a past amplify app was using the same domain. However, it is deleted now so i am not able to disassociate this domain from old app. 

Please suggest next steps
