### ISSUE TITLE
SSL verification is Failed - When trying to add domain to blog from Amplify Console

### ISSUE THREAD

**Issue by cognitiaclaeves** [aws-amplify/amplify-console#15]
**App Id**: d1dxfezyi4jluz
**Region**: us-east-2
**Step**: SSL verification
**Status**: Failed

**Issue/question**
I keep getting an error when trying to attach a domain name to a new blog via Amplify Console.

**Error message**
The status of this certificate request is "Failed". One or more domain names have failed DNS validation. Please check your domain name validation routes and try re-adding the custom domain to your app. 

**Additional information**
The CNAMEs appear to resolve in WhatIsMyDNS.net. (Except for one in China.) It's been 24 hours since the CNAMEs started resolving.

**Comment by cslogan-red** [comment]
Hello,

Your domain appears to be managed with a third party DNS provider, have you validated that your DNS provider has been updated with the following CNAME and ANAME/ALIAS records as outlined here?

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-troubleshoot-guide

You can validate the CNAME and ANAME records have propagated using whatsmydns.net, it may take up to 48 hours for this to complete, after which you should be able to retry the validation.

If you're still having issues after 48 hours, you can delete the domain from Amplify Console and try re-adding it, making sure the DNS provider records have been entered exactly as shown in the tutorial, and it should finish validating.
