### ISSUE TITLE
Private Git Submodule on GitHub - Permission Denied

### ISSUE THREAD

**Issue by RyanHow** [aws-amplify/amplify-console#150]
Hi,

I have a simple project that has a submodule in a private GitHub repo.

The build fails with `Permission denied` when attempting to clone the submodule.

I'm just using a relative path for the submodule.

What's the correct process for getting submodules to work from the amplify console?

(As a side note, the OAuth user has access to the repo, but I'm assuming I need to somehow get the public key across to the repo??)

```
[INFO]: # Updating Git submodules...
[WARNING]: # Unable to update submodules: Error: Command failed: git submodule update
                                    Cloning into '/codebuild/output/src813455/...'...
                                    Permission denied (publickey).
                                    fatal: Could not read from remote repository.
                                    Please make sure you have the correct access rights
                                    and the repository exists.
```

Thanks, Ryan

**Comment by swaminator** [comment]
@RyanHow couple of options. Please refer to this link: https://stackoverflow.com/questions/56219052/fetching-private-submodules-in-aws-amplify-build

**Comment by RyanHow** [comment]
@swaminator Thanks, they are all kind of workarounds and are going to complicate the configuration to bend to what the CI server wants. It looks like hard code a user to pull a submodule or use NPM packages. The other one I saw was to generate a keypair, then put it into the github submodules and the environment variables in Amplify. I think that might be the best bet.

It's still a bit of a shame the public key that Amplify uses isn't downloadable, because I could just add that to the submodule repos and it would all work. It even out of the box tries to pull all the submodules!

Actually... I wonder if I can put something in the build script to dump the public key into the logs, then I can import it into GitHub. Would that be possible do you think?

**Comment by RyanHow** [comment]
I dumped the public key, but GitHub doesn't allow you to use a deploy key in more than 1 repo.

So it looks like I need to use the user account approach in the link that you mention.

I misunderstood the link you posted. I thought I needed to change the way the project was set up, but I can just change the submodule config as part of the build script.

It's kinda complex and I haven't seen much info about it on the web. Thanks for the link.

**Comment by RyanHow** [comment]
I found this link to which has another idea

https://forums.aws.amazon.com/thread.jspa?messageID=888750

**Comment by RyanHow** [comment]
Is there a way to regenerate the private/public key pair, or specify my own?

**Comment by RyanHow** [comment]
Ok, so after messing around with keys I found:

- I didn't actually dump the public key, I don't know what I dumped. But it seems the public key is deleted and the SSH agent is stopped BEFORE the build script runs. So you have no way to get the public key.
- Attempting to add your own private/public keypair results in your private key being plastered everywhere in plain text - In your environment variables screen, and then when you use it in the build script it plasters it all over the logs. Amplify doesn't have secure envrionment variables.
- You have to start ssh-agent yourself
- If `ssh-add` prompts for a passphase (even though there isn't one), it's because something in the key is malformed.
- I ended up adding the key to the repo itself, at least that way it isn't plastered in all the build logs and all over the screen. I chose that over the insecure variables anyway...
- You could add a github personal access token, then change the submodule config as part of the build process. I feel like the same issues apply, you have cleartext credentials there. Security wise it feels pretty to the key method.

As much as I want to use Amplify, I really feel like this is unsupported and these workarounds lower the security significantly and are hard to maintain and configure.

It would be good if we had access to the public key, that would solve my case.
Something else would be secure environment variables, or another way to manage keys more securely.
Another idea would be to use deploy keys, generate separate deploy keys for each submodule, store them in the repo, then have a separate script that clones the submodules using those keys. That would give finer control and less scope if the keys were compromised.

Another idea is to store part of the key in Amplify, and part of the key in the repo. Then join them together as part of the build script.

It would also be a good idea to delete the keys immediately after the clone, so any malicious code in the build step can't extract the keys.

FWIW here is the portion of the build script that may help to get someone started

```
    preBuild:
      commands:
        - eval $(ssh-agent -s)
        - chmod 600 /codebuild/output/src*/src/<repo name>/privatekey
        - ssh-add /codebuild/output/src*/src/<repo name>/privatekey
        - git submodule update
   ```

**Comment by HumbleBeck** [comment]
Hey, I faced this issue today as well. So what I did is next:
- created service account and gave read access to secrets manager
- attached this account to app in amplify console
- created secret manager secret with ssh key, ssh in body directly as plaintext
- in amplify build settings 
```
 - eval `ssh-agent -s`
 - aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanage --query SecretString --output text | tr -d '\r' | ssh-add - > /dev/null
```
So now each build it will get private key from secrets manager and inject it into env, so whenever you install something from private repo it has access.
Mb this steps will help someone who is facing same issue.

**Comment by kushan-gunasekera** [comment]
This [article](https://medium.com/@cristiano.ventura/working-with-git-submodules-in-codepipeline-83e843e5d0a) helped me to fix this issue.

**Comment by ShivamJoker** [comment]
Hello please reopen this issue.
I am still facing it on gitlab

**Comment by dancingfrog** [comment]
@swaminator I am also using a git submodule that refers to a private repository and in my case the credentials needed to access the submodule repo are the same as those used to access the parent repository (and Amplify has permissions to access both). This should mean that `git submodule update` is able to run, HOWEVER, there is a *bug* in the Amplify clone stage run order. The runner *removes* the git credentials immediately after cloning the parent repository and *before* calling `git submodule update` as can be verified in the build log:

```
2022-08-02T16:23:43.388Z [INFO]: Cloning into 'amplify-app'...
2022-08-02T16:23:43.388Z [INFO]: # Switching to commit: ff50e322dcbe6fe5b353069cef010b97bdea9a53
2022-08-02T16:23:43.398Z [INFO]: Note: switching to 'ff50e322dcbe6fe5b353069cef010b97bdea9a53'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by switching back to a branch.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -c with the switch command. Example:
                                 git switch -c <new-branch-name>
                                 Or undo this operation with:
                                 git switch -
                                 Turn off this advice by setting config variable advice.detachedHead to false
                                 HEAD is now at ff50e32 use ssh for git submodule refs
2022-08-02T16:23:43.452Z [INFO]: Successfully cleaned up Git credentials
2022-08-02T16:23:43.452Z [INFO]: # Checking for Git submodules at: /codebuild/output/src964993672/src/amplify-app/.gitmodules
2022-08-02T16:23:43.453Z [INFO]: # Updating Git submodules...
2022-08-02T16:23:43.814Z [WARNING]: # Unable to update submodules: Error: Command failed: git submodule update
                                    Cloning into '/codebuild/output/src964993672/src/amplify-app/src'...
                                    Host key verification failed.
                                    fatal: Could not read from remote repository.
                                    Please make sure you have the correct access rights
                                    and the repository exists.
```

**Comment by raphaelfavier** [comment]
+1 to reopen that issue, I'm facing the exact same issue with gitlab.
it would be so much better to have amplify support submodules
