### ISSUE TITLE
Domain activation is Failed - CNAME already associated

### ISSUE THREAD

**Issue by henry8812** [aws-amplify/amplify-console#1502]
**App Id**: d1cv7mqz7n7e45
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am using aws amplify to create an CI of web repository, but when i try to set up the domain for the project, aws amplify return an error, Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource. i really do not know what is happening because i do not create any CNAME on route 53.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
![Screenshot_2021-01-25 AWS Amplify Console](https://user-images.githubusercontent.com/7896656/105792784-fb6cc300-5f55-11eb-89e0-9db9d22fd10f.png)

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
