### ISSUE TITLE
Domain activation is Failed - [CNAME already in use]

### ISSUE THREAD

**Issue by SelcukKayahan** [aws-amplify/amplify-console#1503]
**App Id**: d39uf4dnz7rsy0
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Hi, we already were in touch with your customer support about the CNAME issue. amplify thinks that there is another app running under the CNAME we want to declare but according to route53 there is not. Also there is no app in amplify with the app-id you gave us. When we add a custom domain to amplify, it creates the CNAME link, which gets visible in route53 but then fails with the error message that it is already in use.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
We also use Cloudfront if that is of importance. Also the customer support issue case is 7891941301.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
