### ISSUE TITLE
Domain activation is Failed - Problems with simple domain in aws amplify

### ISSUE THREAD

**Issue by integraitco** [aws-amplify/amplify-console#1505]
**App Id**: d3bo0yxaq4bkfr
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Im getting this error when trying to activate my domain. We have checked the CNAMES records and we ahve only the 2 subdomains

**Error message**
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Additional information**
![image](https://user-images.githubusercontent.com/33135130/105862457-c7c58380-5fbd-11eb-9e03-957ad18311e1.png)

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
