### ISSUE TITLE
`amplify.yml` monorepo config only deploys first app listed

### ISSUE THREAD

**Issue by bryantbiggs** [aws-amplify/amplify-console#1507]
**Describe the bug**
Setting up my project as a monorepo, only the first app listed in the config is deployed regardless of the path provided to the console. No matter what I try to do, Amplify only recognizes the first app listed in the `amplify.yml` configuration.

**To Reproduce**
1. Fork https://github.com/clowdhaus/amped
2. Go to Amplify console and add new app
3. Select checkbox for monorepo app, set the path to either `apps/laundry` or `apps/tan` (anything other than `apps/gym` because that is what Amplify will default to using no matter what)
4. Click next
5. Use latest yarn - click next
6. Click save and deploy
7. Notice that the branch/app that Amplify is deploying states `master|apps/gym` instead of `master|apps/tan` or `master|apps/laundry` (depending on which app you selected

**Expected behavior**
Users should be able to deploy multiple apps from a monorepo configuration, not just the first app listed in the config

**Screenshots**
- Adding repo/branch/folder in console:
![image](https://user-images.githubusercontent.com/10913471/106015898-ed6d8e00-608c-11eb-8d86-a3842c543e66.png)
- Build settings (not really relevant but sharing for transparency)
![image](https://user-images.githubusercontent.com/10913471/106016094-1e4dc300-608d-11eb-874d-92b58e00b311.png)
- Review - note `Application root` value
![image](https://user-images.githubusercontent.com/10913471/106016316-5523d900-608d-11eb-8dde-03a40b5cd5ad.png)
- App deployment - :warning: notice the branch/app root link in blue, middle of image - it states `master|apps/gym` where `apps/gym` is the first app listed in `amplify.yml` but it should show/point to `master|apps/tan` :warning:
![image](https://user-images.githubusercontent.com/10913471/106016473-813f5a00-608d-11eb-9e5c-3f005b019728.png)

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser Firefox
 - Version 84.0.2

**Comment by abhi7cr** [comment]
Hi @bryantbiggs, 

Thanks for reporting this. We have a fix for this, along with a bunch of other monorepo fixes in the pipeline. We will let you know once its deployed.

**Comment by jackh-ncl** [comment]
Any update on this one? Also running into the same problem.

**Comment by lucasmarshall** [comment]
I'm also running into this. Is a fix forthcoming?

**Comment by victorccccc** [comment]
Hi, we've updated Monorepo feature and you can specify `appRoot` via `AMPLIFY_MONOREPO_APP_ROOT` environment variable now

Docs for reference: https://docs.aws.amazon.com/amplify/latest/userguide/monorepo-configuration.html

Feel free to reopen this if issue persists

**Comment by bryantbiggs** [comment]
wait, what?! in order to have the monorepo config work as advertised I need to specify in the yaml config AND set an environment variable?!

**Comment by victorccccc** [comment]
> wait, what?! in order to have the monorepo config work as advertised I need to specify in the yaml config AND set an environment variable?!

Yes, For existing app, you'll need to set `AMPLIFY_MONOREPO_APP_ROOT` in order to make sure everything works as expected, but if you create a new app via Amplify Console, we'll set this environment variable for you.
