### ISSUE TITLE
SSL verification is Failed - multilevel subdomain

### ISSUE THREAD

**Issue by 0luftballoons** [aws-amplify/amplify-console#151]
**App Id**: d3ahdw9b83q4fv
**Region**: us-west-2
**Step**: SSL verification
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Was successful in creating custom subdomain, but then when tried to create multilevel subdomain based on the previous subdomain, could not get past the step where SSL process looking for new verification CNAME entry. Yes, we created and inserted new verification DNS record for the multilevel subdomain.

**Error message**
If there is an error message, please include it here. 
We could not verify ownership of the domain. Please ensure you own the domain and choose retry. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: The status of this certificate request is "Failed". One or more domain names have failed DNS validation. Please check your domain name validation routes and try re-adding the custom domain to your app. Learn more: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-troubleshoot-guide

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by garyleefight** [comment]
@0luftballoons What you could do is add a domain abc.example.com as the root domain. Then you could attach any prefix to that domain to achieve multilevel subdomain, such as test.abc.example.com.

**Comment by 0luftballoons** [comment]
@garyleefight Thanks for the suggestion, abandoning multilevel subdomain, just going to use regular subdomains instead. So far, AWS Amplify seems to like that better.
