### ISSUE TITLE
Deployed Github Gatsby Frontend returns error after first load

### ISSUE THREAD

**Issue by Karynvo** [aws-amplify/amplify-console#1517]
**Describe the bug**
Deployed front-end site (Gatsby) returns error after a normal refresh. However, the site reloads successfully when you do a hard reload so I wonder if it has something to do with caching.

**To Reproduce**
1. Connect Github branch to deploy to Amplify console
2. After site finishes making it through the pipeline, navigate to the Amplify-generated domain for the site
3. Verify the site shows up
4. Do a normal refresh on the site; the site does not show up

**Expected behavior**
Upon a normal refresh, the site should show up

**Desktop (please complete the following information):**
 - OS: Mac 10.14.6
 - Chrome 88.0.4324.96, Safari 14.0.1

**Comment by abhi7cr** [comment]
Hi @Karynvo, when you say the site does not show up, do you mean you are getting an error like `403/404` or its loading the previous version ?

**Comment by Karynvo** [comment]
![Screen Shot 2021-02-02 at 10 48 33 PM](https://user-images.githubusercontent.com/6239798/106709211-06080780-65a9-11eb-89f0-98a268d0c3be.png)

@abhi7cr It just doesn't show up on the browser. I checked the network tab and no response code is given. I forgot to mention that the screen shots in the Verify tab show up just fine if that helps

**Comment by ganipcanot** [comment]
Resolving due to age - please re-open if you are still experiencing issues.
