### ISSUE TITLE
amplify application does not request the server

### ISSUE THREAD

**Issue by israelitalo** [aws-amplify/amplify-console#1519]
![Capturar](https://user-images.githubusercontent.com/49887063/106397825-26d82d80-63ee-11eb-9933-f17947ef85c3.PNG)
Hi! I have a REST API on a node hosted on an EC2, which has CORS released.
I uploaded the front-end (REACT) to this api, but he is unable to make the request to the server.
Do you have any idea why?

On the navegaor network, in Request Headers, a message appears: rovisional headers are shown. I suspect the request is going with an empty header ...

I saw that amplify allows you to customize the request header, but I want to use the standard headers. Do I still need to change this option? Can anyone show an example of how to set a standard header?

I added the proxy to the package.json file.

Note: the front-end is able to make requests normally on localhost for the api.

Thank you in advance

**Comment by abhi7cr** [comment]
Hi @israelitalo, are you directly hitting the REST Api from the browser or going through a proxy ?
