### ISSUE TITLE
SPA index page accidentally cached for 86400 seconds in CloudFront edge location

### ISSUE THREAD

**Issue by qxzzxq** [aws-amplify/amplify-console#1522]
**Describe the bug**
I am having this problem with my Angular application. After a recent code deployment, my website doesn't work anymore when I try to open the root URL (https://www.yankong.org). It works without any problem if I directly open other pages (for example https://www.yankong.org/review).

After some investigation, it seems that the problem comes from the index page. An old version of the index page is accidentally cached in an edge location for 86400 seconds so it always tries to load outdated stylesheets and js files (which no longer exist). As a result, Amplify redirects these requests to the index page, and the application cannot be loaded.

![image](https://user-images.githubusercontent.com/17144939/106414034-91d54300-6486-11eb-8ddd-188f76b8e625.png)

![image](https://user-images.githubusercontent.com/17144939/106412975-e3c89980-6483-11eb-8f81-a390ef771e59.png)

I also tried to open the URL with a VPN connection (in order to use another CloudFront edge location), and the app works. 

**Expected behavior**
The index page should not be cached for this long. Normally even in the performance mode, the `s-maxage` is set to 600 seconds. I don't know why my index page was cached for so long and it never gets purged even after re-deployments.
![image](https://user-images.githubusercontent.com/17144939/106412093-cf839d00-6481-11eb-9054-54a8647789b1.png)

Or could we have the possibility to manually invalid edge location caches?

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - Browser chrome, safari, MS edge
 - Version any

**Additional context**
I am using Angular 11.1.1. The edge server that caches the index page is `KIX56-C1` (there may be others)

**Comment by ganipcanot** [comment]
Can you confirm your appId: `d25acyg7ezko7f` and region: `us-east-1` (IAD) are correct?

**Comment by qxzzxq** [comment]
> Can you confirm your appId: `d25acyg7ezko7f` and region: `us-east-1` (IAD) are correct?

yes they are correct

**Comment by qxzzxq** [comment]
hi @ganipcanot, do you have any update about this issue? fyi, after the cache was expired, my app has been working correctly. But I am still curious about the cause of this issue :)

**Comment by ganipcanot** [comment]
Amplify allows for flexibility in caching mechanisms through various mechanisms, one being cache-control headers. 

As documented here https://docs.aws.amazon.com/amplify/latest/userguide/ttl.html we will honor cache-control headers sent by clients:

"Note that apps hosted with Amplify Console honor and reuse the Cache-Control request headers sent by clients, unless they are overridden by a custom header that you define."

One of the by-products of this design is that if a client sends cache-control headers that increase the max-age and didn't include an s-maxage header, CloudFront will use that age to cache the content at the edge level. We realize this by-product can have unintended effects.

We currently have a fix in flight for this.

**Comment by qxzzxq** [comment]
That's great :) thank you for your response
