### ISSUE TITLE
Amplify Console Monitoring improvements and Real-Time Access Logs 

### ISSUE THREAD

**Issue by arnaskro** [aws-amplify/amplify-console#1524]
**Is your feature request related to a problem? Please describe.**
Currently, for our amplify deployed website, there is no way to monitor incoming requests, cache hit rates, latency, and error rates which is very important for DevOps. Access logs do actually provide some information for all of this, but they take up to 1 hour to appear, meaning if there is something wrong that we don't notice ourselves it can take up to 1 hour to find out about it. 

**Describe the solution you'd like**
Ideally, we would like to monitor the Cloudfront instance which is created by the amplify app. We are interested in monitoring incoming requests, cache hit rate, latency, and error rates. 
Having real-time or 5min late access logs would work for us too since we could reuse the current setup we have now to monitoring everything we need.

**Additional context**
At the moment we have a setup where we schedule a Cloudwatch job to trigger a lambda function every 5 minutes, which will call amplify to generate access logs, then we upload them to S3, trigger SNS to forward to Splunk, and connect that with Grafana for monitoring. We perform multiple deployments throughout the day, and our website is one of the most visited ones in Norway, so having good up-to-date monitoring is crucial for us.
We are still live with our old solution where we primarily use S3+Cloudfront+Cloudwatch, and the amplify solution is running in a shadow now. The only thing really holding us back from fully switching to amplify is monitoring, because we don't want to go live without knowing what is working and what is not, so it would be great to get some improvements with this 😊

**Comment by abhi7cr** [comment]
Hi @arnaskro, 

Thanks for reaching out. We are in the process of surfacing CloudFront metrics to the Console, will update this thread once its out :)

**Comment by arnaskro** [comment]
I can't believe how fast you guys are 🎉 
This morning I opened up amplify console and to my surprise, there are 3 new features: CloudFront metrics, alarms and Dark Mode 🥳 You just made my day! Thank you and keep up the good work 🤩

**Comment by KristinaPeterson** [comment]
The documentation for monitoring Cloudwatch metrics and setting alarms is now available at this link:
https://docs.aws.amazon.com/amplify/latest/userguide/access-logs.
