### ISSUE TITLE
Domain management is missing from App Settings

### ISSUE THREAD

**Issue by giorgiocarniel** [aws-amplify/amplify-console#1525]
** Please describe which feature you have a question about? **

Unable to find a way to connect a domain to my Amplify application.

** Provide additional details**

I'm following this guide, but under my App Settings on Amplify I don't have the voice "Domain Management".
https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-amazon-route-53.html

What am I missing?

![No_DomainMngmnt](https://user-images.githubusercontent.com/69838480/106488257-cf9c9080-64b3-11eb-997e-0eb9db187b30.png)

**Comment by ganipcanot** [comment]
Could you share more  details about your app?  

How did you deploy the app?  
Is it backend only?
Frontend only?
Fullstack?  
Did you do a manual deploy?
- S3?
- drag-and-drop folder?
- zip upload?
- URL upload?
Is the application CICD (meaning it's connected to a git repository like github, gitlab, codecommit)?
What is your `appId` and `region` (These are part of your app ARN)?

**Comment by giorgiocarniel** [comment]
> How did you deploy the app?

 By using the command `amplify publish`

> Is it backend only? Frontend only? Fullstack?

It's a backend + React frontend

> Did you do a manual deploy?

I'm not sure what you mean but I just use `amplify publish` and the files are uploaded on an s3 bucket

> Is the application CICD (meaning it's connected to a git repository like github, gitlab, codecommit)?

Not yet

> What is your appId and region (These are part of your app ARN)?

I'm working on eu-central-1 and my app id is doi87xs5wbi44

**Comment by giorgiocarniel** [comment]
Any news about it? I have no ideas how to make that "Domain Management" page appear.

**Comment by giorgiocarniel** [comment]
Solved it by connecting a frontend repository.
