### ISSUE TITLE
Amplify stuck in deploy stage again.

### ISSUE THREAD

**Issue by ryanbagwell** [aws-amplify/amplify-console#1527]
```
2021-02-01T18:44:45 [INFO]: Starting Deployment
2021-02-01T18:44:45 [INFO]: Updating Edge config
```

App id: dzdjg1b39mpia
Preview pr-671
Build #39

I cancelled after about 45 minutes.

**Comment by ganipcanot** [comment]
Could you share the region where this is happening?

**Comment by ryanbagwell** [comment]
Happened again just now:

```
2021-02-02T22:17:33 [INFO]: Starting Deployment
2021-02-02T22:17:33 [INFO]: Updating Edge config
```

us east 1

**Comment by ryanbagwell** [comment]
happened again:

```
2021-02-02T22:28:20 [INFO]: Starting Deployment
2021-02-02T22:28:21 [INFO]: Updating Edge config
```

build no. 692.

us east 1

**Comment by ryanbagwell** [comment]
Happened for a third time. Build 693.

Please help.

**Comment by ganipcanot** [comment]
We are taking a look at this issue.  Do you happen to know the last time your builds were working i.e. specific build number?  Looke like there was a pause between 1-29 (Build number 670) and 02-02.  Was 670 the last known working build if you can recall?

**Comment by ryanbagwell** [comment]
tried to access the web console this morning to answer your question but there is a React js error that's preventing the UI from loading.

<img width="1215" alt="Screen Shot 2021-02-03 at 9 22 09 AM" src="https://user-images.githubusercontent.com/365105/106759959-50b56e00-6601-11eb-8740-95e427810e2a.png">

**Comment by ryanbagwell** [comment]
I went back to the Amplify web console landing page, and was then able to navigate to the master branch build history, but the build history is empty. It shows no builds.

**Comment by ryanbagwell** [comment]
![Screen Shot 2021-02-03 at 9 29 58 AM](https://user-images.githubusercontent.com/365105/106761030-6a0aea00-6602-11eb-961e-d8e2fbf646e4.png)

**Comment by ryanbagwell** [comment]
We triggered a build via the API, and it appears to have built and deployed successfully.

We still need an answer about these deploy phase problems, however. This happens far too frequently and our clients are demanding answers.

**Comment by ganipcanot** [comment]
> tried to access the web console this morning to answer your question but there is a React js error that's preventing the UI from loading.
> 
> <img alt="Screen Shot 2021-02-03 at 9 22 09 AM" width="1215" src="https://user-images.githubusercontent.com/365105/106759959-50b56e00-6601-11eb-8740-95e427810e2a.png">

Can you confirm what page this is on, or maybe provide a screenshot of the page you're using?

**Comment by ganipcanot** [comment]
We have some fixes that we are testing now.  Will let you know once it makes it into `us-east-1` (IAD)

**Comment by nimacks** [comment]
We have pushed a fix for this issue. Re-open if you're still experiencing issues.
