### ISSUE TITLE
Multiple frontends: Amplify build not working after publication

### ISSUE THREAD

**Issue by TinoOnline** [aws-amplify/amplify-console#1529]
**Describe the bug**
I am using the multiple frontends scenario and following the documentation (https://docs.amplify.aws/cli/teams/multi-frontend). I have one front end (A) that houses the backend where it was initialized, after creating the react project. This front end works well and builds without errors when I publish it to the repository. The second front-end (B) however which is another react project has the issue, I ran the amplify pull command and added the schema manually. I tested it on my local machine and it reads from the correct backend environment A, the moment I got to publish this, and the build finishes on the amplify console. The application gives me errors like :
<img width="1440" alt="Screenshot 2021-02-02 at 13 59 00" src="https://user-images.githubusercontent.com/64155956/106597314-eba93c00-655e-11eb-8f59-52da0408889c.png">

<img width="1440" alt="Screenshot 2021-02-02 at 13 37 38" src="https://user-images.githubusercontent.com/64155956/106597099-9a00b180-655e-11eb-823e-51f4f5266e88.png">
"ERROR] 56:51.816 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties. 
            Did you run `amplify push` after adding auth via `amplify add auth`?
            See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information"

even though it was working fine on the localhost. Add this is the same case with all the other parts such as the APIs.

**To Reproduce**
1. React New React project
2. Pull backend changes from an existing amplify project
3.  Test locally - all good
4. publish to the repository
5. Wait for the build to finish
6. build completes successfully but the backend does not seem to be connected correctly or at all.

**Expected behavior**
The expected behavior is that after pushing my changes and the build completing; the application is meant to use the new backend environment (from A), i.e. the authentication works, the graphql calls should work... but it's saying they aren't even installed. On my localhost environment, everything works (the environment is connected) before publishing.

**Desktop (please complete the following information):**
 - OS: MacOS BigSur
 - Chrome
 - Version 87.0.4280.66 

**_This issue is directly related to this: https://github.com/aws-amplify/amplify-console/issues/460#issuecomment-652443342
I have the exact same issue but it seems to be working fine on localhost but not live so I am assuming it's related to the amplify console?_**

**Comment by swaminator** [comment]
@TinoOnline To get this to work in a CICD environment you have to commit your awsexports file to Git in one of your repos. Are you committing the file?

**Comment by TinoOnline** [comment]
@swaminator THANK YOU, I had not attempted that. it works, it is functional now. Thank you. 🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈
