### ISSUE TITLE
Auth method drop down on Query tab doesn't remember users default selection

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-console#1531]
I only use the API key when I'm developing yet everytime I go into run a query it defaults to IAM even though I don't have any IAM setup.

Would be wonderful if it remembered my last selection and then just used that going forward until I change it. It keeps catching me out then when you link that with issue #1530 it can cause quite a bit of frustration as my query disappears!

![image](https://user-images.githubusercontent.com/1674590/106608540-6e7cc780-655c-11eb-9ed5-dd0991453b2d.png)

**To Reproduce**
1. Go to AppSync
2. Click on "Query"
3. Write a query
4. Change the auth drop down to API key
5. Refresh the page
6. Drop down will have reverted to IAM again.

**Expected behavior**

The console remembers the last Auth method I had selected between logins/refreshes/etc.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Comment by swaminator** [comment]
Please open a ticket with the AppSync team here: https://forums.aws.amazon.com/forum.jspa?forumID=280
