### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by rahul-vrecruit** [aws-amplify/amplify-console#1535]
**App Id**: d1mllz0iwwfiqy
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I had completed the necessary steps and added the DNS entries on godaddy and was getting "We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue" message.
But it is stuck in this message since yesterday afternoon (IST)

**Error message**

**Additional information**

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
