### ISSUE TITLE
Unable to connect branches to app

### ISSUE THREAD

**Issue by lukehedger** [aws-amplify/amplify-console#1537]
**Describe the bug**
We are unable to connect branches from a GitHub repository to our Amplify app. Have tried via AWS Console and AWS CLI, both return error message:

```
Oops, something went wrong. Please try again later.
```

<img width="736" alt="image" src="https://user-images.githubusercontent.com/1913316/106900706-bcc1d000-66ee-11eb-896a-a2c87de0e843.png">

The repository is connected and already has the `master` branch connected and running automated builds.

**To Reproduce**
```
aws amplify create-branch --app-id abc --branch-name xyz
```

App ID: d9slrnc36kbq7
Region: eu-west-2

**Comment by hsspain** [comment]
@lukehedger It appears that you have hit an internal limit.  If you close out or merge some of your existing PRs, this will enable you to continue to create branches.

Please let us know if that helps or if you need further assistance.

**Comment by ganipcanot** [comment]
Additionally for your non PR branches, if you re-deploy them via the console via manual ZIP upload, manual S3 (zip of the build artifacts uploaded to S3) or move them to a CI/CD workflow - it should also help get your branches deployed.

**Comment by lukehedger** [comment]
Thank you @hsspain - disconnecting branches seemed to fix the issue.

**Comment by lukehedger** [comment]
Need to re-open this as I have now tried to connect another branch and getting the same error. There are only two branches connected to the app - master and one other.

**Comment by abhi7cr** [comment]
Hi @lukehedger,  
It does look like a lot of the PR branches are still present in one of our persistence objects causing the limit to be reached. However,  I do see only 2 **active** branches associated with your app. I will work with another engineer in a couple of hours to prune the stale PR ones once you confirm on your side that you are not accessing the PR branches (_previews_) anymore via the url.

**Comment by lukehedger** [comment]
Hi @abhi7cr - yes, please prune any state PR branches. I can confirm we are not accessing them via the URLs anymore.

Thank you for your help! 🙏

**Comment by abhi7cr** [comment]
Hi @lukehedger,  the stale branches are most likely caused by a bug on our side. I am still investigating the logs to get a better understanding. I did notice one of the stale pr branch builds failed, so could be related to an edge case. I will keep you posted :)

**Comment by abhi7cr** [comment]
Hi @lukehedger, we pruned **114** branches starting with `pr`. This should give you enough room to create branches now. 
There are still **41** stale branches (_dependabots, other branches_) excluding the **2** active branches. We could clean them too if you are not using them. We are still investigating the rootcause. 🙂

**Comment by lukehedger** [comment]
Hey @abhi7cr - wow, that's a lot of stale branches! Yes, please prune the remaining 41 stale branches. I can confirm none of them are still in use (we didn't know they were still available!).

Good luck with investigation the root cause. Please let us know if you find anything we need to change in our workflow/settings. Thanks for your help.

**Comment by nicki9knuckles** [comment]
@abhi7cr I am having the same issue with my app:
App ID: dv8ybb6qjbg9d
Region: us-east-2

Should I create a new github issue for this, or can you take a look at pruning the stale branches for me as well?
Thanks!

**Comment by quinnturner** [comment]
I think I am having the same error as well, `d3fdiq126p9gfo` `us-east-1` https://github.com/aws-amplify/amplify-console/issues/2180

**Comment by ferdingler** [comment]
@quinnturner, I only see 11 branches on your app. I assume you manage to clean them up? I see that you also have enabled the Branch auto-disconnection configuration. That is a good idea so that when you delete branches from your repo, they automatically get deleted from Amplify. 

@nicki9knuckles your app does have 50 branches so you have already reached the quota. You don't have enabled the auto-disconnection of branches. I recommend you do it so that you don't have to manually disconnect branches on Amplify. 

You can find this in the Console under App Settings > General: 

<img width="510" alt="Screen-Shot-2020-06-24-at-12 34 40-AM" src="https://user-images.githubusercontent.com/3701083/130693664-6eeb571f-68bd-4582-962a-654b7abdd3b1.png">

**Comment by ferdingler** [comment]
@nicki9knuckles by the way, you can disconnect the branches yourself if you go to your Amplify app, under App Settings > General you'll see the list of branches. Simply select the ones you no longer need and click Actions > Disconnect branch. 

Let us know if you need further assistance. Thanks

**Comment by quinnturner** [comment]
@ferdingler I had another AWSer delete all of them. Unfortunately, there's a bug in Next.js (SSR) apps in Amplify where branches are not cleaned up despite having auto-delete branches on. My previously linked issue tracks that lack of closing issue.

**Comment by blaineo** [comment]
@ferdingler I work with @nicki9knuckles on the same application and we need our PR branches pruned. We have turned on the auto-disconnection, but have no way to clean up the unfinished deletions due to our use of Next.js.
