### ISSUE TITLE
Domain activation is Failed - Unable to add Subdomains with a domain name hosted in another AWS account.

### ISSUE THREAD

**Issue by mirnujAtom** [aws-amplify/amplify-console#1538]
**App Id**: d2uz048gh5b550
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Hey Amplify Team
Hope you are doing great! 

I am trying to configure a multi-account AWS setup for an app hosted in Amplify.
Currently, we've got 3 accounts test/dev/prod with separate Amplify apps for each env. 

We are trying to create subdomains for Apps hosted in each account, i.e testing.domain.io --> testing acc, dev.domain.io --> dev, domain.io --> prod

The domain name is added to the Route53 in our main acc.

As described here: [https://github.com/aws-amplify/amplify-console/issues/22](url) I was able to configure the domain name for the testing app by exclluding root and removing the www cname. However, when I try to add the "testing.domain.io" subdomain I get an error "Update domain association failed".

I have also tried to add a random name as a cname just for tests with no luck.
**Error message**
"Update domain association failed"

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

<img width="1693" alt="Screenshot 2021-02-04 at 16 16 12" src="https://user-images.githubusercontent.com/16191069/106907460-f1418600-6706-11eb-8b0a-0609d21f6957.png">
<img width="1758" alt="Screenshot 2021-02-04 at 16 16 38" src="https://user-images.githubusercontent.com/16191069/106907450-eedf2c00-6706-11eb-990c-27f64ccbc05b.png">

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
