### ISSUE TITLE
AWS Amplify console doesn't open with application contained ssh repository url

### ISSUE THREAD

**Issue by JIoJIaJIu** [aws-amplify/amplify-console#154]
**Describe the bug**
When I created a application on amplify as described in case aws-amplify/amplify-js#4071 and pointed git+ssh url
```
aws amplify create-app --name ... --repository git@bitbucket.org:...
```
After that I wasn't able to open AWS Amplify console - continuous loading and error in web-console
![amplify](https://user-images.githubusercontent.com/601863/65497795-684cf480-deed-11e9-9a6d-f82439f5ce33.png)

**To Reproduce**

1. Create amplify application through aws cli and with git+ssh repo url
    ```
   aws amplify create-app --name ... --repository git@bitbucket.org:...
    ```
2. Open https://console.aws.amazon.com/amplify/home
3. Continuous loading and error in the console
    ```
    this.host is undefined
    ```
    looks like `splitRepoUrl` cannot parse git+ssh urls

**Additional context**
1. Only manual removing application through **awscli** helps
2. Pointing urls as **git@bitbucket.org/** works well (with https:// schema its rejected by awscli api)

**Comment by garyleefight** [comment]
We only support https// like repository. And the repository link should be the one that links to the homepage of your repo. 
For example: https://bitbucket.org/{username}/{repoName}/src/{branchName}/

**Comment by JIoJIaJIu** [comment]
Hello @garyleefight 
Unfortunately such url is not supported by **aws cli**
```
$ aws amplify create-app --name ... --repository  https://bitbucket.org/path.git --platform WEB --oauth-token ...

An error occurred (BadRequestException) when calling the CreateApp operation: The repository url is not valid.
```
```
aws --version
aws-cli/1.16.244 Python/3.7.0 Linux/5.1.2-gentoo botocore/1.12.234
```
I can raise the issue in awscli repo if needs

Workaround is to submit repository url as
```
git@bitbucket.org/path
```
it's accepted by **aws cli** and aws console works well
