### ISSUE TITLE
Not starting build process, undefined repo

### ISSUE THREAD

**Issue by Neobii** [aws-amplify/amplify-console#1540]
**Describe the bug**
Repo flips back and forth between `https://github.com/undefined/tree/master` and my actual repo name and doesn't start build process.

**To Reproduce**
I created an app before where I could drag and drop HTML files, now I have connected it to my git repo with a similar setup of the other apps I have static deployed on amplify. 

**Expected behavior**
Provision deploy etc, but doesn't start the build process

**Screenshots**
https://share.getcloudapp.com/4gu1xWeG

**Comment by mabdullahabid** [comment]
Hey @Neobii, did you figure out what was happening here?

**Comment by Neobii** [comment]
Yeah, it looks like when I initially set up the host, I can’t start with
yarn, I have to use npm ci, otherwise the hosting gets stuck.

**Comment by mabdullahabid** [comment]
Hmm. I tried both. Still doesn't work.

**Comment by Neobii** [comment]
When I first create the server I have to use npm ci in the build settings
yaml.

version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

This way, it will get past the provisioning stage.  Once the first build
fails, I change the npm ci to yarn and and then my build works.
