### ISSUE TITLE
Improve amplify backend deployment processing

### ISSUE THREAD

**Issue by frankclaassen** [aws-amplify/amplify-console#1541]
**Is your feature request related to a problem? Please describe.**
Problem with amplify is that each time a deployment is done, it runs through the entire schema / cloudformation template and does updates when no changes were even done on the schema which makes deployments very slow.  A simple example is changing a small piece of javascript code on a component and then deploy. The amplify console will do a full backend deployment which is a complete waste of time and resources

**Describe the solution you'd like**
I would like amplify deployments to be smart and only update what has changed.  If a developer only does not make schema changes, don't redeploy the full backend.  If shema changes are made, only deploy the changes and not the full stack.  For example:  If I add a new @model type, just deploy the changes for that.  If I add a new @key, just deploy the changes for that

**Comment by swaminator** [comment]
@frankclaassen we added support for conditional backend builds: https://docs.aws.amazon.com/amplify/latest/userguide/conditional-backends.html
