### ISSUE TITLE
SSL configuration is Running - Amplify Console Add Domain from Google SSL Hangs but URL Resolves Correctly

### ISSUE THREAD

**Issue by jgairjr** [aws-amplify/amplify-console#1549]
**App Id**: d3aap5jpebw3tu
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I'm trying to use a domain registered using Google Domains with an AWS Amplify App (website). I've added the CNAME records to Google Domains, and navigating to the domain URL resolves to the Amplify App, but the Amplify Console Status still says "SSL Configuration" after more than 48 hours. The message on the page says "We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue in our GitHub issue tracker."

**Error message**
"We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue in our GitHub issue tracker."

**Additional information**
it has been more than 48 hours.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by jgairjr** [comment]
Thanks for sending those docs. I verified that the CNAME resolves correctly using "whatsmydns.net" as suggested in the first link. I also checked the CloudFront console and verified that I have no distributions. I'm not sure what other resource the CNAME can be associated with.

**Comment by jgairjr** [comment]
I've transferred my domain to Route 53 to help resolve this issue, but am still getting the same error message (Error message: One or more of the CNAMEs you provided are already associated with a different resource.). This is after deleting the hosted zone, the domain from the Amplify domain management console, and recreating a hosted zone.
