### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by baycultivate** [aws-amplify/amplify-console#1551]
**App Id**: d7kv57bq9cr6n
**Region**: us-west-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.
Setting up Domain Management with GreenGeeks. GreenGeeks is where I registered the domain 'https://baycultivate.com' and I want it to redirect to my aws url.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 
just says something went wrong

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

I'm trying to use a domain I registered with a different company, greengeeks. I've added the cName, but AWS Amplify is having trouble setting it up. I've had issues with Green Geeks, so I'm just trying to move forward and get this working.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
