### ISSUE TITLE
SSL configuration is Running - stuck on "We will now verify ownership of the domain"

### ISSUE THREAD

**Issue by markevans** [aws-amplify/amplify-console#1558]
**App Id**: dsu4j3n01arok
**Region**: eu-west-2
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Our DNS provider has two relevant CNAME records:
1. one for wildcard subdomains to point to cloudfront as per Amplify DNS instructions (it actually uses a different cloudfront subdomain, taken from instructions for a different Amplify app, but from the error message it seems to still work)
2. one to verify ownership of the domain - another subdomain we have shows this should work fine

According to the message below, 1 appears to be working but not 2

**Error message**
![Screenshot 2021-02-10 at 10 07 28](https://user-images.githubusercontent.com/12292/107495293-ce402780-6b87-11eb-98b5-2e0dce987a12.png)

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
