### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH with Third-Party Subdomain

### ISSUE THREAD

**Issue by ChadVerity** [aws-amplify/amplify-console#156]
** Please describe which feature you have a question about? **
We're building an app with Amplify, we've connected the domain and the DNS appears to be all correct, but we are getting  ERR_SSL_VERSION_OR_CIPHER_MISMATCH and I have no idea why or how to fix it. I'd appreciate any insight you'd be willing to give. We are using Cloudflare, and I'm not sure if that's part of the problem.
** Provide additional details**
The domain we have mapped to Amplify is app.holmetrics.com

**Comment by garyleefight** [comment]
Looks like your CNAME doesn't resolve https://www.whatsmydns.net/#CNAME/app.holmetrics.com

**Comment by Joycehao19** [comment]
@ChadVerity : Can you please provide your appId and region?

**Comment by bsithub** [comment]
Secure Connection Failed
Same Issue 
Error code: SSL_ERROR_NO_CYPHER_OVERLAP 
Region: ap-south-1
app Id: awsdev.globalhuntindia.com

**Comment by Joycehao19** [comment]
@bsithub Can you please provide your appId (Amplify Console -> App Setting -> General -> App ARN)

**Comment by bsithub** [comment]
App Id: arn:aws:amplify:ap-south-1:714744135226:apps/d2ewkckdcn0l3d

**Comment by bsithub** [comment]
> App Id: d2ewkckdcn0l3d
> Region: ap-south-1

Any help?

**Comment by simpson** [comment]
@bsithub did you ever figure this out?

**Comment by simpson** [comment]
@ChadVerity did you ever figure this out? I'm getting the ERR_SSL_VERSION_OR_CIPHER_MISMATCH
