### ISSUE TITLE
Domain activation failed 

### ISSUE THREAD

**Issue by GeneNcho** [aws-amplify/amplify-console#1560]
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I hosted an app on amplify before, but somehow the app disappeared and went offline. My Colleague hosted another app on a subdomain for the parent domain I used earlier. I don't know if that is what caused the main website to disappear. Right now I am trying to redeploy the app, but when I try to reconnect it to my custom domain hosted on Route53, it keeps failing at the domain activation stage. 
**Error message**
One or more of the CNAMEs you provided are already associated with a different resource. 

**Additional information**

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
