### ISSUE TITLE
Amplify Deployment Failing

### ISSUE THREAD

**Issue by benmkramer** [aws-amplify/amplify-console#1561]
**Describe the bug**
Amplify failing to build master (frontend).

The logs on the frontend build step appear to be as expected (nothing unusual). It just stops at some point often after "Compiled with warnings" or slightly after that, at which point building the react app is effectively completed.

**To Reproduce**
Trigger a deploy of master (either via merge code, or webhook, both are failing).

**Expected behavior**
App should continue deployment process as expected.

**Additional context**
us-east-1

Something odd is the pr preview branches seem to build fine, then once merged, they fail.

**Update 1**
After a few hours of failed builds, I've had one go through successfully on an adjacent app. Attempting redeploying other apps and all still consistently failing. Build logs don't indicate anything failing, it just seems to get to the point just after saying that it's compiled the app with some warnings, but failing before it prints the warnings and continues. I'm aware of the warnings and see them when running the same build process locally, they don't seem to cause an error though.

**Update 2**
Suspicious that the problem may be specifically with the master branch. It seems pr preview branches are deploying OK, and I created a random branch (off of master, with no changes) and it has built successfully several times in a row.

**Update 3**
Removed the cache of node modules from the build, and have seen successful builds again. Looking back at when the failures started, I don't see anything unusual in the logs. But, for now, likely going to leave the amplify.yml cache config out.

```
-  cache:
-    paths:
-      - node_modules/**/*
```
Still interested to understand why it started failing though 🤔

**Comment by benmkramer** [comment]
After a few hours of failed builds, I've had one go through successfully on an adjacent app. Attempting another rebuild here in case there was some strange intermittent issue.

**Comment by blairtaylor** [comment]
We are running into the same issue. We have 2 CI builds - one FE only and one FE and BE. The FE only succeeds while the FE and BE build fails while building the FE. Makes no sense since the FE build is identical for both.

**Comment by benmkramer** [comment]
@blairtaylor You could try removing the `cache` section from the frontend app's config where it is failing. It seemed to unblock us, at least to get deployed yesterday.

**Comment by blairtaylor** [comment]
@benmkramer Commenting the cache section does seem to work. Since the change our CI builds have been worked.

Just FYI:
- this was on a dev branch not a master branch
- after the CI build failed, I was able to trigger a build through the Amplify console which was successful even with the cache section enabled

**Comment by ConnorV645** [comment]
I can say that I had this same issue. Builds for me were failing after about 7.5 minutes, I'd have to redeploy about 5 times to get it to go through successfully after building for 15 minutes. I removed the cache and I now get successes after 7 minutes.

**Comment by behrooziAWS** [comment]
We have deployed some changes to how we do caching:

1. We limit the folder depth of the cache in case you accidentally have recursive symlinks leading to OOM errors during caching
2. We automatically omit node_modules/.cache to prevent intermediate files from bloating your cache size
3. We don't download old cache artifacts if you previously had a cache section in your buildspec but removed it

If I had to guess, your issue may have been related to fix 1.  Without app ids, I can't confirm.  Please reopen with app ids if you are still seeing this behavior.
