### ISSUE TITLE
SSL configuration is Running - Custom Domain works but not for the root domain

### ISSUE THREAD

**Issue by ashajjar** [aws-amplify/amplify-console#1562]

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
