### ISSUE TITLE
UX — Darkmode not applied an element in the Enable admin UI

### ISSUE THREAD

**Issue by omenking** [aws-amplify/amplify-console#1564]
<img width="765" alt="Screen Shot 2021-02-13 at 7 43 10 AM" src="https://user-images.githubusercontent.com/7776/107850283-49474f00-6dcf-11eb-83e3-cc39a8621ecf.png">

**Comment by abhi7cr** [comment]
Hi @omenking, thanks for reporting. The fix is in the pipeline and will let you know once it’s rolled out🙂
