### ISSUE TITLE
DX - Host web app vs Create app backend

### ISSUE THREAD

**Issue by omenking** [aws-amplify/amplify-console#1566]
As a developer I have the following options when using the Amplify Console:

1. Frontend (Just use Amplify Console to host my client-side code)
2. Backend (Admin UI provides a managed backend without requiring me to write back-end code)
3. Frontend + Backend 

So I wanted Amplify to take care of everything and wanted the 3rd option. I am presented with two options.

If you had to guess, which one do you think would take care of both the Frontend and the Backend?

<img width="1040" alt="Screen Shot 2021-02-13 at 7 46 48 AM" src="https://user-images.githubusercontent.com/7776/107850356-bf4bb600-6dcf-11eb-89e3-4cad5ee8a365.png">

<img width="256" alt="Screen Shot 2021-02-13 at 7 46 59 AM" src="https://user-images.githubusercontent.com/7776/107850361-c4a90080-6dcf-11eb-8e3d-16514c1b4d05.png">

I chose "Backend" because the Amplify Console's original offering was just Frontend hosting.
I also clicked into both due to uncertainty and when "Host Web app" asked to connect a repo, that made me think it was only frontend because a Frontend + Backend would be low-code and would not ask me too much upfront.

So I ended up creating the Backend, only to discover I had no Frontend. 

There is no way to add a Frontend to a Backend, so then I had to create Hosted web app and had setup all of my Backend again...

**Comment by swaminator** [comment]
@omenking if you start down the route of creating a backend first, you will be able to then create and connect a new frontend. Were you not seeing a Frontend tab with the ability to connect a branch?

**Comment by vic-blt** [comment]
@omenking What you need is a fullstack amplify app.
For that, you need to need to click on *Host web app*.
Then you select your repository and you deploy it on Amplify.
The thing is, you have to version the file `amplify/.config/project-config.json`.
You can found an example of here https://github.com/aws-amplify/amplify-console/issues/448#issuecomment-781233282
Otherwise your app won't be detected as fullstack, even if you have a frontend and a backend deployed.

**Comment by victorccccc** [comment]
Hi, we've improved our backend build feature, you can now configure the Amplify backend across apps. Details can be found here: https://docs.aws.amazon.com/amplify/latest/userguide/reuse-backends.html 

Feel free to re-open this issue if you have any question. Thanks!
