### ISSUE TITLE
Domain activation is Failed

### ISSUE THREAD

**Issue by mattb** [aws-amplify/amplify-console#1569]
**App Id**: dobr51ne9m48v
**Region**: us-west-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Trying to activate a domain "mikebiddulph.org" fails. Domain records are in Route53. Tried deleting all hosted records and recreating on Route53 but still fails. Other domain "michaelbiddulph.org" pointing to the same app had no problem during activation.

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by mattb** [comment]
I deleted the domain from the app, removed all records from Route53, and then re-added it. This time it worked.
