### ISSUE TITLE
Build fails while cloning: "Unable to clone repository"

### ISSUE THREAD

**Issue by butaca** [aws-amplify/amplify-console#157]
Log output:

```
2019-09-25T21:54:53.807Z [INFO]: Git SSH Key acquired
2019-09-25T21:54:53.910Z [INFO]: # Cloning repository: git@bitbucket.org:******
2019-09-25T21:54:54.063Z [INFO]: Agent pid 72
2019-09-25T21:54:54.067Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2019-09-25T21:54:54.119Z [INFO]: Cloning into '******'...
2019-09-25T21:54:54.240Z [INFO]: Warning: Permanently added the RSA host key for IP address '18.205.93.1' to the list of known hosts.
2019-09-25T21:54:54.368Z [INFO]: git@bitbucket.org: Permission denied (publickey).
2019-09-25T21:54:54.369Z [INFO]: fatal: Could not read from remote repository.
                                 Please make sure you have the correct access rights
                                 and the repository exists.
2019-09-25T21:54:54.370Z [ERROR]: !!! Unable to clone repository.
2019-09-25T21:54:54.370Z [INFO]: # Starting environment caching...
2019-09-25T21:54:54.370Z [INFO]: # Environment caching completed
Terminating logging...
```

App ARN
arn:aws:amplify:us-east-2:970150125456:apps/d1sstkga163z5f

_**Edit to add some extra info:**_

* Last successful build was on 2019-09-25T20:20:40 (timezone as shown in the logs).
* I didn't change anything in AWS Console or Bitbucket since then.
* The repo is private.

**Comment by Mangosteen-Yang** [comment]
> Log output:
> 
> ```
> 2019-09-25T21:54:53.807Z [INFO]: Git SSH Key acquired
> 2019-09-25T21:54:53.910Z [INFO]: # Cloning repository: git@bitbucket.org:******
> 2019-09-25T21:54:54.063Z [INFO]: Agent pid 72
> 2019-09-25T21:54:54.067Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
> 2019-09-25T21:54:54.119Z [INFO]: Cloning into '******'...
> 2019-09-25T21:54:54.240Z [INFO]: Warning: Permanently added the RSA host key for IP address '18.205.93.1' to the list of known hosts.
> 2019-09-25T21:54:54.368Z [INFO]: git@bitbucket.org: Permission denied (publickey).
> 2019-09-25T21:54:54.369Z [INFO]: fatal: Could not read from remote repository.
>                                  Please make sure you have the correct access rights
>                                  and the repository exists.
> 2019-09-25T21:54:54.370Z [ERROR]: !!! Unable to clone repository.
> 2019-09-25T21:54:54.370Z [INFO]: # Starting environment caching...
> 2019-09-25T21:54:54.370Z [INFO]: # Environment caching completed
> Terminating logging...
> ```
> 
> App ARN
> arn:aws:amplify:us-east-2:970150125456:apps/d1sstkga163z5f

Same error here in Sydney region

**Comment by madrussa** [comment]
Same again, eu-west-2. I've also tried removing and reconnecting the branch to no avail. I also tried removing the oauth connection in Bitbucket and recreating it... still same issue. All builds failing for us now.

**Comment by sarahsweat** [comment]
Having the same issue. All builds failing. SOS.

**Comment by TariqRumie** [comment]
Having the same issue as-well.

**Comment by garyleefight** [comment]
Thanks for reporting. We are working on it right now

**Comment by garyleefight** [comment]
@sarahsweat @TariqRumie Can you let me know which region your app lives?

**Comment by randallPerez** [comment]
@garyleefight i'm having the same issue, my region is us-east-1

**Comment by sarahsweat** [comment]
@garyleefight 
App ARN
arn:aws:amplify:us-east-1:190931189545:apps/dizosossq3y7o

**Comment by victorhsb** [comment]
same thing here, region is us-east-1
app id is:
arn:aws:amplify:us-east-1:830062373251:apps/d2936znhm1bogq

**Comment by swaminator** [comment]
@victorhsb @sarahsweat @randallPerez @TariqRumie @madrussa @Mangosteen-Yang @butaca We are currently experiencing issues building and deploying apps that are connected to BitBucket repositories. We are actively working on a fix to give users the ability to reauthenticate with Bitbucket. We apologize for any inconvenience caused and will update this issue with an ETA shortly.

**Comment by butaca** [comment]
@swaminator thanks. good to know you are working on this. Is there a way to deploy my app using a build done locally in my computer? I’m thinking this as a workaround, in order to be able to update my site.

**Comment by swaminator** [comment]
We are testing a fix currently and should roll something out shortly. Please track https://github.com/aws-amplify/amplify-console/issues/157 for updates.

**Comment by swaminator** [comment]
@butaca yes you can use manual deploys: https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html

**Comment by Mangosteen-Yang** [comment]
@swaminator Can we manual deploy on current butbucket project because we need to kepp using the domain URL.

**Comment by swaminator** [comment]
@victorhsb @sarahsweat @randallPerez @TariqRumie @madrussa @Mangosteen-Yang @butaca The fix has been rolled out. Can you please go to **General > App settings ** and choose **Re-authenticate**. This should fix the issue. Please let us know if this works.
![Screen Shot 2019-09-26 at 6 09 38 PM](https://user-images.githubusercontent.com/2429410/65734668-f0b3cc80-e088-11e9-97eb-c9ebe8f8e152.png)

**Comment by swaminator** [comment]
@victorhsb @sarahsweat @randallPerez @TariqRumie @madrussa @Mangosteen-Yang @butaca The fix has been rolled out. Can you please go to **General > App settings** and choose **Re-authenticate**. This should fix the issue. Please let us know if this works.
![Screen Shot 2019-09-26 at 6 09 38 PM](https://user-images.githubusercontent.com/2429410/65734798-82bbd500-e089-11e9-8b1a-cd195b742195.png)

**Comment by Mangosteen-Yang** [comment]
@swaminator After clicked the button, I got the same error during deployment.

**Comment by swaminator** [comment]
@Mangosteen-Yang can you try to reauthenticate again and trigger a new build? It's possible that your oauth token was in a stale state.

**Comment by Mangosteen-Yang** [comment]
> @Mangosteen-Yang can you refresh the browser and try to reauthenticate again. After that, trigger a new build. It's possible that your oauth token was in a stale state.

It success now, thanks. I will try other applications.

**Comment by anthonyjc** [comment]
@swaminator  Working for me now - thanks very much for the fix

**Comment by butaca** [comment]
@swaminatoe it’s working now. Thank you 🙏

**Comment by devengarg** [comment]
> @victorhsb @sarahsweat @randallPerez @TariqRumie @madrussa @Mangosteen-Yang @butaca The fix has been rolled out. Can you please go to **General > App settings** and choose **Re-authenticate**. After this is done trigger a new build which should fix the issue. Please let us know if this works.
> ![Screen Shot 2019-09-26 at 6 09 38 PM](https://user-images.githubusercontent.com/2429410/65734798-82bbd500-e089-11e9-8b1a-cd195b742195.png)

Thanks a ton! Its working now

**Comment by sarahsweat** [comment]
SUCCESS! Thank you thank you thank youuu! <3

**Comment by randallPerez** [comment]
@swaminator it's working, thank you

**Comment by salzbrenner** [comment]
@swaminator I am still getting this error. I'm dealing with two different AWS accounts, both with projects connected to Bitbucket. On one account, the re-auth fix worked. On the other account, re-authorizing does nothing. Still get the same auth build error

**Comment by butaca** [comment]
@salzbrenner I had to re authorize two times to make it work. Maybe this works for you.

**Comment by salzbrenner** [comment]
thanks @butaca , i've re authorized multiple times to no avail

**Comment by salzbrenner** [comment]
@butaca @swaminator nevermind, my fault. I wasn't admin of repo

**Comment by sbodi10** [comment]
@swaminator I'm still facing this issue. I've tried re-authenticating the app a few times, but the build still fails.

**Comment by sbodi10** [comment]
I believe this was because the repo is private. In order to use a private repo, an ssh key is needed.

Found this information from the below link:
https://forums.aws.amazon.com/thread.jspa?threadID=297933

**Comment by miguel258** [comment]
The same problem here with GitHub private repository, and its some complicated reconfigure all settings for my deploymet each time that the error occurs.

**Comment by torgeadelin** [comment]
I'm encountering the same issue.

**Comment by sbodi10** [comment]
For those who are having trouble deploying their private repo.. I wrote a blog post that describes what you'll need to do step by step. Hope this helps.

https://sapanbodiwala.com/blog/deploying-to-aws-amplify

**Comment by torgeadelin** [comment]
@sbodi10 I followed your tutorial and it's still failing...
@swaminator this is getting frustrating, could you investigate the issue?

**Comment by equivalent** [comment]
@sbodi10 nice article but this didn't solve my problem (As clone hapens even before preBuild phase)
@swaminator  re-authenticate app didn't work (I've tried it multiple times with pultiple accounts Admin/Owner ...no result) 

it worked when I created the app couple of days later this particular issue happen ( none of the solutions worked). Only thing that helps is deleting app and creating new ...But I have 10 SPAs I cannot do that forever.

**Comment by CGarces** [comment]
Same issue. 
It happens after --force-with-lease operation

**Comment by inmyth** [comment]
Still happening 2022 September. The only way to fix this is to delete and create new.
