### ISSUE TITLE
Creating an Amplify subdomain via api or console (automatically)

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-console#1572]
Is there any way to automate the process of creating a subdomain?

I.e. In the console, AWS Amplify->Domain Management->Manage Subdomains->Add

We assign a unique subdomain for each application client and would like to fully automate the client on-boarding process.

Right now we need to set this up manually via the Amplify console.

**Comment by kahdojay** [comment]
@blairtaylor - @SwaySway is correct, you can call CreateDomainAssociation but keep in mind that activating the custom domain requires that you first verify ownership by CNAME (see [certificateVerificationDNSRecord](https://docs.aws.amazon.com/amplify/latest/APIReference/API_GetDomainAssociation.html#API_GetDomainAssociation_ResponseSyntax)) which you might automate by calling Route53 APIs.

Closing this for now, let us know if you have any other questions or run into any issues

**Comment by manikpokhetra79** [comment]
> @blairtaylor - @SwaySway is correct, you can call CreateDomainAssociation but keep in mind that activating the custom domain requires that you first verify ownership by CNAME (see [certificateVerificationDNSRecord](https://docs.aws.amazon.com/amplify/latest/APIReference/API_GetDomainAssociation.html#API_GetDomainAssociation_ResponseSyntax)) which you might automate by calling Route53 API.
> 
> Closing this for now, let us know if you have any other questions or run into any issues

I am using createdomainassociation api to associate subdomain to amplify app but its not working.
I also tried adding a CNAME record to hosted zone, then call the api but it didn't create any association/entry in amplify app under domain management.
Any ideas on what is causing this behaviour
