### ISSUE TITLE
Domain activation is Failed - incorrectly configured DNS record

### ISSUE THREAD

**Issue by ajarti** [aws-amplify/amplify-console#1576]
**App Id**: dcfo4u6v8lwpa
**Region**: eu-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am trying to add a custom domain to an Amplify App, but the domain activation keeps failing.

**Error message**
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. 

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
I have removed all DNS records bar the NS/SOA several times and the newly added domain records by Amplify look fine, but the domain fails to activate with the above error.  I cannot find any track of another CloudFront distribution?

I have worked my way though:
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error

And still no joy.

**Comment by kahdojay** [comment]
@ajarti looks like the CNAME for one of your subdomains (www) is still pointing to a cloudfront endpoint, can you make sure there isn't a CNAME record in place for www.<yourdomain>.com?

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by ajarti** [comment]
@brnmye could you be any less helpful ... possibly not responding at all?  Did you even read the thread?  unless this is a bot response, in which case it's just adding cruft and needs tuning.

I have sorted out the issue myself, which is clearly the aim of this generic response I see on every post regarding this issue. 

Amplify adds  huge value and is very cost effective **self managed** solution, but I think adding paid support would be a better option than a half-arse attempt to look like support is given when really an auto-respond with _RTFM_ would do the same job.
