### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by tofmat** [aws-amplify/amplify-console#1578]
**App Id**: d3hg06jiyepb29
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company, etc.

**Issue/question**
Why do my domain activation keep failing.

**Error message**
Error message: The status of this certificate request is "Failed". One or more domain names have failed validation due to a Certificate Authority Authentication error.

**Additional information**
Been trying this for a long time. I am trying to connect a domain hosted in hostinger. And hostinger A records only support ip addresses. But amplify is requesting to connect a domain.

**Comment by kahdojay** [comment]
@tofmat it looks like you were able to set it up. That error could have been happening because you had a CAA record in place without the requisite values (see for example #200 or #1546).

Closing this for now, feel free to re-open if you're still having issues.
