### ISSUE TITLE
Branch auto detection does not work

### ISSUE THREAD

**Issue by mathvbarone** [aws-amplify/amplify-console#1579]
**Describe the bug**
We are using Amplify as a deployment tool within Raisin (the company I work with) and we would like to establish a convention to add `-amplify` as a postfix in the name of the branches that should be automatically deployed by Amplify.

However, if we put `*-amplify` or `**-amplify` as an auto-detection pattern, the branch is not being automatically recognized.

**To Reproduce**

- Go to General settings
- Click on Edit button
- Scroll down to Branch autodetection - patterns
- Click Enabled
- Add following patterns: `*-amplify,**-amplify`
- Click on Save button
- Push branch `feature/test-amplify`
- Nothing happens

**Expected behavior**
- The branch connected, the application is built and deployed

Additional context
arn:aws:amplify:eu-central-1:077441365433:apps/d2cfppkljv49ml

**Comment by garyleefight** [comment]
Hi, I tested. *-amplify works fine for me. Is it because you added double quote in your pattern configuration?
Use *-amplify instead of "*-amplify"
