### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by ccunning2** [aws-amplify/amplify-console#1581]
**App Id**: d26pdrxvogg6p
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

I see that the standard response is to post links to the troubleshooting pages. I have read and followed these pages multiple times at this point and don't know what else to do.

**Comment by brnmye** [comment]
I believe you are referring to these docs:
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Which part of these steps are you having an issue with?

**Comment by ccunning2** [comment]
Can you explain how to solve 'Error message
Error message: One or more of the CNAMEs you provided are already associated with a different resource.' ?

**Comment by fattoriaweb** [comment]
Same insue here, i created a app with de domain, and then changed to another domain, after that i added the first domain that i changed again and the error occurs.

It seems like the cloudfront distribution alreat exists but ai cant visualize the cloudfront distribution to remove it or edit it, it doens't exist
