### ISSUE TITLE
CloudFront cache not invalidated

### ISSUE THREAD

**Issue by thobson** [aws-amplify/amplify-console#1582]
**Describe the bug**
I was playing around with the customHeaders directive in amplify.yml and set a cache-control header to `"public, max-age=86400"` for `"*".` I subsequently deleted this directive and have been redeploying all day (10 times or so) however CloudFront is still returning a cached copy of the index file at "/". I tried enabling and disabling performance mode but it has no effect. It seems there is no way to invalidate the CloudFront cache. 

App ARN is arn:aws:amplify:eu-west-2:221735481848:apps/d2l9y02x47olju 

I'm hoping CloudFront with respect the 86400 max-age and fetch the origin in 24 hours. However the docs suggest that performance mode will fetch from the origin every 10 mins and standard mode with fetch on every request. Neither of these seem to happening.

**To Reproduce**
1. Go to [www.viko.co.uk](https://www.viko.co.uk)
2. Check the Cache-Control header
2. It is "public, max-age=86400"

**Expected behavior**
"public, max-age=0, s-maxage=2" or something similar

**Additional context**
Interestingly the other paths are ok e.g. [www.viko.co.uk/features/](https://www.viko.co.uk/features/)

**Comment by thobson** [comment]
More strange behaviour - it started to work as expected "public, max-age=0, s-maxage=2" but I then checked again and it's reverted to max-age=86400.

**Comment by hloriana** [comment]
Hi @thobson 👋🏽 are you still experiencing this issue?

**Comment by Athena96** [comment]
Closing this issue, If this is still an issue please feel free to reopen. Thank you!
