### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by rupam-bumba** [aws-amplify/amplify-console#1584]
**App Id**: d3qyu0j9paenbt
**Region**: ap-south-1
**Step**: SSL configuration
**Status**: Running

**Issue/question**
I closed an account on AWS which haveing a amplify app attach to a domain name on that account.
 now I want to shift that app from that account and add that domain name to this new account but I am getting error.
I want to use that domain name from my new account who can I get that .. how much time it will take  ?

**Error message**
Create domain association failed
One or more domains requested are already associated with another Amplify app: example.com

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
