### ISSUE TITLE
Amplify builds failing intermittently : JavaScript heap out of memory

### ISSUE THREAD

**Issue by victorbelt** [aws-amplify/amplify-console#1586]
**Describe the bug**
Amplify builds for AngularJS front end application intermittently fail with: _FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory._

We have four environments enabled and preview builds enabled for our develop branch.
Failure intermittently occurs with preview builds and environment builds. 
Occasionally the same code fails to build with preview merges but succeeds with environment branch merges.
Occasionally a manual 'Redeploy this Version' resolves the issue.
Build success and fail has become very inconsistent over the past week.
 

**To Reproduce**
1. Create pull request in github
2. Build either succeeds or fails.

**Expected behavior**
The build is expected to succeed.

**Screenshots**
The same pull request failed during automated build, then failed three manual rebuilds, succeeded on fourth manual rebuild. It is the exact same commit, code and configuration. 
![image](https://user-images.githubusercontent.com/24881270/108518367-5fb64480-72c0-11eb-9657-fda5196d47fd.png)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
We have recently moved to AOT for AngularJS. Failures were initially seen on previews builds only. We disabled previews and disabled `"sourceMap": false` to reduce the build memory footprint. 

Non preview builds were successful for about 24 hours and then started failing again.

We then removed caching in the amplify.yml located in the Amplify Console (we do not keep the amplify.yml directly in the codebase)
`-  cache:
-    paths:
-      - node_modules/**/*`

Builds again started working for about 24 hours, including preview builds but have now started failing again in the same inconsistent manner, sometimes the build succeeds and sometimes it doesn't.

We are using the default docker provisioning of 4 vCPU and 7GB Memory as follows:
`Use the standard Amazon Linux base, provided by ECR/KaOS
It points to the standard shared Amazon Linux image, with a versioned tag.
FROM 137112412989.dkr.ecr.us-west-2.amazonaws.com/amazonlinux:2
MAINTAINER Amazon AWS

_Framework Versions_
ENV VERSION_NODE_8=8.12.0
ENV VERSION_NODE_10=10.16.0
ENV VERSION_NODE_12=12
ENV VERSION_NODE_DEFAULT=$VERSION_NODE_12
ENV VERSION_RUBY_2_4=2.4.6
ENV VERSION_RUBY_2_6=2.6.3
ENV VERSION_BUNDLER=2.0.1
ENV VERSION_RUBY_DEFAULT=$VERSION_RUBY_2_4
ENV VERSION_HUGO=0.75.1
ENV VERSION_YARN=1.22.0
ENV VERSION_AMPLIFY=4.29.4
` 

Questions:
1. Why does the same code base build successfully sometimes but fails other times? Are the default dockers being provisioned during the build consistently 4 vCPU and 7GB Memory? 
2. Is it possible to provision an image with more than 4 vCPU and 7GB Memory? Would this be done with Custom Build Images? We would prefer to use the default image if possible.
3. Is the console housed amplify.yml always being referenced such that the caching settings are honored? Would it be better to move this into the codebase?

**Comment by victorbelt** [comment]
This issue was resolved in our use case by leveraging the node setting: `--max-old-space-size=6144`  _(6GB RAM to leave 1 GB of the 7 GB for any potential overhead needs)_ as follows:

Old Script Commands:

```
"start": "ng serve --disable-host-check",
"start-qa": "ng serve --configuration=qa --disable-host-check",
"start-beta": "ng serve --configuration=beta --disable-host-check",
"start-prod": "ng serve --configuration=production --disable-host-check",
"build": "ng build",
```

Updated Script Commands:
```
"start": "node --max-old-space-size=6144 ./node_modules/@angular/cli/bin/ng serve --disable-host-check",
"start-qa": "node --max-old-space-size=6144 ./node_modules/@angular/cli/bin/ng serve --configuration=qa --disable-host-check",
"start-beta": "node --max-old-space-size=6144 ./node_modules/@angular/cli/bin/ng serve --configuration=beta --disable-host-check",
"start-prod": "node --max-old-space-size=6144 ./node_modules/@angular/cli/bin/ng serve --configuration=production --disable-host-check",
"build": "node --max-old-space-size=6144 ./node_modules/@angular/cli/bin/ng build"
```

**Comment by tobinbc** [comment]
To aid anyone finding this with AWS Amplify Geo Location library using maplibre-gl and maplibre-gl-js-amplify this amazingly detailed solution fixes it.
