### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by fattoriaweb** [aws-amplify/amplify-console#1593]
**App Id**: dxeuftgjql81x
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
"com.amazonaws.services.cloudfront.model.CNAMEAlreadyExistsException: One or more of the CNAMEs you provided are already associated with a different resource. (Service: AmazonCloudFront; Status Code: 409; Error Code: CNAMEAlreadyExists; Request ID: 229affed-7996-483c-88f5-c38bba28b8eb; Proxy: null)",

**Additional information**
I do not have any cloudfront distribution or apigatway associated with my domain, or any other services, its a brand new domain and its on my route 53

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by fattoriaweb** [comment]
Hey tks for the reply,

I already try this guide but no success, the guide says that i need to edit my Distribution, but i dont have any distribution using my domain.

what happened is:
- I created an app with domain xxx.com
- Then a change the domain to yyy.com
- and now i am trying to add the xxx.com custom domain again, and got this error.
