### ISSUE TITLE
SSL configuration is Running - 8 plus hours

### ISSUE THREAD

**Issue by ibrahimcesar** [aws-amplify/amplify-console#1595]
**App Id**: d1z5mpo47b14mo
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Running

**Issue/question**
Validation is stalled at SSL configuration step

**Error message**
Only: We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue in our GitHub issue tracker.

**Additional information**
My domain is hosted and registered through Route 53 in the same account and the CNAME is already in place

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by ibrahimcesar** [comment]
After delete and tried two more times I finally git running
