### ISSUE TITLE
Update Hugo web framework to 0.58.x

### ISSUE THREAD

**Issue by TARDIS42** [aws-amplify/amplify-console#160]
**Is your feature request related to a problem? Please describe.**
Yes, unable to compile my web app on Amplify as the hugo web framework is on a older version.  Log below:

```
# Starting phase: build
# Executing command: hugo
2019-09-28T18:16:12.859Z [INFO]: ERROR 2019/09/28 18:16:12 HELLO-FRIEND theme does not support Hugo version 0.55.6. Minimum version required is 0.57
```

**Describe the solution you'd like**
Update Hugo version from 0.55.6 to 0.58.x or later release.

**Additional context**
None

**Comment by swaminator** [comment]
You can set the version of Hugo the latest here: https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates
This should fix the issue.

**Comment by TARDIS42** [comment]
Yup, setting that variable to `latest` fixed the issue.  Thanks!  Closing this issue.
