### ISSUE TITLE
App fails to deploy after changing backend env

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-console#1602]
**Describe the bug**
Can't deploy after changing backend env of a frontend env through Amplify Console. The amplify push fails. It seems the build is still stuck with some sort of remnant of the previous backend. I have to disconnect the branch and reconnect to get it to work. 

My amplify console id is d2d6ty1wlg8jch. 

The exact error is : 

`2021-02-24T20:52:15.307Z [INFO]: UPDATE_FAILED      LambdaExecutionRole AWS::IAM::Role Wed Feb 24 2021 20:52:14 GMT+0000 (Coordinated Universal Time) essapp<myfn>-<mybackend> already exists in stack arn:aws:cloudformation:us-east-1:<my_aws_id>:stack/amplify-ess-app-<mybackend>-215910-functionessapp0f5644a0PreTokenGeneration-1JXBZHOJZCDQD/4999acd0-a04f-11ea-9414-12328959da6d`

**Additional context**
It seems the auth role in the STACKINFO is still the previous backend: amplify-ess-app-<previousbackendname>-150238-authRole

**Comment by JosephVasse** [comment]
I'm facing the same kind of issue here : can't push my new backend, i,ve got the following error : 

`A deployment is already in progress for the project, cannot push resources until it finishes.`

Happened after a failed push 12hours ago. 

How do you disconnect/reconnect the branch ?

**Comment by kenchoong** [comment]
This still happened for me, all update in Amplify Admin ui Data model cant be deploy. 

Then when I make changes in `schema.graphql` and `amplify push` I get this error as well: 

> A deployment is already in progress for the project, cannot push resources until it finishes.

As mention in this issues: 

https://github.com/aws-amplify/amplify-js/issues/8085

**Comment by ryarasi** [comment]
Facing the same issue. This happened after I was facing some errors and it finished with errors. I then did an amplify pull to get my local schema synced with the latest successful push in the backend and it succeeded. Now when I make some additional changes to the pulled schema and push, it results shows this:-

`A deployment is already in progress for the project, cannot push resources until it finishes.`

**Comment by kenchoong** [comment]
@ryarasi go to ur s3 deployment bucket, delete the `deployment-state.json` 

[Refer this issue](https://github.com/aws-amplify/amplify-adminui/issues/172), recently pulling my hair off for 3 days, hope this not happen to you

**Comment by victorccccc** [comment]
Feel free to reopen this if issue persists
