### ISSUE TITLE
Can I use Amplify as a replacement for S3/CloudFront?

### ISSUE THREAD

**Issue by domi91c** [aws-amplify/amplify-console#161]
Just a quick question about Amplify. I managed to get it 90% working in about 5 minutes of work, but the Axios calls in my Nuxt app aren't being made.

Am I forced to use the Amplify API, or should Axios work as usual? I'm hoping to use Amplify as a simple replacement for S3/CloudFront, because it's been a very fast way to setup a CD pipeline for my frontend. But I already have my own API calls and auth solution. 

My API is handled with CloudFormation on an EC2 instance if that matters.

**Comment by swaminator** [comment]
Your API calls should work. What error are you getting?

**Comment by domi91c** [comment]
You're right, it was an issue with the proxy I had set up.
