### ISSUE TITLE
Domain activation is Failed - Amplify creates CNAME resources, then fails as a result of these resources existing

### ISSUE THREAD

**Issue by JessicaNeary** [aws-amplify/amplify-console#1611]
**App Id**: d4dpo55c42sfj
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am migrating an existing react web app to amazon Amplify. I have deleted the previous s3 bucket, cloudfront distribution, and all DNS records relating to the app. When I try to add my custom domain, it creates new CNAME and an alias record during the SSL creation and configuration steps, but fails on the last step with the error message, presumably as a result of the records created in the previous steps. This means I am unable to add my domain. I've followed all the troubleshooting steps with no luck.

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
After running the amplify add domain process, my website is able to be loaded from the domain, but is unsecure, and references an old, now expired amazon certificate. I use Route 53 as my DNS provider, but the domain is registered elsewhere.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
