### ISSUE TITLE
Cloudfront cache cookie

### ISSUE THREAD

**Issue by jenjen75** [aws-amplify/amplify-console#1613]
** Please describe which feature you have a question about? **
Hello,

Is there a way to configure Cloudfront cache cookie to ignore or whitelist ? Some cookies, like Google Analytics, generate new cookie value after each page loaded. The problem is, without cookie cache control, each request is cache-ignored and send to the S3 origin, so cloudfront cache is ineffective in this case.

** Provide additional details**
Example with cUrl with an arbitrary cookie:
![image](https://user-images.githubusercontent.com/22404507/109502011-b7129c80-7a98-11eb-99f5-9e4aa5e24a8a.png)

**Comment by VictorCcccc** [comment]
Hi @jenjen75, for better Cloudfront cache performance, you can add custom header, please refer to this doc: https://docs.aws.amazon.com/amplify/latest/userguide/ttl.html
