### ISSUE TITLE
Stuck on "Retrieving deployment details..."

### ISSUE THREAD

**Issue by brandonkun5** [aws-amplify/amplify-console#1614]
I tried connecting my Amazon S3 bucket to my AWS Amplify app but it is currently stuck on deploying. What is the reason for this?

**Comment by nimacks** [comment]
In order to better assist you, can you provide the following details:

- AppId. ( Send to aws-amplify-customer@amazon.com )

**Comment by ganipcanot** [comment]
Going to close this issue for now.  If you're still experiencing issues @brandonkun5 please re-open.  If you are still experiencing issues please provide appId (part of app ARN) and we can investigate.
