### ISSUE TITLE
Domain activation is Failed - Message is about CNAMEs already associated...

### ISSUE THREAD

**Issue by markcamos** [aws-amplify/amplify-console#1615]
**App Id**: d3gouz5o93easj
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
AWS Amplify Domain Activation failed with the error message below. I deleted the root domain and www.rootdomain and tried to retry the Add domain, but no joy.

**Error message**
Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: One or more of the CNAMEs you provided are already associated with a different resource. 

**Additional information**
Oddly, when I try to Add Domain my domain doesn't show up in the domain list (though it DOES show up in Route 53 - both as a Registered Domain and hosted zone.

Each time I do the Add Domain the A record Alias and CNAME for the root domain and www.root domain is replaced by the cloudfront  domain name and the app works (at least!) but, obviously, the SSL piece doesn't.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by markcamos** [comment]
Duh - it was an old cloudfront distribution... Thanks for the tip - I'm sorry I didn't find that in the docs, myself
