### ISSUE TITLE
SSL Connection Issue 

### ISSUE THREAD

**Issue by AdbC99** [aws-amplify/amplify-console#1616]
**App Id**: d1awnuwa8cl123
**Region**: London
**Step**: Customer accessing site from multiple browsers / machines
**Status**: Site down for customer but not developer

**Issue/question**
Whilst I can access the app perfectly, my customer cannot access it. Safari and Chrome both give SSL errors, and he has tried multiple devices, mobile + desktop. Customer was able to access app a couple of days ago, but it has been down for 1-2 days for him now.

**Error message**
Safari can't establish a secure connection to the server
Chrome: this site can't provide a secure connection

**Additional information**

Works on 4G for customer, but not on Wifi

**Comment by nimacks** [comment]
I confirmed that I was able to access the app with no issue. Can you provide more details on how your customer is accessing the site?

- What is the location they are in?
- Do they have any browser add-ons installed?
- Can they try loading the site with https://downforeveryoneorjustme.com/?
