### ISSUE TITLE
Third commit pushed while first build is in progress will be skipped, turning off the check on GitHub PR

### ISSUE THREAD

**Issue by astef-trilogy** [aws-amplify/amplify-console#1617]
**Describe the bug**
GitHub webhook is broken after third commit to a branch, if first build is still in progress. You have to re-create the PR with a different branch to see CI status.

**To Reproduce**
1. Commit to a new branch, create a PR for a repository connected to Amplify
2. Our build takes ~10 minutes. Push two more commits to the branch within this period.
3. Go to Amplify Build history - see no third build planned.
4. Go to GitHub PR - see no check is present at all (crashed and exited?)

**Expected behavior**
All three builds to run. Check to be present and show build status.

**Additional context**

After seeing this issue https://github.com/aws-amplify/amplify-console/issues/400 I have deleted all existing webhooks in settings, and re-connected the repository in Amplify app. It didn't help.

**Comment by behrooziAWS** [comment]
@astef-trilogy Can you send the appId, region and the commit hash of your third commit that didn't trigger to aws-amplify-customer@amazon.com and reference this issue?

**Comment by behrooziAWS** [comment]
It looks like what is happening is this:

1st commit starts building with job 1.
2nd commit is put in pending with job 2.
3rd commit sees that there is a pending build and updates job 2 with commit 3.  So commit 3 gets built with job 2 and there is no job 3.

I'll review this with the team.  If it is causing ci checks to break, we likely want to update this to not collapse commits on pull requests and just create 1 job per/commit.

**Comment by behrooziAWS** [comment]
We've made a change so it should cancel the second check-run when it collapses commit 3 into job 2.  Are you still seeing this behavior?
