### ISSUE TITLE
Incomplete awsexports file leads to a 401 error in Amplify CI/CD deployment

### ISSUE THREAD

**Issue by ntrabue** [aws-amplify/amplify-console#162]
** Which Category is your question related to? **
AppSync? Cognito? Amplify

** What AWS Services are you utilizing? **
AppSync, 
Cognito, 
Amplify CLI, 
Amplify console, 
DynamoDB

** Provide additional details e.g. code snippets **
Sorry, I'm sure this is something simple that I'm missing. Deployment to S3 and working locally I'm able to log in, query and mutate data but I get a 401 error on my Amplify Console deployment. I'm able to log in with email address and password no problem but the errors start as soon as I query for data. 

Here is the repo for the project: https://github.com/ntrabue/amplify-todo 

Please let me know if there is any more info I can provide.

Thank you!

**Comment by swaminator** [comment]
Update: Turns out its because there is a version mismatch between the Console and the CLI. You can set the version of the CLI to the latest here: https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates
This will fix the issue.
