### ISSUE TITLE
Custom Domain doesn't work without "www" before domain name

### ISSUE THREAD

**Issue by mro-robert** [aws-amplify/amplify-console#1620]
**App Id**: dm5g332ltk8gl
**Region**: us-east-2
**Step**: Custom Domain Activation
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Using go daddy for the domain. 
I followed all steps here: 
https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-godaddy.html 
And it's working if and only if I type the domain with "www" in front of it, if I skip the "www" doesn't work and it should. 
I reached out to go daddy and they told me it was something to do with reissuing ssl on aws/amplify part. 

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
DNS and DevOps are not my strong skill, please help me with this, thank you very much!

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by mro-robert** [comment]
the CNAME resolves correctly for "www.myapp.com", however gives error if it's just "myapp.com"
I followed the directions to setup a custom domain with go daddy. 
I get this error on chrome if I type the domain without "www": DNS_PROBE_FINISHED_NXDOMAIN
Any ideas?
