### ISSUE TITLE
AWS Amplify Console File Upload

### ISSUE THREAD

**Issue by basfordrobert** [aws-amplify/amplify-console#1622]
**Describe the bug**

**To Reproduce**
1. Go to 'https://ap-southeast-2.console.aws.amazon.com/amplify/home?region=ap-southeast-2#/d2ina7ghoi2un8'
2. Click on 'Chose files'
3. Scroll down to 'Archive.zip'
4. See error - Upload "Queued // Pending // Failed".  Note: Network bandwidth for upload 20Mbps & file-size "Archive.zip" 34.2MB  // Drag and Drop feature exhibits same behaviour.

**Expected behavior**
File "Archive.zip" uploads successfully followed by AWS frontend deployment web page updated with "Last deployment + new Date Time"

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [safari]
 - Version [e.g. 14.0.3]

**Comment by basfordrobert** [comment]
<img width="1026" alt="1622" src="https://user-images.githubusercontent.com/59182639/109882013-4ef8cc00-7ccd-11eb-931f-351225be6926.png">
Could be some data corruption has occurred in AWS Amplify backend or frontend end file transfer is defective.

**Comment by VictorCcccc** [comment]
Hi @basfordrobert, can you retry to drop project's build output directory or zip file? I can't reproduce your problem on my end.

**Comment by basfordrobert** [comment]
It seems to be working again.
However, I did get two upload fails followed by success.  As noted in the ticket our uplink is around 20Mbps (downlink x10) and was working quite well tested Speedtest.net so I don’t think it was a network issue but with NBN you never know.

Kind regards,
robert.basford@icloud.com
M. +61 (0)431 623347
About me:   otso.com.au
eCard: https://otso.com.au/card.html
