### ISSUE TITLE
404 Rewrite Still Not Working

### ISSUE THREAD

**Issue by bvirlet** [aws-amplify/amplify-console#1623]
**Describe the bug**

This is related to #1176. While there isn't a 502 error anymore, the 404 Rewrite doesn't seem to work.

App ARN arn:aws:amplify:us-east-1:324915367782:apps/d2zlsiaic5yx2j

**To Reproduce**
1. Go geniusscansdk.com/test
2. Notice you get a 404 but also a blank page

<img width="949" alt="image" src="https://user-images.githubusercontent.com/792706/109934456-db56bf00-7ccc-11eb-805d-489f72eadb5e.png">

4. Notice the configuration

<img width="870" alt="image" src="https://user-images.githubusercontent.com/792706/109934550-f32e4300-7ccc-11eb-9cd4-fbab0e1d997e.png">

5. Notice that the target page does exist
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/792706/109934626-06411300-7ccd-11eb-9a71-d94fe08c2aaa.png">

6. Notice that a 404 Redirect works properly
<img width="873" alt="image" src="https://user-images.githubusercontent.com/792706/109934747-27096880-7ccd-11eb-9d60-8771defeb965.png">
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/792706/109934795-31c3fd80-7ccd-11eb-9b28-6d0bf08950a8.png">

**Note that I'm leaving the app in this state because we can't expose a broken website to customers**

**Desktop (please complete the following information):**
 - Browser Firefox 85.0.2

**Comment by brnmye** [comment]
Hello, could you please share the source and target that you are using. I.e. if the target has a /<*> at the end of the path, please try removing that and let me know if that works.

**Comment by bvirlet** [comment]
> Hello, could you please share the source and target that you are using. I.e. if the target has a /<*> at the end of the path, please try removing that and let me know if that works.

Hi @brnmye ,

Looks like you removed your question, but just in case, the redirect is configured as follow:


Source address: `/<*>`
Target address: `/404/`
Type:  `404 (Rewrite)`

(Again, note that I'm leaving the app in this state because we can't expose a broken website to customers, so our live website is currently set to `404 (Redirect)`).

**Comment by siegerts** [comment]
hi @bvirlet, is this still an issue?  I tested the URL that you had posted above and the redirect to the 404 page seems to be working as expected (based on what I'm gathering from your info above 😄  ).

**Comment by bvirlet** [comment]
@siegerts yes, this is still an issue. As I mentioned above 

> (Again, note that I'm leaving the app in this state because we can't expose a broken website to customers, so our live website is currently set to 404 (Redirect)).

So, currently what you see in the live version is a 404 Redirect instead of a 404 Rewrite. The 404 Redirect works properly. The 404 Rewrite don't. (I just can't leave the website in a broken state while waiting for you guys to investigate…)

**Comment by siegerts** [comment]
Thanks for the followup, @bvirlet. 

Depending on how you are controlling the navigation in the app, can you add an `404.html` to the build output or directory and rewrite to that? That won't change the URL but it will show as a valid 404.

For example, I have an example React app @ https://main.d1m5x5zjik90i7.amplifyapp.com/ with the below rewrite for 404. It handles direct nav and in-app navigation.

```json
[
    {
        "source": "/<*>",
        "target": "/404.html",
        "status": "404-200",
        "condition": null
    }
]
```

If this is in app navigation (React, Vue, etc.), it's possible to catch unmatched routes and direct/push accordingly .

Is that an option? Hope that this helps.

**Comment by bvirlet** [comment]
Thanks for your reply. I do have a `404/index.html` and not a `404.html`. Would that cause the problem? (website generator is Jekyll).

**Comment by siegerts** [comment]
The below gives me the same behavior after putting the 404 page in a dir within the public build:

```json
[
    {
        "source": "/<*>",
        "target": "/404/index.html",
        "status": "404-200",
        "condition": null
    }
]
```

The bare `/404/` dir does not implicitly return the `index.html`.

**Comment by bvirlet** [comment]
This fixes the issue. Thanks.

**Comment by tatethurston** [comment]
I'm still seeing this issue for 404 rewrites
