### ISSUE TITLE
Yahoo domains do not allow "_" for CNAME

### ISSUE THREAD

**Issue by ernestrlee** [aws-amplify/amplify-console#1626]
**App Id**:
**Region**:
**Step**:
**Status**:

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**

When trying create a custom domain on my Yahoo hosted site, Yahoo does not allow an underscore, "_" in the CNAME, so I am not able to establish the custom domain due to the format of the name for the AWS cert manager validation server.  Is there a way to set up custom domains another way?  Maybe by using TXT record?

**Error message**
Error occurs in the Yahoo DNS settings, saying that it is an invalid name (due to the underscore).

**Comment by behrooziAWS** [comment]
Hi, unfortunately we only support cnames at this time and underscore is required in the name of the cname. This thread has some more details: https://forums.aws.amazon.com/thread.jspa?threadID=304209  Of note, we also do not support email verification as mentioned in the thread.
