### ISSUE TITLE
SSL configuration is Running - My domain is not getting verified. 

### ISSUE THREAD

**Issue by maxawad** [aws-amplify/amplify-console#1627]
**App Id**: d3dmepo6dnw2u1
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Running

**Issue/question**
The issues is that the domain have been verifying for about 24 hours now

I have added the domain to my Cloudflare DNS the same way I have added my other domain in the same Amplify

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
