### ISSUE TITLE
Amplify Stuck on Domain Activation

### ISSUE THREAD

**Issue by michaeljoelsmith** [aws-amplify/amplify-console#1628]
I transferred my domain from GoDaddy to Route 53, which was successful. Then I deployed a simple Amplify site and attempted to use my domain.  The Route 53 DNS records look correct.  However, the Amplify console is stuck on the "Domain activation".

Any help on getting past this step would be appreciated.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
