### ISSUE TITLE
Missing aws_appsync_authenticationType in Amplify deployment

### ISSUE THREAD

**Issue by Cas-Laputa** [aws-amplify/amplify-console#163]
**Description**
My application is using AppSync and it is multienv. The `aws-exports.js` is ignored from the Git so when the deployment is triggered by the change in Bitbucket, the amplify configuration is auto-generated internally from the Amplify console during the build. The `aws_appsync_authenticationType` is missing and the frontend will use AWS_IAM as default instead of AMAZON_COGNITO_USER_POOLS (my local config).

**To Reproduce**
1. Go to Amplify console
2. Connect project to bitbucket and select any backend environment
3. Make sure `aws-exports.js` is not committed to the GIT
4. Save and deploy
5. Query from the frontend
6. AppSync authorization error: UnauthorizedException - Unable to parse JWT token.

Request headers:

![image](https://user-images.githubusercontent.com/49227702/65021566-f2cbac00-d961-11e9-99a4-e0fb64f44b44.png)

**Expected behavior**
Detect API default authentication method and set `aws_appsync_authenticationType` to correct value. In my case, use AMAZON_COGNITO_USER_POOLS

**Comment by swaminator** [comment]
Update: Turns out its because there is a version mismatch between the Console and the CLI. You can set the version of the CLI to the latest here: https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates
This will fix the issue.

**Comment by Cas-Laputa** [comment]
> Update: Turns out its because there is a version mismatch between the Console and the CLI. You can set the version of the CLI to the latest here: https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates
> Please verify this works for you.

It works.

**Comment by Cas-Laputa** [comment]
@swaminator Setting the latest Amplify-cli has caused another build error:

> Parameters: [unauthRoleName, authRoleName] do not exist in the template

[Reference link](https://github.com/aws-amplify/amplify-console/issues/10#issuecomment-534723637)

**Comment by swaminator** [comment]
@Cas-Laputa I see you came across https://github.com/aws-amplify/amplify-console/issues/10#issuecomment-534787729
Will close this issue and provide additional updates there.

**Comment by helloPiers** [comment]
Thank goodness I found this ticket, after a lot of searching. It still seems necessary to set this "live updates" setting for the aws-exports.js to be generated properly during a console build. Is there a non-closed bug tracking a fix so the console build environment actually works out of the box, or should I open one?

**Comment by lorenzk** [comment]
Update: It is still necessary today to set live updates to "latest" or else you are using the broken amplify CLI version that silently swallows `aws_appsync_authenticationType`. 

<img width="571" alt="grafik" src="https://user-images.githubusercontent.com/74110/97007654-0290c900-1542-11eb-93e6-15cc0fb026d5.png">

It is confusing to me, that this ticket is closed while the default state of the amplify build environment is broken. Is there another place to open an issue for using the fixed version of the tool by default?

**Comment by malcomm** [comment]
Shouldn't Amplify CLI: "latest" be the default? This is confusing, if you want a specific version then you should pin it. But it sure seems like latest should be the default.

**Comment by duranmla** [comment]
IDK if this stills relevant but I am trying to fix an issue with DataStore with multi auth and the `aws_appsync_authenticationType` does not seems to have any effect on DataStore behaviour.

I have tried:

```ts
Amplify.configure({
      ...awsconfig,
      // https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/js/#configure-multiple-authorization-types
      DataStore: {
        authModeStrategyType: AuthModeStrategyType.MULTI_AUTH,
        aws_appsync_authenticationType: ['AMAZON_COGNITO_USER_POOLS', 'API_KEY'], // --> And also with a single string like 'AMAZON_COGNITO_USER_POOLS' and no changes are seen on the Logger when performing a request
      },
    })
```
