### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by a-farhat** [aws-amplify/amplify-console#1631]
**App Id**: d6lpa86eraat7
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I had a manual deploy application called "softcloud" successfully configured to the domain. I had also another application called "SCAng" that gets deployed from a github repo. so I deleted the manual and configured the domain with the github deployment app. I updated the CNAME with my DNS provider. 

**Error message**
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
![image](https://user-images.githubusercontent.com/5553585/110318281-f94a5980-8015-11eb-84aa-2a8024c259a2.png)

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by a-farhat** [comment]
Thanks for that, but still. originally, in the manual deploy, I did not have to do any setup with the Distributions. but if it makes any difference, the domain name for the distribution ***************.cloudfront.net is different from the 2 CNAMEs that are propagated for my domain. One CNAME for https://example.com  and  another CNAME for https://www.example.com. When creating or editing a distribution, I cannot add a *****************.cloudfront.net domain.

**Comment by a-farhat** [comment]
When I retry the Domain activation process, a new CNAME gets generated. How I can use the 2 already propagated CNAMEs with amplify? Thanks

**Comment by a-farhat** [comment]
Hello ! Hope all is well.
I am trying to find out what the difference is between the cloudfront domain in the cloudfront distribution:
![image](https://user-images.githubusercontent.com/5553585/110914769-7aa83180-831f-11eb-8624-e4216a5a031b.png)


and the one in amplify for CNAME configuration:
![image](https://user-images.githubusercontent.com/5553585/110914788-81cf3f80-831f-11eb-826c-2492014676a9.png)

they are different !
which one should I use for configuration with my DNS provider ?
thank you
