### ISSUE TITLE
Unable to attach custom domain to an Amplify App

### ISSUE THREAD

**Issue by toolsadminatl2it** [aws-amplify/amplify-console#1633]
I have hosted a React App in Amplify. I am not able to attach a custom domain to it. 

It says the domain is already associated with another app. However, I have not attached the domain anywhere.

I followed the troubleshooting guide [here](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html)  but the domain is not associated anywhere.

Any clue what the issue can be?

**Comment by ganipcanot** [comment]
Could your share some more details so we can try and figure out what is going on?  Your app ARN (or appId) and what custom domain you're trying to associate to your application could be useful in this case.

**Comment by ferdingler** [comment]
Closing as we don't have `appId` and `region` to troubleshoot on our end. Feel free to reopen and provide the requested info.
