### ISSUE TITLE
Builds failing on attempting to install amplify video plugin. 

### ISSUE THREAD

**Issue by tscole** [aws-amplify/amplify-console#1634]
**Describe the bug**
Builds failing on attempting to install amplify video plugin. 

**To Reproduce**
1. add `npm install -g amplify-category-video` to your prebuild 
2. Build hangs on `node ./postinstall.js` with no error. Eventually times out.

**Expected behavior**
It should install the plugin and build the app

**Additional context**
This worked on 05/03/2021. We have made no changes to our build script and it has suddenly stopped working.
App ID: d38nbwxvz29evz

**Comment by ganipcanot** [comment]
It looks like your recent builds are passing.  Closing this issue for now.  If you're still having issues please re-open the issue.
