### ISSUE TITLE
Domain activation is Failed - CNAME issue

### ISSUE THREAD

**Issue by tinarastic** [aws-amplify/amplify-console#164]
**App Id**: d1hzuvtb4krkm6
**Region**: ap-southeast-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
The domain activation fails even though the domain name is on Route53 and has only ns and soa records

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by swaminator** [comment]
Can you check the CloudFront console for a matching CNAME: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

**Comment by tinarastic** [comment]
Nice one, that was it. I had a previously configured distribution with certs and domain names. I'm guessing that despite deleting it from Route 53 the distribution kept putting it back in there? Either way, by deleting those entries from the distribution that solved my problem with the Amplify domain management. Cheers,
