### ISSUE TITLE
Difference between domain name in Cloudfront distribution and Amplify Domain Management

### ISSUE THREAD

**Issue by a-farhat** [aws-amplify/amplify-console#1641]
Hello ! Hope all is well. 
I am trying to find out what the difference is between the cloudfront domain in the cloudfront distribution: 
![image](https://user-images.githubusercontent.com/5553585/110803749-2d2cb580-8288-11eb-8846-023449b18391.png)

and the one in amplify for CNAME configuration: 
![image](https://user-images.githubusercontent.com/5553585/110803990-6d8c3380-8288-11eb-87e0-6bd8519fe969.png)

they are different ! 
which one should I use for configuration with my DNS provider ? 
thank you

**Comment by ganipcanot** [comment]
Amplify manages the actual CF distributions associated with an amplify app in our service accounts.  You would not see an amplify CF distribution in your personal account.

You should configure your DNS provider with whatever is shown on the Amplify console side, not the one you see in the Cloudfront console.
