### ISSUE TITLE
Backend environment cannot be deleted

### ISSUE THREAD

**Issue by andre-scheffer** [aws-amplify/amplify-console#1642]
**Describe the bug**
Deleting backend environments failed:

![image](https://user-images.githubusercontent.com/48789566/110858418-58c89380-82ba-11eb-97b2-cf6b3dd4f3e8.png)

![image](https://user-images.githubusercontent.com/48789566/110858429-5b2aed80-82ba-11eb-8c46-9769cdc9d7d0.png)

Then this message does not disappear:

![image](https://user-images.githubusercontent.com/48789566/110858469-667e1900-82ba-11eb-805e-8c9350f0979d.png)

But I can continue to work with backend environments that are actually to be deleted.

**Expected behavior**
As a developer, I expect that the environments to be deleted will actually be deleted.

**Comment by bhavinkamani-gt** [comment]
I am facing the same issue. I am seeing this message since last 30 minutes.

![Screenshot 2021-03-12 at 1 52 41 PM](https://user-images.githubusercontent.com/79074469/110912756-50b03880-833a-11eb-82f7-f42e5d766fc7.png)

**Comment by andre-scheffer** [comment]
https://github.com/aws-amplify/amplify-console/issues/1330#issuecomment-740632418 does the trick.

**Comment by andre-scheffer** [comment]
At first I thought https://github.com/aws-amplify/amplify-console/issues/1330#issuecomment-739493860 does the trick. But after creating a new backend environment with the same name (test) I see the same error again for the complet new backend environment.

**Comment by bhavinkamani-gt** [comment]
I had a web hook created for the build trigger which was blocking the
deletion. After removing the hook I was able to clear the message.

Best Regards

*Bhavin Kamani*

*Gembatech*

Mobile: +919342054041

=============================================================================

"This email is confidential and may contain legally privileged
information. If you are not intended recipient, you should not copy,
distribute, disclose or use the information it contains. Please email
the sender immediately and delete this message from your system.
Emails are susceptible to corruption, interception and unauthorized
amendment; we do not accept liability for any such changes, or for
their consequences."
----------------------------
Gembatech, Bangalore, India

**Comment by andre-scheffer** [comment]
@swaminator please reopen this issue. My problem was not solved.

**Comment by weeksseth** [comment]
This is still an issue. We have been waiting for an environment deletion to complete for over two weeks, and it it causing other deployments to fail.

**Comment by bhavinkamani-gt** [comment]
@weeksseth  Try amplify-cli with `amplify delete` command. That worked for me. I tried this after waiting for a night.

**Comment by weeksseth** [comment]
@bhavinkamani-gt, thanks for the suggestion, but I only want a specific environment to be deleted, not the whole app.

**Comment by andre-scheffer** [comment]
Hi, any updates on that?

**Comment by andre-scheffer** [comment]
Found a solution:

1. Delete all related stacks in CloudFormation
2. In your local IDE: Add an empty dummy entry for the relevant environment in file team-provider-info.json
3. "amplify -push" --> Than you will get an error
4. "amplify env add" --> Here you can add the relevant environment again
5. "amplify -push" --> Tha should work
6. No you can delete the relevant environment with "amplify env remove" --> Now it should work and your repository is clean again.

**Comment by andre-scheffer** [comment]
@swaminator, could you please reopen this and take a look at my specific case? After everything went well for a while, it bothers me again after recreating the backend environment of the same name:

![image](https://user-images.githubusercontent.com/48789566/113180511-178c2980-9251-11eb-943b-ea1f3f9149c8.png)

**Comment by ganipcanot** [comment]
Closing due to age - please re-open if still experiencing issues.
