### ISSUE TITLE
Cloning of a backend environment fails

### ISSUE THREAD

**Issue by andre-scheffer** [aws-amplify/amplify-console#1644]
**Describe the bug**
Cloning of a backend environment fails:

![image](https://user-images.githubusercontent.com/48789566/110918460-7c6ff600-831b-11eb-8c7c-24259f17af01.png)

**Comment by victorccccc** [comment]
Hi, thanks for reporting this. Are you still have this issue? 

If this issue persists, could you please fill out the relevant issue template to help us troubleshoot: https://github.com/aws-amplify/amplify-console/tree/master/.github/ISSUE_TEMPLATE

Thank you!

**Comment by siegerts** [comment]
Hi @andre-scheffer, are you still having this issue? I'm going to close this issue for now but please open a new issue (as referenced above) if the behavior still exists.  That will help provide the team with a bit more context for debugging.
