### ISSUE TITLE
Deploy amplify project to regions which don't support cognito

### ISSUE THREAD

**Issue by gaochenyue** [aws-amplify/amplify-console#1649]
** Please describe which feature you have a question about? **
I'm trying to deploy an amplify project to HongKong ap-east-1, but it failed with the error below. 
`CREATE_FAILED amplify-vendorauto-hkprod-135803-authvendorauto9ce87142-1MXGA9T1CLNS5 AWS::CloudFormation::Stack Fri Mar 12 2021 14:03:27 GMT-0500 (Eastern Standard Time) The following resource(s) failed to create: [IdentityPool].                                             
CREATE_FAILED IdentityPool                                                          AWS::Cognito::IdentityPool Fri Mar 12 2021 14:03:26 GMT-0500 (Eastern Standard Time) null (Service: AmazonCognitoIdentity; Status Code: 502; Error Code: null; Request ID: null; Proxy: null)`

 ap-east-1 is the list of supported regions of Amplify but it doesn't support Cognito. I'm not sure if that caused the error.

**Comment by ganipcanot** [comment]
Yes Amplify is launched in that region but unfortunately it looks like Cognito is not launched in `ap-east-1` yet.

In order for Amplify+Cognito to get up and running we'll need to wait for the Cognito team to officially launch in that region.
