### ISSUE TITLE
Parameters: [s3Key, deploymentBucketName] must have values

### ISSUE THREAD

**Issue by volkanunsal** [aws-amplify/amplify-console#1650]
**Describe the bug**

I created a function and pushed it from the CLI, and it deployed successfully. I have a continuous deploy set up for the master branch, so I pushed my changes to the remote, and it gave me this error during the build phase. 

> Parameters: [s3Key, deploymentBucketName] must have values

Both of these keys are available in `team-provider-info.json`.

I've tried deleting the function and creating a new hello world function. Same error. The continuous deploy pipeline seems to be unable to find these keys.

This is the command I'm using in my build script:

```yml
backend:
  phases:
    build:
      commands:
        - amplifyPush -s
```

Amplify CLI version: 4.44.0

**Comment by VictorCcccc** [comment]
Hi @volkanunsal, thanks for reporting this. Can you provide your App ARN for us to locate the issue?

**Comment by swaminator** [comment]
@volkanunsal can you check your live package updates and ensure you're using the latest version: https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates

**Comment by volkanunsal** [comment]
I didn't come across this issue again. So maybe it was fixed in a later version. I'll close it for now.
