### ISSUE TITLE
Domain activation Failed - Error message: One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by djasuncion** [aws-amplify/amplify-console#1653]
**App Id**: d22ck6crc780yq
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Domain activation failed. 

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Additional Info**
I've tried so many times with no luck. My domain is purchased from Namecheap. I've previously used Vercel to host my site, but I deleted that record in Vercel and in Namecheap.

I've added the 3 dns records provided by amplify. And the configuration still fails.

4 days without help.

I've changed my nameserver to aws (previously namecheap).

checking dns checker shows that i've set them up correctly.
I also transferred my email records successfully.

domain activation still fails at amplify console.

I'm also sure that I have 0 distributions in cloudfront.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by djma777** [comment]
> Refer to our documentation to troubleshoot domain setup.
> https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
> https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
> Let us know if you're still facing issues.

these docs doesn't for me at all. I have no distributions in cloudfront, like I said. I even transferred my nameservers to Route 534. None of these worked.
