### ISSUE TITLE
Amplify build failed to complete successfully

### ISSUE THREAD

**Issue by ParulSharma2622** [aws-amplify/amplify-console#1656]
I have created three instances for my application on amplify. All the instances were working fine few days back but suddenly one of my instance is not able to upload build successfully. 

Following are the three instances on my AWS amplify console:
1. branch A
2. Branch B
3. Branch C

However, first two instances are working absolutely fine but branch C is not able to deploy the build properly.

Here is my application id and region:
appId: d18qtdhf6c7z65
region: ap-southeast-2

Please let me know what's wrong at my end. so I can fix it. I really don't want to re-setup my branch. I want to know the root cause for this issue. I faced it 2 months ago and I fixed it by re-setting everything from scratch. I want to know exact reason this time so that it can be fixed permanently.

Thanks
Parul

**Comment by ParulSharma2622** [comment]
can anybody help me to resolve this issue.

**Comment by behrooziAWS** [comment]
Hi Parul, the build container is running out of memory during the caching step.  It looks like you have a lot of babel-loader, and terser-webpack files in the node-modules/.cache folder.  Likely we should automatically omit these in the cache, but can you add the following line `!node_modules/.cache` to your paths to cache in your buildspec to omit that folder?  That should get your build working again. i.e.:

```
  cache:
    paths:
      - node_modules/**/*
      - !node_modules/.cache
```

**Comment by ParulSharma2622** [comment]
I tried your solution and it worked. 
I hope, it will not repeat in future now.
Thanks Alot.!!!
