### ISSUE TITLE
Broken domain after transferring between AWS accounts

### ISSUE THREAD

**Issue by treski** [aws-amplify/amplify-console#1657]
**App Id**: d2ijfx64xoo032
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Running

**Issue/question**
I have an AWS created domain that seems to be broken. I had created it on an AWS account but needed access to it on another so I had it transferred by AWS support. When I try to use it in AWS Amplify, it gets stuck on the SSL configuration step with the following message: _In order to verify domain ownership, configure the following CNAME record associated with your domain and verify that the CNAME record exists in your Domain Name Server (DNS) file._ 

I thought this was strange, so I bought another domain that I will need later to simply test this process. That domain worked fine on another account with the same process. This domain seems to have somehow "broken" in the transfer process. I believe AWS thinks this is a 3rd party domain when it was indeed created in AWS.

**Error message**

**Additional information**

**Comment by ganipcanot** [comment]
Are you still having issues?  What is the domain you're trying to get up and running?
