### ISSUE TITLE
Domain activation is Failed - Unable to add custom domain

### ISSUE THREAD

**Issue by nottix** [aws-amplify/amplify-console#1663]
**App Id**: d3inyt16c4mcj0
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I'm trying to add a custom domain. I added DNS records properly but we receive an error.

**Error message**
I'm receiving this message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Additional information**
![image](https://user-images.githubusercontent.com/90825/111491591-46c47600-873c-11eb-8681-133e0bc0809e.png)

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
