### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by stevepetersen** [aws-amplify/amplify-console#1665]
**App Id**: d20g1r9gvh7n4i
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am trying to associate the p***t.com TLD and www.p***t.com with this app on Amplify, and it keeps telling me that the CNAME is in use somewhere, but I can't find the resource.  I've looked through my S3 buckets, CloudFront, etc, everywhere.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by djma777** [comment]
I have the same issue, no one's responding here, unfortunately. My case has been open for 5 days and I've been trying the same number of days.

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by stevepetersen** [comment]
Thank you for the reply. I have read through the documentation multiple times. The error message doesn’t say what resource the CNAME is referencing, so I am stuck. I have combed through all of my AWS resources and can’t find any reference to playlist.com or www.playlist.com anywhere in my account. Can you tell me specifically what resources are in conflict, or reimplement the error message to specify the resource in contention?

**Comment by stevepetersen** [comment]
bump.  still stuck, no response.

**Comment by nimacks** [comment]
@stevepetersen our records indicate that your custom domain for the app with id `d20g1r9gvh7n4i ` is available. Domain `joh*****.com`. In regard to your other domain, can you try re-creating a custom domain? It looks like it was deleted.

**Comment by nimacks** [comment]
Re-open if you're still having issues.
