### ISSUE TITLE
Cannot increase CloudFront timeout

### ISSUE THREAD

**Issue by GhostApps** [aws-amplify/amplify-console#1668]
I would like to be able to increase the timeout of my CloudFront distribution but it does not appear in the CloudFront console, can someone explain how I do this

**Comment by ganipcanot** [comment]
The cloudfront distribution will not appear in your account as Amplify manages it for you.

Could you give more details of what exactly you're trying to accomplish?

What do you mean when you say you're trying to "increase the timeout of the cloudfront distribution"?

**Comment by siegerts** [comment]
Hi :wave:, Closing until further information is provided.
