### ISSUE TITLE
Amplify Apps missing after changing username

### ISSUE THREAD

**Issue by djasuncion** [aws-amplify/amplify-console#1670]
**Describe the bug**
My apps are missing after I changed my username.

**To Reproduce**
1. change aws username
2. check amplify

**Expected behavior**
Amplify apps is empty

**Screenshots**
![aws](https://user-images.githubusercontent.com/22920210/111724131-aab37f80-889f-11eb-8556-010ce1907473.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser google chrome
 - latest

**Additional context**
I was able to see the apps when I used a link provided by my command line after doing a `amplify publish`

**Comment by VictorCcccc** [comment]
Hi @djma777 , thanks for reporting this. We are aware of this issue and will actively fix this. For the workaround, can you keep your original username?

**Comment by djma777** [comment]
> Hi @djma777 , thanks for reporting this. We are aware of this issue and will actively fix this. For the workaround, can you keep your original username?

No, I got too frustrated I delete those apps using the workaround that I mentioned and I'm just starting over. This are just starter apps anyways, so not a huge deal.

**Comment by VictorCcccc** [comment]
We link Apps by Account Id and please check if you are in the right region when you sign in using new username
