### ISSUE TITLE
Domain activation is Failed - The status of this certificate request is "Failed"

### ISSUE THREAD

**Issue by josimarz** [aws-amplify/amplify-console#1672]
**App Id**: d5jmvdc4kaave
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I got a domain activation error while creating a custom domain.

**Error message**
The status of this certificate request is "Failed". One or more domain names have failed validation due to a Certificate Authority Authentication error. Learn more: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-caa.html

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
