### ISSUE TITLE
SSL configuration is Running - Can not add custom domain in the amplify application.

### ISSUE THREAD

**Issue by HamzaAnis** [aws-amplify/amplify-console#1680]
**App Id**: d1ye3ih3r4al13
**Region**: ap-south-1
**Step**: SSL configuration
**Status**: Running

**Issue/question**
Can not add custom domain in the amplify application.

**Error message**
>Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
<img width="1123" alt="Screen Shot 2021-03-23 at 2 24 01 AM" src="https://user-images.githubusercontent.com/18266623/112060318-d88a1400-8b7e-11eb-9f81-488cc24e2a82.png">

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.
