### ISSUE TITLE
CustomHeaders.

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-console#1682]
`customHeaders:
  - pattern: '*'
    headers:
      - key: Access-Control-Allow-Origin
        value: '*'
`

This is my customHeader Setup. 
But I got under Chrome a cors error for my ttf files. 

https://www.aivy.app/develop/direct-react?partner=bei32464-06d4-4caa-900f-2812223db310

What can I do?

**Comment by siegerts** [comment]
Hi @davidbiller, thanks for raising.  Is this still an issue? I see that the files are loading in the site above although coming from a the base amplify site.

If this is still an issue, do you mind providing a bit more information about the setup of your application - type, framework, redirects, etc for more context. 

Thanks!
