### ISSUE TITLE
Suggest me what does xxxxxx.cloudfront.net in the docs mean? Is it the amplify app url or the domain name that I want?

### ISSUE THREAD

**Issue by Anwesh10o9x** [aws-amplify/amplify-console#1685]
**App Id**: dfsg0fmbpaqm8
**Region**: us-east-2
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by ganipcanot** [comment]
Could you give some more information here?  What specific documentation link are you looking at?  Are you trying to setup a custom domain?
