### ISSUE TITLE
Custom Domain SSL is not resolving

### ISSUE THREAD

**Issue by mandeepsingh-private** [aws-amplify/amplify-console#1686]
**App Id**: arn:aws:amplify:us-east-1:048020187914:apps/dp7ej7xd3vqtp
**Region**:us-east-1
**Step**: SSL
**Status**: not verified SSL Configuration
The app is stuck in verification step while configuring custom domain name

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by mandeepsingh-private** [comment]
None of the above apply. It is plainly stuck without any error.

**Comment by nimacks** [comment]
Our records indicate that your domain is now available. Re-open if you're still having issues.
