### ISSUE TITLE
Support Node.js 14

### ISSUE THREAD

**Issue by ceefour** [aws-amplify/amplify-console#1690]
**Is your feature request related to a problem? Please describe.**
Support Node.js 14

**Describe the solution you'd like**
We can use `nvm use $VERSION_NODE_14`

Since 14 is LTS I'd say it should be default anyway.

**Additional context**

@kevinadhiguna please support

**Comment by michaelbrewer** [comment]
Pretty please, alot of frameworks like GatsbyJS now requires this.

**Comment by metadiego** [comment]
+1. I am using airbnb eslint config and lint-staged, these are not compatible with Node 12, so I had to change version to Node 10 and also change lint-staged version to an earlier release.

I imagine these sort of issues will only get worse until AWS adds support for more recent node versions...so, pretty please do :)

**Comment by mnightingale** [comment]
In the [Dockerfile](https://github.com/aws-amplify/amplify-console/blob/main/images/latest/Dockerfile) VERSION_NODE_12 is defined as `12` so if you want to use 14 just add preBuild steps such as:

```yaml
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 14
```

Looking at the file you might also want a `npm install -g sm grunt-cli bower vuepress gatsby-cli` step if you need those global deps.

**Comment by clintfoster** [comment]
Not to pile on, but [Quasar](https://quasar.dev) is also incompatible with the current default Node in Amplify's build image:

```
INCOMPATIBLE NODE VERSION
    @quasar/app requires Node 12.22.1 or superior
    You are running Node v12.21.0
    Please install a compatible Node version and try again
```

Ideally the default version in the build image should be the current LTS (`14.18.1`). Next best would be to make it available via `nvm use`. But, as far as I can tell, it isn't. Thus, it must be installed in `preBuild` each time.

**Comment by swaminator** [comment]
@clintfoster @mnightingale @metadiego @ceefour we now support Node v14 in the build container by default.
