### ISSUE TITLE
Upgrade to Yarn 1.22.10

### ISSUE THREAD

**Issue by ceefour** [aws-amplify/amplify-console#1691]
**Is your feature request related to a problem? Please describe.**
Upgrade to Yarn 1.22.10

**Describe the solution you'd like**
Upgrade to Yarn 1.22.10

**Additional context**
Currently it uses Yarn 1.22.0 and the latest stable (that everyone else is using, e.g. when we do `npm -g install yarn`) is 1.22.10.

@kevinadhiguna please support

**Comment by kahdojay** [comment]
closing in favor of https://github.com/aws-amplify/amplify-console/issues/661

**Comment by kevinadhiguna** [comment]
@ceefour The update will show up in several weeks as said by @kahdojay and I will see the logs to ensure the Yarn version I am using. Thank you.
