### ISSUE TITLE
Domain activation is Failed - Subdomain DNS settings pointing to another Amplify project

### ISSUE THREAD

**Issue by agyimr** [aws-amplify/amplify-console#1696]
**App Id**: d3um28pzf6wxer
**Region**: eu-central-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**

We have an Amplify project which we connected to our root domain: example.com, and two environments are mapped to dev.example.com an our production environment which is mapped to app.example.com. So far everything works perfectly. 

I made another separate amplify project, containing separate code, that I would like to map to share.example.com. I tried every possible way to set this relation up, share.example.com never worked so far. I read the URL linked in the error message, but I don't see the Cloudfront distributions where I could set up routing to wildcards.

**Error message**

*"Domain activation is Failed".

One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Additional information**

**Comment by ganipcanot** [comment]
The Cloudfront distributions are managed in the Amplify service accounts so you wouldn't see any provisioned in your AWS account.

Are you not able to view the configuration details from app1 with is connected to `example.com` and `dev.example.com`?

Are you using Route53 or some other DNS provider?
