### ISSUE TITLE
Domain activation is Failed - Repeated failure on custom domain with Route 53 DNS

### ISSUE THREAD

**Issue by Guenther93** [aws-amplify/amplify-console#1697]
**App Id**: d2l91s6l8s81pp
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I am getting continual failures attempting to add a custom domain to my Amplify project. 4 out of the 5 succeeded (although some took multiple tries) but the last one fails. It fails if I hit the Retry button or if I delete it and start from scratch by clearing the DNS entries.

This DNS is hosted on Route 53 so the Amplify console is auto creating all the DNS entries. When I attempt to add the custom domain to Amplify I can see it adding the root A alias, the www CNAME and the-validation.aws CNAME as expected. This allows it to get past the SSL creation and SSL configuration steps but then it fails on "Domain Activation" But then it gives me the below error message.

I have attempted waiting overnight to make sure that the DNS properly clears and still this fails every time. 

This domain name was purchased only a few days ago - based on my reading I am curious if another AWS user previously owned this domain and has it registered somewhere else in CloudFront that I cannot see.

**Error message**
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Additional information**

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by Guenther93** [comment]
Yes - I am still having issues. Please actually read the ticket before giving the stock responses. This is a NEW domain, I have it properly registered in Route 53 - it has no current A or CNAME records in the way. I have not assigned it to any other Amplify Apps.

When I attempt to configure it - Amplify is able to get through the first couple steps because it can directly update the Route 53 DNS and self verify. I can see the verification CNAME being created as well as the A Alias for the @ and the CNAME for the WWW - after that it just fails with "One or more of the CNAMEs you provided are already associated with a different resource". 

The docs you pointed me to refer to looking at CloudFront Distributions which if I go to that I see...

_"Either your search returned no results, or you do not have any distributions. Click the button below to create a new CloudFront distribution."__

So clearly somewhere in AWS it thinks that I am using the domain somehow - but until a couple days ago I didn't even have the domain - I have no CloudFront distributions - and only 2 Amplify Apps and have verified that the other doesn't have this domain. So there is a remnant of something somewhere that I have no ability to remove.

Prior to attempting to enable in Amplify there isn't even a single A or CNAME record associated with that domain yet in Route 53.

**Comment by emilhovad** [comment]
I have problem with my s53 domain and amplify as well. I should simply be able to add the domain (since it should be simple to use) and it does not work.

**Comment by kahdojay** [comment]
@emilhovad the error you shared means that there is a DNS record pointing to a different CloudFront distribution at the time we attempt to create one for you. Since you own the domain and the authoritative records it likely wasn't from a previous owner/record. It may be that your first attempt failed and upon deleting the custom domain, re-attempted creation before we finished cleaning up the previous Route53 records in your account (which were pointing to the CF distro from the previous attempt). About the retry button - we have a known bug 

It looks like you've managed to get it working now, I see your domain is pointing to a wip site, let us know if that's not right.

**Comment by emilhovad** [comment]
Hallo aws
thanks for the detailed answer, it still does not work, I think i do not have other pointing to itracket.com.
i can try with itracket.eu
Emil Hovad

________________________________

**Comment by siegerts** [comment]
Hi @emilhovad , the above response is related to the original issue question.  If you're also having trouble, please [open an issue ](https://github.com/aws-amplify/amplify-console/issues/new?assignees=&labels=custom-domain&template=2.domain_issue.yaml&title=) if the information in the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html)  doesn't help.

**Comment by fenglinnorway** [comment]
my experience is that i mistakenly created another amplify app in another regsion that is associated with this domain. you need to check if you have created another amplify app in another aws region, if so, you need to delete that app. then the domain is released.

**Comment by Guenther93** [comment]
I let this sit for a little while and it is still failing. I check all the other AWS Zones on the off chance I created something in a different zone. If I look at my DNS in Route 53 - no CNAME exists for "www" or ANAME for the root. 

If I try to add in the domain - it does the SSL creation, it does the SSL Configuration - it adds in 3 entries into Route 53 (root, www and acm-validations.aws) and then fails on Domain Activation.

Which would imply that Cloudfront is misconfigured somewhere out of my control. I don't know how AWS expects us to fix the problem with such terrible feedback or some sort of "take ownership" mode.

**Comment by ferdingler** [comment]
Hi @Guenther93, apologies for the delay here. I'm currently investigating what happened to your domain name association. It appears to be related to an issue we had on March 24th in regards to deleting custom domains. I will update this ticket as soon as I have a resolution. Thanks for bringing this to our attention.

**Comment by ferdingler** [comment]
Hi @Guenther93, we were able to find the root cause and fix the issue with your domain. You will see it in FAILED state but feel free to remove it from your Amplify app and re-associate it again. You shouldn't get the CNAMEAlreadyExist error anymore. 

Thanks again for letting us know and apologies for the inconvenience.
