### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by kraastier** [aws-amplify/amplify-console#1702]
**App Id**: d1bckmmtwjq6n8
**Region**: ap-south-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by der4eichi** [comment]
I think its a duplicate from #1712 ?

**Comment by siegerts** [comment]
Hi @kraastier, were you able to get this resolved?

If not, be sure to check the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html) and [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md) to see if that helps.
