### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by JimBrocato** [aws-amplify/amplify-console#1703]
**App Id**: d2vv85dompacun
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am trying to add a custom domain managed by SquareSpace to my Amplify site.  I think it is stuck trying to verify the domain because it took me too long to add the DNS records in SquareSpace.

**Error message**
No error message.  It's just hung on pending SSL configuration.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by JimBrocato** [comment]
This is resolvec

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by medelman17** [comment]
Reopening. I am encountering the same issue. Nothing I have done (messing around in Route53, etc) has been able to resolve issue, which appears to have just arisen for no reason. 

<img width="956" alt="Screen Shot 2021-04-01 at 9 45 41 PM" src="https://user-images.githubusercontent.com/14793389/113376167-120d0d00-933f-11eb-9f6b-641083919379.png">
<img width="867" alt="Screen Shot 2021-04-01 at 11 06 58 PM" src="https://user-images.githubusercontent.com/14793389/113376161-0faab300-933f-11eb-9078-b91eaa6deec3.png">
<img width="922" alt="Screen Shot 2021-04-01 at 9 45 51 PM" src="https://user-images.githubusercontent.com/14793389/113376163-11747680-933f-11eb-8b66-938bb9419f95.png">

**Comment by siegerts** [comment]
Closing for now since this specific issue was resolved.

@medelman17 If this is still persisting on your side, then I'd go ahead and open a new issue with your app specific info.
