### ISSUE TITLE
Issue with Access control in AWS Amplify

### ISSUE THREAD

**Issue by tranthang212** [aws-amplify/amplify-console#171]
**To Reproduce**
1. Go to Amplify Console
2. Click on Access control
3. Click button Manage access
5. Disable "Apply a global password - OFF"
6. Save

After performing the above steps, the password is still required to access the website
How to clear it?
I do not use any cache tool.
Does anyone have a problem like me?

**Comment by visusnet** [comment]
We are experiencing the same issue with branch-specific passwords. We have disabled them in the Amplify Console but users are asked regardlessly.

**Comment by visusnet** [comment]
@swaminator Is this something you could help with? Our production system is not usable at the moment which is ... a bummer...

**Comment by shiruba** [comment]
Just tried it - confirmed. When I add password protection to a branch and remove it after that, the domain still asks for a username/password via htaccess.

**Comment by dabit3** [comment]
@shiruba @visusnet @tranthang212 Thanks for the info and for reporting this issue. We're looking into it as we speak.

**Comment by 0luftballoons** [comment]
I have the same problems. Existing login branches can't be changed, either by changing username + password or changing to publicly-accessible. New deployment branches are stuck with public access, can't configure for username + password

**Comment by swaminator** [comment]
@0luftballoons @shiruba @visusnet @tranthang212  we are rolling out a fix shortly. I'll update this thread when it's ready.

**Comment by swaminator** [comment]
@0luftballoons @shiruba @visusnet @tranthang212 the fix is rolled out. Please try updating the access control settings once more and let me know if it works.

**Comment by 0luftballoons** [comment]
I think it mostly works. Took existing deployed branch (public access), and did the following access changes
public --> login required (ok) --> public (ok) --> login (nope, still public) --> change username, pw (get login, but can't login, maybe user error?) --> change username, pw (ok)

**Comment by 0luftballoons** [comment]
I'd like to see what happens when deploying a new branch and then changing access to require login before the branch deploys, but I'm just about to start a real software release and don't want to cause any problems :)

**Comment by tranthang212** [comment]
@swaminator It worked. Thanks for the update.

**Comment by kieran9176** [comment]
Seems like this issue is back and I haven't yet been able to resolve it. @swaminator @dabit3 is this something you could help with?

Steps to recreate
1. create develop and master branches
2. apply global username/password
3. remove global username/password 
4. apply develop branch-specific username/password
5. apply master branch-specific username/password
6. remove master branch-specific username/password

This is with a custom domain, master points to the root and develop points to develop.root.com.

The result is as if steps 3-6 had not been completed. The master branch still has a password and it's the global username/password combo that was created in step 2. Removing passwords from both branches doesn't work, neither does a redeploy of the whole app. 

Any tips to get the master branch working in the short term? Or will I need to create a new branch and redirect my custom root domain to that?

**Comment by abhi7cr** [comment]
Hi @kieran9176,

Thanks for reporting. I will take a look and get back to you.

**Comment by BenSaus** [comment]
Any progress on this issue or work arounds? I have a site that needs to go into production soon and this could be a problem.

**Comment by mansiva** [comment]
Hello, we're facing the same issue.

I added access control individually per branch but password wasn't being asked for everyone, maybe due to caching. So I removed access control from all branches but password it still being asked a few hours after the change was made, does anyone know if there's a delay or something? I've tried clearing the local cache and using a different device in incognito but password is still being asked.

**Comment by mansiva** [comment]
In case anyone else has the issue I was able to resolve by setting a new password for the branches that had issues, waiting a bit (not sure if that's necessary) and then removing the password.

**Comment by Espen-Ellevseth** [comment]
I also have this problem. I've been trying to remove the Access Control by removing password in the Amplify Console. The password box still appears, however the password will no longer work. I've tried from a clean browser, same result.

Is there a timeline for fixing this problem?

**Comment by swaminator** [comment]
@Espen-Ellevseth @mansiva @BenSaus we are going to invesitgate this ASAP.

**Comment by alanpilloud** [comment]
I experienced the same issue today, this solved the issue for me :

1. clic "manage access"
2. restrict again the branch that has the issue
3. clear username and passwords fields
4. set again the branch to be publicly viewable then save

**Comment by Espen-Ellevseth** [comment]
I also managed to remove the password using @alanpilloud's procedure with the difference that my password was global.

What I did:

1. Turn off the global password
2. Set a branched password and save.
3. Remove the branched password using the procedure (Removing the text in username/password and setting public).

**Comment by abhi7cr** [comment]
@Espen-Ellevseth @mansiva  @BenSaus @alanpilloud , we rolled out a fix recently for the above issue. Could you verify if it works on your end?

**Comment by alanpilloud** [comment]
@abhi7cr sorry for responding this late. I did not experienced this issue since then. Thanks a lot !

**Comment by mawhtin** [comment]
Annnnd it's back. Can we address this again? Our production site was to go live tomorrow but our testers are being pass-walled. @abhi7cr @swaminator 

I've tried applying the branch specific PW then turning it off. No luck.

**Comment by vladimirsm** [comment]
@abhi7cr we are having the same issue as @mawhtin. 
No luck with reapplying the passwords and removing them.

**Comment by abraly** [comment]
Any movement here?

**Comment by kirkmin-clearmarket** [comment]
This is still an issue for us in 2022.
Despite the console stating that it's publicly viewable, the login prompt is still showing up
![image](https://user-images.githubusercontent.com/77646458/152047358-d91fd133-26bc-4df2-ac74-3d1effa50a3b.png)

**Comment by leonardof131** [comment]
I'm facing this exact issue on my amplify web app. Is this bug back ?

**Comment by brunoksato** [comment]
I have same issue today!

**Comment by ivadenis** [comment]
I experience this issue too!

**Comment by alexbahnean** [comment]
I have the same issue ..

**Comment by dewflowersp** [comment]
I have the same issue... facing too much trouble...

**Comment by alexbahnean** [comment]
I manager to fix The issue some how 

I disabled the authentication from console (turn off global password and making sure that I game no password for the branch)

Then I made one new dummy commit
I pushed my code
And then I waited until the build was done on amplify console
Checked the website and the password was not there anymore

somehow this steps helped me bypass the issue

**Comment by gagharutyunyan1993** [comment]
Rebuild your branch after changing Access control, it will fix the issue.

**Comment by hloriana** [comment]
If you are running into this issue with an SSR Amplify app, please redeploy your application. This is necessary so that Amplify can apply the access control settings. Please refer to step 6 in the documentation: https://docs.aws.amazon.com/amplify/latest/userguide/access-control.html
