### ISSUE TITLE
SSL not working when leaving 'www' out of the domain

### ISSUE THREAD

**Issue by Gui-JVale** [aws-amplify/amplify-console#1712]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dm5g332ltk8gl

### Region

us-east-2

### Step

Domain Activation

### Status

The required CNAME records are not yet configured for the below subdomains. Click "Actions > View DNS Records" and configure the required CNAME records with your DNS provider:

### Issue or question

I have already changed DNS, it's all working fine, except the following:

My app domain is: https://www.thetri.app
However if I go to https://thetri.app it gives an SSL error (not secure).
It should work fine for both addresses, I already read troubleshoots guides, and talked to domain provider support. This has to be fixed in the AWS end.

### Error message

Error code(Firefox): SSL_ERROR_BAD_CERT_DOMAIN

**Comment by siegerts** [comment]
Hi @Gui-JVale, sorry that you are running into this.  

Did you initially have the redirect set up from `https://<your-domain>.com` to `https://www.<your-domain>`.com when you added the domain?

This can be set in **App Settings** -> **Domain Management**:

![image](https://user-images.githubusercontent.com/634958/113433579-7797e280-93ad-11eb-8e31-fe8590373fdb.png)

And then after adding :
![image](https://user-images.githubusercontent.com/634958/113435253-6dc3ae80-93b0-11eb-9624-186a17d1941b.png)

**Comment by Gui-JVale** [comment]
Yes, that's how I setup in the beginning. It looks the same as the screenshot you sent. What else should I do?

**Comment by siegerts** [comment]
Do the rewrites also match this logic (for the redirect)?

**App Settings** -> **Rewrites and redirects**
![image](https://user-images.githubusercontent.com/634958/113597462-c04bd780-9609-11eb-8291-f1947c530412.png)

**Comment by Gui-JVale** [comment]
Almost the same except it's a 302(temporary redirect) instead of a 301. Do you think that's the issue? Thanks

**Comment by siegerts** [comment]
When I view the cert for your domain above, it looks like the cert is valid.  When I view the TLD (without `www.`), it looks like the cert is coming from another provider (possibly from the provider?) 

If this isn't familiar, have you tried removing and re-adding the custom domain as mentioned here? - https://github.com/aws-amplify/amplify-console/issues/66#issuecomment-525009758

If the domain is being migrated, possibly validating your previous steps to set up against - https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md#how-do-i-migrate-domains-to-amplify-with-minimal-downtime.

**Comment by Gui-JVale** [comment]
ok I redid the domain, but as happened before, it gets stuck on this last step. I configured the CNAME, is there any more configuration that I should do? 
![Screen Shot 2021-04-08 at 11 50 55 AM](https://user-images.githubusercontent.com/54419613/114080944-cf789280-9860-11eb-9b3f-43b991f2adfa.png)

**Comment by Gui-JVale** [comment]
Please I really need to get this fixed!

**Comment by Gui-JVale** [comment]
@siegerts any updates?

**Comment by siegerts** [comment]
Hi @Gui-JVale , apologies for the delay. It looks like your DNS records for the bare domain (`thetri.app`) doesn't point to the Amplify app whereas the DNS for `*.thetri.app` does point to the app.

This may be related to how the DNS is configured. Can you confirm that you've configured DNS settings as outlined in the DNS record section?

![image](https://user-images.githubusercontent.com/634958/114925542-3e279400-9dfd-11eb-9b64-2b4f2d78d8d9.png)

**Comment by Gui-JVale** [comment]
@siegerts talked to go daddy, they told me to update my A record with the IP address of the app. But they told me I have to buy an SSL for the domain without the 'www', that's not the case since AWS provides one right?

Also I couldn't find the app's IP address nowhere, how do I get that info?

**Comment by siegerts** [comment]
If you're using GoDaddy, then follow these steps below. It outlines the process for linking everything up using the DNS records provided to you in the Amplify console for the app.

https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-godaddy.html

**Comment by Gui-JVale** [comment]
@siegerts Those were the steps I followed twice and didn't solve the problem. They told me I just need the IP address and once I configure the A record on Godaddys end it will work.

 Can you please instruct me on how to get the app's IP address?

Thank you very much!

**Comment by Gui-JVale** [comment]
@siegerts any updates?

**Comment by Gui-JVale** [comment]
@siegerts Could you please instruct me on how to get the IP address of the app, so that I can setup the A record on GoDaddy and fix this??

**Comment by Gui-JVale** [comment]
@siegerts updates?

**Comment by siegerts** [comment]
Hi @Gui-JVale, have you tried making Amazon Route 53 the DNS service for the existing domain? 

That is the recommended approach since GoDaddy doesn’t support ANAME/ALIAS records. For these providers, we strongly recommend migrating your DNS to Amazon Route 53 to account for this (below) or possibly transferring to another host that does allow for this. Given the current limitations that you've run in to, I think that it makes sense to investigate a migration to Route 53 or other.

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/MigratingDNS.html. 

There isn't a single dedicated IP for your app that you can point to since it is a Cloudfront distribution and is a globally distributed by nature (i.e. requests are routed via DNS based on location of access and the IPs may always be changing, etc.).
