### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by jmhen** [aws-amplify/amplify-console#1713]
**App Id**: dsa40otdropqh
**Region**: ap-southeast-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
All retry attempts failed at domain activation stage

**Error message**
One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem.

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
The DNS tracker showed me all our CNAME records points to the one distribution indicated under action > DNS records. I dont understand why is there a need to update DNS record.

**Comment by der4eichi** [comment]
I think its a duplicate from #1712 ?

**Comment by siegerts** [comment]
Hi @jmhen, is this still an issue?

If  so, be sure to check the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html), specifically [CNAMEAlreadyExists ](https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/)to see if that helps.
