### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by kiruthikcs** [aws-amplify/amplify-console#1717]
**App Id**: d34c9drqerklwf
**Region**: ap-south-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
even after clearing other CNAMEs, the same issue & error.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
![image](https://user-images.githubusercontent.com/29199000/113240017-78efdf00-92c9-11eb-854f-666c073d9179.png)

**Comment by siegerts** [comment]
Hi @kiruthikcs, thanks for raising. Are you still having this issue? 

If so, does the information on the [CNAMEAlreadyExistsException FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md#cnamealreadyexistsexception) help at all? 

Thanks!
