### ISSUE TITLE
Manually rebuild project

### ISSUE THREAD

**Issue by PieceOfWire** [aws-amplify/amplify-console#1723]
** Please describe which feature you have a question about? **
I changed the output directory in my build settings and amplify did not build my project again. Maybe I am blind but I can't see the option to manually re-build my project anywhere. Am I forced to commit and push something for the build to happen again?

**Comment by siegerts** [comment]
Hi @PieceOfWire, thanks for raising. Apologies if this is slowing you down. 

Yes, currently, you can trigger a redeploy by adding  and pushing a commit. There is an open feature request for this @ https://github.com/aws-amplify/amplify-console/issues/599.

**Comment by siegerts** [comment]
Also, depending on the changes. You can use the `Redeploy this version button`:

- Make build setting changes
- Click on the build pipeline icon
- Click redeploy this version

![image](https://user-images.githubusercontent.com/634958/113740173-7842b880-96ce-11eb-8de3-95d7b0dd2cd4.png)
