### ISSUE TITLE
No builds. Your build is being queued. If your build has not started in over a minute, click the button below.

### ISSUE THREAD

**Issue by Sureshkumar251997** [aws-amplify/amplify-console#1724]
### Before opening, please confirm:

I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

After Clicking Save and Deploy. Build got stucked.
I already checked this in the issue. They are mentioned , this is because of permission issue,
But where i need to change the permission, I got stuck with this.
Let me know how to solve this. 

### Expected behavior

it needs to setup the four step process
provision , Build , Deploy and Verify

### Reproduction steps

1. Host new app
2.Select Bit Bucket
3.Save and Deploy
I got the error

**Comment by siegerts** [comment]
Hi @Sureshkumar251997, thanks for raising.

> I already checked this in the issue. They are mentioned , this is because of permission issue,
But where i need to change the permission, I got stuck with this.

Can you link the issue here that describes your issue? Also, if there are any specific log messages, please copy here (be sure to remove sensitive information).

Thanks!

**Comment by Sureshkumar251997** [comment]
> Hi @Sureshkumar251997, thanks for raising.
> 
> > I already checked this in the issue. They are mentioned , this is because of permission issue,
> > But where i need to change the permission, I got stuck with this.
> 
> Can you link the issue here that describes your issue? Also, if there are any specific log messages, please copy here (be sure to remove sensitive information).
> 
> Thanks!

**Comment by Sureshkumar251997** [comment]
> > Hi @Sureshkumar251997, thanks for raising.
> > > I already checked this in the issue. They are mentioned , this is because of permission issue,
> > > But where i need to change the permission, I got stuck with this.
> > 
> > 
> > Can you link the issue here that describes your issue? Also, if there are any specific log messages, please copy here (be sure to remove sensitive information).
> > Thanks!
### ### 

>This is my APP ID : dt929pepd0nfi.
I am using Bit Bucket.
Step: 1 
I selected bitbucket with repo and branch
Step: 2 
Confirm build settings for the front end
Step : 3 
When I click save and deploy , It got stucked
No builds. 
Your build is being queued. If your build has not started in over a minute, click the button below.

**Expected behavior**
it needs to setup the four step process
provision , Build , Deploy and Verify 
It is not happening.
This issue is not solved 

Thanks .
