### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by NickGibbssoftio** [aws-amplify/amplify-console#1725]
**App Id**: d39uypep1uivto
**Region**: eu-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by NickGibbssoftio** [comment]
I was trying to migrate to a new domain but it failed the new domain creation process. Now I am unable to delete the new domain to try again.

**Comment by siegerts** [comment]
HI @NickGibbssoftio, sorry to hear.  Have you had any success since?  Also, if there are any screen shots, messages, etc after you try to delete, that'd be helpful to see.  I'd also recommend hard refreshing the browser too :) Sometimes, that helps.

**Comment by NickGibbssoftio** [comment]
Thanks for your response. It turned out to be a permissions issue. Unfortunately the error didnt suggest this but looks to be working now. Thanks
