### ISSUE TITLE
Provide build and deploy status to GitHub pull requests

### ISSUE THREAD

**Issue by nikovirtala** [aws-amplify/amplify-console#173]
**Is your feature request related to a problem? Please describe.**

Currently I cannot check the status of a build or deploy status from the version control system, in our case GitHub. This has become even bigger distraction after feature branch deployments enablement.

**Describe the solution you'd like**

AWS Amplify Console should feed in minimum the build and deploy status, with links to detailed content (e.g. link to the deployment or error log) back to the GitHub pull request, if the job is triggered from one. 

This will enable teams and developers to build their workflows around the pull request and get a full picture of the project state from one tool.

**Additional context**

+ https://help.github.com/en/articles/about-status-checks
+ https://developer.github.com/v3/repos/statuses/

![image](https://user-images.githubusercontent.com/6813506/65938376-7b9b1b00-e42b-11e9-8ee5-5497f1f6bdfc.png)

**Comment by simpson** [comment]
This would be great! We could replace Netlify for our test builds and just use Amplify

**Comment by simpson** [comment]
The new previews feature is working awesome! Thank you @swaminator!!! We no longer need Netlify and can run all of our CI/CD through Amplify

**Comment by swaminator** [comment]
@nikovirtala has your usecase been addressed?

**Comment by nikovirtala** [comment]
> @nikovirtala has your usecase been addressed?

Yes, thank you!

Leaving some bread crumbs for further searches:

Amplify Console’s Pull Request Preview: https://aws.amazon.com/blogs/aws/improve-your-app-testing-with-amplify-consoles-pull-requests-previews-and-cypress-testing/
