### ISSUE TITLE
Site Cant Be Reached when using Subdomain

### ISSUE THREAD

**Issue by Townsheriff** [aws-amplify/amplify-console#1735]
### Before opening, please confirm:

I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dc4pva0vvcs9h

### Region

eu-central-1

### Step

Opening website

### Status

Pagenotfound

### Issue or question

Hi,

I've yesterday added a subdomain to my Amplify application through "Domain Management". At first it worked fine, but later on sometimes it would not load and eventually I would "server IP address could not be found".  In route53 and in DNS lookup I see the cloudfront CNAME entries.

I tried removing, adding back domain name and pushing changes to repo to trigger rebuild. Did not help. Eventually I created another subdomain which also at first worked fine, but then "server IP address could not be found".

Some notes on my setup. I have lightsail aws service which is using root domain name and I also had another amplify app (not used)  same root domain, but not with subdomain. I removed the amplify app domain settings which has been using this domain.

One of the CNAME that did not resolve website -d2165ossa3y875.cloudfront.net

And now while I'm writing this ticket it started working again, my guess it will not work for long.

### Error message

There is no error message, only that page is not resolved in browser with "server IP address could not be found".

**Comment by Jarodwr** [comment]
I'm experiencing the same issue, I've repeated the process multiple times.

**Comment by ferdingler** [comment]
Hi @Townsheriff, sorry to hear that you experienced issues with Amplify custom domains. 

> Some notes on my setup. I have lightsail aws service which is using root domain name and I also had another amplify app (not used) same root domain, but not with subdomain. I removed the amplify app domain settings which has been using this domain.

I'm a little confused with your setup because you mention you have the same root domain used twice, in Amplify and Lightsail? I was trying to lookup your domain based on the AppId you provided `dc4pva0vvcs9h` but it doesn't seem to have any domains attached to it. 

If you are still looking to set it up, I'm happy to provide assistance. I will just need clarification on what does your current setup looks like and what would you like to achieve. If you can provide this information it would be very helpful. Thanks.

**Comment by medelman17** [comment]
I wonder if an additional hosted zone for the subdomain and an explicit delegation record in the root zone would fix? This tends to solve a lot of consternation for me when it comes to this sort of thing. CNAMEs are fickle. :-)
