### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Kanakala** [aws-amplify/amplify-console#1739]
**App Id**: d2xcrpry4q858a
**Region**: eu-central-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
We were having an AWS account for one of our environments and we deployed our webApp in it through AWS Amplify. For some internal reasons, we had to suspend that old account, delete all the resources priorly & created a new WebApp in a freshly created AWS Account. Although we've deleted all the resources from the old account, we're getting the below error when configuring the domain on the WebApp in Amplify. Can someone please look into the issue and help us through it.

Thanks,
Sumanth.

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
<img width="1073" alt="Screenshot 2021-04-12 at 8 23 23 PM" src="https://user-images.githubusercontent.com/24492030/114415032-f4f0fd80-9bcc-11eb-88e7-c6fa70163733.png">

**Comment by Kanakala** [comment]
I waited for 6 hours as it mentioned in here -> [I get a CNAMEAlreadyExistsException error
](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error). Actually, i remember deleting the amplify in the old account and then suspended it few days ago. But still, I couldn't able to add my domain.

### I can see the below error now
Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

Got stuck this from yesterday and we want to get it resolved. I really would appreciate if you guys help me in this. @siegerts 

Thanks,
Sumanth.

**Comment by ferdingler** [comment]
Hi @Kanakala, looks like you manage to setup your domain successfully for the appId `d2xcrpry4q858a`. 

In this case, you got that error because your domain name had a DNS record (CNAME) that was pointing to another CloudFront distribution. You mention you deleted the Amplify app before closing the AWS account but perhaps you didn't cleanup the DNS records on your domain so it still had one pointing to the old CloudFront distribution. 

But I'm glad to see this is resolved. Let us know if you need any further assistance.
