### ISSUE TITLE
Private GitHub repository to the amplify project

### ISSUE THREAD

**Issue by hugoebarboza** [aws-amplify/amplify-console#1741]
Hello,

I would like to configure your private GitHub repository to the amplify project, how can I do this ?

Thanks in advance.
Hugo Barboza

>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

**Comment by hugoebarboza** [comment]
Hello @siegerts  thanks for your response. I already set a public GitHub repo, but how can I reset this setting to add a private ? or how can I have both, public and private ?

**Comment by siegerts** [comment]
Yes, you'll need to reconnect the repo which can be done in **App settings** -> **General settings** -> **Reconnect repository** 

![image](https://user-images.githubusercontent.com/634958/114587394-9f136880-9c53-11eb-91aa-78aab4758d99.png)


From here, you can connect a private or public repo.

**Comment by hugoebarboza** [comment]
Hello @siegerts thanks for your response. I don't see any option to reconnect o reset my Github credentials. The reconnect option only allows me to change my public/repo or public/repo/branch. How can I reset o change my Github credentials in AWS Amplify?

**Comment by siegerts** [comment]
Hi @hugoebarboza, currently it's not possible to disconnect and reauthenticate with another GitHub account. There is an open feature request to allow for this type of scenario - https://github.com/aws-amplify/amplify-console/issues/735. 

Please upvote and add any specific experiences/expectations to that request so that it's all located in one place.

Apologies for the inconvenience here.
