### ISSUE TITLE
Production website suddenly 404's with “x-cache: Error from cloudfront”

### ISSUE THREAD

**Issue by adam-discover** [aws-amplify/amplify-console#1745]
### Before opening, please confirm:

I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

Suddenly after gaining traction on my website, amplify website is no longer available from my custom domain and 404 spikes in the monitoring logs.

Production site: https://discovercoolshit.com/
Amplify site: https://master.dlbltkz9nkkdx.amplifyapp.com/

The site is reachable on the amplify provided url and all deployment is successful as expected, however none of the custom domain links work all of a sudden. There is a 404 "x-cache: Error from cloudfront" response and I cannot manually invalidate it.

I have tried re-deploying a new master commit and also looked around in the cloudfront console but there is no amplify app there.

### Expected behavior

Cloudfront should be working exactly as the amplify url and not be caching a 404 blank screen.

### Reproduction steps

Visit the two sites separately:

Production site: https://discovercoolshit.com/
Amplify site: https://master.dlbltkz9nkkdx.amplifyapp.com/

**Comment by adam-discover** [comment]
This is a similar issue to https://github.com/aws-amplify/amplify-console/issues/1130

**Comment by mxbi** [comment]
+1 Seeing this across multiple production sites. All requests from all regions receiving 404

**Comment by adam-discover** [comment]
I hope we can get some responses here asap, this is a major issue right now and costing me a lot of users

**Comment by mxbi** [comment]
We're starting to migrate our sites off of AWS since there's no indication of this problem being investigated, hopefully we'll get an update soon.

**Comment by swaminator** [comment]
@mxbi we're looking into this now

**Comment by swaminator** [comment]
@mxbi @adam-discover can you share your appids please?

**Comment by mxbi** [comment]
@swaminator One affected app for us is 
`arn:aws:amplify:eu-west-2:735131531275:apps/dhcqqfxku673r`

And then another one from a _different_ account:
`arn:aws:amplify:eu-west-2:894661647532:apps/d2da68rhta8m7o`

**Comment by adam-discover** [comment]
@swaminator 
`arn:aws:amplify:eu-west-2:694173258393:apps/dlbltkz9nkkdx`

**Comment by nimacks** [comment]
We're actively investigating this issue. @mxbi @adam-discover

**Comment by khushkaranbajwa** [comment]
Also having the same issue arn:aws:amplify:eu-west-2:915535109082:apps/dknjyrfl0iujx

**Comment by ganipcanot** [comment]
> ### Before opening, please confirm:
> I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
> I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
> I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
> I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
> 
> ### Describe the bug
> Suddenly after gaining traction on my website, amplify website is no longer available from my custom domain and 404 spikes in the monitoring logs.
> 
> Production site: https://discovercoolshit.com/
> Amplify site: https://master.dlbltkz9nkkdx.amplifyapp.com/
> 
> The site is reachable on the amplify provided url and all deployment is successful as expected, however none of the custom domain links work all of a sudden. There is a 404 "x-cache: Error from cloudfront" response and I cannot manually invalidate it.
> 
> I have tried re-deploying a new master commit and also looked around in the cloudfront console but there is no amplify app there.
> 
> ### Expected behavior
> Cloudfront should be working exactly as the amplify url and not be caching a 404 blank screen.
> 
> ### Reproduction steps
> Visit the two sites separately:
> 
> Production site: https://discovercoolshit.com/
> Amplify site: https://master.dlbltkz9nkkdx.amplifyapp.com/
> 
> ### Build Settings
> _No response_
> 
> ### Additional information
> _No response_

This one should be back up again please check on your end.

**Comment by adam-discover** [comment]
@ganipcanot confirmed working on my end thank you, what were the issues? Anything I can manually do to recover from this problem again in the future? etc.

**Comment by khushkaranbajwa** [comment]
@ganipcanot - any idea when the rest will begin coming back online?

**Comment by ganipcanot** [comment]
> dhcqqfxku673r

Please check your respective sites they should be back up now.

**Comment by ganipcanot** [comment]
> @swaminator One affected app for us is
> `arn:aws:amplify:eu-west-2:735131531275:apps/dhcqqfxku673r`
> 
> And then another one from a _different_ account:
> `arn:aws:amplify:eu-west-2:894661647532:apps/d2da68rhta8m7o`

Please check your respective apps above they should be back up now.

**Comment by ganipcanot** [comment]
> dknjyrfl0iujx

**Comment by ganipcanot** [comment]
> I'm also having the same issue for `arn:aws:amplify:eu-west-2:915535109082:apps/dknjyrfl0iujx` :/

Please check now.

**Comment by khushkaranbajwa** [comment]
Thanks all working now. What was the root cause?

**Comment by michaelr-pa** [comment]
Hi all, we are having similar issues with - arn:aws:amplify:eu-west-2:993648739978:apps/d9dpmzn9szqwe
we have tried removing and re-adding the custom domain, but it may be stuck on SSL configuration, is there anything that can be done?

**Comment by mxbi** [comment]
> Please check your respective apps above they should be back up now.

Thanks, our sites appear to be back up now. It would be good to get some indication what the root cause/fix was, it looks like this isn't the first time this issue has happened (#1130).

Is there anything we can do on our ends to fix if it happens again?

**Comment by cameron-robey** [comment]
Hi, I was also affected, but all my sites seem to be up now again. Do you have any information about the root cause of this? 

Is there anything I can do to make sure it doesn't happen again, I had to migrate a couple of sites to a different platform yesterday as they were in production so couldn't afford the downtime.

**Comment by swaminator** [comment]
@cameron-robey @mxbi @michaelr-pa @khushkaranbajwa we sincerely apologize for the downtime. Some feature code we released caused a regression that was uncaught with our integration tests. We are taking this issue extremely seriously and have paused all work on the team with everyone focused solely on improving test coverage for a variety of scenarios around custom domains.

**Comment by RunoFawkes** [comment]
Hello, I'm having this issue since today (detected 05/01/2021 08:00 PM GMT-3) on `arn:aws:amplify:us-east-1:781297274255:apps/d1bb4ivo76onoa`

Can I get some assistance on this? I had minor deployments yesterday but they were all successfull, and everything was working.
Should I open a new issue? I didn't want to clutter since there seems to be multiple people having this, but I seriously need to get this up again ASAP.

Both of my branches are down, none of the below addresses work for me right now:

MAIN
https://app.potencia40.com.br
https://main.d1bb4ivo76onoa.amplifyapp.com

STAGING
https://app.potencia40.com.br
https://staging.d1bb4ivo76onoa.amplifyapp.com

The response I get on `/` is:

```
content-length: 0
date: Sun, 02 May 2021 00:11:50 GMT
server: AmazonS3
via: 1.1 ef0351f6e6a938444811465f38f5ed86.cloudfront.net (CloudFront)
x-amz-cf-id: GdCj4xdXGhueZt5bIGS88PTrQtpAdTlgrPQRa6C1zgdrbZBMYeWQ4Q==
x-amz-cf-pop: GIG51-C2
x-cache: Error from cloudfront
X-DNS-Prefetch-Control: off
```

I've tried redeploying and updating some of my rewrites/redirects, but it doesn't seem to do much. I need some of these redirects for functionality. 

Any help is appreciated
