### ISSUE TITLE
AWS amplify + Slack

### ISSUE THREAD

**Issue by ramimohammad** [aws-amplify/amplify-console#1747]
Hi Support team,

AWS amplify doesn't send notification to slack ,

my setup like this :  Amplify > SNS topic subscribed by AWS chatbot linked with a slack channel.
but unfortunately doesn't work.

Is there any straight forward steps could help or clear aws docs. Thanks a lot.

**Comment by swaminator** [comment]
@ramimohammad we do not have a clean integration just yet. If you enable Email notifications in the Amp console we actually create an SNS topic for you which you can then configure to connect to Slack: https://medium.com/cohealo-engineering/how-set-up-a-slack-channel-to-be-an-aws-sns-subscriber-63b4d57ad3ea. Deeper chatbot integration is tracked here: https://github.com/aws-amplify/amplify-console/issues/271
