### ISSUE TITLE
Domain activation is Failed - CNAMEs already associated with a difference resource

### ISSUE THREAD

**Issue by mahdikhaliki** [aws-amplify/amplify-console#1749]
**App Id**: d1dxez8p8p92lo
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
A clear and concise description of what the issue/question is.
I am trying to add a custom domain to my Amplify app, however, it keeps failing on the Domain activation step. I've deleted all the CNAMEs from Route 53 but it still fails. When I try to access the app with my domain I can see the page but it only contains HTML code. 

I've already tried the [Troubleshooting custom domains](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html) guide.

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**

<img width="1334" alt="Screen Shot 2021-04-15 at 8 14 01 PM" src="https://user-images.githubusercontent.com/54607305/114966773-1c8fd200-9e28-11eb-991d-80dccd8a9f61.png">

**Comment by ferdingler** [comment]
Hello @mahdikhaliki, I see on our end that you manage to setup your domain successfully which I'm glad to see. Feel free to re-open this ticket if you have any additional questions.
