### ISSUE TITLE
Access control in AWS Amplify does not work

### ISSUE THREAD

**Issue by rfallasch** [aws-amplify/amplify-console#175]
It is not possible to remove the password right now. I removed it via amplify console but it is still required to access the site.

A global password overwrites the required password. But changing it for only the affected Domain does not change the required password.

Amplify Console -> Access control -> Manage access -> Disable "Apply a global password - OFF" -> Save

Is there some kind of cache which still has the old value saved?

**Comment by swaminator** [comment]
#171

**Comment by swaminator** [comment]
Closing this issue as a  duplicate of #171. Please follow there for updates.
