### ISSUE TITLE
Amplify web app is absolutely broken

### ISSUE THREAD

**Issue by astef-trilogy** [aws-amplify/amplify-console#1754]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

Application page is broken:

- requests do not stop even after 1 minute
- tons of errors in console
- some forms behave strange, they clear the text, which was entered

That's what happens after navigating to the application page, and dosn't stop (the whole history is after single web page visit)
![image](https://user-images.githubusercontent.com/73665312/115120255-40cce980-9fb5-11eb-9933-7edbb6aa9eae.png)

### Expected behavior

It should work

### Reproduction steps

1. Navigate to application page

**Comment by Karmavil** [comment]
@astef-trilogy 
Maybe "amplify is broken" but make sure you are not gonna be broken 🤑
I've just got an alert about usage of my bucket.. no logs, no subscriptions floating in the ether..  I don't have clue about what's going on but until I figure it out I closed/delete everything. 
It couldn't have happened at a worse timing

**Comment by ganipcanot** [comment]
Closing due to age - please reopen if still having issues.
