### ISSUE TITLE
AWS Amplify connect to specific project 

### ISSUE THREAD

**Issue by MustafaHasria** [aws-amplify/amplify-console#1758]
after i execute "amplify init" they tell to enter name of project and after that should i set configuration 
but i built one before how can i connect my Flutter app to specific project in AWS Amplify

**Comment by siegerts** [comment]
Hi @MustafaHasria, thanks for asking.  The the command that you'll want to look at is `amplify pull`.

https://docs.amplify.aws/cli/start/workflows#amplify-pull

Hope that this helps.
