### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by jamarks** [aws-amplify/amplify-console#1767]
**App Id**: d2f9yk7hmhri5c
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by jamarks** [comment]
This domain was already a hosted zone in route 53, pointing to an elastic beanstalk in an ec2.

**Comment by nimacks** [comment]
Our records indicate that your app has been deleted. Re-open if you're still having issues.
