### ISSUE TITLE
Amplify default domain 404 error

### ISSUE THREAD

**Issue by marco910** [aws-amplify/amplify-console#1770]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

When opening the Amplify app's default domain `main.XXX.amplifyapp.com` in the browser I'm getting a 404 error.

### Expected behavior

The domain should show the app deployed with Amplify.

### Reproduction steps

1. Deploy an Next.js SSR app with Amplify Console
2. Try to access the app in the browser with the default Amplify domain `main.XXX.amplifyapp.com`

### Additional information

- When trying to access the domain before the first build is published, it works and the default page is shown.
- My App is based on Next.js with Incremental Site Generation
- In the build output are no errors or warnings, that could cause the problem.
- The problem even happens when no custom domain attached.

**Comment by siegerts** [comment]
Hi @marco910, SSR for hosting on Amplify is currently not supported yet.  It's listed as a feature request -https://github.com/aws-amplify/amplify-console/issues/412.  Please upvote and follow along there.

You can include elements of Amplify JavaScript in your SSR application but the _hosting_ of the application is not yet supported through the Console.

https://aws.amazon.com/blogs/mobile/ssr-support-for-aws-amplify-javascript-libraries/

**Comment by marco910** [comment]
Hi @siegerts ,
the problem that caused the 404 error was the config of the URL rewrites and redirects. After testing around I found a solution that works.
But thanks for the info that SSR is currently not supported.

**Comment by ssousa33** [comment]
@marco910 , what was the solution that worked? currently pulling my hair out on this one

**Comment by marco910** [comment]
@ssousa33 , I also tried around for a few hours until I found a solution. My app is pretty simple and only has one dynamic route called `/report/[slug]`. So came to the following redirect/rewrite rules:

```
[
    {
        "source": "/report/<slug>/",
        "target": "/report/<slug>",
        "status": "200",
        "condition": null
    },
    {
        "source": "/report/<slug>",
        "target": "/report/<slug>.html",
        "status": "200",
        "condition": null
    },
    {
        "source": "/report/<*>",
        "target": "/",
        "status": "404",
        "condition": null
    },
    {
        "source": "/<*>",
        "target": "/404.html",
        "status": "404-200",
        "condition": null
    }
]
```
- The first one rewrite all routes of `/report/[slug]` with a trailing slash to the route a without trailing slash.
- The second one rewrites the requested `/report/[slug]` route to the html-file.
Using `<*>` instead of `<slug>` as placeholder as mentioned in the AWS docs did not work for me.
- The third rule redirect all request to the `/report/`, that are not found to the index page.
- The last rule is for a 404 page, if no page was found.

I hope this helps you

**Comment by ssousa33** [comment]
@marco910 , 

I came to essentially the same solution, with essentially the same conditions (only two dynamic routes in my app). I did, however, have to override the build config to amplify-cli@4.50.0

thanks for the response!

**Comment by marco910** [comment]
@ssousa33 ,

You have to add in your `package.json` for the build-script `next build && next export` and change the output directory in the build setting in the Amplify console to "out"
