### ISSUE TITLE
You have reached the maximum number of custom domains in this app

### ISSUE THREAD

**Issue by NimaSoroush** [aws-amplify/amplify-console#1771]
**Please describe which feature you have a question about?**

I have added Amplify Hosting to my application.
I wanted to configure custom domains through aws console for my amplify hosting app and I get this error 

![Screenshot 2021-04-25 at 16 22 46](https://user-images.githubusercontent.com/7963223/115999735-c7507f00-a5e4-11eb-8044-658a372dabae.png)

Is there any way to fix this?

**What AWS Services are you utilizing?**
AppSync, DynamoDB, Labmda, S3, Amplify

**Comment by nimacks** [comment]
Amplify allows you to add 5 custom domains to your app. https://docs.aws.amazon.com/general/latest/gr/amplify.html. If you would like to add more, use Service Quota https://console.aws.amazon.com/servicequotas/home/services/amplify/quotas/L-AD277529 to request limit increase. Reopen if you still have questions
