### ISSUE TITLE
Old page still visible after removed from build

### ISSUE THREAD

**Issue by thedgbrt** [aws-amplify/amplify-console#178]
**Describe the bug**
I removed a page from my Gatsby app, it is still visible on the deployment url (not using a custom domain)

**Expected behavior**
The pages available on a deployment should match what's generated by the build.

**Additional context**
I reloaded on a different browser, cleared the browser cache, force reloaded. 

**Sample code**
I downloaded the build artifacts from the amplify build step, and the page is not in there. This is likely a bug in the deployment step, as I only see updates and skips from the deploy logs, but no "delete" operation.

**Comment by thedgbrt** [comment]
It might be related to https://github.com/aws-amplify/amplify-console/issues/74

**Comment by cslogan-red** [comment]
This is an intentional feature within Amplify Console to gracefully handle a number of scenarios, like code splitting as an example, so that new builds don't invalidate cached resources while a user is actively browsing your app. Deleted resources are eventually invalidated and purged after several builds, and will then no longer be accessible from your app's url.

**Comment by thedgbrt** [comment]
@cslogan-red interesting, I’d like to have more information about this from the console, but for now your comment is helpful. 👍

**Comment by simpson** [comment]
I am also in hot water because I can't purge files that users have explicitly requested be removed from our platform, we have deleted them in the build but the cache still exists. Is there any short term workaround for this while we find a better solution?

**Comment by lukaskoeller** [comment]
We are using Amplify to deploy our app but received several `ChunckLoadError`s. Is this feature of keeping old assets not enabled by default? Is there a way to enable it?
