### ISSUE TITLE
amplify pull --appId xxx --envName staging gets stuck 

### ISSUE THREAD

**Issue by nyholku** [aws-amplify/amplify-console#1781]
I've been following the tutorial

https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-one/

to letter.

Made it through twice, now stuck on third try.

I do 'ampllify configure'

and create a new user (accepting the default), download the .csv with credentials, copy/paste those in the terminal
and accept the creation of defaul profile (what ever that means).

I the try in terminal to 'amplify pull -'appId ....." 

And I get to the browser page (in Chrome/Macos) where I should enter my user name and password.

I enter the user name I just created but where do I get the password?

When I created the user there was no place where to add the password.

I cannot as for password reset because this user has no email.

When I created the password there was no place to add an email?

If I try my root user that does not work here.

From AWS management console I cannot find any place where to enter the password nor the email.

I don't recall what I did different on the previous occasions when it succeeded, perhaps something to do with 'amplify role'.

Anyway, help would be appreciated, stuck here for four hours now. This is getting old.

I see a lot of people having difficulties with this. 

There is something wrong or missing with this process or instructions.

**Comment by nyholku** [comment]
Thanks for the quick response. No, not custom domains, have difficulties to get to the starting line ;)

I looked through the FAQ but nothing rang a bell.

But many similar issues can be easily googled for.

I have tried many of the suggestions but no luck so far. 

Worked for me two experimental projects, third time was not the charm.

**Comment by siegerts** [comment]
Hi @nyholku, thanks for raising. Make sure to click the **Open Admin UI**(below in orange) button before you run `amplify pull ...`.  This will authenticate you into the Admin UI so that when the page opens you won't be prompted for those credentials.

![image](https://user-images.githubusercontent.com/634958/116416882-c4ce6f00-a808-11eb-8dd8-624fe117a57a.png)

**Comment by nyholku** [comment]
Thanks! That did the trick!

My bad, it says that on the instructions, however this might be underlined and bolded in red letters cause this is such a crucial step and it is very difficult to understand because of the confusion with the invite users, missing emails and passwords etc. One goes up the creek without a paddle so fast.

Also it is not clear what to do if one wants to run "amplify configure" without creating a new user, could you throw some light on that ?

**Comment by siegerts** [comment]
Great! I agree that it needs to be called out more and have raised with the team.

If you have an existing user configured on your machine with the correct permissions then you should be able to select that profile when `amplify init` or `amplify pull ...`. This configuration is usually in the same place where your profile/creds are stored for the AWS SDK.
