### ISSUE TITLE
[ERROR]: Failed to deploy ... with no clues to the problem

### ISSUE THREAD

**Issue by nyholku** [aws-amplify/amplify-console#1786]
I've been following the tutorial

https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-one/

At first when there was only react front end the deployment went without a hitch.

I then added the authentication and it works locally, builds in the cloud, but the deploy stage fails with:

```
2021-04-29T06:33:33 [INFO]: Starting Deployment
2021-04-29T06:33:33 [ERROR]: Failed to deploy
```

App ARN is

arn:aws:amplify:eu-central-1:910630674321:apps/dqlclxsy9in2m

thank you for your help.

**Comment by alice-was-here** [comment]
Our team is having the exact same issue, which started around the same time (e.g. a few hours ago today). 

Our app reports the `Build` step as being successful, but the logs stop just after our `yarn build` step and no artifact is attached to the `Build` step. The deploy step shows the same error as @nyholku 

Our app arn is arn:aws:amplify:ap-southeast-2:734296576770:apps/dtdeunq6oaa7z

**Comment by nyholku** [comment]
Same kind of problem with me second test app/build/deploy 

arn:aws:amplify:eu-north-1:910630674321:apps/d6afkrqqsfxop

maybe this is my bad cause I did this test in a hurry...

**Comment by alanhortz** [comment]
We have the exact same issue on a fresh react app ...

Build successful but deploy fails for no apparement reasons

2021-04-29T11:13:59 [INFO]: Starting Deployment
2021-04-29T11:13:59 [ERROR]: Failed to deploy

arn:aws:amplify:eu-west-1:066832409643:apps/d3cldr4npp3c0

**Comment by artidata** [comment]
I have the eaxct same issue on existing project with 50+ build history.

**Comment by alanhortz** [comment]
I have deleted the stack and bootstrap a new one from the React Sample with authentication directly from Amplify admin, this built properly and deployed without any issue ... 

The create-react-app script was used for the first fresh react app strictly following the Sandbox guidelines 

![image](https://user-images.githubusercontent.com/1903681/116604348-49ff7400-a92e-11eb-9003-8339d234eee6.png)

> We have the exact same issue on a fresh react app ...
> 
> Build successful but deploy fails for no apparement reasons
> 
> 2021-04-29T11:13:59 [INFO]: Starting Deployment
> 2021-04-29T11:13:59 [ERROR]: Failed to deploy
> 
> arn:aws:amplify:eu-west-1:066832409643:apps/d3cldr4npp3c0

**Comment by nyholku** [comment]
I redid the project from scratch, struggled with the permissions but now it works.

**Comment by ac3charland** [comment]
Was experiencing this same issue and was able to find a fix that doesn't require redoing the project. I discovered I was using the latest version Amplify CLI in my build settings, which must have recently introduced a breaking change.

To fix:
- In the Amplify console, go to Build settings > Build image settings > Edit
- Specify the version of Amplify CLI that's in your project's package.json
<img width="601" alt="Screen Shot 2021-04-29 at 4 21 12 PM" src="https://user-images.githubusercontent.com/36909821/116620268-35f44c00-a907-11eb-879d-91da24af46d7.png">
