### ISSUE TITLE
Starting Deployment then immediately Failed to Feploy.

### ISSUE THREAD

**Issue by artidata** [aws-amplify/amplify-console#1787]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

Hi, I have been using the continuous deployment setup. With a simple git push, my project has always been deployed successfully. However, my three latest push seems to failed without giving any clue to fix it. The three deployment always show the following message in the console: 

2021-04-29T12:32:10 [INFO]: Starting Deployment
2021-04-29T12:32:10 [ERROR]: Failed to deploy

Please advice.

### Expected behavior

I look at successful build history. On the deploy stage the message should have shown:

2021-04-27T12:54:22 [INFO]: Beginning deployment for application d1tm708pfdcz9c, branch:dev, buildId 0000000057
2021-04-27T12:54:22 [INFO]: Got archive: 3420216 bytes
2021-04-27T12:54:22 [INFO]: Archive unzipped: 96 files
2021-04-27T12:54:23 [INFO]: Deployment complete

### Reproduction steps

git push

**Comment by ac3charland** [comment]
Was experiencing this same issue and was able to find a fix. I discovered I was using the latest version Amplify CLI in my build settings, which must have recently introduced a breaking change.

To fix:

In the Amplify console, go to Build settings > Build image settings > Edit
Specify the version of Amplify CLI that's in your project's package.json
<img width="301" alt="Screen Shot 2021-04-29 at 4 21 12 PM" src="https://user-images.githubusercontent.com/36909821/116620393-62a86380-a907-11eb-869f-cd2974890f4e.png">

**Comment by artidata** [comment]
I updated my local aws-amplify/cli vesion. It then leads to build error exactly as https://github.com/aws-amplify/amplify-cli/issues/7190
