### ISSUE TITLE
SSL configuration is Running - Getting 403 from CloudFront via Browser

### ISSUE THREAD

**Issue by RockManJoe64** [aws-amplify/amplify-console#1788]
**App Id**: d3ch5q6h4m31s8
**Region**: us-east-2
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I have a domain at GoDaddy which I am trying to add as a custom domain in AWS Amplify.
I created the app 2 weeks ago, and I set up the custom domain 2 days ago. However, it is stuck in the SSL Configuration state.
I've added the custom CNAME entry in GoDaddy for certificate verification, but nothing has moved.

**Error message**

When I try to go to the domain in the browser, I get this message:

```
403 ERROR
The request could not be satisfied.
Bad request. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: EAzSM4dcZ_9Wb0mQcAWCAMJl8TluXuLfhVS1D6pU1YAe4Imqz32rJA==
```

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by nimacks** [comment]
Our records indicate that your domain is now available. Re-open if you're still having issues.
