### ISSUE TITLE
When doing "amplify publish", how do I connect the app to a custom domain?

### ISSUE THREAD

**Issue by ilyador** [aws-amplify/amplify-console#179]
I see it can be done in the Amplify console, but for some reason, my app does not appear there.

It is quite confusing since I'm not sure what is the difference between the Amplify CLI and the console on AWS.

**Comment by PavleNeskovic** [comment]
You need to connect the app that you initialized with Amplify CLI to GitHub (or some other Git provider) and then in Amplify Console choose that repo and deploy the app from there.

Amplify CLI and Amplify Console are kinda two different things.  CLI helps you to build your app and manage your cloud resources and Amplify Console is a continuous deployment tool.

**Comment by cslogan-red** [comment]
https://docs.aws.amazon.com/amplify/latest/userguide/deploy-backend.html

The above docs will help you get started, presently you'll start your project using the Amplify CLI and then push your project's repo to the Git provider of your choice. You then connect your app to the Amplify Console via that Git repo for full hosting and CD support, including features like adding a custom domain.
