### ISSUE TITLE
Hosted web app React + Next.js not deploying correctly. getting 404. No log error.

### ISSUE THREAD

**Issue by fattoriaweb** [aws-amplify/amplify-console#1791]
My web app stopped deploying correctly, from all branches. The pipeline completes with no erros messages, but the deploy phase is not showing the receiving deployment artifact. 

ARN app: arn:aws:amplify:us-east-1:330301280103:apps/dxeuftgjql81x

Not working deploy log
`2021-04-30T15:42:15 [INFO]: Beginning deployment for application dxeuftgjql81x, branch:desenv, buildId 0000000201 
2021-04-30T15:42:20 [INFO]: SSR Deployment complete`

Expected deploy log, working
`2021-04-30T15:42:26 [INFO]: Beginning deployment for application dwj8l3t9bajpa, branch:desenv, buildId 0000000004 
2021-04-30T15:42:31 [INFO]: Got archive: 434341907 bytes 
2021-04-30T15:42:52 [INFO]: Deployment complete`

Have created a new test app with the same steps, and works fine with the expected deploy log
ARN test app: arn:aws:amplify:us-east-1:330301280103:apps/dwj8l3t9bajpa

**Comment by brnmye** [comment]
Hello I tried looking into the apps information, and it seems to have been deleted, is this the case?

**Comment by Athena96** [comment]
Hi @fattoriaweb it looks like in issue with the output directory being set to out instead of .next for your SSR app which lead to the 404. Closing this issue, please feel free to re-open if you are still facing this issue. Thanks!
