### ISSUE TITLE
Master backend environment is gone

### ISSUE THREAD

**Issue by svota** [aws-amplify/amplify-console#1793]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

Similar to https://github.com/aws-amplify/amplify-console/issues/560
I have an Amplify app with multiple backend environments tied to two frontend environments. Today, I opened my console and it showed that both frontend environments were not connected to a backend, and my dev environment was failing on build. I was able to reconnect my dev environment, but when I tried to connect the master, I found that the environment was missing from both the dropdown menu and the backend environments tab. (See attached images)

The website is still working, and associated stacks in CloudFormation, tables in DynamoDB and APIs in AppSync are still present, but I'm still feeling a little confused.
![image](https://user-images.githubusercontent.com/424767/116750400-68b64700-a9d0-11eb-9a1e-2f6a2a131e6e.png)
![image](https://user-images.githubusercontent.com/424767/116750462-7ec40780-a9d0-11eb-96cb-ea01380d877c.png)

### Expected behavior

I expect to be able to see the master backend as connected to the master frontend, as well as find it in the backend environments tab.

### Reproduction steps

1. Go to Amplify Console
2. Click on zipclix App
3. Click on 'backend environments' tab
4. See that there's no master backend env.

### Additional information

App ARN: arn:aws:amplify:us-east-1:731527939576:apps/d1jzyhgg6qwh7a

**Comment by brnmye** [comment]
Hello thank you for bringing this up I am looking into this issue to ensure whether or not this is a bug on our end. Is this occurring on more than one app?

**Comment by svota** [comment]
No, it's only happening on the one app, but none of my other apps have a
frontend and backend deploying together. Also, I suspect that the master
backend is still present because it deploys new versions correctly. It just
seems to have disappeared.

**Comment by victorccccc** [comment]
Hi, sorry for the inconvenience. From our logs, `master` backend has been deployed successfully for `zipclix` app. 

Feel free to re-open this if issue persists. Thanks
