### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by heightsInnov** [aws-amplify/amplify-console#1797]
**App Id**: d1jlz4qc1uwfqn
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am unable to link my domain to the amplify app I created. I have once created it and it worked only for the domain to fail after some days. i tried reconnecting the domain but I get the error in the attached everytime.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
<img width="1083" alt="Screenshot 2021-05-02 at 12 33 25" src="https://user-images.githubusercontent.com/13130013/116811714-9c18e300-ab42-11eb-8177-68b767e592c6.png">

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by heightsInnov** [comment]
Looking forward to a valid assistance as it is a matter of urgency

**Comment by heightsInnov** [comment]
I have follows the documents sent to me in the previous response but I couldn't find any distribution on CloudFront and nothing attached to my domain, yet it returns the same error for all retrials.

**Comment by heightsInnov** [comment]
I am getting the issue on Amplify, I hope that is not different from CloudFront.

**Comment by ferdingler** [comment]
#1798

**Comment by ferdingler** [comment]
@heightsInnov I see on our end that your custom domain is available and deployed correctly. Can you please confirm you were able to set it up?

**Comment by heightsInnov** [comment]
The root domain remains unusable for me due to the above error but I was able to create subdomains. Why is my root domain still unusable? It says it is already connected to another resource which I don't know. 
Root domain: ermportal.org

**Comment by ferdingler** [comment]
Hi @heightsInnov, I'm sorry you had issues creating your custom domain. We have recently improved our error messaging on the CNAMEAlreadyExistException to give customers better information on how to recover from it. This usually means one of these things: 

1) You have already used the same custom domain in another Amplify App in another region/account. 
2) You are using this domain in another service: LightSail or API Gateway. 
3) Your domain has an old CNAME record that points to a cloudfront.net URL from a previous Amplify App. 

Feel free to re-add the custom domain and you should get better information on what's going on. Thanks for reporting!
