### ISSUE TITLE
Unknown backends appearing

### ISSUE THREAD

**Issue by djsmedes** [aws-amplify/amplify-console#1801]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2986q4269uszd

### Region

us-east-1

### Amplify Console feature

Backends

### Describe the bug

A colleague on my team, @ryanpeelman, has three unknown backends showing up on his Amplify app. They appear in the `Backend environments` tab, with a deployment status that constantly spins in "Fetching." They are named `anita`, `gwyneth`, and `maggie`.

![image](https://user-images.githubusercontent.com/7870631/116923617-dbb7fb80-ac24-11eb-9160-025687449a63.png)

We have no idea where these came from. We use AWS Organizations to manage multiple AWS accounts, and the account in question is meant to be @ryanpeelman's sandbox; I as the manager of the Organization _can_ assume a role into his account, though I have never done so in any workflow relating to Amplify (only management functions like IAM), and no one else even has access.

This seems to be some kind of tenanting or configuration bug within Amplify - we're not seeing random resources showing up in other AWS services - so I'm starting here.

### Expected behavior

Backends should not appear unless we put them there.

### Reproduction steps

Unknown.

### Additional information

Upon attempting to delete one of the environments, we got this:

![image](https://user-images.githubusercontent.com/7870631/116923919-39e4de80-ac25-11eb-8211-dae3313cd400.png)

But when reloading the page, all three remain, with their perpetual "Fetching" status.

**Comment by brnmye** [comment]
Hello thank you for sharing your issue, I am investigating this to determine whether it is a bug on our side.

**Comment by benmj** [comment]
Hey @brnmye -- any update on this? It's concerns me that there might be cross-tenant leaks going on with amplify. @djsmedes is on my team.

Thanks

**Comment by codecadwallader** [comment]
I can't find it in the source code for this repo.. but it looks like this may be deliberate behavior based on these logs:

> 2021-06-07T20:53:46.867Z [INFO]: BackendEnvironment name ab/cdef for app d1234 is invalid
> 2021-06-07T20:53:46.944Z [INFO]: Random environment name willy generated

**Comment by brnmye** [comment]
Hello the behavior behind the random backend names appearing is expected. If the name input is invalid it will be replaced with a randomly generated first name such as willy. An acceptable name is 2-10 characters long and must be lowercase letters only. The logs that will appear if the name is invalid and a random name is generated will look like what @codecadwallader commented above. We are working on improving this process, thank you.
