### ISSUE TITLE
Domain activation is Failed - Trying to assign a subdomain to a new AWS Amplify webapp

### ISSUE THREAD

**Issue by carlosalvidrez** [aws-amplify/amplify-console#1809]
**App Id**: d20el7a7f463ab
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
The CNAME gets verified, but I get this error message, in spite of this being the one and only CNAME I have pointing to AWS: "Error message: One or more of the CNAMEs you provided are already associated with a different resource."

**Error message**
"Error message: One or more of the CNAMEs you provided are already associated with a different resource."

**Additional information**
New to this, wondering if I might be missing something obvious. The AWS Amplify webapp works well, but with the native AWS URL. All I am trying to do is use it with my own domain.
Thanks!

**Comment by carlosalvidrez** [comment]
I followed the troubleshooting guide, thanks. No luck though. I do not have any distribution on cloudfront.
https://console.aws.amazon.com/cloudfront/home?#

Two things that may be relevant though:
(1) I have a custom subdomain setup with Meteor Cloud.
(2) I also have another subdomain setup with Mongo Atlas (Cloud service for MongoDB).

**Comment by gautam-nutalapati** [comment]
> I followed the troubleshooting guide, thanks. No luck though. I do not have any distribution on cloudfront.
> https://console.aws.amazon.com/cloudfront/home?#
> 
> Two things that may be relevant though:
> (1) I have a custom subdomain setup with Meteor Cloud.
> (2) I also have another subdomain setup with Mongo Atlas (Cloud service for MongoDB).

This helped me. Mine was failing due to a cloudfront distribution using the same domain I want to use in amplify under its CNAME. Even though distribution was disabled, I still had to remove the CNAME from it.

**Comment by ferdingler** [comment]
@carlosalvidrez I see on our end that your domain association is currently waiting to validate that a CNAME exists pointing to the cloudfront distribution for your app. You should create an entry in your DNS records like this: 

```
www.example.com       CNAME          123456789.cloudfront.net <--- replace with the correct URL for your app
```

**Comment by carlosalvidrez** [comment]
Thanks Fernando... as soon as I deactivated Mongo Atlas hosting (I don't handle those things directly, they are a bit of a black box to the end-user), the thing worked. They must have their own cloudfront records for it.
I appreciate the help anyway. 
Cheers
