### ISSUE TITLE
GatsbyImage and StaticImage Does Not Load on Deployment

### ISSUE THREAD

**Issue by abechoi** [aws-amplify/amplify-console#1810]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-west-2:986268797763:apps/d2p7f1yfv5gsu0

### Region

us-west-2

### Describe the bug

I want to deploy my Gatsby project on AWS Amplify, but when I do, the images do not load. I've deployed it on Netlify and I did not have an issue, so I'm assuming I'm not using AWS Amplify correctly here. Is there anything special I need to take care of?

https://github.com/abechoi/Abechoi_Gatsby

### Expected behavior

Images to load.

### Reproduction steps

Deploy my repo on AWS Amplify.

**Comment by abechoi** [comment]
Update: It appears that I needed to create and add a service role for Amplify, which I just did, but I'm still not seeing changes. Just thought I'd add that.

**Comment by JKalm** [comment]
Hello @abechoi,
I was able to reproduce issue. Looks like frontend build creates 3 versions for each image: .avif, .webp and .png. I can see that all images were uploaded to S3 bucket, but only PNG files are available via CloudFront, .webp (the one that is used now) is not available. As a workaround you can try to switch to PNG in Gatsby config.

Thank you for pointing out, we will investigate if some Gatsby features are not working as expected with Amplify.

**Comment by abechoi** [comment]
Thanks for replying! I will definitely try that.
