### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Andrewkizito** [aws-amplify/amplify-console#1812]
**App Id**: d2ro6djv2wan83
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I have added to cnames to my godaddy domain but the process of domain activation still fails

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by mtimbs** [comment]
I am also getting this issue and AWS premium support has been no help. They keep linking me to the troubleshooting guide.

In my case, I have checked countless times and no Cloudfront distribution exists linked to the domain. Is it possible that this is an internal AWS issue

**Comment by Andrewkizito** [comment]
**mtimbs** I solved it after realising that I was referencing my domain  as an alternate cname on a cloudfront distribution I had created before, removing the alternate cnames saved the day. Since I didn't need the cloudfront distribution , I just deleted it
