### ISSUE TITLE
Read values from Secrets managers as environment variables in amplify.yml

### ISSUE THREAD

**Issue by akanungo22** [aws-amplify/amplify-console#1814]
**Please describe which feature you have a question about?**

**Provide additional details**

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

**Comment by brnmye** [comment]
Hello could you please provide more details on your issue, such ass appId, region, and what specific issue you are facing. Thank you

**Comment by behrooziAWS** [comment]
Untested but you should be able to run aws cli commands like this to get secrets in your account in your buildspec:

`ENV_VARIABLE=$(aws secretsmanager get-secret-value --secret-id <your-secret-id>)`

**Comment by akanungo22** [comment]
I got another issue - The cypress tests are failing but the Test phase is showing as successful.

**Comment by akanungo22** [comment]
ENV_VARIABLE=$(aws secretsmanager get-secret-value --secret-id <your-secret-id>) is working when there is no secret key for the secret id.
but how to access a particular secret key value of secret id through aws secretsmanager cli?

**Comment by behrooziAWS** [comment]
You should be able to test the command locally.  You'll likely need to use a [tool like jq](https://stackoverflow.com/questions/35154684/how-to-parse-a-json-string-with-jq-or-other-alternatives) if you want to unescape the string 

Using the example from [here](https://docs.aws.amazon.com/cli/latest/reference/secretsmanager/get-secret-value.html) your command might look like this to get the database password:

`ENV_VARIABLE=$(aws secretsmanager get-secret-value --secret-id MyTestDatabaseSecret | jq -r ".SecretString | fromjson | .password")`

You may need to install jq on the build image with a command like 
`yum install jq`

**Comment by behrooziAWS** [comment]
Not info info to troubleshoot the issue with cypress tests, create a new issue with the appid/region etc if you still need assistance.
