### ISSUE TITLE
Redirect any root request with no extension to another site

### ISSUE THREAD

**Issue by carlosalvidrez** [aws-amplify/amplify-console#1817]
**Please describe which feature you have a question about?**
Can you help me formulate a redirection, so that anything requested that (1) has no file extension, and (2) is not a root folder, gets sent to another site?

For example /index.html stays, no redirect.
But, the following do redirect (2 examples):
(1) /asdf?a=b  to  https://app.domain.com/asdf?a=b
(2) /1xh!d?v=36&ppn=4  to  https://app.domain.com/1xh!d?v=36&ppn=4

**Provide additional details**
Background: I switched my web app from "www" to "app", and with that, a few thousand tweets with links to "www" do not work. WWW is now my new amplify root webapp.

**What AWS Services are you utilizing?**
AWS Amplify for my new web root, my www subdomain if you will.
Another service provider to host my "app" subdomain.

THANS!

**Comment by hloriana** [comment]
Hi, if you still need help with this, please feel free to re-open.
