### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by sven-simonsen** [aws-amplify/amplify-console#1826]
**App Id**: d3880pl7cp91jk
**Region**: eu-west-1
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
We moved from eu-central-1 to eu-west-1 and tried to connect the new deploys to different subdomains than the old deploys to have them both running while we iron out the kinks.
The move was much harder than we expected and now we have waited a day for the SSL Configuration.
Is it not possible to have deploys in different region on the same domain as long as subdomains don't overlap?

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by ferdingler** [comment]
@sven-simonsen, apologies for the delay here. Correct, you cannot use the same FQDN (Fully Qualified Domain Name) in 2 different applications. For example, if you have `app.example.com` as a custom domain in an app in `eu-central-1` and you want to move it to an app in `eu-west-1`, you'll need to use a different FQDN like `eu-west.example.com`. Regardless of what subdomains you configure on each app, what matters is the root of the custom domain. 

It looks like you manage to migrate your domain which I'm glad to see. We actually have a guide here https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md#how-do-i-migrate-domains-to-amplify-with-minimal-downtime that explains how to migrate a domain with minimal downtime for future reference. 

Feel free to re-open if you have further questions.
