### ISSUE TITLE
App suddenly showing `Access Denied`

### ISSUE THREAD

**Issue by bryantbiggs** [aws-amplify/amplify-console#1834]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://us-west-2.console.aws.amazon.com/amplify/home?region=us-west-2#/d3ndnd4b9c3ojo

### Region

us-west-2

### Describe the bug

Hi - our app suddenly started showing `Access Denied` errors this morning and we haven't made any changes. It looks like an S3 permission issue but the S3 bucket is controlled by Amplify, not us.

`AccessDeniedAccess DeniedJ7BBEX18P9JE5DGH4qBTV9lP82GtiBhXRxlcP+suE7Vxq2k7at/+hzKkgqe4cyVhG6iRFSkvYioT3OM5IuxVp9i+CfA=`

### Expected behavior

Website should continue to load successfully as it did before.

### Reproduction steps

N/A - we didn't change anything

### Additional information

![image](https://user-images.githubusercontent.com/10913471/118170952-b2ebef00-b3f8-11eb-93c8-a043205d89d0.png)

**Comment by JKalm** [comment]
Hello Bryant, can you please specify url you're trying to access? https://master.d3ndnd4b9c3ojo.amplifyapp.com seems to be working for me, do you still see the issue?
