### ISSUE TITLE
502 Cloudfront cannot resolve origin domain

### ISSUE THREAD

**Issue by jleslie02** [aws-amplify/amplify-console#1840]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2811gs0q9oaie

### Region

us-west-2

### Step

After Domain activation

### Status

Available

### Issue or question

After creating a custom domain, the link does not work and I receive the error below (see attached image)
I have:
- deleted the app
- deleted the hosted zone
- deleted the stack
- rebuilt it all again

Same outcome. Also the same issue happens with appId: d91in9rb7qfx (us-west-2)

Note: sometimes it works and then few minutes later all links give a 502 (CloudFront wasn't able to resolve the origin domain name as the mage specifies)
![Screen Shot 2021-05-14 at 5 25 39 PM](https://user-images.githubusercontent.com/6761015/118342724-73e19a80-b4d9-11eb-8fc0-73da80bb8b77.png)

### Error message

502 ERROR
The request could not be satisfied.
CloudFront wasn't able to resolve the origin domain name. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: -I9G0pUZNdsZFfiL915frMF76Jxnb7SJ0WwQjdWSAtU6p7Cu7wu96w==

**Comment by ferdingler** [comment]
Hi @jleslie02, a quick look at your app with id `d91in9rb7qfx` shows that it doesn't have any subdomains on it (including the domain itself), and therefore no branches are connected to your custom domain. Let me do some additional investigation to confirm this is what's going on.
