### ISSUE TITLE
[Error: Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference]

### ISSUE THREAD

**Issue by kush4999** [aws-amplify/amplify-console#1844]
what can i do in this particular error? any one can please help.

**Comment by siegerts** [comment]
Hi :wave: - thanks for raising this!  To get a bit more context, do you mind porting this a [formatted issue](https://github.com/aws-amplify/amplify-console/issues/new?assignees=&labels=&template=1.bug_report.yaml)? This will help the team determine the best approach to take.

Thanks!
