### ISSUE TITLE
Domain activation is Failed - [Assign a domain on Route53]

### ISSUE THREAD

**Issue by Yusadolat** [aws-amplify/amplify-console#1846]
**App Id**: d1pd30g9n1cswg
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.
I have deleted the hosted routes, Where can I check out the existing CNAME 
**Error message**
If there is an error message, please include it here. 

Error message: One or more of the CNAMEs you provided are already associated with a different resource. 

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by ferdingler** [comment]
Hi @Yusadolat, I see that your domain is already in the AVAILABLE state and resolving properly, I'm glad to see you figured it out.
