### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by crazydev901** [aws-amplify/amplify-console#1848]
**App Id**: d1e54nzu0apre2
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Running

**Issue/question**
I connected my custom namecheap doamin to aws amplify console. How long does it take to validate the domain?

**Comment by ferdingler** [comment]
Hi @crazydev901, looks like your domain is already in the AVAILABLE state, but to answer your specific question: 

If you add the CNAME verification record as soon as you create your custom domain, We check for the CNAME record every few minutes to determine if it resolves. If it doesn’t resolve after an hour, the check is made every few hours, which can lead to a delay in your domain being ready to use. 

More info: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#my-domain-hosted-with-a-third-party-is-stuck-in-the-pending-verification-state
