### ISSUE TITLE
Domain activation is Failed - CNAME provided already in use by another resource

### ISSUE THREAD

**Issue by segura27** [aws-amplify/amplify-console#1849]
**App Id**: d28h9ork5atphk
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I'm trying to use my Route53 registered custom domain on my Amplify app. However, I'm getting an error: "One or more of the CNAMEs you provided are already associated with a different resource."

I went to Route53 and deleted all A and CNAME records except the ones that were created by Amazon SES and WorkMail as these are services being used as we speak.

**Error message**
"One or more of the CNAMEs you provided are already associated with a different resource."

**Additional information**
Do I need to completely delete all of my domain CNAME records? Won't this affect my WorkMail and SES infrastructure. If so, I guess I can take care of rewiring stuff in the early morning to minimize downtime for my users.

**Comment by ferdingler** [comment]
Hi @segura27 , I see that your domain is already being used by another CloudFront distribution on the same AWS account as your Amplify app. Consider using a subdomain (i.e. `app.example.com`) for your Amplify app, or release the domain from the other CloudFront distribution so that Amplify can use it.

**Comment by segura27** [comment]
Thanks a lot for the help. I actually ended up doing that but would work either. Only after waiting like 30min was the domain resolved.
