### ISSUE TITLE
Domain activation is Failed - Domain activation failed 

### ISSUE THREAD

**Issue by yu-randolph** [aws-amplify/amplify-console#1859]
**App Id**: d3r7qc2di3baed
**Region**: ap-southeast-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Currently trying to use our business domain that is in route 53 for Amplify. The domain activation seems to fail due to an error that is usually tied to having used the domain in an existing cloudfront account even if my AWS account does not have any cloudfront distributions.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**

![image](https://user-images.githubusercontent.com/12183600/118810090-08833880-b8de-11eb-95ab-4f07a2338765.png)
![image](https://user-images.githubusercontent.com/12183600/118810154-20f35300-b8de-11eb-86f1-f8404862c081.png)

**Comment by yu-randolph** [comment]
APP ID
arn:aws:amplify:ap-southeast-1:735152622280:apps/d3r7qc2di3baed 
REGION
ap-southeast-1

**Comment by nimacks** [comment]
Our records indicate that your domain is now available. Re-open if you're still having issues.
