### ISSUE TITLE
On page reload in the browser or when using windows.location.href  a trailing slash is added to the end of the url.

### ISSUE THREAD

**Issue by suhas-007** [aws-amplify/amplify-console#186]
On page reload in the browser or when using windows.location.href  a trailing slash is added to the end of the url.

The above behaviour is only when a domain is used, for example 
https://www.test.com/test  is getting replaced as https://www.test.com/test/

**Comment by swaminator** [comment]
@suhas-007 do you have a file available at https://www.test.com/test.html? If not, then Amplify Console automatically adds trailing slashes.

**Comment by suhas-007** [comment]
Yes files are available at the corresponding url.

**Comment by nimacks** [comment]
> Yes files are available at the corresponding url.

@suhas-007, just to confirm, is the file an html file?

**Comment by Joycehao19** [comment]
@suhas-007 I saw your folder structure on AWS Premium Support. If you have an available file `test.html`, the url would be replaced as https://www.test.com/test
If the file is `test.component.html`, it would be automatically added trailing slashes by Amplify Console.

**Comment by suhas-007** [comment]
@Joycehao19  I changed the test.component.html  to test.html  and even in the test.component.ts file I am referring the html in selector as test.html . 
After pushing the changes and testing it ,still the same issue.

Please guide.

**Comment by suhas-007** [comment]
Please guide

**Comment by Joycehao19** [comment]
If you have a file available at test.com/test.html, the url should be https://www.test.com/test. If you still having this issue, would you mind provide your appId and region to us?
