### ISSUE TITLE
Deploy failed to complete successfully - No Error message

### ISSUE THREAD

**Issue by ACPK** [aws-amplify/amplify-console#1863]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3auzkbi1yrd6m

### Region

us-east-1

### Describe the bug

I am unable to deploy as I get the following error message on the third step in Amplify:

```Deploy failed to complete successfully.```

There is only 1 line in the logs on the screen. That one line is:

2021-05-19T20:59:29 [INFO]: Beginning deployment for application <app_id>, branch:comparison, buildId 0000000018

### Expected behavior

The app should deploy or at least provide error logs.

### Reproduction steps

I deployed via Github and also clicked the "Rebuild" button via the Amplify UI.

**Comment by ACPK** [comment]
Seems to be related to: https://github.com/aws-amplify/amplify-console/issues/1854

**Comment by thomaschaaf** [comment]
same is happening for us. AWS Support Ticket 8382651151

**Comment by nestorochoa** [comment]
We are having the same issue and we cannot deploy anything 
App ID: d3td4in2dnk19a
Region: ap-southeast-2

**Comment by ncoop720** [comment]
I had the same issue and resolved it by adding administrator access to the service role.

**Comment by Athena96** [comment]
closing this issue, feel free to re-open if you continue to face it. thanks!

**Comment by ACPK** [comment]
@Athena96 We hit the issue (third time now) again today. The "framework" in the CLI keep going blank. We've deployed 30+ times successfully, but then hit the issue randomly.

Here's the screenshot of the AWS Amplify CLI > General. This should to say Next.JS SSG.

https://www.loom.com/i/e5ae98a56d994eafa389f9021f2762ff
