### ISSUE TITLE
Domain activation is Failed - One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by godsmustbcrazy** [aws-amplify/amplify-console#1868]
**App Id**: d3mygq1w99jrhx
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am trying to activate a domain for an amplify project with root redirecting to www for one branch and a sub domain for another branch. My domain is in Route53 and the records  are being automatically created by Amplify but it fails at the end.

**Error message**
 One or more of the CNAMEs you provided are already associated with a different resource.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**

**Comment by godsmustbcrazy** [comment]
Any help on this please? I have searched for this issue and tried different things to no avail. Any help would be greatly appreciated.

**Comment by nimacks** [comment]
Our records indicate that your domain is now available. Re-open if you're still having issues. `c*****p*****.io`
