### ISSUE TITLE
Can we use django framework web app and API in AWS Amplify ?

### ISSUE THREAD

**Issue by etechdreams** [aws-amplify/amplify-console#1869]
How to deploy django web app in AWS amplify ?

**Comment by siegerts** [comment]
Hi @etechdreams, 

An option would be to deploy using the Serverless Container functionality with the Amplify CLI - https://docs.amplify.aws/cli/usage/containers

I wrote up an example with FastAPI (below) , but a similar approach can be taken with Django and a `docker-compose` to link other services if needed:

https://dev.to/siegerts/deploying-a-fastapi-backend-using-aws-amplify-container-based-rest-apis-2f6i

Hope that helps!
