### ISSUE TITLE
Domain activation is Failed - JS error prevents any action

### ISSUE THREAD

**Issue by aromka** [aws-amplify/amplify-console#187]
**App Id**: d2knlhjugeqf3e
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Neither delete or retry works - any domain option throws JS error - see screenshot:

![Screen Shot 2019-10-08 at 3 24 49 PM](https://user-images.githubusercontent.com/2651029/66426424-cb578480-e9df-11e9-9728-2fd584d06a99.png)

**Error message**
No error message - js fails and nothing happens.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by swaminator** [comment]
@aromka are you still seeing the same error? Can you retry please?

**Comment by bokobza** [comment]
**App Id**: d2a1a4icip7mla
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

I have the same issue.
When the domain management page loads I see this:
![image](https://user-images.githubusercontent.com/1867877/66958404-0309a080-f060-11e9-892d-3ccf80ab4c5b.png)

then the process fails here:
![image](https://user-images.githubusercontent.com/1867877/66958455-19aff780-f060-11e9-93f2-833ec5004ae2.png)

When I click Retry, I see this:
![image](https://user-images.githubusercontent.com/1867877/66958519-3b10e380-f060-11e9-9384-f0c2718c6af5.png)

but it doesn't retry.
If I click multiple times it tells me it's going to retry but if I refresh the page, it's telling me it failed.

**Comment by jojojo123** [comment]
@bokobza Do you still have this issue?

**Comment by Joycehao19** [comment]
@aromka : According to our records, your app is not available. Did you delete it?

**Comment by aromka** [comment]
@Joycehao19 - yes, deleted it, and re-created a new app. Seems to work fine.
One of the issue was that I had a disabled cloudfront using the same S3 bucket, so it was conflicting. The other issue is that you have js errors on that page.

In any case, everything works fine now.
Thanks!
