### ISSUE TITLE
Domain activation is Failed - Custom Domain for Amplify App

### ISSUE THREAD

**Issue by BenjaminBaekelandt** [aws-amplify/amplify-console#1879]
**App Id**: d3ty7ttco9mo8f
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
![image](https://user-images.githubusercontent.com/84841270/119634376-fd1a9a80-be12-11eb-8bb5-034c878f59df.png)

**Comment by nimacks** [comment]
@BenjaminBaekelandt , per the error message it looks like you have already associated your domain with another distribution

`com.amazonaws.services.cloudfront.model.CNAMEAlreadyExistsException
`
