### ISSUE TITLE
NextJS app API routes not working when deployed from monorepo

### ISSUE THREAD

**Issue by ashsmith** [aws-amplify/amplify-console#1881]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d350agb1cpqnvl

### Region

eu-west-1

### Amplify Console feature

Monorepo

### Describe the bug

When deploying a minimal nextjs app from within a subdirectory (monorepo) the build goes fine, but the API routes do not work.

Example site: https://main.d1rgx08nip8jme.amplifyapp.com/api/hello

The error is a CloudFront error with the following message:

>The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation. 

So this suggests there was an error with the Lambda@edge function. I used the "Test" section under the Lambda console and sent the following payload:

```json
{
  "Records": [
    {
      "cf": {
        "config": {
          "distributionDomainName": "d111111abcdef8.cloudfront.net",
          "distributionId": "EDFDVBD6EXAMPLE",
          "eventType": "viewer-request",
          "requestId": "4TyzHTaYWb1GX1qTfsHhEqV6HUDd_BzoBZnwfnvQc_1oF26ClkoUSEQ=="
        },
        "request": {
          "clientIp": "203.0.113.178",
          "headers": { },
          "method": "GET",
          "querystring": "",
          "uri": "/api/hello"
        }
      }
    }
  ]
}
```

And the Lambda result is as follows:

```
{
  "errorType": "Error",
  "errorMessage": "Cannot find module '../../chunks/400.js'\nRequire stack:\n- /var/task/pages/api/hello.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Error: Cannot find module '../../chunks/400.js'",
    "Require stack:",
    "- /var/task/pages/api/hello.js",
    "- /var/task/index.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:667:27)",
    "    at Module.require (internal/modules/cjs/loader.js:887:19)",
    "    at require (internal/modules/cjs/helpers.js:74:18)",
    "    at Object.__webpack_require__.f.require (/var/task/pages/api/hello.js:355:28)",
    "    at /var/task/pages/api/hello.js:289:40",
    "    at Array.reduce (<anonymous>)",
    "    at Function.__webpack_require__.e (/var/task/pages/api/hello.js:288:67)",
    "    at Function.__webpack_require__.x (/var/task/pages/api/hello.js:371:33)",
    "    at /var/task/pages/api/hello.js:381:57"
  ]
}
```

The two lambda's are vastly different sizes, as you can see below, which makes me think the issue is due to missing files (which lines up with the error above too!).

![image](https://user-images.githubusercontent.com/1086841/119676979-37496380-be36-11eb-9d61-fb1763d411b4.png)

I have successfully deploy without using a monorepo, from this repo: https://github.com/ashsmith/nextjs-amplify and the same build config except for the `appRoot: frontend`

### Expected behavior

The API lambda edge function executes successfully.

### Reproduction steps

Deploy this repo: https://github.com/ashsmith/nextjs-amplify-subdir

With the build config below.

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - yarn install
        build:
          commands:
            - yarn run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: frontend
```

**Comment by nimacks** [comment]
We are investigating this issue.

**Comment by Athena96** [comment]
@ashsmith I was able to deploy this mono repo with an API: https://github.com/Athena96/nextjs-blog/tree/monorepo
https://monorepo.du1neyjr0mzn5.amplifyapp.com/api/hello

Are you using any features of Next.js 10 in next version you are using?

**Comment by civicleb** [comment]
Having the same issue deploying simple nextjs app with an API using AWS amplify.
App worked fine when deployed to netlify.

**Comment by alistairstead** [comment]
I have run into the same issue.

@ashsmith there is a different next.js version between your two repositories:

- https://github.com/ashsmith/nextjs-amplify-subdir is pinned to 10.2.3
- https://github.com/ashsmith/nextjs-amplify is pinned to 10.2.0

I can confirm that by downgrading next.js to 10.2.0 that monorepo projects will correctly build the /pages/api resouces

I have not confirmed if this version of next.js will build in a simple project.

**Comment by Athena96** [comment]
Closing this issue, please feel free to re-open if you are still facing it. 
Also, keep in mind that Amplify currently supports 9.x.x of Next.js (with the exception of ISR): https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#nextjs-version-support

**Comment by oosswwaalldd** [comment]
I can confirm that I'm experiencing the same problem with Nextjs v12.1.0
