### ISSUE TITLE
New app does not successfully load at the <id>.cloudfront.net url shown

### ISSUE THREAD

**Issue by johnkavanagh** [aws-amplify/amplify-console#1883]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d28m7byy9tl8j1

### Region

eu-west-2

### Step

Domain activation

### Status

In progress

### Issue or question

Domain verification occurred a few days ago.  I'm now at the last step where I need to make ANAME and CNAME changes to my domain registration to point to AWS.

I've not yet made these changes because this is a live domain with active users, so need to be sure before making the switch.  In 'Update DNS records', there is the following message:

> Please wait until your new application loads successfully at the <id>.cloudfront.net url shown below.

The cloudfront URLs do not load, but return 404 when accessed directly.  I have kicked off new builds but this does not appear to make any difference.  I assume that there is a configuration step or option somewhere that is not documented or that I may have missed.

<img width="1181" alt="Screenshot 2021-05-27 at 08 35 52" src="https://user-images.githubusercontent.com/2272755/119785380-0ebd7a00-bec7-11eb-96e3-dcd22486db53.png">

### Error message

None.  Cloudfront URL does not load.

### Additional information

N/A

**Comment by nshyam97** [comment]
@johnkavanagh Did you manage to find out how to fix this issue at all? I'm running into the same one trying to get a custom domain registered through 123 Reg to work

**Comment by saadataz** [comment]
@johnkavanagh, Sorry for the delayed response. I see the app no longer exists.
Can you please reopen this issue (with your appID) if it reproduces again.

**Comment by johnkavanagh** [comment]
Hi @saadataz .  Thank you for coming back to me.  I'm afraid after waiting some weeks for a response, I simply gave up and moved across to Netlify for this one.
