### ISSUE TITLE
Custom Cache-Control headers are not being applied

### ISSUE THREAD

**Issue by Becerra45** [aws-amplify/amplify-console#1886]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-2:706262113099:apps/d3c5i43eqy03z6

### Region

us-east-2

### Amplify Console feature

Custom headers

### Describe the bug

I am trying to add Cache-Control headers to our site but have been unsuccessful in doing so. I am currently attempting to add the headers in the aws amplify console -> app settings -> custom headers. I have followed the [instructions](https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html#setting-custom-headers) but still no luck. Below is a copy of what is currently listed:

`customHeaders:
  - pattern: static/js/*.js
    headers:
      - key: Cache-Control
        value: max-age=31536000
  - pattern: static/css/*.css
    headers:
      - key: Cache-Control
        value: max-age=31536000`

If any additional information is needed I would be happy to supply just let me know. Thanks. 

### Expected behavior

Expecting the cache-control headers to be applied to our assets/files.

### Reproduction steps

1. Go to site and take a look at cache headers and you will see our rule specified above is not being applied

**Comment by nimacks** [comment]
@Becerra45  I was able to to setup cache control settings using the following rule
```
customHeaders:
  - pattern: '**/*'
    headers:
      - key: Cache-Control
        value: max-age=80
```
Ensure you're using the right pattern by testing with `**/*` before scoping down to only javascript and CSS files.

**Comment by Becerra45** [comment]
@nimacks Thank you!!! It worked with that general pattern going to try scoping down. Now the only thing I'm wondering is if there is some special rule to ensure the index.html file doesn't get cached? Or if amplify has its own rule around that?

**Comment by kahdojay** [comment]
Hi @Becerra45 these are glob patterns so you could try `!**/index.html` to exclude all index.html files from being matched. Closing this for now but please reopen if it doesn't work.
