### ISSUE TITLE
Domain activation is Failed - CNAME already associated with a different resource

### ISSUE THREAD

**Issue by raulgarciadevop** [aws-amplify/amplify-console#1890]
**App Id**: dgpb3ay8quu2m
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I'm trying to add a custom domain to my aws amplify app, configuration pass but activation fails.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
I recently transferred the custom domain from another aws account to the one I'm currently using.

<img width="1059" alt="Screen Shot 2021-05-28 at 10 08 01 a m" src="https://user-images.githubusercontent.com/33263436/120012336-99bc7400-bf9c-11eb-81da-d3ceb7473733.png">

**Comment by raulgarciadevop** [comment]
I already solved it by deleting a previous cloudfront instance.

**Comment by sujan-s** [comment]
@raulgarciadevop I had the same issue—how long did it take for the issue to resolve? I too have deleted my instance a couple of hours back, but still getting this error.
