### ISSUE TITLE
Stuck at "Fetching Access Logs..." for production site

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-console#1891]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2d6ty1wlg8jch

### Region

us-east-1

### Amplify Console feature

Logging

### Describe the bug

Trying to fetch access logs for our production site, but the thing is stuck at "Fetching access logs.." even when I try to limit timeframe. 

Other (non-production, lower traffic) sites retrieve access logs fine. 

### Expected behavior

Should retrieve access logs

### Reproduction steps

1. Try to retrieve access logs for domain source that has lots of traffic.

**Comment by kahdojay** [comment]
#1004

@hisham are you able to use the CLI workaround to get access logs for shorter timeframes, i.e.

```
aws amplify generate-access-logs --app-id <appId> --domain-name 'example.com' --start-time 2021-01-13T14:00:00Z --end-time 2021-01-13T14:59:59Z
```

**Comment by hisham** [comment]
Yes that worked.

**Comment by kahdojay** [comment]
Ok, I'm closing this for now, please #1004 for this issue/fix
