### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by sairamvj** [aws-amplify/amplify-console#1895]
**App Id**: d3j3mihhmofcoj
**Region**: ap-northeast-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am trying to add a subdomain, but it's failing at Domain activation stage. 

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
1. Verified the CNAME and there are no duplicates. 
<img width="1231" alt="Error Message" src="https://user-images.githubusercontent.com/84446559/120078931-5ca4ce80-c0cf-11eb-8a0d-d5583c51bc84.png">
<img width="1508" alt="Error Message2" src="https://user-images.githubusercontent.com/84446559/120078932-5e6e9200-c0cf-11eb-9f35-637f55221613.png">

**Comment by nimacks** [comment]
Our records indicate that this app has been deleted. Re-open if you're still having issues
