### ISSUE TITLE
Cannot delete my amplify apps 

### ISSUE THREAD

**Issue by thissaleh** [aws-amplify/amplify-console#1898]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify Console feature

Backend builds

### Describe the bug

Hi Team,

I cannot delete my amplify apps as there is issue with backend resources.

Please delete to avoid costs.

Regards,
Saleh 

### Expected behavior

Delete my amplify apps.

### Reproduction steps

Cannot delete my amplify apps.

**Comment by nimacks** [comment]
@thissaleh, can yo provide details in the template above? In order to investigate we will need an appId and Region etc.

**Comment by thissaleh** [comment]
Hi Sam,

Please delete all these apps in my accounts:

Acc ID 835704532157
us-east-1
amplify-identity-broker
Azure-SSO
wildrydes-site
