### ISSUE TITLE
Sub domain Management with new branches

### ISSUE THREAD

**Issue by kontrol-debug** [aws-amplify/amplify-console#190]
**App Id**: arn:aws:amplify:ap-south-1:193864310997:apps/d2po5bkxstg6hw
**Region**: Ap-south1
**Status**: Active

Hi,

I have my app running, Can i have an automatic update to sub domain as a new branch is pushed.

for example ->My domain is : www.happyme.com
As a new branch "test" is created, my build starts at test amplify. But i have to manually set this branch url with domain name. Is there a way out i can automatically set it.

As a new branch is hit , build is created the url is redirected to "test.happyme.com"

Thanks & Regards

**Comment by swaminator** [comment]
There's an active feature request for this here #23

As a workaround you could run a script that uses the AWS CLI to create a domain association https://docs.aws.amazon.com/cli/latest/reference/amplify/create-domain-association.html

**Comment by swaminator** [comment]
Closing this in favor of #23

**Comment by kontrol-debug** [comment]
Hi ,
@swaminator I tried using the solution but it doesn't work for me. The "enableautosubdomain" value remains false . It doesn't work.

**Comment by swaminator** [comment]
@kontrol-debug you can use the AWS CLI to manually create subdomains. 
1. Create an SNS topic (you can do so by choosing App settings > Email notifications)
2. Create a Lambda function to watch for new branches
3. Create a new domain association without using the enableautosubdomain flag.
