### ISSUE TITLE
AWS Amplify App : chunk.js/:1 Failed to load resource: the server responded with a status of 403 ()

### ISSUE THREAD

**Issue by vikramdinator** [aws-amplify/amplify-console#1900]
Hi,

I have created a new react app, and i have the same in AWS Amplify App using manual Drag and Drop of build folder created via npm run build. when i am accessing the site, i am seeing blank page with script error in the console.

**Failed to load resource: the server responded with a status of 403 ()**

I did small research and found some of the people faced the same issue but no proper solution was given in the created posts.

I think, i may need to give some sort of permission, as it tend to look for JS files from inner folder. I dont know how and where to do it. Some reference link, should be helpful.
https://devvscorz.d2oiuesiplptc1.amplifyapp.com/static/js/main.96f63843.chunk.js/

![image](https://user-images.githubusercontent.com/23398259/120225608-2ac47100-c263-11eb-9005-1b41920b244e.png)

Any help would be much appreciated.

**Comment by vikramdinator** [comment]
Region: us-east
App Id: i dont know where to get the app id. i dont see any id in app. i see app ARN

App ARN: arn:aws:amplify:us-east-2:121730437856:apps/d2oiuesiplptc1

**Comment by kahdojay** [comment]
hi @vikramdinator seems like you have a couple script tags that refer to nonexisting assets in your `index.html`, looking at your hosting files those files are not there. Are those two script tags hardcoded?

```
<script src="/static/js/2.c327a5f8.chunk.js"></script>
<script src="/static/js/main.96f63843.chunk.js"></script>
```

As an experiment, are you able to deploy the site successfully using a CI/CD app and providing the same build instructions?

**Comment by vikramdinator** [comment]
Those chunk files were generated from npm run build command. I upload the build folder, which was generated using npm run build command. The same code works in IIS. not here so assuming it would be any sort of permission issue. and the same code works when i upload in AWS Storage bucket. Only not working in Amplify. Do you think, i need to give any permission as it shows 403 error.

**Comment by kahdojay** [comment]
@vikramdinator it appears that those assets weren't deployed. Did the deploy log show deployments of other files, or any error? I don't see a failure on our end yet but will keep investigating.

Can you also try uploading your artifacts as a zip file (the folder contents, not the folder itself)?

https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html

**Comment by vikramdinator** [comment]
@kahdojay Last time also i have tried deploying as a zip file and it was not working. But after your comment i tried same now, and it works. Thank you. I really appreciate your help :)
