### ISSUE TITLE
My Route 53 domain is not connecting to my Amplify Project 

### ISSUE THREAD

**Issue by seanymcelroy** [aws-amplify/amplify-console#1904]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

935621549604:apps/d107b93xyq3nhc

### Region

eu-west-1

### Step

Deployed

### Status

"This site can’t be reached"

### Issue or question

The DNS was working for a few weeks. But when I went to check out my site there, it couldnt be found

### Error message

"This site can’t be reached"
"DNS address could not be found"

### Additional information

Was working correctly when i initially deployed the web app

**Comment by kahdojay** [comment]
@seanymcelroy I only see one domain name configured for that app, and when I look at the NS records it's not pointing to Route 53 nameservers:

```
dig <yourdomain.tld> ns
```

It seems like your domain is managed by a third party registrar, in which case you can follow these steps to complete your Route 53 setup:

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/migrate-dns-domain-in-use.html

Did something change in the registrar settings for the domain?

**Comment by seanymcelroy** [comment]
![image](https://user-images.githubusercontent.com/44436095/120638021-852e1f00-c467-11eb-8640-e2f4204449be.png)

I registered/bought the domain with Route 53. I'm going to try unlink the domain to the app and reconnect it

**Comment by kahdojay** [comment]
@seanymcelroy ok, when you registered the domain with route 53 it automatically created and configured the hosted zone, if it got deleted or the ns records changed for the zone you'll need to reconfigure it

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-replace-hosted-zone.html
