### ISSUE TITLE
Deploy doesn't work and doesn't log anything

### ISSUE THREAD

**Issue by AustinDidierTran** [aws-amplify/amplify-console#1905]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dyo0mu88xmovw

### Region

us-east-2

### Amplify Console feature

Manual deploys

### Describe the bug

When I deploy, it simply fails, and there is not much logs

### Expected behavior

It should deploy well 😅 

### Reproduction steps

Redeploy the current state

### Build Settings

```yaml
Not much, except that I use `next build-amplify` instead of `next build` directly.
```

### Additional information

I've done a workaround to force SSG rather than SSR, as the build did fail under SSR. But now it won't deploy :(

**Comment by kahdojay** [comment]
@AustinDidierTran Hi, this happens when switching from SSR to SSG. We will update our documentation to make this more clear. In the meantime can you attempt to recreate your app as SSG:

https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app

Can you also provide details on the SSR deployment failure - any logs as well as the app/branch/jobId?

**Comment by Athena96** [comment]
Hi @AustinDidierTran it looks like the build was not completing successfully (and affecting the deploy) because the branch `develop` was being deleted and could not be found. This should be resolved if you connect a new branch. Resolving, feel free to re-open if you continue to face this issue
