### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by deniska83** [aws-amplify/amplify-console#1906]
**App Id**: d16r1udv6fx3ai
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Getting Activation error after adding CNAMEs and CAA records. 

**Error message**
he status of this certificate request is "Failed". One or more domain names have failed validation due to a Certificate Authority Authentication error.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by nimacks** [comment]
This domain is now available m***m**.io. Reopen if you have any further issues
