### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by pankajsoni19** [aws-amplify/amplify-console#1907]
**App Id**: d2xp91rpokz5da
**Region**: ap-south-1
**Step**: Domain activation
**Status**: Failed

I am deploying 1 repos with 2 branches in 2 AWS amplify apps

1st [ this succedded ] 
x-prod.mydomain.com
x-staging.mydomain.com

-
2nd 
y-prod.mydomain.com
y-staging.mydomain.com

I am constantly having this issue

```
We had issues connecting your custom domain: mydomain.com. Please visit the Domain Management page for more information.
```

**Comment by pankajsoni19** [comment]
Error message is 

```
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
```

**Comment by pankajsoni19** [comment]
the solution according is here

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error

Its a live production site. What would be an alternative?

**Comment by siegerts** [comment]
Hi @pankajsoni19 , it seems that your domain is already associated with a domain (1st example). Because of that, you can't add another app to that domain. It's not possible to share that domain across separate Amplify apps.

**Comment by pankajsoni19** [comment]
both cloudfront and amplify are products of aws. so this transfer should work out of the box.
what i ended up doing was setting up entire environment on aws alb + 2 instances

I migrated from cloudfront to alb to amplify.

For production sites, this was a nightmare migration.

**Comment by pankajsoni19** [comment]
@prakharrke tagged
