### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by ihor1010** [aws-amplify/amplify-console#1908]
**App Id**: d1zfhwu6p9kbep
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
domain name: from godday
assigned cloudfront first. Here now, I want to connect amplify app.
Let me know how to roll back initially and go on setting domain name from start

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by nimacks** [comment]
This domain is now available. s-----i----.com. Reopen if you have any further issues
