### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Devichand1** [aws-amplify/amplify-console#1909]
**App Id**: d2bfm2vq7qmpea
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by nimacks** [comment]
@Devichand1 can you provide information about what happened when you tried to add a custom domain? Is your domain hosted in Route53 or an external DNS provider?

**Comment by nimacks** [comment]
@Devichand1, it looks like your app no longer exists. Re-open if you continue to have issues
