### ISSUE TITLE
Auto Sub domain is not getting enabled

### ISSUE THREAD

**Issue by kontrol-debug** [aws-amplify/amplify-console#191]
Hi,
I am using aws ampliy through command line and was trying to use "create-domain-association" feature.
I am using it to enable auto sub domain association but it remains false. Please help

Below is the output snippet :

"domainName": "abc.com",
 "enableAutoSubDomain": false,

**Comment by swaminator** [comment]
@kontrol-debug we do not have that feature available yet. I realize that its causing some confusion since its in our SDK docs.

**Comment by swaminator** [comment]
@kontrol-debug you can use the AWS CLI to manually create subdomains.

Create an SNS topic (you can do so by choosing App settings > Email notifications)
Create a Lambda function to watch for new branches
Create a new domain association without using the enableautosubdomain flag.

**Comment by kontrol-debug** [comment]
Hi @swaminator,

I tried your given steps but my new branch is still connected to amplifyapp.com domain. It doesnt gets redirected to <branchname>.mydomain.com
