### ISSUE TITLE
Access Denied Error when running the `amplifyPush --simple` is run on CD

### ISSUE THREAD

**Issue by Arash-Afshar** [aws-amplify/amplify-console#1912]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d24rbpko4p4hk

### Region

us-west-2

### Amplify Console feature

Backend builds, Build settings

### Describe the bug

I followed the tutorial (https://docs.amplify.aws/start/getting-started/setup/q/integration/react#install-amplify-libraries) and created a new user and gave it AdministratorAccess. The environment is created successfully. Next, I logged into amplify console and went to the "frontend section". I connected the github branch and chose the option to build the backend on every push (this added `amplifyPush --simple`) to the yaml file.

Now, when I push a commit or click on deploy, the backend build fails with the following error:

```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2021-06-02T16:38:51.620Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2021-06-02T16:38:57.676Z [WARNING]: - Initializing your environment: staging
2021-06-02T16:38:57.676Z [WARNING]: - Initializing your environment: staging
2021-06-02T16:38:57.739Z [INFO]: [31mCould not initialize 'staging': Access Denied[39m
2021-06-02T16:38:57.755Z [ERROR]: !!! Build failed
2021-06-02T16:38:57.755Z [ERROR]: !!! Non-Zero Exit Code detected
2021-06-02T16:38:57.755Z [INFO]: # Starting environment caching...
2021-06-02T16:38:57.756Z [INFO]: # Environment caching completed
```

### Expected behavior

Since the user has admin access, I expect this to pass. Moreover, the error is not helpful as I don't know what is the access issue.

### Reproduction steps

Log in to amplify console and click on redeploy this version.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by Arash-Afshar** [comment]
I am going to remove the `amplifyPush` for meth yaml file for now. If you want to test it out let me know and I'll add it back.

**Comment by Arash-Afshar** [comment]
Removing it caused a different issue with aws-exports. So I added back the amplifyPush and kicked another build. Can you please look into what kind of access I need to give it?

**Comment by kahdojay** [comment]
@Arash-Afshar can you double check that the IAM role that Amplify service is using is the one you gave AdministratorAccess - you can confirm the app's IAM role arn in the Amplify Console under General Settings for the app under "Service role". I suspect this is the cause but let me know if that role already has the admin policy attached to it.

**Comment by Arash-Afshar** [comment]
Ah right! Thanks @kahdojay. I only gave the access to my user and not the service role. The issue is resolved now.
