### ISSUE TITLE
Unable to find Access Control settings per Restricting Access user guide

### ISSUE THREAD

**Issue by bharloe** [aws-amplify/amplify-console#1916]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1uo6cazksxjze

### Region

us-east-2

### Amplify Console feature

Access control

### Describe the bug

I cannot find the "Access Control" setting for adding password protection in the Amplify console. I was able to add password protection, but only by clicking the link in the 5 step start up checklist for new apps. Now that that is completed and it is gone I cannot find any way to get to Access control page via the Amplify console. 

### Expected behavior

I expected it to work as described in the Console User Guide page ["Restricting Access"](https://docs.aws.amazon.com/amplify/latest/userguide/access-control.html):

> 1. Sign in to the AWS Management Console and open the Amplify Console.
> 2. Choose the app you want to set feature branch passwords on.
> 3. In the navigation pane, choose App settings, and then choose Access control.
> 4. In the Access control settings section, choose Manage access.

When I follow these steps, I get to step 3. I can see the App settings drop-down, but there is no option that says "Access control": 

![image](https://user-images.githubusercontent.com/14279964/120574016-60886780-c3d3-11eb-980c-6e05907c6437.png)

I tried my best to search through each settings page to try to find it but I wasn't able. Currently I can only access this setting by re-opening the URL that I saved from the starter checklist.

### Reproduction steps

Attempt these steps from the ["Restricting Access"](https://docs.aws.amazon.com/amplify/latest/userguide/access-control.html) guide:
> 1. Sign in to the AWS Management Console and open the Amplify Console.
> 2. Choose the app you want to set feature branch passwords on.
> 3. In the navigation pane, choose App settings, and then choose Access control.
> 4. In the Access control settings section, choose Manage access.

**Comment by kahdojay** [comment]
Hi, the app is an SSR app - access control is not yet supported for SSR apps - please track the feature in #1857 

We're also updating the docs to make this more clear.

Closing this in favor of #1857

**Comment by bharloe** [comment]
@kahdojay Thanks for the info. Just so you know I was able to add password protection on this app, which is SSR as you note, when working through the 5 step starter guide. One of the steps instructed me to add it. I did add it and now it is enabled, but if I understand correctly I would have no way of disabling it if I wanted to, and I have no way of managing the settings (Like username and password). I don't want to change it so it doesn't matter much for me, but this seems to me like it still represents a bug in the UI.

**Comment by kahdojay** [comment]
Thanks for the additional detail, I missed that you had it already enabled. It shouldn't be possible to create net new SSR apps with access control enabled, I'm assuming yours was created before we made that change.

If you do end up needing to make changes, you should be able to use [update-app](https://docs.aws.amazon.com/cli/latest/reference/amplify/update-app.html) or [update-branch](https://docs.aws.amazon.com/cli/latest/reference/amplify/update-branch.html) to change your settings, if you run into issues or have questions please re-open this issue.
