### ISSUE TITLE
Disable Backend Deployment when build is triggered 

### ISSUE THREAD

**Issue by ParulSharma2622** [aws-amplify/amplify-console#1918]
Hi, 

I have a use case: 

We have 2 instances : A and B.
We always add any new feature or feature extensions in instance B.
Once everything is done and tested then we merge it with instance A.

Suppose, I am working on a new feature on instance B and this new feature requires data model changes. We updated the data model from amplify admin, deployed and take it's pull on our local system using amplify pull command.
Meanwhile, I have to fix an urgent issue on instance A, so I extended a branch C from A and merged C branch to A after fixing the issue. 
But, all the data model changes vanished when a new build is triggered on instance A. Reason being, updated backend schema  code was there in branch B but not A and C. 
That's why, I want to disable backend deployment on each build trigger. If there's any other way out, please let me know.

Here's the app id : d18qtdhf6c7z65
Region: ap-southeast-2 (Sydney)

Thanks In Advance.!!!

**Comment by kahdojay** [comment]
Hi @ParulSharma2622 thanks for your feedback, we're working on adding support for this use case, don't have an ETA to share at the moment but please stay tuned

**Comment by swaminator** [comment]
@ParulSharma2622 we added support for conditional backend builds: https://docs.aws.amazon.com/amplify/latest/userguide/conditional-backends.html
