### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by tscole** [aws-amplify/amplify-console#192]
**App Id**: d2z0aapvx3jong
**Region**: eu-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Can not add custom domain to my app

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by swaminator** [comment]
@tscole have you checked out this doc: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

**Comment by tscole** [comment]
I have read and followed that. It is still not working. Now I am getting a different error message:
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

I have checked my DNS. There aren't CNAME records

**Comment by tscole** [comment]
I've managed to fix it by completely deleting the domain and starting again
