### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nav' of undefined

### ISSUE THREAD

**Issue by agueric** [aws-amplify/amplify-console#1920]
When trying to access the Amplify Console from AWS website i get a white screen:
On the dev console i see a bunch of errors starting with:
`Uncaught TypeError: Cannot read property 'nav' of undefined`

And some more similar to this:
`Refused to connect to 'https://console.aws.amazon.com/feedback/custsat/1/popquestion?locale=es&service=amplify&region=us-east-2' because it violates the following Content Security Policy directive: "connect-src https://us-east-2.console.aws.amazon.com/amplify/ https://bitbucket.org/ https://*.ccs.amazonaws.com https://aws-amplify-prod-us-east-2-access-logs.s3.us-east-2.amazonaws.com/ https://aws-amplify-prod-us-east-2-artifacts.s3.us-east-2.amazonaws.com/ https://e7auv6no3g.execute-api.us-east-1.amazonaws.com/ https://*.analytics.console.aws.a2z.com https://github.com/ https://phd.aws.amazon.com https://console.aws.amazon.com/amplify/ https://x1wkkmql32.execute-api.us-east-2.amazonaws.com/ https://gitlab.com/ https://console.aws.amazon.com/feedback/custsat https://ccs.amazonaws.com https://api.bitbucket.org/ https://api.github.com/ https://us-east-2.prod.signer.console-api.aws.amazon.com".`

**Comment by aws-amplify-console** [comment]
@agueric are you still seeing this? The Amplify console loads for me in us-east-2 and other regions as well. Is there a specific page this happens or some way to repro?

**Comment by kahdojay** [comment]
@agueric are you still seeing this? The Amplify console loads for me in us-east-2 and other regions as well. Is there a specific page this happens or some way to repro?

**Comment by agueric** [comment]
@kahdojay i'm still seeing the same problem. I've had it since at least 3 weeks. I thought it was some temporal problem but still seeing the same errors.

![Captura de Pantalla 2021-06-04 a la(s) 13 34 04](https://user-images.githubusercontent.com/3620329/120847812-9a737e00-c539-11eb-938b-2c415ab3159c.png)

**Comment by kahdojay** [comment]
@agueric Thanks for reporting. Are you seeing the issue in any service consoles other than Amplify? Just trying to narrow down the issue.

**Comment by agueric** [comment]
No, actually if I visit another region I see the Start page. But on this one we do have a couple Apps running. I've tried another browser but still the same. 
Should I try Incognito mode or some other test?

**Comment by kahdojay** [comment]
@agueric yes if you could confirm whether this happens in multiple browsers/incognito, and whether other service consoles are having the same issue in the same region (for example Rekognition, Batch, etc)

**Comment by agueric** [comment]
I've tested on an incognito browser and **it did work**. Using it for now. On other services there is not such problem. 
I guess there's something wrong with cookies, cache, or something similar :/

**Comment by kahdojay** [comment]
Ok, we'll need to look into this further, I'm not able to reproduce the issue and haven't heard of other customers experiencing this yet but we will take a look. If you have a consistent repro we can follow let us know.

**Comment by hloriana** [comment]
Hi @agueric are you still running into this issue or were you able to resolve it?

**Comment by agueric** [comment]
Hi.

I resolved it. It had to do with something in the browser and session. I
ended up clearing cookies and local storage on Chrome and it worked.

**Comment by hloriana** [comment]
@agueric Awesome. Thanks for reaching out and if you have any more questions or feedback, feel free to submit another issue. Thanks 🙂
