### ISSUE TITLE
Dose Amplify need to be instructed to install fronted dependency when it builds?

### ISSUE THREAD

**Issue by peter-wd-1** [aws-amplify/amplify-console#1921]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Amplify frontend build

**Amplify CLI Version** 
4.51.2

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
I'm trying to integrate cognito into react app by following this [documentation](https://aws.amazon.com/ko/getting-started/hands-on/build-react-app-amplify-graphql/module-three/)

**Provide additional details e.g. code snippets**
I added aws-amplify package by `yarn add aws-amplify @aws-amplify/ui-react` and I pushed it to amplify console. Then I get 
same error on the frontend build like in [this link](https://forums.aws.amazon.com/thread.jspa?threadID=334433).
So I've added the next command under `preBuild` phase. And It works fine. Now I don't understand why it can't add these packages since it has package.json with all the dependency information.

```
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
        - yarn add aws-amplify @aws-amplify/ui-react
```

**Comment by yuth** [comment]
This looks like issue related to Amplify Console and the console team is better equipped to help you with this. Transferring it to the Console repository

**Comment by kahdojay** [comment]
@peter-wd-1 when you ran your `yarn add` command your package.json should've been updated with the new dependency. Did you push this update to your git repository? Amplify Console pulls your package.json from your repository at build time so it would need to be in place before triggering a build.

**Comment by behrooziAWS** [comment]
Resolving, I searched the logs and looks like you were able to build if your app was dt48h6lwdzstp.
