### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by jaume-unimedia** [aws-amplify/amplify-console#1929]
**App Id**: d3o4o6fxrn7pjj
**Region**: eu-west-1
**Step**: SSL configuration
**Status**: Running

**Issue/question**
We are stuck on the SSL Configuration step

**Error message**
No error message 

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
I am following these instructions here as it's taken longer than 8hrs

We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue in our GitHub issue tracker.

**Comment by nimacks** [comment]
Our records indicate that this domain is now available. c******.media. Re-open if you run into any further issues.
