### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by CoinvestingDeFi** [aws-amplify/amplify-console#1932]
**App Id**: d2o9p8pjuzszop
**Region**: us-east-2
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue in our GitHub issue tracker.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
The last update of the DNS record took place on 06/07/21 at 4:18 pm.
No error message displayed, just the issue described above.

**Comment by nimacks** [comment]
Our records indicate this app no longer exists. Please re-open if you encounter any further issues with an Amplify App.
