### ISSUE TITLE
503 ERROR The request could not be satisfied.

### ISSUE THREAD

**Issue by hecool108** [aws-amplify/amplify-console#1935]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3e4u1u0b8ejac

### Region

us-east-1

### Step

Visit https://master.d3e4u1u0b8ejac.amplifyapp.com

### Status

Failed

### Issue or question

Since yesterday my app could be deployed, but just couldn't be visited. The error message is listed below.

### Error message

503 ERROR
The request could not be satisfied.
The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: F0SkirWMPKKGZZVhIRDRzSYDrNLs_qLw2TT9SQdZzSPQdHFZC0coBw==

### Additional information

I have no idea what I've done with the lambda function, which I haven't put my hands on it.

**Comment by tmbtech** [comment]
> Downgrading Next to 10.0.5 and setting webpack5: false in the next.config.js did the trick.

source: https://github.com/aws-amplify/amplify-console/issues/412#issuecomment-851704285

This also worked for me.

**Comment by hecool108** [comment]
> > Downgrading Next to 10.0.5 and setting webpack5: false in the next.config.js did the trick.
> 
> source: [#412 (comment)](https://github.com/aws-amplify/amplify-console/issues/412#issuecomment-851704285)
> 
> This also worked for me.

Oh, man !! You're my Super Hero!! It works. Danke!

**Comment by sohammondal** [comment]
I downgraded to v11.1.3 and set webpack5 to false and then it worked for me.
