### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by fullstackfool** [aws-amplify/amplify-console#1936]
**App Id**: d3deaao4c2twkg
**Region**: eu-west-2
**Step**: SSL configuration
**Status**: Running

**Issue/question**
SSL configuration has taken longer than 8 hrs.

**Error message**
We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue in our GitHub issue tracker.

**Comment by tmbtech** [comment]
>Downgrading Next to 10.0.5 and setting webpack5: false in the next.config.js did the trick.

source: https://github.com/aws-amplify/amplify-console/issues/412#issuecomment-851704285

This worked for me.

**Comment by fullstackfool** [comment]
Not using Nuxt, additionally, this is a deployment that has been successfully done on several sub-domains. Now on the root it is failing.

**Comment by fullstackfool** [comment]
To clarify the setup:
- Root account owns the domain name in 53.
- Member account has a hosted zone
- The NS details of the member hosted zone have been copied into an NS record on the root hosted zone (for said domain)
- Member amplify app has the custom domain pointing to the member hosted zone.

I've since removed everything and started from scratch, checking each stage, and it STILL isn't completing the SSL configuration.

If I look at the records for the member hosted zone I can see that Amplify has added several:
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/14146557/121503923-6e447b00-c9d9-11eb-857e-9289ce6d7702.png">

**Comment by nimacks** [comment]
According to our records, this domain is now available. app.********-i*******.com
