### ISSUE TITLE
Next.js Incremental Server Rendering (ISR) support

### ISSUE THREAD

**Issue by andrewbtp** [aws-amplify/amplify-console#1939]
**Is your feature request related to a problem? Please describe.**
For SEO reasons, we have certain pages rendering through SSR. The problem is this can take ~8 seconds on a cold start for the Lambda function, not a great UX. ISR solves this with near-immediate retrieval and by providing up-to-date-enough data for SEO.

**Describe the solution you'd like**
I'd like to implement [ISR](https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration) in my Next.js app and just have it work :)

**Additional context**
IIRC the intent is for Amplify to be open-source, but it seems like the deployment code related to Next.js is not publicly available. This is a round-about way of saying I'd be open to potentially contributing this if it's a few days effort and available via open-source.

**Comment by andrewbtp** [comment]
Yep, SSR works fine! Looking forward to the update, we're considering moving our front-end off Amplify and this feature alone is really the driving motivation.

**Comment by rababahmed** [comment]
@brnmye could you possibly provide an ETA for this feature? This is a blocker for us migrating to Amplify.

**Comment by Athena96** [comment]
Hi all, we've recently made improvements to our SSR error logging and have added support for Next.js 10/11 (including ISR!)
Please follow this guide to upgrade to our latest support of Next.js: https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#update-app-nextjs-version

**Comment by SatadruBhattacharjee** [comment]
Still the ISR is not working with nextjs 11

**Comment by tsfahmad** [comment]
Facing same issue. ISR not working. Any update on this please currently it is a blocker for us.

**Comment by yoongti** [comment]
It's working for us, but the regeneration(update) is very inconsistent. a `revalidate: 10`(10 sec) could take minutes before seeing the update
