### ISSUE TITLE
Source Repository says "master" instead of "main"

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-console#1940]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dsc8vruff37bh

### Region

us-east-2

### Amplify Console feature

Not applicable

### Describe the bug

The **Production branch** is `main`, but the **Source Repository** links to `master`.

This repo does not have a `master` branch, only `main`, so I'm not sure where this value came from:

> ![Screen Shot 2021-06-09 at 3 13 32 PM](https://user-images.githubusercontent.com/15182/121423634-56abba80-c925-11eb-8567-d40cc42c5805.png)

### Expected behavior

Use **Production branch** value.

### Reproduction steps

1. View General settings for your app connected to a GitHub repo's `main` branch:

    https://us-east-2.console.aws.amazon.com/amplify/home?region=us-east-2#/dsc8vruff37bh/settings/general

**Comment by brnmye** [comment]
Hello, is this effecting your deployments? I see a recent successful build, but I am not seeing any jobs

**Comment by ericclemmons** [comment]
@brnmye It appears to be largely cosmetic, but makes me wonder if my Production branch value were to change, would the link above work correctly?  I don't know where the `master` value came from.

**Comment by sliedig** [comment]
I'm having the same issue. The URL that is defined for the Source repository in the App details is appending `browse/refs/heads/master?region={REGION}`, even though I haven't got a master branch in my repo. Clicking on the hyperlink gives me a 

```
CommitDoesNotExistException
Could not find commit refs/heads/master
```
Its not affecting my builds but it is confusing.

**Comment by calavera** [comment]
I think this is a duplicated of https://github.com/aws-amplify/amplify-console/issues/1520 I'm going to close this issue to centralize all the information in one single place.
