### ISSUE TITLE
How to execute a "yarn start" without blocking the deployment?

### ISSUE THREAD

**Issue by BoarSwap** [aws-amplify/amplify-console#1942]
**Please describe which feature you have a question about?**

Hi everyone,
I am trying to deploy a project with Amplify, and the project needs a direct "yarn start" to work properly.
Problem, the yarn start is blocking the build process (obviously). Even in a post-build command.
Because of that, the project is never deployed, and the build times-out.

If I delete the "yarn start" command, Amplify can build and deploy my project, but the project doesn't work.

Thanks for your help

**Comment by victorccccc** [comment]
Hi, can you specify the use case for this in build phase? What's script you are running in the "start" property of `package.json` ?

**Comment by ganipcanot** [comment]
Closing due to age - please reopen or create a new ticket if you are still having issues.
