### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by KalvinWei** [aws-amplify/amplify-console#1949]
Tried to deploy a create-react-app on amplify, but it seemed amplify did not build the artefacts successfully due to 'build' folder nonexistence. But I had `npm run build` in the script.

My project structure:
<img width="381" alt="image" src="https://user-images.githubusercontent.com/65690659/121810296-5ceabf80-ccb4-11eb-8b01-0716cd7b9c1d.png">

Script:
<img width="521" alt="image" src="https://user-images.githubusercontent.com/65690659/121810304-6b38db80-ccb4-11eb-88de-a5bcb327bf0d.png">

Error:
<img width="894" alt="image" src="https://user-images.githubusercontent.com/65690659/121810320-7be95180-ccb4-11eb-82be-3bb0ab9c9142.png">

Where did I make mistakes?
The Region is `US-west-1`

**Comment by KalvinWei** [comment]
> Hi 👋, thanks for opening! While we look into this...
> 
> If this issue is related to custom domains, be sure to check the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html) to see if that helps. Also, there is a more general [troubleshooting FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md) that may be helpful for other questions.
> 
> Lastly, please make sure you've specified the `App ID` and `Region` in the issue!

Hi, there.
What is

**Comment by KalvinWei** [comment]
> Hi 👋, thanks for opening! While we look into this...
> 
> If this issue is related to custom domains, be sure to check the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html) to see if that helps. Also, there is a more general [troubleshooting FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md) that may be helpful for other questions.
> 
> Lastly, please make sure you've specified the `App ID` and `Region` in the issue!

Hi, there. I don't think your reply is regarding my question since there seems nothing related to **domains**.  Also, what is **App ID** and where can I find it?

**Comment by brnmye** [comment]
Hello, you can find your appId by going to your amplify apps selecting the specific app giving you issues, then going to general on the left side. There you should see an appArn on the center-left side of the screen. The appId is after apps/

**Comment by behrooziAWS** [comment]
I was able to find your appId in the logs.  Seems like the error is that you've accidentally set your baseDirectory to `.frontend/build` instead of `frontend/build` in your amplify.yml.  You don't have a folder named `.frontend` but do have one named `frontend`.
