### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Mehdi-111** [aws-amplify/amplify-console#1950]
**App Id**: d1qt84e06r2r5k
**Region**: eu-west-3
**Step**: SSL configuration
**Status**: Running

**Issue/question**
i'am stuck in this step : "We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue" for more than 24h and i don't know what i can do next.

**Comment by nimacks** [comment]
According to our records, this app no longer exists. Re-open  if you're still having issues.
