### ISSUE TITLE
PR previews don't use branch's amplify.yml

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-console#1955]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).

    This may be related to #1880 and #1134

- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3inl0muob87le

### Region

us-east-2

### Amplify Console feature

Build settings, Previews

### Describe the bug

When testing `amplify.yml` changes in a PR, those changes aren't used in the Build step – it appears that the `amplify.yml` from the `main` branch is instead.

### Expected behavior

I expect that I can test changes to `amplify.yml` in a PR prior to merging to prevent broken production deployments on `main`.

### Reproduction steps

1. Have `main` with an `amplify.yml`
2. In a new PR, update `amplify.yml` with some new build steps (e.g. `nvm install`)
3. Watch Amplify Console's GitHub Check progress and notice how the new build steps aren't executed
4. `git checkout main && git cherry-pick <your commit that introduced new steps> && git push origin main` to add these changes to `main`
5. `git checkout - && git merge main && git push` to add a new (redundant) commit to the PR branch & push it
6. Notice how the PR preview runs the new build steps – because it's on `main` now?

### Additional information

- https://us-east-2.console.aws.amazon.com/amplify/home?region=us-east-2#/d3inl0muob87le/pr-43/3

**Comment by lynnfaraday** [comment]
This is a problem for us too. We need to be able to preview and test changes to the build config before merging, which is impossible if the builds always use the main version of amplify.yml and not the branched version.

**Comment by swaminator** [comment]
@ericclemmons this sounds like a bug. Your PR should be using the `amplify.yml` checked into your repo.

**Comment by ganipcanot** [comment]
A fix for this has been checked into all waves
