### ISSUE TITLE
Failed to add a custom subdomain to my Amplify app

### ISSUE THREAD

**Issue by brayann** [aws-amplify/amplify-console#1958]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d24dy7stqrcc87

### Region

us-east-1

### Step

Subdomain activation

### Status

Failed

### Issue or question

Hi. I am getting this error (Update domain association failed) when trying to add a subdomain to my Amplify application. When inspecting the request from the console it returns the following response: "One or more of the CNAMEs you provided are already associated with a different resource. (Service: AmazonCloudFront; Status Code: 409; Error Code: CNAMEAlreadyExists; Request ID: 852d6eae-a427-4013-819f-7a4ddf1822cd; Proxy: null)"
However I checked and I don't have any other CloudFront distributions or anything like that. Any ideas how to resolve? it is specifically for the "app" subdomain, I'm able to set to any other value, but ofc I want to use the app one. 
Thanks!

### Error message

Update domain association failed, One or more of the CNAMEs you provided are already associated with a different resource. (Service: AmazonCloudFront; Status Code: 409; Error Code: CNAMEAlreadyExists; Request ID: 852d6eae-a427-4013-819f-7a4ddf1822cd; Proxy: null)

**Comment by ferdingler** [comment]
Hi @brayann, I'm sorry you had issues creating your custom domain. We have recently improved our error messaging on the CNAMEAlreadyExistException to give customers better information on how to recover from it. This usually means one of these things: 

1) You have already used the same custom domain in another Amplify App in another region/account. 
2) You are using this domain in another service: LightSail or API Gateway. 
3) Your domain has an old CNAME record that points to a cloudfront.net URL from a previous Amplify App. 

Feel free to re-add the custom domain and you should get better information on what's going on. Thanks for reporting!

**Comment by brayann** [comment]
Hey @ferdingler thanks for your help, however the message says it's on Cloudfront but I checked and there's nothing in there.

<img width="1403" alt="Screen Shot 2021-10-04 at 14 29 37" src="https://user-images.githubusercontent.com/253673/135897652-65d6100a-4cb1-47e9-baf4-c4188199cb73.png">

<img width="1584" alt="Screen Shot 2021-10-04 at 14 28 39" src="https://user-images.githubusercontent.com/253673/135897671-da4b0c39-7d10-4ab8-a555-2d15fdd1e24d.png">
