### ISSUE TITLE
amplifyPush doesn't work

### ISSUE THREAD

**Issue by hoangnguyencong-agilityio** [aws-amplify/amplify-console#1963]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2spojpha93fpk

### Region

us-east-1

### Amplify Console feature

Backend builds, Environment variables, Monorepo

### Describe the bug

I used amplifyPush command for Amplify CI/CD.
It worked before. However, this didn't work anymore.

My env variables:

AMPLIFY_NATIVECLIENT_ID
AMPLIFY_USERPOOL_ID
AMPLIFY_WEBCLIENT_ID

Below are error messages:
```
2021-06-16T03:02:40.626Z [INFO]: # Initializing new Amplify environment: dev (amplify init)
2021-06-16T03:02:43.078Z [INFO]: �[33mNote: It is recommended to run this command from the root of your app directory�[39m
2021-06-16T03:02:50.906Z [WARNING]: - Initializing your environment: dev
2021-06-16T03:02:52.964Z [WARNING]: ✔ Initialized provider successfully.
2021-06-16T03:02:53.194Z [WARNING]: ✖ There was an error initializing your environment.
2021-06-16T03:02:53.209Z [INFO]: �[0mError: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId
```

### Expected behavior

amplifyPush should work with correct env variables

### Reproduction steps

1. Init amplify app
2. Config Amplify CI/CD
3. Connect to Github
4. Add override AWS CLI version to 4.46.1
5. Config ENV variables: AMPLIFY_NATIVECLIENT_ID, AMPLIFY_USERPOOL_ID, AMPLIFY_WEBCLIENT_ID
6. Trigger build

### Build Settings

```yaml
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - amplifyPush -e $USER_BRANCH --simple
    frontend:
      phases:
        build:
          commands: []
      artifacts:
        baseDirectory: /
        files:
          - '**/*'
      cache:
        paths: []
    appRoot: api
```

**Comment by swaminator** [comment]
Can you update your script to use `amplifyPush --simple` @hoangnguyencong-agilityio

**Comment by hoangnguyencong-agilityio** [comment]
Yes, I can. @swaminator.

**Comment by adi518** [comment]
It still doesn't work. It doesn't pass the google input params correctly:

```sh
auth headless is missing the following inputParams googleClientId
```

**Comment by wvidana** [comment]
@hoangnguyencong-agilityio did amplifyPush worked? For me I had to add the script to my repo and edit it to make amplifyPush able to read the env vars `AMPLIFY_USERPOOL_ID`, `AMPLIFY_WEBCLIENT_ID`, `AMPLIFY_NATIVECLIENT_ID`, `AMPLIFY_IDENTITYPOOL_ID` from `amplify.yml`

https://github.com/aws-amplify/amplify-console/issues/2039

------

Also manually modifying the script resulted in the CI/CD to not apply changes when pushed, so I assume the script they have on master is not currently in use by the console, @swaminator any idea?

https://github.com/aws-amplify/amplify-console/issues/2075

**Comment by hoangnguyencong-agilityio** [comment]
@wvidana thanks for the message, it worked for me since I have added my self script instead of.
