### ISSUE TITLE
Frontend builds failing

### ISSUE THREAD

**Issue by mansiva** [aws-amplify/amplify-console#1966]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dfpscjrn83sez

### Region

us-east-1

### Amplify Console feature

Backend builds, Custom builds

### Describe the bug

Since yesterday our frontend builds have stopped working because of this error related to fetching backend:
```                                 ## Checking for associated backend environment...
                                 ## Backend environment association found
2021-06-15T18:59:10.377Z [INFO]: 
2021-06-15T18:59:10.379Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
2021-06-15T18:59:10.624Z [INFO]: Amplify AppID found: dfpscjrn83sez. Amplify App name is: onmo
2021-06-15T18:59:10.686Z [INFO]: Backend environment dev found in Amplify Console app: onmo
2021-06-15T18:59:11.492Z [INFO]: 
2021-06-15T18:59:11.494Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2021-06-15T18:59:12.194Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2021-06-15T18:59:12.231Z [WARNING]: ✖ There was an error initializing your environment.
2021-06-15T18:59:12.250Z [INFO]: Failed to pull the backend.
2021-06-15T18:59:12.252Z [INFO]: auth headless is missing the following inputParams googleClientId, facebookAppId
2021-06-15T18:59:12.280Z [INFO]: Error: auth headless is missing the following inputParams googleClientId, facebookAppId
                                 at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/index.js:61:15)
                                 at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/index.js:230:28
                                 at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
                                 at runMicrotasks (<anonymous>)
                                 at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-06-15T18:59:12.295Z [ERROR]: !!! Build failed
2021-06-15T18:59:12.295Z [ERROR]: !!! Non-Zero Exit Code detected
2021-06-15T18:59:12.295Z [INFO]: # Starting environment caching...
2021-06-15T18:59:12.295Z [INFO]: # Uploading environment cache artifact...
2021-06-15T18:59:12.366Z [INFO]: # Environment caching completed
Terminating logging...```

However in our build settings we don't include building backend (as shown below).

This was working fine until yesterday, no significant changes have been made on our end for either frontend or backend

### Expected behavior

Building frontend should be independent of backend if no backend build steps have been specified in build settings.

### Reproduction steps

Using our app, just redeploying frontend version or deployment through CI/CD fails.

### Build Settings

```yaml
version: 1
env:
  variables:
    REACT_APP_ENV: $USER_BRANCH
    REACT_APP_BUILD: $AWS_JOB_ID
    REACT_APP_FACEBOOK_CLIENT_ID: $AMPLIFY_FACEBOOK_CLIENT_ID
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by cslogan-red** [comment]
Sorry to hear @mansiva and @thedgbrt, if you refresh the page, on the branch list page for your app in the Console, there should be a blue `(Edit)` link near the branch name, whether or not it shows associated with a backend environment.

<img width="412" alt="Screen Shot 2021-06-16 at 8 51 13 AM" src="https://user-images.githubusercontent.com/1307688/122252859-848e8300-ce80-11eb-8687-be7c8629680e.png">

Click the Edit link and on the modal that appears, **uncheck** the checkbox for "Enable full-stack continuous deployments (CI/CD)" and click Save and then redeploy your latest version? We have a docs update being published tomorrow that covers this release. In short, we'll now always attempt to pull your frontend apps associated backend resources in during a build so that you no longer need to check in an `amplify` folder in your repo, we do this regardless of having a backend section in your build spec as we're finding many customers are having a poor experience with failing full-stack builds due to not having a local `amplify` folder checked in, or not setting up a backend build section in their build specs, neither of which will be required anymore (but won't hurt if still checked in). **Unchecking** the "Enable full-stack continuous deployments (CI/CD)" checkbox ensures that we only ever attempt to run an `amplify pull` on that backend, and it _should_ be enough to get you unblocked, but there may be a scenario or two with headless auth that has other nuances, sorry for the inconvenience!

**Comment by thedgbrt** [comment]
@cslogan-red thank you for the quick response. I just tried it and the redeploy still tries to build the backend. Same with someone else from the discord server. Is there some missing part of the explanation? My app id is `d19neubxmmsnaf` and I'm trying to deploy the master branch. Please be careful I have a line business running in prod.

**Comment by mgarabedian** [comment]
I am also having this issue. Very frustrating. Isn't the point of not declaring the backend in the amplify.yml file so it doesn't deploy? I just tried the above suggestion, but deployment still failed.

```
## Checking for associated backend environment
## Backend environment association found
```

**Comment by mansiva** [comment]
Thanks for the quick reply @cslogan-red , however I already tried that and to no avail:
![image](https://user-images.githubusercontent.com/1873405/122254705-5cf8e400-ce9b-11eb-97c1-d9e7b6d4d9c4.png)

It still gives the same error message when trying to build the frontend. In our case we do not have an amplify folder as part of our frontend since we build the backend separately.

On another note we have another frontend app (d3go8s777z98bv) that is using the same amplify backend (same aws-exports file) but isn't directly linked to the backend through the amplify console and this one however is building fine. So the problem is probably due to the fact that the frontend is still linked to the backend even if the checkbox above is unchecked, either the checkbox isn't doing anything or something else is still trying to pull the backend.

I suppose a solution would be to create a new app that will use the same frontend repo, but I'd rather avoid going through all that.

**Comment by thedgbrt** [comment]
Creating a new app is not an option when you have live paying users, custom domain, etc.

**Comment by mansiva** [comment]
it should still be possible if you're only using amplify console to build the frontend. Creating a new app for the frontend (not the backend) and using the same repo and aws-exports for the frontend, then it should just be a matter of replacing the domain to point to the new one... but it's definitely not an ideal solution. I hope they can fix quickly since we're also live and blocked from doing any deployments. Fortunately we didn't have anything planned this week to go out on prod but it's still very frustrating to have something break that was working fine.

I understand the point of making it easier for new users, but when I had the full-stack project set up to build both front and back through the console it was working fine, it was just not very practical to have front and back in the same repo and rebuild backend every time a commit for the frontend was being pushed.

As a general rule, don't fix it if it ain't broken!

**Comment by cslogan-red** [comment]
@thedgbrt @mansiva @mgarabedian apologies for the inconvenience! To be clear, unchecking the full-stack CI/CD box will still result in us only running an `amplify pull`, which in nearly all cases takes about 10 seconds and results in four new lines being logged to the Console in the Backend section:

```
                                 ## Checking for associated backend environment...
                                 ## Backend environment association found
2021-06-16T16:44:47.609Z [INFO]: [0mAmplify AppID found: dy4umyq0m667k. Amplify App name is: aws-amplify-gatsby-auth[0m
2021-06-16T16:44:47.745Z [INFO]: [0mBackend environment hmc found in Amplify Console app: aws-amplify-gatsby-auth[0m
2021-06-16T16:44:48.588Z [WARNING]: - Fetching updates to backend environment: hmc from the cloud.
2021-06-16T16:44:48.899Z [WARNING]: ✔ Successfully pulled backend environment hmc from the cloud.
```

This is the same as if you have your `aws-exports.js` file and `amplify` folder checked into your app's repo, we're simply generating them for you at build time in the container in the event that you don't. **That said**, it's been identified that the headless pull is not supported by 100% of the enabled CLI categories, and is resulting in a prompt after we run the pull.

To unblock you all, we are rushing an escape hatch that will let you disable the Console from even attempting to run a backend build if you do not have a backend section present in your build spec. I will update this thread as soon as it's available in your regions.

**Comment by thedgbrt** [comment]
@mansiva you are right, thank you for the tip I've learned something!
@cslogan-red I tried it again and it worked, thank you. I've seen that you've added a couple of ENV variable to fix it too?

**Comment by cslogan-red** [comment]
@thedgbrt there are two new managed env vars the Console creates to enable the `pull-only` experience, they'll be described in the docs update published tomorrow, can just leave them as created.

**Comment by mansiva** [comment]
@cslogan-red I've tried again but builds are still failing. Do I need to actually push a new commit to the repo or can I just "Redeploy this version" ?

**Comment by cslogan-red** [comment]
@mansiva your build in particular is going to need our emergent fix, you'll be able to skip checking for a backend association at all if you don't have a backend section in your build spec, I'll let you know once it's available in your region.

**Comment by cslogan-red** [comment]
@mansiva as well as for anyone else that happens to have their amplify environment checked into their app's repo with no backend section in your build spec at all, and unchecking "Enable full-stack continuous deployments (CI/CD)" for your branch is still resulting in build failures, you can disable Amplify Console from even attempting to run a backend association by creating and setting the `AMPLIFY_SKIP_BACKEND_BUILD` environment variable to `true`, and we'll skip the association check entirely, only running a frontend build. The docs will be updated to reflect this.

**Comment by warrenmcquinn** [comment]
Thanks for your quick help @cslogan-red! 

Side note: I do use a custom `amplify.yml` build setting that doesn't have a backend phase, but I don't have my environment (or aws-exports.js) checked into my repo. My frontend phase runs a script called "amplifyPull.sh" that simply generates an aws-exports.js file prior to running the frontend build command.

This unanticipated Backend phase has been re-creating Lambda layers on every deploy, which just slows down the build process.

The `AMPLIFY_SKIP_BACKEND_BUILD` env var has circumvented the issue for me.

**Comment by cslogan-red** [comment]
@warrenmcquinn sorry to hear that, you can continue to use your existing setup, or you can now also use the option explained a few replies above. Unchecking the "Enable full-stack continuous deployments (CI/CD)" for your branch will cause us to only run an `amplify pull` at build time, generating the `aws-exports.js` file for you, and you can remove your custom script. (I'll update this thread with the docs release once they are published) By default, we'll run an `amplify pull && amplify init`, and the init results in recreation of the Lambda layers. Glad this is resolved for you either way!

**Comment by swaminator** [comment]
@warrenmcquinn can we hop on a call? We'd like to figure out what's going on with your app.

**Comment by warrenmcquinn** [comment]
@swaminator sure thing, I can be on the Amplify discord anytime tomorrow if that's convenient. My handle is warrenmcwin if you want to coordinate on chat.

**Comment by cslogan-red** [comment]
Our updated [docs](https://docs.aws.amazon.com/amplify/latest/userguide/amplify-config-autogeneration.html) and [blog post](https://aws.amazon.com/blogs/mobile/complete-guide-to-full-stack-ci-cd-workflows-with-aws-amplify/) have been published, for anyone's future reference.

**Comment by rallona** [comment]
> @warrenmcquinn sorry to hear that, you can continue to use your existing setup, or you can now also use the option explained a few replies above. Unchecking the "Enable full-stack continuous deployments (CI/CD)" for your branch will cause us to only run an `amplify pull` at build time, generating the `aws-exports.js` file for you, and you can remove your custom script. (I'll update this thread with the docs release once they are published) By default, we'll run an `amplify pull && amplify init`, and the init results in recreation of the Lambda layers. Glad this is resolved for you either way!

and how can I uncheck this  "Enable full-stack continuous deployments (CI/CD)" option when I am deploying the app using the AWS NODEJS API?

**Comment by rallona** [comment]
> @mansiva as well as for anyone else that happens to have their amplify environment checked into their app's repo with no backend section in your build spec at all, and unchecking "Enable full-stack continuous deployments (CI/CD)" for your branch is still resulting in build failures, you can disable Amplify Console from even attempting to run a backend association by creating and setting the `AMPLIFY_SKIP_BACKEND_BUILD` environment variable to `true`, and we'll skip the association check entirely, only running a frontend build. The docs will be updated to reflect this.

If I attach the `AMPLIFY_SKIP_BACKEND_BUILD` = true environment variable it doesn't generate me the aws-export.js file... 

I have read and the aws-export file is generated when you build the backend isn't it?

Any solution to this??

**Comment by rallona** [comment]
> Our updated [docs](https://docs.aws.amazon.com/amplify/latest/userguide/amplify-config-autogeneration.html) and [blog post](https://aws.amazon.com/blogs/mobile/complete-guide-to-full-stack-ci-cd-workflows-with-aws-amplify/) have been published, for anyone's future reference.

If I use `AMPLIFY_SKIP_BACKEND_BUILD` the build doesn't generate me the aws-export file...
