### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by PedroSimacek** [aws-amplify/amplify-console#1968]
**App Id**: dea3ns359jf5i
**Region**: sa-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Error when creating a custom domain for my Amplify APP. It seems that the "View DNS Records" shows a CNAME entry while the process creates an A registry with the same value, but error massage is not making it explicite WHICH CNAME registry is breaking.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by nimacks** [comment]
Our records indicate that this domain is available. Re-open if you're still having issues
