### ISSUE TITLE
Branch auto detection does not work with Github

### ISSUE THREAD

**Issue by rkul** [aws-amplify/amplify-console#197]
**Describe the bug**
I tried to build branches based on pattern as described in the documentation. So I added few patterns and created appropriate branches on Github, but nothing happens.

**To Reproduce**
1. Go to General settings
2. Click on Edit button
3. Scroll down to Branch autodetection - patterns
4. Click Enabled
5. Add following patterns: `GWY-**, feature/**, gwy-**`
6. Click on Save button
7. Push branch `feature/GWY-123` to GitHub repo
8. Nothing happens

**Expected behavior**
Branch connected, application is built and deployed

**Additional context**
Application ID: arn:aws:amplify:us-east-1:044883579400:apps/d12p4sd3t7f46a

**Comment by jojojo123** [comment]
@rkul  Can you try adding following patterns without spaces
`GWY-**,feature/**,gwy-**`

It should work as expected.

**Comment by rkul** [comment]
Yes it works now. Documentation is unclear on that.
