### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by bentomania** [aws-amplify/amplify-console#1970]
![Snip20210617_50](https://user-images.githubusercontent.com/41994557/122332378-50f53c80-cf04-11eb-9e79-31da8b677c05.png)
**App Id**: d2pt2g1nsum9j7
**Region**: us-west-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I have been trying to connect a custom domain to my Amplify app. Each time it will fail at the last step stating that "Error message: One or more of the CNAMEs you provided are already associated with a different resource. " I have only one hosted zone with the domain name and I can guarantee that the CNAME record is only in this hosted zone. The Nameservers are set up correctly as the SSL is generated correctly and the cloudfront URLs are automatically updated. I had two hosted zones in the past (less than 24 hours ago) where this CNAME was used. Could it be the reason why I am seeing this message even though they are now deleted? 

**Error message**
If there is an error message, please include it here. 
Error message: One or more of the CNAMEs you provided are already associated with a different resource. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by nimacks** [comment]
Our records indicate that this domain is now available.
