### ISSUE TITLE
Path pattern for custom headers

### ISSUE THREAD

**Issue by rkul** [aws-amplify/amplify-console#198]
**Please describe which feature you have a question about?**
Configuration for custom headers in `amplify.yml`

**Provide additional details**
As stated in documentation https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html  we can add custom headers based on some pattern. I didn't find what exactly the pattern may be. Does it support any regular expression?

**Comment by swaminator** [comment]
Custom headers support any regular expression patterns. What patterns are you trying to use?

**Comment by rkul** [comment]
I wanted to use something like ```^(controller|field)/**.html```
Could you tell me do headers get merged if file path hits few patterns? What is precedence order?
I'm trying to understand can I put common headers using `**/*` pattern and then just add more specific for `/controller/*.html` for example?

**Comment by rkul** [comment]
I figured out that this is possible if I put common headers at the top of the `customHeaders` section and more specific ones below.

**Comment by rkul** [comment]
Any chance to use environment variables in `customHeaders` header values? I'd like to put content-security-policy: "default-src 'none'; base-uri 'none'; object-src 'none'; font-src 'none'; media-src 'none'; connect-src self $ORIGIN; etc..."
