### ISSUE TITLE
Cloning repository in Preview Build fails when branch adds amplify.yml to repo root

### ISSUE THREAD

**Issue by grimsa** [aws-amplify/amplify-console#1981]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2ibhgok7yafet

### Region

us-east-1

### Amplify Console feature

Previews

### Describe the bug

**Context:**
The main branch of the repository does not have `amplify.yml` or `customHttp.yml` files in repo root.
Then a branch is created that:
1. Adds `amplify.yml` or `customHttp.yml` to repo root
2. Includes other changes, e.g. changing the build command, settings or business logic

**A PR preview build has the following problems:**
1. Amplify fails to checkout the correct branch, but this does not mark the build as failure
```
[INFO]: error: The following untracked working tree files would be overwritten by checkout:
                                 amplify.yml
                                 customHttp.yml
                                 Please move or remove them before you switch branches.
                                 Aborting
```
2. Instead Amplify executes the build on the main (default) repository branch using old build config (i.e. preview fails)

### Expected behavior

1. Amplify can checkout the new branch that contains newly added `amplify.yml` or `customHttp.yml` in repo root.
2. If checkout fails, build is marked as a failure **immediately**

### Reproduction steps

1. Create a repository with no `amplify.yml` or `customHttp.yml` files in repo root and some script `build-1.sh` that prints something to console
2. Define a single build step in Amplify Console that executes on `build-1.sh`
3. Make sure build for default branch succeeds
4. Create a new branch that adds `amplify.yml` or `customHttp.yml` files to repo root, and renames `build-1.sh` to `build-2.sh`
5. Create a PR so that a Preview build is triggered
6. Observe: 1) failure to check out the preview branch and 2) build log showing execution of `build-1.sh`

### Additional information

**Workaround**
Add additional `preBuild` command to `amplify.yml` in your branch that would force checkout of the current branch:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        # Workaround for https://github.com/aws-amplify/amplify-console/issues/1981
        - git checkout $AWS_BRANCH -f
        - # <other pre-build commands>
    build:
      commands:
        - # <build command>
```

**Comment by victorccccc** [comment]
Hi, sorry for the inconvenience. We've fixed this preview issue, feel free to reopen this if issue persists
