### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by wsun66** [aws-amplify/amplify-console#1985]
**App Id**: d2o8bf25o8z7gi
**Region**: us-west-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Unable to set up custom domain: aleracareservices.com. We've tried a couple of times. Another issue is we are not able to see DNS records on Amplify console. View DNS records are disabled. 

**Error message**
One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
The DNS of the domain is Goddady.

**Comment by wsun66** [comment]
APP ID and Region are in the original issue: 
App Id: d2o8bf25o8z7gi
Region: us-west-1

We've tried many times and verify the records in the Goddady. The another issue is "View DNS records" in the Actions dropdown of Amplify console is grey out (disabled). Therefore there is no way for us to verify the DNS records. Do you have a solution for the issue? Thanks,

**Comment by ferdingler** [comment]
Hi @wsun66, I'm sorry you had issues creating your custom domain. We have recently improved our error messaging on the CNAMEAlreadyExistException to give customers better information on how to recover from it. This usually means one of these things: 

1) You have already used the same custom domain in another Amplify App in another region/account. 
2) You are using this domain in another service: LightSail or API Gateway. 
3) Your domain has an old CNAME record that points to a cloudfront.net URL from a previous Amplify App. 

Feel free to re-add the custom domain and you should get better information on what's going on. Thanks for reporting!
