### ISSUE TITLE
Issues connecting amplifyapp.com custom domain

### ISSUE THREAD

**Issue by tgilland95** [aws-amplify/amplify-console#1990]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-west-2:748075443147:apps/d1kpd82nueb3jq

### Region

us-west-2

### Step

SSL configuration

### Status

failed

### Issue or question

This is an issue/error we've had for quite a while (around 1 year i would guess). Since it doesn't cause any real issues, we have ignored this, but it would be nice to get resolved. 

Note: We are connected to our own custom domain (a domain managed in route53) without problems, this constant error is only for the amplifyapp.com domain.

I get a red banner across the top of the screen that says: "We had issues connecting your custom domain: amplifyapp.com. Please visit the Domain Management page for more information."

![image](https://user-images.githubusercontent.com/22225140/123157086-592f0980-d427-11eb-8d16-706374589b16.png)

![image](https://user-images.githubusercontent.com/22225140/123156565-afe81380-d426-11eb-9340-e35899bf44fc.png)

**Comment by tgilland95** [comment]
Okay, let me know if anything else is needed (AppId and Region are both in issue description)

**Comment by victorccccc** [comment]
Hi, @tgilland95. amplifyapp.com is default domain of your amplify app. You don't need to manually add it

**Comment by tgilland95** [comment]
@victorccccc how can we remove it?

**Comment by victorccccc** [comment]
Sorry, you cannot remove default domain.

**Comment by tgilland95** [comment]
@victorccccc  Okay, so how do i get rid of this error message?
- I already have a custom domain configured with the app.
- I have looked for a way to remove the domain with the errors, but can't

What can i do to get rid of this error message?
![image](https://user-images.githubusercontent.com/22225140/123286208-f42cef80-d4ca-11eb-8d36-7c84733dc1da.png)

**Comment by tgilland95** [comment]
@victorccccc In case it isn't clear, we aren't trying to add amplifyapp.com as a domain to the app.  We have a custom domain setup and used already. We would just like to get rid of this error.

**Comment by nimacks** [comment]
Our records indicate that the domain you are trying to associate is `amplifyapp.com`. You can verify this information here : https://docs.aws.amazon.com/cli/latest/reference/amplify/get-domain-association.html. In order to remove this error message you will need to choose a different domain.

**Comment by nimacks** [comment]
Your account has the following custom domains added to it:

1. amplifyapp.com
2. findd.amplifyapp.com

`amplifyapp.com` is a reserved domain and you cannot add this to your app. Remove the two domains and this error will clear. 

Use the following CLI commands to view your information

- https://docs.aws.amazon.com/cli/latest/reference/amplify/list-domain-associations.html

- https://docs.aws.amazon.com/cli/latest/reference/amplify/delete-domain-association.html
` delete-domain-association
--app-id <value>
--domain-name <value>`

Reopen if you have any issues.
