### ISSUE TITLE
Cannot connect a new branch I made

### ISSUE THREAD

**Issue by glidaa** [aws-amplify/amplify-console#1991]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-1

### Amplify Console feature

Build settings

### Describe the bug

I have created a new branch in my github called frontfour but I cannot see it when I click connect branch on the front end section of my app dsqawqiqetm4f

### Expected behavior

I want to see the branch I just made

### Reproduction steps

make a new branch 
try to connect it

**Comment by victorccccc** [comment]
Hi, @glidaa. I'm sorry I cannot reproduce this issue on my end, can you try to disable cache and then refresh the page? Thanks

**Comment by nimacks** [comment]
We are unable to reproduce this issue. Re-open if you are still facing this issue.
