### ISSUE TITLE
Domain activation is Failed - [Domain Activation - Amplify - Failure] 

### ISSUE THREAD

**Issue by byfnoel** [aws-amplify/amplify-console#1997]
**App Id**: d3qyprr3fsw9uv
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Domain registration failed. Previously it was successful, but I remove the app and add it again. However, it results in failure.
I am also using google domains.

**Error message**
We had issues connecting your custom domain: 3linic.com. Please visit the Domain Management page for more information.

**Additional information**
Please add any other relevant 
<img width="1080" alt="Screen Shot 2021-06-24 at 9 10 01 PM" src="https://user-images.githubusercontent.com/63328653/123353918-94692f80-d530-11eb-857f-2d7a8c8dc089.png">
information. Please feel free to include screenshots.

**Comment by ferdingler** [comment]
Hi @byfnoel, I'm sorry you had issues creating your custom domain. We have recently improved our error messaging on the CNAMEAlreadyExistException to give customers better information on how to recover from it. This usually means one of these things: 

1) You have already used the same custom domain in another Amplify App in another region/account. 
2) You are using this domain in another service: LightSail or API Gateway. 
3) Your domain has an old CNAME record that points to a cloudfront.net URL from a previous Amplify App. 

Feel free to re-add the custom domain and you should get better information on what's going on. Thanks for reporting!
