### ISSUE TITLE
Domain activation is Failed - One or more domain names have failed validation due to a Certificate Authority Authentication error.

### ISSUE THREAD

**Issue by HMilbradt** [aws-amplify/amplify-console#200]
**App Id**: d3bsiju3l3vwuf
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I'm unable to add a root domain in the Amplify console.  I have tried with and without CAA records that include amazon.com, as outline [here](https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-caa.html).  I have tried deleting the domain multiple times, deleting the DNS verification records and re-adding them, and have been at this a few days now.

I ran into this same issue a week ago, posted [here](https://github.com/aws-amplify/amplify-console/issues/194), and was only able to work around it by immediately adding the CNAME record pointing the the Cloudfront distribution during the setup.

However, we're now wanting to switch a production app over, and cannot have the site down while the Amplify setup is going.  Waiting is recommended in step 5 [here](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html).  

Any ideas what could be going wrong here?  

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

> Error message: The status of this certificate request is "Failed". One or more domain names have failed validation due to a Certificate Authority Authentication error. Learn more: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-caa.html

**Additional information**
Our domain is on Cloudflare.  The verification CNAME was added with proxy turned off.  I was able to verify that our verification CNAME record is propagated according to [this](https://www.whatsmydns.net).

**Comment by nationwide13** [comment]
Can you share the CAA record you created? (omitting your domain name)

Regardless of what domains you specify Amplify Console requests a certificate with both the root (mydomain.com) as well as a wildcard cert (*.mydomain.com), so your CAA record must allow us to create a certificate for both of those.

Thanks

**Comment by anatonie** [comment]
Can you share the CAA record you created? (omitting your domain name)

Regardless of what domains you specify Amplify Console requests a certificate with both the root (mydomain.com) as well as a wildcard cert (*.mydomain.com), so your CAA record must allow us to create a certificate for both of those.

Thanks

**Comment by HMilbradt** [comment]
Thanks for the reply @anatonie. 

I did not have a wildcard cert set up.  I have just added it and will update if that works 👍.

My CAA records:

CAA example.com 0 issue amazon.com
CAA example.com 0 issuewild amazon.com

**Comment by HMilbradt** [comment]
Adding the wildcard CAA as well as the root CAA fixed this.

I believe the reason the CAA records were required at all is because we are using Cloudflare's Universal SSL, which automatically adds several CAA records behind the scenes.  I didn't realize that all these records also had both the root CAA and wildcard CAA records, which should have told me that the amazon CAA records likely require the same.

Is it possible to update the error message or trouble shooting steps with this information?  It wasn't immediately obvious that the Amazon CAA records, if required, need both the wildcard and root record attached.

Thanks so much for your help!

**Comment by swaminator** [comment]
@HMilbradt out of curiosity why are you using CloudFlare in front of Amplify?
