### ISSUE TITLE
Domain activation is Failed - Can't add domain from Route 53

### ISSUE THREAD

**Issue by munkhbayar17** [aws-amplify/amplify-console#2005]
**App Id**: d3l2zst03ssv9f
**Region**: eu-central-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
We have been failing to configure our domain name. Reading the error message, we have completely cleared CNAMEs and tried again. But still no good.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by nimacks** [comment]
Our records indicate that this domain is now available.
