### ISSUE TITLE
Build fails with "internal error"

### ISSUE THREAD

**Issue by captaineffe** [aws-amplify/amplify-console#2006]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3iy9uh0b6vanf

### Region

eu-central-1

### Amplify Console feature

Backend builds

### Describe the bug

Build always fails with "internal error" with not further information:

2021-06-26T12:40:50.297Z [INFO]: Starting SSR Build...
2021-06-26T12:42:27.061Z [ERROR]: Internal error

Error accours with next.js version 11, 10 und 9.

### Expected behavior

Build log should at least display some more informations about the concrete problem.

### Reproduction steps

Happens always when build is started

**Comment by Athena96** [comment]
Hi all, we've recently made improvements to our SSR error logging and have added support for Next.js 10/11. 
Please follow this guide to upgrade to our latest support of Next.js: https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#update-app-nextjs-version
