### ISSUE TITLE
TLSv1.2_2021 Will this be supported on Amplify Soon?

### ISSUE THREAD

**Issue by mb-genvis** [aws-amplify/amplify-console#2007]
**Is your feature request related to a problem? Please describe.**
When will amplify allow sites to choose the TLS policies from cloudfront?

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html#secure-connections-supported-ciphers

Outlines a list and the latest 2021 policy removes all weak ciphers.

In certain SSL security tests the default list of ciphers gives 2 weaker options as standard:

From an SSL Labs Report of an amplify website:
```
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)   ECDH x25519 (eq. 3072 bits RSA)   FS   WEAK	256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)   ECDH x25519 (eq. 3072 bits RSA)   FS   WEAK	128
```

**Describe the solution you'd like**
When creating SSL certificates have a simple dropdown on the creation screen or an advanced dropdown letting you select the policy to be applied to the CloudFront deployment. 

I would imagine this is just defaulted in the Cloudformation template your triggering under the hood, so it should only be adding a new param to the request you send to it.

**Additional context**
None

**Comment by kahdojay** [comment]
Hi @mb-genvis, we will be rolling out TLSv1.2_2021 to all distributions within the new few weeks, some have already been updated. If you need your specific app updated urgently, please raise a case with AWS Support and we can take a look.
