### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by rignellj** [aws-amplify/amplify-console#2008]
**App Id**: d2hwqisn1lqyc8
**Region**: eu-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by nimacks** [comment]
Our records indicate that the domain associated with this is app is now available : ******.fi
