### ISSUE TITLE
DNS expecting IP in A record while custom domain dns Aname is the url

### ISSUE THREAD

**Issue by alimamoon** [aws-amplify/amplify-console#2010]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dcnkgrg0d99qo

### Region

us-east-2

### Step

Domain DNS ANAME adding in DNS

### Status

Expecting IP instead of URL

### Issue or question

I have verified the domain and successfully deployed. Now, at last step I need to add the ANAME and CNAME on my domain dns. 

I have added the CNAME but DNS is expecting IP for A record while amplify is giving me cloudflare url. I'm not sure how it will be added. 

    @    ANAME    d1ta3j5oj6kidc.cloudfront.net

**Comment by garyleefight** [comment]
You don't have to add the ANAME record

**Comment by alimamoon** [comment]
will site open with just cnam record and no A record? 

can I get the IP against  d1ta3j5oj6kidc.cloudfront.net?

**Comment by alimamoon** [comment]
It started working with cname
