### ISSUE TITLE
Make Nuxt.js SSR deployment as easy as Next.js! 😥

### ISSUE THREAD

**Issue by Rusinas** [aws-amplify/amplify-console#2011]
I beg you guys, I'm trying to deploy Nuxt.js app on AWS since the last year. And today I tried to deploy Next.js and it took a couple of minutes. I am so tired and frustrated so I write this here but I really need this. I don't understand why you still haven't implemented it!
TT___TT

**Comment by siegerts** [comment]
Hi @Rusinas, thanks for raising and trying Nuxt! :) 

Currently, you can host [**static** Nuxt.js applications on Amplify Console](https://docs.amplify.aws/guides/hosting/nuxt/q/platform/js).  SSR-based Nuxt apps are _not yet supported_ (from a hosting standpoint) but there is a [feature request opened to capture interest](https://github.com/aws-amplify/amplify-console/issues/1860). 

Closing this in favor of the above feature request.
