### ISSUE TITLE
Fails to clone backend environment (no error details provided)

### ISSUE THREAD

**Issue by alonsnir** [aws-amplify/amplify-console#2016]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d9dwprxsmtbx8

### Region

us-east-2

### Amplify Console feature

Not applicable

### Describe the bug

I'm trying to clone backend environment.

From the Amplify Console, opened an application. Clicked on 'Backend Environments'. From 'Actions' menu selected 'Clone'.
It starts with:
1) Invoking clone success (or something similar)
2) Cloning env:dev to env: test in app:d9dwprxsmtbx8. This operation will take a few minutes.
3) Cloning env:dev to env: test in app:d9dwprxsmtbx8 failed

### Expected behavior

Backend environment clone to work or at least provide meaningful error message

### Reproduction steps

1. open aws amplify console
2. open app
3. shitch to backend environments
4. from the Actions menu, right to the environment select Clone

**Comment by hloriana** [comment]
I was not able to reproduce this behavior. If you're still running into this issue please feel free to re-open.

**Comment by scottbw** [comment]
Just had exactly the same happen to me now.
