### ISSUE TITLE
What is the current build resources and can we add more resource ?

### ISSUE THREAD

**Issue by talebbits** [aws-amplify/amplify-console#202]
** Please describe which feature you have a question about? **
We are looking to options speed up gatsby build is it possible to add more CPU?

** Provide additional details**
If you can point me to documentation where we could find amplify console CPU count so that we can set `GATSBY_CPU_COUNT`

**Comment by anatonie** [comment]
Hello @talebbits 

Builds currently use an instance with **4 vCPU** and **7GB RAM** (from [FAQs](https://aws.amazon.com/amplify/console/faqs/))

At this point in time there is no way to use more powerful instances at build time. You are more than welcome to open a [new feature request](https://github.com/aws-amplify/amplify-console/issues/new?template=feature_request.md) for this feature!

Thanks
