### ISSUE TITLE
Domain activation is Failed -CNAME in use

### ISSUE THREAD

**Issue by multiapps** [aws-amplify/amplify-console#2030]
**App Id**: d1mdnra0y20jxc
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: I went through the steps to add the domain to my amplify project, but I always get an error, despite having reset everything.

**Issue/question**
The configuration was carried out several times, the hosted zone was eliminated and added again, but it continues to bring failures with the main domain in the amplify

**Error message**
We had issues connecting your custom domain: cuidate.com.pe. Please visit the Domain Management page for more information.

**Note**: Be sure to check the message for sensitive information.

**Comment by nimacks** [comment]
Our records indicate that this domain is available. Re-open if this is still an issue.
