### ISSUE TITLE
SSL configuration is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by GodStorm91** [aws-amplify/amplify-console#2032]
**App Id**: d33p4yzn737cze
**Region**: ap-northeast-1
**Step**: SSL configuration
**Status**: Running

>**Note**: 
I created the CNAME record but still stuck at SSL Configuration. 

**Issue/question**
Could you please help me to check whether my configuration is wrong  ?

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by nimacks** [comment]
Our records indicate that this domain is now available: co********s.d*******.g**.v*
