### ISSUE TITLE
Amplify push gives an error:- Unknown directive "ttl". An error occurred during the push operation. Unknown directive "ttl".

### ISSUE THREAD

**Issue by goluarchana** [aws-amplify/amplify-console#2041]
I have used @ttl directive in schema for Expiration of message as such:-
expirationUnixTime: AWSTimestamp! @ttl 
but the push command is giving error. How to proceed with this?

API ID:-drz0286oglp5q
Region:-ap-south-1

**Comment by siegerts** [comment]
Hi @goluarchana , thanks for opening. The @ttl directive is a third-party directive (links below) that will need to be installed separately, in addition to, the Amplify CLI.

If you're still hitting issues, please open an [issue in the Amplify CLI repo](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml) with the any relevant details (reproduction steps, code snippet, log, etc) .

- https://github.com/flogy/graphql-ttl-transformer
- https://docs.amplify.aws/cli/graphql-transformer/directives#aws-appsync-provided-directives
