### ISSUE TITLE
Custom Domain Issue (modernIrondesign.com)

### ISSUE THREAD

**Issue by ansaridevelopment** [aws-amplify/amplify-console#2043]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://us-west-2.console.aws.amazon.com/amplify/home?region=us-west-2#/d2o4eiyc05b4w

### Region

us-west-2

### Step

ssl config

### Status

pending

### Issue or question

pending for 24+ hours. I've tried to delete and propagate again and it still doesn't work. I've waited many days and I've checked hosted zone multiple times

**Comment by nimacks** [comment]
Our records indicate that this domain is now available m*****i***d******.com
