### ISSUE TITLE
Cannot delete orphaned app

### ISSUE THREAD

**Issue by difsta** [aws-amplify/amplify-console#2044]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:ap-southeast-2:032312983640:apps/d9o5hf4erei4n

### Region

ap-southeast-2

### Describe the bug

I am attempting to delete an App via the Amplify Console, it deleted the first environment and then has been stuck for almost 24hrs now.
"Removing backend envs for app d9o5hf4erei4n. This operation will take a few minutes."
I have then attempted to delete either the app or the backend environments via the Amplify CLI, but I receive the following error:
"An error occurred (NotFoundException) when calling the DeleteBackendEnvironment operation: App d9o5hf4erei4n not found."
I have then manually tried to delete the resources used, ie. deleted the lambda functions, the stack via Cloudfront, etc. I believe the only thing left is the app itself, which everytime I open it up shows that it is still removing the backend envs for the app.

### Expected behavior

I should be able to delete an Amplify App

### Reproduction steps

1. In the API Conosle I selected Actions | Delete App.
2. I then get a message in blue saying it is invoking remove all backends
3. It turns red and states: Invoking remove all backends execution failed
4. I try the Amplify CLI: aws amplify delete-backend-environment --app-id d9o5hf4erei4n --environment-name dev
5. I get an error: An error occurred (NotFoundException) when calling the DeleteBackendEnvironment operation: App d9o5hf4erei4n not found.

**Comment by ferdingler** [comment]
Hello, thanks for reporting this issue. We delete things in certain order, I suspect that in this case the backend environment (CFN stack) was deleted before the app so it may be in this stuck state. Can you please try deleting it directly with the AWS CLI? 

```bash
aws amplify delete-app --app-id 123
```

Let us know if this helps
