### ISSUE TITLE
Building is stuck 

### ISSUE THREAD

**Issue by zbsergio** [aws-amplify/amplify-console#2045]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d133xwjunyhoyf

### Region

eu-central-1

### Amplify Console feature

Backend builds

### Describe the bug

I try to build the code using GitHub but it gets stuck / time out in build phase:
Build Timeout

Note: is working fine on CLI amplify push (in sandbox environment).

### Expected behavior

Display an error on where the issue is 

### Reproduction steps

1.- connect the project to the branch
2.- build it
3.- it hangs 

### Additional information

![Screen Shot 2021-07-13 at 10 32 29 AM](https://user-images.githubusercontent.com/62180288/125419407-e12800dc-a4a9-43b8-8d1a-7b92b3333bc0.png)

**Comment by zbsergio** [comment]
Please note that I am using RDS on appsync

**Comment by zbsergio** [comment]
Hi all,
I have managed to reproduce it:
1.- do amplify api add-graphql-datasource
2.- push will work
3.- adding it to another environment (account) via GitHub won't work

This is due to the creation of the IAM user. 

I will add the db manually in the console, but please advice when this is fixed in the code.

Kind Regards,

Sergio

**Comment by ferdingler** [comment]
Hi Sergio, thanks for reporting this issue. I wasn't able to find the appId `d133xwjunyhoyf` in `eu-central-1`. I would also like to understand when you say that _"it fails due to the creation of the IAM user"_. What do you mean by this?

**Comment by zbsergio** [comment]
HI Fernando, 
I had to rebuild it so is now dxt2j6vj3zyx in eu-central-1.
However, this bug can easily be reproduced by your end by simply
1.- do amplify api add-graphql-datasource
2.- push will work to the local account 
3.- adding it to another environment (account) via GitHub won't work

I have reproduced it in several environments.
What I mean that it could be due to the creation of IAM is because it gets stuck in that process.

I can jump into a call if you need to have more information.

Sergio

**Comment by behrooziAWS** [comment]
I was able to locate the build logs for: d133xwjunyhoyf 
It is making it past the IAM step, but it appears the amplify push command you are running is blocking waiting on input and needs to be run in headless mode:

```
2021-07-13T08:00:24.301Z	2021-07-13T08:00:23.487Z [INFO]: ? Provide the region in which your cluster is located: (Use arrow keys)
2021-07-13T08:00:24.301Z	❯ us-east-1
2021-07-13T08:00:24.301Z	us-east-2
2021-07-13T08:00:24.301Z	us-west-1
2021-07-13T08:00:24.301Z	us-west-2
2021-07-13T08:00:24.301Z	ap-south-1
2021-07-13T08:00:24.301Z	ap-southeast-1
2021-07-13T08:00:24.301Z	ap-southeast-2
2021-07-13T08:00:24.301Z	(Move up and down to reveal more choices)
2021-07-13T08:00:24.301Z	2021-07-13T08:00:23.488Z [INFO]: [41D
2021-07-13T08:00:24.301Z	2021-07-13T08:00:23.488Z [INFO]: [41C
```
