### ISSUE TITLE
I have created many AWS Amplify Web apps but they are not listed

### ISSUE THREAD

**Issue by cristhianmarroquinse** [aws-amplify/amplify-console#2047]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-1

### Amplify Console feature

Access control

### Describe the bug

I have created many AWS Amplify Web apps but they are not listed on my list of all amplify apps.

### Expected behavior

When i create an AWS Amplify web app, I expect this new app appear in my list

### Reproduction steps

1. Create aws amplify web app
2. Enter to https://console.aws.amazon.com/amplify/home?region=us-east-1#/home
3. There is no apps listed

**Comment by JKalm** [comment]
Please provide AWS account id so we can check assigned apps.

Also double check the selected region, i.e. if application was created in us-west-2 it would not be listed in https://console.aws.amazon.com/amplify/home?region=us-east-1#/home

**Comment by cristhianmarroquinse** [comment]
My AWS account id is: 381029074462
I have tested in all regions where I can and in all I got blank list :(

**Comment by cristhianmarroquinse** [comment]
> Please provide AWS account id so we can check assigned apps.
> 
> Also double check the selected region, i.e. if application was created in us-west-2 it would not be listed in https://console.aws.amazon.com/amplify/home?region=us-east-1#/home

My AWS account id is: 381029074462
I have tested in all regions where I can and in all I got blank list :(

**Comment by JKalm** [comment]
I verified that apps were created and assigned to your account, please navigate here https://console.aws.amazon.com/amplify/home?region=us-east-1#/ 
- make screenshot 
- retrieve HAR
(in chrome: press F12 -> reload page -> Network -> XHR -> Right click on any row -> save all as HAR with content )
- email screenshot and HAR to aws-amplify-customer@amazon.com  (keep in mind it has sensitive information like cookies, please don't post here)

**Comment by cristhianmarroquinse** [comment]
![image](https://user-images.githubusercontent.com/58575153/125672060-2790a023-8a7a-4dbd-a9db-a97f0be0a22c.png)

The email was sent ! Thanks

**Comment by JKalm** [comment]
Updated accountClosureStatus attribute, can you please verify you can see the apps now?

**Comment by cristhianmarroquinse** [comment]
Thank a lot, now I can see the apps !!! 

![image](https://user-images.githubusercontent.com/58575153/125791303-d8819adb-3912-43e9-9a99-0aad7f033d9c.png)
