### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by atul7v7** [aws-amplify/amplify-console#2049]
**App Id**: d2oknmlludd9v9
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by siegerts** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-console/issues/2048
