### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by atul7v7** [aws-amplify/amplify-console#2050]
**App Id**: d2oknmlludd9v9
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Ownership verified successfully. After this i am getting error.
I registered my domain to aws amplify from one of my account. I closed that aws account and created new one.
Now in new one i am trying to add domain to hosted web-app.But i am getting error.

**Comment by siegerts** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-console/issues/2048
