### ISSUE TITLE
Domain activation is Failed - Domain activation fails when; Amplify provides a unique CloudFront Distribution CNAME record on each retry

### ISSUE THREAD

**Issue by tlh2857** [aws-amplify/amplify-console#2053]
**App Id**: d34zy4rgyo2d03
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am using AWS organizations and am trying to point my a subdomain that I manage with Route53  in one AWS account to an amplify project that I manage in a different AWS account, both under the organization. I seemingly pass the first two checks (SSL Creation, SSL configuration) under domain management, but each time it fails on 'Domain Activation'. 

I've retried this several times, and have noticed that each time it gives me a unique cloudfront distribution CNAME to use.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by ferdingler** [comment]
Hi @tlh2857, I'm sorry you had issues creating your custom domain. We have recently improved our error messaging on the CNAMEAlreadyExistException to give customers better information on how to recover from it. This usually means one of these things: 

1) You have already used the same custom domain in another Amplify App in another region/account. 
2) You are using this domain in another service: LightSail or API Gateway. 
3) Your domain has an old CNAME record that points to a cloudfront.net URL from a previous Amplify App. 

Feel free to re-add the custom domain and you should get better information on what's going on. Thanks for reporting!
