### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by felipehv** [aws-amplify/amplify-console#2054]
**App Id**: d28buth1nsldaa
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Why can't the domain be activated

**Error message**
Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: The status of this certificate request is "Failed". One or more domain names have failed validation due to a Certificate Authority Authentication error. Learn more: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-caa.html

**Additional information**
![image](https://user-images.githubusercontent.com/11399594/125821857-a5019352-a2e7-40ef-b9fb-80f588fc43f9.png)

**Comment by nimacks** [comment]
Hi @felipehv ,
The CAA error happens when your domain has a CAA DNS record that does not specify Amazon as an approved Certificate Authority. The solution is to either remove your CAA records entirely, or add at least one of these records to your domain DNS: 

```
example.com.  CAA 0 issue "amazon.com"
example.com.  CAA 0 issue "amazontrust.com"
example.com.  CAA 0 issue "awstrust.com"
example.com.  CAA 0 issue "amazonaws.com"
```
