### ISSUE TITLE
amplify nextjs ssr lambda@edge region is wrong

### ISSUE THREAD

**Issue by ywroh** [aws-amplify/amplify-console#2057]
**Please describe which feature you have a question about?**
Currently, amplify nextjs ssr has been distributed in the Seoul region, and lambda@edge is registered in the Virginia region.

**Provide additional details**

**What AWS Services are you utilizing?**
amplify, rds(auroraDB), ec2, LB, ecs, ecr

**Provide additional details e.g. code snippets**

**Comment by osnodegeoffrey** [comment]
Same here. It seems that the lambdas are always registered in us-east-1

**Comment by OG84** [comment]
lambda@edge is only available in us-east-1. I mean technically the lambda is deployed to the edge in any region, but registered it is in us-east-1. That is a lambda@edge constraint which is not related to amplify.

**Comment by osnodegeoffrey** [comment]
Makes sense. Thanks for the clarification.

**Comment by ywroh** [comment]
Lambda@Edge functions are distributed globally, but they originate from one place - region. This region must be in the US East (N. Virginia). As shown in the documentation [1], this is currently one of the restrictions of Lambda@Edge. Therefore, this is the reason of your Lambda@Edge is placed in N. Virginia rather than Seoul.

Reference:
[1] - [https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions-restrictions.html]
