### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by pmehtaaustin** [aws-amplify/amplify-console#2058]
**App Id**: d2nmjo2pta7ar4
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

Domain Activation during AWS-Amplify Domain addition fails with the message below. 

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

I have removed all CNAME entries from the Route 53 hosted zone, except for the ones created by sendgrid.net (for email purposes).  Is there an incompatibility with sendgrid?  How can I view more info? What is wrong?

**Comment by nimacks** [comment]
Our records indicate that this app no longer exist. Re-open if you're still experiencing issues with your custom domain.
