### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Megha0612** [aws-amplify/amplify-console#2063]
**App Id**: d2v29s0ma66hdj
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
My website is hosted on the domain previously . I deleted it due to some reasons . Now I am trying to host the site again but domain is not changing .

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource. 

![image](https://user-images.githubusercontent.com/74145629/126068600-695a4868-ade7-4b57-8701-3850e52c748a.png)

**Comment by adlershai** [comment]
same issue
app id: dyw0wxv3jeu7n
region: us-east-2

**Comment by nimacks** [comment]
@Megha0612, can you ensure that you've cleaned up the old CNAME record that was associated with your previous app? This would explain the error message you're getting at the moment in regards to CNAME Already associated with an existing resource.

**Comment by adlershai** [comment]
Thanks, now it's OK
