### ISSUE TITLE
Adding new route53 domain stuck on SSL configuration

### ISSUE THREAD

**Issue by Joaker4** [aws-amplify/amplify-console#2064]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d291tiov1118lj

### Region

us-east-1

### Step

Domain Activation > SSL Configuration

### Status

Stuck in SSL Configuration Step

### Issue or question

I'm trying to set up a custom domain from Route53 to my Amplify application but getting stuck on SSL configuration. I've added that domain from Route53 UI (Hosted Zones -> Create hosted zone -> domain name preview.example.com, Private hosted zone, chose a VPC in us-east-1
After adding the zone, it appeared in the domain dropdown and choosing it do create some CNAME records but immediately get stuck on SSL configuration.

### Error message

There are no error messages present, just stuck validating SSL Configuration for now.

**Comment by nimacks** [comment]
Hi, @Joaker4, if your domain is hosted in Route53 you do not need to make any manual changes in Route53. Amplify does that on your behalf. You should be able to select the domain in Amplify and follow the wizard to setup the domain. For your reference. https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

One or more domain names have failed DNS validation. Please check your domain name validation routes and try re-adding the custom domain to your app. Learn more: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-troubleshoot-guide
