### ISSUE TITLE
Build fails with "Internal error". 2 weeks ago everything was fine.

### ISSUE THREAD

**Issue by DandyDev** [aws-amplify/amplify-console#2065]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2p2tgjorslyut

### Region

eu-central-1

### Amplify Console feature

Not applicable

### Describe the bug

The [build fails](https://eu-central-1.console.aws.amazon.com/amplify/home?region=eu-central-1#/d2p2tgjorslyut/main/10?step=BUILD) for an app which [previously would build and deploy just fine](https://eu-central-1.console.aws.amazon.com/amplify/home?region=eu-central-1#/d2p2tgjorslyut/main/8).

<details>
<summary>The logs are less than helpful:</summary>

```
2021-07-19T16:09:13.632Z [INFO]: info  - Checking validity of types...
2021-07-19T16:09:19.267Z [INFO]: info  - Creating an optimized production build...
2021-07-19T16:09:19.782Z [INFO]: info  - Using external babel configuration from /codebuild/output/src764318014/src/app-frontend/.babelrc
2021-07-19T16:10:02.839Z [INFO]: info  - Compiled successfully
2021-07-19T16:10:02.840Z [INFO]: info  - Collecting page data...
2021-07-19T16:10:05.848Z [INFO]: info  - Generating static pages (0/4)
2021-07-19T16:10:07.889Z [INFO]: info  - Generating static pages (1/4)
2021-07-19T16:10:07.896Z [INFO]: info  - Generating static pages (2/4)
2021-07-19T16:10:08.068Z [INFO]: info  - Generating static pages (3/4)
2021-07-19T16:10:08.556Z [INFO]: info  - Generating static pages (4/4)
2021-07-19T16:10:08.556Z [INFO]: info  - Finalizing page optimization...
2021-07-19T16:10:08.562Z [INFO]: 
2021-07-19T16:10:08.567Z [INFO]: Page                                Size     First Load JS
                                 ┌ ○ /                               1.08 kB         490 kB
                                 ├   /_app                           0 B             469 kB
                                 ├ ○ /404                            3.1 kB          472 kB
                                 └ ○ /control/kpis/[gid]             149 kB          638 kB
                                 └ css/d9ad2655faa7dd06e8a3.css  873 B
                                 + First Load JS shared by all       469 kB
                                 ├ chunks/framework.2f6124.js      42.4 kB
                                 ├ chunks/main.c9abfc.js           19.6 kB
                                 ├ chunks/pages/_app.e985a1.js     405 kB
                                 ├ chunks/webpack.25bf63.js        2.6 kB
                                 └ css/c65ec94fc66e62b19d8b.css    25.6 kB
2021-07-19T16:10:08.568Z [INFO]: 
2021-07-19T16:10:08.568Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
                                 (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
2021-07-19T16:10:08.569Z [INFO]: 
2021-07-19T16:10:08.810Z [INFO]: Done in 56.03s.
2021-07-19T16:10:08.814Z [INFO]: Starting SSR Build...
2021-07-19T16:11:48.740Z [ERROR]: Internal error
```

</details>

What's interesting:

- The app is currently still super simple and doesn't use any SSR, only SSG
- I'm using NextJS 10, but not 10-specific features
- Aside from actual frontend code, there is not much that changed between the last successful build and this failing build. No dependency changes, no big feature changes etc.

### Expected behavior

I would have expected the build to succeed, just like the previous builds. Failing that, I would have at least expected the logs to give a clear indication of what went wrong, instead of `Internal error`.

I've seen many issues here on Github about logging being bad and the response always seems to be "We're looking into improving logging", but nothing much happens ever. The fact that you guys from AWS can look at _actual_ logs and tell us what's going wrong, means that it should be relatively simple to improve logging for us, paying customers, as well right?

### Reproduction steps

Just push code to Git and wait for the build to fail, where it previously would succeed just fine.

### Build Settings

```yaml
Build settings are standard auto-generated
```

**Comment by ferdingler** [comment]
Hi @DandyDev, I understand your frustration. We are indeed actively making changes to our build system to improve logging and propagate build errors better. I appreciate your patience while we work on this and thank you for reporting issues.

In this case, I see that your build failed with the following message: 

```
Error: Command failed with exit code 1: node_modules/.bin/next build

(node:2420) [DEP_WEBPACK_CHUNK_HAS_ENTRY_MODULE] DeprecationWarning: Chunk.hasEntryModule: Use new ChunkGraph API
--
944 | warn  - Compiled with warnings
945 | ./node_modules/next/dist/next-server/server/load-components.js
946 | Critical dependency: the request of a dependency is an expression
947 | ./node_modules/next/dist/next-server/server/load-components.js
948 | Critical dependency: the request of a dependency is an expression
949 | ./node_modules/next/dist/next-server/server/load-components.js
950 | Critical dependency: the request of a dependency is an expression
951 | ./node_modules/next/dist/next-server/server/require.js
952 | Critical dependency: the request of a dependency is an expression
953 | ./node_modules/next/dist/next-server/server/require.js
954 | Critical dependency: the request of a dependency is an expression
955 | ./node_modules/next/dist/next-server/server/require.js
956 | Critical dependency: the request of a dependency is an expression
957 | (node:2420) UnhandledPromiseRejectionWarning: TypeError: (0 , _styleChecker.isStyleSupport) is not a function
958 | at Object.86586 (/codebuild/output/src764318014/src/app-frontend/.next/serverless/chunks/418.js:263119:59)
959 | at __webpack_require__ (/codebuild/output/src764318014/src/app-frontend/.next/serverless/pages/_error.js:278:43)
960 | at Object.15394 (/codebuild/output/src764318014/src/app-frontend/.next/serverless/chunks/418.js:263897:36)
961 | at __webpack_require__ (/codebuild/output/src764318014/src/app-frontend/.next/serverless/pages/_error.js:278:43)
962 | at Object.53740 (/codebuild/output/src764318014/src/app-frontend/.next/serverless/chunks/418.js:264109:36)
963 | at __webpack_require__ (/codebuild/output/src764318014/src/app-frontend/.next/serverless/pages/_error.js:278:43)
964 | at Module.34182 (/codebuild/output/src764318014/src/app-frontend/.next/serverless/chunks/763.js:162:18)
965 | at __webpack_require__ (/codebuild/output/src764318014/src/app-frontend/.next/serverless/pages/_error.js:278:43)
966 | at Module.66544 (/codebuild/output/src764318014/src/app-frontend/.next/serverless/pages/_error.js:44:22)
967 | at __webpack_require__ (/codebuild/output/src764318014/src/app-frontend/.next/serverless/pages/_error.js:278:43)
```

Can you please confirm that your build succeeds if you run it locally? If it does, the docker image that we use to run builds by default can be found here: https://github.com/aws-amplify/amplify-console/blob/master/images/latest/Dockerfile, you may want to check the versions of node and other packages that we use and compare it to your local environment. 

Let us know if this helps.

**Comment by ferdingler** [comment]
Hi @DandyDev, I understand your frustration. We are indeed actively making changes to our build system to improve logging and propagate build errors better. I appreciate your patience while we work on this and thank you for reporting issues.

In this case, I see that your build failed with the following message: 

```
Error: Command failed with exit code 1: node_modules/.bin/next build

(node:2420) [DEP_WEBPACK_CHUNK_HAS_ENTRY_MODULE] DeprecationWarning: Chunk.hasEntryModule: Use new ChunkGraph API
--
944 | warn  - Compiled with warnings
945 | ./node_modules/next/dist/next-server/server/load-components.js
946 | Critical dependency: the request of a dependency is an expression
947 | ./node_modules/next/dist/next-server/server/load-components.js
948 | Critical dependency: the request of a dependency is an expression
949 | ./node_modules/next/dist/next-server/server/load-components.js
950 | Critical dependency: the request of a dependency is an expression
951 | ./node_modules/next/dist/next-server/server/require.js
952 | Critical dependency: the request of a dependency is an expression
953 | ./node_modules/next/dist/next-server/server/require.js
954 | Critical dependency: the request of a dependency is an expression
955 | ./node_modules/next/dist/next-server/server/require.js
956 | Critical dependency: the request of a dependency is an expression
957 | (node:2420) UnhandledPromiseRejectionWarning: TypeError: (0 , _styleChecker.isStyleSupport) is not a function
958 | at Object.86586 (/src/app-frontend/.next/serverless/chunks/418.js:263119:59)
959 | at __webpack_require__ (/src/app-frontend/.next/serverless/pages/_error.js:278:43)
960 | at Object.15394 (/codebuild/output/src764318014/src/app-frontend/.next/serverless/chunks/418.js:263897:36)
961 | at __webpack_require__ (/src/app-frontend/.next/serverless/pages/_error.js:278:43)
962 | at Object.53740 (/codebuild/output/src764318014/src/app-frontend/.next/serverless/chunks/418.js:264109:36)
963 | at __webpack_require__ (/src/app-frontend/.next/serverless/pages/_error.js:278:43)
964 | at Module.34182 (/codebuild/output/src764318014/src/app-frontend/.next/serverless/chunks/763.js:162:18)
965 | at __webpack_require__ (/src/app-frontend/.next/serverless/pages/_error.js:278:43)
966 | at Module.66544 (/src764318014/src/app-frontend/.next/serverless/pages/_error.js:44:22)
967 | at __webpack_require__ (/src/app-frontend/.next/serverless/pages/_error.js:278:43)
```

Can you please confirm that your build succeeds if you run it locally? If it does, the docker image that we use to run builds by default can be found here: https://github.com/aws-amplify/amplify-console/blob/master/images/latest/Dockerfile, you may want to check the versions of node and other packages that we use and compare it to your local environment. 

Let us know if this helps.

**Comment by DandyDev** [comment]
Hey @ferdingler, thanks for your reponse. Thanks to the logs you shared, I managed to pinpoint the issue. We use Ant Design as our component library, and apparently when used together with NextJS, it [behaves differently](https://github.com/vercel/next.js/issues/8151) when you build it for a serverless environment (which I assume Amplify is doing)?

So locally it was building just fine, but on Amplify it failed. It was solved by [upgrading one of my dependencies to a newer version](https://github.com/SolidZORO/next-plugin-antd-less/pull/57).

The bigger issue of course, is lack of proper build logs in Amplify. Do you have an ETA on when you will be sharing more/better logs with your users automatically? Because having to rely on Github issues or AWS Business Support - potentially taking days to respond - is a bit ridiculous for something that can be so easily solved on your end!

**Comment by DandyDev** [comment]
One more question: the Dockerfile you mentioned, how do I use this to test the build locally? Do I just run the docker container with my working directory mounted and then run `next build` in the container?

What are the commands that you run to build NextJS on Amplify? And do I just run those commands in a container built from the Dockerfile you mentioned?

**Comment by ferdingler** [comment]
@DandyDev glad to hear the issue was solved! 

> One more question: the Dockerfile you mentioned, how do I use this to test the build locally? Do I just run the docker container with my working directory mounted and then run next build in the container?

I was mostly pointing you to the Dockerfile to compare the versions of software that we use with your local environment. But, you could try running a build inside the container by mounting your source directory as you described and then running the same commands on your App buildspec: 

```
version: 1
backend:
  phases:
    build:
      commands:
          # AmplifyPush.sh can be found here https://github.com/aws-amplify/amplify-console/blob/master/scripts/amplifyPush.sh 
          - amplifyPush --simple

frontend:
  phases:
    preBuild:
      commands:
          - yarn install
    build:
      commands:
          - yarn run build
  artifacts:
      baseDirectory: .next
      files:
        - '**/*'
      cache:
        paths:
           - node_modules/**/*
```

> Do you have an ETA on when you will be sharing more/better logs with your users automatically? 

Unfortunately we can't provide an ETA, but we are making progress as we speak rolling out enhancements incrementally and continuously. Thanks again for reporting these issues, it is really helpful as we learn the nuances of SSR builds.

**Comment by Athena96** [comment]
Hi, we've recently made improvements to our SSR error logging and have added support for Next.js 10/11. 
Please follow this guide to upgrade to our latest support of Next.js: https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#update-app-nextjs-version
