### ISSUE TITLE
My custom domain SSL is not working

### ISSUE THREAD

**Issue by funkel1989** [aws-amplify/amplify-console#207]
**App Id**:  d2xsvr2jiiyamj
**Region**: us-east-1
**Step**: Complete
**Status**: Complete

**Issue/question**
when navigating to my website through my custom domain the site is showing as an insecure site and not having an SSL certificate. When using the URL amplify provides for CloudFront this issue does not occur. When clicking the view SSL cert for my site the domain manager says it is active

**Error message**
This site can’t provide a secure connection test.domain.com sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

This is the message provided to me by google chrome
(the above domain name is an example)

**Comment by garyleefight** [comment]
@funkel1989 Sorry for the late reply. Looks like you have deleted the app. Please let us know if you still have issues.

**Comment by funkel1989** [comment]
Hello @garyleefight . I had deleted and recreated the hosting and then the entire app to see if it would make a difference and it did not. Here is the new App Id - d2xsvr2jiiyamj.   Everything else is the same

**Comment by Joycehao19** [comment]
@funkel1989 It looks like your custom domain works fine now. Please let us know if you have any issues.

**Comment by funkel1989** [comment]
it does seem to be working now but was not just the other day. I also find it fairly odd that it happened after removing and re-adding the entire application also. I'm glad this was able to be resolved but just curious if there is something different I should do in the future?

**Comment by swaminator** [comment]
@funkel1989 tough for us to speculate what the issue was without the appid. If you encounter something like this in the future, please let us know and we'll diagnose this for you.

**Comment by iocuydi** [comment]
Having this same exact issue now. ssl works for the amplify domain but not for my domain. 

However, I'm hosting it on godaddy and I couldn't set up the ANAME record, only the www one. Instead I'm having godaddy forward the base domain to www. 

But https://www.mydomain.io still returns unsecure warnings. Any idea on how to fix this? Thanks!

**Comment by SandaruwanDKM** [comment]
Having the same issue with my custom domain - https://www.woworderz.com/ . But it's working fine with amplify domain. It was working fine a few days but after connecting my node js backend my main domain converted to not secure. I have created my subdomain using this woworderz.com.

Any idea about this issue? Thanks

**Comment by diyism** [comment]
same error here:

```
$ dig +trace up.guagle.com @1.1.1.1
up.guagle.com.		300	IN	CNAME	main.d9jh3z73a3ui0.amplifyapp.com.
;; Received 86 bytes from 44.226.226.6#53(curitiba.porkbun.com) in 259 ms

$ curl -v https://up.guagle.com/
*   Trying 13.35.162.59:443...
* Connected to up.guagle.com (13.35.162.59) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Comment by MatteoGioioso** [comment]
Same issue
