### ISSUE TITLE
Custom domain associated with an existing resource

### ISSUE THREAD

**Issue by ryj1023** [aws-amplify/amplify-console#2070]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2pmqeo7dxjt83

### Region

us-east-1

### Step

Domain activation

### Status

Failed

### Issue or question

When trying to activate my custom domain I receive an error related to my domain already being associated with an existing resource.

I verified that there is no existing CloudFront distribution. My 'CNAME' resolves correctly after checking on https://www.whatsmydns.net/

My custom domain seems to be serving an old version of my application that is nowhere present within the AWS ecosystem.

### Error message

Error message: One or more of the CNAMEs you provided are already associated with a different resource.

### Additional information

![Screen Shot 2021-07-20 at 11 50 40 AM](https://user-images.githubusercontent.com/18105491/126355620-1018c177-7609-4d38-bae8-21c805beb592.png)
![Screen Shot 2021-07-20 at 11 49 42 AM](https://user-images.githubusercontent.com/18105491/126355634-e5d2a495-35c3-42dc-8212-d425b993564c.png)

**Comment by ferdingler** [comment]
Hi @ryj1023, I'm sorry you had issues adding your custom domain. We have recently improved our error messaging on the CNAMEAlreadyExistException to give customers better information on how to recover from it. This usually means one of these things: 

1) You have already used the same custom domain in another Amplify App in another region/account. 
2) You are using this domain in another service: LightSail or API Gateway. 
3) Your domain has an old CNAME record that points to a cloudfront.net URL from a previous Amplify App. 

Feel free to re-add the custom domain and you should get better information on what's going on. Thanks for reporting!
