### ISSUE TITLE
How to get CNAME records for my custom domain DNS

### ISSUE THREAD

**Issue by nilyin** [aws-amplify/amplify-console#2071]
**Which Specific Feature is your question related to?**
Custom domain setup

**Provide additional details e.g. code snippets**
Trying to add custom domain to amplify hosted frontend. getting error "domain activation" as on screenshot

The expected behavior in accordance with manual should be possibility to access a "View DNS records" option in "Action" drop-down (see 
<img width="829" alt="Снимок экрана 2021-07-19 в 21 46 48" src="https://user-images.githubusercontent.com/10655234/126215055-3f753d65-0953-4f24-8759-e9b240998088.png">
screenshot), but these item is disabled!

How to troubleshoot the domain problems in general?

my app ID - dgzmixxw4s34v   (dgzmixxw4s34v.amplifyapp.com)

Thank you, Nikolay

**Comment by ferdingler** [comment]
Hi @nilyin , I know you opened the issue a while ago, I'm sorry you had issues with custom domains. For future reference, here is our troubleshooting guide: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html. Feel free to re-open this ticket if you are having issues again.
