### ISSUE TITLE
Domain activation

### ISSUE THREAD

**Issue by yoyogias** [aws-amplify/amplify-console#2072]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2rh12ms92pe73

### Region

ap-southeast-1

### Step

Domain activation

### Status

Failed

### Issue or question

my domain is activating

**Comment by ferdingler** [comment]
Hi @yoyogias, I know you opened the issue a while ago but for future reference, here is our troubleshooting guide for custom domains: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html. Feel free to re-open if you are having issues again.
