### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by mkirashimas** [aws-amplify/amplify-console#2077]
**App Id**: d1ntqc6752mudf
**Region**: eu-south-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

In AWS Amplify Console I ahve selected the app and then "delete app" and removed it from my apps.
Now I am trying to re-create it and assign the same respective domain name in Domain management and SSL creation & SSL configuration are valid, but Domain activation is not:
"Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem."

I know I need to update the DNS configuration but your system seems to still be using the old configuration.
Under Actions, View DNS records is unavailable so I do not have access to the new records that have to be added to the domain registrar.

Is there a way to remove the old settings? what can I do? 

Thanks

**Comment by ferdingler** [comment]
Hello, I see that your domain is AVAILABLE now. Glad to see you were able to solve it. 

For future reference, this error happens when the DNS records in your domain still contain an old record pointing to the old CloudFront distribution. Deleting the record from your DNS and re-adding the domain is the solution.

**Comment by mkirashimas** [comment]
Indeed. This was resolved when I received access to the settings and had personally checked the DNS records and updated the values. Thank you for your response, @ferdingler; much appreciated.
