### ISSUE TITLE
Angular subscribed paramater URL

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-console#2079]
Hi,

For my angular 12 website I use subscribed parameters of URL to detect and to allow URLs different from the URL source.
I removed redirection rules but il fails. It works on my local work.
How to work around ?

Maybe I have to add a redirect rule, but I do not know the type.

**Comment by ferdingler** [comment]
Hello, thank you for reaching out. I am not able to understand your use case, could you please elaborate more? In the meantime, here is our documentation for redirect rules: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html . It explains the different types of rules and how to use them.

**Comment by rudyhadoux** [comment]
Hi,
The use case is very simple.
When the connexion to the website begins, Angular parses the URL. 
And in the starting page if there is '/result' it navigates to the Result page.
Very simple.

Then if Amplify Console hosts my website www.example.com, it should start with the URL www.example.com/result too.

**Comment by ferdingler** [comment]
Ok, this sounds similar to how React Router works and most SPA frameworks, which is that they use HTML5 history.pushState() to change browser location without triggering a server request, which works for users who land on your website from the root (example.com) but fails for users who land directly on a path (example.com/result). 

What you need to create in this case is a redirect rule to catch all those routes and serve them with index.html: 

```
Source address: 
</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|woff2|ttf|map|json)$)([^.]+$)/>

Target: 
/index.html

Redirect type: 
200 (Rewrite)
```

I hope this helps

**Comment by rudyhadoux** [comment]
Thanks a lot. I will test it.

**Comment by rudyhadoux** [comment]
It does not work. It refreshes.
example.com/result gives example.com.

**Comment by rudyhadoux** [comment]
It is my error.
It works thanks.
