### ISSUE TITLE
Next.js SSG 404 on page load of dynamic route

### ISSUE THREAD

**Issue by quinnturner** [aws-amplify/amplify-console#2085]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

SSG app: ddsf1gbrctse5 , SSR app: dc3blsn6e63vx

### Region

us-east-1

### Amplify Console feature

Redirects

### Describe the bug

When deploying an SSG version of Next.js on Amplify initial page loads on routes that are at least partially dynamic fallback to the root `index.html` rather than serving the dynamic page. The same code but with an SSR build works.

Here is the (default) `Rewrites and redirects` logic (same for SSG and SSR):
Source address: `/<*>`, target address: `/index.html`, type: `404 (Rewrite)`

SSG src: https://github.com/quinnturner/nextjs-amplify-ssg-routing
SSR src: https://github.com/quinnturner/nextjs-amplify-ssr-routing

### Expected behavior

When performing `next build && next export` on the attached project, this is the resulting file structure:

```
├── 404.html
├── index.html
├── with-indexes
│   ├── [a]
│   │   ├── [b]
│   │   │   └── static.html
│   │   ├── [b].html
│   │   └── static.html
│   ├── [a].html
│   ├── static
│   │   ├── [c]
│   │   │   ├── [d].html
│   │   │   └── static.html
│   │   └── [c].html
│   └── static.html
├── with-indexes.html
├── with-named
│   ├── [a]
│   │   ├── [b]
│   │   │   └── static.html
│   │   ├── [b].html
│   │   └── static.html
│   ├── [a].html
│   ├── static
│   │   ├── [c]
│   │   │   ├── [d].html
│   │   │   └── static.html
│   │   └── [c].html
│   └── static.html
└── with-named.html
```

Notably, Next.js "flattens" the `with-indexes` approach to use named files with no `index.html`s.

* https://main.ddsf1gbrctse5.amplifyapp.com/with-named/a should serve `/with-named/[a].html`.
* https://main.ddsf1gbrctse5.amplifyapp.com/with-indexes/a/b/static should serve `/with-indexes/[a]/[b]/static.html`

### Reproduction steps

1. Visit the website https://main.ddsf1gbrctse5.amplifyapp.com/ (SSG build)
2. Click the `/with-named/a` in the `anchor component` section (or just click here: https://main.ddsf1gbrctse5.amplifyapp.com/with-named/a)
3. Notice that the app that is served is the fallback `index.html`

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: out
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

I have tried to do various rewrites and redirects but I have not even been able to perform a workaround.

**Comment by zugger14** [comment]
try adding this trailingSlash: true option (on next.config.js) file.

**Comment by quinnturner** [comment]
https://trailing-slash.ddsf1gbrctse5.amplifyapp.com/with-named/a/static/

Does not work

**Comment by victorccccc** [comment]
Hi, according to your src repository, uri `/with-named/[a]` serves `/with-named/[a].html` and  `/with-indexes/[a]/[b]/static` serves `/with-indexes/[a]/[b]/static.html`

Feel free to reopen if you have other question, thanks!
