### ISSUE TITLE
Troubleshooting custom domain name activation

### ISSUE THREAD

**Issue by iamzoh** [aws-amplify/amplify-console#2087]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2qr5ws0tmr8wq

### Region

us-east-1

### Step

Domain activation

### Status

Failed

### Issue or question

I receive this error when attempting to activate my custom domain: `One or more of the CNAMEs you provided are already associated with a different resource.`

The [Troubleshooting Guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error) references a potential duplicate CloudFront distribution, but I do not have any CloudFront Distributions on my AWS account. I also do not have another Amplify app using this custom domain. 

I purchased the domain via Route53's Domain Registration Service. 

### Error message

One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by adlershai** [comment]
I have the same issue with 
App ID: dyw0wxv3jeu7n
Region: us-east-2

**Comment by nimacks** [comment]
@iamzoh our records indicate that this domain is now available. iam***.com. Re-open if you have any other issues.

**Comment by iamzoh** [comment]
Hey @nimacks iam***.com is new domain I bought because the one I first purchased won't work with my Amplify App.

If you see Amplify App `d2qr5ws0tmr8wq`, there's domain failing to register and I'm asking for assistance with that.
