### ISSUE TITLE
Domain activation

### ISSUE THREAD

**Issue by FeMonteiro** [aws-amplify/amplify-console#2089]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2d3mniy3abssh

### Region

sa-east-1

### Step

Domain activation

### Status

Failed

### Issue or question

I tried to add the dns configuration, following all the steps of the platform.

But I've got an error on Domain Activation step.

Our client is owner of the domain, and if i click on "Retry" button, the registers will change, and we'll have to open a new ticket.

We are facing this problem in multiple clients.

### Error message

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: The status of this certificate request is "Failed". One or more domain names have failed validation due to a Certificate Authority Authentication error. Learn more: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-caa.html

**Comment by ferdingler** [comment]
Hi @FeMonteiro, 

The CAA error happens when your domain has a CAA DNS record that does not specify Amazon as an approved Certificate Authority. The solution is to either remove your CAA records entirely, or add at least one of these records to your domain DNS: 

```
example.com.  CAA 0 issue "amazon.com"
example.com.  CAA 0 issue "amazontrust.com"
example.com.  CAA 0 issue "awstrust.com"
example.com.  CAA 0 issue "amazonaws.com"
```

**Comment by nimacks** [comment]
Our records indicate that this domain is now available.
