### ISSUE TITLE
Moving custom domain between different AWS Amplify accounts deployments

### ISSUE THREAD

**Issue by 0luftballoons** [aws-amplify/amplify-console#209]
**Issue/question**
We currently have an app deployed under AWS Amplify, using an account "Account-A", and using a custom subdomain, "foo.bar.com".
We'd like to move/redeploy the app using AWS Amplify, but using a different account, "Account-B", and using the same subdomain, "foo.bar.com".

I found a similar issue https://github.com/aws-amplify/amplify-console/issues/22
and would just like to confirm with you that this would still be an appropriate set of steps to follow?

**Comment by garyleefight** [comment]
@0luftballoons . This is the right steps for now.
