### ISSUE TITLE
Hosting a Javascript bundle for use on third-party sites

### ISSUE THREAD

**Issue by davekiss** [aws-amplify/amplify-console#21]
** Please describe which feature you have a question about? **
Does Amplify hosting have some kind of measure in place to prevent/throttle the use of assets outside of the Amplify domain name? I’m trying to host a Javascript bundle that will be placed on many different sites but it’s not loading successfully, but it works fine when loading from my local machine or if it is hosted on a public S3 bucket.

** Provide additional details**
- Upload a JS bundle to Amplify and attempt to load it on a third-party domain. Script attempts to load but ultimately times out/browser runs out of memory

- Upload the same bundle to S3 public bucket and load it on a third-party domain. note how it works as expected

**Comment by garyleefight** [comment]
@davekiss Hi, can you run curl ${amplify url} locally and get your json object?

**Comment by swaminator** [comment]
@davekiss reminding you about this issue. Can you curl your amplify url?

**Comment by davekiss** [comment]
Yes, I was able to curl the amplify url. I think it is working as expected now, was something changed?

**Comment by swaminator** [comment]
Nope. Closing this issue.
