### ISSUE TITLE
Deploying specific CodeCommit CommitId (not a retry of a previous job) 

### ISSUE THREAD

**Issue by clownbaby** [aws-amplify/amplify-console#2100]
**Please describe which feature you have a question about?**

I would like to deploy a specific commit to my amplify app branch, which is connected to a CodeCommit repository.
There doesn't seem to be a way to do this.

**Provide additional details**

I have an app configured to deploy from 'master' branch.

I would like to start a build with a specific commit from that branch.

The start-job API call seems to have a 'commit-id' parameter, but I don't understand how to use it to specify an arbitrary CommitId.

According to the StartJob documentation (  https://docs.aws.amazon.com/amplify/latest/APIReference/API_StartJob.html#API_StartJob_RequestSyntax ), there are four types of Jobs I can start:

**RELEASE**: Always uses 'HEAD,' so commit-id is ignored.
  -- Example 1 below

**RETRY**: Uses whatever commit applies to the job being retried, so commit-id is ignored.  I could use RETRY to deploy a previously-deployed CommitId, but that doesn't help me deploy any other CommitIds.

**MANUAL**: Not applicable to a connected branch.
  -- Example 2 below

**WEB_HOOK**: I believe web-hooks always use 'HEAD,' so commit-id is ignored, I would guess.
  -- Example 3 below

In what situation would the 'commit-id' parameter NOT be ignored?

**More importantly, is there a way to start a job with a specific (non-retry) CommitId on a connected branch?**

**What AWS Services are you utilizing?**

AWS Amplify API

**Provide additional details e.g. code snippets**

For example: 

Example 1:
```
$ aws amplify start-job --app-id <some app-id> --branch master --commit-id <some non-HEAD CommitId> --job-type RELEASE
{
    "jobSummary": {
        "commitId": "HEAD", 
        "commitTime": <some time>,
        "status": "PENDING",
        "jobId": <some job id>,
        "jobArn": <some job arn>
    }
}
```

Example 2:
```
$ aws amplify start-job --app-id <some app-id> --branch master --commit-id <some non-HEAD CommitId> --job-type MANUAL

An error occurred (BadRequestException) when calling the StartJob operation: The requested jobType MANUAL does not support.
```

Example 3:
```
$ aws amplify start-job --app-id <some app-id> --branch master --commit-id <some non-HEAD CommitId> --job-type WEB_HOOK

An error occurred (BadRequestException) when calling the StartJob operation: The requested jobType WEB_HOOK does not support.
```

**Comment by ganipcanot** [comment]
I was able to verify this behavior on my end as well.  I'm putting in a code fix that will allow customers to use the `RELEASE` job type to trigger builds against arbitrary commits.  Previously the `RELEASE` job type would always use `HEAD` but with my upcoming fix that will no longer be the case - if you specify a commitId we will use that to process the job.

So in the future you'll be able to do something like this: `aws amplify start-job --app-id <some app-id> --branch master --commit-id <some non-HEAD CommitId> --job-type RELEASE` and it won't just ignore the `commit-id` field.

**Comment by clownbaby** [comment]
Thanks!
