### ISSUE TITLE
Domain activation

### ISSUE THREAD

**Issue by mikelin2** [aws-amplify/amplify-console#2101]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1eqrct9sbxwxw

### Region

us-west-2

### Step

Domain activation

### Status

Failed

### Issue or question

I have verified the domain using CNAM.
I have added the CNAM for cloudfront and point the custom domain (www.tcrindustries.com) to cloudfront.
Yet, I am getting the Domain Activation error.

Not sure wh

### Error message

Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Comment by nimacks** [comment]
According to our records, this domain is now available. Re-open if you have any further issues.
