### ISSUE TITLE
Cloudfront doesn't connect with the repository

### ISSUE THREAD

**Issue by mikelin2** [aws-amplify/amplify-console#2109]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-west-2:858275305422:apps/d1eqrct9sbxwxw

### Region

US-West-2

### Step

Domain activation

### Status

Failed

### Issue or question

According to the process, I should verify that the cloudfront domain works before pointing the DNS to the domain.

d1287u1dxzftzu.cloudfront.net

Currently, the cloudfront URL is not rendering.

### Error message

This d1287u1dxzftzu.cloudfront.net page can’t be found
No webpage was found for the web address: https://d1287u1dxzftzu.cloudfront.net/
HTTP ERROR 404

**Comment by nimacks** [comment]
According to our records your domain is now available at `tc************s.com`. Reopen if you have any other issues.
