### ISSUE TITLE
custom godaddy domain, managed with Route53 not working

### ISSUE THREAD

**Issue by anjalimaheshwari** [aws-amplify/amplify-console#211]
Currently a Wix website is hosted on my domain but now I am trying to develop my own website. I disabled my Wix website connection to the domain. I followed the steps in this article: https://read.acloud.guru/how-to-deploy-a-custom-domain-with-the-amplify-console-a884b6a3c0fc 
My website it available on the domain Amplify provides under amplifyapp. However, the custom domain is not working. 

I've also done everything under the Godaddy section except for actually migrating the domain in the aws docs: https://docs.aws.amazon.com/amplify/latest/userguide/howto-third-party-domains.html 
(I created a template and applied that template to the domain name in GoDaddy and added the two CNAME values).
 
My DNS is fully activated on the AWS side and all of the nameservers are correct. Unfortunately, when I go to the URL, it says that the IP address cannot be found. I also haven't received any errors. 

Thanks in advance

**Comment by anjalimaheshwari** [comment]
On chrome I get "The site cannot be reached.... server IP address could not be found."

**Comment by Joycehao19** [comment]
Hi @anjalimaheshwari 
Could you please send me your appID(App settings > general), region and the status of domain management page?
