### ISSUE TITLE
Next.js SSR build incorrectly determines page to be SSR instead of SSG

### ISSUE THREAD

**Issue by quinnturner** [aws-amplify/amplify-console#2114]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

Probably can't share unless I DM someone

### Region

us-east-1

### Amplify Console feature

Build settings

### Describe the bug

Amplify incorrectly identifies an SSG page as an SSR page when it includes (some combination of) dynamic imports, writing, and reading from the filesystem.

### Expected behavior

The below snippet (when using `getStaticPaths`, `getStaticProps`, and the filesystem) should result in an SSG path, not an SSR path.

### Reproduction steps

Have this in a page file:

```tsx
// this snippet is paraphrased but functionally very similar to our usage

// This function gets called at build time
export const getStaticPaths: GetStaticPaths<TalentStaticPathsProps> =
  async () => {
    const data = await expensiveCallFetchAllData();
    // Get the paths we want to pre-render based on posts
    const fileData: Record<string, any> = {};
    const paths =  data.map(d) => {
      fileData[d.id] = d;
      return { params: { id: d.id } };
    });
    const fs = await import("fs/promises");
    const dir = "./.next/cache/user";
    const stat = await fs.stat(dir);
    if (!stat.isDirectory()) {
      await fs.mkdir(dir, { recursive: true });
    }
    await fs.writeFile(`${dir}/data.json`, JSON.stringify(fileData), {
      encoding: "utf-8",
      flag: "w",
    });

    // We'll pre-render only these paths at build time.
    // { fallback: false } means other routes should 404.
    return { paths, fallback: false };
  };

let cachedFile: Record<string, any>;

// This also gets called at build time
export const getStaticProps: GetStaticProps< StaticPathsProps> = async ({ params }) => {
  const queryClient = new QueryClient();
  if (!params) {
    throw new Error("Excepted params");
  }
  const { id } = params;
  if (!cachedFile) {
    const fs = await import("fs/promises");
    cachedFile = await fs
        .readFile("./.next/cache/user/data.json", "utf-8")
        .then((t) => JSON.parse(t) as Record<string, any>);
  }
  const getDataQuery = () => cachedFile[id];
  await queryClient.prefetchQuery(["data", id], getDataQuery);

  // Pass post data to the page via props
  return {
    props: {
      dehydratedState: dehydrate(queryClient),
      seo: {
        description: data?.description ?? null,
        title: data?.title ?? null,
        keywords: data?.keywords ?? null,
      },
    },
  };
};
```

This will result in a Lambda route, not an SSG route.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
      - .next/cache
```

**Comment by Athena96** [comment]
hi @quinnturner can you please share you appId and your package.json (you can also email your package.json to aws-amplify-customer@amazon.com if you don't want to share it here) thanks!

**Comment by hughesjj** [comment]
Hey, make sure your `package.json`'s definition for "build" does not include a "next export" statement.  Also, in `amplify.yml` (assuming you have one configured), take care to ensure your output directory is `.next` and not `out`

**Comment by quinnturner** [comment]
Hi @hughesjj, neither were the case. I use SSR build (as defined in the app), .next output folder, next build as the command.

While I am not blocked by this anymore since I use ISR instead of SSG for this route, I suspect it's still an issue.

**Comment by victorccccc** [comment]
Hi, according to the docs: https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app, we detect SSR app by inspecting `package.json` file in your **app root** folder, . Please make sure you have correct settings in `build script`. Thanks! Feel free to reopen if issue persists.
