### ISSUE TITLE
SSL configuration

### ISSUE THREAD

**Issue by nguyenmqua** [aws-amplify/amplify-console#2115]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d34owdjfejvflb

### Region

us-east-2

### Step

SSL configuration

### Status

Running

### Issue or question

Help

### Error message

nothing is happening!

**Comment by lrob7325** [comment]
@nguyenmqua Hey, I was wondering if you heard from AWS, or if your status changed in Amplify? I just created an issue because it's been 30 hours for me, and I see we're both in the same region.

**Comment by nimacks** [comment]
Our records indicate that this domain is now available. Re-open if you're still facing issues.
