### ISSUE TITLE
Domain activation

### ISSUE THREAD

**Issue by FeMiqui** [aws-amplify/amplify-console#2122]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3ad4ndp8re3ej

### Region

us-east-1

### Step

Domain activation

### Status

Failed

### Issue or question

I'm trying to set up a custom domain to my website: runeinnovations.com. However, every time it is in the step "domain activation", it shows an error -the image will be uploaded in the error message. I have set my third-party domain in Route 53 and even deleted the route and recreated it. 

### Error message

![image](https://user-images.githubusercontent.com/51029840/127751672-05fca4a3-59a3-4796-aba5-fe391203e86a.png)

**Comment by nimacks** [comment]
Our records indicate that this app is no longer available.
