### ISSUE TITLE
build timeout example nextjs ssg

### ISSUE THREAD

**Issue by fdoyanes** [aws-amplify/amplify-console#2124]
### Before opening, please confirm:

- [x] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [x] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

I try to deploy an example application with nextjs I have done all the steps to do the ssg unfortunately the build does not advance after what appears in the image but it ends in build time out
<img width="1262" alt="Captura de pantalla 2021-08-01 a las 14 17 55" src="https://user-images.githubusercontent.com/1696438/127781366-6e567599-9cb9-4d93-86af-08d712fb7ca9.png">

### Expected behavior

You try to deploy through codecommit

### Reproduction steps

You try to deploy through codecommit

**Comment by Athena96** [comment]
Hi @fdoyanes can you please try to run a build locally to see how long it takes roughly.
Also, can you please send you appId, so we can take a look as well. Thanks!

**Comment by calavera** [comment]
@fdoyanes you can increase the time that your builds run by setting the `_BUILD_TIMEOUT` environment variable in your app settings. You can read me about this variable in the docs linked below:

https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#amplify-console-environment-variables

Let me know if the problem still persists after setting that variable, and I'll happily reopen the issue.
