### ISSUE TITLE
SSL configuration

### ISSUE THREAD

**Issue by shashikantvani** [aws-amplify/amplify-console#2126]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2s2jcs2v75tl2

### Region

ap-southeast-2

### Step

SSL configuration

### Status

Running

### Issue or question

i want to run project using this server

**Comment by ferdingler** [comment]
Hi @shashikantvani, can you please provide more information about your issue/question. Feel free to reopen if you have additional info so we can help you better.
