### ISSUE TITLE
SSL certificate for root domain is showing invalid.

### ISSUE THREAD

**Issue by teslaLDead** [aws-amplify/amplify-console#213]
**App Id**: d1adxv4fcyjebh
**Region**: Mumbai
**Step**: SSL certificate for custom third party domain

**Issue/question**
The SSL certificate configured by amplify for the root domain i.e **domain.com** is showing invalid, while the SSL certificate for the **www.domain.com** url is working fine. I am using godaddy for my domain management. I have configured a redirect from root domain to the **www** subdomain in my godaddy as well as amplify aws account. 
Whenever I browse to **domain.com** it shows privacy error with the error message 
**NET::ERR_CERT_COMMON_NAME_INVALID** and my page does not redirect to the www domain.

I have configured the CNAME record for the ssl certificate and the www domain at godaddy properly.

**Comment by garyleefight** [comment]
@teslaLDead. The reason is that the certificate we issued for you is for www.domain.com and is mismatched with domain.com.  You should set redirect rule for your root domain.

**Comment by teslaLDead** [comment]
I solved the issue by using aws name servers instead of godaddy NS. Configured aws route 53 to set my CNAME and other records. It is working fine now.

**Comment by tommerkle1** [comment]
@teslaLDead I am having the exact same issue and followed what you described to resolve- however I am now getting a https://shortener.secureserver.net/error_404 response when trying to navigate to the root domain. Any thoughts?

**Comment by dsk6677** [comment]
After the long research, the AWS amplify is not supporting the https://example.com, it only redirect URL to www by using the domain forward option with our domain provider, The solution was we need to replace our AWS Route 53 NS Records with our domain provider NS record, then it will work with https://example.com

Anyone have better solution please share here

Thanks in Advance

**Comment by oliver-leung** [comment]
In case anyone comes across this problem in the future, we've added a FAQ section to our docs: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#ssl-HTTPS-errors-on-domain
