### ISSUE TITLE
Domain activation

### ISSUE THREAD

**Issue by felipehv** [aws-amplify/amplify-console#2132]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1n5yymf5qivnm

### Region

us-east-2

### Step

Domain activation

### Status

Failed

### Issue or question

My domain can't be activated.
I am using route53 for faster deployment but it continues to say that the CNAME does not match the one provided by amplify. But Amplify is supposed to modify the CNAME for me and, as I could see in Route 53, the CNAME did match the current cloudfront distribution domain, so I don't know what is the problem here if everything is perfectly configured.

### Error message

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by felipehv** [comment]
Is there any way to know what is the different resource associated?

**Comment by syngate** [comment]
We are also having the same issue using AWS Amplify, the CNAME records do get created but an error appears at the validation stage suggesting that the CNAME is already associated to another resource. 

As a workaround I seem to be able to use a different subdomain, however, when trying with the root domain we keep getting this error message despite having removed the records before retrying.

![image](https://user-images.githubusercontent.com/75013259/129456330-5c927127-608b-43be-beef-3b803fc53b13.png)

**Comment by nimacks** [comment]
> Is there any way to know what is the different resource associated?

We are working on surfacing this information in the console to make it easier for customers to view associated resources.

Looks like your domain is resolving now app*.g****.w***

**Comment by reyts** [comment]
I have a similar issue and the website has been down for a week now.
![image](https://user-images.githubusercontent.com/73900693/130339881-7206e296-245d-42a9-bcc6-a3c24f925a10.png)
I don't have any cloudfront setup. So I can't even troubleshoot as described in this document https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

I really like AWS Amplify when it works but I can't even explain to anyone why the site is down .

**Comment by felipehv** [comment]
@reyts I had to check at Cloudfront if the domain was assigned to any distribution, no matter if the cname is pointing to the cloudfront distribution of the Amplify deploy.
Just unassign the domain of the other cloudfront distribution or delete the distribution and it will work.

**Comment by felipehv** [comment]
If you don't have cloudfront set up, check another resources such as elastic beanstalk, API Gateway, etc.
