### ISSUE TITLE
[amplify-codecommit]Unable to clone repo...

### ISSUE THREAD

**Issue by sebastian-bustillo** [aws-amplify/amplify-console#2133]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1artn2t6nzgkz

### Region

us-east-1

### Step

Amplify Build: Cloning Repo

### Status

Failed

### Issue or question

So I used a CFN template to provision an empty Amplify app, then I try to add an env by using a codeCommit repo. The service role is provided with the right permissions. Why is my amplify app not being able to clone my codeCommit repo?

### Error message

Fatal: unable to access 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/<repoName>  The requested URL returned error: 403

**Comment by kahdojay** [comment]
@sebastian-bustillo looks like the app was deleted. Do you mind setting up a new repro app and share the id? If you can also share the CFN template you used it would be helpful. Feel free to share here or if you prefer you can email it to aws-amplify-customer@amazon.com

**Comment by hughesjj** [comment]
I was getting this issue for a while last week.  I believe making a dummy "master" branch in gitlab fixed it for me.

**Comment by behrooziAWS** [comment]
@sebastian-bustillo The usual cause for this is that the role associated with your app doesn't have the necessary codecommit:GitPull permissions.  These permissions are not included in the AdministratorAccess-Amplify managed policy  and must be added.  If this is still happening, please reopen and provide a current appid and what permissions or managed-policies you have associated with the role.
