### ISSUE TITLE
Amplify not including zip file inside React project

### ISSUE THREAD

**Issue by jacksonHendric** [aws-amplify/amplify-console#2135]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Categories

hosting

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I use amplify for CI/CD, the react project has a amplify.yml file that is used to automatically build when pushed into releases/production.
This works great but if I use the leaflet library and have a .zip file that has map routing information, when the build is complete the routing information is missing. The zip file is essentially removed or not included in the build somehow.

If I manually build the project locally and upload the build directory into amplify that zip is all good and the routes can be seen on the map after deployment on amplify.

Is there a way to allow the zip file to be included in my CI/CD?

( zip file location in project --> src --> routes.zip )

### Expected behavior

amplify.yml file is used for CI/CD, zip file is included in the build and the routing info is available

### Reproduction steps

Try doing CI/CD using amplify.yml with a .zip file inside the project files. 

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by kahdojay** [comment]
@jacksonHendric can you provide your appId and example build number, and your amplify.yml, stripping any sensitive info?

**Comment by jacksonHendric** [comment]
> @jacksonHendric can you provide your appId and example build number, and your amplify.yml, stripping any sensitive info?

AppId: dao95hbd985ep

`version: 1
frontend:
  phases:
    preBuild:
      commands:
        - eval $(ssh-agent -s)
        - ssh-add <(echo $AUTO_KEY | base64 -d)
        - git submodule update
        - yarn
        - unset CI #they treat warnings as errors in CI
        - GENERATE_SOURCEMAP=false
    build:
      commands:
        - yarn run build
    postBuild:
        commands:
            - cd build/static/js
            - rm *.map
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*`

**Comment by jacksonHendric** [comment]
Any updates on this?

**Comment by behrooziAWS** [comment]
It should be accessible here because I see the .zip file correctly uploaded: 

https://test-jumparound.dao95hbd985ep.amplifyapp.com/static/media/WinkSystem_Routing_namefix.d5a68bda.zip

However, there is a [redirect rule for SPA apps](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa) that doesn't include .zip which is redirecting it to your index.html page.  If you update this in the Rewrites and Redirects section of your app to add .zip to it, it should work.
i.e.: `</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json|zip)$)([^.]+$)/>`
