### ISSUE TITLE
React.js and cache invalidation

### ISSUE THREAD

**Issue by maiconcarraro** [aws-amplify/amplify-console#214]
**Describe the bug**
I created an app using create-react-app, connected my repo to amplify console and deployed. Then I did some changes and pushed to the master branch. Waited for deploy finish, went to amplify's url and nothings changes. I need to force cache reload (CTRL+SHIFT+R) to see new changes.

**To Reproduce**
1. Use create-react-app
2. Configure and deploy on amplify console
3. Make new changes on repo
4. Push
5. Wait for deploy
6. Check url

**Expected behavior**
I expected to see new changes without force reload cache.

**Comment by garyleefight** [comment]
@maiconcarraro. Could you provide your appId and region? It could be a bug for us.

**Comment by maiconcarraro** [comment]
@garyleefight Sure, it's **us-east-1** and **d3n05fd1eoav4x**

**Comment by maiconcarraro** [comment]
@swaminator that's right, it was service worker. sorry about that.

**Comment by akabynga** [comment]
Hi there, did you resolve the issue? I have the same :)

**Comment by maiconcarraro** [comment]
hey @akabynga yeah, there are 2 approaches:

1 - Unregister service worker, it will prevent caching. On your `app.js`:

```js
import * as serviceWorker from "./serviceWorker";
serviceWorker.unregister();
```

2 - Manage to reload everytime has a new registration (automatically), during register you can send onUpdate logic
```js
serviceWorker.register({
  onUpdate: registration => {
    registration.unregister().then(() => {
      window.location.reload();
    });
  }
});
```
