### ISSUE TITLE
SNS set up configuration while creating Amplify App using  Cloudformation 

### ISSUE THREAD

**Issue by akanungo22** [aws-amplify/amplify-console#2146]
**Please describe which feature you have a question about?**

**Provide additional details**

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

**Comment by Athena96** [comment]
Hi @akanungo22 this is not possible at the moment with CloudFormation alone. You would have to do it [programmatically](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Amplify.html) using  our AWS sdk, or through the [console](https://docs.aws.amazon.com/amplify/latest/userguide/notifications.html). We can add this as a feature request.

**Comment by akanungo22** [comment]
Ok.. thank you..

**Comment by akanungo22** [comment]
I have one more query.. I have set it up manually.. but I want to send notification based on certain status of BUILD stage like if its FAILED only, where do I configure that? Because I don't find that in console .

**Comment by Athena96** [comment]
Our notifications send a message when the build starts and then the status of the build Success/Fail when it ends.

If you want this level of customization. You could implement something similar by:
1. create a lambda that is triggered by the sns topic we create: https://docs.aws.amazon.com/amplify/latest/userguide/notifications.html
2. in the lambda, you can use the aws Amplify sdk to get the build status of the app.
3. then do any custom alerts for if the build fails.

**Comment by akanungo22** [comment]
Thank you for the guidance :)

**Comment by Athena96** [comment]
Closing, feel free to re-open if you have any related issues. thanks!
