### ISSUE TITLE
How to change github repository for a NEW app. Not an existing app. 

### ISSUE THREAD

**Issue by tmckeagecirs** [aws-amplify/amplify-console#2147]
I created an amplify app using github. I need to make a second app using a different github account. When I go to create a new amplify app under github I am only able to use the other accounts repo's. How do I create a new app using a second repo without removing the webhooks to the first?

Deleting webhooks in the first account would disable the first app and therefore is not a reasonable option. Moving either repo to a different git provider is not an option due to organizational constraints. 

I am using AWS amplify in the web console.

I have no code snippets, if this is possible through the CLI please let me know because I have been unable to locate that option.

**Comment by Athena96** [comment]
Hi @tmckeagecirs unfortunately the workaround for this is to sign into the console in incognito mode, then it will ask you to sign into a github repo. Please re-open if this doesn't work for you.
