### ISSUE TITLE
Build fails with "TypeError: Cannot read property 'trim' of undefined"

### ISSUE THREAD

**Issue by leemhenson** [aws-amplify/amplify-console#2148]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2dqnnzb9dhjm0

### Region

eu-west-2

### Amplify Console feature

Backend builds

### Describe the bug

Frontend build fails with this message shown in a red box:

> There was an issue connecting to your repo provider, click "Reconnect repository" in General Settings, and then try your build again.

If I look at the `Cloning Repository` log output I see:

```
2021-08-10T20:15:05.212Z [INFO]: Git SSH Key acquired
2021-08-10T20:15:05.287Z [INFO]: # Cloning repository: git@github.com:<organisation>/<repo>.git
2021-08-10T20:15:05.334Z [INFO]: Agent pid 137
2021-08-10T20:15:05.370Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-08-10T20:15:05.690Z [INFO]: Cloning into '<repo>'...
2021-08-10T20:15:06.182Z [INFO]: Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
2021-08-10T20:15:12.921Z [INFO]: # Checking for Git submodules at: /codebuild/output/src899994275/src/<repo>/.gitmodules
2021-08-10T20:15:13.021Z [INFO]: # Retrieving environment cache...
2021-08-10T20:15:13.054Z [INFO]: # Retrieved environment cache
2021-08-10T20:15:13.054Z [INFO]: ---- Setting Up SSM Secrets ----
2021-08-10T20:15:13.054Z [INFO]: SSM params {"Path":"/amplify/d2dqnnzb9dhjm0/<app>/","WithDecryption":true}
2021-08-10T20:15:13.560Z [WARNING]: !TypeError: Cannot read property 'trim' of undefined
2021-08-10T20:15:13.562Z [ERROR]: !!! TypeError: Cannot read property 'trim' of undefined
2021-08-10T20:15:13.562Z [INFO]: # Starting environment caching...
2021-08-10T20:15:13.563Z [INFO]: # Environment caching completed
```

If I try reconnecting the repository, I can see it recreates the webhook but the build fails in exactly the same way.

### Expected behavior

The build succeeds or gives a more descriptive error about what I need to fix.

### Reproduction steps

It happens every time I attempt to build my app. 

### Build Settings

```yaml
version: 1
applications:
  - approot: monorepo/packages/<app>
    frontend:
      phases:
        prebuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        basedirectory: .next
        files:
          - "**/*"
      cache:
        paths:
          - node_modules/**/*
```
```


### Additional information

This is a monorepo. I had an app set up previously which was working, but then this error came up and I tried creating a new app in the hope that starting from scratch again would clear it.

**Comment by RealDrewKlayman** [comment]
It looks like where ever you are using the .trim you are not defining the variable that you are trimming.

If you just want to turn off TS errors you can add this to `next.config.js` but it is not recommended:
```
  typescript: {
    // !! WARN !!
    // Dangerously allow production builds to successfully complete even if
    // your project has type errors.
    // !! WARN !!
    ignoreBuildErrors: true,
  },
```

**Comment by Athena96** [comment]
@leemhenson does the build compile/build locally? If so this might be an issue with the path/directory you're using for your monorepo in your buildspec

**Comment by leemhenson** [comment]
@RealDrewKlayman This isn't an issue with the code in my project. The `trim` error message is coming from inside amplify during the repo clone process. I included the logs above.

@Athena96 Yes, my project builds and runs locally without errors. I also believe the monorepo config to be correct inside my amplify.yml because I previously had a working installation on Amplify with the exact same yml file. I deleted that previously-working installation because it started reporting errors about needing to be reconnected to my repository. That reconnection process never completed successfully due to the trim error, so I deleted the entire app and started again. I continue to have the same problem on my new app, which is the one I'm including the ID for in this ticket.

**Comment by Athena96** [comment]
@leemhenson I reproed your issue.
The problem is that `approot` in your build spec should be `appRoot`.
Reference this [doc](https://docs.aws.amazon.com/amplify/latest/userguide/monorepo-configuration.html#monorepo-yml-syntax) for the correct capitalization, I think there were a couple other capitalization errors.

Regardless, we should have a mechanism to provide a less cryptic error message.

**Comment by leemhenson** [comment]
🤦 You are right. Looks like I lowercased the keys in amplify.yml somehow. Thanks for pointing it out! 🙏
