### ISSUE TITLE
Domain activation is Failed - [CName already associated with a different resource]

### ISSUE THREAD

**Issue by shimcup** [aws-amplify/amplify-console#215]
**App Id**: d2m2l8ev6wkq0g
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I keep getting the error of CNAME being associated with a different resource. I am using my route53 domain that I used to host my app with using S3 with, but I don't think there is any other resource I am using.

**Error message**
If there is an error message, please include it here.
Error message: One or more of the CNAMEs you provided are already associated with a different resource. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by garyleefight** [comment]
@shimcup. Searched your distribution. Looks like your domain is attached to accountID:
392xxxxx6650 with Distribution id: d3a0leoic8awjx. Please deleted it first.

**Comment by shimcup** [comment]
Hi, so seems like that's coming from the certificate manager that I created for one of the CloudFront distributions that I already deleted. I checked the CloudFront console, and I don't have any distributions there. I tried to delete the certificate, but it says that the certificate is associated with the deleted distribution. Do I need to delete the distribution via CLI?

**Comment by shimcup** [comment]
any updates on this?

**Comment by Joycehao19** [comment]
@shimcup Did you still have this issue when you add the custom domain?
