### ISSUE TITLE
Is it possible to set alerts on an amplify env?

### ISSUE THREAD

**Issue by ilansh** [aws-amplify/amplify-console#2151]
**Please describe which feature you have a question about?**
I have several environments for a single amplify App and I want to be able to use amplify provided metrics to monitor my production environment, but I'm not sure if it is possible to filter noise from other envs.
In particular, is it possible to configure alarms only on production env?

**Provide additional details**
For example, alert on 4XX, 5XX errors in production env

**What AWS Services are you utilizing?**
Appsync, lambda, dynamodb

**Provide additional details e.g. code snippets**
I've seen this blog https://medium.com/swlh/add-monitoring-to-your-amplify-app-by-using-amplify-framework-d4c43b2bb84b which describes what I want to achieve, and there's also reference to conditionally alerting on prod environment, but I don't understand how to achieve this, and whether it is possible at all.

**Comment by Athena96** [comment]
Hi @ilansh I think this: https://docs.aws.amazon.com/amplify/latest/userguide/access-logs.html
is what you're looking for. Thanks!

**Comment by Athena96** [comment]
closing, feel free to re-open if my suggestion doesn't work

**Comment by ilansh** [comment]
> Hi @ilansh I think this: https://docs.aws.amazon.com/amplify/latest/userguide/access-logs.html
> is what you're looking for. Thanks!

Thanks for the quick reply @Athena96 , though I don't think that was what I'm looking for.  
I am quite aware that amplify emits metrics to cloudwatch, and that alerts can be configured on those metrics, which is what is specified in the link you provided.  
The link also specifies that the available dimensions are `aws account` and `app`, but I'm looking for `env` (within a single app).   
Is there some way to achieve this kind of resolution with the metrics?

**Comment by behrooziAWS** [comment]
Hi, you are correct that the most granular you can setup metrics is per app.  The current workaround is to use a different app for your non-prod environments.
