### ISSUE TITLE
When launching Amplify App  using Cloudformation Template, the 1st Build is not triggered automatically

### ISSUE THREAD

**Issue by akanungo22** [aws-amplify/amplify-console#2154]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

When launching Amplify App  using Cloudformation Template, the 1st Build is not triggered automatically

### Expected behavior

The moment the Amplify App is created using cloud formation, atleast the 1st Build should run like it happens when the App is created from console.

### Reproduction steps

 Created Amplify App using cloudformation template.

**Comment by swaminator** [comment]
@akanungo22 that is by design. An Amplify app just consists of the actual project resources. To trigger a build you could use deploy hooks: https://docs.aws.amazon.com/amplify/latest/userguide/webhooks.html

**Comment by akanungo22** [comment]
@swaminator then webhook creation is not available in Amplify Cloudformation ?
