### ISSUE TITLE
Is Conditional Build possible? 

### ISSUE THREAD

**Issue by akanungo22** [aws-amplify/amplify-console#2156]
Can we build the amplify app, based on certain conditions, not that for every code merge we will build?

I am not talking about AMPLIFY_DIFF_DEPLOY, some other conditions, where I can build and deploy the App, based on my requirements.

Thanks in advance

**Comment by akanungo22** [comment]
I mean can we add any approval stage in the amplify pipeline for selective Deploy?

**Comment by siegerts** [comment]
Hi @akanungo22, do you mind providing a bit more context (process, git flow, environments, etc)?  Currently, it's not possible to suspend the build for approvals but there are some options (below) if the approval process follows a a multi-environment promotion flow. So, the deploy to prod is predicated on a merge into a specific prod branch _instead_ of selectively filtering commits to a single branch for deploy/no-deploy.


Skip build for a commit 
https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#skip-build-for-a-commit

Bash scripting for conditional build logic
https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html 

Pattern-based feature branch deployments
https://docs.aws.amazon.com/amplify/latest/userguide/pattern-based-feature-branch-deployments.html

PR Previews
https://docs.aws.amazon.com/amplify/latest/userguide/pr-previews.html

**Comment by akanungo22** [comment]
Hello @siegerts, we actually follow trunk based, so for 3 environment(dev/stage/prod) all are deployed from "Main" branch.
That's why, wanted one approval process stage before Deploy

**Comment by siegerts** [comment]
In that scenario, can the [Skip build for a commit](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#skip-build-for-a-commit) help? Larger PRs merged into `main` can be squashed and preprended with`[skip-cd]`.

**Comment by akanungo22** [comment]
I will try that..

**Comment by akanungo22** [comment]
Hope it does not skips the CD which is implemented by CodePipeline. As we have mono repo with UI and Backend code together

**Comment by Athena96** [comment]
@akanungo22 `[skip-cd]` will only skip with the Amplify build

**Comment by Athena96** [comment]
closing, feel free to re-open if you have any other questions. thanks!
