### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by essudhir** [aws-amplify/amplify-console#2165]
Sir,

When I am go through AWS Amplify - All apps GettingStarted Add environment & trying to uploading the index.html RAR file into the program, it will gives error message i.e. "Unsupported Content Please zip your project's root directory and try again.". I am uploaded the file from my computer, then how it will make from project's root directory? please give me a solution.

Regards,

Sudhir Kumar

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by behrooziAWS** [comment]
RAR is not a supported zip format.  Please use zip.  Details on the manual deploy process [here](https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html)  If you continue to have issues, provide your app id and region.
