### ISSUE TITLE
Failed to identify framework when used with CDK

### ISSUE THREAD

**Issue by chmod** [aws-amplify/amplify-console#2168]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d856v6jzm73js

### Region

eu-central-1

### Amplify Console feature

Build settings, Not applicable

### Describe the bug

Deploying a next.js SSR app through CDK is failing to identify correctly that app is SSR. General -> App Details -> Framework is empty. If I deploy the app using the UI, Framework is identified correctly, and it builds as SSR.

### Expected behavior

I am expecting to see that Framework in General -> App Details is Next.js - SSR

### Reproduction steps

Use CDK to create a stack
export class AmplifyStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props: cdk.StackProps) {
        super(scope, id, props);

        const sourceCodeProvider = new amplify.GitHubSourceCodeProvider({
            owner: '.....',
            repository: '....',
            oauthToken: cdk.SecretValue.secretsManager('github-token'),

        });
        const buildSpec = codebuild.BuildSpec.fromObjectToYaml(
            {
                version: 1,
                applications: [
                    {
                        frontend: {
                            phases: {
                                preBuild: {
                                    commands: [
                                        "npm install"
                                    ]
                                },
                                build: {
                                    commands: [
                                        "npm run build"
                                    ]
                                }
                            },
                            artifacts: {
                                baseDirectory: ".next",
                                files: [
                                    "**/*"
                                ]
                            },
                            cache: {
                                paths: [
                                    "node_modules/**/*"
                                ]
                            }
                        }
                    }
                ]
            }
        );
        const amplifyApp = new amplify.App(this, "cdk-nf-web-app", {
            sourceCodeProvider: sourceCodeProvider,
            buildSpec: buildSpec
        });

        amplifyApp.addBranch('develop', {
            basicAuth: amplify.BasicAuth.fromGeneratedPassword('dev')
        });
        amplifyApp.addCustomRule({
            source: "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
            target: "/index.html",
            status: amplify.RedirectStatus.REWRITE
        });
    }
}

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm install
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - "**/*"
      cache:
        paths:
          - node_modules/**/*
    appRoot: nf-app
```

**Comment by behrooziAWS** [comment]
Just for confirmation, you are using the same repo/branch when you use the console as you do when you use the cdk and the package.json contains something like [this]? (https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app):

```
"scripts": {
  "dev": "next dev",
  "build": "next build",
  "start": "next start"
},```

**Comment by hughesjj** [comment]
Have you attempted to actually build the app yet?

When I make an SSR app via CDK, it doesn't display a detected framework until after my first attempted build.  It looks like that field is "lazily populated" upon first build, and some call in the web console but not in cdk/cfn sets it

**Comment by chmod** [comment]
> Just for confirmation, you are using the same repo/branch when you use the console as you do when you use the cdk and the package.json contains something like [this](https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app)?:
> 
> ```
> "scripts": {
>   "dev": "next dev",
>   "build": "next build",
>   "start": "next start"
> },
> ```

Yes.
@hughesjj I have build the app, but it fails to identify it as SSR and instead just zips it.

This is the same repo, same branch build output but using CDK
<img width="776" alt="Screenshot 2021-08-17 at 08 13 16" src="https://user-images.githubusercontent.com/614067/129673278-b7201ec1-05b7-4762-b575-66b3f094a7a7.png">
while this is using the UI
<img width="812" alt="Screenshot 2021-08-17 at 08 13 47" src="https://user-images.githubusercontent.com/614067/129673365-54c9f51b-8515-4b5c-9692-0ad90dae9e91.png">
Notice the lack of Starting SSR build.

Similarly, the deploy log for the latter cause mentions that it is deploying an SSR build and reserving cloudfront resources while the first doesnt.

**Comment by chmod** [comment]
https://github.com/chmod/nextjs-test/tree/main is a out of the box project. I tried deploying it using the CDK on the initial comment and the results are the same. Used both CDK v1.118 and v1.67. App made with CDK refuses to identify it as SSR

**Comment by behrooziAWS** [comment]
It looks like you haven't set a [role](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-amplify.App.html#rolespan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan) A role is required to provision ssr resource like the cloudfront distribution in your account.

**Comment by chmod** [comment]
Thanks, i added a role
```
    const role = new iam.Role(this, 'Role', {
            assumedBy: new iam.ServicePrincipal('amplify.amazonaws.com'),
            // custom description if desired
            description: 'Custom role permitting resources creation',
        });
        let iManagedPolicy = iam.ManagedPolicy.fromAwsManagedPolicyName(
            'AdministratorAccess',
        );
        role.addManagedPolicy(iManagedPolicy)

        this.amplifyStack = new amplify.App(this, id, {
            sourceCodeProvider: props.provider,
            buildSpec: buildSpec,
            role: role
        });
```
but still same output.

**Comment by behrooziAWS** [comment]
@chmod Per your last update it sounds like you got it working?  If so, please close this issue.
