### ISSUE TITLE
Next.js deploy failed: Error: CloudFront input failed validation. Could not find next.js pages for "_next/image*"

### ISSUE THREAD

**Issue by dn-l** [aws-amplify/amplify-console#2169]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

Deploy Next.js app through the CI

### Amplify CLI Version

5.3.0

### What operating system are you using?

Mac

### Amplify Categories

hosting

### Amplify Commands

Not applicable

### Describe the bug

```
2021-08-13T23:01:38.894Z [INFO]: Starting SSR Build...
2021-08-13T23:03:09.562Z [ERROR]: Error: CloudFront input failed validation. Could not find next.js pages for "_next/image*"
                                  at NextjsComponent.validatePathPatterns (/root/.//node_modules/@sls-next/-component/dist/component.js:97:19)
                                  at NextjsComponent.<anonymous> (/root/.//node_modules/@sls-next/-component/dist/component.js:346:18)
                                  at Generator.next (<anonymous>)
                                  at fulfilled (/root/.//node_modules/@sls-next/-component/dist/component.js:5:58)
                                  at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-08-13T23:03:09.563Z [ERROR]: [G[?25h[G[J
                                  70s › dv7gx4tsginir › Error: CloudFront input failed validation. Could not find next.js pages for "_next/image*"
                                  [G[?25h
Terminating logging...
```

### Expected behavior

Successful build

### Reproduction steps

1. git commit
2. git push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I'm not using `next/image`. Anything I should check?
Currently using `"next": "^11.1.0"` but same issue with `10.2`

**Comment by dn-l** [comment]
@edwardfoyle you're right the issue happens when I push to the repo and Amplify CI deploys the Next.js app. So yes, it happens on the Amplify Console side

**Comment by dn-l** [comment]
Also opened ticket 8725464361

**Comment by dn-l** [comment]
Disconnected my branch and connected it again. Deploy works again

**Comment by Leejjon** [comment]
This issue happens a lot to us. While disconnecting the branch and connecting it again works, it would be better if this wouldn't happen at all.

**Comment by dn-l** [comment]
@Leejjon my best suggestion to you: dump amplify and use vercel, your life will be so much easier
(what I did)

**Comment by Leejjon** [comment]
I would but the company I work for wants to use AWS and not too many external systems.
I just managed to solve it by the way. We had this only after a migration. Our package.json specified "next": "11.1.4",  but because we forgot to add the environment variable _LIVE_UPDATES=[{"name":"Next.js version","pkg":"next-version","type":"internal","version":"latest"}] Amplify figured we wanted to use Next.js version 9. That caused the issue.

**Comment by chemalopezp** [comment]
For anybody looking into this, the bug is still active and AWS has been notified of it.
Alto take into account that Amplify is only compatible with NextJS up to version 11 and webpack 4 so plan accordingly when choosing a platform.

I followed @dn-l advice and chose vercel too, unfortunately it was too late for me and I had already wasted a few hours trying to make Amplify work.

**Comment by mkkeffeler** [comment]
I am trying this fix now and what really sucks the most is I had to search discord to find a thread linking to this issue and google didn't have this properly indexed as the best way to solve my problem for "CloudFront input failed validation. Could not find next.js pages for "_next/image*", with any luck this post mentioning that this solves "CloudFront input failed validation. Could not find next.js pages for "_next/image*" will help with search results
