### ISSUE TITLE
build navigation UX bug

### ISSUE THREAD

**Issue by stefangomez** [aws-amplify/amplify-console#217]
**Describe the bug**
If you're on the latest build, and you are navigating to previous builds. it's way too easy to accidentally click "redeploy this version". It's really annoying -- I've done it too many times to count now.

**To Reproduce**
1. Go to latest build of any project that has current builds
2. Click on the < button to go to previous build
3. The cursor is now on the "Redeploy this version" button

**Expected behavior**
The mouse cursor should stay on the back arrow. maybe move "Redploy this version" somewhere else.

**Additional context**
See this screen recording: ![Screen gif](https://drops.nafets.io/7ivXGeT8.gif)

**Comment by garyleefight** [comment]
@stefangomez Thanks for the feedback

**Comment by swaminator** [comment]
This is fixed. @stefangomez
