### ISSUE TITLE
Event hooks

### ISSUE THREAD

**Issue by alastair-todd** [aws-amplify/amplify-console#220]
**Is your feature request related to a problem? Please describe.**
It would be useful to have events to hook into from Lambda

**Describe the solution you'd like**
Make available standard build started, failed, completed events to lambda

**Comment by swaminator** [comment]
@alastair-todd those are currently available. Adding an 'Email notification' actually creates an SNS topic which will allow you to watch for build start/fail/complete events.

**Comment by alastair-todd** [comment]
I want to trigger some further external testing.

**Comment by swaminator** [comment]
@alastair-todd can you be more specific? The SNS topic that we create can be used with a Lambda function to trigger on events: https://docs.aws.amazon.com/lambda/latest/dg/with-sns.html
