### ISSUE TITLE
Build stuck on patching packages

### ISSUE THREAD

**Issue by aaronmcadam** [aws-amplify/amplify-console#2200]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d499on4khjks2

### Region

eu-west-2

### Amplify Console feature

Build settings

### Describe the bug

My build is stalling on patching the `@aws-amplify/cli` package:

![CleanShot 2021-08-24 at 12 17 33](https://user-images.githubusercontent.com/37928/130607801-8c979267-1170-4a50-87a0-1400fa47ab9a.jpg)

### Expected behavior

I'd expect this step to work as normal.

### Reproduction steps

1. Create a new app
2. Set the build settings for Amplify CLI to the latest version:
![CleanShot 2021-08-24 at 12 20 16](https://user-images.githubusercontent.com/37928/130607911-fbe33c44-aecb-45dd-8681-8f4dd84ff8d4.jpg)

**Comment by sananbintahir** [comment]
Facing the same issue

**Comment by VincentvdE** [comment]
Having the same issue since a few hours.

**Comment by aaronmcadam** [comment]
A few people on my Twitter thread saying they're having problems with Yarn and NPM: https://twitter.com/aaronmcadam/status/1430128253579284504?s=20

**Comment by ParulSharma2622** [comment]
I am also facing same issue from past 2 hours.

**Comment by heavyskyl** [comment]
Looks like a network error, 1 time Patching step finished, but then I got a yarn install network timeout error.

**Comment by VincentvdE** [comment]
For me it's working again in "eu-central-1"

**Comment by aaronmcadam** [comment]
> For me it's working again in "eu-central-1"

Yes, it's working for me now too, thanks for the update!

I'm going to leave this issue open in case one of the team wants to add better error handling over patching packages.

**Comment by behrooziAWS** [comment]
This seems to be the reason: https://status.npmjs.org/incidents/bydjtj102gsn?u=tw8bmmsq4wgy
It appears that your job 13, which took 28 minutes to patch the cli and failed due to network errors cached that package so that subsequent builds didn't have to pull it down.
