### ISSUE TITLE
Domain Activation Failed

### ISSUE THREAD

**Issue by andrei-zgirvaci** [aws-amplify/amplify-console#2203]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2wvgb2x0c7scd

### Region

us-west-2

### Step

Domain activation

### Status

Failed

### Issue or question

I have successfully added my domain to a previous amplify app, but I deleted it as I had some issues and deiced to create a new app.

Since I tried to add the same domain to the new app, I cannot longer activate the same domain again. I made sure to check the dns records in GoDaddy but without success. I suspect something went wrong when deleting the old app and dns wasn't deleted correctly.

Will appreciate any help! Thank you!

### Error message

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below.

Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

### Additional information

<img width="1298" alt="Screenshot 2021-08-26 at 10 41 28 AM" src="https://user-images.githubusercontent.com/7466068/130892112-07507f15-32f8-46e0-b649-0cb1f7767beb.png">

**Comment by ivanlori** [comment]
I have the same problem, how did you solve that?
