### ISSUE TITLE
Amplify.yml file as per the environment

### ISSUE THREAD

**Issue by akanungo22** [aws-amplify/amplify-console#2208]
I have a monorepo and only one branch main. And from one main, I have to set up 3 amplify apps with different build setup.
So I tried creating amplify_dev.yml and amplify_prod.yml. But the amplify app did not recognize.

I have created the apps using cloudformation template.

Can we not rename the amplify.yml? Has it to be always amplify.yml?

In CodeBuild, we are able to rename the buildspec.yml

**Comment by behrooziAWS** [comment]
Although it must be named amplify.yml, you should be able to use a technique similar to [this](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#branch-specific-build-settings).

If you set [environment variables](https://docs.aws.amazon.com/amplifyenvironm/latest/userguide/build-settings.html#branch-specific-build-settings) for each app differently you can have one buildspec that runs different commands based on what a variable is set to.
