### ISSUE TITLE
My page can't be found - Even the default setup doesn't work

### ISSUE THREAD

**Issue by selhari** [aws-amplify/amplify-console#2209]
I am deploying a React.js web app on Amplify, have done before both React.js and HTML/CSS applications, and didn't cross any issues. 
 But, this time even when deploying the core create-react-app template setup, it's show a error 404 page and doesn't show the application.
 Have read some articles, setup the original project and some test one's, but couldn't figure out why is this happening.
 
 Can anybody help me?
 
 I didn't even configurate the DNS.
 
 My app URL is https://master.d2ui557i8b4kuv.amplifyapp.com/

My region is sa-east-1 (Latin America São Paulo - East 1)

![image](https://user-images.githubusercontent.com/48302894/131150899-3f21d6b5-f4dd-4e8e-af62-141785ce9037.png)

**Comment by siegerts** [comment]
Hi :wave: - thanks for raising this!  To get a bit more context, do you mind using the formatted template here:

- [bug report](https://github.com/aws-amplify/amplify-console/issues/new?assignees=&labels=&template=1.bug_report.yaml)

This will help the team determine the best approach to take.

**Comment by victorccccc** [comment]
Hi, looking at your build history, can you try to add build command so that amplify know how to build your application? 
Please refer to this docs https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html

Feel free to re-open if your have questions, thanks
