### ISSUE TITLE
I created and deleted an AWS amplify app. I created a new one and I can't point it to the same domain I used before.

### ISSUE THREAD

**Issue by camello222** [aws-amplify/amplify-console#2211]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1ks4ccnb8x28j

### Region

us-west-2

### Step

Domain Activation

### Status

Failed

### Issue or question

I created an Amplify app and pointed it to a domain. I then removed it and created a new one, pointing to the same domain. Now I get the error message attached below, following the same steps as I had previously done to setup the domain successfully.

It seems to me there had been registries at CloudFront from my previous apps and attempts, that remained there and that I can't remove. I have no distribution showing in CloudFront, so I am not sure how that's managed by AWS when leveraging Amplify, but I don't seem to have control over that, unfortunately.

Please help with the error below, most likely by accessing and removing the CF distributions of my previous Amplify apps. You can nuke my whole Amplify setup and history, as long as I can set things up fresh in my next attempt and use my same domain.

Thanks.

### Error message

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below.
Error message: [CNAMEAlreadyExistsException] The following CloudFront distributions are already using one or more of your domains: [Distribution: *******0NH09S6 in AWS Account: ******200621, Distribution: *******0NH09S6 in AWS Account: ******200621]. If you own these distributions, please remove the domains from them first and then retry adding your domain. If you don't own them, then you may already have associated this domain to another Amplify App in another account or region. You can also check our troubleshooting guide for more help: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

**Comment by camello222** [comment]
Hello, can I expect any support from this issue?

**Comment by ferdingler** [comment]
Hi @camello222, may I ask what is the domain name that you are trying to associate? By any chance, do you have the appId for the app that you deleted?

**Comment by ferdingler** [comment]
I found the domain name you are trying to add and looks like it is associated to an app in the us-east-2 (Ohio) region under the same AWS account. You'll need to delete it from there first so that you can re-associate it to a new Amplify app.

**Comment by camello222** [comment]
@ferdingler  Thank you. I thought that app was deleted. Hadn't noticed it was in another region.
