### ISSUE TITLE
Domain Management not working because of previous EC2

### ISSUE THREAD

**Issue by toddcoulson** [aws-amplify/amplify-console#222]
I am working through domain management in Amplify. I had a domain, buckscountytourofhonor.org. I had it tied up with a Bitnami instance on EC2. That was giving me problems, so I rebuilt the app in React, put it in github and used amplify. The app works before I add domain management. But I terminated the EC2 instance that was tied to my Route53 domain. Then I added the same domain from Route53 into Domain Management on Amplify, and when I check in my browser, nothing shows up, it just tries to connect to nothing. 

My id for the project is d2hqhp7xpxgqpz
Please let me know if I can do anything different to get this to work.

**Comment by swaminator** [comment]
@toddcoulson sometimes it takes time for the domain to become available again. Is your app working now?

**Comment by toddcoulson** [comment]
No it is not working. I have been trying to enter different things into the
hosted zone but I do not really know what I am doing. I did try to add the
nameservers into godaddy to get the transfer of the 3rd party domain to
work right. I waited 48 hours after doing so, but it is still not reading
the other domain. Please help. buckscountytourofhonor.org is the domain I
am trying to get to work.
Todd Coulson

**Comment by Joycehao19** [comment]
Hi @toddcoulson  I checked your domain www.buckscountytourofhonor.org on https://www.whatsmydns.net/, it seems like your domain is working now. Please let us know if you have any questions about this issue. Thank you!

**Comment by toddcoulson** [comment]
Sorry I should have posted again. I was able to get amplify working, but had to remove everything and rebuild. Thanks for the help.

**Comment by Joycehao19** [comment]
Cool!
