### ISSUE TITLE
BUG: The API for my app won't load

### ISSUE THREAD

**Issue by SusanaVelez** [aws-amplify/amplify-console#2225]
Hi,
I've entered my app and I clicked "API", but nothing appears. My internet connection is working, but I have no idea why this screen won't load. Could it be a permissions issue?

`App ID` d2sguvrv2tq3uo
`Region` us-east-1

Tks

<img width="2034" alt="Screen Shot 2021-08-31 at 18 00 45" src="https://user-images.githubusercontent.com/88371851/131879917-d60c00d9-4de2-40c0-b7a9-df2c9f482ef8.png">

**Comment by siegerts** [comment]
Hi @SusanaVelez, is this still happening?

**Comment by SusanaSVelez** [comment]
Not anymore.

Thank you.
