### ISSUE TITLE
Amplify build fails due to a layer that was removed already

### ISSUE THREAD

**Issue by dcfranca** [aws-amplify/amplify-console#2226]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dr30qdghmfhdu

### Region

us-east-1

### Amplify Console feature

Backend builds

### Describe the bug

I was having issues with pushing the stack after the removal of a lambda layer, the issue is described here: https://github.com/aws-amplify/amplify-cli/issues/7824

After walk through the issue with the help of the Amplify team, I managed to push the stack and update it successfully from the CLI
The staging and dev environments can be updated via the CLI, but fails to update via the Amplify build pipeline

The build log:

> 2021-09-02T16:55:23.425Z [WARNING]: - Initializing your environment: staging
> 2021-09-02T16:55:30.112Z [WARNING]: ✔ Initialized provider successfully.
> 2021-09-02T16:55:35.281Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
> 2021-09-02T16:55:35.289Z [WARNING]: ✖ There was an error initializing your environment.
> 2021-09-02T16:55:35.332Z [INFO]: [0mError: Lambda layer ThumbnailsGenerator is missing a state file. Try running "amplify pull --restore". If the issue persists, recreating the layer is the best option. Ensure your layer content is backed up![0m
>                                  [0m    at getLegacyLayerState (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/layerMigrationUtils.ts:159:9)[0m
>                                  [0m    at migrateLegacyLayer (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/layerMigrationUtils.ts:50:23)[0m
>                                  [0m    at AmplifyToolkit.invokePluginMethod [as _invokePluginMethod] (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/invoke-plugin-method.ts:29:10)[0m
>                                  [0m    at runMicrotasks (<anonymous>)[0m
>                                  [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
>                                  [0m    at Object.legacyLayerMigration (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/lambdaLayerInvocations.ts:21:3)[0m
>                                  [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:148:7)[0m
> 2021-09-02T16:55:35.362Z [ERROR]: !!! Build failed
> 2021-09-02T16:55:35.362Z [ERROR]: !!! Non-Zero Exit Code detected
> 2021-09-02T16:55:35.363Z [INFO]: # Starting environment caching...
> 2021-09-02T16:55:35.363Z [INFO]: # Uploading environment cache artifact...
> 2021-09-02T16:55:35.445Z [INFO]: # Environment caching completed
> 

I have tried doing `amplify pull --restore`, nothing happens
I also have tried removing the layer with `amplify function remove` and then I get the error:

> Cannot read property 'filter' of undefined
> TypeError: Cannot read property 'filter' of undefined
>     at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts:248:33
>     at Array.filter (<anonymous>)
>     at Object.getLambdaFunctionsDependentOnLayerFromMeta (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts:245:45)
>     at Object.removeWalkthrough (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/removeLayerWalkthrough.ts:25:43)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/commands/function/remove.ts:30:29)
>     at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/index.ts:251:3)
>     at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:177:3)
>     at Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/

> execution-manager.ts:29:5)
>    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:200:5)

### Expected behavior

The backend build step should work, and finish the deployment

### Reproduction steps

Update the master branch
Push the changes
The build is triggered
The build fails on the backend build stage

### Build Settings

```yaml
version: 0.1
backend:
  phases:
    build:
      commands:
        - amazon-linux-extras install python3.8
        - ln -fs /usr/bin/python3.8 /usr/bin/python3
        - pip3.8 install pipenv
        - amplifyPush --simple
```

**Comment by dcfranca** [comment]
Is there a way to locally publish my changes without having to go through the console pipeline? So I can still have my changes deployed even with the console pipeline broken?
I have tried using `amplify publish --invalidateCloudFront`
but it doesn't seem to work, is there something I am missing?

**Comment by dcfranca** [comment]
Anyone?

**Comment by behrooziAWS** [comment]
It looks like recent builds have been succeeding and there were some updates in the other thread.  If you need to temporarily skip the backend build in the future, one option is to set the environment variable `PROCESS_SKIP_BACKEND` to `true` for that branch.  Reopen if there are still outstanding issues.
