### ISSUE TITLE
Next.js deployment gives the error `ERROR: AccessDenied: Access Denied`

### ISSUE THREAD

**Issue by fossamagna** [aws-amplify/amplify-console#2230]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2s6j07ddh3c5s

### Region

ap-northeast-1

### Amplify Console feature

Not applicable

### Describe the bug

I deployed the application created by executing only `yarn create next-app --typescript`.
Before deploy, I created a service role as `amplifyconsole-backend-role` according to [the documentation](https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html) and attached it.

```
2021-09-03T07:59:03.855Z [INFO]: info  - Finalizing page optimization...
2021-09-03T07:59:03.857Z [INFO]: 
2021-09-03T07:59:03.863Z [INFO]: Page                                Size     First Load JS
                                 ┌ ○ /                               4.61 kB        71.6 kB
                                 ├   └ css/eb291d7de33c874d5a88.css  732 B
                                 ├   /_app                           0 B              67 kB
                                 ├ ○ /404                            194 B          67.1 kB
                                 └ λ /api/hello                      0 B              67 kB
                                 + First Load JS shared by all       67 kB
                                 ├ chunks/framework.b97a0e.js      42 kB
                                 ├ chunks/main.c4f254.js           23.6 kB
                                 ├ chunks/pages/_app.d4f4e0.js     556 B
                                 ├ chunks/webpack.fb7614.js        770 B
                                 └ css/120f2e2270820d49a21f.css    209 B
2021-09-03T07:59:03.863Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
                                 (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

2021-09-03T07:59:04.024Z [INFO]: Done in 12.89s.
2021-09-03T07:59:04.029Z [INFO]: Starting SSR Build...
2021-09-03T08:00:40.036Z [ERROR]: AccessDenied: Access Denied
                                  at Request.extractError (/root/.//node_modules/aws-sdk/lib/services/s3.js:714:35)
                                  at Request.callListeners (/root/.//node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                  at Request.emit (/root/.//node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                  at Request.emit (/root/.//node_modules/aws-sdk/lib/request.js:688:14)
                                  at Request.transition (/root/.//node_modules/aws-sdk/lib/request.js:22:10)
                                  at AcceptorStateMachine.runTo (/root/.//node_modules/aws-sdk/lib/state_machine.js:14:12)
                                  at /root/.//node_modules/aws-sdk/lib/state_machine.js:26:10
                                  at Request.<anonymous> (/root/.//node_modules/aws-sdk/lib/request.js:38:9)
                                  at Request.<anonymous> (/root/.//node_modules/aws-sdk/lib/request.js:690:12)
                                  at Request.callListeners (/root/.//node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
                                  code: 'AccessDenied',
                                  region: null,
                                  time: 2021-09-03T08:00:39.568Z,
                                  requestId: 'XE37CYKQCYBXR8S5',
                                  extendedRequestId: '6IGl67kwC2nqKebJRNZGG498W0fibZK9McIBneUqN0WPFSDK+fUG/m+4YWBR/jz1DmPJ4//saSA=',
                                  cfId: undefined,
                                  statusCode: 403,
                                  retryable: false,
                                  retryDelay: 168.77706262530862
                                  }
Terminating logging...
```

### Expected behavior

- The missing policy is documented
- successful deployment

### Reproduction steps

1. Create Next.js app (`yarn create next-app --typescript`)
2. Run `amplify init`
3. git commit & git push to GitHub remote repository
4. connect to GitHub repository amplify app on Amplify Console (Created a service role as `amplifyconsole-backend-role` according to [the documentation](https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html) and attach it to amplify app.)
5. Run deploy

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

After the above error, I added the `AdministratorAccess` policy to `amplifyconsole-backend-role and restart job, and the deployment was successful.

**Comment by ferdingler** [comment]
Hi @fossamagna, 

Apologies for the confusion on the necessary IAM permissions. The reason why we are not prescriptive about it is because customers may have all kinds of resources in their Amplify Apps, like AppSync APIs, DynamoDB tables, Lambda functions, etc. And so the IAM policy highly depends on your environment needs. 

However, in this case, it looks like you are trying to deploy a basic NextJs SSR app. For those kind of apps, we create a few resources in your account like S3 Bucket, CloudFront Distribution, Lambda@Edge functions, SQS queue (if you are using ISR), etc. So your IAM role needs to have enough permissions to do so. Here is a list of permissions that should help you without assigning full Admin access. 

<details>
<summary>IAM permission for SSR apps</summary>

```
acm:DescribeCertificate
acm:ListCertificates
acm:RequestCertificate
cloudfront:CreateCloudFrontOriginAccessIdentity
cloudfront:CreateDistribution
cloudfront:CreateInvalidation
cloudfront:GetDistribution
cloudfront:GetDistributionConfig
cloudfront:ListCloudFrontOriginAccessIdentities
cloudfront:ListDistributions
cloudfront:ListDistributionsByLambdaFunction
cloudfront:ListDistributionsByWebACLId
cloudfront:ListFieldLevelEncryptionConfigs
cloudfront:ListFieldLevelEncryptionProfiles
cloudfront:ListInvalidations
cloudfront:ListPublicKeys
cloudfront:ListStreamingDistributions
cloudfront:UpdateDistribution
cloudfront:TagResource
cloudfront:UntagResource
cloudfront:ListTagsForResource
iam:AttachRolePolicy
iam:CreateRole
iam:CreateServiceLinkedRole
iam:GetRole
iam:PutRolePolicy
iam:PassRole
lambda:CreateFunction
lambda:EnableReplication
lambda:DeleteFunction
lambda:GetFunction
lambda:GetFunctionConfiguration
lambda:PublishVersion
lambda:UpdateFunctionCode
lambda:UpdateFunctionConfiguration
lambda:ListTags
lambda:TagResource
lambda:UntagResource
route53:ChangeResourceRecordSets
route53:ListHostedZonesByName
route53:ListResourceRecordSets
s3:CreateBucket
s3:GetAccelerateConfiguration
s3:GetObject
s3:ListBucket
s3:PutAccelerateConfiguration
s3:PutBucketPolicy
s3:PutObject
s3:PutBucketTagging
s3:GetBucketTagging
lambda:ListEventSourceMappings
lambda:CreateEventSourceMapping
iam:UpdateAssumeRolePolicy
iam:DeleteRolePolicy
sqs:CreateQueue
sqs:DeleteQueue
sqs:GetQueueAttributes
sqs:SetQueueAttributes
amplify:GetApp
amplify:GetBranch
amplify:UpdateApp
amplify:UpdateBranch
```
</details>

**Comment by ferdingler** [comment]
I have added this to our FAQ in the meantime for anyone who comes across this in the future. 

https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md#error-accessdenied-access-denied

**Comment by fossamagna** [comment]
Thank you. By attaching the permissions you showed me, I was able to deploy without error.

**Comment by opqpop** [comment]
Thank you, how do we use a custom role for Amplify frontend? In the AWS Amplify console, I'm only able to get the default created one that uses managed AWS policies to show up (role created following https://docs.aws.amazon.com/es_es/amplify/latest/userguide/how-to-service-role-amplify-console.html)

![image](https://user-images.githubusercontent.com/5566843/132265558-13d6b8b2-c645-4869-ada1-a2d991d174b4.png)

I can't edit the permissions on this role as a result, nor can I create a non-managed role and assign it to my Amplify app through the AWS Amplify console. Is there another way I should be doing this?

**Comment by fossamagna** [comment]
@opqpop I have added the permissions indicated in Issue to an existing role as an inline policy. That works fine.

**Comment by opqpop** [comment]
Ah thanks that worked! I had the concepts mixed up.

The role has a managed AWS policy which can't have permissions edited, so the fix is to just attach a second policy to the role that has above permissions. In my case, I just attached the AdministratorAccess policy alongside "AdministratorAccess-Amplify", which fixed the issue now that my permissions are less restrictive
