### ISSUE TITLE
Amplify React Native app fails to build

### ISSUE THREAD

**Issue by wjatx** [aws-amplify/amplify-console#2241]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2d1hhyx04gxbg

### Region

us-east-2

### Amplify Console feature

Build settings

### Describe the bug

I am following the steps in the React Native tutorial here:
https://docs.amplify.aws/start/getting-started/hosting/q/integration/js/

The app runs locally but will not build in the Amplify console.

### Expected behavior

Amplify console should pick up changes to Github repo and automatically build successfully. It is picking up the changes and kicks off the build, but build always fails.

### Reproduction steps

1. Make a change to a file (any change)
2. Commit and push
3. Amplify starts the build but fails.

**Comment by siegerts** [comment]
Hi @wjatx, Amplify Hosting doesn't support hosting React Native applications. The backend infrastructure for these apps can be provisioned/hosted (i.e. GraphQL APIs, Lambda Functions, Auth, etc.) but the "mobile" app itself is not.

More information can be found here about Single Page App deployments - https://docs.aws.amazon.com/amplify/latest/userguide/getting-started.html. 

Hope that this helps.
