### ISSUE TITLE
An error occurred during the publish operation: User: arn:aws:sts::407223949779:assumed-role/us-east-2_iispTEBq7_Full-access/amplifyadmin is not authorized to perform: amplify:ListJobs on resource: arn:aws:amplify:us-east-2:407223949779:apps/d1vqj8u2diu92j/branches/prod/jobs/*

### ISSUE THREAD

**Issue by Mystsra** [aws-amplify/amplify-console#2245]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

An error occurred during the publish operation: User: arn:aws:sts::407223949779:assumed-role/us-east-2_iispTEBq7_Full-access/amplifyadmin is not authorized to perform: amplify:ListJobs on resource: arn:aws:amplify:us-east-2:407223949779:apps/d1vqj8u2diu92j/branches/prod/jobs/*

### Describe the bug

An error occurred during the publish operation: User: arn:aws:sts::407223949779:assumed-role/us-east-2_iispTEBq7_Full-access/amplifyadmin is not authorized to perform: amplify:ListJobs on resource: arn:aws:amplify:us-east-2:407223949779:apps/d1vqj8u2diu92j/branches/prod/jobs/*

### Expected behavior

An error occurred during the publish operation: User: arn:aws:sts::407223949779:assumed-role/us-east-2_iispTEBq7_Full-access/amplifyadmin is not authorized to perform: amplify:ListJobs on resource: arn:aws:amplify:us-east-2:407223949779:apps/d1vqj8u2diu92j/branches/prod/jobs/*

### Reproduction steps

An error occurred during the publish operation: User: arn:aws:sts::407223949779:assumed-role/us-east-2_iispTEBq7_Full-access/amplifyadmin is not authorized to perform: amplify:ListJobs on resource: arn:aws:amplify:us-east-2:407223949779:apps/d1vqj8u2diu92j/branches/prod/jobs/*

### Build Settings

```yaml
An error occurred during the publish operation: User: arn:aws:sts::407223949779:assumed-role/us-east-2_iispTEBq7_Full-access/amplifyadmin is not authorized to perform: amplify:ListJobs on resource: arn:aws:amplify:us-east-2:407223949779:apps/d1vqj8u2diu92j/branches/prod/jobs/*
```

### Additional information

An error occurred during the publish operation: User: arn:aws:sts::407223949779:assumed-role/us-east-2_iispTEBq7_Full-access/amplifyadmin is not authorized to perform: amplify:ListJobs on resource: arn:aws:amplify:us-east-2:407223949779:apps/d1vqj8u2diu92j/branches/prod/jobs/*

**Comment by siegerts** [comment]
Hi @Mystsra, is this related to using the Amplify CLI?

**Comment by siegerts** [comment]
Closing for now. Please reopen if the issue occurs again.
