### ISSUE TITLE
CustomerError: Unable to clone repository due to user error code: 128

### ISSUE THREAD

**Issue by jigote** [aws-amplify/amplify-console#2249]
Hi, I'm using **Amazon Amplify** trying to host a simple web app from a **AWS CodeCommit** repository, I'm following [this tutorial](https://aws.amazon.com/es/getting-started/hands-on/build-serverless-web-app-lambda-apigateway-s3-dynamodb-cognito/module-1/) step by step but when I deploy it, it pass the provission stage but fails at the **build** stage, where say it was unable to access the repository.

```
2021-09-12T16:36:51.072Z [INFO]: # Cloning repository: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/wilderydes-site
2021-09-12T16:36:51.567Z [INFO]: Cloning into 'wilderydes-site'...
2021-09-12T16:36:57.960Z [INFO]: fatal: unable to access 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/wilderydes-site/': The requested URL returned error: 403
2021-09-12T16:36:57.963Z [ERROR]: !!! CustomerError: Unable to clone repository due to user error code: 128
```

I also saw other comments on the [same issue](https://github.com/aws-amplify/amplify-console/issues/572), where suggest to add a Service role to have permission to accept codecommit. But here it shows I already added that Service role.
![IAMRole](https://user-images.githubusercontent.com/33304552/133000351-dd36d7ea-9090-4433-8ef8-d05ec6d67d77.JPG)

My region is: us-east-1
My App ARN is: arn:aws:amplify:us-east-1:116464983000:apps/d3hydnsxqfbect

Please, I would appreciate any guidance to complete that step in the tutorial. Thanks

**Comment by ganipcanot** [comment]
Did you check the permissions of that role and it does have access to code commit?

Have you tried it again with another role with full Admin permissions?

**Comment by hloriana** [comment]
Closing due to no response. If you are still having this issue, feel free to re-open. Thanks!
