### ISSUE TITLE
Webhook is not added after reconnecting repository

### ISSUE THREAD

**Issue by baruchvlz** [aws-amplify/amplify-console#2256]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1due1b25qzpv3

### Region

eu-west-1

### Amplify Console feature

Webhooks

### Describe the bug

I had to reconnect the repository and it said to delete the webhook that was added by Amplify Console, so I did assuming that it would be added again while reconnecting but it seems my assumption was wrong.

### Expected behavior

Amplify Console adds webhook on reconnecting repository

### Reproduction steps

1. Delete webhook
2. reconnect repository

**Comment by baruchvlz** [comment]
Fixed it by linking a different repo then reconnecting to the actual repository I need. I'm going to keep the issue open though because I don't think this is the intended UX.

**Comment by kegorgas** [comment]
I am also getting this same exact behavior. This started occurring after we transferred ownership of the repo from a user's account to an org account. As @baruchvlz said, we removed the existing webhook before we reconnected the app to the repo but after reconnecting (and getting the success message in Amplify), the webhook and deploy key are not populating on the Github repo side. I did see some advice through various searches that the Amplify third party app needs to be connected in the organization settings. I checked this and verified that it was present and approved. Additionally, I verified that the user account attempting to perform this step was set up as an admin in the repo after transferring this over. 

After this behavior, we did set up a new Amplify instance and hooked it up to the repo and the new instance did successfully set up the new resources. However, it would be preferable if this behavior worked via the reconnection setting in the old one as we have a custom domain set up in that one (or at least determine if the resources were not set up correctly and notify us).,

**Comment by victorccccc** [comment]
Sorry for the inconvenience, we've noticed this issue and fix is rolling out. I'll update here when deployment is completed

**Comment by hloriana** [comment]
A fix for this was rolled out. If you have any other questions please feel free to open a new issue. Thanks!

**Comment by ivadenis** [comment]
still have this issue
