### ISSUE TITLE
Push CSS-only changes to my auto-build branch fails to trigger build

### ISSUE THREAD

**Issue by dwvisser** [aws-amplify/amplify-console#226]
**Describe the bug**
Twice now in my Amplify project, I've had a push to my auto-build branch ("master" on AWS CodeCommit) fail to trigger a new build. Both times the commits consisted only of changes to my main CSS file.

**To Reproduce**
1. Take an existing Amplify project, which usually builds upon commit to a auto-build branch.
2. Make changes only in a CSS file that is part of the build (in my case, my WebPack entry point imports the CSS via css-loader).
3. Push change to the auto-build branch.
4. No build is triggered.

**Expected behavior**
Since locally, the WebPack dev server correctly recognizes rebuild is necessary upon CSS change, I would expect Amplify auto-build triggers to be now different.

**Additional context**
Simple single page site, built using WebPack, and css-loader is leveraged for "packing" the CSS into the bundle.js.

**Sample code**
https://us-east-1.console.aws.amazon.com/codesuite/codecommit/repositories/knoxccl.org/browse/refs/heads/master?region=us-east-1#

Commits 94ffe84 and 9814ba7 both failed to trigger auto-build when pushed.

**Comment by Joycehao19** [comment]
Thanks for reporting this issue. We are currently investigating.

**Comment by Joycehao19** [comment]
@dwvisser : Can you please send me your appID (App settings > general) and region?

**Comment by dwvisser** [comment]
Is this it?
`arn:aws:amplify:us-east-1:756692076925:apps/d13zqa7kc42leq`

**Comment by swaminator** [comment]
@dwvisser do you have an example repo that we can try? we haven't been able to reproduce this at our end.

**Comment by dwvisser** [comment]
I've cloned my repo to a public GitHub repo: https://github.com/dwvisser/knoxccl/commits/master

https://github.com/dwvisser/knoxccl/commit/9814ba70a96038a8ea91439616c318247dc45ee2 is an example of a commit I pushed that didn't trigger a build.

**Comment by Joycehao19** [comment]
@dwvisser I tried and reproducing this [here](https://github.com/Joycehao19/knoxccl/commit/d75af9adf07d8d6f7dd05a18eb5d57c626f3a038) and I wasn't able to reproduce the issue. Are you still facing this issue with your app?

**Comment by Joycehao19** [comment]
@dwvisser just a reminder on above. We weren't able to repro the issue with the repository you shared.

**Comment by dwvisser** [comment]
Perhaps it's just something weird about my repo. In any case, I have since deleted the Amplify app, and moved to other infrastructure (not because of this... I just found a cheaper way to deploy from Git).

**Comment by swaminator** [comment]
@dwvisser sorry to see you leave. Where did you move to and are there any features that can bring you back?!

**Comment by dwvisser** [comment]
I realized GitHub Actions could do what I was getting out of Amplify, with the exception of having test/develop app targets. In my case , that wasn’t hat important. If I ever want to stand up a preview site, I’ll probably just dump a local build into S3.
