### ISSUE TITLE
aws console DOES NOT let you edit build command inline

### ISSUE THREAD

**Issue by opqpop** [aws-amplify/amplify-console#2264]
5### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

This screen does nothing, you can't edit the input. Please fix

![image](https://user-images.githubusercontent.com/5566843/134095617-9b677c60-f3c9-4769-89dc-dac21956b9eb.png)

### Expected behavior

somebody broke this and regressed it

### Reproduction steps

try to connect new frontend env to github

**Comment by kahdojay** [comment]
Hi @opqpop I'm not able to reproduce this in my own app. Are you seeing it in other apps of yours / repro it consistently? Can you provide an appId so I can dig further into this?

**Comment by opqpop** [comment]
Hmm very strange, now I can't repro it. I'm able to successfully edit inline. I don't think I changed anything.
