### ISSUE TITLE
An error occurred during the publish operation: Deployment file has not been uploaded

### ISSUE THREAD

**Issue by Nxtra** [aws-amplify/amplify-console#2266]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

14.17.0

### Amplify CLI Version

5.6.0

### What operating system are you using?

Mac

### Amplify Categories

hosting

### Amplify Commands

publish

### Describe the bug

We publish our app via de CI tools of gitlab.
When executing `amplify publish --y` on the publish we get the amplify error: `An error occurred during the publish operation: Deployment file has not been uploaded, please make sure you uploaded the deployment file prior to invoke this api.`

We have never encountered this before. 
Do you know where this error comes from?

### Expected behavior

`amplify publish --y` deploys the new version of our app.

### Reproduction steps

amplify publish --y

### Log output

An error occurred during the publish operation: Deployment file has not been uploaded, please make sure you uploaded the deployment file prior to invoke this api.

**Comment by Nxtra** [comment]
@rcambrj , for me the jobs are already in failed state. I cannot cancel them anymore.
+ yes, indeed the problem is only happening for when I deploy using my CI pipeline. (headless deploy)
I can still deploy from my local machine. Ofc, that's not what I wanna do for prod deploys :) 

Any ideas on how to fix this "An error occurred during the publish operation: Deployment file has not been uploaded " error?

**Comment by TheRyanBurke** [comment]
I unblocked myself by installing the latest version of Amplify CLI `npm i -g @aws-amplify/cli` (6.0.1). Despite the docs for the geo module specifying CLI version 5.6.0-geo.0 is required, I am able to publish my app once again. Perhaps I only need the geo version to make changes to Amazon Location resources and can otherwise use the main CLI branch?

**Comment by Nxtra** [comment]
We were able to move forward at a certain point but don't know what changed. We had not updated our amplify cli version (still on 5.6.0) and suddenly it worked again. 

No Amazon Location in our project, so for us the issue was independent of amplify location.

**Comment by kahdojay** [comment]
@Nxtra glad to hear you were able to unblock yourself. If you run into more issues with Amplify Console/Hosting feel free to open an issue in our repo: https://github.com/aws-amplify/amplify-console/issues/
