### ISSUE TITLE
Root domain does not connect

### ISSUE THREAD

**Issue by justinpezzack** [aws-amplify/amplify-console#2270]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-1:147761352395:apps/d4nahud7y9q9t

### Region

us-east-1

### Step

Finished

### Status

Success

### Issue or question

Cannot access my root domain.

I am using an externally owned domain, with Route 53 as my DNS. I have setup records as follows

![image](https://user-images.githubusercontent.com/11285997/134435890-8d1f1c1c-5fd2-4533-9c5f-f37c2c4a4f3f.png)

1. A record from mydomain.com to my cloudfront dns 
2. NS
3. SOA 
3. Auth for SSL
4. CNAME from mysubdomain.mydomain.com -> cloudfront dns.

What is weird is I am able to get through to my subdomain.mydomain.com, but mydomain.com I get the following error.

Thoughts?

![image](https://user-images.githubusercontent.com/11285997/134435982-ae65b3ff-ec2c-4ba5-867f-3efd8276342b.png)

**Comment by ferdingler** [comment]
hi @justinpezzack , are your Route53 records in a different account than your Amplify app? Because if they are on the same account, we take care of adding the proper DNS records automatically for you.

**Comment by justinpezzack** [comment]
They are on the same account! For future reference did I set something up incorrectly? If you need more information / specific sensitive info I can reach out via email .

**Comment by kahdojay** [comment]
@justinpezzack it looks like you've setup a redirect from your apex domain to www subdomain, but you didn't setup www, so when you visit your root domain it attempts to redirect there but it doesn't exist.

Go to App Settings > Rewrites & Redirects and delete the rule that redirects from root to www, then it should work again.

Hope this helps, closing this one for now, please re-open it if this doesn't resolve the issue.

**Comment by justinpezzack** [comment]
Fixed it! thank you @kahdojay
