### ISSUE TITLE
Environment stuck on "Retrieving deployment details..."

### ISSUE THREAD

**Issue by nrmilstein** [aws-amplify/amplify-console#2275]
**Please describe which feature you have a question about?**

My frontend environment is stuck on "Retrieving deployment details." I have already cancelled all active deployments.

I originally tried deploying via the CLI and received:

An error occurred during the publish operation: Deployment file has not been uploaded, please make sure you uploaded the deployment file prior to invoke this api

I went to the console, cancelled any active deployments, and tried uploading via zip file. This causes another deployment stuck on pending. When I cancel that deployment, the console is now stuck on "Retrieving deployment details."

**Provide additional details**

My app ID is d51x1p5vho0k and my region is us-east-2.

**What AWS Services are you utilizing?**

AWS Amplify

**Provide additional details e.g. code snippets**

**Comment by kahdojay** [comment]
@nrmilstein will take a look. Looks like you previously used ci/cd deploys but now you're attempting to use manual. Did you disconnect the branch first?

**Comment by kahdojay** [comment]
It looks like your zip file isn't being successfully uploaded. Is your zip uploaded successfully? Can you share screenshots and a zip file to repro? (You can email it or a presigned url to aws-amplify-customer@amazon.com)

**Comment by nrmilstein** [comment]
I just tried to manually upload via zip file, and it said deployment success, but the entire site was down and I got an AccessDenied page.

I then tried to remove hosting from the prod environment, which worked, but it would not let me re-add it from the CLI, saying "You have already connected branches to your Amplify Console app. Please visit the Amplify Console to manage your branches." I tried adding the prod front-end environment via the console, which was successful, but now I get access denied to every request (when I use the direct Amplify URL. Our custom URL isn't even functioning at all).

We have never used ci/cd or connected a branch as far as I know, we have always deployed via `amplify publish`. Please help us resolve this as our website is now down.

**Comment by nrmilstein** [comment]
I've sent an email with our zipped bundle to aws-amplify-customer@amazon.com.

**Comment by nrmilstein** [comment]
The Access Denied is an Amazon S3 error.

**Comment by nrmilstein** [comment]
I have tried deploying via zip upload to our dev environment, and that is now down with S3 AccessDenied as well.

**Comment by kahdojay** [comment]
@nrmilstein can you ensure you're zipping the contents of the folder and not the folder itself? See the bottom of https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html

**Comment by nrmilstein** [comment]
Thanks for your swift reply, that was the problem with the zip upload, we're back online.

I believe I may still be having the original CLI issues with publishing (and pulling now it would appear), but as it is nearing midnight here, I will address any problems next week by either commenting here or opening a new issue :)

Thanks.

**Comment by kahdojay** [comment]
sounds good, I'll close this one for now, thanks!

**Comment by nrmilstein** [comment]
Hi, I'm still having problems with my amplify configuration.

I have two environments: dev and prod. According to the console, both have frontend hosting.

When I switch to the prod environment and run `amplify status`, it wants to create hosting. If I `amplify push`, it fails, saying "Invalid request provided: Failed to create branch. The branch prod already exists for the app d51x1p5vho0k".

If I `amplify pull`, it removes hosting and states I do not have it. If I then `amplify env checkout dev` and `amplify status`, it says I've deleted hosting and wants to push that. If I then `amplify pull`, it reverts to saying I have hosting.

How can this be resolved? I have backend auth on the prod branch that I cannot lose; otherwise I would just recreate the environment. I cannot find a way on the console to delete just the `prod` hosting.
