### ISSUE TITLE
Automatically delete cloudfront, s3 bucket and edge (SSR/API/Image optimization) lambda's after deleting branch

### ISSUE THREAD

**Issue by Leejjon** [aws-amplify/amplify-console#2279]
**Is your feature request related to a problem? Please describe.**
We have a Next.js SSR project in Amplify set up with automatic environment creation whenever a branch is created on our Git Repository. This works perfectly fine, an environment appears in the Amplify Console which starts building.

In my case it creates the following resources:
```
2021-09-21T15:15:55 [INFO]: Deploying SSR Resources. Distribution ID: E26MY4WISD74E2. This may take a few minutes...
2021-09-21T15:15:56 [INFO]: Deployed the following resources to your account:
2021-09-21T15:15:56 [INFO]: - CloudFront Domain ID: d11p7906k936xa
2021-09-21T15:15:56 [INFO]: - SSR Lambda@Edge: 4a03d77-u0dvfhd
2021-09-21T15:15:56 [INFO]: - API Lambda@Edge: 4a03d77-0jjxrp
2021-09-21T15:15:56 [INFO]: - Image Optimization Lambda@Edge: 4a03d77-prh8oqj
2021-09-21T15:15:56 [INFO]: - S3 Bucket: 4a03d77-gjf52si
2021-09-21T15:15:56 [INFO]: SSR Deployment complete
```
When we delete the Git branch, the environment disappears from the Amplify console. However, it still leaves the S3 bucket, the lambda functions (and their IAM role) and the cloudfront distribution stay in AWS.

**Describe the solution you'd like**
I want AWS to delete these resources. Cleaning them up manually is a lot of work. I am writing scripts for it now, but it is really a pain (disabling the cloudfront distributions takes a while and I have to make sure my script waits for it).

I contacted the premium AWS support via my company, and they said:

"I understand that you want to know why the automatically created environment in Amplify Console does not de-provision resources on branch deletion.

You seem to be using SSR in your App. If so, this is a known issue and the team is already working on a fix. Although I can not provide an exact ETA on when these changes will be implemented as I do not have visibility regarding the same, this should be fixed in an upcoming update. I would request you to monitor our blogs and What's new page for updates on any enhancements or new releases. You can also open an issue on GitHub[1] where you can interact directly with the Amplify Console team and monitor the issue progress there."

So here it is. I would appreciate if you guys can notice me when this gets fixed.

**Comment by victorccccc** [comment]
Hi @Leejjon, can we know the AppId for further investigation? Thanks

**Comment by Leejjon** [comment]
Here is the one of my test project: d3vi5l09es50zc
The full source:
https://github.com/Leejjon/next-with-logging

**Comment by victorccccc** [comment]
> The logs are from a production project, and I'd rather not post the app id publicly.
> 
> Instead I have a test project with the same problem. The app id is d3vi5l09es50zc
> The full source:
> https://github.com/Leejjon/next-with-logging

Thanks for your information, have you tried to delete `acc2` branch? for this `d3vi5l09es50zc` app

**Comment by Leejjon** [comment]
> > The logs are from a production project, and I'd rather not post the app id publicly.
> > Instead I have a test project with the same problem. The app id is d3vi5l09es50zc
> > The full source:
> > https://github.com/Leejjon/next-with-logging
> 
> Thanks for your information, have you tried to delete `acc2` branch? for this `d3vi5l09es50zc` app

Indeed that is one of the branches I tested with, but I ran into another problem there, we reached our 100 buckets limit (which was caused by many s3 buckets of amplify branches already gone). I will remove some of the buckets that are not in use anymore tomorow. The region is eu-west-1 by the way.

**Comment by Leejjon** [comment]
I managed to successfully deploy the environment from the "acc" branch now (acc had zero differences with the main branch).
2021-09-28T09:57:29 [INFO]: Starting Deployment
2021-09-28T09:57:29 [INFO]: Updating Edge config
dId 0000000008
2021-09-28T09:57:53 [INFO]: Deploying SSR Resources. Distribution ID: E32JW490SGE0NI. This may take a few minutes...
2021-09-28T09:57:53 [INFO]: Deployed the following resources to your account:
2021-09-28T09:57:53 [INFO]: - CloudFront Domain ID: d3nhetti8gew0t
2021-09-28T09:57:53 [INFO]: - SSR Lambda@Edge: zhgmsl-mn2ug7
2021-09-28T09:57:53 [INFO]: - API Lambda@Edge: zhgmsl-wk3vf5m
2021-09-28T09:57:53 [INFO]: - S3 Bucket: zhgmsl-95xmx1
2021-09-28T09:57:53 [INFO]: SSR Deployment complete

After this, I deleted the acc branch. All these resources are still in my aws account.

**Comment by victorccccc** [comment]
> I managed to successfully deploy the environment from the "acc" branch now (acc had zero differences with the main branch) once I deleted some S3 buckets to make space. 2021-09-28T09:57:29 [INFO]: Starting Deployment 2021-09-28T09:57:29 [INFO]: Updating Edge config dId 0000000008 2021-09-28T09:57:53 [INFO]: Deploying SSR Resources. Distribution ID: E32JW490SGE0NI. This may take a few minutes... 2021-09-28T09:57:53 [INFO]: Deployed the following resources to your account: 2021-09-28T09:57:53 [INFO]: - CloudFront Domain ID: d3nhetti8gew0t 2021-09-28T09:57:53 [INFO]: - SSR Lambda@Edge: zhgmsl-mn2ug7 2021-09-28T09:57:53 [INFO]: - API Lambda@Edge: zhgmsl-wk3vf5m 2021-09-28T09:57:53 [INFO]: - S3 Bucket: zhgmsl-95xmx1 2021-09-28T09:57:53 [INFO]: SSR Deployment complete
> 
> After this, I deleted the acc branch. And all these resources are still in my aws account. The backend too, but that is quite easy to delete as I can just delete the generated cloudformation stack and run aws amplify delete-backend-environment --app-id d3vi5l09es50zc --environment-name acc
> 
> The cloudfront distribution and related edge lambda's are a pain to delete manually and it's quite hard to script.

Hi, I can see Cloudfront distribution E32JW490SGE0NI has been deleted successfully. Typically the deletion will take a few minutes. do you still see Lambda@Edge function and S3 bucket in your account?

**Comment by Leejjon** [comment]
Hmm I guess it does work for this project then. Can you explain what exactly cleans up these resources? Is it the amplify service role? This test project has AdministratorAccess, but my main production project has reduced access. Do you reckon I need to give the service role rights to delete cloudfront/lambda/s3 buckets?

**Comment by victorccccc** [comment]
> Hmm I guess it does work for this project then. Can you explain what exactly cleans up these resources? Is it the amplify service role? This test project has AdministratorAccess, but my main production project has reduced access. Do you reckon I need to give the service role rights to delete cloudfront/lambda/s3 buckets?

Sorry for the inconvenience, we recently fixed SSR resources not being deleted issue. However, your service role should have permission to delete CloudFront/Lambda/S3 buckets.
