### ISSUE TITLE
SSL verification is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by despau** [aws-amplify/amplify-console#228]
**App Id**: d1ivk7sfrct595
**Region**: us-east-1
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Joycehao19** [comment]
@despau  Looks like your domain is in PENDING_VERIFICATION status. Please try to remove and add the custom domain again. The following links show the way to set up :
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html
https://docs.aws.amazon.com/amplify/latest/userguide/howto-third-party-domains.html

If you still face the same issue, please let us know.

**Comment by despau** [comment]
Thank you very much for the help. Everything is working now. I appreciate
the effort.

Regards
