### ISSUE TITLE
Tag Underlying SSR Resources

### ISSUE THREAD

**Issue by jonathanlemonsonos** [aws-amplify/amplify-console#2282]
**Is your feature request related to a problem? Please describe.**
I am trying to tag resources for cost reporting purposes and am unable to do so easily in Amplify. We have a front end only SSR application so the tags.json file does not work. The CLI also does not allow for tagging of underlying resources, only the amplify arn itself.

**Describe the solution you'd like**
In the console, or amplify.yml, it would be great to define tags in one central location and have them apply to all the generated underlying resources.

**Additional context**
This would be a major help to our organization as we are currently unable to tag, and report cost, on our resources easily. Having this within the existing flow would be of a great benefit to us.

**Comment by swaminator** [comment]
You can use Amplify hosting to tag resources: https://docs.aws.amazon.com/amplify/latest/userguide/resource-tagging-support-chapter.html

**Comment by jonathanlemonsonos** [comment]
Why is this closed? I know I can tag with the CLI but it is very cumbersome.

I have to find each and every resource and then run the command for each. 8 commands to tag the resources, which also vary by service.

Would it not make more sense to be able to do this at the amplify project level?
