### ISSUE TITLE
Having problem with domain activation

### ISSUE THREAD

**Issue by GMM92** [aws-amplify/amplify-console#2283]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-1:844224957600:apps/delf4nbw9vszb

### Region

US-East (N VIrginia)

### Step

Custom Domain Activation

### Status

Failed

### Issue or question

I am trying to set up a custom domain (www.letsjusttalk.org) with this app.  I have changed the name servers in Godaddy based on Route 53 instruction.  But then I am receiving an error when AWS is trying to activate the domain.  The error message indicates that this domain has already been used with another app, even though that's not the case (I have not associated this domain with any additional app).  But there may be a twist to the situation.  I did start creating an app with this same name but quickly realized that I chose the wrong region selected, US East (Ohio) instead of US East (N Virginia). So I changed the region and started creating the app from scratch.  However, I did not add a custom domain in my previous try. 
And I can't figure out why AWS is having trouble activating the domain with this app.  Can you please let me know where is the issue and what can I do to resolve it?
Please see the error message for further details. 
![image](https://user-images.githubusercontent.com/22373410/135144284-5bd07b8e-e6a0-43a2-a411-f89b99d7de74.png)

### Error message

![image](https://user-images.githubusercontent.com/22373410/135144198-e46f2953-5c0f-4422-a295-0a09519aa0cf.png)

### Additional information

ss

**Comment by ferdingler** [comment]
Hi @GMM92, your domain is being used in another app (dwdalmitcqq4t) in the Ohio region by your same AWS account. Can you double check that app and make sure the custom domain is deleted from it?

**Comment by hloriana** [comment]
Closing due to no response. If you're still having this issue feel free to re-open. Thanks!
