### ISSUE TITLE
 [ERROR]: {"code":"7","message":"No ssrResources.json file"} when deploying a SSR Next Js App

### ISSUE THREAD

**Issue by abdullahmujahidali** [aws-amplify/amplify-console#2284]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Not applicable

### Amplify Categories

hosting

### Environment information

<details>

```
# Put output below this line

2021-09-29T04:42:25 [INFO]: Beginning deployment for application dh8mh8nkle4ny, branch:dev, buildId 0000000018
2021-09-29T04:42:26 [INFO]: Cannot find any generated SSR resources to deploy. If you intend for your app to be SSR, please check your app Service Role permissions. Otherwise, please check out our docs on how to setup your app to be detected as SSG (https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app)
2021-09-29T04:42:26 [ERROR]: {"code":"7","message":"No ssrResources.json file"}

```

</details>

### Describe the bug

When I try to deploy my Next JS app on Amplify I encounter this error. My build is 100% successful but I don't know why I am getting this error. I have set my app Service Role permission.

I am using Amplify website to deploy my Next JS application ( not with Amplify CLI)

### Expected behavior

100% status on deploy

### Reproduction steps

1. Connected my Github Private Repo with Amplify
2.  Build the project (100% success)
3. Fails on Deploy with the error above.

### EXPECTED OUTPUT

<img width="1378" alt="Screenshot 2021-09-29 at 1 14 30 PM" src="https://user-images.githubusercontent.com/48271080/135229726-286001f9-807d-49a7-8387-16fad2a2ab53.png">

### ACTUAL OUTPUT

// Put your logs below this line

<img width="1380" alt="Screenshot 2021-09-29 at 1 15 09 PM" src="https://user-images.githubusercontent.com/48271080/135229840-593fa6df-47d7-4bdd-8f14-16b6c24f1761.png">

**Comment by chrisbonifacio** [comment]
Hi @abdullahmujahidali 👋 Thank you for raising this! transferring this issue over to the console repo as it seems more related to hosting than the Amplify JS library.

**Comment by ttlpta** [comment]
Any updated for this issue?

**Comment by LuisBrime** [comment]
I got the same issue and spent hours trying to figure out what was wrong, finally, I realized that I was using `yarn`'s **berry** version to manage my project, and when Amplify builds the app; it uses the **classic** version. So after installing again the dependencies with the **classic** version, it finally worked.

I was using NextJs version 12 and initially thought that was the problem, but I managed to deploy that version with the `yarn` change.

Hope this helps someone.

**Comment by shishkin** [comment]
>  I realized that I was using yarn's berry version to manage my project, and when Amplify builds the app; it uses the classic version

I had the same issue and thought yarn would look into `.yarnrc.yml` file to look for yarn implementation.

**Comment by andypanix** [comment]
Same error as above, `No ssrResources.json file`. The build procedure was stopping at the SSG phase, and was skipping the SSR build.

I've a mixed SSG and SSR nextJS 12 app and I solved the problem adding this line  `"export": "next build && next export",` to the `package.json` script.

```
"scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "export": "next build && next export",

```

**Comment by victorccccc** [comment]
Hi, here is the docs for deploying SSR App (Package.json file settings) https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app 

Feel free to re-open this if issue persists, thanks!

**Comment by NotSoShaby** [comment]
I'm having the same issue. I'm not using yarn berry (for all I know). This happens after updating to next12 version. @victorccccc I followed the instructions and even admin access to the amplify-backend-deployment role did not work. I think this should be reopened

**Comment by rei-shaholli** [comment]
@NotSoShaby 

try running:
`aws amplify update-app --app-id <APP_ID> --platform WEB --region <REGION>`

if you've followed everything in this article: https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app

Also, take a look at this helpful link: https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#convert-an-ssr-app-to-ssg

**Comment by man517** [comment]
I'm also facing this issue when using Amplify's build preview feature. I've tried everything above and nothing has worked. Interestingly enough though, sometimes a build generated from a new PR with the same code used in a different PR's build preview that failed will succeed (I have no idea why). Any help on this matter would be great, it is quite frustrating.
