### ISSUE TITLE
amplify cmd error response

### ISSUE THREAD

**Issue by increasifydev** [aws-amplify/amplify-console#2298]
amplify version
ENOENT: no such file or directory, stat 'emulator'
Error: ENOENT: no such file or directory, stat 'emulator'

**Comment by siegerts** [comment]
Hi :wave: - thanks for raising this!  To get a bit more context, do you mind porting this to one of the formatted templates listed here:

- [bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml&title=) or [usage question](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=question&template=3.usage-question.md&title=)

This will help the team determine the best approach to take.
