### ISSUE TITLE
Custom domain for pattern-based branch deployments

### ISSUE THREAD

**Issue by nikovirtala** [aws-amplify/amplify-console#23]
**Is your feature request related to a problem? Please describe.**
The new pattern-based branch deployments are neat but they get endpoint only from builtin amplifyapp.com domain.

**Describe the solution you'd like**
I'd like have an option to use my custom domain also on pattern-based branch deployments.

**Comment by swaminator** [comment]
@nikovirtala @mwarkentin @thys-unomena @visusnet @menge101 @federicopuntoni @rkul this feature is now supported: https://aws.amazon.com/blogs/mobile/automatically-create-and-delete-custom-sub-domains-for-your-branch-deployments-with-amplify-console/
