### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by aprabhakar90** [aws-amplify/amplify-console#231]
**App Id**: d1zp1nkmpr9my5
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by swaminator** [comment]
@lion-and-lotus what reason are you seeing?

**Comment by lion-and-lotus** [comment]
One or more of the CNAMEs you provided are already associated with a different resource. 

I have checked and I don't see any cloudfront distributions.

**Comment by Joycehao19** [comment]
Hi @lion-and-lotus Is this domain connected to a different App that you own? 
Can you check `CNAMEAlreadyExistsException Error` section of
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-troubleshoot-guide ?

**Comment by lion-and-lotus** [comment]
I checked as per the directions you provided, including using the AWS CloudFront console and I do not currently see any distributions. Please advise.

**Comment by Joycehao19** [comment]
@lion-and-lotus It seems like you deleted your app. Did you try to add the custom domain on your app? Did you still see the issue?

**Comment by lion-and-lotus** [comment]
Yes, I re-created a new instance of the app and tried adding the custom domain once again. I am still experiencing the same issue.

**Comment by Joycehao19** [comment]
@lion-and-lotus Do you still have the app in App Id: d1zp1nkmpr9my5, region us-west-2? If not, could you please create it.

**Comment by lion-and-lotus** [comment]
The new App Id is d3hrm7k8egypi9 in region us-west-2. Apologies for the delayed response.

**Comment by lion-and-lotus** [comment]
Been a while since I heard back. Can someone please help?

**Comment by aprabhakar90** [comment]
Created the same app again with new app id. Reopened it as a new issue. Closing this one. Thanks!
