### ISSUE TITLE
Only deploy backend without frontend (react-native)

### ISSUE THREAD

**Issue by AlessandroVol23** [aws-amplify/amplify-console#2313]
**Please describe which feature you have a question about?**
I'd like to automatically deploy my backend on every commit but only the backend. The console forces me to enter some frontend phases to the build specs as well. Since I am developing a react-native app Amplify cannot build it. 
How can I configure ONLY backend deploys?

**Comment by AlessandroVol23** [comment]
Basically, I need that for frontend. Is this possible? 
![image](https://user-images.githubusercontent.com/19362086/136783187-c32d6c4e-86e8-4978-8d8d-db47886789c7.png)

**Comment by swaminator** [comment]
@AlessandroVol23 try this: https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#enable-diff-deploy

**Comment by AlessandroVol23** [comment]
Okay but do I understand it correctly if I activate `AMPLIFY_DIFF_DEPLOY` and there is a difference in the `src` folder it will execute the frontend right? 
Becuase I never want to build the frontend and deploy it.

**Comment by hloriana** [comment]
@AlessandroVol23 This is not possible at the moment. `AMPLIFY_DIFF_DEPLOY` will skip building a frontend if there aren't any changes detected in the `src` folder so the frontend won't be updated but it will be hosted.
