### ISSUE TITLE
My SSL cert issued by Amazon expired on 10/12/2021, doesn't it renew automatically?

### ISSUE THREAD

**Issue by timendez** [aws-amplify/amplify-console#2324]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dbk544gce61z8

### Region

us-west-1

### Step

SSL Cert Renewal?

### Status

Did not happen

### Issue or question

If you go to https://www.shopbysub.com/ you can see that the SSL cert issued by Amazon has expired.

Do I really have to set a reminder in my calendar to re-create my site in Amplify once a year? Seems a little strange.

Please help I'm losing users!

### Error message

```
Subject: *.shopbysub.com

Issuer: Amazon

Expires on: Oct 12, 2021

Current date: Oct 15, 2021
```

**Comment by ferdingler** [comment]
Hi @timendez, I'm sorry you had this problem with your certificate. That's correct, the CNAME verification record should not be removed from your domain. We attempt to renew your certificate 60 days prior expiration time but we have to confirm that you still own the domain by checking the CNAME verification record. If it is not present, we continue to retry until it expires. At which point, the only solution is to delete the domain and re-add it so that we can provision a brand new cert again.

**Comment by chrodin** [comment]
We also had the problem of the certificate expiring on my Amplify app 18 months after initial setup.

Unlike some reports above, we had NOT removed the CNAME record, and still it failed to renew. The DNS is being managed via Route 53. This should probably be looked at by the AWS team..

Process:

1. Removed the custom domain on `Amplify > Domain settings`
2. Added the domain, and was given CNAME to add to DNS
3. Went to Route 53 to add CNAME, but got message that said said `InvalidChangeBatch 400: Tried to create resource record set [name='_abunchoflettersandnumbers.mydomain.com.', type='CNAME'] but it already exists`
4. Waited a few mins and the process succeded and domain was working again.

For anyone going through this, the whole process only took a couple of minutes before the domain had the new SSL Cert active, so it was very fast.

**It is, however, very worrying that the cert was not renewed automatically!**

In the Amplify domain settings it said `HTTPS is automatically enabled for your custom domains to secure traffic` and that Amazon Certificate Manager was the certificate issuer. So even there it was not aware of that the cert was expired or that there had been any issues
