### ISSUE TITLE
Import backend env made in previous version of console / cli

### ISSUE THREAD

**Issue by tscole** [aws-amplify/amplify-console#2328]
I have an amplify project that I first deployed over two years ago. I've not done much development on it since then, but it does have active users.

In the current version of the console the front end environments are listed but there are no backend environments. However the app has two backend environments (dev and production) and the corresponding CloudFormation stacks all exist along with their associated dynamo tables, cognito pools and so on.

Trying to user `amplify push` or `amplify pull` results in the error `An error occurred during the push operation: The specified key does not exist.`

I need to get the cli and console to recognise my existing environments. How can I do this?

Region: eu-west-2
AppId: d2z0aapvx3jong

**Comment by hloriana** [comment]
Hi @tscole, it looks like you were able to successfully push changes after this issue was created. If this is still a problem, please feel free to reopen. Thanks!

**Comment by tscole** [comment]
This is still a problem
