### ISSUE TITLE
Rewrite rule for sub domains to sub directory causes an infinite loop.

### ISSUE THREAD

**Issue by tmbtech** [aws-amplify/amplify-console#233]
**Describe the bug**
Adding a rewrite rule which redirects a subdomain to a subdirectory causes an infinite redirect loop.

**To Reproduce**

1. Click `Domain management` link in the menu
2. Manage subdomain
3. create a subdomain "https://subdomain.example.com" and point it to master
4. click `rewrites and redirects` in the menu
5. add the redirect 
```
[
  {
    "source": "https://subdomain.example.com",
    "target": "/website",
    "status": "301",
    "condition": null
  }
]
```
6. in the browser goto `https://subdomain.example.com`
7 chrome will redirect to `https://subdomain.example.com/website/website/website/website....`

**Expected behavior**
Browse to `https://subdomain.example.com` and get redirected to `https://subdomain.example.com/website`

**Additional context**
The website is a SPA using CRA.

Thanks for your help, let me know if you need me to provide any more info/context.

**Comment by swaminator** [comment]
Can you try:
```
  {
    "source": "/",
    "target": "/website",
    "status": "301",
    "condition": null
  }
```

**Comment by tmbtech** [comment]
> Can you try:
> 
> ```
>   {
>     "source": "/",
>     "target": "/website",
>     "status": "301",
>     "condition": null
>   }
> ```

Sorry, I should have provided more context. I have 3 different apps and would like to provide a vanity url. For example, each subdomain is routed to a different app. I'm basically running a monolithic repo, with multiple websites and npm modules.

```
[  
  {
   source: "https://appA.example.com"
   target: "/appA/index.html"
   status: "200"
  },
  {
   source: "https://appB.example.com"
   target: "/appB/index.html"
   status: "200"
  },
  {
  source: "https://appC.example.com"
   target: "/appC/index.html"
   status: "200"

  }
]

```
 
would be ideal, but that didn't seem to work either.


the below caused an infinite redirect loop.

```
[  
  {
   source: "https://appA.example.com"
   target: "/appA"
   status: "301"
  },
  {
   source: "https://appB.example.com"
   target: "/appB"
   status: "301"
  },
  {
  source: "https://appC.example.com"
   target: "/appC"
   status: "301"
  }
]

```

**Comment by Joycehao19** [comment]
@tmbtech Sorry that you are facing this issue. We are currently investigating it.

**Comment by swaminator** [comment]
@tmbtech here's what you can do:
1. Connect 3 different apps using the same monorepo in the Amplify Console (one for each of your apps: admin, consumer, other) 
2. For each app connect a subdomain.
3. For each app, add the specific redirect. For example in the admin.example.com app, add a redirect like: 
```
  {
    "source": "/",
    "target": "/admin/index.html",
    "status": "200",
    "condition": null
  }
```
This will solve your usecase.

**Comment by tmbtech** [comment]
> @tmbtech here's what you can do:
> 
> 1. Connect 3 different apps using the same monorepo in the Amplify Console (one for each of your apps: admin, consumer, other)
> 2. For each app connect a subdomain.
> 3. For each app, add the specific redirect. For example in the admin.example.com app, add a redirect like:
> 
> ```
>   {
>     "source": "/",
>     "target": "/admin/index.html",
>     "status": "200",
>     "condition": null
>   }
> ```
> 
> This will solve your usecase.

I'll give it a try and report back, thank you for your suggestion!

**Comment by tmbtech** [comment]
Just reporting back in case anyone else sees this. The suggestion worked perfectly. Thank you @swaminator
