### ISSUE TITLE
Change api authorization from api key to IAM

### ISSUE THREAD

**Issue by ParulSharma2622** [aws-amplify/amplify-console#2332]
We have built a white label solution using AWS Amplify and React JS, so we have a simple admin panel from where we can add some dynamic options which can be used at frontend according to different whitelabel requirements.

We are using graphql api at admin panel, but unfortunately using api-key as authorization in production mode. Now, We want to change it to IAM. We have tried using amplify update API but not able to change the authorization. 

Can anyone help me to find out a way for updating authorization right from Amplify admin UI or appsync dashboard. 

Here are our app id and region:

app id : d2pn7gfisu8uje

region : ap-southeast-2

Thanks in advance.

**Comment by ParulSharma2622** [comment]
can somebody help me to resolve this problem.

**Comment by hloriana** [comment]
Hi @ParulSharma2622 👋🏽!  Thanks for reaching out and apologies on the delay. Did you receive any errors when running `amplify update api` and selecting `IAM` for the default authorization type?

**Comment by ParulSharma2622** [comment]
I will try running everything once again and will share screenshots here.

**Comment by ParulSharma2622** [comment]
Hi, Please check the screenshot to better understand the problem I am facing.

![Screenshot_58](https://user-images.githubusercontent.com/69511562/140692083-330de3e6-aa34-4f57-a1dd-795aaacd90e6.png)

**Comment by ParulSharma2622** [comment]
Finally resolved this issue. I am writing the steps that I followed :

1. Added IAM authorization rule for data model and removed API key rule using admin console.
2. After this, I took latest pull of amplify application on my local integration.
3. Run **amplify update api** command from cli and change authorization for graphql api from **api-key to IAM**.
4. Then push all the changes using **amplify push** command.
5. After this, you have to add permission for unauthorized IAM role to access appsync APIs, graphql operations etc.
6. That's it. Amplify will use identity pool id saved in aws exports file to generate temporary credentials for authorization purpose.

You can go to identity pool and from there you will know the name of unauth role which is assigned to that identity pool. You can then go to IAM dashboard to assign all the required permissions.

Thanks,
