### ISSUE TITLE
Delete previous builds

### ISSUE THREAD

**Issue by ThinkingAbout** [aws-amplify/amplify-console#2338]
Hi everyone, is it possible to delete previous builds of our app? From what I have understood the size of the app continues to increase and I do not have any need. Thanks!

**Comment by spormeon** [comment]
@ThinkingAbout do you believe that leaving these "contributes" to the overall "data storage" charges we all see in aws bills, I've asked this question else where and they all just ignored it

**Comment by hloriana** [comment]
Hi @spormeon 👋🏽 no, these do not contribute to storage costs.

**Comment by spormeon** [comment]
@hloriana so what does contribute to "GB build artifacts stored"  , as the onlt thing that seems to increase it, is pushing new builds etc.  I can t find any info on this anywhere and zero on how to reduce the storage?
