### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by ryanm43** [aws-amplify/amplify-console#235]
**App Id**: d3pra1i98n24cg
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

Error message
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

Notes
We used the domain before for a CloudFront distribution but we deleted everything.

**Comment by Joycehao19** [comment]
@ryanm43 It seems like your domain works fine now (www.roxxxxxxxxar.com & testapp.roxxxxxxxxar.com). If you face the same issue, please let us know.
