### ISSUE TITLE
Amplify CI/CD will build a backend no matter what

### ISSUE THREAD

**Issue by SebastianKurp** [aws-amplify/amplify-console#2352]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d25uttzj9fmok

### Region

us-east-2

### Amplify Console feature

Backend builds

### Describe the bug

For one of my deploys I want to use an existing backend since a new backend is not needed and would cut down on our costs. No matter what logic I do, the build will still deploy. The logic below will still deploy. I have noticed if I remove 
`amplifyPush --simple` from the yml it will not deploy.

Build Settings YAML
```
backend:
  phases:
    build:
      commands:
        - echo ${AWS_BRANCH} "<>"
        - echo [ "${AWS_BRANCH}" = "test" ] || [ "${AWS_BRANCH}" = "prod" ] "<>"
        - if [ "${AWS_BRANCH}" = "qa" ]; then echo "qa branch"; fi
        - if [ "${AWS_BRANCH}" = "test" ] || [ "${AWS_BRANCH}" = "prod" ]; then npm i -S graphql-ttl-transformer; fi
        - if [ "${AWS_BRANCH}" = "test" ] || [ "${AWS_BRANCH}" = "prod" ]; then amplifyPush --simple; fi
```
Results:
```
# Starting phase: build
                                 # Executing command: echo qa "<>"
                                 qa <>
                                 # Executing command: echo [ "qa" = "test" ] || [ "qa" = "prod" ] "<>"
2021-10-28T19:15:40.591Z [INFO]: [ qa = test ]
                                 # Executing command: if [ "qa" = "qa" ]; then echo "qa branch"; fi
                                 qa branch
                                 # Executing command: if [ "qa" = "test" ] || [ "qa" = "prod" ]; then npm i -S graphql-ttl-transformer; fi
2021-10-28T19:15:50.320Z [INFO]: [0mAmplify AppID found: d25uttzj9fmok. Amplify App name is: AppName[0m
2021-10-28T19:15:50.404Z [INFO]: [0mBackend environment dev found in Amplify Console app: AppName[0m
2021-10-28T19:15:53.555Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2021-10-28T19:15:55.354Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2021-10-28T19:15:56.305Z [INFO]: 
```

### Expected behavior

The `amplifyPush --simple` does not run because the if statement is false.

### Reproduction steps

- Push a Pr To the QA Branch
- Wait for the CI/CD to run
- Fails on the backend step

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - echo ${AWS_BRANCH} "<>"
        - echo [ "${AWS_BRANCH}" = "test" ] || [ "${AWS_BRANCH}" = "prod" ] "<>"
        - if [ "${AWS_BRANCH}" = "qa" ]; then echo "qa branch"; fi
        - if [ "${AWS_BRANCH}" = "test" ] || [ "${AWS_BRANCH}" = "prod" ]; then npm i -S graphql-ttl-transformer; fi
        - if [ "${AWS_BRANCH}" = "test" ] || [ "${AWS_BRANCH}" = "prod" ]; then amplifyPush --simple; fi
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 14.17.0
        - nvm use 14.17.0
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
```

**Comment by ganipcanot** [comment]
To conditionally build the backend:

Have you seen this? https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html More specifically: `AMPLIFY_DIFF_BACKEND`


"You can configure Amplify to use diff based backend builds using the AMPLIFY_DIFF_BACKEND environment variable. When you enable diff based backend builds, at the start of each build, Amplify attempts to run a diff on the amplify folder in your repository. If Amplify doesn't find any differences, it skips the backend build step, and doesn't update your backend resources. If your project doesn't have an amplify folder in your repository, Amplify ignores the value of the AMPLIFY_DIFF_BACKEND environment variable."

**Comment by swaminator** [comment]
You can also follow this blog: https://aws.amazon.com/blogs/mobile/complete-guide-to-full-stack-ci-cd-workflows-with-aws-amplify/
