### ISSUE TITLE
Connect to CodeArtifact

### ISSUE THREAD

**Issue by Vector-Hector** [aws-amplify/amplify-console#2359]
I am building an amplify react app and trying to connect it to my private npm packages in my CodeArtifact repository. However, everything I try results in a `error An unexpected error occurred: "<some-package-url>: Request failed \"401 Unauthorized\"".`

I added the login to my `amplify.yml` and a policy, that grants the amplify service role the permission to fetch from CodeArtifact. 
The login succeeds, but the build is still unable to fetch any npm packages.

I noticed, that the build environment variables do not contain any AWS access key id or secret. Is this intended? Doesn't the login need that to authorize?

**Comment by hloriana** [comment]
Hi @Vector-Hector 👋🏽, can you provide your App ID and the region your app is deployed in please

**Comment by Vector-Hector** [comment]
Sure. AppId: d1l6dvqrsfcs1c, region: eu-central-1

**Comment by Vector-Hector** [comment]
I just tried creating a new user, that has my CodeArtifact policy and added the credentials to the amplify build environment. However it still fails. I tested `yarn install` on my local windows machine using that user which works without any issues... Why do these calls fail with 401 in the builds? I'm really lost right now.

**Comment by hloriana** [comment]
Hi @Vector-Hector, I'm still looking into what could be the cause. We can see in your build logs that logging into CodeArtifact is successful but once the next build command is called, you get the 401 error. I wasn't able to reproduce this behavior 🤔, but I'm still looking into what could be causing this.

**Comment by Vector-Hector** [comment]
Hi @hloriana , thanks for trying to help. Unfortunately my issue gets weirder.
While trying to reduce the amount of steps to reproduce, I created a new react app and deployed it via amplify with default values. It still gave me an error 401, even before I used any login procedure. It tries to fetch from my CodeArtifact repository, even though I did not tell that amplify app, that it even exists. How is this possible? 
AppId for this one is d2me0l3nqv6h3k

**Comment by Vector-Hector** [comment]
Ok I resolved my issue by deleting `yarn.lock` and adding it to `.gitignore`.

The problem was, that yarn caches the resolved package address in `yarn.lock`. That address was in my CodeArtifact repository, because I was logged in while installing dependencies on my dev machine. Since `yarn.lock` is not in `.gitignore` by default, I just pushed it into the build. When yarn installs dependencies in build, it uses the cached addresses, which can't be reached anymore.

**Comment by hloriana** [comment]
@Vector-Hector I'm glad you were able to figure out the problem! 🥳 

And the reason why CodeArtifact was still being accessed is because you need to switch back to the default npm registry: run `npm config set registry https://registry.npmjs.com/`  when you no longer want to access your CodeArtifact repository. If you don't, NPM will keep prompting you to authenticate back into your CodeArtifact repo. 

Ref: https://docs.aws.amazon.com/codeartifact/latest/ug/npm-auth.html

**Comment by Vector-Hector** [comment]
@hloriana Okay, thanks! That makes sense.
