### ISSUE TITLE
404 (Rewrite) to static 404.html file not working

### ISSUE THREAD

**Issue by patleeman** [aws-amplify/amplify-console#236]
**Describe the bug**

I have an application that looks like this:

```
|-- /static
|---- /404.html
|-- index.html
```

I want to rewrite the path `/404.html` -> `/static/404.html` so I set up my rewrites like this:

![Screen Shot 2019-11-08 at 5 28 10 PM](https://user-images.githubusercontent.com/11035426/68514917-2a155580-024d-11ea-8358-6e6d50f9119e.png)

When I navigate to `/404.html` it falls through to my catch all and I'm redirected to example.com/404.html. Note that `404.html` in this example could be any url like If I wanted to 404 `/testpagethatshouldreturn404`.
 
If i change it to a 200 rewrite, it serves the page as intended.

![Screen Shot 2019-11-08 at 5 30 49 PM](https://user-images.githubusercontent.com/11035426/68515020-8a0bfc00-024d-11ea-9f0f-35052edc6717.png)
**To Reproduce**
1. Create an extremely simple application with an index.html, and a static folder with a 404.html file inside it.
2. Deploy to an amplify application.
3. Set up the rewrites and redirects like in the screen shot. 

**Expected behavior**
I expect when I navigate to `/404.html` it rewrites to `/static/404.html` and returns a 404 status code.

**Additional context**

**Sample code**
- Sample application [test_amplify.zip](https://github.com/aws-amplify/amplify-console/files/3826530/test_amplify.zip)
- Rewrite & Redirect code

```
[
    {
        "source": "/404.html",
        "target": "/static/404.html",
        "status": "200",
        "condition": null
    },
    {
        "source": "/",
        "target": "/index.html",
        "status": "200",
        "condition": null
    },
    {
        "source": "/<*>",
        "target": "https://www.example.com/<*>",
        "status": "302",
        "condition": null
    }
]
```

**Comment by patleeman** [comment]
I'm still not sure I understand how the rewrites and redirects work for 404 (Rewrite). I assumed it would function similarly to the 200 (Rewrite) where we would be able to take a path, say /404, and rewrite it to a destination, say /404.html while returning a 404 error code.

I simplified my project to:

| - index.html
| - 404.html

If I have a rewrite and redirect that looks like this:

[
    {
        "source": "/",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]

Going to /,  /index.html, and /404.html all return a 200 as expected because it's serving the files it finds. Next, testing this: 

[
    {
        "source": "/",
        "target": "/index.html",
        "status": "200",
        "condition": null
    },
    {
        "condition": "",
        "source": "/error",
        "status": "200",
        "target": "/404.html"
    }
]

Going to /error does a 200 rewrite to /404.html as expected.

If I change it to this:

[
    {
        "source": "/",
        "target": "/index.html",
        "status": "200",
        "condition": null
    },
    {
        "source": "/error/",
        "target": "/404.html",
        "status": "404-200",
        "condition": null
    }
]

Going to /error/ shows the Access Denied screen. (If you change it to /error, it redirects to /error/). Probably because there is no catch-all route.

The only case I could get anything to return a 404 error code was the catch-all case:

[
    {
        "source": "/",
        "target": "/index.html",
        "status": "200",
        "condition": null
    },
    {
        "source": "<*>",
        "target": "/404.html",
        "status": "404-200",
        "condition": null
    }
]

What is extra confusing to me is that there is little to no documentation around 404 behavior and I can't for the life of me find any documentation other than the tiny blurb on this page: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html 

Some clarification around this feature would really be helpful.

**Comment by Joycehao19** [comment]
@patleeman we have identified the bug and are investigating a fix. The ordering rules are not being applied to the 404 rewrites which is why the rules are not being applied. We'll update you when we rollout a fix.

**Comment by nimacks** [comment]
@patleeman , a fix has been pushed out for this. Feel free to close this ticket after verifying.
