### ISSUE TITLE
Console Backend Deployment Fails with Function Env Variables

### ISSUE THREAD

**Issue by mgarabedian** [aws-amplify/amplify-console#2365]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-1

### Describe the bug

I am having backend deployment issues in the amplify console. Environmental variables in functions, which have been set correctly, end up not being picked up by the backend and the deployment fails. The issue was discussed with josef on the amplify-hosting discord channel.  I also notice in general that backend deployments seem to not be picking up latest code changes and deploying them.

NOTE: This may be related to Admin UI not being enabled. It is not enabled in my case.

### Expected behavior

Deploy succeeds

### Reproduction steps

This is what I see, end to end ( both my local and amplify console are 6.3.1 ):

- Create an environmental on a function, via 'amplify update function'
- team-provider-info.json, function-parameters.json and FUNCTION-cloudformation-template.json are updated accordingly.
- 'amplify push' from local terminal pushes and succeeds.
- Lambda console shows the env variable and value correctly.

I then commit code to git, amplify console is picking up the commit and attempts backend/frontend deploy.  The backend deploy starts, and fails, with a rollback:

- "Parameters: [testEnvironmental] must have values"

### Additional information

Admin UI is NOT enabled

**Comment by hloriana** [comment]
Hi @mgarabedian 👋🏽. Thanks for raising this issue. What is the ID of your Amplify app?

**Comment by mgarabedian** [comment]
@hloriana sure. ID is d38e71f6ezbxf5, us 1 east

**Comment by hloriana** [comment]
Hi @mgarabedian 👋🏽 I was investigating this issue but I see you were able to successfully build recently. Were you able to identify the cause of the behavior and are you still having this problem?

**Comment by hloriana** [comment]
If you are still running into this problem, please feel free to re-open this issue. Thank you!
