### ISSUE TITLE
Domain activation is Failed - CNAMEs you provided are already associated with a different resource

### ISSUE THREAD

**Issue by blomm** [aws-amplify/amplify-console#237]
**App Id**: dbwksz5yaroo9
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Domain name registration fails for the root path

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
In route 53, there does exist a CNAME for the certificate registration (which is necessary). But there are no other CNAMEs when I start the domain activation process in Amplify. When I go into route 53 after the Domain name registration fails, I can see the a CNAME has been added, as I would expect.  
Interestingly sub domain name registrations do succeed, like dev.myurl.com.

Also in route 53, the root domain (myurl.com) has NS type (pointing to 4 NS servers), SOA type and A type.

Also, as soon as I try to register the root domain in Amplify, it breaks any sub-domains that had been registered and working (like dev.myurl.com)

Very stuck here, please help.

**Comment by nimacks** [comment]
@blomm , Sorry to hear that you're having trouble setting up your custom domain. Do you have your root domain associated with any other resources for example a cloud front distribution?

**Comment by blomm** [comment]
Hi @nimacks , in route 53 I have a NS type with four values, an SOA type, and a CNAME type for the certificate verification that points at _somegobledygoop.acm-validations.aws.
Is there somewhere else I should be looking other than route 53?

**Comment by Joycehao19** [comment]
Hi @blomm , Could you please check the `CNAMEAlreadyExistsException Error` section in
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html ? If you still have this issue, please let us know.

**Comment by blomm** [comment]
@Joycehao19 @nimacks 
doh, my bad, I had only "disabled" the cloudfront setup that I had created a few months back. Needed to fully delete it.  Appreciate both your efforts in helping out.
