### ISSUE TITLE
One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by ShellyDumont** [aws-amplify/amplify-console#2370]
I currently have a static website that is hosted through S3. I am trying to use CloudFront so I can add my SSL.
I only have one distribution, so I cannot for the life of me figure out why I am getting the "One or more of the CNAMEs you provided are already associated with a different resource." while trying to add my alternate domains to the distribution. 

I have been through every tutorial and have not yet found an answer.
Is there any other location that the CNAME might already exist without my immediate knowledge? 

Thank you

**Comment by hloriana** [comment]
Hi @ShellyDumont 👋🏽 Usually that error is thrown in these scenarios:

1. You have already used the same custom domain in another Amplify App in another region/account.
2. You are using this domain in another service: LightSail or API Gateway.
3. Your domain has an old CNAME record that points to a cloudfront.net URL from a previous Amplify App.

Can you please confirm if any of these apply to your issue?

**Comment by hloriana** [comment]
Hi @ShellyDumont, if you're still having this issue, feel free to re-open.
