### ISSUE TITLE
is it possible to run docker inside build image?

### ISSUE THREAD

**Issue by nickygb** [aws-amplify/amplify-console#238]
** Please describe which feature you have a question about? **

Is it possible to create a custom build image that contains docker installed or is it there any managed build image with docker already installed? I want to run docker inside my build image in order to build an image and then push it to ECR.

**Comment by Joycehao19** [comment]
@nickygb there isn't a managed build image that has docker pre-installed. You can use our custom container feature to reference a public image with docker installed: https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html

**Comment by MaralKay** [comment]
We would like to mount the host machine's `/var/run/docker.sock` to the build container (from our custom build image), because we need the Docker daemon running in it. Is this somehow configurable in the Amplify console?
