### ISSUE TITLE
[CNAMEAlreadyExistsException] - CNAME exists in an account I don't own or have access to?

### ISSUE THREAD

**Issue by 50k-Adam** [aws-amplify/amplify-console#2382]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2qd73cf0xk67h

### Region

us-east-1

### Step

Domain Activation

### Status

Failed

### Issue or question

We're getting a CNAMEAlreadyExistsException for a website in our account. We use Amplify to deploy a multisite and this is the first time we've hit an issue with a domain. The domain/company was purchased last year and the previous owners don't recognize the AWS account number (account ending in ...) in the error message. We control the DNS for the domain but even though we do a previous CNAME somewhere in the system is preventing us from launching this domain on Amplify. 

How can we fix this if we don't have acccess to or even know who has access to the other account?

### Error message

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below.

Error message: [CNAMEAlreadyExistsException] The following CloudFront distributions are already using one or more of your domains: [Distribution: **********HC27 in AWS Account: **(has different ending #s)**]. If you own these distributions, please remove the domains from them first and then retry adding your domain. If you don't own them, then you may already have associated this domain to another Amplify App in another account or region. You can also check our troubleshooting guide for more help: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

**Comment by 50k-Adam** [comment]
Thanks, looked through the FAQs and troubleshooting guide with no resolution.

**Comment by hloriana** [comment]
Hi @50k-Adam 👋🏽 Can you provide us with the account ID that's showing up in the error logs so we can investigate? It's possible that the CNAME is connected to another resource in that separate account. You can also email us at aws-amplify-customer@amazon.com.

**Comment by 50k-Adam** [comment]
Hi, thanks for the reply!

[Distribution: *******7LVHC27 in AWS Account: ******222334]

I've already sent an email over last week with no response, I'll follow up again, thanks!

**Comment by hloriana** [comment]
Hi Adam, I'll go through the emails again and see if we accidentally missed it. We'll take a look to see what's connected to the CNAME and figure out next steps to remove this roadblock. Thank you for your patience!

**Comment by i3ima** [comment]
I have the same problem. Just sent you email with all information.

**Comment by hloriana** [comment]
@50k-Adam Since the distribution is in an unfamiliar account, I think you should open an AWS Support ticket so that you can receive assistance. The support team will be able to help you with next steps for finding the account your CNAMEs are being used in.

**Comment by 50k-Adam** [comment]
If anyone runs into the same issue, this is the resolution that AWS came back with.

Briefly explaining the steps to follow:
--------------------------------------------
1) Please create a dummy CF Distribution in your account(####) and wait till the distribution gets deployed. It may take 5-10 minutes to deploy the distribution. 
Please ensure this dummy CF distribution is attached with a valid certificate for the domain(sumterseniorliving.com). 

2) Once the CF distribution gets deployed,  Please follow the below article to move the domain(sumterseniorliving.com) from the other account to your AWS account.
https://aws.amazon.com/de/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/   -----> under the section "Use the ListConflictingAliases API to move your CNAME"

3) Once the domain name is migrated to your account, you would have control over it. And hence, you can now delete the  dummy CF distribution to release the domain and start using the domain(sumterseniorliving.com) for your amplify app.

**Comment by ganipcanot** [comment]
Closing due to workaround posted above.
