### ISSUE TITLE
Deleting back-end environment just deleted all our S3 data?!

### ISSUE THREAD

**Issue by jamescrowley** [aws-amplify/amplify-console#2384]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3dw5sp1sablwh

### Region

eu-west-1

### Amplify Console feature

Backend builds

### Describe the bug

Deleting our back-end deleted the storage S3 bucket (along with all its contents), despite the fact the cloudformation retention policy was set to retain. 

			"DeletionPolicy" : "Retain",

 (I double checked before triggering the delete from amplify). 

We tested deleting the dev environment, but due to https://github.com/aws-amplify/amplify-console/issues/2369 we had to delete manually from cloud formation, which worked as expected and retained the S3 bucket and it's data.

When deleting the production environment, the CloudFormation log clearly shows it being retained as expected

<img width="711" alt="Screenshot 2021-11-16 at 16 48 03" src="https://user-images.githubusercontent.com/509533/141935255-68dd93b6-ecd9-42e8-b99f-db80927e7763.png">

and yet somehow subsequently Amplify deletes it later in the process when deleting from the console?

### Expected behavior

You should not delete data in S3 storage buckets without warning! What am I missing here? This seems a completely insane default behaviour without some kind of UI warning or confirmation or option.

### Reproduction steps

1. Create back-end environment configured with storage
2. Store data in storage
3. Delete back-end environment

**Comment by hloriana** [comment]
Hi @jamescrowley 👋🏽  thank you for raising this issue. We are treating this as a priority and are currently investigating this behavior. We will provide an update as soon as possible.

**Comment by hloriana** [comment]
@jamescrowley This is default behavior when deleting backend environments. Buckets are generated with the `"DeletionPolicy" : "Retain"` policy so that they aren't deleted when running CLI commands like `amplify remove`. However, deleting your backend will remove all resources associated with that project.
