### ISSUE TITLE
An error occurred during the publish operation: request to <long amplify url> failed, reason: socket hang up

### ISSUE THREAD

**Issue by YazidHamdi** [aws-amplify/amplify-console#2398]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

duujlwv5zlxdt

### Region

us-east-2

### Amplify Console feature

Manual deploys

### Describe the bug

Next js application that used to build and publish with no issues.
No changes to the frontend code.
Suddenly, this starts happening (ca. 5:30PM CET, 11.21.2021):

Upon "amplify publish", the console passes until "✔ Zipping artifacts completed." and the next line shows:

```
✖ Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
An error occurred during the publish operation: request to https://aws-amplify-prod-us-east-2-artifacts.s3.us-east-2.amazonaws.com/<appid>/<envname>/<some_number>/DEPLOY/artifacts.zip?X-Amz-Security-Token=<token>&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=<date>&X-Amz-SignedHeaders=host&X-Amz-Expires=10800&X-Amz-Credential=<credential>&X-Amz-Signature=<signature> failed, reason: socket hang up
```

### Expected behavior

I expect publish to be successful especially that the app build succeeded.

### Reproduction steps

1. "amplify publish"

**Comment by hloriana** [comment]
Hi @YazidHamdi 👋🏽, apologies for the delay but are you still running into this issue?

**Comment by victorccccc** [comment]
Feel free to re-open this if issue persists. Thanks
