### ISSUE TITLE
Pattern-based branch deployments, behaviour on branch deletion

### ISSUE THREAD

**Issue by nikovirtala** [aws-amplify/amplify-console#24]
**Is your feature request related to a problem? Please describe.**
Pattern-based branch deployments allows ephemeral deployments but the deployments remain there until they're manually removed, despite the source branches are deleted from VCS.

**Describe the solution you'd like**
I'd like to have an option to delete deployments automatically, if and when the source branch is deleted from VCS.

**Comment by hotgazpacho** [comment]
For GitHub repositories, there's a `DeleteEvent` that gets fired whenever a branch is deleted: https://developer.github.com/v3/activity/events/types/#deleteevent

Perhaps this could be leveraged to provide this functionality?

**Comment by acq688** [comment]
This is something that we're looking for as well. Right now I'm using Amplify Console to spin up "test sites" on a per-pull request basis, but I'm having to clean up those manually at the moment after the pr gets closed or merged.

I think I might try to accomplish this with a Github Action triggered by the Pull Request being closed/merged for the time being.

**Comment by adamJLev** [comment]
Please for the love of god add this. AWS amplify needs a lot of work to be a viable alternative to netlify or zeit or any of the others.

**Comment by mikedizon** [comment]
I don't even have the option to enable creating a new backend for new branches. Is there a configuration that I'm missing to enable that option?

**Comment by jimvermillion** [comment]
> This is something that we're looking for as well. Right now I'm using Amplify Console to spin up "test sites" on a per-pull request basis, but I'm having to clean up those manually at the moment after the pr gets closed or merged.
> 
> I think I might try to accomplish this with a Github Action triggered by the Pull Request being closed/merged for the time being.

I was wondering if you were successful with the Github Action approach. If so, how did you actually disconnect the AWS Amplify branch? I can't find a webhook/way to disconnect one.

**Comment by swaminator** [comment]
@nikovirtala @jimvermillion @mikedizon @adamJLev @hotgazpacho @acq688 this feature is now supported: this feature is now supported: https://aws.amazon.com/blogs/mobile/automatically-create-and-delete-custom-sub-domains-for-your-branch-deployments-with-amplify-console/

**Comment by lorengordon** [comment]
@swaminator The backend deletion appears to only work for preview builds, e.g. the prNN backend. When the feature is enabled to autocreate environments for feature branches, and to autocreate the backend for each feature branch, i.e. [this feature](https://docs.aws.amazon.com/amplify/latest/userguide/pattern-based-feature-branch-deployments.html), in that case the backend is *not* deleted when the feature branch is deleted.

I wonder if this issue was closed prematurely? It appears to be speaking to the feature branch option, not the preview option...

**Comment by riywo** [comment]
@swaminator This has never worked for me. I use CodeCommit and tried `feature1` or `pr-1` branches but both didn't clean up backend environments.
