### ISSUE TITLE
Amplify import auth (existing cognito user Pool) - issue building app backend

### ISSUE THREAD

**Issue by julienlaurent-migso** [aws-amplify/amplify-console#2403]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-central-1:304701460251:apps/d1xcnvy7afof72

### Region

eu-central-1

### Amplify Console feature

Backend builds, Build settings, Environment variables

### Describe the bug

We deployed our application with amplify, and it works well with a new cognito user pool.
We need to use an existing cognito user pool. 
We used the command "amplify import auth" and configured it

When we deploy it, the backend fails with this issue :

There was an error initializing your environment.
2021-11-23T14:52:05.443Z [INFO]: [31mFailed to pull the backend.[39m
2021-11-23T14:52:05.445Z [INFO]: [31mThe "path" argument must be of type string. Received undefined[39m
2021-11-23T14:52:05.445Z [INFO]: [0mTypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined[0m
                                 [0m    at validateString (internal/validators.js:120:11)[0m
                                 [0m    at Object.join (path.js:1039:7)[0m
                                 [0m    at PathManager.constructPath (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/pathManager.ts:253:34)[0m
                                 [0m    at PathManager.getResourceDirectoryPath (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/pathManager.ts:142:10)[0m
                                 [0m    at PathManager.getResourceParametersFilePath (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/pathManager.ts:149:34)[0m
                                 [0m    at StateManager.setResourceParametersJson (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:284:34)[0m
                                 [0m    at updateStateFiles (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:728:16)[0m
                                 [0m    at Object.headlessImport (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1277:26)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at importedAuthEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:946:12)[0m
                                 [0m    at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/index.js:52:72)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/index.js:349:22[0m

### Expected behavior

We need to use all amplify features using an existing cognito user pool.

### Reproduction steps

1) Amplify import auth (configure the existing cognito user pool + identity pool
2) Amplify push
3) deploy app

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

See or package.json :
  "dependencies": {
    "@aws-amplify/analytics": "^3.3.11",
    "@aws-amplify/api": "^3.3.3",
    "@aws-amplify/api-graphql": "^2.2.15",
    "@aws-amplify/api-rest": "^2.0.26",
    "@aws-amplify/auth": "^3.4.34",
    "@aws-amplify/cache": "^4.0.28",
    "@aws-amplify/core": "^3.8.24",
    "@aws-amplify/datastore": "^3.7.0",
    "@aws-amplify/geo": "^1.1.8",
    "@aws-amplify/interactions": "^3.3.34",
    "@aws-amplify/predictions": "^4.0.26",
    "@aws-amplify/pubsub": "^4.2.2",
    "@aws-amplify/storage": "^3.4.4",
    "@aws-amplify/ui": "^2.0.3",
    "@aws-amplify/xr": "^2.2.34",
    "@testing-library/jest-dom": "^5.11.10",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^12.8.3",
    "aws-amplify": "^4.3.2",
    "aws-amplify-react": "^5.0.4",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.1.1"
  },

**Comment by hloriana** [comment]
Hi @julienlaurent-migso 👋🏽 can you verify the file path for the `parameters.json` file created when you imported auth? It should be `amplify/backend/auth/appXXXXXX/parameters.json`.

**Comment by julienlaurent-migso** [comment]
Hello hloriana, thank you for your answer.
The file path of my parameters.json is : amplify/backend/auth/appXXXXXX/build/parameters.json
the file is included inside **build** folder. 
his content is : 
{
  "authSelections": "identityPoolAndUserPool",
  "resourceName": "appXXXXX",
  "serviceType": "imported",
  "region": "eu-central-1",
  "requiredAttributes": [
    "email"
  ],
  "passwordPolicyMinLength": 8,
  "passwordPolicyCharacters": [],
  "mfaConfiguration": "OFF",
  "autoVerifiedAttributes": [
    "email"
  ],
  "mfaTypes": []
}

how can i fix the issue with these information ? thank you for your help

**Comment by hloriana** [comment]
@julienlaurent-migso awesome! I'll close this issue. If you have any other questions feel free to open a new issue. Thanks!
