### ISSUE TITLE
301 redirects does not work.

### ISSUE THREAD

**Issue by perdomofranklindev** [aws-amplify/amplify-console#2405]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2pqqvwqi6cf5p

### Region

N. Virginia

### Amplify Console feature

Redirects

### Describe the bug

Do not redirect to the target configuration

![Screenshot from 2021-11-23 12-36-37](https://user-images.githubusercontent.com/92344582/143073310-6c3decf6-a6b1-4649-b7bc-d0369c3a0527.png)

### Expected behavior

Redirect correctly

source: [https://www.cobuildlab.com/blog/methods-to-raise-funds-for-your-startup](https://www.cobuildlab.com/blog/methods-to-raise-funds-for-your-startup)
target: [https://www.navigate.capital/post/10-methods-to-raise-funds-for-your-business-idea-or-startup](https://www.navigate.capital/post/10-methods-to-raise-funds-for-your-business-idea-or-startup)

### Reproduction steps

I just configured in the Rewrite and Redirects options on Amplify Console.

### Build Settings

```yaml
Is not applicable
```

### Additional information

All the configuration was done from the console. And only the options it offers for redictions

App -> AWS Amplify Console -> Rewrites and redirects -> Add rule.

**Comment by hloriana** [comment]
Hi @perdomofranklindev 👋🏽 it seems like your redirect is working now. If you're still running into this issue please feel free to re-open.

**Comment by tyirvine** [comment]
For anyone stumbling across this thread in the future, be aware of the rule's position. For example, if you want to redirect `https://www.example.com -> https://example.com` that rule would have to be placed first.

I discovered this in this thread → https://repost.aws/questions/QUB5Y06NtjSFqCpz7LAb256w/amplify-redirect-www-to-apex
