### ISSUE TITLE
SSL verification is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by MoneyMan** [aws-amplify/amplify-console#241]
**App Id**: d1vmj5meg81w5g
**Region**: us-east-1
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
It has taken more than 8 hours to conduct SSL Verification on my account.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by nimacks** [comment]
@MoneyMan, sorry to hear that you're having issues getting your custom domain setup. My recommendation for you would be to remove and re-attach the custom domain since it has been more than 8hours. Let us know if this does not resolve your issue.

**Comment by MoneyMan** [comment]
@nimacks Thanks, it's all fixed now!
