### ISSUE TITLE
Amplify "List apps call failed Network Failure"

### ISSUE THREAD

**Issue by 24jr** [aws-amplify/amplify-console#2417]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify Console feature

Access control

### Describe the bug

My boss created an aws account and gave me admin permissions and yet aws amplify showing my this error "List apps call failed Network Failure" and seems to be unusable contrary to my personal account which works fine 

### Expected behavior

works as expected and can create a backend and look at amplify admin ui

### Reproduction steps

make new aws account and add a user which has proper permissions (I didnt do this part)

login and go to amplify page and it shows error

I have a personal account on same device not sure if affects anything
![Screen Shot 2021-11-29 at 9 46 53 AM](https://user-images.githubusercontent.com/34662182/143890793-4650db77-00a6-431d-ae33-cf68888d558b.png)
g

**Comment by hloriana** [comment]
Hi @24jr 👋🏽,  can you contact your administrator and make sure the proper permissions were added? Here is an AWS-managed policy that provides admin access to AWS Amplify resources: https://docs.aws.amazon.com/amplify/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-AdministratorAccess-Amplify

**Comment by 24jr** [comment]
@hloriana I was given admin access I was told. First tried just amplify access then eventually full admin and still same

**Comment by hloriana** [comment]
@24jr If your administrator created a user for you in the right account and attached the AWS-managed `AdministratorAccess` policy to the user, then you should have access 🤔. Are you able to access other resources in the console (ex. Amazon S3)?  

Also, can you please share the policy your administrator attached to the user you sign in as?

**Comment by 24jr** [comment]
<img width="324" alt="Screen Shot 2021-12-01 at 11 01 46 AM" src="https://user-images.githubusercontent.com/34662182/144268872-eadaa7a3-e918-45a4-8cac-c0fbd17e4ddb.png">
I was sent that this was given to my account

**Comment by hloriana** [comment]
@24jr Please make sure your administrator followed these instructions to create a user and assign permissions: [Creating IAM users (console)](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html#id_users_create_console)

Then you can follow these instructions to sign in and view the Amplify projects: [How IAM users sign in to AWS](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_sign-in.html)

**Comment by jwhyte88** [comment]
Hi @hloriana , 

Thanks for looking into this. 
I currently have the same issue, but at least in my case, it doesn't appear to be caused by permissions. 

Using the same account, I'm able to access the Amplify console from certain devices*, and on others, I see the same "**List apps call failed**" error message. 

<img width="796" alt="aws" src="https://user-images.githubusercontent.com/5682015/144694135-05e77bbd-8c13-4928-afe8-9013c825d150.png">

*All devices I've used have been Macbooks, and they're all on the same network.

**Comment by apcexchange** [comment]
i am having same issues after creating an account, what do i do?

**Comment by hloriana** [comment]
> i am having same issues after creating an account, what do i do?

Hi @apcexchange 👋🏽, did you follow these instructions to create a user with the proper permissions: [Creating IAM users (console)](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html#id_users_create_console)? And did you follow these instructions to sign in with that user [How IAM users sign in to AWS](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_sign-in.html)?

**Comment by 24jr** [comment]
@hloriana I'm pretty sure we have both given those permissions and the issue is less obvious. I never solved the issue and gave up asking my boss to verify the same thing over and over again

**Comment by hloriana** [comment]
Hi @24jr thank you for being thorough in helping us to troubleshoot. I've escalated this to the team to further investigate what else can be throwing this error. Thank you for your patience!

**Comment by victorccccc** [comment]
Hi @24jr , can you share your accountId (or send it to aws-amplify-customer@amazon.com)? Is there any Organization  policy which your account is inheriting? Thanks.

**Comment by 24jr** [comment]
4756-9797-1287 and us-east-2 ohio @victorccccc

**Comment by victorccccc** [comment]
Thanks for your information @24jr, I cannot find any ListApps request from our end. Can you share the HAR file?

**Comment by 24jr** [comment]
@victorccccc what is the HAR file? 
<img width="1443" alt="Screen Shot 2021-12-10 at 3 54 03 PM" src="https://user-images.githubusercontent.com/34662182/145640072-0b05cf6a-c85e-4cc7-8e5e-2bbf141d74a0.png">

**Comment by victorccccc** [comment]
If you go to Network tab in Developer console and you can click download to get the HAR file, we want to take a look at the ListApp request from your browser. You can send it to aws-amplify-customer@amazon.com .Thanks 

<img width="828" alt="Screen Shot 2021-12-10 at 1 10 27 PM" src="https://user-images.githubusercontent.com/17761274/145641817-cdc47c51-34f8-4f85-ae15-c877a42cd166.png">


<img width="1041" alt="Screen Shot 2021-12-10 at 1 07 10 PM" src="https://user-images.githubusercontent.com/17761274/145641691-0df865c0-8783-41e2-ab1c-5a75b8a14628.png">

**Comment by 24jr** [comment]
@victorccccc sent it thanks

**Comment by 24jr** [comment]
<img width="829" alt="Screen Shot 2021-12-10 at 5 11 10 PM" src="https://user-images.githubusercontent.com/34662182/145647912-166a035f-432d-4bee-a475-3d3f1f772db7.png">
@victorccccc nevermind

**Comment by hloriana** [comment]
Hi @24jr sorry for the delay but it looks like your user does not have multi-factor authentication setup and there is an explicit deny policy attached to your user that will deny all actions without enabling MFA. 

Explicit deny policies are honored over allow policies as part of security best practices, this is why you're not able to perform any actions even though you have the AdministratorAccess policy attached. 

Once you've setup MFA for your user, you should be unblocked.

**Comment by 24jr** [comment]
@hloriana Interesting. We tried to add mfa to my account and wasnt working so we said forget it
<img width="778" alt="Screen Shot 2021-12-17 at 2 11 09 AM" src="https://user-images.githubusercontent.com/34662182/146504342-4559978e-47ab-4f6f-bbb6-10b19ee925f7.png">

**Comment by 24jr** [comment]
@hloriana I had to have my boss. send me the qr code and I sent him my mfa code and he set it up through his account for my account. Odd but works now

**Comment by SkaarFacee** [comment]
I have this same issue, however even with MFA there seems to be no progress

**Comment by rwslippey** [comment]
I just found this issue after having the same problem. Wanted to add to this. I'm having this problem only on Linux, specifically Firefox and Brave on Manjaro. Switching over to my Windows box, Console loads fine and everything works. I've messed with Firefox's security and privacy policies a bit to no avail.

**Comment by 24jr** [comment]
@rwslippey Oh I'm using Brave. Didn't think to try else

**Comment by SkaarFacee** [comment]
@rwslippey Oh, I had the same issue. The only difference was that the error stuck on windows for me. The moment I switched to Linux (Pop_OS) it started working fine. A few hours later when I tried opening Amplify on windows it began working fine. I would suggest try waiting it out for some time  as that did it for me. I tried everything else that was mentioned on this thread to get it working on Windows.

**Comment by douglas1850** [comment]
I'm getting this same error on the root user account - admin access to everything, and MFA is set up.

**Comment by cobaltplay** [comment]
hey all. just sharing. I had the same problem as above. Looks like the problem was because I had manually set my Mac system time to the wrong zone. Ie. I'm in South America (-3 GMT), and I wanted my mac clock to show UK time (GMT-0) because I'm working based on a UK timezone. Looks like AWS didn't like this. Setting my clock back to the correct timezone (GMT-3) based on my physical location seemed to have worked.

**Comment by hloriana** [comment]
> 

@douglas1850 do you have an AppID or region we can use to investigate? We can also investigate using your account ID. If you'd like to provide this information privately you can email aws-amplify-customer@amazon.com

**Comment by hexdecimal16** [comment]
for me the problem was solved by correcting my system date and time

**Comment by VusalHamidov** [comment]
I solved by correcting my system date and time

**Comment by keith284487** [comment]
Had the same issue. Worked only after I resync time on windows. It was 5 minutes ahead.

**Comment by kolpaja** [comment]
I had the same issue, and i even tried to log in as the Admin user, but it was all about the datetime of the system, because I changed one day before, so now I set up accordingly automatic date and time for my laptop and it works fine. thanks guys
