### ISSUE TITLE
Is there a domain limit per app?

### ISSUE THREAD

**Issue by erikvanbeijnen** [aws-amplify/amplify-console#2425]
We are investigationg some AWS functionalities for handling traffic for about 300+ domain names and came accross Amplify.
I read some questions if domain limits could being increased, but I cannot find anything about any domain limits in the documentation.
So my question is: is there a domain limit for an Amplify App? If so, what is the limit?

**Comment by hloriana** [comment]
Hi @erikvanbeijnen 👋🏽 Yes, there is a limit. You can have up to 5 domains per Amplify application. Here is documentation for [Amplify service quotas](https://docs.aws.amazon.com/general/latest/gr/amplify.html#service-quotas-amplify).
