### ISSUE TITLE
Page can’t be found in all my *.amplifyapp.com pages

### ISSUE THREAD

**Issue by jhlusko** [aws-amplify/amplify-console#2433]
Still having this issue for https://master.d3bce1v0sadz4r.amplifyapp.com/

_Originally posted by @jhlusko in https://github.com/aws-amplify/amplify-console/issues/664#issuecomment-987012753_

**Comment by jhlusko** [comment]
App ID: d3bce1v0sadz4r
Region: us-east-2

**Comment by hloriana** [comment]
Hi @jhlusko 👋🏽, I'm able to see your website. Can you please provide a screenshot of what you're seeing?

**Comment by jhlusko** [comment]
I see a blank screen when I access it from the united states, but it loads properly from Toronto. From the console, I can see the error "Cannot read properties of react-dom.production.min.js:209  undefined (reading 'api')". Any idea why it would load differently in the two locations?
