### ISSUE TITLE
Access a second GitHub organization?

### ISSUE THREAD

**Issue by dhait** [aws-amplify/amplify-console#2437]
When I go to the AWS Amplify Console, it only shows repositories from one GitHub organization.  I want to authenticate to a second organization for which I am an administrator.  How can I do this?

**Comment by dhait** [comment]
Bot, stand aside and let a human handle this.

**Comment by hloriana** [comment]
Hi @dhait 👋🏽  thanks for raising this question. I'm looking into this now and will post an update/instructions on how to do this in just a moment.

**Comment by hloriana** [comment]
@dhait To authenticate into to another GitHub organization follow these steps:
1. In GitHub, navigate to Settings -> Applications -> Authorized OAuth Apps.
2. Find the AWS Amplify (<region>) application and revoke permissions.
3. In the Amplify console, select New app -> host web app.
4. Select GitHub. You will be prompted to authorize Amplify to access your GitHub account.

You should see both organizations listed. Make sure to grant access for both organizations. 

If you are not the owner of the organization, then make sure you select the option to request access from the owner. Once they grant permissions, you'll be able to see those repositories listed as options when you create an Amplify app. 

Please let me know if you need further assistance. Thank you for reaching out!

**Comment by dhait** [comment]
Thank you!
