### ISSUE TITLE
Amplify CI/CD Branch Changes are not Detected

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [aws-amplify/amplify-console#2438]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-1

### Amplify Console feature

Not applicable

### Describe the bug

Any PRs or direct merges into my connected branches are not detected. 

This happened in the past (could be the same issue): https://github.com/aws-amplify/amplify-console/issues/1154

### Expected behavior

Deployment is kicked off

### Reproduction steps

Merge changes to any connected branch

**Comment by Narrator** [comment]
@Jordan-Eckowitz Could you please share your app id so we can look into it further?

**Comment by Jordan-Eckowitz** [comment]
> @Jordan-Eckowitz Could you please share your app id so we can look into it further?

@Narrator here you go: `d3ryd18bpdre9s`

**Comment by Narrator** [comment]
@Jordan-Eckowitz I looked into your app and it seems like webhooks are triggering builds. I can also see that you have 15 branches connected. Could you please specify which branch you've been having issues with?

**Comment by entest-hai** [comment]
I got the same issue, here is my app id: d2bdgfrxcjfn9h. Amplify CI/CD does not detect changes in two branches deploy-admin, and deploy-user. Please check

**Comment by hloriana** [comment]
> I got the same issue, here is my app id: d2bdgfrxcjfn9h, region: ap-southeast-1. Amplify CI/CD does not detect changes in two branches deploy-admin, and deploy-user. Please check.
> 
> I think it happens because I change my username in GitHub, then Amplify is not able to detect branches ...

Hi @entest-hai, if you changed your username then you'll need to reconnect the repository because Amplify will still be looking for changes to your repository with the former GitHub url.

**Comment by hloriana** [comment]
If you are still having this issue, feel free to re-open. Thanks!
