### ISSUE TITLE
How do I send parameters to the Cloud Formation Templates from Amplify Console

### ISSUE THREAD

**Issue by jon144** [aws-amplify/amplify-console#244]
** Please describe which feature you have a question about? **
Amplify Console / Cloud Formation Templates

** Provide additional details**
How do I pass custom parameters to the Cloud Formation Templates from the Amplify Console?

I want to pass a custom parameter to the Cloud Formation Templates so the execution policies can be generated correctly.  Here is an example of the custom parameter that I have added to the cloud formation template "appId".  Currently, I have a default value but I would like to pass this in from the Amplify Console.  Somehow 'env' is being passed in, I want to add 'appId'.

![image](https://user-images.githubusercontent.com/11067697/68904494-b0c1ab00-0703-11ea-8f94-0ced57f1cb7d.png)

This is what I see under Amplify Console / Build Settings.  Can I add parameters on the end?  If so, what is the syntax?
![image](https://user-images.githubusercontent.com/11067697/68904715-2ded2000-0704-11ea-9f2b-5da52b8dbf1a.png)

**Comment by Joycehao19** [comment]
We are aware of this issue. Currently there isn't a way to pass custom parameters to the amplifyPush.sh script. If you would like to manage your own version you can check out https://github.com/aws-amplify/amplify-console/issues/206#issuecomment-552548466 as a temp workaround

**Comment by swaminator** [comment]
Closing issue as it can be done manually using headless scripts: https://docs.amplify.aws/cli/usage/headless

**Comment by leontp587** [comment]
@swaminator , can you please explain how to use headless scripts to send parameters to CloudFormation templates via amplify console? The link you provided doesn't explain this.

**Comment by sc0ttdav3y** [comment]
@leontp587 Did you ever get this working? If so, can you explain how?
