### ISSUE TITLE
Can't pass step 1 - Add a git repository -- "There was an error detecting your build settings"

### ISSUE THREAD

**Issue by cgallivanpam** [aws-amplify/amplify-console#2443]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

I can't even pass step 1 to add a git repository. I get this error:

<img width="1218" alt="Screen Shot 2021-12-09 at 5 05 03 PM" src="https://user-images.githubusercontent.com/89227903/145499793-7a7f6ba3-d7a7-4e7b-a550-49baef2e406e.png">

### Expected behavior

Expected behavior is to give the user more information on where to identify and find the bug.

### Reproduction steps

1. connect repository to amazon amplify
2. Add repository.

### Build Settings

```yaml
do not currently have an amplify.yml file.
```

**Comment by hloriana** [comment]
Hi @cgallivanpam 👋🏽 thank you for raising this issue. Are you able to build your app locally?

**Comment by cgallivanpam** [comment]
Hello! Yes I am able to!

Thanks,
CG

**Comment by hloriana** [comment]
@cgallivanpam Does this error pop up after you've selected the repository and branch and then clicked the **Next** button? What kind of app are you trying to host?

**Comment by cgallivanpam** [comment]
Yes it happens after that. It goes into the next page and fails on step 1 with that error.

I am trying to host a standard front end website.

Thanks,
CG

**Comment by cgallivanpam** [comment]
We just got it figured it out. It was trailing commas in json files.

Thank you for your help!!

Best,
CG

**Comment by aaronksaunders** [comment]
i am running into this error, what JSON file where there errors in?

**Comment by ASDjonok** [comment]
Also had such issue. Solved it by avoiding special symbol ('&') in branch name.

**Comment by ASDjonok** [comment]
Also had such issue but without details of syntax error in JSON. Solved it by avoiding special symbol ('&') in branch name. Maybe it will help somebody because it is first page of Google search results with query "There was an error detecting your build settings."
