### ISSUE TITLE
 Rewrites and Redirects tab menus

### ISSUE THREAD

**Issue by togenius1** [aws-amplify/amplify-console#2451]
I dont see any Rewrites and Redirects tab menus. Please help?

**Comment by hloriana** [comment]
Hi @togenius1 👋🏽, If you've created an Amplify application, login to the Amplify console and navigate to one of your applications. You should see a dropdown menu on the left side of the screen under **App setting**. You should then see **Rewrites and redirects** listed towards the bottom.
