### ISSUE TITLE
Amplify console must list all the domain associated with the application

### ISSUE THREAD

**Issue by asumvp** [aws-amplify/amplify-console#2455]
**Is your feature request related to a problem? Please describe.**

I have more than 10 domains configured with my amplify application. However, currently Amplify console lists only 10 domains. Others are not visible in the console. 

** Known workaround**

Use the Amplify CLI commands to modify/delete the domains that are not visible.

**Describe the solution you'd like**

1. Amplify console should show all the domains associated with the Amplify application.
2. If possible, the recently added domain should appear first i.e at the top.

**Additional context**

NA

**Comment by ganipcanot** [comment]
I currently have a fix for this locally - needs to go through code review and deployment though.  Will update here once it's deployed to all regions.

**Comment by ganipcanot** [comment]
This has been deployed to all waves.  Please re-open if you are still having issues.
