### ISSUE TITLE
Can not delete Amplify backend after delete their bucket in s3

### ISSUE THREAD

**Issue by duyetphamm** [aws-amplify/amplify-console#2456]
After creating amplify backend. I have found out some buckets in my aws s3.
I'm new on AWS so, I do not know about the relationship between my amplify backend and buckets in s3.
I have tried to delete those buckets then amplify backend could not detect environment anymore.
Finally, I have tried to delete the backend also the amplify app but nothing work.

In console,
After I delete app, I got this message "Invoking remove all backends execution failed"
After deleting bankend, I got this message "Deleting backend env: undefined from app: d2dpdzrg81wf52 failed"

" No Amplify backend project files detected within this folder. Either initialize a new Amplify project or pull an existing project.
      - "amplify init" to initialize a new Amplify project
      - "amplify pull <app-id>" to pull your existing Amplify project. Find the <app-id> in the AWS Console or Amplify Admin UI."
I also get this message, while deleting app using cli

Please help/guide me to delete amplify app!
region=ap-southeast-1
appId= d2dpdzrg81wf52

**Comment by hloriana** [comment]
Hi @duyetphamm 👋🏽 thanks for raising this! Try running this command to completely remove your backend: `aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>`.

**Comment by duyetphamm** [comment]
I can delete it now. thank you @hloriana

**Comment by chrisl777** [comment]
Note that I had to add the `--profile` argument, as in: `aws amplify delete-backend-environment --app-id <APP_ID> --environment-name <ENV_NAME> --profile <PROFILE_NAME>`
