### ISSUE TITLE
Published my first Gitlab project to AWS Amplify. The pipeline is successful but not able to launch the application

### ISSUE THREAD

**Issue by hibannu** [aws-amplify/amplify-console#246]
**Describe the bug**
Published my gitlab project to AWS Amplify. It's called sample-calc-app and got published to Amplify successfully. The pipeline is successful but still not able to access it.

**To Reproduce**
1. Go to 'AWS Amplify console'
2. Click on app 'sample-calc-app'
3. Access the end point on amplify site: https://master.d2jymt0a0odnwr.amplifyapp.com/
4. It redirected to https://master.d2jymt0a0odnwr.amplifyapp.com/index.html but not launching the actual application.

**Expected behavior**
The gitlab project works fine in local and should launch a calculator application.

**Additional context**

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by swaminator** [comment]
Check your outpue folder in your [build settings](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#setting-the-output-folder)  (under `App settings > build settings`) to ensure the your files are correctly being uploaded.  By default Amplify Console sets up a redirect `App settings > Rewrites and redirects` for any path that doesn't resolve to redirect to `index.html`. However, if your `index.html` isn't detected then you're stuck with infinite redirects
