### ISSUE TITLE
Deploy multiple front ends to interact with one backend amplify studio

### ISSUE THREAD

**Issue by 24jr** [aws-amplify/amplify-console#2461]
I have an amplify studio backend and added one front end. I want to add another front end but am not able to it seems. It should be fine to so I must be missing something https://docs.aws.amazon.com/amplify/latest/userguide/reuse-backends.html
<img width="782" alt="Screen Shot 2021-12-18 at 3 20 19 PM" src="https://user-images.githubusercontent.com/34662182/146654589-2666ae80-71ad-4f81-827a-26689598ac61.png">
<img width="1027" alt="Screen Shot 2021-12-18 at 3 20 09 PM" src="https://user-images.githubusercontent.com/34662182/146654590-e5fe0e95-ce52-4a57-9acf-d35adbdffe82.png">
<img width="1056" alt="Screen Shot 2021-12-18 at 3 19 58 PM" src="https://user-images.githubusercontent.com/34662182/146654591-2ae13a8c-1951-46ea-910c-a46b16df1f87.png">
 

### Expected behavior

Select my branch like the first time and build it like other one and have two front ends. Eventually may want an app and a website or an admin website etc so multiple front ends is desired

### Reproduction steps

Make backend
Add Front-end
Add Front-end again

**Comment by swaminator** [comment]
You only have a single branch in your repo which is why you're not seeing anything in the dropdown.

**Comment by 24jr** [comment]
@swaminator but I dont want to use another branch i want to use a different repo. Admin repo. User Repo. Different interface for front end repo. stuff like that

**Comment by swaminator** [comment]
@24jr you need to connect a new repo, and then when you connect the branch you should be able to connect it to a backend from a different app.

**Comment by nimacks** [comment]
@24jr Let us know if the steps mentioned above does not resolve your issue. Feel free to re-open.
