### ISSUE TITLE
Custom Domain Activation Fails

### ISSUE THREAD

**Issue by jferrell5** [aws-amplify/amplify-console#2470]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d4orsqqyxbpq1

### Region

us-east-1

### Step

Domain Activation

### Status

Failed

### Issue or question

When I attempt to add a custom domain from GoDaddy I get a domain activation failure. I have followed all of the relevant AWS Amplify documentation and error message information provided in the Amplify console.

Working amplify url: https://main.d4orsqqyxbpq1.amplifyapp.com/

GoDaddy DNS Configuration

![GoDaddyDNS2](https://user-images.githubusercontent.com/3710376/146980972-12c31080-1f23-4a66-8ff5-7de27c8c96b2.png)

![GoDaddyForwarding](https://user-images.githubusercontent.com/3710376/146963438-9178f8a0-fe56-4c9e-8f23-a94d4547a643.PNG)

Amplify Console Results after attempted activation

![FlexspaceDomainMgmt](https://user-images.githubusercontent.com/3710376/146963333-2d8af91e-d4ff-4067-b998-efd01bace671.PNG)

![FlexspaceDomainMgmt2](https://user-images.githubusercontent.com/3710376/146963461-1710cc7f-6a53-4427-9239-d1eda7831665.PNG)

Cloudfront distribution provided in the Amplify console not resolving

![WhatsMyDNS](https://user-images.githubusercontent.com/3710376/146973925-6a03c4d2-130a-4899-8fb2-5427b8e8ca04.PNG)

### Error message

See screenshots above

**Comment by dersven98** [comment]
Hi, I have also a bit confusing Problem.

You can see on this Screenshot, that I have added all CAA on my domain:
![CleanShot 2021-12-23 at 13 07 58](https://user-images.githubusercontent.com/75265769/147238362-50b852f6-f041-448b-b0f9-b224923fde16.png)

Next I go to the AWS-Console, and start the Verfification Process.
And here I get the following Problem:
![CleanShot 2021-12-23 at 13 10 15](https://user-images.githubusercontent.com/75265769/147238645-eccefb23-318a-47e0-86d8-fc142c6264e0.png)

So what should i do now?

**Comment by jferrell5** [comment]
Finally figured this out. The Cloudfront url that the UI was directing my to use was actually incorrect whenever trying to activate the domain(see my 3rd screenshot. The correct Cloudfront url for my CNAME entry with GoDaddy was actually found at Domain managment>View DNS records.
