### ISSUE TITLE
Amplify backend resources out of sync when moving between branches.

### ISSUE THREAD

**Issue by suhas-007** [aws-amplify/amplify-console#248]
Amplify backend resources out of sync when moving between branches.

Two branches dev and test.
1.  A lambda function was created in the dev branch successfully 
2. It was moved to the test branch by the following commands
git checkout test
git pull origin test
amplify env checkout test
amplify env pull origin test 
git checkout proto amplify/
amplify status 
amplify push 
git status 
git push origin test

3. the lambda function is show in the local copy (under folder amplify--backend)

But the lambda function is not built in the test branch and neither getting reflected when we do the amplify status in test branch

the team-provider-info.json is also not in sync with the resources created in the dev branch.

Please guide.

**Comment by Joycehao19** [comment]
@suhas-007 Could you please provide your appid and region? Thanks

**Comment by Joycehao19** [comment]
@suhas-007 struggling to follow your workflow completely. How many backend environments do you have? How many branches are connected to Amplify Console? Why are you checking out to a new branch `git checkout proto amplify/`

**Comment by suhas-007** [comment]
I have 2 branches ( test and proto ).
I have 2 backend environments( one for test and one for proto).
proto --- development environment.
test---test environment.
--------------------------------------------------------
In proto environment I create a backend resource , for example lambda by using the command
amplify function add  and select the required options.

The lambda gets successfully created in the proto environment.

Now I checkout to the test environment  by using the following commands:
For git files:
git checkout test
git pull origin test

For amplify files:
amplify env checkout test
amplify env pull origin test

My question is how do I move my backend resources  from one environment to another ?So that after moving I can just do amplify push to build my backend resources.

Please guide.

**Comment by swaminator** [comment]
Here's the recommended workflow: https://docs.aws.amazon.com/amplify/latest/userguide/multi-environments.html#team-workflows-with-amplify-cli-backend-environments
