### ISSUE TITLE
amplify push - An error occurred when pushing on cloud

### ISSUE THREAD

**Issue by hiteshtSociosquares** [aws-amplify/amplify-console#2481]
**Describe the bug**
=> **amplify status**
then will try '**amplify push**'
that time we received "**An error occurred during the push operation: Stack:arn:aws:cloudformation** "

**To Reproduce**
- Change in to amplify backend
- Run amplify push

**Comment by hloriana** [comment]
Hi @hiteshtSociosquares 👋🏽, did the error message have any more information?

**Comment by hloriana** [comment]
Closing. If you need assistance please open a new issue and fill out the prompts so we can better assist you. Thanks!
