### ISSUE TITLE
Provision image is really used?

### ISSUE THREAD

**Issue by SteeveGL** [aws-amplify/amplify-console#2484]
**Please describe which feature you have a question about?**
Amplify Build

**Provide additional details**
Amplify Build indicate in Build that Provision docker file is used to build the project but I have a doubt about it. In the file we can see "Install AWS Amplify CLI for all node versions ..." but the npm patching happen in the build steps. The section "Install python3.8" install python3.8 but set the version with `ln -fs /usr/bin/python3.8 /usr/bin/python3` return nothing `python found but version  is less than the minimum required version`. I have to install it in the "amplify.yml". Even "amazonlinux:2" has python 3.8 installed.

Which image is really used to build the project?

**Comment by hloriana** [comment]
Hi @SteeveGL 👋🏽 thanks for raising this issue! The team is aware of this and has a resolution in progress. I will update once the fix has been rolled out. Thank you!
