### ISSUE TITLE
Ampify Build stuck when i create in new region

### ISSUE THREAD

**Issue by SantoshRaoMea** [aws-amplify/amplify-console#2489]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-west-1:324106371807:apps/d2775g2vwzhi4n

### Region

eu-west-1

### Amplify Console feature

Backend builds

### Describe the bug

I am trying to create an instance of amplify application in new region

When I connect to repo and branch, the build is stuck at backend phase
```
                                 # Starting phase: build
2022-01-06T10:54:53.871Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2022-01-06T10:54:54.130Z [INFO]: [0mAmplify AppID found: dvb6mzqluh031. Amplify App name is: meaplatform[0m
2022-01-06T10:54:54.225Z [INFO]: [0mAdding backend environment luelle to AWS Amplify app: dvb6mzqluh031[0m
2022-01-06T10:54:54.401Z [WARNING]: - Initializing project in the cloud...
2022-01-06T10:54:59.635Z [INFO]: 
2022-01-06T10:54:59.638Z [INFO]: CREATE_IN_PROGRESS amplify-meaplatformmeaplatfo-luelle-105453 AWS::CloudFormation::Stack Thu Jan 06 2022 10:54:54 GMT+0000 (Coordinated Universal Time) User Initiated
                                 CREATE_IN_PROGRESS DeploymentBucket                           AWS::S3::Bucket            Thu Jan 06 2022 10:54:58 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UnauthRole                                 AWS::IAM::Role             Thu Jan 06 2022 10:54:58 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS AuthRole                                   AWS::IAM::Role             Thu Jan 06 2022 10:54:58 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UnauthRole                                 AWS::IAM::Role             Thu Jan 06 2022 10:54:59 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2022-01-06T10:55:04.636Z [INFO]: 
2022-01-06T10:55:04.638Z [INFO]: CREATE_IN_PROGRESS DeploymentBucket AWS::S3::Bucket Thu Jan 06 2022 10:54:59 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_IN_PROGRESS AuthRole         AWS::IAM::Role  Thu Jan 06 2022 10:54:59 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2022-01-06T10:55:14.639Z [INFO]: 
2022-01-06T10:55:14.640Z [INFO]: CREATE_COMPLETE UnauthRole AWS::IAM::Role Thu Jan 06 2022 10:55:14 GMT+0000 (Coordinated Universal Time)
2022-01-06T10:55:19.654Z [INFO]: 
2022-01-06T10:55:19.656Z [INFO]: CREATE_COMPLETE AuthRole AWS::IAM::Role Thu Jan 06 2022 10:55:14 GMT+0000 (Coordinated Universal Time)
2022-01-06T10:55:24.636Z [INFO]: 
```

And ultimately times out, there is no error or anything to indicate what is going wrong

### Expected behavior

Build should succeed or error that needs to be fixed in build should be shown. Even if a permission issue, it should indicate what is getting missed.

### Reproduction steps

1. Rebuild the app for above ARN
2. Build will get stuck in backend build phase

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by SantoshRaoMea** [comment]
I created a new app meaplatformie in eu-west1 and ran into same issue of deployment getting stuck
App ARN
arn:aws:amplify:eu-west-1:324106371807:apps/dmyim1snahlt7

**Comment by hloriana** [comment]
Hi @SantoshRaoMea thanks for raising this issue. It's stalling because behind the scenes you're being prompted to select an AWS region. I'm brining this up to the team for further investigation.

**Comment by victorccccc** [comment]
Hi, can you try to check your `.gitignore` file to ensure all these files are ignored? Thanks! 
 https://docs.amplify.aws/cli/reference/files/#gitignore

**Comment by SantoshRaoMea** [comment]
@hloriana , just to aid the investigation, I am using an Aurora data source on a cluster, and there is only one cluster and 1 database in the region of eu-west-1 account

**Comment by SantoshRaoMea** [comment]
I tried recreating app again, just to check with latest CLI (Sorry that I recreated, wanted to keep the region clean). Issue still persists, app details bellow

App name
meaplatform
App ARN
arn:aws:amplify:eu-west-1:324106371807:apps/dtesxd31tv0np

**Comment by SantoshRaoMea** [comment]
@hloriana would there be any workaround for the moment, to get past the prompts by supplying the region in some way

**Comment by SantoshRaoMea** [comment]
Hi VIctor,

All these files are ignored.

my .gitignore for reference as well. Also i double checked the repo doesnt have any of these files as well.

# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# production
/build

# misc
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*
*.xlsx

.secret-*
**.sample

#amplify-do-not-edit-begin
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/logs
amplify/mock-data
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
amplify/backend/.temp
build/
dist/
node_modules/
aws-exports.js
awsconfiguration.json
amplifyconfiguration.json
amplifyconfiguration.dart
amplify-build-config.json
amplify-gradle-config.json
amplifytools.xcconfig
#amplify-do-not-edit-end


Regards
Santosh

________________________________

**Comment by SantoshRaoMea** [comment]
I could get this working, steps i followed *though a work around"

1. Created a New App in the new region
2. Connected to Github
3. Let the Backend build hang and timeout
4. Pulled the code locally along with new env
5. This causes many backend files related to resourced to be deleted
6. Restored the deleted files
7. In amplify/team-provider-info.json copied over categories from a working env
8. Adjusted the region and ARN settings where applicable in the copied over data
9. Pushed to Git and let it build

**Comment by hloriana** [comment]
Hi @SantoshRaoMea, glad to see you were able to find a workaround and thank you for providing feedback on the logging process. If you run into this issue again feel free to reopen this.
