### ISSUE TITLE
App deletion and deployment stuck in process for over an hour

### ISSUE THREAD

**Issue by danielmbutler** [aws-amplify/amplify-console#2495]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3tmxf00jyzsb9

### Describe the bug

trying to delete app from console but the process has been stuck for over an hour.

### Expected behavior

Deletion should have happened within 15 mins or so.

### Reproduction steps

clicked delete from amplify console

**Comment by danielmbutler** [comment]
![image](https://user-images.githubusercontent.com/46110343/148703295-4775c593-045a-4dd5-8101-2a5230f5d3cd.png)

**Comment by hisham** [comment]
I think there is an ongoing issue with amplify console currently - see https://github.com/aws-amplify/amplify-console/issues/2494

**Comment by hloriana** [comment]
Hi @danielmbutler 👋🏽, if you're still running into issues deleting your app try running this command to completely remove your backend: `aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>`.

You should then be able to delete the frontend from the console.

**Comment by danielmbutler** [comment]
Hi @hloriana thanks for your response, after some time all the operations were completed and all is good now.  will clsoe this
