### ISSUE TITLE
How can I stop or cancel app deletion?

### ISSUE THREAD

**Issue by zijing07** [aws-amplify/amplify-console#2496]
**Please describe which feature you have a question about?**
I have initiated app deletion, but I want to cancel it.

**Provide additional details**
I found it is deleting the whole app, including my prod stage.

**What AWS Services are you utilizing?**
amplify

**Provide additional details e.g. code snippets**
app id: d3ps42sgg5f2m5
Region: us-west-2

**Comment by hloriana** [comment]
Hi @zijing07 👋🏽 thanks for reaching out! Deleting an application is irreversible. When doing so from the console, a modal will pop up for you to confirm that you want to proceed with deleting the application. 

If you want to delete a single environment from the console, you'd navigate to the **Actions** drop down menu within that environment section and select **Delete**.
