### ISSUE TITLE
How to change repository service provider Github to Gitlab

### ISSUE THREAD

**Issue by julienlaurent-migso** [aws-amplify/amplify-console#2502]
Hello, we need to update our git repository service provider : Github to >> Gitlab 
When we try to do it inside the amplify console using the button "reconnect repository we do not have the option to change the service provider to Gitlab.
![image](https://user-images.githubusercontent.com/79509459/149128318-cf98055c-bb51-4d03-ae38-587401c25a8b.png)
![image](https://user-images.githubusercontent.com/79509459/149128511-72d22dd1-b5c7-48ca-b377-dc3465e7a9ac.png)

We really need to change our repository without creating a new amplify app, reconfiguring everything ... 
Thank you very much for you help, 
Regards

**What AWS Services are you utilizing?**
Aws Amplify

**Comment by hloriana** [comment]
Hi @julienlaurent-migso 👋🏽 thanks for raising this question!  I'm checking in with the team to see if this is possible. I'll be back with an update shortly.

**Comment by hloriana** [comment]
You can change your Git provider via the CLI using this command `aws amplify update-app --app-id <value> --repository <value> --access-token <personal access token value>`. If you need anything else please feel to open a new issue. Thank you!

**Comment by julienlaurent-migso** [comment]
Hi @hloriana,

Thank you very much, it works well !
(just before use the command I had to configure aws with my AWS Access Key ID & AWS Secret Access Key)
regards,

**Comment by satyadeepk** [comment]
@hloriana When I am trying to change my repository provider from Gitlab to Github, I get the following error.

`Error parsing parameter '--repository': Unable to retrieve https://github.com/org/repo: received non 200 status code of 404`

I am trying with a personal access token. It's a private repo in an organization of which I am an owner.

**Comment by medinatochiajro-metergram** [comment]
@satyadeepk did you manage to solve this issue, I am having the same issue with BitBucket?

**Comment by daroczig** [comment]
@satyadeepk @medinatochiajro-metergram I'm probably late to this party, but wanted to share my related experiences as might be useful for others in the same situation: you might get the `404` error when using AWS CLI v1 with the `--access-token`, which does an extra `GET` call to the URL (without the access token) and fails. In theory, setting `cli_follow_urlparam` to `false` should solve it, but I needed to update to AWS CLI v2 after all. Thanks to AWS Support Team for pointing this out!
