### ISSUE TITLE
how to connect to Amazon Documentdb?

### ISSUE THREAD

**Issue by two4zero** [aws-amplify/amplify-console#2504]
**Please describe which feature you have a question about?**

My project(react client) requires mongodb. therefore..
How to connect to Amazon Documentdb using Amplify?

**Provide additional details**
amplify react client

**What AWS Services are you utilizing?**
Amazon Documentdb

**Provide additional details e.g. code snippets**

**Comment by hloriana** [comment]
Hi @two4zero 👋🏽, thanks for reaching out with this question! In short, you'll need to [create an AppSync API](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js/) and attach a Lambda resolver which will allow you to connect to Amazon DocumentDB. Here is a blog with a tutorial for how to do so: [Build a GraphQL API for Amazon DocumentDB (with MongoDB compatibility) using AWS AppSync](https://aws.amazon.com/blogs/database/build-a-graphql-api-for-amazon-documentdb-with-mongodb-compatibility-using-aws-appsync/).
