### ISSUE TITLE
how do i configure amazon aws email with webhooks

### ISSUE THREAD

**Issue by umerghori786** [aws-amplify/amplify-console#2505]
Hi i am using aws amazon smtp for emails now i need to configure webhooks with my email service.. how i configure it.. my region is US East (N. Virginia)
us-east-1
Thanks

**Comment by umerghori786** [comment]
Thanks for answer! my region is US East (N. Virginia)
us-east-1 and i do not know my App ID where i get this

**Comment by hloriana** [comment]
Hi @umerghori786, you can find your App ID by navigating to the AWS Amplify console, select the app, then choose **General** under **App settings**. The App ID can be found at the end of the arn like so: 
`arn:aws:amplify:us-east-1:<aws-account -id>:apps/<app-id>`. 

For clarification, are you asking how to setup email notifications for your Amplify app? Instructions can be found here: https://docs.aws.amazon.com/fr_fr/amplify/latest/userguide/notifications.html.
