### ISSUE TITLE
Can't delete app and back-end environment

### ISSUE THREAD

**Issue by Klinker195** [aws-amplify/amplify-console#2506]
First of all, this is my first time using Amazon services. I've been trying to delete my Amplify app (which I had for testing purposes) from the AWS Console but I always get this error:

![a](https://user-images.githubusercontent.com/64706581/149328832-36a3bf02-645a-4640-a04a-b3056a306381.PNG)

What should I do?

APP ID: d3w0w82urvq6fg
Region: EU (Paris)

**Comment by hloriana** [comment]
Hi @Klinker195  👋🏽 Try deleting your backend environment with this AWS CLI command : `aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>`.

Then you should be able to go into the Amplify Console and delete the frontend.
