### ISSUE TITLE
Could not initialize 'prod': The specified bucket does not exist

### ISSUE THREAD

**Issue by jericopulvera** [aws-amplify/amplify-console#2510]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

ap-southeast-1

### Describe the bug

2022-01-14T07:47:59.845Z [INFO]: [31mCould not initialize 'prod': The specified bucket does not exist[39m

### Expected behavior

the build should be completed. we didn't do any changes for a long time.

### Reproduction steps

trigger rebuild

### Additional information

App ID: d2ueuypv723ohy

**Comment by jericopulvera** [comment]
Closing this issue. Fixed it by removing BACKEND_PULL_ONLY=true env.

Turns out that old builds have problems with the Amplify backend environment as well but it's still proceeding with the build now it no longer proceeds. 

The app we're running is Next SSG but we cannot run it without an Amplify backend environment which we don't need.

**Comment by iuyt9003** [comment]
Same issue, looks like bucket is not exists. and not idea why or how
