### ISSUE TITLE
What username / password to use when logging in to Amplify Studio ?

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-console#2526]
**Please describe which feature you have a question about?**
Amplify Studio

When I try to pull my backend via cli like this:
```
amplify pull --appId xxxxxxxx --envName dev
```

I'm presented with the Amplify Studio login in a browser.
I've tried using various IAM user's I've made (With admin permission) and my root account user, but none of these work.

So, how do I log in to Amplify Studio ?

**Comment by hloriana** [comment]
Hi @kjetilge 👋🏽 thanks for reaching out for assistance. You can login to the AWS Amplify console and navigate to the **Amplify Studio settings** under the app you want to access. In the **Access control**  panel, select **Invite Users**. You'll be able to create a user that can login to the Amplify Studio.

**Comment by kjetilge** [comment]
Thanks! 😃

**Comment by hloriana** [comment]
You're welcome! 🙂

**Comment by LightbulbServices** [comment]
Hi @hloriana 
I tried your suggestion...
> Hi [no need to alert] 👋🏽 thanks for reaching out for assistance. You can login to the AWS Amplify console and navigate to the **Amplify Studio settings** under the app you want to access. In the **Access control** panel, select **Invite Users**. You'll be able to create a user that can login to the Amplify Studio.

When I try this I am notified by AWS that I "Cannot create user(s)".
This is the case for full access or manage only.
The user I'm logged in to the AWS Console with has AdministratorAccess.

Thank you for any help you may be able to provide on this!

![image](https://user-images.githubusercontent.com/56498633/160182880-1d335eaf-b9c1-4ae8-96d4-cd495e16f63e.png)
