### ISSUE TITLE
I cannot attach my domain with amplify

### ISSUE THREAD

**Issue by investorkraft** [aws-amplify/amplify-console#2528]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2wjeg6853vdll

### Region

ohio

### Step

domain activation

### Status

failed

### Issue or question

please assist me to attach my domain

**Comment by ganipcanot** [comment]
Closing due to age - please re-open if you are still experiencing issues.
