### ISSUE TITLE
Using Amplify CLI, GitFlow, and Amplify Console to Deploy on branch commit

### ISSUE THREAD

**Issue by dsr771** [aws-amplify/amplify-console#253]
** Please describe which feature you have a question about? **
Amplify CLI and Amplify Console using gitflow branching and auto deploy via console

** Provide additional details**
I created 3 environments for a React / AppSynch / GraphQL application with Cognito Auth. 
I am using the gitflow branching method with a develop, staging, and master branch.
I have connected all 3 environments using amplify add env and push.

When I make a code update, I will test on my dev environment with amplify mock, then use amplify push from my 'dev' environment.
Next, I commit all of the changed files and push the branch to github.

When ready, I create a release branch and merge it into master. master is connected to an amplify env called 'prod'. 
Amplify Console gets the  commit notice from github and does a build/deploy. And usually succeeds.

My problem is that the build for master which is handled by Amplify console will not use the correct  lambda custom variables. Because of this, the custom email message (Auth) for new signups is wrong and users are not added to my desired cognito group. And anything else configured for those lambda functions.

If I follow up and use amplify cli to checkout the prod environment and use amplify push, it seems to fix the problem temporarily until the next commit/build/deploy.

This same thing happens for my staging branch which is deployed by amplify console.
The develop branch will actually deploy properly if I merge branches via github without using amplify push.

I am expecting that the amplify console build would be able to deploy to any connected branch without having to manually push via amplify push for each env. 

It appears to be almost doing everything. I see that each environment has the proper S3 bucket with the values needed.

Here is what the two build outputs look like:

The dev env and develop branch:
"function": {
  "myappe5bf4e43DefineAuthChallenge": {},
  "myappe5bf4e43CreateAuthChallenge": {},
  "myappe5bf4e43VerifyAuthChallengeResponse": {
  "RECAPTCHASECRET": "myappchal"
  },
  "myappe5bf4e43CustomMessage": {
  "REDIRECTURL": "https://on.myapp.com/",
  "EMAILSUBJECT": "DEV - MyApp Account Confirmation",
  "EMAILMESSAGE": "Thank you for creating a new account on MyApp.\\\\n\\\\n Please enter this code to confirm your recent signup: {####}.\\\\n\\\\nTo confirm this new registration, click or visit the link below (If this was in error no action is necessary):\\\\n\\\\n"
  },
  "myappe5bf4e43PostConfirmation": {
  "GROUP": "Instructors"
  }

The build for other branches via console have this:
"function": {
    "myappe5bf4e43DefineAuthChallenge": {},
    "myappe5bf4e43CreateAuthChallenge": {},
    "myappe5bf4e43VerifyAuthChallengeResponse": {},
    "myappe5bf4e43CustomMessage": {},
    "myappe5bf4e43PostConfirmation": {}
    }

I am using amplify cli 3.16.0

My console build setting:
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - envCache --set stackInfo ""
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

I have tried without the - envCache as well. It seems to fail on build without it.
I recently added a build image setting to test: Amplify CLI latest

Once I get this working, I want to explore how to make the custom email look nicer.

Thank you in advance for any help.

**Comment by swaminator** [comment]
This is linked to #206

**Comment by litwicki** [comment]
Resolved with #206
