### ISSUE TITLE
Can't get data to return on App screen from GraphQL query

### ISSUE THREAD

**Issue by trevorkirchnerID** [aws-amplify/amplify-console#2533]
**Please describe which feature you have a question about?**
Amplify

**Provide additional details**
I am trying to run a simple query from my Aurora DB. I am confident that there are not authorization/access issues as I am an admin. I have dummy data loaded in the DB and I am trying to run the query I have in the screenshot. It returns in the network console but does not render on the screen. I have tried it so many different ways from all the different documentation, but I can't seem to get it to work. Also, the query works in AppSync. 

Any help with this is greatly appreciated!!

**What AWS Services are you utilizing?**
Amplify
AppSync
Aurora RDS
Cognito
GraphQL

**Provide additional details e.g. code snippets**
![image](https://user-images.githubusercontent.com/96851861/150623434-7a671ed8-61a6-492d-bd30-3593a651ad6b.png)
![image](https://user-images.githubusercontent.com/96851861/150623448-3df57d07-142a-4197-aec9-fe4680b25f23.png)

Region - us-east-1

**Comment by trevorkirchnerID** [comment]
import awsExports from "./aws-exports";
import "./styles.css";
import '@aws-amplify/ui-react/styles.css';
import React, { useEffect, useState, Component } from 'react'
import Amplify, { API, query, graphqlOperation, signInButtonContent } from 'aws-amplify'
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);
Amplify.configure(awsExports);

const USERSql = `
query getUSERS {
  getUSERS (USER_ID: 3) {
    LAST_NAME
  }
}
`

const App = () => {
  //const [formState, setFormState] = useState(initialState)
  const [user, userData] = useState([])

  useEffect(() => {
    fetchUSERS()
  }, [])

  const  fetchUSERS = async () => {
    try {
      const userData = await API.graphql(graphqlOperation(USERSql))
      const user = userData.data.USERSql.items
      userData(user)
    } catch (err) { console.log('error fetching users') }
  }

  return (
    <div>
      <h2>Return Users</h2>
    
      <button onClick={fetchUSERS}>List Users</button>
      {
        user.map((USER) => (
          <div key={USER?.name}>
            <p>{USER?.LAST_NAME} </p>
          </div> 
        ))
      }
    </div>
  )
}
export default withAuthenticator(App)

**Comment by trevorkirchnerID** [comment]
`import awsExports from "./aws-exports";
import "./styles.css";
import '@aws-amplify/ui-react/styles.css';
import React, { useEffect, useState, Component } from 'react'
import Amplify, { API, query, graphqlOperation, signInButtonContent } from 'aws-amplify'
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);
Amplify.configure(awsExports);

const USERSql = `
query getUSERS {
  getUSERS (USER_ID: 3) {
    LAST_NAME
  }
}
`

const App = () => {
  //const [formState, setFormState] = useState(initialState)
  const [user, userData] = useState([])

  useEffect(() => {
    fetchUSERS()
  }, [])

  const  fetchUSERS = async () => {
    try {
      const userData = await API.graphql(graphqlOperation(USERSql))
      const user = userData.data.USERSql.items
      userData(user)
    } catch (err) { console.log('error fetching users') }
  }

  return (
    <div>
      <h2>Return Users</h2>
    
      <button onClick={fetchUSERS}>List Users</button>
      {
        user.map((USER) => (
          <div key={USER?.name}>
            <p>{USER?.LAST_NAME} </p>
          </div> 
        ))
      }
    </div>
  )
}
export default withAuthenticator(App)

`

**Comment by hloriana** [comment]
Hi @trevorkirchnerID can you try to console.log the user data

**Comment by hloriana** [comment]
Closing due to no response, if you are still having this issue please feel free to re-open. Thanks!
