### ISSUE TITLE
Amplify push is not working. Pops error "GraphQL Schema is using "@connection" directive from an older version of the GraphQL Transformer"

### ISSUE THREAD

**Issue by spharsh** [aws-amplify/amplify-console#2536]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-1

### Step

Launching one basic web app

### Status

Failed

### Issue or question

I am creating a web app for the first time. I followed following steps:
1)Installed node.js (v16.13.1) and npm (8.1.2) (all latest version)
2) npm install @aws-amplify/cli (latest version)
3) npx create-react-app
4) npm start (the basic app is live)
5) amplify init (success)
6) amplify add api
7) then i changed my schema.graphql, saved it
8) amplify push: This is giving me this error!!!

Since this is graphql error, this is what my schema.graphql looks like
type Post @model{ 
   id: ID!
   postOwnerId: String!
   postOwnerUsername: String!
   postTitle: String!
   postBody: String!
   createdAt: String
   comments: [Comment] @connection(name: "PostComments") #relationship
   likes: [Like] @connection(name: "PostLikes")
  
}

 
type Comment @model {
   id: ID!
   commentOwnerId: String!
   commentOwnerUsername: String!
   post: Post @connection(name: "PostComments")
   content: String!
   createdAt: String!
 
}
 
type Like @model {
   id: ID!
   numberLikes: Int!
   likeOwnerId: String!
   likeOwnerUsername: String!
   post: Post @connection(name: "PostLikes")
}

### Error message

An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Your GraphQL Schema is using "@connection" directive from an older version of the GraphQL Transformer. Visit https://docs.amplify.aws/cli/migration/transformer-migration/ to learn how to migrate your GraphQL schema.

**Comment by hloriana** [comment]
Hi @spharsh, you need to replace `@connection` with a more explicit directive such as `@hasOne`, `@hasMany`, `@belongsTo`, `@manytoMany`. More information can be found here: https://docs.amplify.aws/cli/migration/transformer-migration/#relationship-mappingconnection-changes
