### ISSUE TITLE
GitHub repo's not showing in list even with recent commits.

### ISSUE THREAD

**Issue by Beancow** [aws-amplify/amplify-console#2543]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dret5c7ityp6b

### Region

eu-west-2

### Amplify Console feature

Webhooks

### Describe the bug

Builds fail occasionally with this message.
> There was an issue connecting to your repo provider, click "Reconnect repository" in General Settings, and then try your build again.

I go to reconnect it, but I can't get the repo to show in the list.

I have tried:

* Adding a commit to the repo.
* Revoking access on my GH profile in the applications section and then re-authorizing AWS
* Removing the old webhooks manually.
* Deleting the app from amplify and re-adding it.

I have the same issues when adding new regions sometimes. I go to select the repo and I can't get it to show in the list.

_Extra info_: 

* I have instances/apps for production, develop and staging on different sub accounts watching different branches in the same repo if that affects anything.
* The repo list is very large for the org
* The only thing that does seem to fix it is renaming the repo, which isn't ideal.

### Expected behavior

I would like to be able to select the repo as needed. Failing that if there was a field I could just paste the path that would do too.

### Reproduction steps

This is intermittent. It is resolved at the moment.

Just going to the reconnect repo dropdown and sometimes it doesn't have the required repo listed.

**Comment by hloriana** [comment]
Hi @Beancow 👋🏽 thank you for raising this issue. It seems like this is intermittent behavior without clear reproduction steps. I've not been able to reproduce this behavior so far. Please update this issue if this behavior occurs again.
