### ISSUE TITLE
Deploy Failure: No ssrResources.json file

### ISSUE THREAD

**Issue by carlosbvz** [aws-amplify/amplify-console#2545]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1t8f7v7uqkz9e

### Region

us-east-1

### Amplify Console feature

Monorepo, Not applicable

### Describe the bug

Deploy process is failing with the following error: 

```
 [INFO]: Cannot find any generated SSR resources to deploy. If you intend for your app to be SSR, please check your app Service Role permissions. Otherwise, please check out our docs on how to set up your app to be detected as SSG (https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app)
 [ERROR]: {"code":"7","message":"No ssrResources.json file"}
```

I have reviewed all related issues here: https://github.com/aws-amplify/amplify-console/issues?q=No+ssrResources.json

We do have set a service role, and this issue happens with new branches only.

### Expected behavior

Deploy step should succeed. 

### Reproduction steps

Create a new branch and push it to the repo
This will automatically trigger a deploy process.
The deploy step is currently failing.

**Comment by carlosbvz** [comment]
Update:

As stating, not new branches seems to complete the whole process. 

I did clone one this branches locally, and pushed it to the repo to trigger a build, and I got a pretty odd message in the "Deploy" tab:

```
2022-01-27T17:41:45 [INFO]: Starting Deployment
2022-01-27T17:41:45 [INFO]: Start deploying test artifact
2022-01-27T17:41:46 [INFO]: Deploying videos/pages/districts/filters.spec.ts.mp4
2022-01-27T17:41:46 [INFO]: Deploying videos/pages/home/title.spec.ts.mp4
2022-01-27T17:41:46 [INFO]: Deploying videos/shared/footer.spec.ts.mp4
2022-01-27T17:41:46 [INFO]: Deploying videos/shared/navigation.spec.ts.mp4
2022-01-27T17:41:46 [INFO]: Deploying videos/user/login.spec.ts.mp4
2022-01-27T17:41:46 [INFO]: Deploying videos/user/register.spec.ts.mp4
2022-01-27T17:41:46 [INFO]: Finish deploying test artifact
2022-01-27T17:41:46 [INFO]: Updating Edge config
```

**Comment by kahdojay** [comment]
@carlosbvz thanks for reporting - we're investigating

**Comment by kylemilden237** [comment]
we are seeing the same issue.

**Comment by victorccccc** [comment]
Sorry for the inconvenience, we are actively working on the fix.

**Comment by MEaston12** [comment]
Same problem here, just went through and wiped everything related to Amplify from the account and restarted my build from scratch, here's my app id if it helps: d1t8f7v7uqkz9e

**Comment by StephaneBischoff** [comment]
Same problem. Where can we check for Amplify live issue. Is there a website? Just found out by finding this open issue which is not great experience

**Comment by StephaneBischoff** [comment]
Same problem here. Any update? Our website is down.

**Comment by ferdingler** [comment]
@StephaneBischoff websites should not be down. This issue is only impacting new deployments. Our hosting service is not impacted. We are deploying a fix right now.

**Comment by charlieboles** [comment]
@ferdingler That's great to hear. Will this also fix #2540? After experiencing that issue I created a new branch and ran into this one.

**Comment by ferdingler** [comment]
> @ferdingler That's great to hear. Will this also fix #2540? After experiencing that issue I created a new branch and ran into this one.

Sounds related. This issue started happening today though. New apps are seeing deployment errors. Existing apps may not see any deployment error, but their latest changes won't be deployed. 

Appreciate the patience while we push a fix. 🙏

**Comment by victorccccc** [comment]
Thanks for the patience. This issue has been resolved

**Comment by carlosbvz** [comment]
Thanks for addressing this @ferdingler, 
I can confirm it all went back to normal.

**Comment by dogma-systems-c3x** [comment]
Hi @ferdingler I'm getting the same issue today (1/31/2022) with a new app (d16stj20da1jq0), you said issue has been resolved, there is something we need to do or change to make it work? Thanks in advance

**Comment by carlosbvz** [comment]
Hey @dogma-systems-c3x , 

I take back the "all went back to normal"

There is something still going on with Amplify, since we are facing still some issues. 

In my case, I am facing this one now: https://github.com/aws-amplify/amplify-console/issues/2551

**Comment by jericopulvera** [comment]
Happens again on #2602
