### ISSUE TITLE
Integrate dynamic subdomain with Amplify App

### ISSUE THREAD

**Issue by drashtibpatel** [aws-amplify/amplify-console#2560]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Step

Manage Domain > Subdomain auto-detection

### Status

not able to access subdomain automatically

### Issue or question

I have specific requirement for my application. Please find my requirement given below:

1) I am registering user in my application
2) I want to create the automatic custom subdomain for each users
3) My domain is configured in the Amplify app
For eg, My domain is www.example.com
My user is abc then subdomain www.abc.example.com should automatically pointing to the Amplify app
same for all other users. I want to do it automatically without open and create from the panel.
I checked it in the Route53 with the *.example.com on the same CNAME but not working as it might require to add IP.

Is there any other way or steps through that we can do it?

Thanks.

**Comment by ferdingler** [comment]
Hi, 

We do not support wildcard subdomains at the moment. We have a feature request in our backlog, feel free to +1 on it: https://github.com/aws-amplify/amplify-console/issues/44 

Thank you
