### ISSUE TITLE
Amplify ENV VARS documentation is wrong

### ISSUE THREAD

**Issue by gcid12** [aws-amplify/amplify-console#257]
**Describe the bug**
Amplify Environment Variables Documentation is wrong

**To Reproduce**
1. Go to 'https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html'
2. Scroll down to  : "Accessing Environment Variables"
3. The code example is wrong

```
build:
  commands:
    - npm run build:$BUILD_ENV
```
If you modify your Amplify Console YML, it will throw and error.  
At first sight is bad formatted YML

In my case, but most probably not for everyone, I fixed it like this:

```
build:
   commands:
      - REACT_APP_BUILD_ENV=$BUILD_ENV yarn build
```

**Expected behavior**
A code example in the docs 😘

**Desktop (please complete the following information):**
 - OS: OSX 10.14
 - Browser Chrome
 - Version 76.0.3809

**Comment by Joycehao19** [comment]
@KristineTrona @gcid12 we have provided a general way for you to access environment variables. We provided an example with `npm run build:$BUILD_ENV`. The point is you can access env variables in the build container by passing $ENV_NAME.

**Comment by Albert-Gao** [comment]
@Joycehao19 The problem is there is no such section...

![image](https://user-images.githubusercontent.com/18282328/74634885-b549a400-51c9-11ea-9e2c-c7cc64788c67.png)

Where can I find this env var section on Amplify's AWS GUI?

**Comment by KristineTrona** [comment]
@Albert-Gao that is very strange, the environmental variables, should be there:

<img width="245" alt="Screenshot 2020-02-17 at 09 13 37" src="https://user-images.githubusercontent.com/39855778/74635191-c9f45080-5165-11ea-91ba-26a8fc46149b.png">

**Comment by Albert-Gao** [comment]
I do not even have the build settings...
OK, so this is not an outdated doc...

Maybe it is because I am not using amplify to manage my front-end code's deployment?

And this disabled the Env Var section for me to use in the back-end code...
