### ISSUE TITLE
Install docker on Amplify build agent

### ISSUE THREAD

**Issue by anastasiyamazheika** [aws-amplify/amplify-console#2584]
**Please describe which feature you have a question about?**
Amplify CI

**Provide additional details**
Hello, I have a question. Does your team have a script on how to install the properly docker on Amplify build agent?
Thanks!

Regards,
Anastasiya

**Comment by hloriana** [comment]
Hi @anastasiyamazheika 👋🏽 here are the instructions to setup a custom build image with your preferred dockerfile: https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html

**Comment by hloriana** [comment]
If you need further assistance, feel free to re-open this issue. Thanks!
