### ISSUE TITLE
The type 'Query' [@83:1] has declared a field with a non unique name 'customersByEmail'

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-console#259]
**Describe the bug**
The schema compiles without errors using `amplify api gql-compile` but gives the following error when deploying:

`The type 'Query' [@83:1] has declared a field with a non unique name 'customersByEmail'`

The customer type: 

```gql
type Customer
  @model
  @key(
    name: "customersByEmail"
    fields: ["email"]
    queryField: "customersByEmail"
  )
  @auth(
    rules: [
      {
        allow: groups
        groups: ["Admins"]
        operations: [read, create, update, delete]
      }
      { allow: owner, ownerField: "owner", operations: [create, update, read] }
      { allow: public, provider: apiKey, operations: [create] }
    ]
  ) {
  id: ID!
  email: String!
  [...]
}
```

The Query schema: 
```gql
enum ModelSortDirection {
  ASC
  DESC
}

input ModelStringFilterInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
}

input ModelIDFilterInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
}

type ModelCustomerConnection {
  items: [Customer]
  nextToken: String
}

input ModelCustomerFilterInput {
  id: ModelIDFilterInput
  firstName: ModelStringFilterInput
  lastName: ModelStringFilterInput
  email: ModelStringFilterInput
  zipCode: ModelStringFilterInput
  owner: ModelStringFilterInput
  and: [ModelCustomerFilterInput]
  or: [ModelCustomerFilterInput]
  not: ModelCustomerFilterInput
}

type Query {
  customersByEmail(
    email: String
    sortDirection: ModelSortDirection
    filter: ModelCustomerFilterInput
    limit: Int
    nextToken: String
  ): ModelCustomerConnection @aws_api_key @aws_cognito_user_pools
}
```

I am attempting to override what is generated so that `@aws_api_key` (public access) is available to this query.

**To Reproduce**
1. write the above in schema
2. run gql-compile
3. push change in repo to console

**Expected behavior**
Successful deployment

**Comment by Joycehao19** [comment]
Hello @aireater , sorry that you are facing this issue. We are currently investigating this issue. Do you have a sample repo that we could test with?

**Comment by aireater** [comment]
I don’t have a sample repo to test. Are you not able to replicate the issue with the code I included?

**Comment by swaminator** [comment]
Cannot reproduce anymore.

**Comment by arealmaas** [comment]
I get the same error. Could it be that the name and queryField has the same name? 

using 4.34.0

I had:

@key(name: "byClaimCode", fields: ["claimCode"])

changed it to

@key(name: "byClaimCode", fields: ["claimCode"], queryField:"byClaimCode")

And then i got that same error.

**Comment by arealmaas** [comment]
The reason is because I didn't include the list query... once I remove this line it worked: ✅
```queries: { get: "getXX" }```

**Comment by blackgerman** [comment]
duplicated fiield in the schema
