### ISSUE TITLE
Unable to delete application

### ISSUE THREAD

**Issue by mhinton** [aws-amplify/amplify-console#2596]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3t3z91wv3psp4

### Region

us-east-1

### Describe the bug

Performing the delete application in the UI returns this error message.

"Invoking remove all backends execution failed"

### Expected behavior

The application should be deleted.

### Reproduction steps

Select the app
Selection Actions -> Delete app
Confirm deletion

### Build Settings

```yaml
not applicable
```

**Comment by hloriana** [comment]
Hi @mhinton, please try this command: `aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>`

**Comment by mhinton** [comment]
@hloriana thanks for the response but this is what happens when I issue that command.

```sh
aws amplify delete-backend-environment --app-id d3t3z91wv3psp4 --environment-name dev 

An error occurred (NotFoundException) when calling the DeleteBackendEnvironment operation: App d3t3z91wv3psp4 not found.
```

Here's my app details to confirm the app id.

![CleanShot 2022-02-23 at 09 58 41](https://user-images.githubusercontent.com/23145/155357190-cb9824ad-5993-4f80-a7a8-4558d127049b.png)

**Comment by hloriana** [comment]
@mhinton interesting. Can you confirm if the CloudFormation stack still exists? If not then the backend is deleted so you should be able to delete the frontend application from the console now. Please let me know if you're still not able to delete the application.

**Comment by mhinton** [comment]
Thanks, I was finally able to delete the application.
