### ISSUE TITLE
Custom Domain issue 

### ISSUE THREAD

**Issue by Abdulmoeidkhan** [aws-amplify/amplify-console#260]
**App Id**:Z1HB588SF3891N
**Region**:ALL
**Step**:SSL certification
**Status**:Pending

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I have deploy an APP on AWS amplify then i made a domain transfer from another provided to GANDI and then to AWS Route 53 then i add a domain to my aws amplify app but unfortunately it is still in the pending status at the point SSL certification i have tried it thrice but not found any result yet 
![ERR](https://user-images.githubusercontent.com/25826032/69262622-a3199300-0be5-11ea-9ba9-28aaed61c8d0.png)

  

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by Joycehao19** [comment]
@Abdulmoeidkhan can you try retry adding the domain?

**Comment by Abdulmoeidkhan** [comment]
i have tried multiple times but still facing the same

**Comment by Joycehao19** [comment]
@Abdulmoeidkhan Can you remove the app, wait and try again after some time(6 hours)? If you still face the issue, please let me know.
