### ISSUE TITLE
App frontend failed with no code change

### ISSUE THREAD

**Issue by qingjamazon** [aws-amplify/amplify-console#2600]
Hello, 

I am new to this tool and try to find out why a tool built in AWS Amplify failed. There is no code change in the past half year, but front end UI has been not working anymore since begining of Feb this year. I am unable to find any error message or useful log in Amplify. 

This tool allows users to upload excel file and triggers lambda function to pass the excel file to a S3 location. But this tool is now completly frozen. Files can not be uploaded successfully even though there is always a message of 'Success! excel uploaded to bucket.' in the UI. 

App name: amazon-s3-presigned-urls-aws-sam
Source repository: https://us-east-1.console.aws.amazon.com/codesuite/codecommit/repositories/amazon-s3-presigned-urls-aws-sam/browse/refs/heads/master?region=us-east-1
Production branch URL: https://master.d3r5s4z4i748yl.amplifyapp.com/

**Comment by hloriana** [comment]
Hi @qingjamazon your frontend is password protected so I can't see what could be happening. Are there any errors being thrown in the browser? Have you tested that the uploads are successful when running the app locally?

**Comment by qingjamazon** [comment]
I was able to troubleshot with a software enginner from our team to resolve it. Thank you.
