### ISSUE TITLE
Domain activation is Failed - [Is used on another app but doesn't work on this one with different route]

### ISSUE THREAD

**Issue by rolandoesc** [aws-amplify/amplify-console#261]
**App Id**: d2t54xascgadwa
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
This domain is being used on another app I have but it doesn't work for this other.

**Error message**
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
![Captura de pantalla 2019-11-20 a la(s) 11 59 11](https://user-images.githubusercontent.com/13950384/69264611-438f9900-0b8d-11ea-969e-8c14b8d7d04b.png)

**Comment by Joycehao19** [comment]
Hi @rolandoesc you could check `CNAMEAlreadyExistsException Error` section to see if it works: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#CNAMEAlreadyExistsException%20\Error.html

**Comment by rolandoesc** [comment]
Your solution worked perfectly for my requeriment, thank you very much.
