### ISSUE TITLE
Domain activation is Failed - [Problems Registering Domain]

### ISSUE THREAD

**Issue by WryanBrock** [aws-amplify/amplify-console#263]
**App Id**: d2t40cu5ulc5lh
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Can't seem to configure the transferred domain with route 53 and amplify.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Joycehao19** [comment]
Hi @WryanBrock , sorry that you having the custom domain issue. Could you please check and try `CNAMEAlreadyExistsException Error` section at https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#CNAMEAlreadyExistsException%20\Error.html
