### ISSUE TITLE
Migrate Amplify apps between Regions

### ISSUE THREAD

**Issue by Zelig880** [aws-amplify/amplify-console#266]
** Please describe which feature you have a question about? **
Amplify deployment and management

** Provide additional details**
I have the need to move an amplify website between environments.
The website was deployed on the wrong region, and it was been "fully set up" and it is actively used online.

I would like to know, if there is a way to "migrate" the apps, programmatically, or if I have to manually "copy" the website on the other region and then manually "switch" the DNS over the new endpoint.

Thank you for your help.

**Comment by swaminator** [comment]
For now you have to migrate it. You could also use CloudFormation to define your Amplify Console infrastructure. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Amplify.html
