### ISSUE TITLE
One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by AdnanGhazi16** [aws-amplify/amplify-console#267]
**App Id**: d3cuqmeuh212hh
**Region**: ap-south-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Joycehao19** [comment]
Hi @AdnanGhazi16 , sorry that you are facing the custom domain issue. Could you please check and try CNAMEAlreadyExistsException Error section at https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#CNAMEAlreadyExistsException%20\Error.html

If you still have this issue after 8 hours, please let us know.

**Comment by sankojunagendra** [comment]
Even I have the same problem
