### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Abdulmoeidkhan** [aws-amplify/amplify-console#268]
**App Id**: d3cuqmeuh212hh
**Region**: ap-south-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Joycehao19** [comment]
@Abdulmoeidkhan have you checked out this doc: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

You could also try deleting the domain and connecting the app again.

**Comment by Abdulmoeidkhan** [comment]
i already did these mention things but still i m facing the same

**Comment by Joycehao19** [comment]
@Abdulmoeidkhan  The error is `com.amazonaws.services.cloudfront.model.CNAMEAlreadyExistsException: One or more of the CNAMEs you provided are already associated with a different resource. (Service: AmazonCloudFront; Status Code: 409; Error Code: CNAMEAlreadyExists; Request ID: 7520d80d-0f48-11ea-89c4-b5c1772de095)`

If you had this domain successfully connected to another app and then recently (within the last hour) deleted it, please wait and try again after some time.

**Comment by Abdulmoeidkhan** [comment]
i have done this as well but whenever i did this and start whole process again all the things successfully done but domain activation is failed and previous website become live

**Comment by Abdulmoeidkhan** [comment]
??
