### ISSUE TITLE
Deleting GitHub Branch to result in deprovision and delete of CFN stacks

### ISSUE THREAD

**Issue by akrsmv** [aws-amplify/amplify-console#269]
I write this as a feature request, because not sure whether such behavior is expected. Basically my issue is that Aws Amplify,does not automatically deprovision, after a branch was deleted.

I am using Github with the AWS amplify app connected. I configure it to listen and automatically provision new backends for each new branch that is with the name pattern feature/**

That works great, however after PR approval of the feature branch, and deleting the feature branch, One has to manually go to:
1) Amplify console and disable the branch connection (branch is already deleted in Github)
2) CloudFormation and manually delete the Root stack for the feature branch infrastructure, that was provisioned.
3) Manually delete S3 deployment bucket

It would be great if Aws Amplify can do this automatically, on branch delete

**Comment by swaminator** [comment]
#24
