### ISSUE TITLE
Can't find github team repo

### ISSUE THREAD

**Issue by dongjason1** [aws-amplify/amplify-console#270]
**Describe the bug**
Recently moved code from a private personal repo to a private team repo and I can no longer find the the project in the list of repositories. The migration was not GitHub's migration tool but instead manually pushed to a new repository. 

**To Reproduce**
1. Click on GitHub
2. Scroll down to all possible repos
3. Cant find my team repos

**Expected behavior**
I should be able to see my team repos

**Additional context**
I thought maybe this was part of the github api throttling issue but after making a commit and waiting several days, the repo never showed up. I'm also curious to know if there's any way to disconnect my github account and reconnect a different one.

**Comment by dongjason1** [comment]
Issue is also mentioned here https://github.com/aws-amplify/amplify-console/issues/112#issuecomment-555287746

**Comment by Joycehao19** [comment]
@dongjason1 
1. Team repo: go to github.com -> setting -> applications -> Authorized OAuth Apps 
Check if the team is authorized.
2. Log in the different account on github.com. The amplify console will access the new account.

**Comment by dongjason1** [comment]
That did it, thank you!
