### ISSUE TITLE
Preview branches resources are not deleted when prs are merged

### ISSUE THREAD

**Issue by thedgbrt** [aws-amplify/amplify-console#277]
**Describe the bug**
With the preview feature, connected to GitHub PRs, resources are not deleted when the PR is merged / closed.

**Expected behavior**
The aws resources that were created for the preview build should be deleted when the pr is closed.

**Additional context**
I noticed this because s3 told me I was over the limit of 100 buckets. Indeed, there were dozens of buckets (for storage, deployment and verification) that still existed, for pr's that I had long merged.

**Comment by swaminator** [comment]
@thedgbrt currently the CLI does not delete the deployment S3 buckets so you are manually going to have to merge them. We have a PR out to add support for the deleting the buckets. Will notify you once its out.

**Comment by CaptainChemist** [comment]
Out of curiosity, is there any way manually to get those old branches to clear from the amplify console? Is it just a matter of manually deleting the s3 bucket and everything else will get cleaned up or will doing that break the cleanup process from happening once this PR gets merged?

**Comment by hassankhan** [comment]
@swaminator Just wanted to add that Preview environments should also be deleted if a PR is closed (and not merged).

**Comment by swaminator** [comment]
@CaptainChemist what exactly are you seeing?

**Comment by bassrock** [comment]
I am also seeing this. We have preview branches that use an API backend per environment and when pr's are merged and their branches are deleted the appsync preview environments are never removed.

**Comment by nagey** [comment]
@swaminator I'm also not seeing DDB tables as being removed if they have any data in them — is that also something that will be resolved? I know it's a slightly different deletion policy than standard, but given that DDB tables are limited per account, would be really nice to have without have to go through and manually delete them

**Comment by yuanworks** [comment]
Is there an update on this issue? The Amplify PR preview page states that:

```
After the pull request is closed, the preview URL is deleted, and any ephemeral backend environment linked to the pull request is deleted. 
```

I did note that some PRs got eventually deleted after merging / closing or deleting, and I also don't see any extra S3 buckets (that includes the ones for PRs that are still open, not sure where the docker files are stored).

Just want to be absolutely sure this is working 💯 loving Amplify!

**Comment by guillesha** [comment]
Same here, it is really annoying that we have to remove them manually, it looses a bit the meaning of the preview. Also is not valid according to the documentation.

**Comment by chemzo** [comment]
I have a similar issue, my repo is in bitbucket.
Previews are not deleted, as well as the related front-end environments and it fails to manually the backend environments.

Related branches are closed as well as the PRs.

**Comment by sutirtha-crejo** [comment]
Any updates on this? Currently this is a major blocker stopping teams from adopting web previews via Amplify. This looks simple enough to already be working as part of the offering, its frustrating that this is a known issue and has still not been resolved/looked into.

**Comment by astef-trilogy** [comment]
After developing for a few months, we are seeing hundreds of backend environments in "Continuous deploys not set up." state, because they were not cleaned up after PRs were merged/closed.

Now the whole team is blocked because we've hit non-adjustable AWS limits (such as number of CF distros attached to the same policy).

Since I will spend this day on deleting those environments anyway, I'm leaving this message for you to know that **THIS SHOULD BE FIXED**.

Thank you!

**Comment by lukasburns** [comment]
Any update on this, I currently ended up with 100 buckets,
common sense is to automatically delete it after a PR is merged.

**Comment by cpv123** [comment]
Would love an update on this. Having to manually delete resources is really slowing things down for me.

There's a "pending release" label on this issue but I don't see any associated PRs. Any idea if this is _actually_ going to be released soon?

Similar discussion going on at https://github.com/aws-amplify/amplify-console/issues/2123

**Comment by victorccccc** [comment]
Hi, sorry for the inconvenience, we've fixed this issue. Feel free to re-open if issue persists, thanks.
