### ISSUE TITLE
/.well-known/ folder not being copied in deployment

### ISSUE THREAD

**Issue by afladmark** [aws-amplify/amplify-console#278]
**Describe the bug**

Our Gatsby site deployment includes a static file `/.well-known/apple-developer-merchantid-domain-association.txt` required to enable Apple Pay integration. The file is available locally when built, but it does not appear in the file list when the deployment occurs and when requesting the file via our deployment URL we receive a 403 error.

It appears that dot files/folders are being ignored in the deployment? Is there an option or setting to change this behaviour? Or a way to explicitly specify that the folder should be copied? We currently just:

```
  artifacts:
    baseDirectory: public
    files:
      - "**/*"
```
And the file is at `/public/.well-known/apple-developer-merchantid-domain-association.txt`

Happy to provide more information if this isn't expected behaviour.

**Expected behavior**

All files in our deployment would be copied and served.

**Additional context**

The `/.well-known/` folder is a standard [RFC8615](https://tools.ietf.org/html/rfc8615) and is required for a number of important integrations. Apple uses it for Apple Pay, Universal Links, Android for Digital Asset Links, etc.

**Comment by afladmark** [comment]
As a workaround, if I deploy the folder as /well-known/ and then add a `200 (Rewrite)` rule which maps `/.well-known/<*>` to `/well-known/<*>` I can achieve it, but obviously it would be preferable not to have to do this.

**Comment by DavidNelsonCordelia** [comment]
@swaminator   Thanks for the pointer.   I tried this workaround and it does not work for me.  the actual file is slightly different then @afladmark lists.
I need to redirect the file: 
`/public/.well-known/apple-developer-merchantid-domain-association`
not 
`/public/.well-known/apple-developer-merchantid-domain-association.txt`
Note the lack of a file extension

I did try a redirect on
`/.well-known/<apple-developer-merchantid-domain-association>`
to 
`/well-known/<apple-developer-merchantid-domain-association.txt>`

**Comment by kubsystems** [comment]
@DavidNelsonCordelia @afladmark 

I am facing the same issue. Per [Square documentation](https://developer.squareup.com/docs/payment-form/add-digital-wallets/apple-pay), a specific verification file needs to be found at <domain>/.well-known/apple-developer-merchantid-domain-association

It has become clear to me as well that dot files are being ignored in the deployment. I am working through this issue and will comment back here once I find a permanent solution. In the few months since the last post if you've found a solution, if you could comment that would be greatly appreciated.

Thanks!

**Comment by nadirabid** [comment]
same issue - @afladmark thanks for trick

**Comment by gins0023** [comment]
+1 - Using this for apple pay w/ stripe and stripe won't let me add our domain because of this.  Tried the rewrite hack, but doesn't work because stripe rejects the redirect.

**Comment by EllieA** [comment]
@gins0023 try a rewrite, not a redirect - it worked for me with Stripe. @DavidNelsonCordelia I saved the file with a .txt extension and added the file name to the rewrite to make it work.

**Comment by gins0023** [comment]
@EllieA My mistake it actually was a rewrite, but I didn't specify the file in the rewrite or use the .txt extension.  After changing that it worked.  Thank You!

**Comment by swaminator** [comment]
@gins0023 @EllieA @nadirabid @DavidNelsonCordelia @afladmark we are currently working on a fix and should have something shortly.

**Comment by kahdojay** [comment]
Update: we are rolling out a fix that should reach all regions by end of next week

**Comment by kahdojay** [comment]
@gins0023 @EllieA @nadirabid @DavidNelsonCordelia @afladmark can you let us know if you're now able to deploy the .well-known folder? We rolled out a change and I was about to do it.

**Comment by EllieA** [comment]
@kahdojay I confirm that in my case the .well-known folder gets deployed, as well as any .files. Thanks!
