### ISSUE TITLE
Cache invalidation not working for Jekyll blog page

### ISSUE THREAD

**Issue by zackthoutt** [aws-amplify/amplify-console#281]
**Describe the bug**
I host my jekyll blog on Amplify and some of my pages don't have the cache invalidated like they should.

**To Reproduce**
Reproduction might be difficult since you need your browser to cache the files. This is how I'm reproducing it. I'll show you an example using my blog home page, which lists all of my posts (an important page to update correctly).
1. Go to https://www.zackthoutt.com/blog
2. Open up the network tab and look at the response headers. The last_modified date for me is Tuesday Nov 26. However, I've deployed at least once per day the entire week, the last deployment being last night (which I can see in the Amplify console).

<img width="1359" alt="Screen Shot 2019-11-30 at 8 23 10 AM" src="https://user-images.githubusercontent.com/8794758/69902427-f52b8880-134a-11ea-9043-2a265e9048c7.png">

3. If I go into the Amplify console, I can see in the last deployment that Amplify recognized this page as having updated on line 47 (`2019-11-30T04:39:42 [INFO]: Uploading blog/index.html`). 

<img width="1066" alt="Screen Shot 2019-11-30 at 8 25 57 AM" src="https://user-images.githubusercontent.com/8794758/69902441-23a96380-134b-11ea-8bf9-23934ffb70c3.png">

4. Even when I clear the browser cache locally, the file doesn't update correctly. The cache misses, but the last-modified date is still Nov 26. 

5. Opening different browsers returns the same results--files that are several days and several deployments old.

6. I just redeployed again. Now the last-modified date is Nov 27, which is better, but still not accurate. It is still missing several live blog posts which I can see if I navigate directly to those pages. 

7. Interestingly, if I go into the Amplify console and manually redeploy the latest version, the file continues to update incrementally one version. So I hit the redeploy button about five times and each time the cached files caught up by about one deployment. I've deployed enough times that the file in the cache now matches what it should be. So if anyone else has this problem, you can likely fix it by manually redeploying a bunch of times, but I hope this bug can get fixed. It's like only this one page fell out of sync with the Amplify caching.

**Expected behavior**
According to [this page](https://docs.aws.amazon.com/amplify/latest/userguide/ttl.html), the cache should be updated when a file is updated during deployment. Since the file I'm trying to view was updated, the cache should have been bust and the `must-revalidate` cache control should force the new page to be loaded for all users after a deployment.

**Comment by ajohnson1968** [comment]
I'm seeing the same behavior with my amplify page.  What I see in the deployment is 'N' (4 or 5) commits behind what I'm publishing to github.  Also, like you mention, if I 'force' it to redeploy, it moves up one commit (but still not in-sync with the latest commit).  Very strange.

**Comment by bekatom** [comment]
Same problem here, Any solutions?

**Comment by litwicki** [comment]
@bekatom @ajohnson1968 @zackthoutt this should be resolved now. If you notice any recurrence please reopen this issue.
