### ISSUE TITLE
TLS/SSL certificaten versions

### ISSUE THREAD

**Issue by wbroek** [aws-amplify/amplify-console#285]
Because we cannot controle the SSL/TLS certificates ourselves at the moment, see https://github.com/aws-amplify/amplify-console/issues/56 , I was wondering who determines the versions of TLS/SSL for the created certificates? 
The above question is also because version 1.0 and 1.1 are [deemed insecure and deprecated as of Jan 2020](https://blog.qualys.com/ssllabs/2018/11/19/grade-change-for-tls-1-0-and-tls-1-1-protocols) (browsers will also disable them) , will the certificates on Amplify Console also disable these versions then?

**Comment by kahdojay** [comment]
Hi @wbroek, AWS determines the supported TLS versions, and does not provide the ability to disable specific versions. With Amplify, TLS 1.2 is supported and as long as end users use a browser that supports 1.2, that version will be used by default.

**Comment by wbroek** [comment]
Hi @kahdojay thank you for the response. I was thinking that AWS would determine that yes and also my bet would be that they would change the requirements of the certificates if things change.

**Comment by pabloroz** [comment]
@kahdojay we are required to force 1.2 there are some other aws services that allow this, like api gateway or elb is there any way of doing it on amplify?

**Comment by kahdojay** [comment]
@pabloroz we're rolling out TLSv1.2_2021 to all apps over the next few weeks, some have already been updated, more details here

https://github.com/aws-amplify/amplify-console/issues/2007

https://aws.amazon.com/about-aws/whats-new/2021/06/amazon-cloudfront-announces-new-tlsv12_2021-security-policy-for-viewer-connections/

**Comment by jerocosio** [comment]
Hi @kahdojay, I recently came into this issue myself but it looks like my app is still on the older version of TLS, can you still help me out to get it to the latest? This is my app id: d31zivslas7crz

Thanks!
