### ISSUE TITLE
Amplify Console Build completes successfully but then hangs at random places during the deploy stage.

### ISSUE THREAD

**Issue by wajjs** [aws-amplify/amplify-console#287]
**Describe the bug**
We build a gatsby application with around 40k files.
The build-step completes successfully but then hangs at random places during the deploy stage.
I have let the deploy run for a few hours and there is no Errormessage in the AWS Amplify Console.
I have tried to set the parameter BUILD_TIMEOUT from 30 minutues to 480 minutes, but this does not seem to matter.

Here is the Arn for a failing job:
"jobArn": "arn:aws:amplify:eu-west-1:276344999923:apps/dlyg548uv2mf3/branches/master/jobs/0000000073"
"appArn": "arn:aws:amplify:eu-west-1:868638307281:apps/dnl9xdqqvpm5k"

Build artifact is: 504MB (zip) 2.16 Gb unzippped and 39.000 files.

The last line in the deploylogs  for  build #73 looks like this: (line 13447)
2019-11-08T09:16:04 [INFO]: Uploading page-data/bukse-XXXXX-hp-sor-sor-XX-snic-pXXXXX/page-data.json

There is nothing more after this. 
Usually the deploy says "Updating Edge config. Deployment finished."

I Have got this reply from AWS Premium Support (Case #6575401101):
"I researched and noticed that you are having errors after the "Edge config". I'm opening an internal ticket to Amplify team regarding this issue. We had errors similar to this in the past [1], however, they shouldn't be happening anymore."
...
"could you open a GitHub issue on this"

**To Reproduce**
1. Add a gatsy application with 40k files. (~110kb in each file)
2. Trigger a build/deploy in AWS Amplify Console
3. Wait for deploystep to hang (usually around line 14.000)

**Expected behavior**
Amplify deploy step deploy ALL files.

**Additional context**

**Sample code**

**Comment by swaminator** [comment]
@wajjs how big is your node_modules folder? We have a known issue in #115 which we are actively working on. The temporary workaround is to delete unused branches in your app.

**Comment by swaminator** [comment]
Please comment on #115. Closing here.
