### ISSUE TITLE
Domain activation is Failed - Cannot connect to 3rd party provider

### ISSUE THREAD

**Issue by allenheltondev** [aws-amplify/amplify-console#290]
**App Id**: d1prhe5ul32pcx
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I am trying to hook up my amplify app to a specific subdomain on my site that is hosted with a 3rd party provider. I have added the provided CNAME and added a CNAME pointed to the URL of my branch, but I keep getting stuck at the Domain Activation step. I cannot find any meaningful error message to help me troubleshoot the issue further.

**Error message**
Error message: The status of this certificate request is "Failed". One or more domain names have failed validation due to a Certificate Authority Authentication error

**Additional information**
Can somebody please help me with troubleshooting steps? I have tried a number of things, but to no avail.

**Comment by Joycehao19** [comment]
Hello @allenheltondev , we are sorry that you are facing this issue. Could you please try the following links? If those links doesn't help, please let us know.

Troubleshoot CAA: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-caa.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html
https://docs.aws.amazon.com/amplify/latest/userguide/howto-third-party-domains.html

**Comment by allenheltondev** [comment]
I was able to figure this issue out reading through all the documentation. My issue was that I had to create an issuewild CAA on my root domain, and a CNAME for the specific subdomain I was trying to use.

Thank you for all the documentation.
