### ISSUE TITLE
Amplify Console build failing "Can't resolve '../aws-exports' in ...

### ISSUE THREAD

**Issue by jml-nola** [aws-amplify/amplify-console#292]
I have a Gatsby app tied to a CodeCommit repo that builds and deploys fine via Amplify Console until I add Amplify to the mix. I'm getting an error explaining ""Can't resolve '../aws-exports'". I assume that this file should be generated during the build, but I must be missing something. Any help is greatly appreciated!

**Comment by swaminator** [comment]
@jml-nola can you share your build settings please? Found in App settings > General

**Comment by jml-nola** [comment]
Certainly, thanks!

version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

**Comment by jml-nola** [comment]
The Amplify Console default build settings for Gatsby/Amplify are now working for me.
