### ISSUE TITLE
Old files (no longer in repository) not removed during deploy

### ISSUE THREAD

**Issue by leandigital** [aws-amplify/amplify-console#294]
**Describe the bug**
After deployment, files that were removed from repository are still getting served. Whether cached, or stuck in S3 storage. This is using Hugo framework.

**To Reproduce**
1. Deploy initial application.
2. Remove one of the content files from repository.
3. Push update to the repository.
4. Redeploy application.
5. Navigate to the old/removed URL and it is working.

**Expected behavior**
Files deleted from repository should not remain cached/available. I'm sure this can be solved by deleting and re-creating the application, but I would like to understand why this is not behaving normally. I'd expect everything to be overwritten on each deploy.

My build file is pretty simple:

> version: 0.1
frontend:
  phases:
    build:
      commands:
        - hugo --minify
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths: []

**Comment by swaminator** [comment]
Please refer to this: https://github.com/aws-amplify/amplify-console/issues/178#issuecomment-537616693

**Comment by simpson** [comment]
I am also in hot water because I can't purge files that users have explicitly requested be removed from our platform, we have deleted them in the build but the cache still exists. Is there any short term workaround for this while we find a better solution?
