### ISSUE TITLE
Amplify Console fails to detect frontend framework when connecting repo after Console app is initialized

### ISSUE THREAD

**Issue by Burry** [aws-amplify/amplify-console#295]
**Describe the bug**
When connecting git branches to an Amplify Console app that has not been initialized with a git repository, the Amplify Console fails to detect the frontend framework in use by the repository.

**To Reproduce**
To take advantage of the new features that connect a backend environment to the Console, I ran `amplify init --appId xxxxxxxxxxxxxx --envName xxx` on my project. This somehow created a new app in the Console as opposed to connecting my existing app (a separate issue), but I went along with this and re-connected my app's git branches to the new Console app and deleted the old app. Following this, the Console doesn't update to recognize that this is a React application using the Amplify Framework, resulting in a few missing settings in the Console, and there doesn't appear to be a way to manually set the framework.

**Expected behavior**
The Amplify Console automatically detects the frontend framework used by a connected git repository even when that repository is connected to the Console app after it is initialized.

<img width="853" alt="Screen Shot of Amplify Console General Settings" src="https://user-images.githubusercontent.com/1909420/70376884-4697c280-18cb-11ea-8f88-2f5349899822.png">

**Comment by kahdojay** [comment]
@Burry thanks for reporting this. We'll need to investigate this further on our end to see what's going on. Can you provide your Amplify App ARN in the meantime?

**Comment by Burry** [comment]
Hi @kahdojay, thanks for the response. The ARN is `arn:aws:amplify:us-west-2:405458141541:apps/d19p17l5qdw305`

**Comment by Joycehao19** [comment]
Hi @Burry , do you still have this issue when you re-connect a new app?

**Comment by Athena96** [comment]
Closing this issue. @Burry, please re-open this issue if you are still having problems. Thanks!

**Comment by AustinZhu** [comment]
I have the same problem here when I switched my production branch from develop to master. They have exactly the same folder structure and I think AWS should be able to detect the framework (React) we are using.
