### ISSUE TITLE
Add a pre-provision filter to determine whether build should commence

### ISSUE THREAD

**Issue by davekiss** [aws-amplify/amplify-console#30]
**Is your feature request related to a problem? Please describe.**
I'm using a monorepo on GitHub and and have CI/CD set up in Amplify console with several apps watching the same repo/branch. I'm currently exiting builds with a custom pre-build script that determines if the changes affect the current Amplify app, and if not, I exit with a non-zero status code which marks the build as failed, but more accurately, the build should have never began at all and I am likely being charged for the instance being provisioned.

**Describe the solution you'd like**
I'd like to have the ability to run a script from the `.yml` before provisioning to determine whether the build should happen at all, and also a way to exit gracefully without marking the build as errored.

**Comment by VividKnife** [comment]
As a temporary work around, I would suggest you to leverage our incoming webhooks feature to achieve this goal. 

1. Disable auto build for your existing apps.
2. Create an incoming webhook for each of your apps.
3. Create a new app that connects to the same repo. (For this app)
4. Write a script that determines which app should build and invoke that webhook url.

**Comment by talebbits** [comment]
We have been using Github action to hit incoming webhook to start a build. 
It would be great if we get this in amplify console.
```yaml
on:
  push:
    paths:
      # '*' matches any character except '/'
      - 'sub-project/*'
      - 'sub-project/*/*'
      - 'sub-project/*/*/*'```

**Comment by swaminator** [comment]
@talebbits @davekiss We launched monorepo support https://aws.amazon.com/about-aws/whats-new/2020/06/amplify-console-supports-deploying-and-hosting-web-apps-managed-in-monorepos/
