### ISSUE TITLE
Error in deployment getting build failed error..

### ISSUE THREAD

**Issue by MThakkar121** [aws-amplify/amplify-console#305]
Build failed error
And the other one is non-zero exit code detected..
![IMG-20191212-WA0006](https://user-images.githubusercontent.com/36958377/70678241-8c7fcc80-1cb7-11ea-81cd-6ae58b0e7984.jpeg)

**Comment by swaminator** [comment]
@MThakkar121 you need to provide the entire log. Preferable copied and pasted here.
