### ISSUE TITLE
SSL verification is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by chrisgreatest** [aws-amplify/amplify-console#31]
**App Id**: d3m0wg6wtlsyor
**Region**: us-east-2
**Step**: Domain Activation
**Status**: Complete

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I recently added a domain, matterintake.mosaic-consulting.com, and the first time I did it, it worked. I was able to use my subdomain (root excluded). Then, someone on my team didn't realize that I had done that, and they deleted it. I had to readd the domain. After readding the domain exactly the same and going through the same steps, it no longer works. It got all the way through domain activation, but going to my domain does not load anything anymore.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
![domain1](https://user-images.githubusercontent.com/20561261/62405037-b685ed00-b567-11e9-8a6e-34786fb9c279.png)
![domain2](https://user-images.githubusercontent.com/20561261/62405038-b71e8380-b567-11e9-992e-b6a55a334703.png)

**Comment by garyleefight** [comment]
@chrisgreatest Hi, do you still have problems? I checked your domain. Looks like it works now
