### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by aviv** [aws-amplify/amplify-console#310]
**App Id**: d1unyy0awhvypi
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**

I had a couple domains associated with one amplify app and want to move them to another one. I've deleted that first app (after deleting the domain entries) and also deleted those records from our route 53 account (where they had been automatically created). However I'm still getting this error: `Error message: One or more of the CNAMEs you provided are already associated with a different resource.`

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by kahdojay** [comment]
This looks the same as #311 - please see that thread, or re-open if turns out to not be the same.
