### ISSUE TITLE
Domain activation Failed - CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by ravishwetha** [aws-amplify/amplify-console#311]
**App Id**: d1nc9hr9i8v96u
**Region**: ap-southeast-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Custom domain issue

**Error message**
If there is an error message, please include it here. 

Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

Not sure of to delete the different resource

**Comment by kahdojay** [comment]
Hi @ravishwetha, have you tried this https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

**Comment by ravishwetha** [comment]
Hi @kahdojay I've gone through those steps.
1. I realised that I had one distribution attached to this domain and deleted it. I then retried but still got this message: 

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

2. I don't have any other amplify apps using this domain.

3. It's been more than 48 hours since I've connected to the new app.

**Comment by ravishwetha** [comment]
Just to update, I am currently using S3 to host my React app but I would like to switch to AWS Amplify asap. If you need me to update the dns to point back to the cloudfront distribution, let me know. I can do it between 2am and 5am UTC (10am and 1pm SGT)

**Comment by ravishwetha** [comment]
Any updates?

**Comment by Joycehao19** [comment]
Hi @ravishwetha ,  do you still have this issue?
