### ISSUE TITLE
Branch Auto-detection - Backend Environment Selection

### ISSUE THREAD

**Issue by 2ng-james** [aws-amplify/amplify-console#316]
Hi,

I am attempting to follow the steps for Pattern-based feature branch deployments: https://docs.aws.amazon.com/amplify/latest/userguide/multi-environments.html

I am currently unable to complete step 3 of the instructions as I do not get the option to configure backend environments for each auto-detected branch.

This is what I see in Amplify console:
![image](https://user-images.githubusercontent.com/58947678/70920424-7d33b280-201a-11ea-9c67-b4541c079975.png)

This is what I am expecting:
![image](https://user-images.githubusercontent.com/58947678/70920553-b4a25f00-201a-11ea-988c-c05c6afd0747.png)

Additional Info:
If it helps, I previously had the _Create new backend environment for every connected branch_ option selected.

Thanks for any help.

**Comment by kahdojay** [comment]
Thanks for reporting this, we're rolling out a fix this week.

**Comment by kkuriata** [comment]
I have the same issue here. These options are not visible for me as well.

**Comment by kahdojay** [comment]
A fix was rolled out for new apps but we need to look into addressing existing apps which seem to be still experiencing this issue. If deleting and recreating is an option, that should work for the time being, otherwise we'll update this thread once we've fixed it for existing apps as well.

**Comment by 2ng-james** [comment]
> A fix was rolled out for new apps - if possible, please recreate your app and let us know if you still experience the issue.

This is now working for my app - thanks.

**Comment by aleksejkozin** [comment]
@kahdojay hi
I have the same issue, can you help me?

**Comment by Joycehao19** [comment]
@aleksejkozin I tried it on my console without any issue. Would you mind to try it again? If you still didnt see `branch-autodetection - backend-environment`, please let us know,

**Comment by mikedizon** [comment]
I'm seeing this now as well. Recreating my app is not an option. @kahdojay

**Comment by blazinaj** [comment]
I'm also not seeing this option. We cannot re-create our app, but this feature would be nice to use. 
![image](https://user-images.githubusercontent.com/39976117/85612981-40bac200-b60e-11ea-9f75-edc2671c5103.png)

**Comment by cjmartin** [comment]
Also not seeing this option, is there a way to get it back without recreating our app? We're in us-west-2 if that might have something to do with it...
<img width="604" alt="image" src="https://user-images.githubusercontent.com/936/92127005-192a6780-edbe-11ea-83b6-5e1bff393edb.png">

**Comment by mansiva** [comment]
Option isn't showing up for us either, app was created less than a month ago.

**Comment by JarvisH** [comment]
We are also experiencing this. Could this issue be reopened?

**Comment by codecadwallader** [comment]
We're still seeing this with new apps created last week.  Any workarounds?

**Comment by ryan29871** [comment]
This is still an issue.  Any solutions?
