### ISSUE TITLE
Builds in console taking 20+ minutes to complete

### ISSUE THREAD

**Issue by davekiss** [aws-amplify/amplify-console#317]
** Please describe which feature you have a question about? **
How long do builds typically take to complete? I'm running `amplifyPush --simple` as part of my build process and the whole process from updating my CFN stack and building my React app is taking 20+ minutes, which feels pretty outlandish. Is there something I'm missing here?

** Provide additional details**
Happy to provide a build ID if it helps to look up the build logs, but not sure where to find that.

**Comment by kahdojay** [comment]
Hi @davekiss , can you please fill out our bug/issue template, thank you: https://github.com/aws-amplify/amplify-console/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

You can get the build number from looking at the console - click on the branch name in your app and you can scroll through builds

![Screen Shot 2019-12-16 at 16 15 10](https://user-images.githubusercontent.com/8794073/70953757-4744fd00-201f-11ea-8fd7-d44fef90035e.png)

**Comment by swaminator** [comment]
@davekiss it shouldn't take that long unless you're running something really big. Same for CFN deployments, if you're tweaking settings that should be quick, but if you're deploying infrastructure (userpools) for the first time it takes about 10 mins.

**Comment by swaminator** [comment]
@davekiss what region is your app in?

**Comment by harryd31** [comment]
We are also seeing the same thing on our side, started 2 days ago. it compiles successfully  but just stops there until it build time out kicks in.

<img width="1101" alt="Screen Shot 2019-12-18 at 11 58 54 AM" src="https://user-images.githubusercontent.com/6937848/71106820-f6074b80-218d-11ea-8672-9e56d2adfcc7.png">

**Comment by kahdojay** [comment]
Hi @harryd31 if you can provide some more details we can take a closer look, [e.g., App ARN, branch name, build number](https://github.com/aws-amplify/amplify-console/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). How long did it take previously? Did anything change two days ago?

**Comment by harryd31** [comment]
The App ARN is:  arn:aws:amplify:us-east-1:248178383705:apps/d1ne5iotblnclm and the build where thing started going slow is 194. And now we didn't make any real changes to the project. I increased the timeout to see if that will help,  it seems to have a bit.

**Comment by harryd31** [comment]
@kahdojay We're still experiencing the same problem, any luck so far?

**Comment by Joycehao19** [comment]
Hi @harryd31 , we are unable to check your app d1ne5iotblnclm, it seems the app was deleted. Please let us know if you are still having the same issue.
