### ISSUE TITLE
`amplify publish` url works, but CI/CD url fails authentication with AppSync

### ISSUE THREAD

**Issue by mcbergsma** [aws-amplify/amplify-console#318]
I've set up an app with the Amplify CLI, I added auth (cognito user pools), an API (graphql) and hosting.

It all actually went quite smoothly for the first try, and then I went into the Amplify Console and connected the frontend to my github repo. Everything there seems to work too, my app deploys at a new URL (still the default `amplifyapp.com` one). I can visit the page, it requires me to log in, which works, but then when I need to request a resource that queries graphql, it fails.

I've looked into the network tab and I get the following error:

```
{
  "errors" : [ {
    "errorType" : "UnauthorizedException",
    "message" : "Unable to parse JWT token."
  } ]
}
```

That only happens on my the version launched from the CD section of the Amplify Console. The URL from `amplify publish` works.

I looked into the request headers, and I presume this is where something is wrong because it sends the request with a `x-amz-security-token: IQoJb3JpZ2luX2VjEKf//////////wEaCXVzLWVhc...`, instead of the other version which sends a JWT like this in the header: `authorization: eyJraWQiOiJ5QkxnVTAxOWpo...`

I (think) I've scoured the documentation to figure out what's going on, but I might just not know the right terms to describe my issue to find other posts about it. Did my miss something in the automated setup? Is this a manual tweak I need to make after the fact? A bug? Any help is appreciated.

Cheers.

**Comment by mcbergsma** [comment]
It's auto-generated correct? I just noticed it is in .gitignore, so it doesn't go into the repo the CI/CD monitors. I thought I was just failing to understand the difference between `amplify publish` and what gets build by the CI/CD pipeline (I guess I still don't understand the difference!) - thanks for looking into it though.

**Comment by swaminator** [comment]
@mcbergsma it is autogenerated during the CI process. Some questions:
1. Which backend env are you connecting to?
2. Can you share your AppID? (App settings > General)

Thanks

**Comment by swaminator** [comment]
@mcbergsma can you try this:  https://github.com/aws-amplify/amplify-console/issues/163#issuecomment-536236794

**Comment by mcbergsma** [comment]
@swaminator That did it! Thanks very much!

**Comment by vientang** [comment]
I've encountered an issue that's very similar - in deployment there was an error updating the cloudformation stack because it couldn't find the right API key for AppSync. It was clearly an old api key. 

After following the steps to override the Amplify CLI version [setup live updates](https://github.com/aws-amplify/amplify-console/issues/163#issuecomment-536236794), the build passed. Hopefully this helps anyone later.
