### ISSUE TITLE
Wrong content type for CSS files

### ISSUE THREAD

**Issue by eacp** [aws-amplify/amplify-console#320]
**Describe the bug**
I deployed a static site and when I load it the browser does not load the css because the content type is not "text/css"

**Amplify CLI Version**
I'm not using the CLI I just followed the instructions to deploy using CI from github. 

**To Reproduce**
IDK how to I just know I have some CSS files in the generated directory from HUGO and they are served as octet stream.

You can check it at https://master.d1jvdwx4rnbunx.amplifyapp.com/ 

**Expected behavior**
I expected the CSS files to be served correctly.

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Additional context**

**Comment by swaminator** [comment]
@eacp can you share a sample repo to reproduce the same or a screenshot of what you're seeing? Is it accurate to say your CSS isn't being applied properly?

**Comment by eacp** [comment]
Hello. Our team decided to just use S3 and manually upload the files from the dist/ folder.
