### ISSUE TITLE
Domain activation is Failed - app disappeared and an recreated app failed

### ISSUE THREAD

**Issue by ejoonie** [aws-amplify/amplify-console#322]
The reason that I recreated an app was because the previous app associated with the domain(str-temp.com) had been disappeared in the amplify console. 

**App Id**: d2h9x5raax7b74
**Region**: ap-northeast-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by swaminator** [comment]
@ejoonie we do not delete apps on behalf of the customer. Are you sure the first app you created was in the same region as this one? To switch regions, choose the region list to the right of your account information on the navigation bar.

**Comment by Athena96** [comment]
@ejoonie are you still having issues?

**Comment by ejoonie** [comment]
> @ejoonie are you still having issues?

no, it's fine. thank you.
