### ISSUE TITLE
Deploy to custom S3 and leverage Amplify's CI/CD

### ISSUE THREAD

**Issue by cplankey** [aws-amplify/amplify-console#325]
** Please describe which feature you have a question about? **
Question is specifically around amplify hosting. 

** Provide additional details**
Currently I have my app deployed to my own S3 bucket but am struggling for the best CI/CD to make updates to the contents in the bucket. The amplify tutorial [here](https://aws.amazon.com/getting-started/tutorials/deploy-react-app-cicd-amplify/#) is great and I love the functionality, but I am looking for this same setup to go to my own S3 bucket, not an amazon owned one. 
All I am looking for is an easy way to trigger builds/deploys when I commit where I can specify different `npm build` commands per environment and deploy to my own bucket. 

Please let me know if I missed something previously published. Thanks!

**Comment by swaminator** [comment]
@cplankey  if you're looking to use your own S3 bucket, then you can use the manual deploys feature to upload new content: https://aws.amazon.com/blogs/mobile/deploy-files-s3-dropbox-amplify-console/

However you will have to set up your own CodePipeline that deploys to the S3 bucket if you want CI/CD setup. One of the benefits of Amplify is that we manage all the for you.
