### ISSUE TITLE
after failling to build it doesn't detect a fixed version on github

### ISSUE THREAD

**Issue by ei08047** [aws-amplify/amplify-console#326]
I've added a new commit to github; on amplify it picks up the commit but fails to build.
After i commit a fixed version, amplify desn't pick up the new commit.. what can i do?

** Provide additional details**

**Comment by kahdojay** [comment]
@ei08047 can you provide more details? If you can fill in the details from the [bug reporting template](https://github.com/aws-amplify/amplify-console/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) (e.g., steps to reproduce, expected behavior, errors, etc), it will help us understand the issue.
