### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by jimitab** [aws-amplify/amplify-console#328]
**App Id**: d3m1fpustoelzl
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by kahdojay** [comment]
Hello @jimitab, please see the following docs:

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

These guides are helpful for getting started with custom domains, for existing domains there are number of steps that will need to be completed (as outlined in the docs above) depending on your current hosting and DNS providers.

A CNAME alias (domain) can only be used with a single CloudFront distribution at a time, if you receive this error then the domain is already associated with another CF distribution (either in the same AWS account, or potentially in a different account) and must be moved to the distribution created for you by Amplify Console before it will work, the docs help outline how to do this (and you may need to check more than one account if you or your organization owns multiple accounts)

Please let us know if you have any questions!
