### ISSUE TITLE
One click deploy - choose branch

### ISSUE THREAD

**Issue by dabit3** [aws-amplify/amplify-console#33]
**Is your feature request related to a problem? Please describe.**
It would be nice to allow us to choose the branch we'd like to deploy when using the one-click deploy.

**Comment by garyleefight** [comment]
It's possible to deploy specific branch with one-click deploy right now.
https://github.com/${repository}/tree/${branchname} 
You can define the branch name in the repository url like above. But note that, we do not support deploy branch contains '/'
