### ISSUE TITLE
Allow Cloudfront to serve GZIP bundle?

### ISSUE THREAD

**Issue by rallona** [aws-amplify/amplify-console#330]
I have a question, I am using AWS AMPLIFY CONSOLE to run a React App

My app is built and running very well, but the main .js bundle size is 1,3MB. Too high!!

I want to reduce the bundle size, but I don't know how to force to serve only the .js.gz (gzipped version of the bundle) instead of the plain js version.

Its possible to get this in AWS Amplify Console?

Thanks in advance,

**Comment by kahdojay** [comment]
@rallona Are you hosting using CloudFront? If so, I believe we configure distributions to serve compressed assets, so it should just happen [as long as clients are passing the correct `Accept-Encoding` header.](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html). If 

Can you share the url for your app?

**Comment by rallona** [comment]
I use the Amplify Console. I cant change or choose any parameter like I can do it in CloudFront

**Comment by kahdojay** [comment]
@rallona can you share your app ARN, and the endpoint you're using to access your app?

**Comment by Tporkka** [comment]
I'm having the same issue and trying to reduce my bundle size. Is serving gzipped bundles possible with Amplify?

**Comment by bishonbopanna** [comment]
Same issue. +1
Can some one from Amplify team answer this ?

**Comment by YajJackson** [comment]
@swaminator why was this issue closed? What is the recommendation for Amplify users who want to use content-encoding?

**Comment by alacret** [comment]
Having this same problem

**Comment by zanio** [comment]
I am having the same problem

**Comment by s4geraldyeong** [comment]
Hey all, I'm not from the amplify team, but there is thing call performance mode. 

https://docs.aws.amazon.com/amplify/latest/userguide/ttl.html#Instant-cache-invalidation-with-instant-deploys

**Comment by delfu** [comment]
same problem

**Comment by cacharrin** [comment]
We have many sites running on Amplify, some of them are serving gzip files but some of them no. How to enable gzip for every amplify site?
