### ISSUE TITLE
Unable to select production backend environment on amplify console

### ISSUE THREAD

**Issue by zulhilmi-zolkfli** [aws-amplify/amplify-console#334]
Background:

- Build from github to amplify console
- Using PR Preview on github
- Connecting production backend environment to the master branch 

Current behavior:

- Pull request is merged into master branch but failed to build because the settings was set to PR environment from master branch
- I tried to change the settings on amplify console by wanting to select the production environment but the production environment is not listed on the settings even the production environment information is at team-provider-info.json on master branch
- The build worked well during last merge on 28th November but it failed today, 23rd December

Expected behavior:
Able to select production backend environment from the list

<img width="603" alt="Screen Shot 2019-12-23 at 13 22 11" src="https://user-images.githubusercontent.com/37945633/71335684-4401c200-2587-11ea-9581-cb82c34053bc.png">

**Comment by lightsofapollo** [comment]
I hit this too :(

**Comment by Joycehao19** [comment]
Hi, Thank you for reporting! we cut a ticket in our team backlog. We will investigate a fix.

**Comment by nimacks** [comment]
We've made a number of bug fixes to this feature. Verify if this is still happening.
