### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by bsithub** [aws-amplify/amplify-console#335]
**App Id**: d156rr84lt9kay
**Region**: ap-south-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by kahdojay** [comment]
Hi @bsithub if you can fill out the requested fields it will help us help you.

**Comment by bsithub** [comment]
> Hi @bsithub if you can fill out the requested fields it will help us help you.

Resolved- Issue

Deleted Domain From AWS Amplify Console and Re-Create and Configured Goddady CNAME Records - Now it's working.
