### ISSUE TITLE
How to access environment variables in webpack for react app deployed in amplify

### ISSUE THREAD

**Issue by GWSzeto** [aws-amplify/amplify-console#336]
Hey I am incredibly new to AWS amplify and I just got it up and going recently with my app deployed on amplify. The way I currently have it set up is that I have a .env file on my local machine and in my webpack.config.js file, I would access the environment variables from dotenv and then throw it in to the plugins like so
```Javascript
const path = require('path');
const webpack = require('webpack');
const HtmlWebPackPlugin = require("html-webpack-plugin");
const CopyWebPackPlugin = require('copy-webpack-plugin');
const dotenv = require('dotenv');
const fs = require('fs');

module.exports = env => {
  console.log("env: ", env)
  const currentPath = path.join(__dirname);
  const basePath = currentPath + '/.env';
  const envPath = env && env.ENVIRONMENT ? basePath + env.ENVIRONMENT : basePath;
  const finalPath = fs.existsSync(envPath) ? envPath : basePath;
  const fileEnv = dotenv.config({ path: finalPath }).parsed;
  const envKeys = fileEnv ? Object.keys(fileEnv).reduce((prev, next) => {
    prev[`process.env.${next}`] = JSON.stringify(fileEnv[next]);

    return prev;
  }, {}) : {};

  return {
    // code omitted to see the main issue here
    plugins: [
      new HtmlWebPackPlugin({
        template: "./src/index.html",
        filename: "./index.html"
      }),
      new webpack.DefinePlugin(envKeys),
      new CopyWebPackPlugin([
        { from: "images", to: "images"}
      ])
    ]
  }
}
```

I set up the environment variables in the aws amplify console, but I can only access them during the build time. How would I set it up so that I can access the environment variables in my webpack?

**Comment by Taieb** [comment]
I am using dotenv-webpack which gets my env variables from my local .env file.
I also added env variables in the amplify console !
But I still can't access/use env variables .

Thanks !

**Comment by Taieb** [comment]
I just set webpack EnvironmentPlugin and it works for me.

**Comment by swaminator** [comment]
@Taieb can you provide more steps to help out @GWSzeto? Thanks again for your contribution!

**Comment by anatonie** [comment]
Hi @Taieb 

Do you have the **systemvars** property set to true in your webpack-dotenv config?

```systemvars (false) - Set to true if you would rather load all system variables as well (useful for CI purposes).```
[From the properties section of the webpack-dotenv README](https://github.com/mrsteele/dotenv-webpack/blob/master/README.md#properties)

**Comment by anatonie** [comment]
Hi @GWSzeto 

How are you attempting to access the environment variables in your webpack? I don't see any reference to ```process.env``` in the snippet you posted.

Also, can you please give a bit more detail on the distinction between build time (where you can access the variables) and in your webpack (where you can't)? 

Much appreciated!

**Comment by Taieb** [comment]
Actually, if you are using webpack without amplify (I mean in your local machine or in your hosting server) you can create .env file and put in your env variables then you need dotenv webpack module to provide this variable. https://www.npmjs.com/package/dotenv-webpack
In case of using Amazon amplify, you dont need the .env file, you need to add your env variables through Amplify and set up webpack EnvironmentPlugin
https://webpack.js.org/plugins/environment-plugin/

**Comment by GWSzeto** [comment]
Hey, sorry for the late replies. I just did what @Taieb said and it worked perfectly! I just set up my webpack plugins as so

```javascript
    plugins: [
      new HtmlWebPackPlugin({
        template: "./src/index.html",
        filename: "./index.html"
      }),
      new CopyWebPackPlugin([
        { from: "assets", to: "assets"}
      ]),
      new Dotenv({
        path: finalPath,
      }),
      new webpack.EnvironmentPlugin([
         ...
      ]),
    ],
```

**Comment by LucasAndrad** [comment]
@Taieb comment would be a nice complement to the docs.

**Comment by Naes0** [comment]
Hi, @Taieb @GWSzeto 
Could you guys clarify how you setup your env variables in amplify?
I've set them up in the console and tried to add them in the amplify.yml file but it can't seem to find them.

**webpack.config.js**
 ```
 new webpack.EnvironmentPlugin({
      'IMPORT_MAP_DOMAIN': JSON.stringify(IMPORT_MAP_DOMAIN)
    })
```
**amplify.yml**
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - IMPORT_MAP_DOMAIN=$IMPORT_MAP_DOMAIN
        - npm run build
```

**Comment by lifeofdave** [comment]
@Naes0 To get this working I had to wrap the AWS environment variable names in curly braces:

**webpack.config.js**
```
plugins: [
     ...
    new webpack.EnvironmentPlugin(['VARIABLE_NAME_1']),
  ],
```

**amplify.yml**
```
build:
  commands:
    - npm run build
    - VARIABLE_NAME_1=${VARIABLE_NAME_1}
```
