### ISSUE TITLE
Rewrite rule for sub domains to sub directory

### ISSUE THREAD

**Issue by arihantsol** [aws-amplify/amplify-console#337]
I have setup React SPA CRA apps
Need help in configuring on AWS amplify
Apps are using wildcard sub domains. Each user will have its own vanity url to access different apps 
1) Auth Module
https://xxx.example.com/auth
- Above url is used to login and select which app he/she wants to access
2) Consumer Module
https://xxx.example.com/consumer/
3) Sales Module
https://xxx.example.com/sales/
4) Other Module
https://xxx.example.com/other/

Need help in configuring such app. I tried creating different apps on AWS Amplify using same repo for each module app. I didn’t got any success in redirecting.

Any help would be appreciate

Thanks

**Comment by Joycehao19** [comment]
Hi @arihantsol , to make sure your question. Do you want to:
Source: https://xxx.example.com/auth/<*>  
Target: /auth/<*>
status: 301

Then all request will be redirected to /auth/<*>
ref:https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html
