### ISSUE TITLE
Amplify Console - Build Failing - BackendEnvironment already exist

### ISSUE THREAD

**Issue by RobotCharlie** [aws-amplify/amplify-console#340]
**Describe the bug**
After I made updates to my amplify project. I did `amplify push` and after the command succeeded, I pushed my code to the repo, which kicks off a build, but the build keeps failing on the amplify console which says the the `BackendEnvironment feature already exist`. (I was pushing my feature branch, which already has a feature backend env created and I have already built successfully on this backend for dozens of builds).

**To Reproduce**
1. Make update to my code.
2. Do `amplify status` and it show there are categories `Updated`
3. Do `amplify push` and wait util it secceeded.
5. Push the code to repo (GitHub)
6. The Build failed and the log is attached 
 - as you can see the line 7 already said it found the env feature and at line 11 it want to add the env again

**Expected behavior**
The build command should not think that I am creating a new backend environment after I push the code. However, it should just update the existing one.

**Screenshots**
Build Log:
<img width="1312" alt="Screen Shot 2019-12-25 at 8 57 24 PM" src="https://user-images.githubusercontent.com/10777112/71453572-d9ed4680-2759-11ea-8960-001b00534954.png">

**Additional context**
versions:
- "aws-amplify": "^2.1.0",
- amplify cli `4.8.0`

categories used:
- Auth
- Api (GraphQL)
- DataSource (S3)
- Function (Lambda)

**Comment by RobotCharlie** [comment]
@jordanranz Thanks!

**Comment by swaminator** [comment]
@RobotCharlie can you try 4.10? This was fixed.

**Comment by RobotCharlie** [comment]
@swaminator Thanks! Sure, I will try it tomorrow! I will let you know.

**Comment by RobotCharlie** [comment]
@swaminator I have verified the 4.10.0 fixed the issue. Thanks!
