### ISSUE TITLE
Not able to connect to the DNS after setting up custom domain

### ISSUE THREAD

**Issue by ojassinha** [aws-amplify/amplify-console#345]
**App Id**:d2nxsn1faxo9t7
**Region**: us-east-1
**Step**: custom domain
**Status**: Blank hits (unreachable)

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I have setup the GoDaddy hosting for my amplify app. My amplify app is connected to a simple React github repository and working fine for the amplify.com URL but when I connected to GoDaddy via CNAME for subdomain and pointed that to the amplify.com URL, the subdomain url is not working anymore.

abc.xyz.com/ is returning the empty unreachable blank. Browser is not able to load any data.

Should I be doing the configuration of pointing the subdomain to xxxx.cloudfront.net ?

**Error message**
Browser does not load with ERR_CONNECTION_TIMED_OUT

**Comment by AZOM** [comment]
I am experiencing a similar issue. Have a DNS CNAME record on Cloudflare that throws HTTP 404 - but in the Amplify console everything looks fine and I doubled checked that both CNAME under "View DNS records" are set properly on Cloudlfare.

**Comment by beeembeeem** [comment]
ANY FIX???

**Comment by ganipcanot** [comment]
Hi @ojassinha, I tried navigating to your domain at "pulse-staging.optacity.com" and it seems to load correctly.  Are you still experiencing an issue?

**Comment by Athena96** [comment]
Closing this issue, please feel free to reopen if you are still having trouble.

**Comment by lopezdp** [comment]
> **App Id**:d2nxsn1faxo9t7
> **Region**: us-east-1
> **Step**: custom domain
> **Status**: Blank hits (unreachable)
> 
> > **Note**: Do not include information that is sensitive in nature such as your domain name, company etc.
> 
> **Issue/question**
> I have setup the GoDaddy hosting for my amplify app. My amplify app is connected to a simple React github repository and working fine for the amplify.com URL but when I connected to GoDaddy via CNAME for subdomain and pointed that to the amplify.com URL, the subdomain url is not working anymore.
> 
> abc.xyz.com/ is returning the empty unreachable blank. Browser is not able to load any data.
> 
> Should I be doing the configuration of pointing the subdomain to xxxx.cloudfront.net ?
> 
> **Error message**
> Browser does not load with ERR_CONNECTION_TIMED_OUT

@ojassinha were you able to figure this one out?

**Comment by mordechaim** [comment]
I'm having the same issue. How did you fix this?
