### ISSUE TITLE
Custom Google Domain fails even with documented steps completed

### ISSUE THREAD

**Issue by laurachevalier4** [aws-amplify/amplify-console#348]
**App Id**: d1yqog4tmthcsh
**Region**: us-east-1
**Step**: SSL Configuration
**Status**: Running

**Issue/question**
I have a domain configured in Google Domains which I am trying to use for my Amplify app. The amplify URL and ACM certificate records are configured within Google Domain's DNS view, but the app is failing to get past SSL configuration. Thinking this was a problem with Google's domain management, I reached out to them about the issue but got this response:

> However, the reason why you get the 403 Error is because you have to manage and configure something on your web host provider's end. I suggest that you get in touch with them and contact them about the settings of the domain on their end and let them know that you have done the settings on Google Domains' end

I tried several things I found online from others' struggles, to no avail. Among them:
* Creating a hosted zone in route53 for my Google Domain, and switching the nameservers in Google Domain to those created within the hosted zone
* Tried to find a cloudfront URL associated to my app so that I might add this to the DNS record set in Google Domain, but there isn't one for this app in cloudfront, I only have my amplifyapp url found in the Amplify management console
  * relevant [thread](https://forums.aws.amazon.com/thread.jspa?messageID=911455#911455)

**Error message**
"We could not validate the CNAME record exists in your DNS file. Add the following record in your DNS provider to route all the traffic to your domain and try again... "
and a 403 error when I try to access my domain directly.

The first time I saw this error, I didn't have the validation server record in Google Domain's DNS record set, but after I added it, I retried several times within Amplify console, and each time it would just hang on retry (at least in the UI). When I refreshed and returned to the page, I would see a failure status and that same error message. Not sure whether this is a UI error (doubtful, because I did give it more than a day to retry before retrying again, after adding the certification record to Google Domain), or maybe an issue with the retry logic altogether, or something I've missed in my configuration in Google Domain.

**Additional information**
Documentation I followed:
* https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html
* https://docs.aws.amazon.com/amplify/latest/userguide/howto-third-party-domains.html

Before I tried adding AWS nameservers, and while I was getting an error on SSL configuration, I was able to confirm here https://www.whatsmydns.net/#CNAME/ that my custom domain WAS resolving to the aws app correctly, and yet I got a 403 error when trying to go directly to that custom url (the amplify app was accessible).

My latest action has been to delete the hosted zone in Route53, and the custom domain in Amplify, and to recreate it; the acm validation record it generated the second time around is the same as before, so I am just waiting for it to recognize that this is configured in Google Domain. Even if this works, the process has felt buggy and unclear -- perhaps the documentation can be updated to reflect the resolution here... if we reach one :)

**Comment by laurachevalier4** [comment]
Update: it's still hanging on SSL configuration after >24 hours

**Comment by laurachevalier4** [comment]
Oh yay, for a while I would click "View DNS records" and there would be nulls where there should have been Cloudfront URLs, but now there are Cloudfront URLs. Going to try adding these as DNS records to Google Domain and see if that does it... Should that be blocking SSL configuration, in any case?

**Comment by laurachevalier4** [comment]
Still stuck on SSL configuration. Any insight here? I'm not able to add subdomain forwarding through Google Domain to the Cloudfront URL because I get an error that `The SSL Certificate for this domain hasn't been created yet`

**Comment by laurachevalier4** [comment]
Also I'm getting mixed messages about what CNAME record to add for the validation certificate; the console tells me to add:
`_2e19bxxxxxxxxxxx.studentwellness.cc. CNAME _0e52cxxxx.acm-validations.aws.`
but "View DNS Records" displays:
`_2e19bxxxxxxxxxxx CNAME _0e52cxxxx.acm-validations.aws.`

Does it make a difference which of these I use?

**Comment by laurachevalier4** [comment]
Ok, I resolved this:
* The validation cert DNS record was not set to the correct value
* Cloudfront records did not need to be added in Google Domain
* Synthetic records did not need to be added in Google Domain

These issues would have been avoided had the validation cert been set up correctly initially, so my main suggestions coming out of this are:
1) Set SSL configuration timeouts with error messages
2) Add troubleshooting documentation for SSL configuration issues 
  - e.g. what might it mean if the DNS resolves as expected but I still get a 403 error when accessing the domain

**Comment by swaminator** [comment]
@laurachevalier4 thank you so much for providing your solution. Would you be willing to get on a call sometime? We'd like to learn more about where exactly you got stuck.  Would you be open to chatting? I can setup a screenshare and you can walk us through your settings. Please email aws-amplify-customer@amazon.com with your availability. Thanks!

**Comment by conorhalloran** [comment]
Experiencing same issue here. Still not clear which format the CNAME record to point to the AWS Certificate Manager (ACM) validation server should be in. The [docs to add a custom domain](https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-google-domains.html) suggest to not have your custom domain in the name field, where as the Amplify Domain Management explicitly states for it to be present.

@laurachevalier4 - can you please confirm which of the validation cert DNS records you used? 
Option 1. Without your custom domain in the name field:
Name: _**********************.
CNAME 
Data: _********************.**************.acm-validations.aws.

or

Option 2. With your custom domain in the name field: 
Name: _**********************.yourcustomdomain.com.
CNAME 
Data: _********************.**************.acm-validations.aws.

I've had it set at **Option One** for more than 48 hours with no certification and then set it at **Option Two** for more than 24 hours with no certification. @swaminator - sent two emails to aws-amplify-customer@amazon.com over the past four days and no response.

Thank you.
