### ISSUE TITLE
Is streaming media from S3 to an Amplify app free?

### ISSUE THREAD

**Issue by NL33** [aws-amplify/amplify-console#349]
** Please describe which feature you have a question about? **

This question is focused on an app hosted through Amplify.

I am trying to understand how AWS costs can be incurred for streaming media with such an app.

I plan to store audio files on S3. On my Amplify app, I will call these files with the html audio player, like:
```
let audio = new Audio('S3audiourl.mp3')
audio.play()
```
**When a user plays this audio, how will it be charged?**

** Provide additional details**

S3 charges for data transfer, but there is no charge for transferring data to an [EC2 instance in the same region](https://aws.amazon.com/s3/pricing/).

I assume that this also applies to apps hosted on Amplify in the same region. So that if my Amplify app streams audio from S3, there is no charge for that data transfer.

**But, are there other charges for that streaming?** For example, does Amplify consider the audio being streamed to be part of the data that Amplify serves?

I understand that S3 charges for storing data ($.023 per GB stored), and can charge for API requests.

I also understand that Amplify charges for builds ($.01 per minute of the build process), data stored ($.023 per GB), and data served ($.15 per GB).

But what about data streamed from S3 to a user using an Amplify-hosted app?

**Comment by swaminator** [comment]
You should only be paying for the GB served via the Amplify Hosting distribution to the end user browser. We're using CloudFront under-the-hood so there won't be any internal data transfer.
