### ISSUE TITLE
Breaking change in mochawesome-merge affects cypress test step

### ISSUE THREAD

**Issue by patleeman** [aws-amplify/amplify-console#352]
** Please describe which feature you have a question about? **
E2E testing with Cypress.

[Link to guide provided by Amplify Team](https://aws.amazon.com/blogs/mobile/run-end-to-end-cypress-tests-for-your-fullstack-ci-cd-deployment-with-amplify-console/)

** Provide additional details**
Error received when attempting to merge mocha reports generated by Cypress.

```
ERROR: Failed to merge reports
Error: Pattern --reportDir matched no report files
```

In the guide linked above the command `npx mochawesome-merge --reportDir cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json` doesn't work after a [breaking change to mochawesome-merge](https://github.com/Antontelesh/mochawesome-merge/commit/5488967ec193cbe4bcffcf5dad01696ae2e1c321). 

The fix is to omit `--reportDir` or to pin the version of mochawesome-merge to 3.0.0.

```
npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
```

Possibly related to:
#347

**Comment by swaminator** [comment]
@patleeman thanks for reporting this. We are actively working on solving this.

**Comment by cslogan-red** [comment]
Thanks for the update @patleeman , an update has been provided in #115 , fix is pending release.

**Comment by swaminator** [comment]
Closing. Please reopen if it is not fixed.

**Comment by afsaneGhafouri** [comment]
@patleeman I guess they dropped the `--reportDir` in version 4. I've checked the documentation and found this:
https://github.com/Antontelesh/mochawesome-merge#cli-1

**Comment by patleeman** [comment]
@afsaneGhafouri Yeah, they removed it in [this commit](https://github.com/Antontelesh/mochawesome-merge/commit/5488967ec193cbe4bcffcf5dad01696ae2e1c321)
