### ISSUE TITLE
Too Many Redirects when deploying Hugo site

### ISSUE THREAD

**Issue by ajlanghorn** [aws-amplify/amplify-console#353]
I have a Hugo site deployed in to AWS Amplify Console. So far, so good. Locally, the site works when I run `hugo build && hugo serve`, and static files are output to the public/ directory.

When I connect Amplify up to the Git repository, and the project is built, then I end up with a Too Many Redirects error from both the Amplify-provided and custom URLs attached to the project. cURL suggests that when I visit the custom URL, I'm being 302'd by CloudFront to /index.html, where I am then 302d to index.html. So, at least now, I can see where my redirect issue stems from.

In Redirects and Rewrites, I only have one set up - the default:

`
</*> index.html 404 (Redirect)
`

Why I get 302'd when the redirect is a 404 confuses me, too.

Any ideas? The app ID is d2j3luelrf0js9.

**Comment by swaminator** [comment]
Please refer to https://github.com/aws-amplify/amplify-console/issues/28#issuecomment-545271048

**Comment by ajlanghorn** [comment]
> Please refer to [#28 (comment)](https://github.com/aws-amplify/amplify-console/issues/28#issuecomment-545271048)

The build directory is set to `public` (but I've also set it to `public/` to trial that, to no avail). When I run `hugo` locally, without a `public` directory, one gets created and my site is built in to it. So, I'm fairly confident that's the right directory.

The comment in #28 you refer to isn't directly related here, I don't think - the user there is using a completely different build system with a different runtime.

**Comment by swaminator** [comment]
@ajlanghorn whats your `baseDirectory`?

**Comment by ajlanghorn** [comment]
> @ajlanghorn whats your `baseDirectory`?
@swaminator

In the Build Settings in the Amplify console, it's set to:

```
version: 0.1
frontend:
  phases:
    build:
      commands:
        - hugo
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths: []
```

Locally, if I run `hugo build` from the root of the repository, then the base directory (as in, where my static files are generated in to) becomes `public`, too. I think that's set up correctly...

**Comment by ajlanghorn** [comment]
In the end, I resolved this by stopping using the theme Hugo is using as a Git submodule, and instead brought the files within under the control of the repository. This was a bit trial and error to get to this stage, and it doesn't make much sense to me why this worked, but... it did.

Closing off.

**Comment by kieran9176** [comment]
@ajlanghorn mind elaborating on your solution a bit? I'm having the same issue.
