### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by nozen** [aws-amplify/amplify-console#358]
**App Id**: d162vsf9m8tb5j
**Region**: ap-southeast-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Used the default settings to create the custom domain in amplify.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by Joycehao19** [comment]
Hi @nozen 

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

These guides are helpful for getting started with custom domains, for existing domains there are number of steps that will need to be completed (as outlined in the docs above) depending on your current hosting and DNS providers.

A CNAME alias (domain) can only be used with a single CloudFront distribution at a time, if you receive this error then the domain is already associated with another CF distribution (either in the same AWS account, or potentially in a different account) and must be moved to the distribution created for you by Amplify Console before it will work, the docs help outline how to do this (and you may need to check more than one account if you or your organization owns multiple accounts)

**Comment by nozen** [comment]
Hi @Joycehao19,

I did find the problem after all, wasn't amplify, had to track down the issue.

Thank you.
