### ISSUE TITLE
Bug - Cannot select existing environment for previews

### ISSUE THREAD

**Issue by lightsofapollo** [aws-amplify/amplify-console#363]
Hello!

I noticed an issue where my preview builds were creating new backend environments unsuccessfully. I was confused as I had thought I configured to use an existing env only. Below is what at least looks like a bug where the setting is not persisted. 

![amplify-bug-gif](https://user-images.githubusercontent.com/322957/72457990-fa228b00-3784-11ea-8fc4-205696998c46.gif)

I am not sure what else would be relevant but happy to post additional information.

**Comment by Joycehao19** [comment]
Hi @lightsofapollo , sorry that you are having this issue. we are currently investigating it.

**Comment by Joycehao19** [comment]
Hello, we released a fix of the bug. Feel free to reopen if you still see the bug
