### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Bryan-Rojas** [aws-amplify/amplify-console#368]
**App Id**: d36xj5vdib794g
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I have no idea how to resolve this issue. I'm hoping for some guidance or perhaps some troubleshooting guides on this issue.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

Edit: This site has previosuly was using AWS for hosting. Could this be an issue?

**Comment by cslogan-red** [comment]
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

These guides are helpful for getting started with custom domains, for existing domains there are number of steps that will need to be completed (as outlined in the docs above) depending on your current hosting and DNS providers.

A CNAME alias (domain) can only be used with a single CloudFront distribution at a time, if you receive this error then the domain is already associated with another CF distribution (either in the same AWS account, or potentially in a different account) and must be moved to the distribution created for you by Amplify Console before it will work, the docs help outline how to do this (and you may need to check more than one account if you or your organization owns multiple accounts)

**Comment by Bryan-Rojas** [comment]
@cslogan-red Thanks for the trouble shooting guides. So apparently the site was previously hosted on a different CloudFront distribution but I don't have access to this old account. How should I proceed with this scenario? I own the domain now btw.

**Comment by cslogan-red** [comment]
Hi @Bryan-Rojas no problem, AWS supports transferring the CNAME to another distribution, even between accounts. In the first link provided above, there are some steps to take with your DNS provider, and then a link is provided to create a case with AWS support at the bottom, they will need to validate ownership of your domain and should be able to assist in removing the CNAME from the old account's distribution.

**Comment by Bryan-Rojas** [comment]
Thank you @cslogan-red for the information! I contacted "aws-amplify-customer@amazon.com" and I'm awaiting a response.

**Comment by cslogan-red** [comment]
Hi @Bryan-Rojas - we've since moved that Amplify support alias to this issues tracker :)

https://console.aws.amazon.com/support/cases#/create

If you submit a support case there and explain you're trying to remove a CNAME for domain you own from a CF distribution in another AWS account that you can't access, they'll get it to the CloudFront team to help you out, as we do not have access to do that sort of thing on your behalf, thanks!

**Comment by Bryan-Rojas** [comment]
What if I'm enrolled under the "basic" support plan as a student @cslogan-red ? I can't seem to submit technical support cases without upgrading my plan.

**Comment by cslogan-red** [comment]
Hi @Bryan-Rojas , you can use the same above support URL to create an "Account and billing support" case about ownership transfer with the free basic plan, additionally, you can try posting directly on the CloudFront AWS Forums, but as this is really an issue with accessing resources in a non-owned AWS account, I would start with the case.

**Comment by Bryan-Rojas** [comment]
Closed. Thanks for your help by the way @cslogan-red 

For anyone facing this issue:

- I contacted AWS support and they helped me out but the process with a little slow to which I just decided to use Cloudflare DNS instead. 

Definitely check out: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html
