### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by aprabhakar90** [aws-amplify/amplify-console#369]
**App Id**: d3hrm7k8egypi9
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by cslogan-red** [comment]
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

These guides are helpful for getting started with custom domains, for existing domains there are number of steps that will need to be completed (as outlined in the docs above) depending on your current hosting and DNS providers.

A CNAME alias (domain) can only be used with a single CloudFront distribution at a time, if you receive this error then the domain is already associated with another CF distribution (either in the same AWS account, or potentially in a **different** account) and must be moved to the distribution created for you by Amplify Console before it will work, the docs help outline how to do this (and you may need to check more than one account if you or your organization owns multiple accounts)

**Comment by aprabhakar90** [comment]
Sorry again for the delay in responding. I have checked this AWS account as well as other AWS accounts and none of them have the CNAME in any CloudFront distribution. This is starting to become an urgent issue as this is going to be our public facing company website soon and we would like this issue resolved as soon as possible. I know my delay in responding doesn't help move this along and I sincerely apologize. Please help!!! Thanks.

**Comment by Joycehao19** [comment]
@aprabhakar90  What is the error message that you get?

**Comment by aprabhakar90** [comment]
@Joycehao19 Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by Joycehao19** [comment]
@aprabhakar90 Hi, It seems like your custom domain associated with other distribution. Could you double check you and your team account? 
Another question is: did you connect this domain to any CF distributions before?

**Comment by aprabhakar90** [comment]
@Joycehao19 I created an aws amplify app with this domain name for a demo 9 months back on another account and that worked fine. But I deleted the app since and moved it to this account. I checked the CF distributions on both accounts and no distributions exist.

**Comment by Joycehao19** [comment]
@aprabhakar90 can you send an email to us <aws-amplify-customer@amazon.com>

**Comment by aprabhakar90** [comment]
@Joycehao19 Thank you for your response. I actually opted in for amazon support and am currently working with a representative in resolving the issue. Thank you very much for your help!
