### ISSUE TITLE
Domain activation is Failed - subdomain but not root domain

### ISSUE THREAD

**Issue by ardation** [aws-amplify/amplify-console#370]
**App Id**: dxaejndypzj8d
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Wondering if this is being caused by not including the root domain.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by Joycehao19** [comment]
Hi @ardation , to make sure your question. Did you mean that you own www.example.com, and you add abc.example.com? If it is, we recommend you enter your root domain in domain management page.

ref: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html

**Comment by ardation** [comment]
@Joycehao19 the issue is that we already run a site on the root domain. I think the problem was that the subdomain I was using already had a CloudFront distribution. I have since deleted that but no luck as 24 hours later it is still not working.

**Comment by Joycehao19** [comment]
@ardation Sorry that you are having this issue. I will recommend you to take a look of this link if you haven't seen before: https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/. 

If you still have CNAME issue,  you could submit a support case (link: https://console.aws.amazon.com/support/cases#/create) and explain you're trying to remove a CNAME for domain you own from a CF distribution. They'll get it to the CloudFront team to help you out, as we do not have access to do that sort of thing on your behalf, thanks!
