### ISSUE TITLE
SSL verification is Running - verification has taken longer than 8 hours

### ISSUE THREAD

**Issue by bmosoane** [aws-amplify/amplify-console#371]
**App Id**: d2dbjdmx65kh6v
**Region**: eu-west-1
**Step**: SSL verification
**Status**: Running

Verification of ownership my domain has taken longer than 8 hours.

**Comment by Joycehao19** [comment]
Hi @bmosoane , It seems like your app is working now. If you have further question with related to custom domain, please let us know.

**Comment by Joycehao19** [comment]
Hi @bmosoane , did your custom domain work now?
