### ISSUE TITLE
Deployment process does not finish "Provision" step

### ISSUE THREAD

**Issue by TLaue** [aws-amplify/amplify-console#376]
Since this morning I am facing a very strange problem. I am pushing code to CodeCommit but the connected Amplify Console branches do not run anymore. All of them keep pending in the "Provision" step for hours. There seems to be no process at all:

![Screenshot from 2020-01-21 14-03-33](https://user-images.githubusercontent.com/36646404/72807114-f5fbdf00-3c56-11ea-80f0-56243066171c.png)

I have even created a new CodeCommit repository and a new Amplify Console app with ID "doqnjn36rcxp7" - but no success. I would be very thankful if someone could point me to a possible reason fo this problem. 

Thank you very much in advance.

**Comment by swaminator** [comment]
@TLaue we are investigating this with priority

**Comment by Joycehao19** [comment]
Hi @TLaue  , did you try re-deploying your app? Would you mind to provide the region as well?

**Comment by TLaue** [comment]
Hello @Joycehao19, I am working in "eu-central-1". I have tried to re-deploy the app serveral times as the problem happened for different branches and on different apps. I cancelled the deployments several times and tried to re-deploy them but all pipelines kept running the provision step forever.

**Comment by Joycehao19** [comment]
@TLaue Sorry that you are facing this issue. Did you delete your app? Would you mind to connect and deploy it again? Thank you!

**Comment by TLaue** [comment]
@Joycehao19: I have just deleted the app and created a new one for the same CodeCommit branch but the result is the same. It is still not progressing. New appID; d26clkjd3gqprk

**Comment by TLaue** [comment]
@Joycehao19: as additional info: the same project runs successfully in another account. It seems that the problem is somehow related to this specific AWS account. I have just created a new default React project using create-react-app (without any amplify integration), pushed the code to a new codecommit repo and created a new Amplify Console app. Unfortunatelly, the result is still the same. The provision step do not finish.

**Comment by Joycehao19** [comment]
@TLaue Thank you for your additional info. I can't reproduce this issue. I did the same thing, create a default react project --> push to codecommit --> create a new Amplify Console app. It worked fine on my console. I think this is a known issue for us that the build getting periodically stuck in provisioning. We are still investigating a fix. Can you double check if the aws account you use has codecommit permission? (IAM-Users-Permissions-Add permissions -> add AWSCodeCommitFullAccess)

**Comment by TLaue** [comment]
@Joycehao19 The service role used by Amplify Console has administrator access permissons and the role used by my account user has power user permissons (we are accessing this account by an assumed role from another account). However I am assuming that this is not the reason of this problem as the same project works without any problems in another account whose assumed role has only read only permissons. 

I have just tried to deploy one of the full stack example applications provided by Amplify. No success. Are there any logs available which might get an indication what might be causing this problem? The strange this is that everything was working correctly till two days ago (until everything stopped suddenly in the provision step).

**Comment by JoshuaTruscott** [comment]
I'm also having this issue. No changes made to permissions made, yesterday was deploying fine.

**Comment by swaminator** [comment]
@JoshuaTruscott what region is your app in

**Comment by TLaue** [comment]
@Joycehao19 I have just switched to another region (eu-west-1) to check if the amplify console app is running correctly there. No problem. This issue is in our case only related to (eu-central-1). Any ideas how to solve it?

**Comment by Joycehao19** [comment]
@TLaue We are investigating this issue now. We will response as soon as we figure it out.

**Comment by TLaue** [comment]
@Joycehao19 There is another app (det3qgey9p43n) showing the same problem in the same region.

**Comment by Joycehao19** [comment]
@TLaue Could you please add AWSCodeCommitFullAccess permission and try again?  (Console:IAM-Users-Permissions-Add permissions -> add AWSCodeCommitFullAccess)

**Comment by TLaue** [comment]
@Joycehao19 I will try tomorrow as I do not have the necessary permissions to upgrade my IAM permssions at the moment. Is the arn:aws:iam::aws:policy/PowerUserAccess policy not powerfull enough to run Amplify console?

**Comment by Joycehao19** [comment]
@TLaue Hi, could you please try to create a new app again without set AWSCodeCommitFullAccess permission?

**Comment by TLaue** [comment]
@Joycehao19 Everything is working again - without any permission changes or any other action conducted by myself. I do not know what you have done respectively what was the solution to this problem but thank you very much for your support!
