### ISSUE TITLE
[bug] Amplify Console Dark Mode bug

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-console#384]
![image](https://user-images.githubusercontent.com/6764957/73022394-8709bc00-3df7-11ea-8438-697a33db08a2.png)

my path: https://console.aws.amazon.com/amplify/home?region=us-east-1&code=564f27153040679132a4#/dsw4gfc33xhg7/create/addfrontend/github

**Comment by ganipcanot** [comment]
Just curious @sw-yx if you are using a specific browser?  I tried this in Chrome and Firefox and it seems to toggle between Light and Dark just fine.

**Comment by sw-yx** [comment]
chrome. oh dear i didnt really specify what the bug was did i? Just the white-on-grey "light/dark" text up on the top right.

**Comment by ganipcanot** [comment]
@sw-yx Thanks for the additional info!  I just tried on chrome incognito and wasn't able to repro:

![lightvsDark](https://user-images.githubusercontent.com/21091073/73790907-2a42c580-4756-11ea-8503-3e27a7d18c3b.gif)

Maybe you have some custom settings/browser add-ons affecting the text color?

**Comment by sw-yx** [comment]
mmh. yeah my browser has been VERY funky around aws in general. no idea whats going on. thanks for confirming.
