### ISSUE TITLE
Getting "Page Redirected too many times" error

### ISSUE THREAD

**Issue by gvnttdata** [aws-amplify/amplify-console#385]
**App Id**: dnqx9fxprg7z7  
**Region**: us-east-2
**Step**:  Complete
**Status**: Getting "Page redirected too many times" error

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.
I am getting all green check-marks when I deploy but when I go to the url listed in my amplify console I get "This page isn’t working <site address> redirected you too many times."

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 
"This page isn’t working <site address> redirected you too many times."

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
I am trying to host a Nuxt Universal App and am using .nuxt as the baseDirectory 

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by gvnttdata** [comment]
Not sure if it matters but when I look at the Network tab the redirects are giving a 302 code.

**Comment by kahdojay** [comment]
@gvnttdata can you share a copy your build settings (minus any sensitive data)? (From amplify.yml if you're using it, or from the console). Also can you confirm what redirects your app has in place?

**Comment by Joycehao19** [comment]
Hi, @gvnttdata did you still have this issue?

**Comment by TXMack713** [comment]
I'm also getting the too many redirects message and when I checked, the status code given is 302. I've created and modified the app exactly as directed in the tutorial and have also tried checking the link on Chrome, Brave, Firefox and MS Edge and all the browsers have given me this error.

**Comment by Athena96** [comment]
@TXMack713 can you share a copy your build settings (minus any sensitive data)? (From amplify.yml if you're using it, or from the console). 
Can you also share what redirects your app has in place?

**Comment by rolandoesc** [comment]
I'm facing the same issue, here's my amplify.yml

`version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory:  /
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*`

**Comment by Joycehao19** [comment]
Hi @rolandoesc  , thank you for sharing amplify.yml and package.json. Could you also share what redirects your app has in place?

**Comment by Athena96** [comment]
Closing this ticket, please re-open if you are still facing issues
