### ISSUE TITLE
Adding multiple subdomains hangs amplify console

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-console#386]
We have an application that is deployed with some customization based on the url (subdomain).

We have successfully deployed an app with an initial url.

When we add additional subdomains using domain management, the console hangs after clicking on "Update". It appears to be working but the progress logo on the update button appears for several minutes. Eventually it seems to complete (no error) but the additional subdomain is not listed as a URL when we refresh the custom domain page.

There is no evidence that the process has succeeded. When we check Route 53, the subdomain has not been added as a new CNAME entry.

We have also tried adding the CNAME entry directly into Route 53 pointing to the same cloudfront distribution as the original url. We receive the following error:

403 ERROR
The request could not be satisfied.
Bad request. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: OAMu8G_k0s6GKhpkmVSYIq3kBY4w2hqJtqCDBoZlC5hNeZVncAVvKw==

**Comment by kahdojay** [comment]
Hi @blairtaylor can you provide your App ARN/ Thanks

**Comment by blairtaylor** [comment]
arn:aws:amplify:us-east-1:102792536330:apps/d14xpxqf0qgvff

It is really hit or miss. Sometimes hangs for hours and sometimes seems to work.

**Comment by Joycehao19** [comment]
Hi @blairtaylor , it seems like you have 3 subdomains and all of them works fine. Do you have any questions about this issue?

**Comment by jsw** [comment]
I've run into the same or very similar issue. Console has been hanging for 10+ minutes on the update. I restarted a few times. Is there a workaround or any way to get insight into the cause?
