### ISSUE TITLE
Domain activation is Failed - [Removing everything i can see doesn't solve it]

### ISSUE THREAD

**Issue by Bulletninja** [aws-amplify/amplify-console#387]
**App Id**: d35rsxvfnyh81y
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Can't enable custom domain name.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Tried removing everything i had in my aws account, but the error persists

**Comment by Joycehao19** [comment]
@Bulletninja This CNAME is already associated with a different CloudFront distribution. These guides are helpful for getting started with custom domains, for existing domains there are number of steps that will need to be completed (as outlined in the docs above) depending on your current hosting and DNS providers.

A CNAME alias (domain) can only be used with a single CloudFront distribution at a time, if you receive this error then the domain is already associated with another CF distribution (either in the same AWS account, or potentially in a different account) and must be moved to the distribution created for you by Amplify Console before it will work, the docs help outline how to do this (and you may need to check more than one account if you or your organization owns multiple accounts) If you recently deleted it, please wait 6 hours and try to add custom domain again.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

**Comment by Bulletninja** [comment]
I waited, and i don't have cloudfront distributions left. How do i remove such CNAME? I don't see it in route53

**Comment by Bulletninja** [comment]
Solved it. Had to recreate my hosted zone (even though it didn't have any CNAME anymore).

**Comment by kahdojay** [comment]
Thanks for letting us know, closing this for now.
