### ISSUE TITLE
Failed to load resource: the server responded with a status of 403

### ISSUE THREAD

**Issue by cnbrkkaya** [aws-amplify/amplify-console#388]
I am trying to deploy a basic application to amplify console. When i work with localhost everything is perfect but when i try to build it with console i dont see any errors in console but when i click the domain i dont see anything just blank page i these errors in chrome console.
![5](https://user-images.githubusercontent.com/36765181/73068199-9b41cd80-3e78-11ea-98ee-a4b1e0db448d.JPG)

Here is some additional information. If you need something else i can attach.

![3](https://user-images.githubusercontent.com/36765181/73067975-0b9c1f00-3e78-11ea-9623-417e7af263d9.JPG)
Here is my scripts in package.json file

> "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "compile-sass": "node-sass src/assets/scss/now-ui-dashboard.scss src/assets/css/now-ui-dashboard.css",
    "minify-sass": "node-sass src/assets/scss/now-ui-dashboard.scss src/assets/css/now-ui-dashboard.min.css --output-style compressed",
    "map-sass": "node-sass src/assets/scss/now-ui-dashboard.scss src/assets/css/now-ui-dashboard.css --source-map true",
    "install:clean": "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm start"
  },

Thanks for everyone.

**Comment by Joycehao19** [comment]
@cnbrkkaya Sorry that you are having this issue. Can you provide your appId, region and build number? Do you have some sample app we could test with?

**Comment by cnbrkkaya** [comment]
Thanks for your interest.
I made a small mistake i will explain for people having the same issue.
There was a homepage prop in my package.json file that points wrong github url. I delete that prop so everything is fine now.
Thanks

**Comment by kahdojay** [comment]
Thanks, closing this for now.

**Comment by edward-ihealth** [comment]
hi Can you explain for about this issue

**Comment by edward-ihealth** [comment]
Hi @cnbrkkaya   Can you explain for about this issue
