### ISSUE TITLE
Google Font not loading on Amplify deployed site

### ISSUE THREAD

**Issue by nelsynelz** [aws-amplify/amplify-console#389]
Issue: My App hosted on Amplify doesn't seem to be loading my custom font which I'm importing via CSS import statement in my VueJS app. The font loads fine on the same computer/browser when working in my local development environment. 

URL to Amplify Site (congrats you guys get to see the product I'm working on before launch :grin: ):
https://master.d3atxduymnnyre.amplifyapp.com/ 

Here is the screenshot of the same page from my local development environment:
![image](https://user-images.githubusercontent.com/41842184/73079426-2f6c5e80-3e92-11ea-927e-819cbd2b3c26.png)

Code Snippet of how I'm importing the Font:
```
@import url('https://fonts.googleapis.com/css?family=Quicksand:400,600,700&display=swap');

.quicksandFont {
  font-family: 'Quicksand', sans-serif;
}
```

App info: This is a Nuxt JS app (VueJS but with pre-rendered HTML).

**Comment by nelsynelz** [comment]
The font isn't working for anyone else I've shared the site with. Nor is it working on my iPhone in Chrome or Safari.

The only info I could find about this topic is this article, but this obviously is not Amplify hosting: https://docs.wp-rocket.me/article/24-resolving-issues-with-cdn-and-fonts-icons

**Comment by Joycehao19** [comment]
Hi, can you provide your appId, region and build number? Thank you!

**Comment by nelsynelz** [comment]
Hi Joyce, I have build number and region but I don't know what you mean by appId. I don't see any field in my amplify app containing that. Do you mean either App Name (not sure if they're unique) or do you want the App ARN (which I know is unique)?

**Comment by Joycehao19** [comment]
@nelsynelz Yes. It is the last part of the app arn arn:aws:amplify:${region}:${accoundID}:apps/${appID}

**Comment by nelsynelz** [comment]
@Joycehao19 got it!

Appid: d3atxduymnnyre
Region: us-east-2
Build Number: 71

**Comment by kahdojay** [comment]
Hi @nelsynelz I see the fonts https://master.d3atxduymnnyre.amplifyapp.com/ in Firefox and Safari and a 200 from fonts.googleapis.com, were you able to sort it out?

**Comment by nelsynelz** [comment]
@kahdojay yeah it all seems to be good now. I didn't make any changes but I also no longer see the issue. I'm going to close this. 

Thanks all for the help.

**Comment by kalenyk** [comment]
@kahdojay , I got the same issue.
I have react project with a custom font. font works fine on my local computer in chrome, Mozilla and safari.
site: https://master.d341hhj24admog.amplifyapp.com

In response of font loading get a message "You need to enable JavaScript to run this app." and response header content-type: "text/html"
