### ISSUE TITLE
SSL verification is Running -

### ISSUE THREAD

**Issue by adamaltman** [aws-amplify/amplify-console#391]
**App Id**: dwcgpjxiowb7m
**Region**: us-east-1
**Step**: SSL verification
**Status**: Running

>**Note**: 

SSL verification ran for a few days.  I tried to remove the domain and add it again (that didn't fix it).  In other amplify projects in the same account, the root domain is verified and other subdomains of it are in use.

**Issue/question**

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by kahdojay** [comment]
@adamaltman have you verified that the verification CNAME does in fact resolve correctly (for example using dnschecker.org or dig), and that your NS records are properly configured?

**Comment by adamaltman** [comment]
Solution:

1. Delete domain from project
2. Add domain back to project.

SSL issued successfully within 15 minutes.
