### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Robstaa** [aws-amplify/amplify-console#393]
**App Id**: d14jmp6tprcyi
**Region**: eu-central-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I am using the naked domain for a load balancer but wanted to create a subdomain for a React App on Amplify. Before that I used a subdomain wildcard to redirect traffic to the load balancer. But I deleted all that (also the CNAMEs and CloudFront distribution from Amplify created before) and waited for 8 hours. But the error came up again when trying to associate the subdomain with a branch.
Would appreciate any help!

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by kahdojay** [comment]
Hi Robstaa, does the issue still persist? Please see:

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

These guides are helpful for getting started with custom domains, for existing domains there are number of steps that will need to be completed (as outlined in the docs above) depending on your current hosting and DNS providers.

A CNAME alias (domain) can only be used with a single CloudFront distribution at a time, if you receive this error then the domain is already associated with another CF distribution (either in the same AWS account, or potentially in a different account) and must be moved to the distribution created for you by Amplify Console before it will work, the docs help outline how to do this (and you may need to check more than one account if you or your organization owns multiple accounts)

**Comment by Robstaa** [comment]
Thank you for your response!

I am doing everything in Route 53, so no different hosting provider, though I moved the domains from one AWS account to the current one. But on the old one I deleted the registered domains and hosted zones (approx. 4 days ago). For the current one, I do have one subdomain (www) with a CNAME record pointing to a CloudFront distribution on the old AWS account.

The goal is to create a staging.plurapolit.de subdomain to point to the amplify app.
There is no other CNAME associated with that subdomain. I read all the help blogs and documentation, but nothing could resolve this issue... Can I do anything else?

Best
Robstaa

**Comment by kahdojay** [comment]
@Robstaa thanks for sharing. Can you confirm that staging.plurapolit.de is resolving as expected? I don't see it on my end.

If you are positive no CloudFront distribution exists (including in other accounts) using this domain, and only if it would not be disruptive to any currently running services, you might try deleting and recreating the hosted zone and starting from scratch: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-route53

Let me know if that's feasible and how it goes.

**Comment by Robstaa** [comment]
My fault. On another account I had a CloudFront distribution with a wildcard CNAME on that domain. That distribution was disabled but not deleted. Deleted it and now it works.
