### ISSUE TITLE
AWS Amplify deployment issue with spring Boot application

### ISSUE THREAD

**Issue by guruprasad211** [aws-amplify/amplify-console#394]
Deployed and verified springboot application successfully in AWS amplify, but not able to access the domain url.

All steps like Provision, Build, Deploy and Verify is successfull

Not able to access the url given in aws Amplify

**Comment by kahdojay** [comment]
Hi @guruprasad211 if you can fill out our [bug template](https://github.com/aws-amplify/amplify-console/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), it will help us investigate. Thanks in advance.

**Comment by Joycehao19** [comment]
@guruprasad211 Could you please provide your appId, region, build number, branch name?
