### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by julien-tamade** [aws-amplify/amplify-console#395]
**App Id**: d37sqsirhqa81j
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I restarted setting up my domain with amplify so domain activation failed because the dns hadn't yet propagated to the new cname record pointing to cloudfront. Now that those new records have propagated, I'm trying to retry the domain activation. The status says "retry in progress" for a while and I'm unsure if it's actually doing anything because when I refresh the page it's telling me that it failed and offering me to retry again. I would expect either I would get the error without having to refresh, or the error when refreshing is an old error and it's not actually retrying. Please let me know what the expected behavior is and if it's actually retrying.

edit: if I click retry the status changes to "retry in progress", but if I refresh right away the status changes to domain activation failed and it's offering me to retry again. This doesn't seem right

edit 2: The option to view DNS Records under "Actions" is grayed out and I can no longer select that.

**Error message**
If there is an error message, please include it here. 
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Additional information**
I am setting up a subdomain and excluding the root domain.

**Comment by Joycehao19** [comment]
@julien-tamade Hi,  `One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution.` Could you mind try re-add the custom domain and make sure all aliases are correct?
