### ISSUE TITLE
How to CNAME to an Amplify app without adding it as a custom domain

### ISSUE THREAD

**Issue by HMilbradt** [aws-amplify/amplify-console#396]
** Please describe which feature you have a question about? **
Custom domains

** Provide additional details**
Hey there,

We have a use case where we'd like to be able to CNAME to our Amplify app without needing to go through the hassle of setting up the custom domain.  For example, if we have `example.com` added as a custom domain for our Amplify app, we'd also like to be able to add a CNAME record for `example-two.com` which points to `example.com`.  

Currently, trying to do this gives a 525 SSL handshake failed error.  Is there a way that we can do this?

**Comment by kahdojay** [comment]
@HMilbradt unfortunately not - you'll need to setup a custom domain and validate your ownership of the domain prior to allowing requests via that CNAME and establishing https connections. Hope this helps, closing this for now, feel free to reopen if you have any other questions.

**Comment by swaminator** [comment]
@HMilbradt I don't fully understand the usecase. Do you mean:
1. Connect `www.example.com` to an Amplify app
2. Redirect `www.example.com` to `example2.com`
