### ISSUE TITLE
Can I access the CloudFront distribution with Amplify Console hosting?

### ISSUE THREAD

**Issue by kaihendry** [aws-amplify/amplify-console#40]
How does this fit in with [aws-amplify/cli](https://github.com/aws-amplify/amplify-cli) ? cli implies console to a lot of people.

I just provisioned the Hugo example.

It created https://github.com/kaihendry/hugo-example but I don't see any AWS CI related files like a `buildspec.yml`. I expected to be able to tweak some declarative file and not spend time in the clunky Web UI to provision more sites.

After provisioning the [hugo-example](https://s.natalian.org/2019-08-09/1565345101_2560x1440.png) from my account  I don't see any Cloudformation stack or CloudFront distribution or S3 bucket. Is this to be expected?

**Comment by swaminator** [comment]
> It created https://github.com/kaihendry/hugo-example but I don't see any AWS CI related files like a `buildspec.yml`. I expected to be able to tweak some declarative file and not spend time in the clunky Web UI to provision more sites.

You can choose to manage your buildspec in your repo (named amplify.yml). Refer here: https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html

Amplify Console offers fully managed hosting so you don't get access to the CloudFront distribution. Pricing: https://aws.amazon.com/amplify/console/pricing
