### ISSUE TITLE
SSL verification is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by IsaacTrevino** [aws-amplify/amplify-console#403]
**App Id**: daaxdtohx0ws6
**Region**: us-east-2
**Step**: SSL verification
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am implementing a domain name I recently purchased from route53, though I have had issues with amplify console integration. 

**Error message**
Error message: The status of this certificate request is "Failed". One or more domain names have failed DNS validation. Please check your domain name validation routes and try re-adding the custom domain to your app. Learn more: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-troubleshoot-guide

**Additional information**
I've recently added the name services which was my last roadblock, now I am failing ssl.

**Comment by Joycehao19** [comment]
Hi @IsaacTrevino , Did you check if the name servers on your domain match the name servers that the Amplify app created?

**Comment by IsaacTrevino** [comment]
For whoever runs into this issue, it started working automatically after some time.
