### ISSUE TITLE
"Operation Failed: Too many requests" saving environment variables

### ISSUE THREAD

**Issue by vedran** [aws-amplify/amplify-console#404]
**Issue Description**

"Operation Failed: Too many requests" error when pressing "Save" on the Environment Variables management screen.

**Detailed Steps To Reproduce**

1. Visit `App Settings -> Environment Variables`
2. Ensure you have at least 5 environment variables / overrides
2. Press "Save"
3. See the error below: (field values omitted from the screenshot)

![image](https://user-images.githubusercontent.com/473826/73707465-84894b00-46b0-11ea-80fb-61ce23e14074.png)

It seems like Amplify sends the environment variable updates as individual requests, and once there are at least 5 environment variables Amplfiy hits its own rate limit.

**Application Details**

arn:aws:amplify:us-east-1:641747502493:apps/d2pvhkvdg32ywu

**Comment by ganipcanot** [comment]
@vedran Sorry you saw this issue.  I was able to see it working below:

![environmentVariables](https://user-images.githubusercontent.com/21091073/73795642-f79dca80-475f-11ea-953e-7e6429fdd36f.gif)

Maybe you can retry updating the environment variables?

Also if you can give any more detail on how you were able to see this failure:

Did you try to update 5 all at once?  1 at a time?

**Comment by vedran** [comment]
@ganipcanot thanks for replying. I can reproduce the issue even if I don't add any additional environment variables. If the 5 variables that are in the previous screenshot are already defined, all I need to do is visit the environment variables management screen, and press save to trigger it. I just tried this and was about to cause the issue again.

![2020-02-05 08 59 53](https://user-images.githubusercontent.com/473826/73864098-ed2e1000-47f5-11ea-960b-34d3cccdfb93.gif)

Do you think it's because we have a large amount (>20) of connected branches in our amplify project?

**Comment by jhoffmcd** [comment]
We've been having this issue since we've started with Amplify (about 7 months ago). If you want another application to check: `arn:aws:amplify:us-west-2:059525859496:apps/d3a05gjdxb8h74`

**Comment by swaminator** [comment]
Fixed.
