### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by flyfisherdeveloper** [aws-amplify/amplify-console#406]
**App Id**: d3u11owfti6r3u
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am getting a Domain Activation failure, and I am not sure how to resolve it. This domain was created with Route 53 with Hosted Zones.

**Error message**
If there is an error message, please include it here. 
Error message: Oops, something went wrong. Please try again later.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by ganipcanot** [comment]
Hi @flyfisherdeveloper domain activation can take up to 24 hours, give it some time and check back again soon: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-route53

**Comment by Joycehao19** [comment]
@flyfisherdeveloper Did you re-connect the custom domain? Could you please check if the name servers on your domain match the name servers that the Amplify app created?

**Comment by flyfisherdeveloper** [comment]
Where are the name servers that the Amplify app created? I can't find them.

**Comment by Joycehao19** [comment]
@flyfisherdeveloper Sorry, I thought you own a three-party domain and recently transferred it domain to Route53. Did you try remove your custom domain and add it again?

**Comment by flyfisherdeveloper** [comment]
@Joycehao19 I will try that. Thanks for the suggestion.

**Comment by Athena96** [comment]
Closing this issue now, please reopen if you are still having issues.
