### ISSUE TITLE
Custom domain is stuck in verification

### ISSUE THREAD

**Issue by munkhbayar17** [aws-amplify/amplify-console#407]
**arn:aws:amplify:eu-west-2:932072193757:apps/dovytrqeyojo8**:
**ue-west-2**:
**Domain verification**:
**SSL configuration**:

**Issue/question**
I had my domain verified but the domain name was not resolving with `DNS_PROBE_FINISHED_NXDOMAIN`. So I removed my domain and added again. However, it has been stuck in verification step since 2 Feb. I have configured CNAME record on my DNS provider (Cloudflare) as it is requested on the amplify console.

**Error message**
In order to verify domain ownership, we will look for the following CNAME record associated with your domain. Please verify that the CNAME record exists in your Domain Name Server (DNS) file.

**Comment by munkhbayar17** [comment]
I have deleted my domain from Amplify console. Then migrated my DNS to Route 53 and added the domain again on the console. My domain is verified and SSL is issued. I think you guys have done nice job there! But my domain is still not resolving with DNS_PROBE_FINISHED_NXDOMAIN.

**Comment by munkhbayar17** [comment]
Thanks guys. It is resolved now.

**Comment by vikashkr117** [comment]
@munkhbayar17 How was it resolved? I am facing same issue. Please post how it was resolved.

**Comment by munkhbayar17** [comment]
> @munkhbayar17 How was it resolved? I am facing same issue. Please post how it was resolved.

Hi, I have registered for Route 53 as I said above. The Amplify guys must have fixed something on their side, I just removed the domain from Amplify and added it again.
