### ISSUE TITLE
Inconsistency between Amplify CLI and Amplify Console

### ISSUE THREAD

**Issue by ribeirojose** [aws-amplify/amplify-console#410]
** Please describe which feature you have a question about? **
Amplify publish hosting v. Amplify Console frontend hosting

** Provide additional details**
When running `amplify publish` under an amplify environment in the CLI, I'd expect that the frontend application has its own environment in Amplify Console. However, that is not the case, and frontend deploy has to be manually setup in Amplify Console. Additionally, as soon as one frontend environment is manually created (e.g. through using a bucket or uploading the `build` folder), it's not clear if it's possible to create an environment that sources a git repository branch.

**Comment by swaminator** [comment]
@ribeirojose currently the Amplify Console's Hosting feature (CI/CD, managed hosting) is not available in the Amplify CLI. The Amplify CLI has support for adding hosting with CloudFront and S3. To modify those resources, please goto the CloudFront/S3 consoles respectively. To get a frontend environment to show up, please add it through the Amplify Console's UI.
