### ISSUE TITLE
subdomains wont resolve

### ISSUE THREAD

**Issue by blomm** [aws-amplify/amplify-console#411]
**App Id**: d2meqvq92i0efd
**Region**: eu-west-1
**Step**: domain registration succeeds
**Status**: navigating to root domain works, subdomains does not: DNS_PROBE_FINISHED_NXDOMAIN

**Issue/question**
Why wont my subdomains resolve? It really feels like I've done everything right, but nada. I'm a little suspect about the fact that when I create subdomains via the console, all subdomains (dev/stage/uat) point to the same cloudfront distribution.

If I don't register the root domain name (mysite.com), and register dev.mysite.com as the root, then I can navigate to dev.mysite.com

**Error message**
DNS_PROBE_FINISHED_NXDOMAIN

**Additional information**
https://www.whatsmydns.net/ shows that my root site has propagated out, but subdomains no.

I'm totally stuck here, if someone @aws-amplify-ops could please take a look under the hood.

**Comment by ganipcanot** [comment]
Hi @blomm did you create your domains/subdomains and configure them through Route53 or some other provider?

**Comment by blomm** [comment]
Hey @ganipcanot , I created the subdomains via the amplify console, which has automatically updated route 53

**Comment by blomm** [comment]
hi @swaminator, could you please take a look for me? confirm that amplify has created the dns records in route 53 correctly?

**Comment by ganipcanot** [comment]
@blomm I don't think we have visibility into that since the dns entries, domains, subdomains would exist in your account and not ours.

On our end it looks like dev/stage/uat and the root domain are all AVAILABLE and they have different cloudfront distribution IDs.

**Comment by Joycehao19** [comment]
@blomm Hi, did you try delete the custom domain and re-add it on the console?

**Comment by blomm** [comment]
Hi @Joycehao19 @ganipcanot 
I couldn't get my subdomains to work, so instead I registered each subdomain as a custom domain.
Thanks very much for your helps on this.
