### ISSUE TITLE
Amplify build stuck on old graphql endpoint - how to update?

### ISSUE THREAD

**Issue by kuindji** [aws-amplify/amplify-console#416]
** Please describe which feature you have a question about? **
Hi! 
Recently I removed the graphql db/endpoint and created a new one. Everything works fine locally. Everything builds fine in Amplify Console except one thing - it uses old graphql endpoint (or some random endpoint - i don't know; definitely not the one I have right now).

How do I force Console to use new endpoint?

** Provide additional details**

**Comment by swaminator** [comment]
@kuindji how many frontend and backend environments do you see in the Console?

**Comment by kuindji** [comment]
I have only one environment called "test". 
I have three apps building different parts of one monorepo, they all use the same test environment and they all stuck with old graphql endpoint.

Locally `amplify env list` shows the same one environment.

**Comment by kuindji** [comment]
Graphql is a different point of frustration, not relevant to this case. 
But I run `amplify remove api` and `amplify add api` almost every day.

**Comment by swaminator** [comment]
@kuindji are you still having this issue. I'm closing it since it's been a while since there hasn't been a response. Please reopen it if you're still struggling with this.
