### ISSUE TITLE
SSL verification is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by keiscool2468** [aws-amplify/amplify-console#417]
**App Id**: d3jr9okllrs5gn
**Region**: ap-southeast-1
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Joycehao19** [comment]
Hi @keiscool2468 , could you please copy the error message? 

Could you please take a look of the following links? If those links can't solve your question, please let us know.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

**Comment by Athena96** [comment]
Closing this issue, please reopen if you are still facing the issue.
