### ISSUE TITLE
What does the cache field do? 

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-console#418]
** Please describe which feature you have a question about? **

Pardon my ignorance, but what does the cache field in amplify.yml do? The documentation at https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html explains all commands excluding that one.

**Comment by Joycehao19** [comment]
Hi @hisham , the cache path’s are automatically suggested build-time dependency path's (like node_modules) at the time you connect your app to Amplify Console, based on the package manager and framework you’re using. Amplify Console caches these path’s on the first build and reuses them on subsequent builds, when possible, to speed up build execution time.

**Comment by hisham** [comment]
Ok thanks for letting me know. Amplify did not detect my project it seems, probably because I'm using a mono-repo with multiple frontends, but no package.json was in the root dir at the time (new project). So I wrote my own amplify.yml. Will add the appropriate node_modules in the cache param. It's probably helpful to add some documentation about this setting, what to fill it with, and how the cache works, for people in my case who had to write their own amplify.yml.

**Comment by Joycehao19** [comment]
@hisham Thank you for sharing your thought with us. We will add more documentation about the cache field and how to set amplify.yml.

**Comment by Joycehao19** [comment]
pr: https://github.com/awsdocs/aws-amplify-console-user-guide/pull/16/files
