### ISSUE TITLE
Amplify custom domain worked for a while and then it stopped

### ISSUE THREAD

**Issue by pbenipal61** [aws-amplify/amplify-console#419]
So i setup a react app on amplify with a custom domain that's registered with namecheap.com .
I setup a route 53 hosted zone and linked it to my app in the amplify console. The new custom domain worked for a while. It showed my app when i visited the domain but now i just see a random page probably provided by namecheap by default.

**Comment by Joycehao19** [comment]
@pbenipal61 Sorry that you are facing this issue, would you mind provide your appID and region? Don't put you accountID here.(console->App setting-> App ARN (arn:aws:amplify:${region}:${accountID}:apps/${appID})

**Comment by pbenipal61** [comment]
Hey, i managed to fix it. It was a DNS problem.

**Comment by Joycehao19** [comment]
@pbenipal61 Cool. Closing the issue now.
