### ISSUE TITLE
Amplify Console Backend Role

### ISSUE THREAD

**Issue by blazinaj** [aws-amplify/amplify-console#42]
** Please describe which feature you have a question about? **
When setting up the backend role for the Amplify Console, the [docs](https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html) use the `AdministratorAccess` policy.

We try to limit the usage of that blanket policy, what exact IAM permissions does that role need?

**Comment by garyleefight** [comment]
@blazinaj Hi, The Amplify Framework requires AdministratorAccess role. I would suggest you post a question on Amplify Framework Github issue to check whether you can scope it down.
Link: https://github.com/aws-amplify/amplify-js/issues

**Comment by swaminator** [comment]
@blazinaj you can refer to this: https://aws-amplify.github.io/docs/cli-toolchain/usage#iam-policy-for-the-cli

Modify the policy as required with the resources being used.

**Comment by blazinaj** [comment]
Perfect, thank you very much. I missed that page.
