### ISSUE TITLE
Content missing after deploy

### ISSUE THREAD

**Issue by ekim1707** [aws-amplify/amplify-console#420]
**App Id**: kfllc
**Region**: us-east
**Step**: 
**Status**: running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I just deployed my project using a direct pull from github, and everything looks fine except some of my content is missing. 4 images just aren't showing at all, and on the form section of my site, none of the inputfields show their placeholders anymore. I checked locally to confirm, and locally they are still there. Not really sure what the issue could be for randomly missing content..

**Error message**
No error message related to the missing content that I can see.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by Joycehao19** [comment]
@ekim1707 Sorry that you are facing this issue, would you mind provide your appID and region?(like us-east-1 or us-east-2) Don't put you accountID here.(console->App setting-> App ARN (arn:aws:amplify:${region}:${accountID}:apps/${appID})

Thank you.

**Comment by ekim1707** [comment]
I actually think I troubleshooted the issues and now I’m fine. Thanks for
your help anyway though!!

Eugene

**Comment by Joycehao19** [comment]
@ekim1707 Great! Close the issue now.

**Comment by ekim1707** [comment]
Sorry about that.. I’m new to this. Thank you..

**Comment by Joycehao19** [comment]
@ekim1707 Don't feel sorry! Always feel free to contact us!!!

**Comment by ekim1707** [comment]
Thanks :)
