### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by danim47c** [aws-amplify/amplify-console#422]
**App Id**: d2zjc42zx1daxo
**Region**: eu-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I'm getting this error after I updated my dns records on my domain.

**Error message**
One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem.

**Comment by Joycehao19** [comment]
@danim47c  Hi, sorry that you having the custom domain issue. Could you please check if the DNS record is correct? If it is, please let us know. Thanks.

Here is a useful link to show you how to do it.https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error
