### ISSUE TITLE
SSL verification is Failed - Was Previously Verified and have lost DNS Verification

### ISSUE THREAD

**Issue by kziemski** [aws-amplify/amplify-console#424]
**App Id**: d2bskyqm09dyg8
**Region**: us-east-1
**Step**: SSL verification
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

I'm not sure when but at somepoint  today i lost my custom domain for one of the projects i have in amplify. interesting enough i have a another application connected to the same branch but different build setting and that looks fine.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
lot of repeating console error messages
Failed to load resource: the server responded with a status of 416 (Requested Range Not Satisfiable)
and then a repeating type error 
Uncaught TypeError: Cannot read property 'isFailed' of undefined
    at main.js:41
    at Array.filter (<anonymous>)
    at main.js:41
    at Array.forEach (<anonymous>)
    at t.n.getFailedOps (main.js:41)
    at t.render (main.js:41)
    at d._renderValidatedComponentWithoutOwnerOrContext (main.js:102)
    at d._renderValidatedComponent (main.js:102)
    at d._updateRenderedComponent (main.js:102)
    at d._performComponentUpdate (main.js:102)

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
renaming the custom domain name to sidestep this issue

**Comment by Joycehao19** [comment]
@kziemski Hi, did your custom domain fail to connect after Build 17 succeeded? your domain is w********ce.app?

**Comment by kziemski** [comment]
the sequence feels right.

yes thats my domain.

**Comment by Joycehao19** [comment]
@kziemski What is the DNS provider of this domain?

**Comment by kziemski** [comment]
Route 53

Mobile:+16463454567

**Comment by Joycehao19** [comment]
@kziemski  Could you please check if the name servers on your domain match the name servers that the Amplify app created?

**Comment by kziemski** [comment]
this hosted zone was created before the amplify app was created.
i think not sure i can check this as i had to redo the app.
appreciate the help.
there are clearly still some bugs understandable given what you're trying
to do.

any chance on AWS CodeCommit previews functionality?


Mobile:+16463454567

**Comment by Joycehao19** [comment]
@kziemski Yeah... Sorry I was thinking if there was something happened on our side, didn't pay attention on your logs. ;/
It seems like that your code had some issues.

```
lot of repeating console error messages
Failed to load resource: the server responded with a status of 416 (Requested Range Not Satisfiable)
and then a repeating type error
Uncaught TypeError: Cannot read property 'isFailed' of undefined
```

**Comment by kziemski** [comment]
apologies for not being clear  --> the above stuff is what Amplify Console
in chrome console is spitting out.
They weren't errors from my code.
the isFailed is seems like some code related to cloudfront or route53
enumeration if iremember correctly.


Mobile:+16463454567

**Comment by Joycehao19** [comment]
@kziemski what is the Branch name, build ID and the time you deploy the app?

**Comment by kziemski** [comment]
let me close this for now.
i will make sure if it happens again to document these things.

Mobile:+16463454567

**Comment by Joycehao19** [comment]
@kziemski Thanks. Would you mind take a screen shot of that page? Please don't post any sensitive information.

**Comment by ganipcanot** [comment]
Seems it is available when I check here: https://dnschecker.org/#NS/

Closing this issue for now - if you have additional issues please create another ticket.
