### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Chett23** [aws-amplify/amplify-console#426]
**App Id**: d1my21op7zm0sr
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Amplify says it can not activate the domain because of the following error message 

Error message: One or more of the CNAMEs you provided are already associated with a different resource.

I have tried to clear all CNAME DNS records except the ones used for Amazon Workmail.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
I have tried to clear all old dns records and the old s3 buckets used to host the old app. Yet it still errors saying there are CNAMES connected to a different resource.

**Comment by Joycehao19** [comment]
Hi @Chett23 , did you try to re-connect your custom domain on Amplify Console after at least 6 hours?

These guides are helpful for getting started with custom domains, for existing domains there are number of steps that will need to be completed (as outlined in the docs above) depending on your current hosting and DNS providers.

A CNAME alias (domain) can only be used with a single CloudFront distribution at a time, if you receive this error then the domain is already associated with another CF distribution (either in the same AWS account, or potentially in a different account) and must be moved to the distribution created for you by Amplify Console before it will work, the docs help outline how to do this (and you may need to check more than one account if you or your organization owns multiple accounts)
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error
https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/?nc1=h_ls

**Comment by Chett23** [comment]
Yes, I was able to reconnect it after removing the old SSL certificate through AWS certificate manager and it finally went through Thanks!.
