### ISSUE TITLE
Domain is throwing AccessDenied error after successfull deployment

### ISSUE THREAD

**Issue by prasaddattu478** [aws-amplify/amplify-console#427]
I have deployed a  sample app and it is throwing "AccessDenied" Error. 

**App ID: apps/dqkwpdygnzgei
Deployment type: Manual(drag & drop zip file)
Domain: https://dev7969.dqkwpdygnzgei.amplifyapp.com**

I have assigned service to this app. here is the Service role name
**AmplifyConsoleServiceRole-AmplifyRole**

Error:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>DFEC8C9EA8594937</RequestId>
<HostId>
C2RplAj7k2wWf1ENW6yZ9DLSIpMKrfmYKcGbmi6ZcY0deqk2/bE6NLRU9V9nd3Dz7Rh9JmxykME=
</HostId>
</Error>

$ curl -I https://dev7969.dqkwpdygnzgei.amplifyapp.com/
HTTP/1.1 403 Forbidden
Content-Type: application/xml
Connection: keep-alive
Date: Tue, 11 Feb 2020 17:30:00 GMT
Server: AmazonS3
X-Cache: Error from cloudfront
Via: 1.1 5d52966f37c4378fd883294634452d6b.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: DFW55-C1
X-Amz-Cf-Id: SDeiOQSALkhh8xWirM4SYTtMSQZFiEd-fx4im69qzFyfN2QdefxPOA==

By looking at below error from curl, the error it is from cloud front.

**Comment by Joycehao19** [comment]
Hi @prasaddattu478 , we cut a ticket in our customer oncall list, now is pending investigating.

**Comment by prasaddattu478** [comment]
The location of the index.html file was under export. So closing the issue.
