### ISSUE TITLE
Email notification need satisfy regular expression pattern

### ISSUE THREAD

**Issue by idrisov-ri** [aws-amplify/amplify-console#428]
Good day!

For the first time tried to use Amplify Console's  Email notification feature.

 Steps I made:

1. typed email address
2. selected target branch
3. hit "Save" button

every time I make these 3 steps loading spinner spins forever and nothing happens.
SNS topic is not created and subscription confirmation email is not sent. 

I made some investigations and found out that API request to `https://ap-northeast-1.console.aws.amazon.com/amplify/api/sns` returns error with `400 (Bad Request)  InvalidParameter: Invalid parameter: Topic Name` error message

Region I use is `ap-northeast-1`

Browser: Google Chrome for Mac Version 79.0.3945.88

If any additional information needed feel free to let me know!

**Comment by Joycehao19** [comment]
Hi @idrisov-ri , I just added email notification to my app. It works fine. Could you please refresh the page and re-add the email notification?

What I did:
```
Click Manage Notifications
Email: yourname@amazon.com
Branch: master
Save

#Open my email and confirm subscription notification
Re-build App
Received email about build status of my app
```

**Comment by idrisov-ri** [comment]
Hi, @Joycehao19 
Thanks for quick response!

I tried one more time with a short branch name and it worked!
Looks like problem starts only when the branch name is long.

```
Email: yourname@amazon.com
Branch: amplify
Save
```
that works just fine

```
Email: yourname@amazon.com
Branch: feature/amplify-setup
Save
```
and this fails with `400 (Bad Request) InvalidParameter: Invalid parameter: Topic Name` error

Please check if it the same for you. 
And thanx again! Now at least we know that with a short branch name it works.

**Comment by Joycehao19** [comment]
@idrisov-ri Thank you for reporting this bug. We cut a ticket in team backlog to throw error if customer can't create email notification. 

The reason that you can create a email notification of branch `Branch: feature/amplify-setup` is:

```
There was an error while saving rule amplify-${appID}-feature/amplify-setup-branch-notification.
Details: 1 validation error detected: Value 'amplify-${appID}-feature/amplify-setup-branch-notification' at 'name' failed to satisfy constraint: Member must satisfy regular expression pattern: [\.\-_A-Za-z0-9]+.
```

CloudWatch need the branch name satisfy regular expression pattern: [\.\-_A-Za-z0-9]+. You branch name contains '/'. You could reproduce this step in CloudWatch>Events>Rule>Create Rule, in name area put: amplify-${appId}-${branchName}-setup-branch-notification.

**Comment by idrisov-ri** [comment]
@Joycehao19 thanx for kind response and explanation!
Throwing an error would be a good solution.

When this issue is not needed any more please feel free to close it or let me know so I"ll close it for myself.

Have a good day!

**Comment by Joycehao19** [comment]
Hi @idrisov-ri , we released a fix. Now, if the branch name doesn't satisfy regular expression pattern, the save button would be disabled.
