### ISSUE TITLE
Amplify Backend build error through amplify CI

### ISSUE THREAD

**Issue by marksy-91** [aws-amplify/amplify-console#429]
We're currently getting the error below when deploying changes on amplify console ci:

![image](https://user-images.githubusercontent.com/35209732/74320680-2c032d80-4dd5-11ea-9830-3423800e450c.png)

The the backend environment that we've connected to this front-end build is 'prod', but it seems to be picking up 'popfit-rel'

**Comment by Joycehao19** [comment]
Hi @marksy-91 The reason of `Build failed` is `Environment name should be between 2 and 10 characters(only lowercase alphabets)`(line 7). If you change the Amplify environment name, it should be fixed.

**Comment by marksy-91** [comment]
Hi @Joycehao19, thanks, but that doesn't quite explain the issue I'm facing. Although the cli-console output is showing the environment as 'popfit-rel', in actual fact our only backend environments are 'prod' and 'dev'. See below:

![image](https://user-images.githubusercontent.com/35209732/74398821-ec882000-4e6c-11ea-93bf-5c1c4b55083a.png)

For some reason, the CLI doesn't pick up the environment that is assigned to the application.

Any further suggestions?

**Comment by Joycehao19** [comment]
@marksy-91  For me, it seems like that you used backend environment: 'popfit-rel'. 
Did you ever set `popfit-rel` environment? Can you find `popfit-rel` in amplify/team-provider-info.json?

**Comment by marksy-91** [comment]
The ```popfit-rel``` environment doesn't exist in our project, athough, it may have been an environment that we previously used.  Our current amplify/team-provider-info.json is as follows.

```json
{
    "dev": {
        "awscloudformation": {
           
        },
        "categories": {
            "auth": {
                
            }
        }
    },
    "prod": {
        "awscloudformation": {
             
        },
        "categories": {
            "auth": {
                
            }
        }
    },
}
```

Also, the output from amplify list env is:
```
amplify env list

| Environments |
| ------------ |
| dev          |
| prod*        |
```

Any further thoughts?

**Comment by ganipcanot** [comment]
@marksy-91 Could you give your appId and region so we can look into it further?

**Comment by marksy-91** [comment]
@ganipcanot we were able to bypass the issue by creating an `amplify.yml` file in our repository and deleting the backend environment in the AWS Amplify console.

If you're still interested in investigating though, our App Id is `db28ewqe9qw8o`
