### ISSUE TITLE
React app with React-Router deployed on Amplify Console, redirects to index.html

### ISSUE THREAD

**Issue by ilyador** [aws-amplify/amplify-console#430]
Whenever I open the app from the root URL and navigate, all is fine.
However, if I go directly to, or refresh `app.com/login` or any other non-root URL, I get redirected to the non-existent `index.html`.

I have tried the solutions from this issue, but nothing seems to work https://github.com/aws-amplify/amplify-js/issues/2498

I did not configure any other routing or URL related things in my app (there is a comment about Vue saying there is sime configuration to be done before deployment, I haven't found anything similar about react and `react-create-app` scaffolding).

**Comment by Joycehao19** [comment]
Hi @ilyador , did you try
```
source: </^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf)$)([^.]+$)/>
target: /index.html
type: 200 
```
or change source to:
` </^((?!\.(css|gif|ico|jpg|js|png|txt|svg|woff|ttf)$).)*$/>`

**Comment by ilyador** [comment]
@Joycehao19 Yes, this is what I did. No luck. 
<img width="1100" alt="72205123-0cb17180-34b2-11ea-899f-5744d5bc79b0" src="https://user-images.githubusercontent.com/703551/74377879-b8fdb500-4ddc-11ea-8861-96428f8c7897.png">

**Comment by Joycehao19** [comment]
@ilyador Did you have a sample app we could test? Did you set anything we need to pay attention?

**Comment by ilyador** [comment]
@Joycehao19 This is weird: I have one app that works fine, and another that doesn't with the same stack (react + react-router) and same settings.
This is the one that doesn't: https://www.photowin.net/

**Comment by ilyador** [comment]
@Joycehao19 I think I know what went wrong: for some reason, my domain is no longer managed by the Amplify console.
When I go to the URL I still get to the app, but It does not appear in the domain management section. When I try to connect it again I get an error that it is already in use.

**Comment by Joycehao19** [comment]
#454 
Resolved issue. Closing for now.

**Comment by Apoorva-lokhande** [comment]
> #454
> Resolved issue. Closing for now.

how did you resolve?
same issues

**Comment by bksun** [comment]
> > #454
> > Resolved issue. Closing for now.
> 
> how did you resolve?
> same issues

Even I have very same issue, trying to connect to amplify public url but not working as expected.

When route matchs then a blank page and when route doesn't match then I get error page as expected.
