### ISSUE TITLE
I can't find my env in the console 

### ISSUE THREAD

**Issue by randytorres** [aws-amplify/amplify-console#432]
**App Id**: d3u1esrvizobbf
**Region**: us-east-1
**Step**:
**Status**:

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

I can't find my env in the console, I can only see older ones. The url provided from `amplify-console` gives this error `App with id: d3u1esrvizobbf not found`. I'm able to make changes to the env from the cli at least but I need to access the resources manually.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 
`App with id: d3u1esrvizobbf not found`

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by swaminator** [comment]
Are you sure you're in the right region from which you deployed?

**Comment by randytorres** [comment]
Oh wow thats embarrassing 😭I was not in the right region. Thanks for the quick response!
