### ISSUE TITLE
Getting 403 accessing recently deployed app

### ISSUE THREAD

**Issue by jcalvoch** [aws-amplify/amplify-console#435]
**App Id**: d2keoun3hapo8
**Region**: Oregon (us-west-2)

Getting 403 accessing recently deployed app:

curl -i https://prod.d2keoun3hapo8.amplifyapp.com
HTTP/2 403 
content-type: application/xml
date: Thu, 13 Feb 2020 04:47:32 GMT
server: AmazonS3
x-cache: Error from cloudfront
via: 1.1 6970aae0c617a1b9b328fc27b7cb6e3c.cloudfront.net (CloudFront)
x-amz-cf-pop: ORD51-C2
x-amz-cf-id: n54wG0aHLCuGD2gSOcL-oNA-eTFtgxRIzlrPBB50G-z-0irtwBfvGw==

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>2E42DE08404A12CD</RequestId><HostId>sUQlM+lbpVfk7bHyOHus0bDDHr/fi9C5bPYOkdfCm5AFd4DpnwQAlPF+IA5Om/3T6i+zovJz/oY=</HostId></Error>

**Comment by prasaddattu478** [comment]
We got a similar issue. in our case, index.html was under /xyz/xyz/ subdirectory path instead of being at root level. To fix it we went inside the directory where index.html is present & did a zip. deployed the zip file and we are able to access it.

**Comment by jcalvoch** [comment]
@prasaddattu478 thank you for your reply. I did see your post before but in our case the index.html is on the root

**Comment by Joycehao19** [comment]
Hi @jcalvoch , sorry that you have this issue. Did you use manual deploy from S3?

**Comment by jcalvoch** [comment]
@Joycehao19 Manual copy and paste

**Comment by jcalvoch** [comment]
Update: Tried manual deploy from S3 and I am having the same issue.

**Comment by jcalvoch** [comment]
Any update here?

**Comment by ganipcanot** [comment]
It looks like there is some misconfiguration in your application.  I tried it in my test account and I am seeing the same issue related to this file: favicon.ico.

![image](https://user-images.githubusercontent.com/21091073/74771205-8e7b8400-5242-11ea-8b6d-21ca3881e8cf.png)

Maybe check that your favicon.ico is in the correct spot?

**Comment by jcalvoch** [comment]
The favicon.ico is on the document root on the same folder than the index.html. I have other React projects like this one deployed on AWS that use the same structure.

**Comment by ganipcanot** [comment]
@jcalvoch I was able to get it working to the point where it would load your index.html but your site was still unable to find some CSS files.

When you are uploading the zip folder make sure you **zip the contents of your bulid output and not the top level folder**.  For example **if your build output generates a folder named "build" or "public" first navigate into that folder, select all of the contents and zip it from there**.  If you do not do this then you will see an "Access Denied" error because the sites root directory will not be initialized properly.

I would try this and resolve the CSS issues you find - and if you still have issues please reach out to us.

**Comment by jcalvoch** [comment]
Awesome. That's what I needed to know, thank you for your support.

**Comment by yair-submittable** [comment]
I have the exact same problem. Just created a blank react app and uploaded to gitlab. If using AWS Amplify console I get 403 on index.html and favicon.ico. If I use amplify add hosting and then publish I got to go and set up the S3 for web access. I suspect the console does not do that. Oh and I have also added the SPA routing to prevent the redirect.

**Comment by bishonbopanna** [comment]
How did you folks solve this ? I am running into the same issue, when I push the app from the terminal using amplify publish, it works but when configure and build through the amplify console i get 403.

**Comment by beerth** [comment]
I ran into the same issue after creating a new environment and doing a "amplify push". 
Doing also a "amplify publish" solved my issue.
