### ISSUE TITLE
Usage of _LIVE_UPDATES environment variables

### ISSUE THREAD

**Issue by hamasayu** [aws-amplify/amplify-console#438]
**Please describe which feature you have a question about?**
Usage of _LIVE_UPDATES environment variables is not described in the [public documentation](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#amplify-console-environment-variables). Please consider adding description to the docs.

**Provide additional details**
By default, the following environment variable is added to an app that uses Amplify CLI to deploy backends. However, the usage of the variable is not documented. I would like the public document to describe the meaning of its value and how we can use it.

|Variables|Value|Branch|
|:---:|:---:|:---:|
|_LIVE_UPDATES|[{"name":"Amplify CLI","pkg":"@aws-amplify/cli","type":"npm","version":"latest"}]|All branches|

**Comment by Joycehao19** [comment]
Hi @hamasayu , `_LIVE_UPDATES: [{"name":"Amplify CLI","pkg":"@aws-amplify/cli","type":"npm","version":"latest"}]` is used to upgrade the amplify cli tool to the latest version. I'll update the documentation. Thanks.

**Comment by Joycehao19** [comment]
Send PR
