### ISSUE TITLE
Blue/green deployment strategy

### ISSUE THREAD

**Issue by sachinkarale** [aws-amplify/amplify-console#444]
Is it possible to configure Blue/Green deployment strategy with Amplify ?

Basically I wanted to use amplify for static website hosting with blue/green deployment strategy, my backends are running on ec2.

**Comment by swaminator** [comment]
@sachinkarale Amplify Console offers atomic deploys and instant cache invalidation which is essentially offers the same functionality as blue-green. With atomic deploys, we only update your site once the build is succesful, and those changes are available instantly. Is there anything else you're looking for?

**Comment by sachinkarale** [comment]
no, thanks for the clarification.

**Comment by vineethbhargavan** [comment]
Just to clarify...if the static webpage is associated with API's mapped to Appsyc or Lambda function and there are changes involved in them as part of the new deployment - will the static page point to the old Appsyc/Lambda version - until the time the new build is a success?
