### ISSUE TITLE
Connection Timed Out

### ISSUE THREAD

**Issue by jeh26033** [aws-amplify/amplify-console#447]
**d2wqg4b36m462q**:
**us-east-1**:
**Done**:
**Complete**:

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
When going to my Custom Domain, I get a ERR_CONNECTION_TIMED_OUT error, and everything seems to be set correctly as far as settings go. Using Route 53. I've done the 'one click' setup, and it succeeded. 

**Error message**
ERR_CONNECTION_TIMED_OUT
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Not sure what needs to be linked here..

**Comment by ganipcanot** [comment]
How long ago did you configure your custom domain?  It can take up to 24 hours:

"Note: It can take up to 24 hours for the DNS to propagate and to issue the SSL certificate. For more information about the status messages, see Associating a Domain."

Ref: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html

**Comment by ganipcanot** [comment]
You can also try removing and re-adding the domain if it has been more than 24 hours.

**Comment by jeh26033** [comment]
It's been about a week now since I've finished the update. I'll try that now and see if it fixes it.
