### ISSUE TITLE
No option to use existing environment for preview

### ISSUE THREAD

**Issue by brignano** [aws-amplify/amplify-console#448]
Hi,

Not sure if this is related to #363 or not but, I don't see any option to configure a default backend for previews in my console anymore. Is that the expected behavior? 

I checked the latest [AWS Amplify - Console User Guide](https://docs.aws.amazon.com/amplify/latest/userguide/amplify-console-ug.pdf) and Page 45 seems to indicate that I should expect the view pictured below to have an extra column labeled **Backend environment**.

![image](https://user-images.githubusercontent.com/9291621/74793107-62392500-528d-11ea-822a-ceab6a31a4cb.png)

_For some context-_ When I originally setup Amplify console, I saw this option there but opted to create new environments for each pull request. After noticing that setting up new backend environments for every preview extended the build time, I provisioned a dedicated environment for previews but when I went back to manage the preview settings again this option was gone.

![image](https://user-images.githubusercontent.com/9291621/74793172-9280c380-528d-11ea-8c94-ba103b5af71a.png)

**Comment by swaminator** [comment]
@brignano is your repo private? The backend PRs are only enabled for private Git repos.

**Comment by brignano** [comment]
Thanks for the quick reply @swaminator.

Originally, my repository was public but, after noticing pull request previews weren't being triggered, I re-read the documentation and updated my repository to be private. After doing so, I can see pull request previews being successfully triggered but I do not have an option to set the **Backend environment** anymore.

![image](https://user-images.githubusercontent.com/9291621/74891924-3e8de180-5356-11ea-8763-fd71015ce5f6.png)

**Comment by swaminator** [comment]
Try reauthenticating your app. Go to `App settings > general > Reconnect repository`.

**Comment by brignano** [comment]
@swaminator I did try re-authenticating my app prior to opening this issue without any success, and tried again today based on your feedback, but unfortunately I'm still not able to set the Backend environment.

**Comment by brignano** [comment]
Please let me know if there's anything else I should/can try to resolve this issue or if there's anymore information I can provide you to help debug it.

**Comment by Joycehao19** [comment]
Hi @brignano , what do you see when you connect a new app of your repo?

**Comment by brignano** [comment]
Hi @Joycehao19 , sorry I lost track of this issue but noticed it was moved from pending triage to pending release. Is there anything more from my end I can do to help the team debug this?

**Comment by jemucino** [comment]
I am running into the same issue. My app has always been private. I created a new app from the same repo, and still don't see the option to use an existing environment when enabling previews.

This is a big inconvenience because building the environment from scratch takes a long time and I would really like to simply use my dev environment.

**Comment by jemucino** [comment]
Interesting, I accidentally deleted my backend so I rebuilt the app from scratch using the Amplify CLI, but didn't push anything until all services were added and this time the Amplify Console recognized my app's framework as a React-Amplify (whereas previously it only said React) and now I get that option. Hope this helps someone else.

**Comment by ianmartorell** [comment]
I really don't want to recreate my entire app to enable this feature, but it would be really convenient to have. I was also seeing an option to assign a backend to the branch autodetection feature and now it's gone. 😕

**Comment by brignano** [comment]
Agreed, @ianmartorell. 

Very kind of @jemucino to document this workaround, even I previously followed the same steps as a hot fix for this issue, but I hope we are still interested in fixing the root cause because it seems to be impacting multiple users and there is no real mitigation strategy other than to recreate everything which I can't imagine will work for everyone.

**Comment by litwicki** [comment]
@brignano we're going to revisit this and give a proper update this week.

**Comment by vic-blt** [comment]
> Interesting, I accidentally deleted my backend so I rebuilt the app from scratch using the Amplify CLI, but didn't push anything until all services were added and this time the Amplify Console recognized my app's framework as a React-Amplify (whereas previously it only said React) and now I get that option. Hope this helps someone else.

I tried to replicate what you did but I still have "React" instead of "React-Amplify" as "Framework" in the app's details.
Could you share the steps in details please ?

**Comment by vic-blt** [comment]
On this [page](https://docs.aws.amazon.com/amplify/latest/userguide/deploy-backend.html), you can see this picture

![image](https://user-images.githubusercontent.com/48869999/107667495-ea2ef080-6c8f-11eb-9bc7-1d5a4b2ebaab.png)

___________________________

On my side, I can't find the option "From scratch" anymore

![console](https://user-images.githubusercontent.com/48869999/107668110-9670d700-6c90-11eb-8a63-955645f9fe82.png)

**Comment by vic-blt** [comment]
So after doing some tests, I found the solution.
As I was digging into this [aws-samples](https://github.com/aws-samples/create-react-app-auth-amplify) repo, I saw that the folder `amplify` was versioned.
I thought that maybe it would detect my amplify app as **React - Amplify** if this folder was present.
So I also versioned this folder keeping only the same files as the ones in the repo above.
And now if I create an amplify app:

![console](https://user-images.githubusercontent.com/48869999/108341123-a41ae500-71d9-11eb-8d0a-df86f7963912.png)

It correctly detects that this is a fullstack amplify app.

**Comment by codingdiaz** [comment]
I am hitting this same issue. Is there no easy way to tell amplify that I changed my mind from a static site to a full stack app?

**Comment by vic-blt** [comment]
AFAIK, that's the only way.
Try versioning the file `project-config.json` and see if it changed to "React - Amplify" as your Framework in App details.
Maybe you could also try to reconnect your repository.

**Comment by coa00** [comment]
> AFAIK, that's the only way.
> Try versioning the file `project-config.json` and see if it changed to "React - Amplify" as your Framework in App details.
> Maybe you could also try to reconnect your repository.

I am hitting this same issue. 

My project was working fine.Suddenly it stopped working.
Project-config.json was versioned.

New Project is working fine.

**Comment by vic-blt** [comment]
Same here, it's been now some days (maybe weeks) that options related to Amplify fullstack (use same backend for previews...)  have disappeared.
It worked fine for 3 months.

**Comment by jemucino** [comment]
This problem has resurfaced for me. I am unable to see the backend options for previews and it looks like my app no longer recognizes the framework at all:

![image](https://user-images.githubusercontent.com/8001026/122612968-e5f95200-d038-11eb-87be-dac0aa0ff2ec.png)

@aws-amplify-ops you need to do something about this. The only way to get everything to work again is to create a new app from the repo, but I frankly do not want to deal with all the work it will take to recreate my settings and backends. If my app was already in production this would be pretty unacceptable.

**Comment by jemucino** [comment]
For anyone else who comes across this before Amplify devs do anything about it, this worked for me:

1. Go to _App settings: General_ and click _Edit_
2. Make sure your production branch is set to the branch you actually use for production (in my case 'prod')
3. Then use the AWS CLI (I used V2) to set the framework for your production branch:
  `aws amplify update-branch --app-id xxxxxxxxxxxxxx --branch-name prod --framework 'React - Amplify'`

**Comment by ldej** [comment]
@jemucino Thank you, this works!

**Comment by ganipcanot** [comment]
Resolving due to age - please re-open if you are still experiencing issues.
