### ISSUE TITLE
Stuck `Retrieving deployment details...`

### ISSUE THREAD

**Issue by isi-gach** [aws-amplify/amplify-console#45]
**Describe the bug**
My Amplify console is stuck with the message:
> Retrieving deployment details...

**To Reproduce**
I was trying to deploy an S3 bucket with a GatsbyJS application, this is what I did:
1. Create a Gatsby project and an S3 bucket using Amplify
```
gatsby new my-gatsby-site
cd my-gatsby-site

amplify init
amplify add storage
amplify push
```
2. Deploy to S3 using the Gatsby S3 plugin:
https://github.com/jariz/gatsby-plugin-s3#usage
```
npm i gatsby-plugin-s3
npm run build && npm run deploy
```
3. In the Amplify Console, choose *Deploy without a Git provider*.
4. For Method, choose *Amazon S3*, and for Bucket, choose the bucket you just created.

**Expected behavior**
The S3 bucket content is deployed

**Comment by swaminator** [comment]
@isi-gach We're not sure how that Gatsby plugin works (as its a third-party plugin), but to deploy your artifacts from an S3 bucket, you must have a zipfile. Did you pick a zipfile from the bucket?
https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html#amazon-s3-or-any-url

**Comment by isi-gach** [comment]
hi @swaminator
sorry, my bad, I thought that it would upload the content of the S3
maybe it would be more clear the form doesn't allow to go to the next step until you select a `.zip` file?

**Comment by swaminator** [comment]
Thanks for the feedback. We've added it to our backlog
