### ISSUE TITLE
Unable to Add Custom Domain

### ISSUE THREAD

**Issue by cjuszczak** [aws-amplify/amplify-console#450]
**App Id**: d39hhmbxkor2c2
**Region**: us-west-2
**Step**: Adding custom domain
**Status**: Unable to add custom domain

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Unable to add custom domain in Amplify console. 

**Error message**

No option to add domain:

<img width="883" alt="Screen Shot 2020-02-18 at 1 35 29 AM" src="https://user-images.githubusercontent.com/4083073/74849129-351c5f00-52ed-11ea-8f85-c8984a772815.png">

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
I have created an Amplify app using the CLI, I added S3 with CloudFront hosting and published the app using the CLI. The CloudFront URL provided by the CLI during the publish step works and it created the distribution visible in my CloudFront console. However, the Amplify console does not show a front end for my application and I am unable to add a custom domain which I have as a hosted zone in Route 53.

Running `amplify status` in the CLI returns the following:

```Current Environment: prod

| Category | Resource name       | Operation | Provider plugin   |
| -------- | ------------------- | --------- | ----------------- |
| Auth     | <resourceName> | No Change | awscloudformation |
| Storage  | rsvps               | No Change | awscloudformation |
| Function | handleRsvps         | No Change | awscloudformation |
| Api      | rsvps               | No Change | awscloudformation |
| Hosting  | S3AndCloudFront     | No Change | awscloudformation |
```

**Comment by swaminator** [comment]
@cjuszczak currently Amplify Console and Amplify CLI do not have the same hosting options. Hosting with Amplify CLI will create and S3/Cloudfront distribution. Please enable hosting through the Amplify Console and the custom domain options will show up.

**Comment by cjuszczak** [comment]
@swaminator Thanks for following up. That’s disappointing news for sure but I will give that a try. Is there any intent on adding this functionality in the future?

**Comment by stigalvestad** [comment]
This information should be stated on the "Domain management" section - I also spent time trying to understand why I could not setup my custom domain - when I had an app and available domains in Route53, until I found description given by @swaminator .

**Comment by kahdojay** [comment]
Hi @cjuszczak you can check out our recent release adding the Amplify Console as a hosting option from the Amplify CLI: https://aws.amazon.com/blogs/aws/host-your-apps-with-aws-amplify-console-from-the-aws-amplify-cli/

Let us know if you're still unable to setup a custom domain with you Amplify Console-hosted app, our documentation on the topic can be found [here](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html).

@stigalvestad thanks for the feedback, we will take this into consideration and look at clarifying the docs

**Comment by stigalvestad** [comment]
Thanks for linking to the description about the new hosting option @kahdojay . It looks very useful!

**Comment by peerhenry** [comment]
I had the same problem and I just spent hours looking for ways to configure Route 53 so that my domain would route to my amplify app. The solution posted by @swaminator should become a big bold warning in the documentation here: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html
