### ISSUE TITLE
Proper rewrites

### ISSUE THREAD

**Issue by singledigit** [aws-amplify/amplify-console#452]
** Please describe which feature you have a question about? **
Rewrites and Redirects

** Provide additional details**
I am trying to configure a domain to host both the client and API behind it. The application is a URL Shortener. Here is an example of what I am trying to do using use cases.

1. User hits https://mydomain.com -> directed to the amplify console application (including all resource files like JS, CSS, etc)
1. User hits https://mydomain.com/shortcut -> rewrites to cloudfront domain.
     * If shortcut exists -> 301 redirect to target domain.
     * If does not exist -> 301 redirect back to https://mydomain.com?error=url_not_found

**Comment by singledigit** [comment]
So here is some more info. The following works but seems more than needed.

```json
[
    {
        "source": "https://www.slip.link",
        "target": "https://slip.link",
        "status": "302",
        "condition": null
    },
    {
        "source": "/",
        "target": "/index.html",
        "status": "200",
        "condition": null
    },
    {
        "source": "/css/<*>",
        "target": "/css/<*>",
        "status": "200",
        "condition": null
    },
    {
        "source": "/js/<*>",
        "target": "/js/<*>",
        "status": "200",
        "condition": null
    },
    {
        "source": "/favicon.ico",
        "target": "/favicon.ico",
        "status": "200",
        "condition": null
    },
    {
        "source": "/<*>",
        "target": "https://d16140obdnjb2p.cloudfront.net/<*>",
        "status": "200",
        "condition": null
    }
]
```

I feel like I could reduce this with soimething like... 

```
</^(?!(\/css\/|\/js\/|\/index.html|favicon.ico|\/\?)).+/>
```

**Comment by Joycehao19** [comment]
@singledigit  can you try this?
 <^(?!(css|js|index.html|favicon.ico|\/\?)).+>
