### ISSUE TITLE
Domain disconnected from management console, but still connected to hosting

### ISSUE THREAD

**Issue by ilyador** [aws-amplify/amplify-console#454]
**App Id**: `d1cmyetdr5npbg`
**Region**: eu-central-1
**Step**:
**Status**: Connected the domain, but it no longer appears in the Amplify console.

**Issue/question**
I have registered a domain with an Amplify app. At first it worked fine, but later I realized I have a redirects issue. This is when I saw that the domain does no longer appear in the console. The URL still works, but I can no longer manage it, and "rewrite and redirects" don't work with it.

I tried connecting it again but got an error saying CNAME is already taken.

**Comment by ganipcanot** [comment]
@ilyador You can find your appID within the app arn:

![image](https://user-images.githubusercontent.com/21091073/75065186-368c8980-549d-11ea-99a4-dfadbc475f46.png)

**Comment by ilyador** [comment]
@ilyador thanx, so the number I put is correct: 007140722602

**Comment by swaminator** [comment]
@ilyador no.. the appid is after the /

**Comment by ilyador** [comment]
@swaminator got it: `d1cmyetdr5npbg`

**Comment by ganipcanot** [comment]
That’s actually your account id.  In the image I posted above the appId is “d14bgamial4wrt”.

**Comment by ilyador** [comment]
@swaminator `arn:aws:amplify:eu-central-1:XXXXXXXX:apps/d1cmyetdr5npbg`

**Comment by Joycehao19** [comment]
@ilyador Do you mean that you connected an app, then you connected it again? Can you see 2 same app on `All apps` page? If you do, you need to remove the custom domain from the app you don't use and add domain to the new app.

**Comment by ilyador** [comment]
@Joycehao19 No, I have only 1 app. I **connected a domain** to it.
The domain URL works, but no longer appears in the Amplify domain management section.

**Comment by Joycehao19** [comment]
@ilyador Got it. It seems like your app associate with on************.net now. The photowin.net associate with an app in us-east-2.

**Comment by ilyador** [comment]
@Joycehao19 thanx! I removed the us-east version. I'm not sure how it happened that I have it in 2 regions, I'm pretty sure I deployed it only to eu-central.

**Comment by Joycehao19** [comment]
@ilyador I don't know why it happened.. Maybe you browser automatically directly you to us-east-2. It seems your issue solved now, let close this ticket. If you have another question, please open a new issue. Thanks
