### ISSUE TITLE
Cannot edit build commands when connecting frontend web app - due to CSP?

### ISSUE THREAD

**Issue by stigalvestad** [aws-amplify/amplify-console#455]
I've selected Github repo, and I've come to step 2, where I should "configure build settings". I want to edit the auto-generated build and test settings, so I click "Edit". But in the dialog that opens, I cannot edit anything. In the Chrome console, I can see the following error:

> Refused to load the script 'https://eu-west-1.console.aws.amazon.com/amplify/mode-mode.js' because it violates the following Content Security Policy directive: "script-src https://d25ir82nywnt3g.cloudfront.net/ https://d1b6ig1vwyrbxe.cloudfront.net/ https://media.amazonwebservices.com/urchin.js https://d2q66yyjeovezo.cloudfront.net/ https://d1ge0kk1l5kms0.cloudfront.net/ https://d18ovsmfaucn3d.cloudfront.net/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

My chrome version is:
Version 80.0.3987.116 (Official Build) unknown (64-bit)

**Comment by Joycehao19** [comment]
@stigalvestad Thank you for reporting this bug. We will investigate on this issue. I tested on  Version 80.0.3987.106 (Official Build) unknown (64-bit) and 
Version 80.0.3987.122 (Official Build) (64-bit)
They all works fine. If you refresh the page and reconnect your app, would it work? If you don't mind, would you mind upgrade chrome to version 122 and try connecting your app?

**Comment by daunce** [comment]
I get the same result using Firefox 74.0 64bit, Chrome 80.0.3987.149, also with private/incognito mode on 2 different Windows 10 machines, in that I am unable to edit the build commands.

Also the Light/Dark theme toggle does not work when this happens.

**Comment by Joycehao19** [comment]
@daunce @stigalvestad Thank you for reporting this error, we cut a ticket in our team backlog. We will working on a fix.

**Comment by blydewright** [comment]
@daunce are you able to share how to overcome this bug to be able to edit the build command? I'm stuck and unable to continue..

**Comment by blydewright** [comment]
I see that the problem only occurs when setting up your amplify app and linking it to GitHub. After saving and deploying, editing the build command through App settings -> build settings works as expected 👍

**Comment by Attersson** [comment]
Same problem here. Using Chrome, latest

**Comment by vsrey** [comment]
I'm still facing this issue as well. Then, after the build fails, the amplify console behaves as in #1343. I can't manually trigger builds and it doesn't seem to trigger a build when I push to my Github repo. The only option seems to be switching to manual deployments right now -- quite frustrating.

**Comment by theycallmemac** [comment]
Also running into this issue. Would like to see movement on this, or at least a clearer wrok around for setting up Git-based deployments. Very frustrating

**Comment by Athena96** [comment]
Hi @stigalvestad I am unable to repro the issue, please feel free to re-open if you are still facing the issue. Thanks!
