### ISSUE TITLE
Restart app to apply new env variables

### ISSUE THREAD

**Issue by panslava** [aws-amplify/amplify-console#457]
** Please describe which feature you have a question about? **
Is it possible to restart react frontend app manually? I just changed environment variables in aws amplify gui and I want app to restart to apply them

** Provide additional details**

**Comment by Joycehao19** [comment]
@panslava do you mean redeploy the app? If you click `redeploy this version` on the specific branch of your app, the app will be redeployed and applied all of environment variables.

**Comment by panslava** [comment]
Oh my god, I somehow missed that button. Thank you so much!

**Comment by jonathanmanfield** [comment]
Does anyone know why this functionality is not available in a monorepo setup?

I have recently migrated one of our react apps following the guide: https://aws.amazon.com/blogs/mobile/set-up-continuous-deployment-and-hosting-for-a-monorepo-with-aws-amplify-console/

On the previous setup, the "Redeploy this version is available"

Now we are in the monorepo setup, the re-deploy button is lost.

<img width="372" alt="Screenshot 2020-12-30 at 11 46 02" src="https://user-images.githubusercontent.com/2669088/103349381-988e2600-4a94-11eb-9cde-0dfe83ac9c3a.png">

<img width="367" alt="Screenshot 2020-12-30 at 11 45 41" src="https://user-images.githubusercontent.com/2669088/103349356-8dd39100-4a94-11eb-9fac-4b9cd3351a7b.png">

**Comment by terranmoccasin** [comment]
Hello! Also wondering how to redeploy in AWS Amplify specifically to pick up new environment variables. I don't see the "Redeploy this version" option in the console.

**Comment by buzzbites** [comment]
### Follow the Screenshot

![Untitled](https://user-images.githubusercontent.com/102157977/163333123-18a356ab-aa45-41f7-ad29-6cf3d8fcbd23.png)

**Comment by sannjayy** [comment]
### Follow the screenshot

![Untitled](https://user-images.githubusercontent.com/52757722/163333272-ad6bd3dd-7f02-4b4b-8129-0b11fa617d8c.png)

**Comment by ttshivhula** [comment]
@sannjayy thanks, but the fact that if you don't click on that button it doesn't work is annoying.
