### ISSUE TITLE
redirects are working, but I don't know why

### ISSUE THREAD

**Issue by nagey** [aws-amplify/amplify-console#458]
**App Id**: d2daw8z19isuby
**Region**:us-east-1
**Step**:verify
**Status**:complete

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I've recently installed storybook-static as a build step on my branch `build-storybook`

This means (I thought), that I need two rules ideally with the ability to stop after one matches (but IDK if these redirects do passthrough like htaccess does).

I added the rule:
```
{
        "source": "<^storybook[^.]*$|\\.(?!(css|gif|ico|jpg|js|json|png|txt|svg|woff|ttf)$)([^.]+$)>",
        "target": "/storybook",
        "status": "200",
        "condition": null
    },
```
and it didn't work.

HOWEVER,

when I deleted my original rule (from the [docs](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html)):
```
{
        "source": "<^[^.]+$|\\.(?!(css|gif|ico|jpg|js|json|png|txt|svg|woff|ttf)$)([^.]+$)>",
        "target": "/storybook",
        "status": "200",
        "condition": null
    },
```
it started to work just fine.

where it got even weirder was when i deleted *BOTH* the original rule and the new rule, it still works.

## Questions this raises (for me)
* Is it auto-inserting some sort of rule when it detects a react front-end?
* is it caching a ruleset and this will start breaking when that cache expires?
* is there something else happening?

**Additional information**
app is a react frontend

**Comment by nagey** [comment]
ok, so i do know why they weren't "breaking" when I removed the rule, it was just redirecting everything to the index file first and I didn't notice.

However, this still leaves the question of how do I *exclude* a path from being matched? I assume it has something to do with the `condition` field, but can't find docs on how that works (beyond for geographies)

**Comment by Joycehao19** [comment]
@nagey Hi, what do you mean by`how do I exclude a path from being matched?` ? 
Are you looking for something: 
(/index.html will go to /index.html, other 200 response pages will go to /abc.html)
| Source  | Target | Type |
| ------------- | ------------- | ------------- |
| /index.html  | /index.html  | 200 |
| /<*>  | /abc.html  | 200  |

**Comment by nagey** [comment]
@Joycehao19 no — my current rule matches any url that doesn't have a file extension, or has a file extension that is not one of one of `css, woff, png, gif, ico, js, jpg, json, png, txt, svg, woff, or ttf`

I want to do the same thing, but also have it not include urls that start with `storybook`

**Comment by nagey** [comment]
to be more clear, this is my ruleset:
```
[
    {
        "source": "</^(storybook)[^.]+$|^(storybook)(.*)\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
        "target": "/storybook/index.html",
        "status": "200",
        "condition": null
    },
    {
        "source": "</^(?!(storybook))[^.]+$|^(?!(storybook))(.*)\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
        "target": "/",
        "status": "200",
        "condition": null
    },
    {
        "source": "/<*>",
        "target": "/",
        "status": "404",
        "condition": null
    }
]
```

Which, as I intend it, has the following meanings:
1. if a url matches `/storybook/*` redirect it to `/storybook/index.html`, unless it's an asset of some sort
1. if the URL doesn't match rule 1, and it's not an asset, and it doesn't start with storybook, redirect it to `/`
1. if the URL matches neither rule 1 nor rule 2 and the file isn't found locally, treat it as a 404

**Comment by nagey** [comment]
This was a mistake on my part.

For posterity's sake, the issue was that I was misunderstanding how the rules were applied.

These rules are javascript regexes, and transform urls in order. All URLs start with a `/` as they're passed into these regexes, so your pattern needs to take that initial slash into account.

For example, if you want to avoid the directory `static` at the start, you would use the following `source` rule mapping:
```
"source": "</^(?!(/static))(.*)$/>",
```

This rule would explicitly match all URLs *not* starting with `static`
