### ISSUE TITLE
SSL verification is Failed - CNAME setup took time, and verificartion retry fails

### ISSUE THREAD

**Issue by gommmmmm** [aws-amplify/amplify-console#462]
**App Id**: d1f2sjshpf2182
**Region**: ap-northeast-1
**Step**: SSL verification
**Status**: Failed

**Issue/question**
Our domain is hosted under third-party DNS server, and took a week to setup CNAME record.
After the record is set, we retried but it seems to fail. Is there any way to succeed?

**Error message**
We could not verify ownership of the domain. Please ensure you own the domain and choose retry. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: The status of this certificate request is "Failed". One or more domain names have failed DNS validation. Please check your domain name validation routes and try re-adding the custom domain to your app. Learn more: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-troubleshoot-guide

![image](https://user-images.githubusercontent.com/78220/75207868-4cf85500-57bd-11ea-9075-63697c5f7487.png)

**Comment by Joycehao19** [comment]
Hi @gommmmmm Sorry to hear that you have custom domain issue. For this issue, you could either contact the DNS provider to diagnose why the DNS verification CNAME is not resolving or migrate your DNS to Route53. 
How to migrate your DNS to Route53: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/MigratingDNS.html

**Comment by gommmmmm** [comment]
Hello @Joycehao19 Thank you for responce.

>  For this issue, you could either contact the DNS provider to diagnose why the DNS verification CNAME is not resolving

Our DNS server answers correctly to the CNAME record provided by amplify console. So its not a case with DNS, it seems problem on retrying. Does the checking of CNAME keep repeating now?

**Comment by Joycehao19** [comment]
@gommmmmm I'm not sure what happened now... Did you check your domain name validation routes and re-adding your custom domain?

**Comment by gommmmmm** [comment]
@Joycehao19 
Thank you for your response.

Re-adding custom domain works, without changing CNAME record.
Now the "Status detail" step proceeds to "Domain activation", and failed because our domain currently points to another CloduFront distribution (and it is in use for production environment...)

I will look into a documentation for movingan alternate domain name between CloudFront distribution.

Thank you again, I close this issue (may be reopen if alternate domain name matters).

**Comment by gommmmmm** [comment]
Hello again, I have another question. Is there any way to use wildcard domain name in Amplify Console's domain setting?

I read a documentation on CloudFrotn ["Move a subdomain name, like marketing.example.com, to another distribution"](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-move-subdomain) ant can't follow the instruction because Amplify console does not accept wildcard on  creating custom domain.

Or, is it necessary to contact AWS support as mentioned in the next section of the document?

**Comment by Joycehao19** [comment]
@gommmmmm We currently do not support wildcard subdomains. Would you mind tell us why you want this feature?

**Comment by gommmmmm** [comment]
@Joycehao19 
Thank you for your response, we are in such situation:
* Our domain (ex. example.com, www.example.com) is currently hosted with CloudFrront + S3, and it is in production
* To move www.example.com to another CloudFront distribution, the document above says setup `*.example.com` on new distribution and change DNS record of www.example.com to point to new  distribution
* Amplify console does not allow wildcard in domain settings

It's not fundamentally an Ampify problem, but is fthere are any ways to achieve this?

**Comment by gommmmmm** [comment]
@Joycehao19 
Sorry, forgot to reopen with my comment.

**Comment by Joycehao19** [comment]
Hi @gommmmmm Can you open a new ticket of wildcard feature request? We can discuss there. We will close this issue for now. Thank you!
