### ISSUE TITLE
SSL verification is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by doublebiz** [aws-amplify/amplify-console#463]
**App Id**: d22qcbcy4d7mcb
**Region**: ap-southeast-1
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Joycehao19** [comment]
Hi @doublebiz  what is the error message?

**Comment by nimacks** [comment]
Hi @doublebiz, your domain seems to be now available. Please let us know if this is not the case and feel free to reopen.
