### ISSUE TITLE
SSL verification is Running - [SSL verification takes so much time still waiting for it ]

### ISSUE THREAD

**Issue by mastermeric** [aws-amplify/amplify-console#465]
**App Id**: d3nlic1hb9mit2
**Region**: us-east-2
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
During my custom-domain defination in Amplify; 
"SSL verification" stage still is Running - takes so much time still waiting for it.

**Error message**
There is no error message.

**Comment by Joycehao19** [comment]
@mastermeric Sorry to hear that you're having issues of custom domain setup. Can you try remove and re-attach the custom domain? Let us know if this does not resolve your issue.

**Comment by mastermeric** [comment]
Hello Joyce Hao, thanks for caring the issue.
Yes thats right; i was also trying to retaking the actions, and yes, it was kind of mistyping the url somehow added extra suffix at the end of url.
Now it is ok.

**Comment by Joycehao19** [comment]
Great!
