### ISSUE TITLE
Mochawesome updated to 5.0.0 introduces a breaking change.

### ISSUE THREAD

**Issue by patleeman** [aws-amplify/amplify-console#466]
** Please describe which feature you have a question about? **
Cypress tests using mochawesome.

** Provide additional details**

Just a heads up, if you set up your cypress tests per the [tutorial](https://aws.amazon.com/blogs/mobile/run-end-to-end-cypress-tests-for-your-fullstack-ci-cd-deployment-with-amplify-console/) you may have added this command to your build:

```
npm install wait-on mocha@5.2.0 mochawesome mochawesome-merge mochawesome-report-generator
```

[Mochawesome just dropped v5.0.0](https://github.com/adamgruber/mochawesome/commit/1696fb952e9335ad66f2e069362fe8ac5f1669c5) today which introduces a breaking change. If you have mocha@5.2.0 installed you will get an error:

```
Error: Cannot find module 'mocha/lib/stats-collector'
```

Mochawesome 5.0.0 breaks when it doesn't find this module. 

The fix is to install a version of mocha 6.0.0 or higher which includes stats-collector. For our purposes we just omitted the 5.2.0 and it worked fine.

```
npm install wait-on mocha mochawesome mochawesome-merge mochawesome-report-generator
```

**Comment by patleeman** [comment]
An alternative would also be to pin `mochawesome@4.1.0`

**Comment by Joycehao19** [comment]
Thank you for reporting this! We cut a ticket in our team backlog. It's pending prioritizing now.

**Comment by Joycehao19** [comment]
We made the code change of our cypress preTest phase. If you have any questions about this, please feel free to reopen the issue! Thank you!
