### ISSUE TITLE
SSL verification is Failed - dns shows CNAME records correct per docs

### ISSUE THREAD

**Issue by provderek** [aws-amplify/amplify-console#467]
**App Id**: d2ugqfmom5tuc6
**Region**: us-east-2
**Step**: SSL verification
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I have setup CNAME records, verified DNS and everything looks correct according to documentation. But I still get failed verification.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 
We could not verify ownership of the domain. Please ensure you own the domain and choose retry. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: The status of this certificate request is "Failed". One or more domain names have failed DNS validation. Please check your domain name validation routes and try re-adding the custom domain to your app. Learn more: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-troubleshoot-guide

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.
![Screen Shot 2020-02-26 at 2 37 29 PM](https://user-images.githubusercontent.com/19539030/75319093-ea7b8380-58a6-11ea-965c-eee4ac139f61.png)
![Screen Shot 2020-02-26 at 2 30 32 PM](https://user-images.githubusercontent.com/19539030/75319106-f23b2800-58a6-11ea-97c0-89e9169ff1ce.png)

**Comment by Joycehao19** [comment]
@provderek Sorry that you are having custom domain issue. Could you please double check your domain name validation routes and try re-adding the custom domain to your app?

**Comment by provderek** [comment]
The routes are correct as you can see in the photos. I could never get this to work. I gave up and added my domain to route53 and it works fine. I guess a good way to keep users in aws services...
