### ISSUE TITLE
SSL verification is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by proghjy** [aws-amplify/amplify-console#47]
**App Id**: d45uutat1g8mv
**Region**: ap-northeast-2
**Step**: SSL verification
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by VividKnife** [comment]
From my research, at this moment, your DNS verification record has been successfully added. You can go back to the Amplify Console Domain management page and click `Re-Try`.

**Comment by proghjy** [comment]
Hi @VividKnife I tried again but repeated the same failure.

**Comment by VividKnife** [comment]
Which DNS provider you are using? Did you make sure you have already added all required DNS record to the DNS provider? From my end, I can't see any issue that causing it to fail. I might just ask you to try another time.

**Comment by proghjy** [comment]
I'm using Rout 53

**Comment by proghjy** [comment]
DNS record type i have is:
A, NS, SOA, TXT, CNAME

**Comment by proghjy** [comment]
I have succeeded in distributing [salondecode.io](https://salondecode.io)
solved it by adding mx record.
Thank you all
