### ISSUE TITLE
https://domain.com does not work not https://www.domain.com works

### ISSUE THREAD

**Issue by ismaelrumzan** [aws-amplify/amplify-console#471]
**App Id**: d2nja3afindwx2
**Region**: Frankfurt
**Step**: Completed
**Status**: Available

>**Note**: 
I set up a React PWA with custom domain - I set up the domain and everything says it's working with no errors

**Issue/question**
However, browsing to https://mydomain.com does not work but https://www.mydomain.com works fine. I would like both to work as I've connect my root domain to amplify

**Error message**

**Note**: Be sure to check the message for sensitive information. 

**Additional information**

**Comment by nimacks** [comment]
@ismaelrumzan, in order for your root domain to work, you'll need to configure an ANAME record.

More details are provided here : https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html

```Configure ANAME/ALIAS record to point the root domain (https://awesomedomain.com) to your amplifyapp domain. ANAME records enable you to point the root of your domain to a hostname.```

**Comment by nimacks** [comment]
@ismaelrumzan , did you give this a try?

**Comment by Athena96** [comment]
Closing this issue for now, please feel free to reopen if you are still facing issues.
