### ISSUE TITLE
How to deploy customized resolvers?

### ISSUE THREAD

**Issue by PerrySong** [aws-amplify/amplify-console#473]
** Please describe which feature you have a question about? **
Hi I am new to Amplify. I added some customized logic to my resolver using VLT. How should I configure my build settings so that the resolvers will be updated when I push the changes to my branch?  
Thanks!

** Provide additional details**

**Comment by nimacks** [comment]
@PerrySong , you do not need any additional configuration to your build settings. If you are modifying an autogenerated resolver, running the `amplify push` command should be enough to push your changes.

**Comment by nimacks** [comment]
@PerrySong, let us know if you have any further questions.
