### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by ecliman** [aws-amplify/amplify-console#474]
**App Id**: d29ange6273dwa
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Cybergenik** [comment]
Using Route 53, after creating hot zone for my purchased domain I added that domain through the Amplify Console domain management. SSL Creation passed, now its been stuck on SSL Configuration. Tells me to check that the CNAME record exist. I checked my records set for my domain on Route 53 and it's been set, but its still stuck on SSL Configuration...

**Comment by nimacks** [comment]
@ecliman, it looks like your app no longer exists. If you re-created the app, please send us the new appId.

**Comment by nimacks** [comment]
> App Id: d1aq7qsfzxafsb
> Region: ?
> Step: SSL Configuration
> Status: loading
> 
> Issue/question:
> Using Route 53, after creating hot zone for my purchased domain I added that domain through the Amplify Console domain management. SSL Creation passed, now its been stuck on SSL Configuration. Tells me to check that the CNAME record exist. I checked my records set for my domain on Route 53 and it's been set, but its still stuck on SSL Configuration...

@Cybergenik  In order to troubleshoot further you'll need to provide the region your app was created in.

**Comment by Athena96** [comment]
Closing this issue for now, please re-open if you are still facing issues.
