### ISSUE TITLE
Webhooks setup using CLI don't show in Amplify Console 

### ISSUE THREAD

**Issue by poolieweb** [aws-amplify/amplify-console#475]
AWS Cloudformation does not yet have the functionality to produce webhooks for incoming events. (In this case a headless CMS). Therefore after a successful Amplify stack is created, a webhook is created using the following command. 

```aws amplify create-webhook --app-id XXXXXXXXX --branch-name XXXXXX```

And returns the the following:

```
 "webhook": {
        "webhookArn": "arn:aws:amplify:eu-west-2:xxxxxxxx:apps/xxxxxx/webhooks/xxxxxx",
        "webhookId": "xxxx-xxxxx-xxxx-xxxx-xxxxx",
        "webhookUrl": "https://webhooks.amplify.eu-west-2.amazonaws.com/prod/webhooks?id=xxxxx",
        "branchName": "master",
        "createTime": 1582636458.156,
        "updateTime": 1582636458.156
    }
```
However this does not appear in the AWS Amplify Console UI.

<img width="1167" alt="Screenshot 2020-03-02 at 13 09 43" src="https://user-images.githubusercontent.com/160812/75679260-2dfb3680-5c87-11ea-9570-e4afc6e4143e.png">

Is this expected or is there an alternative CLI call?

**Comment by nimacks** [comment]
@poolieweb, can you try refreshing the page?

**Comment by nimacks** [comment]
@poolieweb , did refreshing the page work for you?

**Comment by poolieweb** [comment]
No, refreshing the page did not work.

**Comment by Athena96** [comment]
Hi @poolieweb I was not able to reproduce the issue. Can you try deleting the webhook and then re-adding it.
Also check that your aws cli is configured with the same aws account as your Amplify app is associated with (aws sts get-caller-identity)
