### ISSUE TITLE
[ERROR]: Failed to deploy; after successful build

### ISSUE THREAD

**Issue by AndriiChubariev** [aws-amplify/amplify-console#477]
Hi,
I'm using Amplify to host a website built with GatsbyJS. Today I'm constantly facing an issue when the deploy just fails, after the successful build. The Deployment log looks like this:
```
2020-03-02T18:58:20 [INFO]: Skipping upload of existing file workbox-v4.3.1/workbox-window.prod.umd.js.map
2020-03-02T18:58:20 [INFO]: Updating Edge config
2020-03-02T18:58:20 [ERROR]: Failed to deploy
2020-03-02T18:58:20 [INFO]: Deployment finished.
```

My app id is
d3pfqr9ua6sb81  
https://eu-central-1.console.aws.amazon.com/amplify/home?region=eu-central-1#/d3pfqr9ua6sb81/develop/101?step=DEPLOY

I would be very grateful If somebody could tell me if it is a problem with my app or transient AWS issue.

Thanks

UPD: 
I have same story as here: https://github.com/aws-amplify/amplify-console/issues/101

**Comment by nimacks** [comment]
@AndriiChubariev, it looks like your builds are succeeding again. Please confirm.

**Comment by AndriiChubariev** [comment]
Hi @nimacks 
Thanks for a response.

I have disconnected my **develop** branch and now have only **master**. Indeed, now build works.

Was it a transient issue?
Will it continue working if I re-connect develop branch again?
My build artifact is quite large: 1.0 ~ 1.5 GB, can it somehow cause the issue?

**Comment by nimacks** [comment]
There is a known issue for builds which have very large file sizes. You can track this here https://github.com/aws-amplify/amplify-console/issues/115.

The workaround we recommend to customers at the moment is to delete unused branches in their app.

We are actively, working on a fix for this issue.

**Comment by AndriiChubariev** [comment]
@nimacks 
Once again, thanks for a response. 
I'm closing this issue and will keep an eye on https://github.com/aws-amplify/amplify-console/issues/115
