### ISSUE TITLE
Question regarding backend environment provisioning

### ISSUE THREAD

**Issue by nagey** [aws-amplify/amplify-console#479]
Hi there.

We have an app that requires the usage of a custom graphql transformer to deploy. We've packaged this transformer as a github package (and stored our GH access token in secrets manager, natch).

We're trying to accomplish deployments with backend environments that are maintained by the console.

We had, perhaps naively, assumed that the `amplifyPush` script would be an analogue of `amplify push` — though it appears that it's only running `amplify env init`.

At this point, my understanding of how the cycle works for an auto-deployed branch is thus:
1. New branch matching pattern is detected
1. New deployment bucket is provisioned
1. If backend environment is "Create new environment" then the following occurs
    1. some sort of ecr container is spun up (*important)
    1. amplify env init (to create new env)
    1. amplify push (to provision all resources in the env as are configured in source)
1. front end deployment then occurs as follows:
    1. the ecr build container is spun up
    1. the amplify.yml script is processed
    1. build artifacts are copied to the deployment bucket 
    1. CloudFront deployment details are updated to point to the new bucket

My questions is as follows:
* is the container spun up in 3.i. the same as the container that is spun up in 4.i.? If this is the case, we can add our custom package to that container, and it should be able to push our env

tagging @jdonaghue for visibility

**Comment by nimacks** [comment]
@nagey, Yes, we provision a single Linux docker container (outlined in our Provision step) to complete your backend and frontend builds, and you can control the behavior of this container the way that you would any other Linux container via the commands in your build spec. (amplify.yml).
Feel free to close this ticket if you clear on this now.
