### ISSUE TITLE
[AWS CLI] Explanation of "Stage" Property for Branch Environments

### ISSUE THREAD

**Issue by jhoffmcd** [aws-amplify/amplify-console#483]
** Please describe which feature you have a question about? **

We use the AWS CLI to automate a fair number of Amplify actions. There is very little definition of the commands and properties that are part of that tool. For example:

`create-branch` can accept a `--stage` argument with the following values:

```
Possible values:

PRODUCTION
BETA
DEVELOPMENT
EXPERIMENTAL
PULL_REQUEST
```

What are the effects of each stage in a branched environment? I can assume `PRODUCTION` probably provisions resources in a way that is optimized for production but what are the other designations actually doing?

** Provide additional details**

https://docs.aws.amazon.com/cli/latest/reference/amplify/create-branch.html

**Comment by nimacks** [comment]
A stage in the context of a branch is a designation or label which indicates the purpose of that branch. By default each App in the Amplify Console is required to have a mainline branch that is the live (or production) version. The other stage labels give users the ability to customize their CI/CD workflow but do not inherently modify the out of box behavior for builds.

**Comment by jhoffmcd** [comment]
@nimacks Great! Thank you for the clarification. I just wanted to make sure I was optimizing our env setups.
