### ISSUE TITLE
Files with same content generated after running "amplify env pull --restore"

### ISSUE THREAD

**Issue by 112Cracker** [aws-amplify/amplify-console#484]
**Issue/question**
I am setting up an amplify project. I cloned a existing git repo first.
And I ran `amplify configure` within my project folder and created a new IAM user on aws.
After that, I ran `amplify init` and select a existing environment that have been created by my colleagues to initialize my amplify project.

The problem is when I ran `amplify env pull --restore`, there will be duplicated files generated in several minutes. For a file named "file.json', the file with duplicated content will be "files 2.json". Always have a number like 2 or 3 appending at the end of the previous filename.

**Additional information**
OS: macOS Mojave
node version: 12.16.1
aws-amplify: ^1.1.36

I found a similar issues here but is not exactly same to my situation:
https://github.com/aws-amplify/amplify-cli/issues/3153

**Comment by UnleashedMind** [comment]
Does it resolve your issue if you try what @stefangomez suggested in the aws-amplify/amplify-cli#3153 by giving the terminal full disk access?
