### ISSUE TITLE
Domain activation is Failed - [unable to check correct dns records]

### ISSUE THREAD

**Issue by mtorriani** [aws-amplify/amplify-console#486]
**App Id**: d18ncbl5iq51vc
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Unable to check DNS requirements

**Issue/question**
My configuration is in "Domain activation is Failed" status. The error message suggests that I could have made a mistake in DNS configuration. But I cannot check the correct configuration because in the "Action" menu the item "View DNS Records" is not enabled. How can I check the correct records?

**Error message**
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by KrustyHack** [comment]
Ay,

Your custom domain already has a DNS record which point to another one CloudFront distribution than Amplify one.

For this error I've deleted my DNS records, waited DNS propagation and run again custom domain add on Amplify.

**Comment by Joycehao19** [comment]
Hi @mtorriani , do you still have this issue?
