### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Ravenloup** [aws-amplify/amplify-console#487]
**App Id**: d2bmi4pok4x5k7
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by KrustyHack** [comment]
Ay,

Does your custom domain is already in use in a CloudFront distribution ? I got the same problem because one of my CloudFront has CNAME in it and when I try to add custom domain on Amplify I got your error.

**Comment by Ravenloup** [comment]
I was using CloudFront but I deleted them to use Amplify but still getting this error

**Comment by KrustyHack** [comment]
Ay,

Does your domain is registered in AWS Cert Manager ? I already got an error with a domain already used on Cert Manager too.

**Comment by cslogan-red** [comment]
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

These guides are helpful for getting started with custom domains, for existing domains there are number of steps that will need to be completed (as outlined in the docs above) depending on your current hosting and DNS providers.

A CNAME alias (mydomain.com, sub.mydomain.com) can only be associated with a single CloudFront distribution at a time, if you receive this error then the domain is already associated with another CF distribution (either within the same AWS account, or potentially in a different account) and must be disassociated from the previous distribution before the distribution created for you by Amplify Console will work, the docs help outline how to do this (and you may need to check more than one account if you or your organization owns multiple accounts)

Additionally, if you manage your domain through Route53, make sure to clean up any hosted zone CNAME or ALIAS records that point to the old distribution. After completing the above, I would remove the domain from Amplify Console and start the flow over.

**Comment by Athena96** [comment]
Closing this issue, please feel free to re-open if you are still having issues.
