### ISSUE TITLE
Domain activation is Failed - CNAME

### ISSUE THREAD

**Issue by danielchoi** [aws-amplify/amplify-console#488]
**App Id**: dr9e9wwopj7aw
**Region**: ap-northeast-2
**Step**: Domain activation
**Status**: Failed

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
I tried removing all the CNAMES before setting up. 
Tried deleted custom domain and restarted the process

**Comment by KrustyHack** [comment]
Ay,

Does your custom domain is already in use in a CloudFront distribution ? I got the same problem because one of my CloudFront has CNAME in it and when I try to add custom domain on Amplify I got your error.

**Comment by danielchoi** [comment]
@KrustyHack thx, Found my problem
I didn't have cloudfront in the current aws account,  but had existing cloudfront setup on that custom domain on my personal aws account. (I assumed deleted s3(static hosting) would remove the cloudfront)
