### ISSUE TITLE
Angular routing going wrong

### ISSUE THREAD

**Issue by KrustyHack** [aws-amplify/amplify-console#489]
** Please describe which feature you have a question about? **

Actually I have an Angular app with a working routing :

myapp.com/ is home
myapp.com/auth/signin is signin page

When I go on /auth/signin through Angular routing, no problem. But when I go directly to /auth/signin or if I'm already on /auth/signin and refresh page, I got this :

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>6F7B0AEF5C90BB18</RequestId>
<HostId>
s/9h0NkmYgltzWSYiN9UgwQ+8B3Pn2LZJbD0s5/hbRrkrLo6WjKTzEEdxGdCtBpqIpbtfGS6mm8=
</HostId>
</Error>
```

So I've added redirection through Amplify console and managed to get rid of error with something like that : https://nimb.ws/1tak03

But if I choose 200 rewrite it doesn't work... I can only have my Angular app properly working on /my/path with a redirect from <*> to /index.html with 404 rewrite...

Can someone explain me ? Am I missing something ?

** Provide additional details**

Actually as a workaround I've enabled hosting on my Amplify app and I manage redirect through S3/Cloudfront rules... But it's not what I want, because now I must build myself and publish myself my app because Amplify Console use a managed S3 (if I understand well) and auto build push to this managed S3, not to the "hosting" S3.

**Comment by KrustyHack** [comment]
Ay,

To solve this problem, I've added this redirection in my Amplify Console :

`</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>`

**Comment by florianbaer** [comment]
@KrustyHack Can you reupload the CF File please?

**Comment by KrustyHack** [comment]
Ay,

<https://nimb.ws/BiXlUk>.

**Comment by BrianHHough** [comment]
Hey everyone! I'm currently working on an Angular project and the redirects is life saving, but with this angular project, when I add the amplify routing redirect, it completely changes the fonts across the app. Has anyone experienced this?

As soon as I remove the redirect, the font styles return but then routing is lost... :(

**Comment by KrustyHack** [comment]
Ay @BrianHHough,

What is the extension of your fonts files ? Check if it exists in the snippet I put above : https://github.com/aws-amplify/amplify-console/issues/489#issuecomment-596192908
