### ISSUE TITLE
Domain activation is Failed - "One or more of the CNAMEs you provided are already associated"

### ISSUE THREAD

**Issue by kelsonic** [aws-amplify/amplify-console#490]
**App Id**: d2dfxsbe2c2785
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

My domain is on Google Domains at the moment. I've included the 2 CNAME records and added the subdomain forwarding as documented. I keep getting the below error message and would like to resolve this.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

>**Error message: One or more of the CNAMEs you provided are already associated with a different resource.**

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by kelsonic** [comment]
Noticing there's other people who have the same issues (https://github.com/aws-amplify/amplify-console/issues/488, https://github.com/aws-amplify/amplify-console/issues/487, I'm now following those issues as well) 🙂

**Comment by KrustyHack** [comment]
Ay,

Is your domain already used in a CloudFront distribution ? If I remember I got this error because I already got a CloudFront distribution with a CNAME. Or I was trying to add a domain to a CloudFront distribution but domain was already used on Amplify.

**Comment by cslogan-red** [comment]
Hi @kelsonic , it looks like you've since deleted that app, if you're still having trouble with a new app, feel free to post the app Id and region here and I can help you take a look.

**Comment by kelsonic** [comment]
Thank you @cslogan-red!
