### ISSUE TITLE
Amplify Console should support the "[ci skip]" or "[skip ci]" commit message convention

### ISSUE THREAD

**Issue by josh-tncarry** [aws-amplify/amplify-console#491]
**Is your feature request related to a problem? Please describe.**

Using automated release management tools like `semantic-release` often involves pushing commits back to the repository (updated package.json, changelog, tags, etc...)

Typically these commits result in a message that includes a `[skip ci]` or `[ci skip]` message to indicate this commit is not intended to trigger a build.

Amplify Console currently doesn't honor this, causing a double build. Once for the change commit, and another for the automated commit during the build.

**Describe the solution you'd like**

I can see two possible solutions for this:
- Amplify Console would automatically honor the `[skip ci], [ci skip]` commit message tags.
- The ability to configure a way to ignore commits based on some kind of rule (contains "xyz" in the commit message).

see: [semantic-release git plugin docs](https://github.com/semantic-release/git)

**Comment by swaminator** [comment]
@josh-tncarry we are updating the AWS docs to add the command. We do in fact support this with `[skip-cd]`: https://github.com/awsdocs/aws-amplify-console-user-guide/blob/master/doc_source/build-settings.rst#skip-build-for-a-commit

**Comment by CodySwannGT** [comment]
FYI - this suddenly stopped working for us. Even if we push with "[skip-cd]", the build still kicks off

**Comment by ganipcanot** [comment]
@CodySwannGT Could you share any more details?

What git provider are you using? (github, codecommit, bitbucket etc)
Could you share your appId/region?

Did you include the `[skip-cd]` in the description or in the actual commit message?  [It has to be part of the commit message itself](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#skip-build-for-a-commit).

**Comment by CodySwannGT** [comment]
codecommit repo
us-east-1
appId d1dpmyfrkj4dmc

skip-cd is part of the commit message itself - added via the commit-msg hook

````
echo "$(cat $1) [skip-cd]" > $1
````

**Comment by giricr** [comment]
[skip-cd] is supposed to save money from unwanted builds. AWS should take this on priority at-least for dignity sake! i dont like it when malfunctioning feature cost us money and its not even our mistake.

**Comment by jaubrey-ebar** [comment]
I confirm that '[skip-cd]' in the commit still does not work with CodecCmmit in us-east-2 as of Sept 27, 2021. I pushed such a commit and the CI/CD was triggered.

The amplify-console-ug.pdf page 39 claims it works:
> Skip build for a commit:
> To skip an automatic build on a particular commit, include the text [skip-cd] at the end of the commit message.

**Comment by daniel-zero** [comment]
It should be possible to also use [skip ci] at the end of commits because GitHub Actions and other CI's are using the message to detect if a build should be skipped.
