### ISSUE TITLE
AWSURL Validation

### ISSUE THREAD

**Issue by bassrock** [aws-amplify/amplify-console#497]
It appears that the AWSURL type is not properly validating `.blog` domains. If I try and send `http://foo.blog/` as the field value for an AWSURL parameter it returns the following: 

```
{
  "data": null,
  "errors": [
    {
      "path": null,
      "locations": [
        {
          "line": 32,
          "column": 18,
          "sourceName": null
        }
      ],
      "message": "Validation error of type WrongType: argument 'input.url' with value 'StringValue{value='https://foo.blog/bar'}' is not a valid 'AWSURL' @ 'updateInput'"
    }
  ]
}
```

However, if I change `.blog` to `.com`, `.io`, `.net` it succeeds.

**Comment by cslogan-red** [comment]
This is not something we control via Amplify Console, an internal case has been created with the AppSync team.
