### ISSUE TITLE
SSL verification is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by lengshi01** [aws-amplify/amplify-console#498]
**App Id**: d2xwd9qnua0lgi
**Region**: us-east-2
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by cslogan-red** [comment]
Hi @lengshi01 , it appears you've since deleted that app, let us know if you're still having trouble with a new app.

**Comment by Athena96** [comment]
Closing this issue, please feel free to re-open if you are still having issues.
