### ISSUE TITLE
Domain activation is Failed - One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by knightz007** [aws-amplify/amplify-console#499]
**App Id**: d1cemn72xtnv5b
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

Error message
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

Notes:-
The domain exists in Azure so the cname was already added in Azure and "SSL Verification" was successfully completed.

**Comment by cslogan-red** [comment]
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-third-party

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

_**Please note, even after completing the below steps, it can take up to 48 hours for your third party DNS provider changes to propagate and properly reflect in Amplify Console.**_

These guides are helpful for getting started with custom domains, for existing domains there are number of steps that will need to be completed (as outlined in the docs above) depending on your current hosting and DNS providers.

In the case of a third party DNS provider that you are still using, you must configure your CNAME verification (which looks successful) and ALIAS (A) records before your domain can become available in Amplify. Your domain's current A record still resolves to a non-Amplify address.

Per the first doc above, make sure the A record is configured with your Azure DNS provider and restart the validation process (or disconnect and reconnect the custom domain) in Amplify Console. You will also need to configure an additional CNAME record that points traffic from your custom domain to the Amplify Console hosted URL, you can do this at the same time (if hosting production traffic, it's recommended to wait until the ALIAS record resolves before attempting this step) or after the domain becomes available.

**Comment by Athena96** [comment]
Closing this issue, please feel free to re-open if you are still having issues.
