### ISSUE TITLE
Is backend env name available as an environment variable?

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-console#500]
** Please describe which feature you have a question about? **
Since in the Amplify console, we already connect each frontend with a backend, it appears we still need to do `amplifyPush -e $BACKEND_ENV --simple` in the deploy script. 

Does such an environment variable exist that tells us which backend is configured to be used with the branch, as set by us in Amplify console? I see env variable of USER_BRANCH, but not the beackend.

**Comment by cslogan-red** [comment]
When connecting you Git repo's branch to Amplify Console, if you specify a custom name for your backend environment or choose to reuse an existing one, we store the name of the backend environment in the USER_BRANCH env variable.

Amplify Console presently only utilizes this variable, and the `amplifyPush` script, on your backend's very first build, and there is no need to pass the environment name directly.

**Comment by hisham** [comment]
I tried this but it appears AWS Amplify sets USER_BRANCH to my local git branch name and not the backend env.

**Comment by cslogan-red** [comment]
That would have happened when you first connected the branch, if you did not provide a custom name or select an existing environment checked in to your repo's team-provider file, the console will fall back to using your branch name.

If the backend environment you'd like to use shows up in the "Backend environments" tab, you can edit the front end environment to point to that backend environment from the "Frontend environments" tab, confirm the change, and trigger a new build to persist the backend environment link.

If it does not, you can disconnect that branch from Amplify Console and walk through the connect flow again, or you can manually edit the USER_BRANCH env variable to point at the environment you'd like to use.

**Comment by hisham** [comment]
I disconnected the branch from Amplify Console and reconnected it again, USER_BRANCH is still the branch name and not the connected backend name. And yes the backend is listed under backend environments in AWS Amplify. 

I guess I'll go the overriding USER_BRANCH env var route.

**Comment by hisham** [comment]
I even tried to connect the branch with backend in the aws cli. Still stuck with USER_BRANCH being the branch name and not backend env.

**Comment by hisham** [comment]
Also running get-branch via the aws cli does not return the environment variables for that branch even though documentation says so: https://docs.aws.amazon.com/cli/latest/reference/amplify/get-branch.html

**Comment by hisham** [comment]
Actually, for one of my branches it doesn't, for all my other branches it does but it's empty: 

`        "environmentVariables": {},
`

**Comment by cslogan-red** [comment]
Hi @hisham , when you walk through connecting a branch to Amplify console that has an Amplify backend, you'll get the following screen which asks you to select a backend environment, if you choose nothing, or you choose to create a new env and don't provide a name, we use the name of your branch as the name for the backend env to be created and store it in USER_BRANCH:

<img width="748" alt="Screen Shot 2020-03-12 at 11 08 58 AM" src="https://user-images.githubusercontent.com/1307688/76554547-4e7b7b80-6453-11ea-8880-e5384192588d.png">

If you chose an existing environment from the list, then we'll store the name of that env in USER_BRANCH and use it during build time. If you create this branch from our public API, the value likewise defaults to the name of the branch. 

<img width="713" alt="Screen Shot 2020-03-12 at 11 09 27 AM" src="https://user-images.githubusercontent.com/1307688/76554631-6c48e080-6453-11ea-9656-98f3bbcec355.png">

As mentioned previously, if your backend environment is already listed in the "Backend environments" tab, then from the "Frontend environments" tab, you can associate that backend to any frontend branch from the "Edit" dialog and then triggering a build after saving the change.

<img width="564" alt="Screen Shot 2020-03-12 at 11 09 58 AM" src="https://user-images.githubusercontent.com/1307688/76554872-d6618580-6453-11ea-831f-b4ccb2285f78.png">

<img width="609" alt="Screen Shot 2020-03-12 at 11 10 34 AM" src="https://user-images.githubusercontent.com/1307688/76554881-dc576680-6453-11ea-9e2c-7f8325c6cda3.png">

If you aren't seeing the backend environment dropdown or "Edit" button, it's likely that when you originally connected your app to Amplify Console, we were unable to determine whether or not it had an Amplify backend. Your Amplify backend must be checked into the repo of your frontend app at the time you connect your app in order for us to determine whether or not it has an Amplify backend. You can reconnect your app (you can reconnect the same repo multiple times) from within Amplify Console and walk through the flow again to get this working as expected.

**Comment by cslogan-red** [comment]
Likewise, environment variables are only stored at the app level by default, and only overridden to each branch if configured that way. USER_BRANCH is configured as a branch override by default when/if it is created.

**Comment by hisham** [comment]
Hi @cslogan-red yes I went through all the steps in your screenshots and my backend envs were listed in the select boxes and I selected a backend env. 

The only different I ran into when going through the screenshots is my "Next" button never enables even after selecting a branch and backend env. I had to enable it by modifying the html in the browser. Then everything goes through. I did open a support case about it with AWS but then closed it after I found a workaround. 

But that doesn't seem to be related to this issue, because I followed the same process with the aws cli and USER_BRANCH is still not set to backend env. 

<img width="325" alt="amplify-console 2020-03-12 12-45-32" src="https://user-images.githubusercontent.com/81853/76556613-8092da80-645f-11ea-9435-3c941d23d06d.png">

**Comment by cslogan-red** [comment]
Yes, thanks for reporting, the next button disabled is a known issue we are tracking and happens when you connect multiple branches before your Git provider's Oauth token expires, if you reload the page (or wait for the short lived token to expire), the button will be enabled.

That is unrelated and modifying the HTML directly is not a recommended approach, reloading the page ensures the flow is initialized properly.

Regardless, to clarify, USER_BRANCH is only set to the name of the backend env from the Console, not from our API, the API defaults this value to your branch name.

I would disconnect the branch in the Console and refresh your browser, and then reconnect the branch. Whatever backend environment you select will be set as a USER_BRANCH env variable once the branch is connected. If that's not the behavior you're seeing, feel free to email at aws-amplify-customer@amazon.com so we can take a look at what you're seeing.

**Comment by swaminator** [comment]
@hisham please track the progress of next button here https://github.com/aws-amplify/amplify-console/issues/446

**Comment by helloPiers** [comment]
Having same issue - firstly, the (undocumented?) USER_BRANCH is not set at all, however I connect the branches. There _is_ a variable AWS_BACKEND_ENVIRONMENT_ARN which is the full ARN of the backend. 

But secondly, I don't immediately see why amplifyPush would default to the *front-end* branch name, except there must be a strong assumption by the author that the *backend* environment name is the same as the front-end/git-branch name. 

I think I will script something off AWS_BACKEND_ENVIRONMENT_ARN in order to make sure the right backend is referred to. Can I rely on that env var? 

(This is just to get aws-exports.js into the build, in fact, but it seems to require this "push" to do that.)

**Comment by hyungjunk** [comment]
> When connecting you Git repo's branch to Amplify Console, if you specify a custom name for your backend environment or choose to reuse an existing one, we store the name of the backend environment in the USER_BRANCH env variable.
> 
> Amplify Console presently only utilizes this variable, and the `amplifyPush` script, on your backend's very first build, and there is no need to pass the environment name directly.

Is this documented or officially announced? I am relying on USER_BRANCH value to which database connection is made in my App, but I am afraid if it would change in the future.
