### ISSUE TITLE
How to install private npm package as part of CD? 

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-console#501]
** Please describe which feature you have a question about? **

I have a private package needed by a Lambda of mine. I keep getting this error in the build: 

```
3804 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/<my-package>.tgz
                                 3804 verbose stack     at res.buffer.catch.then.body (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
                                 3804 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
                                 3805 verbose statusCode 404
                                 3806 verbose pkgid <my-package>@1.6.0
                                 3807 verbose cwd /codebuild/output/src314256659/src/ess-app/amplify/backend/function/EssRestAPIFn/src
                                 3808 verbose Linux 4.14.152-98.182.amzn1.x86_64
                                 3809 verbose argv "/root/.nvm/versions/node/v10.16.0/bin/node" "/root/.nvm/versions/node/v10.16.0/bin/npm" "install"
                                 3810 verbose node v10.16.0
                                 3811 verbose npm  v6.9.0
                                 3812 error code E404
                                 3813 error 404 Not Found - GET https://registry.npmjs.org/<my-package>.tgz
                                 3814 error 404
                                 3815 error 404 '<my-package>' is not in the npm registry.
                                 3816 error 404 You should bug the author to publish it (or use the name yourself!)
                                 3817 error 404 It was specified as a dependency of 'src'
                                 3818 error 404 Note that you can also install from a
                                 3819 error 404 tarball, folder, http url, or git url.

```

I tried following the instructions at https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow, http://blog.shippable.com/using-npm-private-modules-in-your-ci-workflow, and https://dev.to/taleb/amplify-private-npm-repository-1bn8

None of them worked for me. What is the recommended way to give AWS Amplify access to a private package needed by the backend?

**Comment by cslogan-red** [comment]
You should be able to store your NPM auth token as an environment variable in Amplify Console (App settings > Environment variables), aka something like NPM_TOKEN.

At build time, you can reference the env variable in your amplify.yml, (App settings > Build settings) Something like the following in your preBuild section just before your npm or yarn install command:

```
 - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
 - npm install
```

Alternatively you could add the above AFTER the install command and change `npm install` to `npm install <package name>` to just your private package to limit the scope of use of your auth token to that single package:

```
 - npm install
 - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
 - npm install <package name>
```

**Comment by hisham** [comment]
Thanks @cslogan-red, it seems something clicked and I have right token in the right .npmrc, and this part of my build is running successfully. Closing for now.

**Comment by arealmaas** [comment]
@cslogan-red  This is what's needed to make the amplifyPush use the correct NPM_TOKEN to install packages for lambdas? Doesn't seem to work on our end.. Added the NPM_TOKEN as an environment variable and added the prebuild content as you said. 

amplify version: 4.36.2

The amplify.yml file:
```yaml
backend:
    phases:
        preBuild:
            commands:
                - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        build:
            commands:
                - amplifyPush --simple
```

**Comment by arealmaas** [comment]
Seems like i have to add it for each function 🤔

**Comment by adamtheadmin** [comment]
I personally feel that it's better to store stuff like this in your secrets manager.

**Comment by amirhajimirsadeghi** [comment]
There doesn't seem to be an answer here for how to do this. I need to do this for my backend packages
