### ISSUE TITLE
Failing to pull access logs: Failed to load the datajava.io.IOException: No space left on device

### ISSUE THREAD

**Issue by patleeman** [aws-amplify/amplify-console#507]
** Please describe which feature you have a question about? **
Access Logs

** Provide additional details**
When I try to download access logs via AWS console, the logs never load. Looking at the network console I get a `500` and see the following error to the endpoint: `https://console.aws.amazon.com/amplify/api/amplify`

```
{"message":"Failed to load the datajava.io.IOException: No space left on device"}
```

ARN: `arn:aws:amplify:us-east-1:831573207012:apps/d2eetebepnv04r`

**Comment by cslogan-red** [comment]
Hi, yes, this is a known issue that is being actively developed, we'll update this thread once we have a release scheduled. In the meantime, choosing a shorter duration time window for generating logs is the recommended workaround for now. For very high volume sites, start with a 24 hour window and work your way up.

**Comment by patleeman** [comment]
Thanks for looking into this. I wasn't able to get a full 24 hour window but I'll try working up from there. Is the time specified in the interface in UTC or local timezone?

**Comment by cslogan-red** [comment]
For access logs the time in the UI is UTC (+7 PST right now), but so is the time range filter, so if your most recent logs show they're from 3/12 @ 1950, then putting 3/12/2020 @ 700PM (1900 auto converts to 12 hour equivalent) is going to return everything from 1900 forward (1900-1950).

**Comment by patleeman** [comment]
Hm, so I tried walking it up to 1 minute and It's still failing. We've been getting a lot of traffic but I'm unable to confirm via the logs.

**Comment by cslogan-red** [comment]
@patleeman we're looking into that particular instance a little further

**Comment by cslogan-red** [comment]
We are actively working on testing and deploying a fix for this issue, which is a bit different and can be fixed independently of the one I originally mentioned. I'll post an update in this thread once the fix is available in all regions.

**Comment by patleeman** [comment]
Thanks again for the quick resolution!

**Comment by cslogan-red** [comment]
We're in the process of deploying the update to all regions, it should be GA by EoD Monday, 3/16, at which point you'll be able to pull the logs again, I'll post an update once available in all regions. I would start with a 24 hour window and work your way up to the largest time frame you can pull down, we're still working on an issue for very large volume requests that will come in a separate, future release.

**Comment by patleeman** [comment]
Thanks again for the updates. Really appreciate it. 👍

**Comment by kahdojay** [comment]
Hi @patleeman we've rolled out a fix, can you give it another try and let us know if the issue persists?

**Comment by patleeman** [comment]
Hey @kahdojay,

I tried pulling 1 minute of logs and I get a bunch of timeout errors and after a few retries I get the same error.

```
{"message":"Failed to load the datajava.io.IOException: No space left on device"}
```

The UI keeps spinning and it says Fetching access logs.

**Comment by kahdojay** [comment]
Hi @patleeman thanks for confirming - I may have spoken prematurely, let me look into this some more and get back to you.

**Comment by kahdojay** [comment]
Sorted this issue offline, closing this for now, please feel free to re-open if issue persists for any other customers as well.

**Comment by patleeman** [comment]
Hey Don and Team,

Thanks again for your help on this matter.

**Comment by talebbits** [comment]
@kahdojay  Stuck at `Fetching access logs..`
Trying to get logs for ::
app_id=d19iz5bhap41u2
region=us-east-1

**Comment by simmbiote** [comment]
@kahdojay I also get stuck with " Fetching access logs..."
Is there a way to access them outside the console? Would appreciate some links for reference if so?
