### ISSUE TITLE
domain link accessible on my system but not on colleague

### ISSUE THREAD

**Issue by SudhirKaushik** [aws-amplify/amplify-console#51]
>**Note**: Intermediate in Front-end development but Noobie in Domain setup and DB setup

**Describe the bug**
When using amplify without custom domain, my link is genrated as "https://production.*********.amplifyapp.com" and works fine as expected. However, Setting up third-party domain is painful. I agree with the level of frustration mentioned in [this isse](https://github.com/aws-amplify/amplify-cli/issues/845) but not the language.

Where I am stuck? well, I added my domain to amplify, click on "Actions - > View DNS records" and copy-pasted everything in DNS record at Google domain except the "@ ANAME" in Google domain's DNS setting.

The link sudhirkaushk.com opens fine on my system but not on my friends'. 

**Screenshots**
<img width="676" alt="site fail" src="https://user-images.githubusercontent.com/8871502/62919131-5c82f400-bdbf-11e9-84dd-1bb585f2aa52.PNG">

**Comment by swaminator** [comment]
@SudhirKaushik sorry to hear about your experience. 3rd party domains such as Google do not support ANAME records. While we provide docs with workarounds for things such as the root domain, we recommend migrating your DNS to Route53 for the smoothest experience: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/MigratingDNS.html

**Comment by SudhirKaushik** [comment]
Google said I can move/transfer to Route53 after 60 days of domain registration, so I think I will wait till then.
