### ISSUE TITLE
Amplify + React 

### ISSUE THREAD

**Issue by winac** [aws-amplify/amplify-console#513]
I am using Amplify Console for the first time to spin up a react app. I do all my development locally and then push this to the Amplify Console to get it hosted. The problem is that certain things that work locally don't work when hosted by Amplify. These include the favicon logo not showing and certain images not showing (this is really weird because some show some don't). I have no idea why this is the case, I am not getting any errors in the console for either of the two apps (the one hosted locally and on amplify). 

Any ideas what the problem might be and how I can fix this?

(I am using react 16.5.2)

**Comment by swaminator** [comment]
Try setting the following redirect rule: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa

**Comment by winac** [comment]
That doesn't solve my problem. It just crashes my app when I go to a sub url

**Comment by kahdojay** [comment]
@winac can you share your appId and region?

**Comment by winac** [comment]
Region:us-east-1
appId: d3g6b6l8krgqrd
I got it working last night by using links to the images which is what I put on my master build. 
My dev build uses the local png images that don't show.

**Comment by Athena96** [comment]
Hi @winac are you still facing the issue, or is it resolved?
Also, a tip for getting your favicon to update. Change the existing `<link>` for the favicon in <repoName>/public/index.html to be:
`<link rel="icon" href="%PUBLIC_URL%/favicon.ico?v2" />`

**Comment by winac** [comment]
Hi @Athena96, I am still facing the issue as described previously. I will try out changing the favicon link but do you have any documentation to explain what adding '?v2' does?

**Comment by Athena96** [comment]
The info I shared basically [forces a favicon refresh](https://stackoverflow.com/questions/2208933/how-do-i-force-a-favicon-refresh)

**Comment by Joycehao19** [comment]
Closing this issue, feel free to reopen it if you still have questions. Thanks
