### ISSUE TITLE
Domain activation is Failed - [Domain Activation - Amplify - Failure]

### ISSUE THREAD

**Issue by joshqq** [aws-amplify/amplify-console#514]
**App Id**: d21j0af9w61fo0
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Domain registration failed. Previously it was successful, but I remove the app and add it again. However, it results in failure.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by Athena96** [comment]
@joshqq  Please see: 

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

These guides are helpful for getting started with custom domains, for existing domains there are number of steps that will need to be completed (as outlined in the docs above) depending on your current hosting and DNS providers.

A CNAME alias (mydomain.com, sub.mydomain.com) can only be associated with a single CloudFront distribution at a time, if you receive this error then the domain is already associated with another CF distribution (either within the same AWS account, or potentially in a different account) and must be disassociated from the previous distribution before the distribution created for you by Amplify Console will work, the docs help outline how to do this (and you may need to check more than one account if you or your organization owns multiple accounts)

Additionally, if you manage your domain through Route53, make sure to clean up any hosted zone CNAME or ALIAS records that point to the old distribution. After completing the above, I would remove the domain from Amplify Console and start the flow over.

**Comment by Joycehao19** [comment]
It seems like your domain works now. Closing this issue, feel free to reopen if you face the same issue. Thanks!
