### ISSUE TITLE
SSL verification is Running - Domain registered in account A pointed to amplify website on account B

### ISSUE THREAD

**Issue by w601sxs** [aws-amplify/amplify-console#516]
**App Id**: d2ifucdfz09ieg
**Region**: us-east-2
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I have a domain www.example.com registered in an AWS Account A, and a hosted zone in AWS account B that also has the amplify app. I have changed the name servers in AWS Account A and can choose the www.example.com domain in the drop-down menu of amplify, but SSL verification has been going on for more than an hour. I want to know if this set up is okay, or if I have to do something to verify.

**Error message**
"We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain."

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by w601sxs** [comment]
Update - been about 4 hours now, still the same status.

**Comment by kahdojay** [comment]
@w601sxs you might've seen this message in the console indicating that it may take longer than 8 hours:

<img width="689" alt="Screen Shot 2020-03-16 at 17 02 10" src="https://user-images.githubusercontent.com/8794073/76809650-c7a70580-67a8-11ea-97a7-e4f50887db96.png">

If it's still pending verification after 8 hours, you can check this troubleshooting doc if you haven't already to see if it helps: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#my-domain-hosted-with-a-third-party-is-stuck-in-pending-verification-state

Let me know if you've already gone through those troubleshooting steps and it's still pending.

**Comment by w601sxs** [comment]
Hi Don,

Looks like the second troubleshooting section (with respect to Route53 and
nameservers matching) applies to my case.

That is a step that I took, and this is why I was able to select my domain
from the amplify dropdrown, although the domain was registered on a
different AWS account. I have also tried deleting the domain, relaunching
the app in another region, and trying to connect the domain name again.
Now, my app id is d1o5q2rs3dom5k.

I also changed the "baseURL" in my hugo website to match the domain name.

What else can I do?

Shreyas

**Comment by w601sxs** [comment]
Hi Don,

I'm still stuck at the same stage. What do you suggest I do?

Shreyas

**Comment by w601sxs** [comment]
Still running, any tips? What do I do?

**Comment by Athena96** [comment]
Hi @w601sxs have you checked that your CNAME resolves? Following these [steps](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#how-do-i-verify-that-my-cname-resolves)

**Comment by w601sxs** [comment]
I deleted and redeployed with the same settings and I'm now live. No
changes from my end. strange.

**Comment by Athena96** [comment]
Great! Closing this issue for now. Please feel free to open if you are still having problems.
