### ISSUE TITLE
Domain activation is Failed - Added CNAMEs after a delay, and now "Retry" is not working

### ISSUE THREAD

**Issue by JohJonker** [aws-amplify/amplify-console#517]
**App Id**: d3sucvvj2fsjhr
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Domain activation is failing for my subdomain xxx.yyyy.zzz (example). I had previously tried to add it as a subdomain for my Amplify app, couldn't get it to work, and then deleted and re-added it.  Upon re-adding it, verification under "Status details" proceeds successfully up to SSL verification, then fails on the final step. I have tried the "Retry" button a couple of times, but it's not working.

**Error message**
A red banner at the top of the page shows: "We had issues connecting your custom domain: xxxx.yyyy.zzz. Please visit the Domain Management page for more information."

And then under "Status details":
"Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-"

**Additional information**
I have verified, using a DNS lookup, that the *new* CNAME record for is set up on the domain, not the old one.

**Comment by kahdojay** [comment]
@JohJonker Please see: 

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error
https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

These guides are helpful for getting started with custom domains, for existing domains there are number of steps that will need to be completed (as outlined in the docs above) depending on your current hosting and DNS providers.

A CNAME alias (mydomain.com, sub.mydomain.com) can only be associated with a single CloudFront distribution at a time, if you receive this error then the domain is already associated with another CF distribution (either within the same AWS account, or potentially in a different account) and must be disassociated from the previous distribution before the distribution created for you by Amplify Console will work, the docs help outline how to do this (and you may need to check more than one account if you or your organization owns multiple accounts)

Additionally, if you manage your domain through Route53, make sure to clean up any hosted zone CNAME or ALIAS records that point to the old distribution. After completing the above, I would remove the domain from Amplify Console and start the flow over.

**Comment by JohJonker** [comment]
Thanks for the response @kahdojay .

I don't have any Cloudfront distributions. I only use Amplify, i.e. it creates the distributions for me automatically, and I have no way of managing it directly.

I tried removing the subdomain and re-adding it, but I'm hitting the same error.

How can I force Amplify to 'release' the Cloudfront distribution, so that it can be added anew?

**Comment by kahdojay** [comment]
Hi @JohJonker I do see that the domain is pointing to a cloudfront domain but it no longer exists. Can you delete the DNS records, and if it won't cause disruption, delete and recreate the custom domain?

**Comment by Joycehao19** [comment]
Closing this issue, please feel free to reopen it if you still face custom domain issues. Thanks!
