### ISSUE TITLE
Large build logs not rendering in build window

### ISSUE THREAD

**Issue by jonvanausdeln** [aws-amplify/amplify-console#518]
A large build log is not rendering completely in the build log window on the build page.

The downloaded log file looks to be complete.  I also notice a discrepancy between the line numbers in the build log window and the downloaded log file.  The downloaded file appears to have quite a few less lines.

**Comment by kahdojay** [comment]
Thanks for reporting this @jonvanausdeln - if you are able to without disclosing any unwanted/sensitive info, could you share some screenshots and a sample repo that will reproduce the issue so we can see what you're experiencing?

**Comment by jonvanausdeln** [comment]
Sorry it took me a little bit to get back to this.  I went and looked at our builds and don't see the issue any longer.  This issue can be closed.  Thanks.

**Comment by Athena96** [comment]
Thanks, please reach out if you have any other issues.
