### ISSUE TITLE
rewrite from one amplify site to another and 403

### ISSUE THREAD

**Issue by smakinson** [aws-amplify/amplify-console#519]
** Please describe which feature you have a question about? **
I'm trying to add a rewrite under a main website Amplify app to another that generates a custom rss feed using hugo and I am seeing a 403. Perhaps I am missing something. Is it allowed to proxy between amplify apps this way?

** Provide additional details**
The rewrite:

source: /rss
target address: https://master.some_app_id.amplifyapp.com/index.xml
type: 200(Rewrite)
country code: not set

The rewrite points directly at the url that should come through but I see a 403:
403 ERROR
The request could not be satisfied.
Bad request. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

The rss generating site has one rewrite set up:
source: /<*>
target: /index.xml
type: 200(Rewrite)
country code: not set

but I have also tried it with no rules and see the same result.

Am I missing something simple?

**Comment by swaminator** [comment]
https://github.com/aws-amplify/amplify-console/issues/445

**Comment by kahdojay** [comment]
@smakinson thanks for reporting this - we're actively investigating. Are you able to workaround with a 302 redirect in the meantime?

**Comment by smakinson** [comment]
@kahdojay I am able to wait for a bit while its resolved since I am also waiting on #91 Thank you for investigating!

**Comment by stefangomez** [comment]
Having same problem here where a redirect won't work for us. we need the domain to stay the same.

**Comment by alimoeeny** [comment]
Any updates on this would be very much appreciated :)

**Comment by Athena96** [comment]
Hi @smakinson this issue has been fixed, please feel free to re-open if you are still having trouble, thanks!

**Comment by shellscape** [comment]
@Athena96 it'd be great to link to the commit or PR that fixed it. otherwise it's not a helpful close.
