### ISSUE TITLE
Custom Domain, cannot access GraphQL API

### ISSUE THREAD

**Issue by emmafass** [aws-amplify/amplify-console#52]
**Issue/question**
After adding a custom domain, I am getting a 401 status when sending requests to my graphql API.

**Error message**
```Uncaught (in promise) Error: Network error: Response not successful: Received status code 401```

**Additional information**
Warning: I am very much in the beginning stages of creating this application. 

I created my react amplify project using the CLI. I want all users to be able to read the data and authenticated users to be able to create, update, and delete. Therefore, I set up the API to use an API key. I am planning on using Cognito User Pools for authenticating users later on. 

I recently added the app to the Amplify Console via Github. I set the dev branch to deploy to a dev environment and the master branch to deploy to a prod environment. 

I added my custom domain which is registered with GoDaddy (so I had to set up Forwarding). The domain is liked to the master branch.

When I go to my custom domain, I get the 401 error. This is the same for the generated master and dev urls.

When I run `amplify publish` from the CLI, I do not get the 401 error when I check the url that publish deploys to.

The amplify.yml file for the build looks like this:
<img width="537" alt="Screen Shot 2019-08-13 at 8 04 20 PM" src="https://user-images.githubusercontent.com/13208951/62985518-a7bff580-be05-11e9-9c59-1c9feb559816.png">

When I check the logs from the last deployment, I do not see anything about setting the API key. I'm worried the API key just isn't being set or that the forwarding is causing an issue.

Any assistance would be great!

**Comment by VividKnife** [comment]
Can you share your appId?

**Comment by emmafass** [comment]
appId: d1z2w4cyfn8c3l

**Comment by emmafass** [comment]
While troubleshooting, I deleted the app and then created it again to verify I still get the same error. I do keep getting the 401 error.

https://master.d1z2w4cyfn8c3l.amplifyapp.com/ is the only url for the app now. I did not add the custom domain or dev branch this time.

**Comment by VividKnife** [comment]
By default, the Amplify Lib should automatically consume the api key in the aws-config.json which is generated after amplify push. Does your website works locally? How do you actually using the API key? Your build and app seems perfectly fine.

**Comment by emmafass** [comment]
It does work locally. The API key is just in the aws-exports.js file (which was auto-generated by the amplify CLI).

**Comment by emmafass** [comment]
I essentially rebuilt the application and made sure to add the services (auth, api) before adding the app to the Amplify Console. It is working now but still unsure what went wrong.
