### ISSUE TITLE
amplifyPush seems to create a new environment, build stuck on 'already exists'

### ISSUE THREAD

**Issue by FemkeBuijs** [aws-amplify/amplify-console#521]
** Please describe which feature you have a question about? **
amplifyPush

** Provide additional details**
My backend code is on a different location than the repository Amplify Console is located on. Below are my build settings:
```
backend:
  phases:
    build:
      commands:
        - git clone --single-branch --branch $USER_BRANCH https://$OAUTH-TOKEN@github.com/user/backend-repo.git
        - cd backend-repo
        - amplifyPush --simple
```

The build breaks with the following error:
```
2020-03-17T12:57:09.955Z [WARNING]: Error updating cloudformation stack
2020-03-17T12:57:14.964Z [INFO]: Following resources failed
                                 Resource Name: SNSRole (AWS::IAM::Role)
                                 Event Type: create
                                 Reason: snsauthcognito-develop already exists in stack ...
2020-03-17T12:57:14.965Z [INFO]: Resource Name: S3Bucket (AWS::S3::Bucket)
                                 Event Type: create
                                 Reason: **BUCKET-NAMEe** already exists in stack ...
                                 Resource Name: **IAM-ROLE** (AWS::IAM::Role)
                                 Event Type: create
                                 Reason: Resource creation cancelled
                                 init failed
```

I would like the following to happen:
With every build, checkout the latest changes in the backend repo and push that to the environment.

Is there anyone that can help me find out what is going wrong? Or even better; if there is a better way of doing the above?
If you need more information or if i'm not explaining it well enough please let me know.

Develop is connected to the develop env, and master to the production env:
![image](https://user-images.githubusercontent.com/32512274/76859696-1cef1f80-685a-11ea-96c0-721b45e077c5.png)

![image](https://user-images.githubusercontent.com/32512274/76859704-1f517980-685a-11ea-8117-b1288082b119.png)

**Comment by swaminator** [comment]
Can you try using `amplifyPush --simple`?

**Comment by FemkeBuijs** [comment]
Sorry forgot to say that that is what I initially used. When that created the above situation I became experimentative and removed it. I've updated the issue.

**Comment by kahdojay** [comment]
@FemkeBuijs This can occur if CloudFormation resources (e.g. the roles/bucket) were not deleted successfully when a backend environment is recreated. 

Can you try manually deleting the stack in CloudFormation console if it still exists?

**Comment by FemkeBuijs** [comment]
@kahdojay maybe it's a silly question, but won't removing the stack remove all its resources (table data, etc)? This is currently a running environment with data that cannot be removed.

**Comment by Athena96** [comment]
Hi @FemkeBuijs have you tried using the --environment flag with the [amplifyPush script](https://gist.github.com/swaminator/7408de774e24ecf031d0d9928f1fbae5)?
e.g. `amplifyPush --environment <ENVIRONMENT> --simple`

**Comment by FemkeBuijs** [comment]
@Athena96 thanks for your answer, I tried it and get the same error:
```Reason: **BUCKET-NAMEe** already exists in stack```

**Comment by adi518** [comment]
There's like 4-5 issues over this and still not fixed: https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+is%3Aopen+environment+exist+.

I worked around it by getting the stack info through AWS CLI.

1. Grab `amplifyPush.sh`: https://github.com/aws-amplify/amplify-console/blob/master/scripts/amplifyPush.sh.
2. Update your `amplify.yml` to use this script instead of the default `amplifyPush`.
3. Paste the following snippet below this line: https://github.com/aws-amplify/amplify-console/blob/master/scripts/amplifyPush.sh#L119.

```sh
echo "# Getting Amplify CLI Cloud-Formation stack info from environment cache"
# export STACKINFO="$(envCache --get stackInfo)"
# https://docs.amplify.aws/cli/teams/commands#import-an-environment    
BACKEND_ENV="$(aws amplify get-backend-environment --app-id ${AWS_APP_ID} --environment-name ${AWS_BRANCH})"
STACKNAME="$(echo ${BACKEND_ENV} | jq --raw-output '.backendEnvironment.stackName')"
STACKINFO=$(aws cloudformation describe-stacks --stack-name ${STACKNAME} | jq '.Stacks[0]')
STACKINFO=$(echo ${STACKINFO} | jq '.Outputs | reduce .[] as $item ({}; .[$item.OutputKey] = $item.OutputValue)')
STACKINFO="{\
    \"awscloudformation\":$STACKINFO\
}"
export STACKINFO
```

**Comment by victorccccc** [comment]
Hi, we've improved our backend build feature and `amplifyPush script` is no longer necessary. Here is the user guide to deploy backend https://docs.aws.amazon.com/amplify/latest/userguide/deploy-backend.html 

Feel free to re-open this issue if you have any question
