### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR with custom domain

### ISSUE THREAD

**Issue by mupml** [aws-amplify/amplify-console#522]
**App Id**:d1g7iclj08ak4
**Region**:eu-west-1
**Step**:Enabling custom domain
**Status**: SSL certificate valid, but invalid response from server

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

I am trying to enable SSL on my custom domain. Domain is verified and domain is active in Amplify/Route53. But when I try to access the site, I get ERR_SSL_PROTOCOL_ERROR this site is sending an invalid response. No webpage loads. The certificate is valid in the browser, but it doesn't load the webpage.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

This site can’t provide a secure connection site sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by kahdojay** [comment]
Hi @mupml, I was able to visit your custom domain and the page loads for me. Have you tried it in different browsers / networks / devices?

**Comment by mupml** [comment]
Hi, it fixed itself. I believe it had something to do with the fact I came over from a different web host and the web browser probably had something cached. Thanks for the help.
