### ISSUE TITLE
Two different accounts, but both pointing at same repo and domain?

### ISSUE THREAD

**Issue by 0luftballoons** [aws-amplify/amplify-console#523]
** Please describe which feature you have a question about? **
This might be a mistake, but we have two separate AWS accounts that will be potentially using the same Github repository, and the same domain name. This only thing that would differ are the subdomains. To summarize:
1) Both account "A" and "B" are using repository "foobar".
2) Both account "A" and "B" use the same domain name "foobar.com", but will not deploy any branches to this domain. Instead, account "A" would deploy to "a.foobar.com", and account "B" would deploy to "b.foobar.com".
3) Accounts "A" and "B" might deploy the same branches, but to different subdomains (see 2)

Can you tell me if either/both 1), 2) and 3) are technically possible?

**Comment by kahdojay** [comment]
Hi @0luftballoons yes, this should work, let us know if you run into any issues
