### ISSUE TITLE
Creating Amplify Console App

### ISSUE THREAD

**Issue by Dcalligy** [aws-amplify/amplify-console#525]
I was trying to deploy one of your fullstack samples in the Amplify Console and kept running into this error. Any tips on how to fix this issue?
![image](https://user-images.githubusercontent.com/22399678/76917275-4da27980-6899-11ea-8ec2-dc092fb907ab.png)

**Comment by kahdojay** [comment]
@Dcalligy thanks for reporting this. It seems there's an issue with the Authentication starter that we'll need to investigate - can you try a different one for the time being?

**Comment by kahdojay** [comment]
@Dcalligy can you give it another try?

**Comment by Dcalligy** [comment]
@kahdojay it worked! Appreciate your help!
