### ISSUE TITLE
Access denied for routes

### ISSUE THREAD

**Issue by indrapranesh** [aws-amplify/amplify-console#526]
After deployment using the Amplify Console, my application throws access denied error when I try to access the routes of the application.

My application  runs on XXXX.amplifyapp.com/
This page works fine.

When I try to access the routes of the app such as 
XXXXX.amplifyapp.com/login

It throws error like this

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>1C7C3381BC80AA90</RequestId>
<HostId>
AofeeNNPFTj7C/vj69cowWLQxSXojPWajANQDHCXp3i3EPi7yBlTEHejpK9tV2FPAtplWejVpoA=
</HostId>
</Error>`

**Comment by kahdojay** [comment]
Hi @indrapranesh can you share your appId and region?

**Comment by Athena96** [comment]
Hi @indrapranesh I think I know a solution for you. 
Try adding this Rewrite/Redirect Rule for your app:
**source**: </^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>
**target**: /index.html
**type**: 200

Resource: https://forums.aws.amazon.com/thread.jspa?threadID=294311&tstart=0

**Comment by Liguo-Ma** [comment]
Hi  Athena96
I do not think so your solution.
Rewrite and redirect is to navigate to 403page.html or others.
So It does not show my site
How I should solve this issue?

**Comment by ycedror** [comment]
hi: 

The error can solve change the @Athena96 source addres.. only need to change 
source: </^[^.]+$|**\**.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>  

greets
