### ISSUE TITLE
Stuck on "Retrieving deployment details..."

### ISSUE THREAD

**Issue by lucaluke88** [aws-amplify/amplify-console#530]
Hello, I have set an application and my deploy method is to manual drag and drop the web project directory inside the related upload field. All worked flawlessy for weeks until yesterday, when after the usual drag and drop, it has "frozen" at "retrieving deployment details" without completing the deploy. I have tried also with S3 zip upload, but at no avail.
Visiting the app url, it shows the previous version, sign that the deploy has not started at all.
What I can do? Does exist a log menu voice in admin panel, specifically for deploy processes, that may I missed?

**Comment by lucaluke88** [comment]
If others should find in my situation: click on branch name, and abort all active deploy processes and make a clean deploy one. All solved.

**Comment by lhovee** [comment]
I had this same issue intermittently and the issue was I was using the drag and drop option but wasn't zipping the dist directory. After creating a support ticket with AWS they let me know you have to zip it.

**Comment by azeveco** [comment]
I'm facing the same problem. I'm zipping the dist and nothing seems to work.

THe funny thing: earlier today we deployed without a problem. And before this one that is stuck, we deployed to staging environment. Now trying to deploy to production and I get this message.

Any clues?

**Comment by lucaluke88** [comment]
be sure that you zip the browser subfolder of dist in order to have the index.html and the First level files of your project as the First level of the zip (no zip with folder browser as only first level child, for clarity). Doing this, you should have a safe deploy

[Luca Costantino - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=pycl1)	[pycl1]

On October 9, 2020 at 23:25 GMT, Gabriel Azevedo <notifications@github.com> wrote:

I'm facing the same problem. I'm zipping the dist and nothing seems to work.

THe funny thing: earlier today we deployed without a problem. And before this one that is stuck, we deployed to staging environment. Now trying to deploy to production and I get this message.

Any clues?
