### ISSUE TITLE
Domain activation is Failed - register same domain in two different apps

### ISSUE THREAD

**Issue by amuresia** [aws-amplify/amplify-console#531]
**App Id**: djaaa364g371e
**Region**: eu-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I have two different Amplify applications, one of them has the root domain registered successfully. However, this one cannot register the same domain.
**Error message**
I cannot see any CNAMEs anywhere. What am I missing?
```
Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
```
**Note**: Be sure to check the message for sensitive information.

**Comment by Athena96** [comment]
Hi @amuresia wanted to confirm, you are trying to register 1 domain with 2 different Amplify apps, is that correct?

**Comment by amuresia** [comment]
Hey, yes. I just moved my DNS zone from GoDaddy to Route53. After a couple of hours and a flow restart, the issue went away. Thanks, I'll close this :)
