### ISSUE TITLE
Transfer App to different Zone (Region)

### ISSUE THREAD

**Issue by posadskiy** [aws-amplify/amplify-console#532]
** Please describe which feature you have a question about? **
Hi!
How can I transfer application from US-East (Ohio) to Europe (Frankfurt)?
I have found only one way: stop the current instance and re-create it in the new zone, set domain and routes again...
There is an easier way?

** Provide additional details**

**Comment by swaminator** [comment]
@posadskiy Unfortunately there isn't an easier way. If you want, you can define Amplify Console resources as CloudFormation so they are easily replicable: https://aws.amazon.com/about-aws/whats-new/2019/06/aws-amplify-console-supports-aws-cloudformation/
