### ISSUE TITLE
SSL verification is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by gestaodomus** [aws-amplify/amplify-console#533]
**App Id**: d3gh2a7f5s3jqq
**Region**: us-east-1
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Athena96** [comment]
@gestaodomus is the SSL verification step still running after 8 hours? If so, check out this [troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#my-domain-hosted-with-a-third-party-is-stuck-in-pending-verification-state) for registering custom domains

**Comment by Joycehao19** [comment]
Closing this issue, feel free to reopen it if you have custom domain issues! Thanks
