### ISSUE TITLE
Linting error in PreBuild step not failing the build

### ISSUE THREAD

**Issue by jonvanausdeln** [aws-amplify/amplify-console#537]
I have a lint step in my preBuild commands.  I have a case where the lint failed (as it should), but the build still went on and completed successfully.  I want it to fail the build at that point.  It was specifically in a preview build.

Here is the log snippet for the error.
```
2020-03-20T10:43:21.732Z [INFO]: $ eslint .
2020-03-20T10:43:27.252Z [INFO]: /codebuild/output/src259344021/src/preva/packages/course-provider/src/components/App/sagas.js
                                 722:49  error  Missing semicolon  semi
                                 726:24  error  Missing semicolon  semi
                                 ✖ 2 problems (2 errors, 0 warnings)
                                 2 errors and 0 warnings potentially fixable with the `--fix` option.
2020-03-20T10:43:27.283Z [WARNING]: error Command failed with exit code 1.
```

and then later the end of the build step:
```
2020-03-20T10:43:50.777Z [INFO]: # Completed phase: build
                                 ## Completed Frontend Build
2020-03-20T10:43:50.777Z [INFO]: ## Build completed successfully
```

**Comment by Athena96** [comment]
Hi @jonvanausdeln can you share your amplify.yml (Build Settings) and your package.json files. (removing any personal info). Thanks!

**Comment by jonvanausdeln** [comment]
[issue_537.zip](https://github.com/aws-amplify/amplify-console/files/4377191/issue_537.zip)
I included the files in the .zip.  Note, I removed some info from each.  Also we use a monorepo, but I left in the commands pertinent to this issue and the package being built.  You can assume the $PACKAGE var is set to "c" so it will evaluate to true.

**Comment by Athena96** [comment]
@jonvanausdeln in your amplify.yml, can you try moving your 'yarn lint' and 'yarn test' commands into the build/commands/ section, and "and" the commands like this:
```
...
build:
  commands:
    - ...
    - yarn lint && yarn test && yarn build
   - ...
```
here's a [resource](https://dev.to/rakannimer/testing-your-amplify-application-with-jest-and-cypress-1g0i) that might be useful as well.

**Comment by jonvanausdeln** [comment]
I moved to the `build` section and that works now as expected (fails on the lint error).

I am curious why it doesn't error out on the preBuild step as I would expect.  What does cause the preBuild steps to fail?

**Comment by Athena96** [comment]
Yes, sorry if it is unclear. The preBuild step is not really pass/fail, it's for installing dependencies and doing setup. e.g. `npm ci`

**Comment by Athena96** [comment]
Closing this issue, feel free to reopen if you have more questions/issues. Thanks!
