### ISSUE TITLE
SSL configuration is Running - Unsupported TLD

### ISSUE THREAD

**Issue by tmeckhoff** [aws-amplify/amplify-console#540]
**d17njfdf3hqm0z**
**us-east-1**
**SSL configuration**
**Running**

**Issue/question**
Trying to add multi level subdomain to Amplify app but it has been running for several hours. The subdomain exists as a hosted zone in Route53.

**Error message**
If there is an error message, please include it here. 

Looking at calls in Network tab the POST to `https://console.aws.amazon.com/amplify/api/route53domains` returns 400 error with the following response:

{"__type":"UnsupportedTLD","message":"base-url.com tld is not supported"} 

Our TLD is `.com` but Amplify seems to think the TLD is our base url

**Comment by Athena96** [comment]
Hi @tmeckhoff sorry you are having trouble. Can you share your apps settings on the "Domain management" page.

**Comment by Athena96** [comment]
Another question I have is, did you acquire your domain by using Rout53, or some other provider?

**Comment by tmeckhoff** [comment]
> Can you share your apps settings on the "Domain management" page.

What information from the "Domain Management" page do you need?

> Another question I have is, did you acquire your domain by using Rout53, or some other provider?

Yes, route53

**Comment by Athena96** [comment]
From the Domain Management page, I want to see how your multilevel subdomain is configured. 
Like [this](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-subdomains) from the docs.

**Comment by tmeckhoff** [comment]
> From the Domain Management page, I want to see how your multilevel subdomain is configured.
> Like [this](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-subdomains) from the docs.

Here is a screenshot
![Screen Shot 2020-03-27 at 3 16 06 PM](https://user-images.githubusercontent.com/5074013/77797789-b0d1a000-703f-11ea-9792-91ab4b845999.png)

**Comment by Athena96** [comment]
Was the root URL ("uat.postlight-lmm.com") added and working before you tried adding the subdomain?

**Comment by tmeckhoff** [comment]
> Was the root URL ("uat.postlight-lmm.com") added and working before you tried adding the subdomain?

We originally had this domain `screen-app.uat.postlight-lmm.com` as a record for our root domain hosted zone `postlight-lmm.com`. But Amplify errored when I tried adding `screen-app.uat` as a domain prefix to the root domain. So I created a new hosted zone for the subdomain `uat.postlight-lmm.com`.

**Comment by Athena96** [comment]
From the screenshot you sent, can you try clicking "Enable" for the root domain first, then try adding the subdomain.

**Comment by tmeckhoff** [comment]
> From the screenshot you sent, can you try clicking "Enable" for the root domain first, then try adding the subdomain.

I deleted the previous attempt, and added new domain with just the root domain of `uat.postlight-lmm.com` and got the same 400 error ```{"__type":"UnsupportedTLD","message":"postlight-lmm.com tld is not supported"}```

**Comment by tmeckhoff** [comment]
Hi @Athena96 has there been any update on our issue?

**Comment by adriencg** [comment]
@tmeckhoff So you should only need one hosted zone for the root (i.e. postlight-lmm.com). Assuming you created the others to try and get Amplify working, I'd go ahead and delete those.

Does the 400 prevent you from clicking 'Configure Domain'?

**Comment by tmeckhoff** [comment]
@adriencg 

`you currently have no custom domains configured, correct? ` 
Correct. We needed to remove the custom domains we had added before.

`So you should only need one hosted zone for the root (i.e. postlight-lmm.com)`
When I try to add the following subdomain (screen-app.staging.postlight-lmm.com) using our root (postlight-lmm.com) hosted zone I get this erro. This is why I switched to adding the additional environment subdomain hosted zone

![Screen Shot 2020-04-15 at 1 03 27 PM](https://user-images.githubusercontent.com/5074013/79371975-d9500a00-7f1a-11ea-91d9-d6ad9a4cf683.png)
 
`Does the 400 prevent you from clicking 'Configure Domain'?`
I added a custom domain again temporarily, using a new hosted zone (staging.postlight-lmm.com) just now to app ID: d15naslsktnpio and I was able to click on "Manage Subdomain" seen here, is this what you mean?

![Screen Shot 2020-04-15 at 1 06 17 PM](https://user-images.githubusercontent.com/5074013/79372273-5bd8c980-7f1b-11ea-9c6f-547cc0e623df.png)

Clicking on "Manage Subdomain" then showed this view

![Screen Shot 2020-04-15 at 1 06 08 PM](https://user-images.githubusercontent.com/5074013/79372326-6dba6c80-7f1b-11ea-938c-749affec0e2c.png)

I got the same 400 again
![Screen Shot 2020-04-15 at 1 06 50 PM](https://user-images.githubusercontent.com/5074013/79372100-15836a80-7f1b-11ea-90ff-c3545d595dba.png)

This is what the previous successful call to `/Route53domains` endpoint returned
![Screen Shot 2020-04-15 at 1 06 43 PM](https://user-images.githubusercontent.com/5074013/79372126-216f2c80-7f1b-11ea-8915-fdec320327e6.png)

**Comment by adriencg** [comment]
I see. I _think_ I know what the issue may be:

Terminology: When i say "create domain", I'm only referring to the Amplify Console Management page. You only need a single Route53 hosted zone with postlight-lmm.com for this to all work.

When creating the domain, go ahead and put the "root" subdomain you want (in this case staging.postlight-lmm.com). 

When adding the prefix, just add "screen-app". Your prefix can only be a single subdomain label i.e. `first.second` is not a valid prefix b/c it's two labels. If you wanted to add "beta.screen-app.staging.postlight-lmm.com" you'd need to add another domain with root "screen-app.staging.postlight-lmm.com".

Can you give that a try, and LMK how it goes? We will work on our docs/error messages to make this all a bit clearer.

**Comment by tmeckhoff** [comment]
@adriencg 

Yes, it works now, thank you! The documentation plus this message in the UI definitely lead me to think it had to come up as an option in the drop down in order to add it. 

![Screen Shot 2020-04-15 at 3 34 34 PM](https://user-images.githubusercontent.com/5074013/79388413-e842b680-7f32-11ea-9442-f1f4a82910d5.png)

But I see now why that wouldn't be the case. Thanks again!

**Comment by adriencg** [comment]
I've cut an internal task for cleaning this up so that it's more intuitive for others in the future. Thanks for your patience, and if you've any other issues please feel free to open an issue. Closing for now.
