### ISSUE TITLE
Constantly failing deploys

### ISSUE THREAD

**Issue by simpson** [aws-amplify/amplify-console#541]
** Please describe which feature you have a question about? **
Over the past 48 hours, a significant portion of our builds are failing to deploy. All it says at the bottom of the deploy logs is:

"2020-03-26T17:48:01 [ERROR]: Failed to deploy"

** Provide additional details**
This happens on all branches, is anyone else experiencing this?

**Comment by Athena96** [comment]
Hi @simpson can you share your appId and region. Thanks

**Comment by simpson** [comment]
Hi @Athena96 

arn:aws:amplify:ap-southeast-1:252100588959:apps/d12hn9rteao8a1
ap-southeast-1

If you just keep re-deploying it eventually works but that is a lot of unnecessary build time

**Comment by ganipcanot** [comment]
Are you still experiencing issues @simpson?

**Comment by simpson** [comment]
@ganipcanot Looks like it has cleared up, do you have any more details on what was failing? Is there anything we can be doing to fix this on our end?

**Comment by ganipcanot** [comment]
Seems it was something intermittent on our end - nothing you could do on your end from what I can see.  If you experience this issue again please feel free to open another ticket with us.

**Comment by simpson** [comment]
@ganipcanot seems like the problem is back! Our deploys are failing again

**Comment by simpson** [comment]
@Athena96
