### ISSUE TITLE
Does Amplify Console Support Keybase Encrypted Git?

### ISSUE THREAD

**Issue by cray75** [aws-amplify/amplify-console#544]
** Please describe which feature you have a question about? **
Amplify Console CI/CD

** Provide additional details**
I know that Amplify has a host of different platforms it supports on its console for CI/CD, GitHub being one. My team was considering moving  an amplify project from GitHub to Keybase encrypted git and before we made the move I was curious as to if this was something supported by Amplify? I couldn't find any documentation on either the Amplify or Keybase side of things and wanted to see if this was possible. Would it be as simple as integrating a git repo and then providing keybase keys to KMS?

**Comment by Joycehao19** [comment]
Hi @cray75 , as far as I know, Amplify Console didn't support Keybase encrypted git yet.
