### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS on a new deployed React App

### ISSUE THREAD

**Issue by timknapp12** [aws-amplify/amplify-console#557]
I followed the guide at https://aws.amazon.com/getting-started/hands-on/deploy-react-app-cicd-amplify/) step by step to deploy a React App and after it is deployed and I follow the url I get an error: 
ERR_TOO_MANY_REDIRECTS master.d3dua5wptaka0z.amplifyapp.com redirected you too many times The error page also says "Try clearing your cookies" which I have looked at but there are no cookies for that page.

The url is: https://master.d3dua5wptaka0z.amplifyapp.com/index.html
I followed the guide and accepted all default settings. It is actually a next.js app and in the build settings for amplify console the baseDirectory is set to .next. I found some similar closed issues but neither had the answers I need.
Any advice? Thanks!

**Comment by swaminator** [comment]
Amplify Console adds a default redirect to index.html for a 404 which tells me your output folder is incorrect. Can you check the output folder in your build settings?

**Comment by timknapp12** [comment]
@swaminator thanks for the quick response! Below is the default yml that was creating in build settings. Is that helpful?

version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

**Comment by timknapp12** [comment]
@ganipcanot  It is not a test, but is meant to be real app. The AppArn is:
`arn:aws:amplify:us-east-2:923533702251:apps/d3dua5wptaka0z`

**Comment by ganipcanot** [comment]
@timknapp12 Thanks for the info!  It looks like your application is missing an index.html page - that is required for Amplify applications.

@swaminator Please correct me if I'm wrong here but AFAIK an index.html file is required.

**Comment by ganipcanot** [comment]
Also looks like the output folder is ".next" - we currently have an issue deploying to hidden folders which we are working on resolving.

**Comment by timknapp12** [comment]
Ok that makes sense why it's not working then. I just tried with a new repo that is not using nextjs but only react and it works fine. So thanks so much for your help @ganipcanot  and @swaminator ! I will close this issue now :)
