### ISSUE TITLE
Backend environments are not up-to-date

### ISSUE THREAD

**Issue by no-creative-name** [aws-amplify/amplify-console#559]
**Is your feature request related to a problem? Please describe.**
The "Backend environments" tab shows environments that already have been removed. When following the instructions to "Delete" them via the amplify cli, they don't show up there (since they have been already removed). 

**Describe the solution you'd like**
Update the backend environments in Amplify console to fit the cli ones.

**Additional context**
The Amplify console "Backend environments" tab shows the following environments: "dev", "develop", "devnew", "prod", "stage", "storage".
The CLi shows the following environments for "amplify list env":
<img width="218" alt="Bildschirmfoto 2020-04-02 um 08 02 17" src="https://user-images.githubusercontent.com/25197658/78215809-b6ecd400-74b8-11ea-9ac8-1bf79fac8358.png">

**Comment by swaminator** [comment]
@no-creative-name  can you try running `amplify pull --appid XXXX --envName storage` from local machine?

**Comment by ganipcanot** [comment]
@no-creative-name Can you please provide your appId and region so we can investigate what backend environments we are seeing on the console side.

 Under appSettings --> General it will look something like this:

arn:aws:amplify:**<region>**:<accountId>:apps/**<appId>**

**Comment by no-creative-name** [comment]
@ganipcanot 
Region: eu-west
AppId: d1emvec1xhju1x

**Comment by ganipcanot** [comment]
@no-creative-name Yes - I can see [dev, develop, devnew, prod, stage, storage] in the list of BE environments.  Will have to test this out to see if this is some CLI bug.

**Comment by no-creative-name** [comment]
@ganipcanot any update on this?

**Comment by swaminator** [comment]
@no-creative-name are you still dealing with this issue?
