### ISSUE TITLE
My production backend envirnoment is gone.

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-console#560]
**Describe the bug**

I've an Amplify app with 2 backend environments, dev and prod. Dev is tied to a git branch of the same name and production is tied to master (I've another backend env called fuse but I've never done anything with it actually). Everything has worked more or less fine for over a year and suddenly I'm trying to push to production and notice that the web app doesn't update (note that the amplify push was successful on the CLI) and when I dig into the Amplify console I notice that my `git push` didn't trigger a build as it has done always and digging deeper (not that deep actually) I realize that there's no prod backend environment ... what's going on here?

See attached images.

PD: I haven't updated my amplify library or CLI recently.

I'd very much appreciate your help here, this is a production website and the problem is actually with the production branch/env.

![1](https://user-images.githubusercontent.com/638567/78265702-d09b1500-74d2-11ea-88d5-b064d877ee0d.png)
![2](https://user-images.githubusercontent.com/638567/78265705-d133ab80-74d2-11ea-8643-2b5d2cece381.png)
![3](https://user-images.githubusercontent.com/638567/78265708-d133ab80-74d2-11ea-8dda-f897dce8d3cb.png)

**To Reproduce**

1. Go to Amplify Console
2. Click on portal App
3. Click on 'backend environments' tab
4. See that there's no prod backend env.

**Comment by sammartinez** [comment]
@damianrr This seems to be related to Amplify Console. I have moved it to their repository and let their oncall know

**Comment by damianrr** [comment]
Thanks @sammartinez

**Comment by swaminator** [comment]
@damianrr we are looking into it and will get back to you soon.

**Comment by damianrr** [comment]
Thanks @swaminator, let me know if you need anything on my end.

**Comment by swaminator** [comment]
@damianrr what's your Appid ( found in app setttings > general)

**Comment by damianrr** [comment]
App ARN
arn:aws:amplify:us-east-1:155161765563:apps/d2poyx4r6wisl6

**Comment by swaminator** [comment]
@damianrr can you run `amplify env list` from your CLI?

**Comment by damianrr** [comment]
I get dev and prod. Please note the first image I attached to the original description of the problem here: https://user-images.githubusercontent.com/638567/78265702-d09b1500-74d2-11ea-88d5-b064d877ee0d.png

**Comment by swaminator** [comment]
Can you go to CloudFormation console and see what amplify stacks you have?

**Comment by damianrr** [comment]
I've quite a number of them, do you want me to send something like name, link ... anything?

**Comment by damianrr** [comment]
https://gist.github.com/damianrr/fc9a30c7a83c039a324ca45ccf35928d

The list is not comprehensive not including here the third unused env here.

**Comment by swaminator** [comment]
@damianrr can you actually flip the `Show nested stacks` to OFF and filter for stacks that start with amplify-

**Comment by swaminator** [comment]
@damianrr  what version of the CLI are you using? Is it 4.x+?

**Comment by damianrr** [comment]
Flipping off the switch I have: 

- portal-20190528145021
- portal-20190328173653

One should be my dev and the other my prod envs (I'm guessing here)

My prod env is currently working but I'm unable to modify it. I noticed the issue by commiting and pushing some changes which up until now triggers a build/deploy action through the Amplify Console, that's broken and I can't push changes to the backend. (Dev env/branch continues to work).

My amplify version is: 4.13.4

**Comment by damianrr** [comment]
BTW, there's a third env a co-worker created with it's stack but he didn't do anything else beyond creating and pushing the environment.

**Comment by ganipcanot** [comment]
@damianrr Can you please try again, you should be able to see your prod backend environment now.

**Comment by damianrr** [comment]
I can see it now! 

Thanks so much for the help guys!

PS: What was going on?!

**Comment by ganipcanot** [comment]
@damianrr Glad it is now working for you and you are unblocked.  We are currently investing into how this backend environment went missing.

**Comment by damianrr** [comment]
Fair enough. Thank you all!

**Comment by swaminator** [comment]
@damianrr glad to see you're unblocked. Did your prod backend ever show up on the 'Backend environment' tab?
