### ISSUE TITLE
My custom domains status is saying available but when i try visiting it its saying privacy error

### ISSUE THREAD

**Issue by Charl070** [aws-amplify/amplify-console#562]
**App Id**: 225235596198
**Region**: South Africa
**Step**: setting up custom domain
**Status**: available (but not working)

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I set up my custom domain from GoDaddy and I got a free SSL certificate after setting up my DNS on GoDaddy. The process took a couple of hours until my status was now saying its available. I then visited the domain but it has been saying not a private connection. I will attach an image on this issue. What can be the problem? 

**Error message**
Your connection is not private

Attackers might be trying to steal your information 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by ganipcanot** [comment]
@Charl070 Could you please include your APP-ID and REGION:

You can find your APP-ID and REGION by looking at the amplify console:

App Settings --> General --> AppArn: It will look something like this:

arn:aws:amplify:REGION:accountId:apps/APP-ID

**Comment by Joycehao19** [comment]
Hi @Charl070 , I checked 3 apps in your account. It seems like you deleted d16qh3rtikptdw and the rest of apps works fine. Closing the issue. Feel free to reopen it if you have another questions related to custom domain. Thanks
