### ISSUE TITLE
Can't connect Github Repo

### ISSUE THREAD

**Issue by kershnerd** [aws-amplify/amplify-console#564]
** Please describe which feature you have a question about? **
I have a react website up and running by using the Amplify CLI and I am able to deploy successfully by doing an `amplify publish`.

I now want to connect to my GitHub repo but there doesn't seem to be a way to connect my repo to an existing app.

** Provide additional details**
Under my app's general settings, source repository is blank and clicking reconnect repository just spins and nothing happens.

Clicking add environment only gives me drag and drop, S3, and any url options.

I have other repos connected correctly but I have create the app directly using a GitHub repo.  This one doesn't seem to work when starting from deployment from CLI.

Any suggestions?

**Comment by ganipcanot** [comment]
@kershnerd Is this a full stack application (back-end and front-end)?  Or is it just a front-end application?

Is there some documentation/links you were following if so please share them.

**Comment by kershnerd** [comment]
This is a front end only (ReactJS) web application.

The other amplify reactjs web applications that are connected to a GitHub repo were created not using the CLI.

This app that isn't working was created using the CLI.

Not sure if this screen shot helps, but here it is:
<img width="1598" alt="Screen Shot 2020-04-03 at 12 37 52 PM" src="https://user-images.githubusercontent.com/5776369/78398785-8a17ea00-75a8-11ea-820e-efc01246fb0c.png">

When I initially clicked `reconnect repository` it were through the steps to connect to my github in which I had to grant access.  Not clicking `Reconnect repository` just keeps spinning and nothing happens.

**Comment by swaminator** [comment]
@kershnerd Currently an Amplify Console app can either have frontend environments that are manual deploys or continuous deploys. Which means if you have frontend envs that you published manually, you first have to disconnect them to set up Ci/CD.

**Comment by kershnerd** [comment]
So I should delete that app and create a new one from a GitHub repo?

**Comment by kershnerd** [comment]
I just deleted my app and created a new one connected to my GitHub.  All is working now.
