### ISSUE TITLE
Domain activation is Failed - [CNAME is already associated with different resource]

### ISSUE THREAD

**Issue by woodsae** [aws-amplify/amplify-console#568]
**App Id**: d2w79oee0e5dqj
**Region**: ap-southeast-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I had previously set up a subdomain, **website.domain.com**, for testing purposes before I migrated my root domain over to my Amplify app.  I have tried to delete that old app and migrate over to my root domain, but I keep getting the error message below.  Any help would be greatly appreciated.

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Joycehao19** [comment]
Hi @woodsae , if you recently removed it, please wait around 6 hours and try it again. If you still face this issue, please let us know.

**Comment by Joycehao19** [comment]
Hi @woodsae , It seems like you deleted `d2w79oee0e5dqj`. Please let us know if you are still having this issue.

**Comment by woodsae** [comment]
Hi @joycehao19, I have tried to delete and recreate the resource a few times, and each time I run into the same issue as before. Does this likely mean that Amplify has an old Cloudfront distro with a CNAME of my root domain? Or is it simply because my root domain DNS record currently points to Wix?

**Comment by Joycehao19** [comment]
Hi @woodsae , I think the reason might be your root domain DNS points to Wix.

Would you mind provide your appId which connect your domain? or just provide your domain here? I can double check if your domain connect with other CloudFront distribution.

**Comment by woodsae** [comment]
Hi @Joycehao19 , the appId that I'm attempting to connect to my domain is d1fyhvomad6kaw.  My domain is https://www.trabr.com.

**Comment by adriencg** [comment]
@woodsae On our end it looks like the domain you've provided is already associated with a Cloudfront distribution in one of your AWS accounts. Can you confirm if this is the case? If so, you'll need to delete that Cloudfront account, or associate your amplify app with a different domain (e.g. app.trabr.com)

**Comment by woodsae** [comment]
Hi @adriencg I did find that there was an old disabled Cloudfront distro in one of my AWS accounts that had a CNAME for **www.trabr.com**.  I removed that this morning and am giving a bit of time to see if that resolves the issue.  Is there any way for you to check on your end to see that there are no other distros pointing to my primary domain?

**Comment by woodsae** [comment]
Hi @adriencg, I can confirm that there are no Cloudfront distros that I am managing in any of my AWS accounts that have a CNAME to my root domain.  Is there any way for you to see any hidden distros that Amplify is managing?

**Comment by adriencg** [comment]
@woodsae Did you try creating the custom domain again recently? If not, can you go ahead and try again, please.

**Comment by woodsae** [comment]
@adriencg Thank you very much for your help.  Deleting and recreating did finally solve the problem.

To summarise what the fix was in my case:
- Go through all of your AWS accounts to verify that no existing Cloudfront distros have a CNAME to the domain you're trying to use
- If you find one, delete it
- Once any existing distros are deleted, wait a while (in my case I left it for a day just to be sure)
- Delete the custom domain entry in the Amplify console
- Create a new custom domain entry pointing to the desired domain
