### ISSUE TITLE
High Time to First Byte (TTFB)

### ISSUE THREAD

**Issue by MatiMenich** [aws-amplify/amplify-console#569]
**App Id**: dtfknvkpkvqk4
**Region**: us-east-2
**Step**:
**Status**: Avaliable

**Issue/question**

Hi Everyone!

I had been getting high TTFB time while using Amplify to serve our static content website (https://kushkipagos.com) on our region (Latin America).

This are examples by using webpagetest.org:

USA
https://www.webpagetest.org/result/200406_6M_df3f200de30ec203ea91d82fb79d0799/

VS

Brazil
https://www.webpagetest.org/result/200406_JA_a237b757d1a5334a07fe21938625992b/
Argentina
https://www.webpagetest.org/result/200406_ZG_b09854d6cb4eac79ecea8be79ebeefc1/

It's ~300ms on the US (which is still a little high) vs ~1200ms on Brazil and Argentina.

I don't get the same results using s3 and a regular self-managed Cloudfront distribution (Here's an example https://www.webpagetest.org/result/200406_FR_910c35a944f387ad4717032763e292c2/) .

Please help :)

**Comment by swaminator** [comment]
@MatiMenich we had an issue in the latin american regions previously and recently fixed this. Closing this issue. Please reopen if its still a problem.
