### ISSUE TITLE
SSL verification is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by TemoLucky** [aws-amplify/amplify-console#57]
**App Id**: d1dmgnwdmwopvw
**Region**: us-east-1
**Step**: SSL verification
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by VividKnife** [comment]
I looked into your domain, the verification record seems fine. Can you goto the domain manage page and click the re-try button?

**Comment by TemoLucky** [comment]
I did but got error message 
"Error message: The status of this certificate request is "Failed". One or more domain names have failed DNS validation. Please check your domain name validation routes and try re-adding the custom domain to your app. Learn more: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-troubleshoot-guide"

**Comment by VividKnife** [comment]
What if delete your current failed domain and try to add it again? Let me if it still doesn't not work.

**Comment by TemoLucky** [comment]
Thanks, it worked
