### ISSUE TITLE
403 ERROR The request could not be satisfied.

### ISSUE THREAD

**Issue by ShoubhikBanerjee** [aws-amplify/amplify-console#571]
**Issue I am Facing :** This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation. 

**When it occurs?**:  While redirecting from other web app, directly to this app's path (say, https://abc.xz.com/myRedirectedPath).

**My Current amplify.yml**:  

`version: 0.1`
`frontend:`
 ` phases:`
  `  preBuild:`
 `     commands:`
 `       - yarn install`
 `   build:`
 `     commands:`
 `       - yarn run build`
`   artifacts:`
`    # IMPORTANT - Please verify your build output directory`
 `   baseDirectory: build/`
 `   files:`
 `     - '**/*'`
`  customHeaders:`
`    - pattern: '**/paymentCallback'`
`     headers:`
`    - key: 'Accept'`
`     value: 'application/json, text/plain, */*'`
`      - key: 'Access-Control-Allow-Methods'`
`        value: '*'`
`  cache:`
`    paths:`
`      - node_modules/**/*`

>**Its a PWA react app**: 

**Issue/question**
On hitting the url (say, https://abc.xz.com/myRedirectedPath), does not gives any error. But when it is redirected from other app, it shows the error. The site is served from Git and not from S3.

**Error message**
403 ERROR
The request could not be satisfied.

**Additional information from error message**
Generated by cloudfront (CloudFront)
Request ID: FEQiDffDdsFBX2Sg6Ct-IrNSFgGpe41WwHsJB5OOV-XilBKO-7PW7g==

**Comment by Joycehao19** [comment]
Hi @ShoubhikBanerjee , sorry that you have this issue.
> When it occurs?: While redirecting from other web app, directly to this app's path (say, https://abc.xz.com/myRedirectedPath).

What is other web app? Is that an Amplify Console App or from other resources? 
Thanks

**Comment by ShoubhikBanerjee** [comment]
@Joycehao19 thanks for reaching out... It's an paytm payment gateway integration. And hence it's redirect redirected from their side. And most probably they are out from amplify console app.

**Comment by ShoubhikBanerjee** [comment]
I am still helpless... Is anyone there to help me out?

**Comment by ShoubhikBanerjee** [comment]
Any one here to help?

**Comment by adriencg** [comment]
https://github.com/aws-amplify/amplify-console/issues/571 This issue appears to be duplicated. If they are, can we close this and follow-up on 571?

**Comment by ShoubhikBanerjee** [comment]
yes please close it

**Comment by MDrifath** [comment]
I thinks you want to look up for the aws documentation
https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cloudfront-bad-request-error/
