### ISSUE TITLE
Unable to clone repo (403) at Build step

### ISSUE THREAD

**Issue by F-JJTH** [aws-amplify/amplify-console#572]
Hi, using AWS Amplify Console App I try to deploy an app with the built-in «Provision, Build, Deploy, Verify» feature.

Unfortunately the Build step fails with the log below. I already «re-connected the repository» twice then re-launch build but it still fails.

How can I get the «Build» step successfully clone my codecommit repository ?

> [INFO]: # Cloning repository: https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/xyz-my-repository
> [INFO]: Cloning into 'xyz-my-repository'...
> [INFO]: fatal: unable to access 'https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/xyz-my-repository/': The requested URL returned error: 403
> [ERROR]: !!! Unable to clone repository.
> [INFO]: # Starting environment caching...
> [INFO]: # Environment caching completed
> Terminating logging...

Regards,

**Comment by Joycehao19** [comment]
Hi @F-JJTH , I can't reproduce your issue. Would you mind re-connect your app? If that doesn't work, would you mind provide your appId and region? (App Setting => General => App ARN =>
arn:aws:amplify:${region}:xxxxxx:apps/${appId})

**Comment by F-JJTH** [comment]
@Joycehao19 , I clicked the «Reconnect repository» button and followed the procedure but the build still fails. However I can't see «Reconnect app» button, am I looking at the wrong place ?

![Workspace 1_087](https://user-images.githubusercontent.com/6074450/78698408-941c4e80-7902-11ea-98c3-77f438b2b8b9.jpg)

My ARN is : arn:aws:amplify:eu-west-1:674771614881:apps/d22wnu0es6yoja

**Comment by Joycehao19** [comment]
Thank you for providing your appId and region. Sorry, I mean that if you could go to `All apps`, click `Connect app`, the `AWS CodeCommit ` to re-build a new app.

**Comment by F-JJTH** [comment]
All right, I clicked `Connect app` and followed the procedure, now `git clone` works

... after a couple of minutes my application is now deployed :-) 

Thanks for your efficient help

**Comment by trungegd** [comment]
I have same problem.
`2020-07-17T09:55:07.190Z [INFO]: # Cloning repository: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/myApp
2020-07-17T09:55:07.664Z [INFO]: Cloning into 'myApp'...
2020-07-17T09:55:14.362Z [INFO]: fatal: unable to access 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/myApp/': The requested URL returned error: 403
2020-07-17T09:55:14.365Z [ERROR]: !!! Unable to clone repository.
2020-07-17T09:55:14.457Z [INFO]: # Starting environment caching...
2020-07-17T09:55:14.459Z [INFO]: # Environment caching completed
Terminating logging...`

My App ARN is: arn:aws:amplify:us-east-1:751062960773:apps/d1a6rku7rwx15v

Please support for me this problem

**Comment by linfiesto** [comment]
I also can't clone repository but has a different error. I've reckon it's a permission issue but don't know how to proceed, I've already made sure I have AdministratorAccess on my IAM account.

It says [ERROR]: !!! Unable to assume specified IAM Role. Please ensure the selected IAM Role has sufficient permissions and the Trust Relationship is configured correctly.


![image](https://user-images.githubusercontent.com/4402009/90095405-2033fc00-dd63-11ea-851f-202aa5d4ec56.png)

**Comment by codingme** [comment]
I tried this and it worked!
[Adding a Service Role to the Amplify Console When You Connect an App
](https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html)
So it is the role problem.

**Comment by dnbtr** [comment]
Had the same issue.
I deployed an app in the wrong region and had to delete it. But the role it created remained.

Solved by deleting the previous role - AWSAmplifyExecutionRole-[instanceID], as it was pointing to the wrong instance, then let AWS create a new role by selecting "Read-only access to your repository with a new service role".

**Comment by mjza** [comment]
I had the same problem. We had already a `AmplifyConsoleServiceRole-AmplifyRole` role. I moved to `IAM Management Console` and then selected roles from the side [menu](https://console.aws.amazon.com/iam/home#/roles/).

Then in the list looked for `AmplifyConsoleServiceRole-AmplifyRole` role and pressed on the `Change boundary` button and in the list searched and selected `AWSCodeCommitReadOnly`. This helped me to pass this error.

**Comment by MiqueiasGFernandes** [comment]
I had same issue, any solution or AWS team answer?

**Comment by josimarz** [comment]
Hello,
If you are facing this problem, check if the **Service Role** associated with your app has permission to access the desired repository in **AWS CodeCommit**.
