### ISSUE TITLE
Wrap the item list to display first set of items after the last set, given pagination size

### ISSUE THREAD

**Issue by AshwiniRaysecur** [aws-amplify/amplify-console#577]
**Description**

The UI has 'Next' button, which calls Amplify auto-generated 'listAll' query.
'Next' button does not wrap the item list to show the first set of items again after the last set is displayed

**Steps to Replicate**
1. Set 'limit' (of displaying number of items in the list) equal to X (eg. 10) in listAll query function
2. Make the number of items in database (dynamo db table), a multiple of X (eg. 20 or 40)
3. Run the app and click the 'Next' button, till you get to the last set of items in the list
4. Click 'Next'

**Expected Result**
clicking the 'next' button should again display the first X items in the list

**Actual Result**
the items list doesn't change and displays the same last set of items

**Comment by Joycehao19** [comment]
Hi @AshwiniRaysecur , would you mind take a screen shot of the page? Thank you

**Comment by adriencg** [comment]
@AshwiniRaysecur Would you mind clarifying: Is this an Amplify Console issue you're reporting or a UI Component (Amplify Framework) one?

As Joyce mentioned, a screenshot would be helpful.

**Comment by AshwiniRaysecur** [comment]
Screenshot of the App :

![listing screenshot](https://user-images.githubusercontent.com/59932758/79144130-6b75d800-7d8c-11ea-9828-1b2bb4b02c83.png)

----

For the application, the pagination limit is set to 5 in 'listAll' query 
+ Case (a)
      1. Total number of items in database (dynamobd) is 11 
      2. Application launch displays 5 items (items 1 - 5)
      3. Click 'Next set' button, displays next 5 items (items 6 - 10)
      4. Click 'Next set' button, displays 1 (11th) item from the database
      4. Click 'Next set' button, wraps around and displays first 5 items (items 1 - 5)

+ Case (b)
      1. Total number of items in database (dynamobd) is 10
      2. Application launch displays 5 items (items 1 - 5)
      3. Click 'Next set' button, displays next 5 items (items 6 - 10)
      4. Click 'Next set' button, displays the same set of 5 items (items 6 - 10) and 
           throws error : "TypeError: Cannot read property 'id' of undefined"

----
Can we have Case (b) to wrap the item list to display first 5 items (items 1 - 5) again ?

**Comment by adriencg** [comment]
@AshwiniRaysecur  Assuming I understand correctly, you're using https://github.com/aws-amplify/amplify-js to create this table. Please go ahead and create an issue in that repo (feel free to link to this one so you don't have to repeat everything)
