### ISSUE TITLE
"The domain you entered is invalid or unavailable" in domain management

### ISSUE THREAD

**Issue by bclarkicc** [aws-amplify/amplify-console#579]
**App Id**: arn:aws:amplify:us-east-2:286574893818:apps/d1fmnb6hndzup5
**Region**: us-east-2
**Step**: setting up custom domain
**Status**: available (but not working)

**Issue/question**
I've deployed an Amplify React app successfully from a repository. I go under Domain Management and click on Add Domain, then type anything on the domain I want to hook this up to (iccsafe.org, though it will be on some kind of a sub-domain), and click on Configure Domain. I'm then given the below error message.

**Error message**
The domain you entered is invalid or unavailable

**Additional information**
I'm not given any guidance as to why this would be, it's obviously a domain that exists. What other reasons would it not be eligible here?

**Comment by Joycehao19** [comment]
@bclarkicc  `iccsafe.org` should work. Can you check it again? (Please make sure no space include)

**Comment by bclarkicc** [comment]
@Joycehao19 It definitely does not. I've made sure there are no spaces or anything in it, and I still get that message as of this morning.

**Comment by bclarkicc** [comment]
Looking into it, this has to do with restrictions on my account. Going to close this issue.

**Comment by HeinMynn** [comment]
Same Issue. Is it already solved? Can you share me how to solve please?

**Comment by bclarkicc** [comment]
@HeinMynn My AWS account actually had permission restrictions on it that were preventing me from doing this. Those permissions just had to be added to my account by our administrator, and it was fixed. Obviously may be different for you.

**Comment by Kaschman** [comment]
Just in case anybody else winds up here - I had the same behavior trying to connect to a 3rd-party managed domain. Make sure your AWS IAM account has permissions for Route 53. I noticed in the console that network calls to Route 53 were failing, updated permissions, and it resolved the issue.

**Comment by jayprakash02** [comment]
Get a certificate from ACM and add it to your Route53 records after your certificate validates try again in the Amlipy it will work this time.
