### ISSUE TITLE
Blank Site and the Build and Deployment were successful according to AWS

### ISSUE THREAD

**Issue by AffiliateThis** [aws-amplify/amplify-console#58]
My site was successufully built and deployed but the deployed url from Amazon Amplify is blank - https://master.d3jh6o39xlyny5.amplifyapp.com.  Is there any other information I should provide?

It is a react-mdl app.

**Comment by VividKnife** [comment]
@AffiliateThis It seems like you already removed your app. Do you still have this issue?

**Comment by AffiliateThis** [comment]
Yes I ended upt deleting it.   Going a different route currently via Amplify CLI.   I looked around on why it was blank to begin with and didn't really much anything on my searches.  I figured it would take a shorter period of time to start over via some youtube videos.  We shall see....

**Comment by AffiliateThis** [comment]
looks like the CLI route and I am getting the same issue.  I did it via cloudfront as I have a custom domain.   Here is the new deployed link - https://d214aumzj2vax1.cloudfront.net/

**Comment by swaminator** [comment]
Did you try runinng your build command from your local desktop. If it works, can you try using the manual deploy feature in the Amplify Console? Build locally and upload your artifacts: https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html

**Comment by AffiliateThis** [comment]
Here is what I did.  
npm i aws-amplify - I should have done the next command.
npm install -g @aws-amplify/cli
amplify configure
then followed through prompts
amplify add hosting
followed prompts
amplify publish

**Comment by swaminator** [comment]
It seems like there's an issue with your app if its failing on both Cloudfront/S3 and Amplify Console. Can you see if you can upload your build artifacts as per https://github.com/aws-amplify/amplify-console/issues/58#issuecomment-522109504
