### ISSUE TITLE
Build Stuck on Deploy With Console Output: [ERROR]: Failed to deploy

### ISSUE THREAD

**Issue by porkrines42** [aws-amplify/amplify-console#580]
Hello,

We are trying to deploy for the first time using Amplify and are facing an issue with the Deploy phase of the build process. The build never completes/times out/errors out (it just stays in the deploy phase). The only thing that does appear in the deploy logs is an error stating: [ERROR]: Failed to deploy.

There is no further description or information and like I stated, the actual build itself just freezes at that point. Any help with this would be greatly appreciated! 

App ID: dfhhg383a201k

**Comment by Joycehao19** [comment]
Hi @porkrines42 , I checked `dfhhg383a201k`, it seems like the build was succeed. Could you please make sure the appId is `dfhhg383a201k`? If it happened in app:dfhhg383a201k, would you mind take a screen shot from your console? Thanks

**Comment by porkrines42** [comment]
@Joycehao19 - Yes, I believe that is the correct ID, but please see screenshots below.

![image](https://user-images.githubusercontent.com/50489634/78942154-19307080-7a87-11ea-88d1-58e1ef3ce2de.png)

![image](https://user-images.githubusercontent.com/50489634/78942176-20577e80-7a87-11ea-9519-f19a35e4ec1d.png)

**Comment by Joycehao19** [comment]
@porkrines42 Thank you for checking id and providing the screen shot. Would you mind provide your build settings as well?

**Comment by porkrines42** [comment]
@Joycehao19  Here it is!

![image](https://user-images.githubusercontent.com/50489634/78990803-6521fa80-7b05-11ea-995e-3089b97c267a.png)

**Comment by porkrines42** [comment]
@Joycehao19 - I've found the issue! It was with the Artifacts base directory. All good now, thanks for your help!
