### ISSUE TITLE
Amplify is not uploading all my deployment build files

### ISSUE THREAD

**Issue by NL33** [aws-amplify/amplify-console#584]
** Please describe which feature you have a question about? **

I am using the Amplify console to deploy my Angular 8 app.  Deployments have stopped working properly, and it seems that **Amplify is not deploying all the files in my distribution build**. What could be happening?

The deployments seem to degrade each time. I just re-uploaded the same exact bundle, and it showed the error (described below) on more and more pages.

This is a critical issue, because it is making my production app unuseable.

** Provide additional details**
My app is Angular 8. 

To deploy, I create a bundle with `$ ng build --prod`

I then drag and drop this bundle into my amplify console. I have also tried uploading the bundle by hitting "upload," and also by putting the bundle on S3, and then accessing that S3 bucket through the Amplify console. None of these alternatives helped.

I have been deploying this way for several weeks without problem. 2 days ago--while not changing any of my app's settings or amplify settings as far as I can tell--the deployed app would fail to show certain pages. And those pages would show this error:

`"Syntax Error: Unexpected Token '<' "     `
`Error: Uncaught (in promise): ChunkLoadError: Loading chunk 5 failed.`   (chunk number varies depending on which component I try to click on)

I also get an error saying: 
`Error while trying to use the following icon from the Manifest: https://www.[app].com/assets/icons/icon-144x144.png (Download error or resource isn't a valid image)`

It seems that Amplify is saying certain files (like the icon file) do not exist in the deployment. But, these files clearly exist in the bundle that I am uploading.

**Comment by adriencg** [comment]
@NL33 So I can better root-cause the issue, would you be able to provide your AppId?

You can find your APP-ID and REGION by looking at the amplify console:

App Settings --> General --> AppArn: It will look something like this:

arn:aws:amplify:REGION:accountId:apps/APP-ID

**Comment by NL33** [comment]
Hi there. I am not able to provide this over github, but if there is another way for me to send it to you I would be glad to do so.

**Comment by adriencg** [comment]
@NL33 Please shoot an email to aws-amplify-customer@amazon.com with the AppID's and regions in question.

**Comment by NL33** [comment]
Awesome. I'll do that now. I've just seen that one of the missing files had this in the debug:
"x-cache: Miss from cloudfront"

Seems like it is an AWS caching issue. I'll send over the email now.

**Comment by adriencg** [comment]
@NL33 Moving any further debug-chatter to email, so please make sure to check for any replies there.

Will update this issue with a resolution/root-cause once we have one.

**Comment by NL33** [comment]
Sounds great. Thanks!

**Comment by adriencg** [comment]
@NL33 Every email I try to send is getting bounced. Can you email another address I can try to the same amplify email I mentioned before?

**Comment by NL33** [comment]
Just re-sent. Thanks.

**Comment by NL33** [comment]
Just spoke with @adriencg and he did an awesome job talking me through this. 

It's not fully clear why the manual build process (dragging and dropping the build folder directly into the amplify console) started failing before, but it looks like uploading a zip file of the build to S3, and then deploying from there works.

To upload from S3:
1. main app folder: `$ ng build --prod`
(creates the build)
2. cd into the build folder. (in my case: dist/app)

3. create zip file from the cli: `$ zip -r build.zip .` 

4. Give the zip file a uniquely-identifying name.

5. S3: go into an existing bucket or create a new one.

6. Upload the zip file to the S3 bucket.

7. Amplify console: go to "choose another method" (from the spot you would drag and drop the bundle). Click S3 -> find the bucket and zip file you created.

8. click "save and deploy"

So far this method is deploying the app without errors.

**Comment by adriencg** [comment]
@NL33 Glad we could help you out.

I'm going to cut a ticket internally to investigate further what might've happened w/ the drag-n-drop, but would suggest anyone that finds this issue b/c they're experiencing a similar behavior to first try and upload via zip. **Please make sure to zip the contents of the output directory, and not the directory itself (i.e. follow the steps mentioned here https://github.com/aws-amplify/amplify-console/issues/584#issuecomment-613570006 and it should work)**

Closing the issue for now

**Comment by G07cha** [comment]
I experience this issue as well @adriencg, also with ZIP file. Just sent my AppId and Region to aws-amplify-customer@amazon.com.
