### ISSUE TITLE
Hugo pages "password" protect with serverlessrepo-amazon-cognito-passwordless-email-auth

### ISSUE THREAD

**Issue by lionzan** [aws-amplify/amplify-console#585]
** Please describe which feature you have a question about? **
password protect

** Provide additional details**

I want to use serverlessrepo-amazon-cognito-passwordless-email-auth to "password" protect pages of a hugo site on Amplify. But I don't understand how to connect that to the password protect. 
 According to [Implementing passwordless email authentication with Amazon Cognito](https://aws.amazon.com/blogs/mobile/implementing-passwordless-email-authentication-with-amazon-cognito/) it should be possible. But I can't find any resource explaining it.
I guess I have to use UserPoolID and UserClientID from there with some script in the hugo static site or specific pages to protect?

**Comment by swaminator** [comment]
@lionzan have you tried: https://docs.amplify.aws/lib/auth/getting-started?platform=js

**Comment by adriencg** [comment]
@lionzan I'm going to close this issue in the meantime...feel free to reopen this one or cut an issue to the JS platform team if you've further questions.

**Comment by lionzan** [comment]
Hey sorry, I missed the response from swaminator.
Anyway, I don't see the connection with the link I mentioned.

**Comment by adriencg** [comment]
@lionzan The suggestion was to use Amplify auth, which is just using cognito under the hood.

I'd suggest opening an issue with https://github.com/aws-amplify/amplify-js if you've more questions about integrating Amplify auth into your web app.

**Comment by lionzan** [comment]
Thanks!

**Comment by DoctorrDeep** [comment]
@lionzan Did you figure out a way to use cognito  based authorization through amplify?
