### ISSUE TITLE
SSL configuration lasts 12 hours 

### ISSUE THREAD

**Issue by usbcombine** [aws-amplify/amplify-console#586]
**App Id**: d2kwnekpp7gsav
**Region**: US East (Ohio)us-east-2
**Step**: SSL configuration
**Status**: Pending

**Issue/question**
SSL configuration lasts 12 hours and more... The domain is registered on Amazon Route 53. NS record set is the same in "hosted zone" and "registered domain" sections.

**Comment by usbcombine** [comment]
It is still waiting for SSL configuration. 27 hours passed. Is it normal, should I wait?

**Comment by adriencg** [comment]
No. You should go ahead and delete the domain in Amplify Console, and re-add it.

If that doesn't fix it, please LMK and I'd be happy to dig in further.

**Comment by usbcombine** [comment]
I have deleted and re-added domain.  Still pending on SSL configuration. 9 hours passed. How long it usually takes? 15-30 minutes?

**Comment by adriencg** [comment]
@usbcombine I looked into your domain, and your domain might not be configured correctly (could be a Route53 issue, or a setting/transfer issue). `https://www.whatsmydns.net/#NS/<your-domain>` <- Use this link to see what I'm talking about; the DNS isn't propagating everywhere, which is likely causing ACM to be unable to verify dns ownership. What's the status of the domain in Route53? I'd suggest reaching out to their customer support if everything looks OK there.

**Comment by usbcombine** [comment]
@adriencg  I figured out the problem with ns records. Now it works, thanks.
