### ISSUE TITLE
Successful Backend Deployment, but No Backend In Console List

### ISSUE THREAD

**Issue by derekw023** [aws-amplify/amplify-console#587]
**App Id**: d1oddychzhcfop
**Region**: us-west-2
**Step**: build
**Status**: 

**Issue/question**
When kicking off a CD deployment from backing branch, Amplify sequences a rebuild of the serverless backend. This backend appears to pass build, but there is no matching backend for the branch present in the backend list

**Error message**
No errors, build appears to pass

**Additional information**
Amplify frontend, backend largely driven by API gateway/AWS Lambda/RDS

**Comment by adriencg** [comment]
@derekw023 Mind clarifying which branch is having the issue? And I assume you selected "Create a new backend environment" when connecting the branch, correct?

**Comment by derekw023** [comment]
Sure. The branch with the issue is `staging`. The branch was already connected via that process, and working as of the last deployment, it developed this issue as of the last automatic CD deployment.

More information:
- The backend that matches this branch name is shown on the CLI from `aws amplify get-backend-environment` with a very stale deployment date. 
- `aws amplify list-backend-environments` does not show any backend for staging
- AWS CLI version string: `aws-cli/2.0.7 Python/3.7.4 Darwin/19.4.0 botocore/2.0.0dev11`

**Comment by adriencg** [comment]
I'm able to see the backend environment, and it looks like the latest build in staging did run amplifyPush:
`2020-04-13T21:22:49.453Z [INFO]: # Executing command: amplifyPush --simple --environment staging` and
`2020-04-13T21:22:59.658Z [WARNING]: ✔ All resources are updated in the cloud`

Are you able to view these environments in the console GUI? _Note_: the `updateTime` returned by `get-backend-environment` doesn't actually reflect the latest update to that environment (it's usually the same as createTime).

Have you noticed that newly added backend resources aren't being created? Or is the only issue the fact that it doesn't appear in the list? 

It's also possible your CLI isn't pointing to the right account/region.

**Comment by derekw023** [comment]
My CLI and console are both in `us-west-2`. The Amplify GUI in the console, under the `backends` tab does not list the `staging` backend, on the `frontends` list the `staging` frontend is there but it does not say its linked to any backend. 
![image](https://user-images.githubusercontent.com/20305986/79259447-b9f1a800-7e5a-11ea-84ba-7f2ee636fe07.png)
![image](https://user-images.githubusercontent.com/20305986/79259462-bfe78900-7e5a-11ea-8d19-8b46ffc99a70.png)

**Comment by derekw023** [comment]
We also have a couple of open application issues, most of those are ruled out but we're working on them in parallel. But there is definitely some front-end weirdness happening in the Amplify console.

**Comment by adriencg** [comment]
@derekw023 Thanks. This might just be GUI bug, but to confirm:
Can you try adding a resource to staging, and just verifying in your AWS account that it's created? e.g. a new DDB table or something similar you can delete afterwards

Also do you remember if you created the backend via the CLI or the Console?

**Comment by derekw023** [comment]
Using the Amplify CLI I was able to add an S3 resource to the cloudformation stack, and it showed changes in the console. I didn't personally create the backend, but I am pretty certain it was created with the CLI.

**Comment by adriencg** [comment]
@derekw023 Glad to hear functionally things are OK (not dismissing your frustration). My suspicion is that when the BE's are created in the CLI, they may not show up correctly in Console. I want to see if i can repro it quickly locally, and will update w/ the results here.

Last question: roughly how long ago was this app/env created? Want to know if it was pre Q4 2019 when we officially launched support for BE's in Console.

**Comment by derekw023** [comment]
I believe this particular backend was created January 29 2020. 

Also yes, after the initial deploy updates were definitely via CI/CD in the Console

**Comment by derekw023** [comment]
I found some new information, we had a lot of backends hanging around from a development cycle, and I just cleaned them up. It looks like the beckend tab can only list so many items, and there is no mechanism to show multiple pages (and also when a backend isn't shown it won't be "linked" with the associated frontend environment in the console). Staging shows up now and everything looks like it should, now that I reduced the count of unique backends to 5
