### ISSUE TITLE
Check previous phase status

### ISSUE THREAD

**Issue by avner-hoffmann** [aws-amplify/amplify-console#589]
** Please describe which feature you have a question about? **
Is there any way to check the previous phase status on the current phase?
e.g. the postTest phase always runs after the test phase, no matter if the test phase succeeded or not. Is it possible to know if the test phase succeeded in the postTest phase? Something like the exit code of the last test phase command, maybe simplified in an aws amplify env variable ?

**Comment by adriencg** [comment]
@avner-hoffmann Is this question specifically about cypress testing? Or are you asking about between all phases in general (build/postBuild, test/postTest)?

**Comment by adriencg** [comment]
@avner-hoffmann Quick update: So this is only the case w/ test phase b/c we need to upload the artifacts even if the test step failed.

The best way to check for test failures is to parse the test output yourself in postTest, and look for success/failed tests.

**Comment by avner-hoffmann** [comment]
@adriencg - It will be very efficient if amplify will be able to supply the result of the test phase as an env variable or so, such that in the post test phase we can know if the tests succeeded or not. the post test phase may require running operations according to the test result
