### ISSUE TITLE
Domain activation is Failed - [Tried several times. Still doesn't work. Yes, it used to be on another app]

### ISSUE THREAD

**Issue by hancharou** [aws-amplify/amplify-console#590]
**App Id**: d38l7gms2jhcnt
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by adriencg** [comment]
@hancharou We're currently working on an issue causing intermittent failures in create domain. Yours was impacted. Will update this issue when you can delete the domain and try again (we're currently working on a fix).

**Comment by adriencg** [comment]
@hancharou It's up to you if you'd like to try again; there's a good chance it will succeed (error rate is pretty low).

Can you delete the domain, and then recreate it?

**Comment by hancharou** [comment]
I'm doing retry. If it doesn't help, I'll delete the domain and add it again. Thx

**Comment by adriencg** [comment]
To clarify: I just mean delete the domain from Amplify Console (not Route53).

**Comment by hancharou** [comment]
I've removed the domain from the console. And restarted the process. Let's see. Will let you know. Txh

**Comment by hancharou** [comment]
Added it again, it's in SSL configuration step. Still waiting...

**Comment by hancharou** [comment]
It's still in SSL verification. Haven't finished yet.

**Comment by adriencg** [comment]
@hancharou I believe your domain isn't hosted in Route53, in which case you'll have to make sure to follow the extra steps mentioned in ["Connecting to Third-Party Custom Domains"](https://docs.aws.amazon.com/amplify/latest/userguide/howto-third-party-domains.html). When it's stuck in this step, it typically means you haven't setup the CNAME so that we can verify you own the domain name; the Amplify console should have more instructions about the the CNAME you'll need to create.

**Comment by hancharou** [comment]
Both CNAMEs are in my CloudFlare DNS names. Still sits on "SSL verification" step.

**Comment by hancharou** [comment]
Did everything according to instructions. Added 2 CNAMES: one for verification and one for forwarding. Double checked with https://mxtoolbox.com/CNAMELookup.aspx and see it's propagated. When I created first amplify application it used to verify it fast and without any issues. But I deleted the app and created a new one and hooking up the same sub-domain.

**Comment by adriencg** [comment]
I can see the SSL verification CNAME is setup, but unable to confirm forwarding to the amplifyapp. How exactly did you verify that your root domain is pointing to your amplifyapp domain?

**Comment by hancharou** [comment]
I didn't setup for root domain. Only for dash.mydomain.dev. I see it moved forward to "Domain Activation" step.

**Comment by adriencg** [comment]
Got it. Yes, if that's the only subdomain you created (and you excluded root) then everything should finish successfully

**Comment by adriencg** [comment]
@hancharou I see the domain is now activated, and things should be worked. Closing this issue, but please reopen if something is still not working.
