### ISSUE TITLE
Access Denied Error for all URLs except homepage

### ISSUE THREAD

**Issue by muhalitas** [aws-amplify/amplify-console#591]
**App Id**: d2iqngmka368lt
**Region**: Frankfurt
**Step**: After Deployment - Usage
**Status**:  Pending

**Issue/question**: We deployed ReactJS app using Amplify from web console. We can access to homepage but got "access denied" error with XML format from AWS for any other URLs. It also happens when we refresh the page.
We read all of docs but could not find a solution for this.

**Error message**
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>4E94B7900CE00FAC</RequestId>
<HostId>
*deleted due to sensitive info*
</HostId>
</Error>

**Comment by adriencg** [comment]
The "Redirects for Single Page Web Apps (SPA)" section of [this wiki](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html) mentions setting up a 200 rewrite for any path that doesn't match a potential static asset (image, js, css, etc.).

Can you try adding this to your redirects/rewrites to see if it fixes the problem?

**Comment by muhalitas** [comment]
Thank you very much, works like a charm!

**Comment by cybershop46-us** [comment]
> The "Redirects for Single Page Web Apps (SPA)" section of [this wiki](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html) mentions setting up a 200 rewrite for any path that doesn't match a potential static asset (image, js, css, etc.).
> 
> Can you try adding this to your redirects/rewrites to see if it fixes the problem?

Thanks for the advice, whe i change this now show me this error:
![image](https://user-images.githubusercontent.com/111092097/198097026-6ca66a5e-c4e4-426d-9858-be689b4c102b.png)
