### ISSUE TITLE
Getting "x-cache: Miss from cloudfront"

### ISSUE THREAD

**Issue by gargshantnu** [aws-amplify/amplify-console#592]
**App Id**: d1v8ph9qar406v
**Region**: us-east-1
**Step**:  
1. Connected GitHub repository
2. in domain setup, added my domain and then excluded root, and added one for specific for the app.

**Status**: not sure what to fill here

**Issue/question**
I have simply integrated amplify for testing purposes of react code and in the domain setup added a new sub-domain there. Now in browser, I am receiving `Miss from cloudfront` also I am getting two values in `via:` header, now I am not able to figure out what the problem is. so can anyone please help me out with this.
Response Headers that are received in the browser.
```
age: 68309
cache-control: public, must-revalidate, max-age=1296000
content-encoding: gzip
content-type: application/javascript
date: Mon, 13 Apr 2020 12:04:48 GMT
last-modified: Mon, 13 Apr 2020 11:19:04 GMT
server: AmazonS3
status: 200
vary: Accept-Encoding
via: 1.1 24412018db9f823badbcceb9b3bbdb6f.cloudfront.net (CloudFront), 1.1 716918b261f035549e3145e5fb7631d4.cloudfront.net (CloudFront)
x-amz-cf-id: RwbsAOAz2BrOZqNfiS8H59cCaRnOgkzlXjsLjzZskKxZUXppuT50Mg==
x-amz-cf-pop: BOM50-C1
x-amz-cf-pop: DEL54-C1
x-amz-server-side-encryption: AES256
x-cache: Miss from cloudfront
```

**Comment by adriencg** [comment]
>Now in browser, I am receiving Miss from cloudfront

Does this mean the page isn't loading as expected?

**Comment by gargshantnu** [comment]
> Does this mean the page isn't loading as expected?

No, pages are loading fine, but I think they are not being served from edge location but from origin.

**Comment by adriencg** [comment]
@gargshantnu This is expected. Amplify's hosting isn't your standard Cloudfront distribution setup; I've confirmed with my app that I receive Cloudfront cache miss headers as well (using both a custom domain and the amplifyapp domain). If you experience performance issues, please cut us an issue and we'd be more than happy to look into it.
