### ISSUE TITLE
Environment mirroring

### ISSUE THREAD

**Issue by iamkevinwolf** [aws-amplify/amplify-console#6]
**Is your feature request related to a problem? Please describe.**
Sometimes, it is helpful to mirror an environment (i.e. mirroring production on pre-production or mirroring dev on feature branches specific environments)

**Describe the solution you'd like**
It would be nice if the console can show options to mirror an environment on a branch pattern (like the new automated branch autodetection flow)

**Additional context**
I don't know if this is too difficult since it may depend on N+ AWS categories, another idea will be to provide a seeding mechanism.

**Comment by adamaltman** [comment]
Here is a workaround:

1. connect another app (linked to the same repo) -- we adjusted our name to add something like repo-{env}
2. Use different env variables.  (eg sandbox-api.example.com)

We just set this up today for our similar env mirroring use cases.  It seems to be working.

**Comment by swaminator** [comment]
@adamaltman thanks for that approach. That approach should work for you to mirror an environment. Closing the issue.

**Comment by iamkevinwolf** [comment]
My suggestion was to have the same data (i.e. same cognito users, same db docs) that on the environment you want to mirror.
