### ISSUE TITLE
Restrict IAM user to only Amplify Console

### ISSUE THREAD

**Issue by araphiel** [aws-amplify/amplify-console#600]
**Please describe which feature you have a question about?**

I want to restrict the user access to *only* the Amplify Console. 
The IAM user should have no CLI access but the ability to manage the console itself (i.e. add new projects, add redirects, env variables, general settings) 

Could you help me determine the proper IAM policy needed to do this?

Something like this?

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "amplify:*"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by litwicki** [comment]
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "amplify:CreateApp",
                "amplify:CreateBackendEnvironment",
                "amplify:CreateBranch",
                "amplify:DeleteApp",
                "amplify:DeleteBackendEnvironment",
                "amplify:DeleteBranch",
                "amplify:GetApp",
                "amplify:GetBackendEnvironment",
                "amplify:ListApps",
                "amplify:ListBackendEnvironments",
                "amplify:ListBranches",
                "amplify:ListDomainAssociations",
                "amplify:UpdateApp"
            ],
            "Resource": "*"
        }
    ]
}`

The full CLI policy definition is here for reference: https://docs.amplify.aws/cli/usage/iam
