### ISSUE TITLE
About amplify command not found

### ISSUE THREAD

**Issue by rnsnknyu** [aws-amplify/amplify-console#601]
**Issue/question**
I've been using AWS Amplify to build my backend in a test environment for some time now. When I use the amplify command in production, "npm install -g @aws-amplify/cli" succeeds, but "amplify configure" command fails with "-bash: amplify: command not found”.

**Error message**
Also, even in test projects where amplify commands were previously available, running amplify related commands such as "$ amplify status", "$ amplify push", etc. will all result in "-bash: amplify: command not found”.
I have tried uninstalling node, deleting npm's cache, and all the solutions listed in the Github issue (410, 778) to solve this problem, but I have not been able to solve the above problem.

**Additipnal info**
Is there a way to solve this problem?
I'd like to know more about it.

--------------------------------------------
I was having trouble with the above issue, so I tweeted the following ( https://twitter.com/rnsnknyu/status/1251336039110606854?s=20 ) and was referred to this page by AWS Support.

**Comment by dabit3** [comment]
Hi @rnsnknyu , this definitely sounds like some sort of issue with your environment installation path and node.js. Has there been any changes to your node.js installation?

One recommended fix is to remove your node.js installation and re-install using node version manager ([NVM](https://github.com/nvm-sh/nvm)). Then, installing the Amplify CLI. NVM has a better track record of being stable with these types of issues than others.

**Comment by rnsnknyu** [comment]
I couldn't get amplify to work properly because the node path was wrong. ( I installled node via homewbrew.  This way(npm (-g@ ) was wrong.)  
Thanks for letting me know!
