### ISSUE TITLE
Wrong URLs, and Branch name Under Domain management Section

### ISSUE THREAD

**Issue by gargshantnu** [aws-amplify/amplify-console#602]
1. **Issue Description**
Wrong URLs, and Branch name Under Domain Management Section

1. **Detailed Steps To Reproduce**
    1. create a branch with `.` in the name.
    1. connect that branch in amplify.
    1. goto "Domain management" section, under `amplifyapp.com` you will see wrong branch URLs and names
![Screenshot 2020-04-18 at 1 09 32 PM](https://user-images.githubusercontent.com/23008972/79631361-912d2380-8176-11ea-958a-7ae9d3d310d3.png)

1. **Expected behavior** e.g. 
```
Expected 
URL => https://release-6-2.d392v2bx7rclk2.amplifyapp.com
Branch => release-6.2
```
```
Actual 
URL => https://release-6.2.d392v2bx7rclk2.amplifyapp.com
Branch => release-6-2
```
Note: I think variables got misplaced, variable to show URL is replaced variable to show branch.

1. **Application Details**

    a. Amplify Console AppID: d392v2bx7rclk2

**Comment by abhi7cr** [comment]
Hi @gargshantnu. Thanks for reaching out. We will be fixing this shortly.
