### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by gargshantnu** [aws-amplify/amplify-console#603]
I am having 2 questions about 
![Screenshot 2020-04-18 at 1 26 01 PM](https://user-images.githubusercontent.com/23008972/79631710-9b502180-8178-11ea-8e39-1ea6b8bc8c72.png)

1. What's the point of the "Production branch"? Why is it used? 
2. What's the point of the "Service role"? Why is it used?

**Comment by swaminator** [comment]
@gargshantnu 
1. The production branch is a label attached to a branch and doesn't have any direct consequences yet. We will be working on features to enable more workflows for production (e.g. rollbacks and pre-production stages).

2. The service role is used for backend deployments: https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html
