### ISSUE TITLE
SSL verification is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by manakbhard** [aws-amplify/amplify-console#608]
**App Id**: djxmevwb0b1d4
**Region**: ap-south-1
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
How much time will it take for ssl verification and domain activation and our main site is also not working.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by abhi7cr** [comment]
Hi @manakbhard,

Usually, domain activation (including verification) should be done within minutes. That said, there are couple of factors affecting this state:

1. Make sure your domain name is able to resolve with the CNAME and NS records listed in your Route 53 hosted zone. If  You can check it here: https://dnschecker.org/
2. Are you transferring the domain to Route53? In this case, the NS records would need to be updated to point to Route 53's NS records, and you need to make sure to set low TTL before the update. Else it would take up to 2 days to take effect.

**Comment by Joycehao19** [comment]
Hi @manakbhard , it seems that your domain works now. Closing the issue for now. If you have the same problem, please feel free to let us know!
