### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by josefm09** [aws-amplify/amplify-console#61]
**App Id**: d8k35pnf9n0rx
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by anatonie** [comment]
Hello @josefm09 

Can you please include the error message displayed on the Domain management page, or a screenshot of that page please?

Thanks

**Comment by josefm09** [comment]
![image](https://user-images.githubusercontent.com/15352246/63642329-dd24d880-c67a-11e9-9053-eeea85c06995.png)

**Comment by nimacks** [comment]
@josefm09 , we're closing this ticket because we haven't heard back from you. Please re-open if this is still an issue.
