### ISSUE TITLE
SSL verification is Running - [>8 hours verifying]

### ISSUE THREAD

**Issue by alientang** [aws-amplify/amplify-console#610]
**App Id**: d1lt6u1r37tpca
**Region**: us-east-1
**Step**: SSL verification
**Status**: Running

**Issue/question**
- Domain transferred from Google to AWS Route 53
- Nameservers updated yesterday ~11am
- May have created some additional record sets in Route 53 for the hosted domain, which I cannot seem to delete

**Error message**
- No error message

**Comment by abhi7cr** [comment]
Hi @alientang. 

We are working internally with another team which does the CNAME record verification, to understand why it is stuck in pending verification state. 

When you say you updated the Name servers, did you lower the TTL in Google, before updating them to match the ones in Route 53? Usually they take 172800 seconds, or two days to take effect.

Thank you for your patience.

**Comment by alientang** [comment]
Deleted record sets and re-added the custom domain. Worked 👌
