### ISSUE TITLE
Domain activation is Failed

### ISSUE THREAD

**Issue by linusws** [aws-amplify/amplify-console#611]
**App Id**: d2s0jhwgpjmiq9
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I'm trying to use my custom domain for my amplify implementation. As you can se it fails on with the following error message: "Error message: One or more of the CNAMEs you provided are already associated with a different resource." 

**Error message**
"Error message: One or more of the CNAMEs you provided are already associated with a different resource." 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

Thanks in advance

**Comment by linusws** [comment]
I've now removed all CNAMES associated with the domain I'm trying to set up, however, still receives the "Error message: One or more of the CNAMEs you provided are already associated with a different resource."....

**Comment by abhi7cr** [comment]
Hi @linusws. Thanks for reaching out.  I can see that the activation of the custom domain was in progress, and just finished. Are you still noticing this issue? 
This issue occurs when you have the CNAME already associated with another cloud front distribution either via another amplify app, or by your own. Usually, it's safe to wait up to an hour  for the disassociation of the CNAME from the old distribution to occur.

Here are some useful links:
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error
https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

**Comment by linusws** [comment]
@abhi7cr  I thought it was enough to disable the CloudFront distribution that contained the CNAME but apparently I had to delete them. It's now working. Thanks!
