### ISSUE TITLE
Cannot select BitBucket with Connecting a frontend web app

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-console#613]
This is a new, weird, issue, and I've logged out of the aws-console and re-opened the aws-console in a new browser window to start clean and recreate the below.

In short, when I try to connect a Bitbucket repo, I am presented with GitHub as the Repository service provider.

1.  Open existing app in Amplify Console that previously had a front-end connected to Github, but that branch has been deleted.

2.  Connect a frontend web app and select Bitbucket

![image](https://user-images.githubusercontent.com/26792769/80076993-1a799700-8577-11ea-876a-321f72abb131.png)

3.  Click connect branch

4.  The correct page flashes for a second (sometimes a bit longer), then a spinner shows, then I am presented with a page to add a repository branch from GitHub

![image](https://user-images.githubusercontent.com/26792769/80077168-544a9d80-8577-11ea-9ea4-62039d4c9aa6.png)

And, by the way, no repositories are showing under Recently updated repositories in the Github screen, not that that is what I want, but...

**Comment by kimfucious** [comment]
Potentially related to this is:

As I mentioned I had previously connected front-ends to Github branches.  These were public branches.  I deleted these front-ends in Amplify Console, as I wanted to test using a private repo (related to a separate issue #206).

The reason I am now trying to connect to a Bitbucket repo is because when attempting to Connect a frontend web app with the GitHub private repo, no branches are shown (the drop down for Branch/Select a branch from your repository is empty), even though these branches are visible in the Github web interface:

![image](https://user-images.githubusercontent.com/26792769/80079838-fddf5e00-857a-11ea-858f-947dcf50abeb.png)

**Comment by kimfucious** [comment]
Oddly, I went away and came back a few hours later to this and it auto-magically fixed itself.

I did push an entirely separate app via the CLI with `amplify push` during the meanwhile.

How that fixed a separate app in the Amplify Console, I knoweth not.

I'm gonna leave this here in case it shows again, and close this if it doesn't in a couple few.

**Comment by abhi7cr** [comment]
Hi @kimfucious. Thanks for reporting. 
The first issue (incorrect provider after disconnecting all branches, and connecting a repo) is a bug. We have added to our backlog. 
As far as the second one, I was able to connect a private github repo. Not sure if the first issue was impacting your ability to connect a private repo, since at that point its in an invalid state.

**Comment by kimfucious** [comment]
Hi @abhi7cr 

Thanks for the response.

I've got a feeling that the second one cleared up when the first one did, as they both went away at the same time.  

So if you've got this in your backlog, I'll close this out.

**Comment by kimfucious** [comment]
Sorry, I'll leave this open, so you can link this to another issue or close it.

**Comment by swaminator** [comment]
Closing as we're tracking it in our backlog. Thanks for reporting @kimfucious

**Comment by iosif-eolas** [comment]
I am having exactly the same problem and logging in and coming back doesn't solve it for me.
<img width="1467" alt="Screenshot 2021-09-24 at 14 46 13" src="https://user-images.githubusercontent.com/78685282/134685172-bfd9b04f-2170-461d-aaf9-4ce26afcba9b.png">
<img width="1156" alt="Screenshot 2021-09-24 at 14 46 31" src="https://user-images.githubusercontent.com/78685282/134685179-7dbf1250-5215-49fe-9d93-162ef4850ca8.png">
