### ISSUE TITLE
Domain activation is Failed - After CNAME confirmed 

### ISSUE THREAD

**Issue by JuliusHimself** [aws-amplify/amplify-console#616]
**App Id**: d23x1yjr8cg4n
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
The domain activation is failing, even though we can see the CNAME is correct on https://www.whatsmydns.net/  

Error message: One or more of the CNAMEs you provided are already associated with a different resource

**Comment by abhi7cr** [comment]
@JuliusHimself  This error message states this domain is already associated with another CloudFront distribution (either through an amplify app or directly using CloudFront). 
In this case, this is the appId associated with the domain: **d2cpzf13tj7nag** . You would need to disassociate the domain from this app (Clear CNAME/A records pointing to the old app in Route53/domain provider you chose) before proceeding with the activation of the domain. 
Once you disassociate, its recommended to remove the domain from this new app, and re-add it.

Here are some links about the error:
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error
https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/
