### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Phangster** [aws-amplify/amplify-console#617]
**App Id**: d243cbs54v8mx2
**Region**: ap-southeast-1
**Step**: Domain activation
**Status**: Failed

My Domain activation name failed, any solution to get it working ?

**Comment by abhi7cr** [comment]
@Phangster Thanks for reporting. Taking a look.

**Comment by abhi7cr** [comment]
@Phangster Is your domain registered in Route53 or elsewhere? Also, are you transferring the domain to Route53? 

It looks like the CNAME record is not resolving correctly. Can you make sure you have the same CNAME record in your domain configuration, as specified in the *View DNS records* section, in the Custom Domains page of your app?
