### ISSUE TITLE
Domain activation is Failed - [CNAMEs already associated with a different resource.]

### ISSUE THREAD

**Issue by alientang** [aws-amplify/amplify-console#626]
**App Id**: d36ivyynncxdo8
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
- Domain transferred from Google to AWS route 53
- Custom domain used to be associated with s3 bucket, which has since been deleted
- Setting up custom domain via AWS amplify passes SSL verification but at `Domain Activation`

**Error message**
```One or more of the CNAMEs you provided are already associated with a different resource.```

**Additional information*
 - Going to the domain gives a `NoSuchBucket` error.

See Amplify, S3, and Route 53 console

**Comment by cslogan-red** [comment]
Hi, 

The below can be helpful for troubleshooting (in the case of your domain, I can see it's still associated to the CF distribution that was created for the S3 hosting bucket, you'll need to remove it from this distribution first, and then reconnect the domain to Amplify Console):

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

A CNAME alias (mydomain.com, sub.mydomain.com) can only be associated with a single CloudFront distribution at a time, if you receive this error then the domain is already associated with another CF distribution (either within the same AWS account, or potentially in a different account) and must be disassociated from the previous distribution before the distribution created for you by Amplify Console will work, the docs help outline how to do this (and you may need to check more than one account if you or your organization owns multiple accounts)

Additionally, if you manage your domain through Route53, make sure to clean up any hosted zone CNAME or ALIAS records that point to the old distribution. After completing the above, I would remove the domain from Amplify Console and start the flow over.

**Comment by Athena96** [comment]
Closing this issue. Please re-open if you are still facing issues.
