### ISSUE TITLE
Domain activation is Failed - Retry button not working

### ISSUE THREAD

**Issue by sferencik** [aws-amplify/amplify-console#630]
**App Id**: dje4umfxudl7v
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
My domain won't activate.

The domain was previously registered through CDK. I've deleted the respective CloudFormation stack and made sure the domain was removed from Route53. However, 3 hours later Amplify is still telling me

> Error message: One or more of the CNAMEs you provided are already associated with a different resource.

As per the [Troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error) it's advised to wait for up to 6 hours. I've only waited 3+ now. However, what's disconcerting is that under AWS Amplify > Domain management the "Retry" button has stopped working. I can click it any number of times, it doesn't seem to initiate the retry.

**Error message**
> Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by cslogan-red** [comment]
It looks like your domains have since come up, let us know if you still have any questions.
