### ISSUE TITLE
How to Exclude draft PRs in github from the Enable Preview feature

### ISSUE THREAD

**Issue by shrirupa** [aws-amplify/amplify-console#639]
How to Exclude draft PRs in github from the Enable Preview feature

I don't want the preview to be enabled for draft PR and only want this enabled if the PR is marked ready for review.

**Comment by swaminator** [comment]
@shrirupa you currently cannot. A lot of customers have *asked* for PRs to be supported in draft PR mode so not sure we are going to prioritize this. As a workaround, submit draft PRs to another branch and when you're ready, update the PR to point to a different branch.
