### ISSUE TITLE
Console does not detect React framework if react-scripts is a devDependency

### ISSUE THREAD

**Issue by kevinwolfdev** [aws-amplify/amplify-console#640]
If I add `react-scripts` as a `devDependency`, the console doesn't detect React as my Frontend framework.

**Comment by Joycehao19** [comment]
Hi @kevinwolfdev , would you mind tell us how you set it? I'll investigate on your issue

**Comment by Joycehao19** [comment]
Hello @kevinwolfdev , do you still face this issue?
