### ISSUE TITLE
Environment variable per domain

### ISSUE THREAD

**Issue by MatanYadaev** [aws-amplify/amplify-console#641]
I want to have 3 environments on different domains:
1) Production - using `master` branch
2) Staging - using `develop` branch
3) Testing - same as staging, using `develop` branch

Is that an option to provide different environment variables for staging and testing?

**Comment by Joycehao19** [comment]
Hi @MatanYadaev , we don't support connect same branch twice in the same application. You could connect 2 applications, 1: Production and Staging, 2: Testing. 
For different environments variables: 1. you could use amplify cli to create different backend environments and push to the cloud. (ref: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#quickstart) Then in Amplify Console, you could select different backend env. 2. Other way is using Amplify Console's environment variable feature.(https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html)

If you have another questions, please let us know!

**Comment by juliomilani** [comment]
Hi, I faced the same issue. 

For testing purposes we exctracted the environment variables with window.location.href. Works like a charm.
