### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by nagey** [aws-amplify/amplify-console#645]
**App Id**: dujkbofvrl3he
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I have a particular subdomain for this project that *always* tries to redirect from https://subdomain.domain.com to https://www.subdomain.domain.com/ — even though i've not set it up that way

**Comment by Joycehao19** [comment]
Hi @nagey , could you please take a look on your `rewrites and redirects` section? Anything here?

**Comment by nagey** [comment]
yep. good to know that the console is putting it in there i suppose. would be neat to have a link from where it says "redirects to" to the redirects panel. I had assumed it was handled within something internally (like the cloudfront distro, for example)
