### ISSUE TITLE
Allow users to delete backend environments on console without requesting cli

### ISSUE THREAD

**Issue by hirochachacha** [aws-amplify/amplify-console#647]
**Is your feature request related to a problem? Please describe.**

There're many backend environments I don't use now.

![image](https://user-images.githubusercontent.com/898442/81045826-fb252700-8ef1-11ea-8c7a-77a191b49e44.png)

I'd like to delete these environments, however when I choose `Delete` from `Actions` drop menu, I see

![image](https://user-images.githubusercontent.com/898442/81045952-42131c80-8ef2-11ea-88a6-e1586432547b.png)

Those entries are already dropped from my `team-provider-info.json`. So I can't delete them.

**Describe the solution you'd like**

Provide independent way to delete backend environments.

**Comment by swaminator** [comment]
@hirochachacha are you saying that you already deleted these envs from the CLI but they are still showing up in the console?

**Comment by hirochachacha** [comment]
@swaminator I'm not sure about that. I don't always use CLI for deleting resources. I often use CloudFormation console to delete them. In any case, I have no way to delete them now.

**Comment by dletozeun** [comment]
Hello,

I have the same issue athough I used the CLI to remove the environment. An error happened during the environment removal causing an infinite waiting loop in the CLI command.

I can remove manually the environment in team-provider-info.json and manually delete all allocated ressources in the cloud but the backend entry still remain in the Amplify console without any way to force remove it. How come that the CloudFormation stack doesn't clean up as well the Amplify console?

Thanks!

**Comment by swaminator** [comment]
@dletozeun currently you can use the AWS CLI as a workaround to delete the backend environment after you have deleted the stack manually via the Console - https://docs.aws.amazon.com/cli/latest/reference/amplify/delete-backend-environment.html

**Comment by bhuber** [comment]
I just ran into this issue, we had several phantom backend environments that couldn't be deleted from the console UI.  @swaminator 's workaround did the trick, but it took a while to figure out.  Given that the original issue (can't delete phantom backend envs from the console) still persists, can this be reopened?
