### ISSUE TITLE
One click deploy - Choose environment variables

### ISSUE THREAD

**Issue by heitorlessa** [aws-amplify/amplify-console#65]
**Is your feature request related to a problem? Please describe.**

As a customer using one-click deploy, I'd like to provide environment variables that are essential to deploy my application successfully. 

Without this feature, I have to take 3 additional steps to bootstrap my application:

1. One-click deploy
2. Set Environment Variables I need (i.e. STRIPE_KEY)
3. Trigger another build

**Describe the solution you'd like**

Ability to set Environment Variables when using one click deploy feature. Pretty much the same way I can do when manually deploying an App through Amplify Console.

**Additional context**

App I'm trying to use one click deploy and provide Environment Variables: https://github.com/aws-samples/aws-serverless-airline-booking

**Comment by heitorlessa** [comment]
@swaminator The value is only known at one-click deploy time, hence i couldn't use that

**Comment by swaminator** [comment]
@heitorlessa this is now available in production
![Screen Shot 2019-12-09 at 2 20 44 PM](https://user-images.githubusercontent.com/2429410/70478159-3e888000-1a8f-11ea-8c2e-e26da2273e8d.png)
