### ISSUE TITLE
Domain activation is Failed while transferring between AWS accounts

### ISSUE THREAD

**Issue by innesian** [aws-amplify/amplify-console#650]
**App Id**: d3av0syqkxkpyw
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Domain activation won't go through despite the domain's name servers being served in Route 53

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
We've recently moved the domain's nameservers from a different AWS account and need to set it up in the new one attached to Amplify. We also set up a certificate in certificate manager

**Comment by Joycehao19** [comment]
Hey @innesian , do you still face this issue?

**Comment by OzzieOrca** [comment]
I might have struggled with the same issue. Does https://github.com/aws-amplify/amplify-console/issues/512#issuecomment-639892355 help?
