### ISSUE TITLE
The Deploy freezes after a success Build

### ISSUE THREAD

**Issue by itdoh** [aws-amplify/amplify-console#651]
We have problems with some deploying. The provisioning and the build finish successfully, but the Deploy freezes without any information about any problem. We tried to set up in different regions in EU but the problem still.

**Comment by Joycehao19** [comment]
@itdoh , I'm sorry that you are having this issue. Would you mind share your appId and region? I'll investigate your issue.

**Comment by itdoh** [comment]
Hi @Joycehao19 thank you for your response. These are the information:
appId: arn:aws:amplify:eu-central-1:000098351948:apps/d3lfc9pdtt3gfv
region: eu-central-1
Thanks!

**Comment by swaminator** [comment]
Closing this to track in #115.

**Comment by itdoh** [comment]
Hi @swaminator , 

The issue persists. Now we are trying in a new APP with the same code that other APP that is Deploying well:

These are the APP with problems to deploy:
**ARN:** arn:aws:amplify:eu-central-1:000098351948:apps/d2k00by58w5diy
**region:** eu-central-1

These are the APP Deploying well:
**ARN:** arn:aws:amplify:eu-central-1:000098351948:apps/d2fbd8k0un5fqf
**region:** eu-central-1

The two APP have the same code.

Thanks!
