### ISSUE TITLE
SSL verification is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by dgnabasik** [aws-amplify/amplify-console#652]
**App Id**: d3fs0vdmimg8k8
**Region**: us-west-2
**Step**: SSL verification
**Status**: Failed

**Issue/question**
1) I successfully transferred my **flyingmonkeyssocialclub.com** domain to Amazon. You sent an email dated May 4 with the message "We have finished transferring your domain registration for the domain flyingmonkeyssocialclub.com from your previous registrar to Amazon Route 53." I have updated the name servers manually. and rebooted the instance. The domain still fails verification.

2) In addition, I see this error when building **backend-env**: 
Message: Service:AmazonCloudFormation, Message:Template format error: Resource name sg-091bd5407b047bafc is non alphanumeric.
Environment: backend-env
Application: fmsc-app
Environment URL: http://backend-env.eba-ghjmpsdt.us-west-2.elasticbeanstalk.com
RequestId: 14f10470-c912-4bd0-be51-81da7692626b
NotificationProcessId: 45825401-8ade-45e1-8a6d-28b8165d73b5

sg-091bd5407b047bafc is specified in two files in the .ebextensions folder (following amazon-provided examples):
# https-backendsecurity.config
Resources:
  # Add 443-inbound to instance security group (AWSEBSecurityGroup)
  httpsFromLoadBalancerSG: 
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: {"Fn::GetAtt" : ["AWSEBSecurityGroup", "GroupId"]}
      IpProtocol: tcp
      ToPort: 443
      FromPort: 443
      SourceSecurityGroupId: {"Fn::GetAtt" : ["sg-091bd5407b047bafc", "GroupId"]}
  # Add 443-outbound to load balancer security group (sg-091bd5407b047bafc)
  httpsToBackendInstances: 
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: {"Fn::GetAtt" : ["sg-091bd5407b047bafc", "GroupId"]}
      IpProtocol: tcp
      ToPort: 443
      FromPort: 443
      DestinationSecurityGroupId: {"Fn::GetAtt" : ["AWSEBSecurityGroup", "GroupId"]}

# https-lbsecuritygroup.config   Use the custom security group for the load balancer
option_settings:
  aws:elb:loadbalancer:
    SecurityGroups: '`{ "Ref" : "sg-091bd5407b047bafc" }`'
    ManagedSecurityGroup: '`{ "Ref" : "sg-091bd5407b047bafc" }`'
Resources:
  sg-091bd5407b047bafc:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: load balancer security group
      VpcId: vpc-5a4e8c22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

**Error message**
Domain flyingmonkeyssocialclub.com failed on SSL verification.
We could not verify ownership of the domain. Error message: The status of this certificate request is "Failed". 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by dgnabasik** [comment]
What is the exact string that replaces the string "sg-091bd5407b047bafc" in 3 places in the https-lbsecuritygroup.config file?

**Comment by ganipcanot** [comment]
Resolving due to age - re-open if you are still facing the issue!
