### ISSUE TITLE
Amplify console - Build successful but fails to deploy

### ISSUE THREAD

**Issue by rnaresh** [aws-amplify/amplify-console#653]
Hi,

We are using Amplify to build a new website using docusaurus. It started failing to deploy for preview branches from the past 20 days

![image](https://user-images.githubusercontent.com/4458618/81261902-891c2180-905a-11ea-990f-59695c4779e8.png)

App ARN - arn:aws:amplify:us-east-2:582734241681:apps/dpwfbpxczhwpr
The artifact size is ~76MB
node_modules folder size is 160MB.

this is blocking our build pipeline. can you let us know what could be the reason for build failures in the last few weeks?

**Comment by swaminator** [comment]
It looks like you're running into one of the issues from #115 due to. While we work on fixing the underlying issue, a workaround would be to close the PR's and potentially move your development branches into a separate Amplify app. Closing to track in one place.
