### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by webpatser** [aws-amplify/amplify-console#655]
**App Id**: d1cupcx2bjjgh4
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Verification fails. Domain is hosted in route53

**Issue/question**
No error is given. Besides that it just fails.

**Error message**
No message..

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Joycehao19** [comment]
Hello @webpatser , sorry that you are having this issue. Could you please try remove and re-add your custom domain?

**Comment by webpatser** [comment]
Did that twice already.. Same result.. 3 green steps. The final step fails. It says the domain already points to an address. Even after removing the records from route53 they cannot be created.

**Comment by Joycehao19** [comment]
"It says the domain already points to an address." It seems like you connected  your domain with other application. Did you remove it?

**Comment by Joycehao19** [comment]
Hello @webpatser , do you still face this issue?
