### ISSUE TITLE
The test phase is hanging with a Vue js project

### ISSUE THREAD

**Issue by ben-elsen** [aws-amplify/amplify-console#658]
** Please describe which feature you have a question about? **
I have a basic vue js project with cypress tests but the Amplify console keeps hanging in the test phase. 

When I do the commands on my macbook, everything works.

Thanks for the help!

My amplify.yml is:
`version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
  phases:
    preTest:
      commands:
        - npm ci
        - npm install wait-on
        - 'npm start & npx wait-on http://localhost:3000'
    test:
      commands:
        - 'npx cypress run --spec cypress/integration/All.features'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json`

** Provide additional details**

**Comment by Joycehao19** [comment]
@ben-elsen Sorry that you are facing this issue. Would you mind share your appID, region and build setting with us?

**Comment by ben-elsen** [comment]
hi @Joycehao19,
Thanks for reaching out! 
Yes off course! 
The appID is d3l9k6n4w6fsrl
The region is eu-west-1 
The build setting are attachted.
[amplify.txt](https://github.com/aws-amplify/amplify-console/files/4602116/amplify.txt)

**Comment by ben-elsen** [comment]
Hello @Joycehao19, 
Is there already any update on this? 
Best regards,
Ben

**Comment by Joycehao19** [comment]
Hi @ben-elsen  could you please try this: https://github.com/aws-amplify/amplify-console/issues/583#issuecomment-614385089 ?

**Comment by ben-elsen** [comment]
Hi @Joycehao19 I tried this en this didn't resolved the problem. The test phase kept freezing..
