### ISSUE TITLE
Constantly failing deploys

### ISSUE THREAD

**Issue by simpson** [aws-amplify/amplify-console#660]
** Please describe which feature you have a question about? **
Failing deploys are back again, halp!

** Provide additional details**
https://github.com/aws-amplify/amplify-console/issues/541

**Comment by simpson** [comment]
@swaminator @ericclemmons @jpeddicord @cslogan-red @litwicki 

can we get a check in health check in place for the backend deploy pipeline dependency that reports to the AWS status page? It is frustrating to reach out to AWS support and they say everything is fine because the status page is green...

**Comment by simpson** [comment]
@ganipcanot @Athena96

**Comment by simpson** [comment]
This problem is back, AWS support won't help..

**Comment by simpson** [comment]
@swaminator @ericclemmons @jpeddicord @cslogan-red @litwicki

Any help? Deploys have been broken for over 4 days for us.

**Comment by simpson** [comment]
@dabit3 @ ericclemmons @harrysolovay @jamesonwilliams @jpignata @kneekey23 @manueliglesias @mauerbac @palpatim @rohitchandalurivt @royjit @wooj2

**Comment by simpson** [comment]
@gsans

**Comment by litwicki** [comment]
@simpson Are you experiencing this in the same appId as your previous post #541? How many branches are in your repo? Do you know off hand how many files per branch on average?

**Comment by simpson** [comment]
@litwicki Same two branches as before, we are pretty simple with staging and production branches that build off the develop and master branch in Github. I think they have about 5k files, but a significant portion don't update each deploy

**Comment by gsans** [comment]
Thanks for reaching out. Sorry to hear about this @simpson. By the looks of it someone needs to take a look at your setup to properly diagnose these intermittent deployment failures once for all. Sorry if it takes a bit longer to find a fix.

**Comment by litwicki** [comment]
@simpson we're going to have @donkahn work with you on this shortly. To recap you have `production` and `staging` branches for hosted environments, and then `develop` and `master` branches your team works off? Am I correct you would have 4+ branches, where at most there are ~5k files?

**Comment by simpson** [comment]
@litwicki  Sorry I wrote that confusing before. We have two branches, master = production, develop = staging. They are usually very close in nature, we almost always merge develop to master after every single successful build

**Comment by simpson** [comment]
@donkahn to the rescue! Thanks @litwicki !

**Comment by litwicki** [comment]
@simpson are you up and running now then?

**Comment by simpson** [comment]
nope, deploys still failing. Hoping that @donkahn can help us track down the problem. It must be something on our end if all Amplify customers aren't impacted

**Comment by kahdojay** [comment]
@simpson It looks like you're running into one of the issues from #115 due to having several open pull requests creating multiple branches. Whlie we work on fixing the underlying issue, a workaround would be to close the PR's and potentially move your development branches into a separate Amplify app (i.e. Connect your non-prod branches to another Amplify app and use the same app to test your PRs)

Let me know if this doesn't help resolve the deploy failures.

**Comment by simpson** [comment]
@kahdojay it seems strange that external branches will break master. I can't delete the PRs but i'm happy to delete the previews, is there a way to remove the preview branch builds? I can't find anything in the UI.

I'll also look at setting up a new app to see if that helps

**Comment by simpson** [comment]
@kahdojay it is failing in the new app but I think I just don't have everything setup yet. Is there an ETA on the failing deploys before I start deleting important PRs?

**Comment by kahdojay** [comment]
@simpson the only way to do it currently is to close the PR in github which will automatically delete the Amplify branch. 

You may need to work on a smaller number of PRs at a time if possible to circumvent the issue.

Re ETA, I don't have one to share at this moment but we are actively working on it and #115 is the issue to watch for updates.

Let me know if you're still not able to get things working on the new app after trying the above.

**Comment by simpson** [comment]
@kahdojay I just removed all of our PRs, I sure hope this works. I can't even redeploy master because it is hung up on something 
![Screenshot 2020-05-11 17 32 33](https://user-images.githubusercontent.com/1605737/81614118-8f3d3580-93ad-11ea-83d2-5a8baf9d38a6.png)

**Comment by kahdojay** [comment]
@simpson I see the recent failure ~15m ago was for the same issue - I still see four pr branches in place against one of your non prod branches. Can you check?

**Comment by simpson** [comment]
@kahdojay staging deployed but master won't... It has failed twice since removing all PRs

**Comment by kahdojay** [comment]
Hi @simpson can you provide a recent example of the branch and build number that failed for d12hn9rteao8a1?

**Comment by swaminator** [comment]
Closing this issue in favor of #115. We are in the process of deploying an update to fix deploy failures. Please track progress there.
