### ISSUE TITLE
[Post deploy issue] API and Storage not working

### ISSUE THREAD

**Issue by lambda0xff** [aws-amplify/amplify-console#662]
I have a nuxt js project with amplify.
Amplify set up with Auth, API and Storage
Working fine on local machine.

After successfull deploy, the site is up and running.
Auth is working.

API is not working: the dataStore is not making any graphql calls to sync 
Storage is not working: trying to upload an image fails with message: `S3 upload error TypeError: Cannot read property 'put' of null`

**Comment by kahdojay** [comment]
@lambda0xff can you provide your AppId and region?

**Comment by lambda0xff** [comment]
@kahdojay 
region: us-east-1
app ARN: arn:aws:amplify:us-east-1:544250939827:apps/d8el6qegalxiu

**Comment by swaminator** [comment]
@lambda0xff in your amplify console app, how many frontend and backend envs do you have?

**Comment by lambda0xff** [comment]
@kahdojay : 1

**Comment by swaminator** [comment]
@lambda0xff just to be clear, you are hosting your frontend on Amplify Console with CI/CD? What are your backend envs named?

**Comment by lambda0xff** [comment]
env name is `amplify`
![Screen Shot 2020-05-15 at 08 10 00](https://user-images.githubusercontent.com/38687176/82017498-943b0700-9683-11ea-9008-fe5f47f842f4.png)
![Screen Shot 2020-05-15 at 08 10 19](https://user-images.githubusercontent.com/38687176/82017505-969d6100-9683-11ea-99f5-5b500db953e8.png)

**Comment by Athena96** [comment]
What's the error message for your graphql api calls that fail?
Also ensure you are [configuring 'Amplify'](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js#configure-your-application)
`Amplify.configure(awsconfig);`

**Comment by Athena96** [comment]
Closing this ticket, please re-open if you are still facing issues
