### ISSUE TITLE
Map preview branches to custom domain

### ISSUE THREAD

**Issue by Munsterberg** [aws-amplify/amplify-console#663]
We want to automate preview branches but our backend systems require the same domain for sessions and cookies to work properly. Instead of building preview branches to `https://pr-299.d3ka6awcf02t21.amplifyapp.com` we want them to map to our custom domain:

`https://pr-299.d3ka6awcf02t21.customdomain.com`

Is this possible currently, and if not is it something we can request?

**Comment by swaminator** [comment]
@Munsterberg currently it isn't available. We are working on a capability to support automatic subdomains for PRs (so you can get `https://pr-299.customdomain.com` automatically)

**Comment by NehaBharadwaj14** [comment]
> @Munsterberg currently it isn't available. We are working on a capability to support automatic subdomains for PRs (so you can get `https://pr-299.customdomain.com` automatically)

Good to know that this will be supported. Do we have any timeline for this feature?
We use Amplify console for our application as well(which works like a charm) and since we use cookies with a particular domain, this feature would be really helpful for pre-testing phase.

**Comment by swaminator** [comment]
Feature is now supported: https://aws.amazon.com/blogs/mobile/automatically-create-and-delete-custom-sub-domains-for-your-branch-deployments-with-amplify-console/

**Comment by julieReitter** [comment]
@swaminator Does the feature you listed above also work for multi-level subdomains? For example 
`https://pr-123.customsubdomain.customdomain.com`. We have been having trouble trying to configure it this way.

**Comment by garyleework** [comment]
@julieReitter Yes. You can register the root domain as customsubdomain.customdomain.com and enable autosubdomain feature for PR branch.

**Comment by croossin** [comment]
@swaminator does the below seem to work?

> @swaminator Does the feature you listed above also work for multi-level subdomains? For example
> `https://pr-123.customsubdomain.customdomain.com`. We have been having trouble trying to configure it this way.
