### ISSUE TITLE
Page can’t be found in all my *.amplifyapp.com pages.

### ISSUE THREAD

**Issue by 07Gond** [aws-amplify/amplify-console#664]
Hi!

I have been working with Amplify console for a while and have a project with branches connected and PR previews.

Suddenly today all my branches and PR Previews URL fail with a "HTTP ERROR 404" The weird part is all the Build and Deploy works fine and doesn't show any error. But the Verify part shows me nothing.

![image](https://user-images.githubusercontent.com/2708687/81829682-c839ef00-9500-11ea-9f95-d3048d7a57a7.png)

**Comment by swaminator** [comment]
@07Gond did you change anything in your app code?

**Comment by 07Gond** [comment]
Hi @swaminator 
Thanks for the answer.
About your question:
On my PR branches, yes.
But none of my branches are currently working.
Neither our master branch.

**Comment by 07Gond** [comment]
This is weird.
Some teammates just told me in some countries they can access to the our pages.
But in others is not posible.
I just tried changing my country trough VPN and it's true.

**Comment by diegorey** [comment]
Same happening here. 404 on all Amplify projects... Both custom domains and amplifyapp domains... This is really bad.

**Comment by nimacks** [comment]
@diegorey can you share your app Id and the region it's located in?

**Comment by diegorey** [comment]
Thanks @nimacks 
d1eidccxtm3b0v 
us east 2

**Comment by nimacks** [comment]
@diegorey, this app is loading on my end without issue. Are you still having this issue? Can you provide a screenshot?

**Comment by diegorey** [comment]
Blank page, this appears on console...
<img width="650" alt="Screen Shot 2020-05-14 at 00 51 23" src="https://user-images.githubusercontent.com/4524865/81897870-1d1b4b00-957d-11ea-891b-bd04ad500bf4.png">

**Comment by diegorey** [comment]
Did you guys did any DNS or domain related changes?

**Comment by nimacks** [comment]
![image](https://user-images.githubusercontent.com/4107271/81898358-5cda3680-956d-11ea-819b-72df51f24b88.png)

Are you connected to a VPN? Custom domain also loads fine for me.

**Comment by diegorey** [comment]
No VPN. My internet has been failing, but that doesn't seem to be the reason. I'll check again first thing tomorrow. Thanks a lot for the help.

**Comment by 07Gond** [comment]
Hi!
This is still happening to me.
It seems to be a regional issue or something like that.
In some countries my app is inaccessible.
I can’t see any of my amplify URLs.
Could you help me please?

**Comment by diegorey** [comment]
Same here still. It seems like when you visit in one Internet Provider (Movistar) it doesn't work. On the other one (Claro) the pages work. All my pages have this problem like 10-12 hours no.

@07Gond Gerson, he visto que somos los dos de Lima. En Movistar no me funciona ninguno de mis dominios. En Claro funciona bien. A ver si encontramos una solución. Saludos

**Comment by diegorey** [comment]
FYI the same domain that doesn't work on amplify works outside of amplify just fine. It's something to do with Amplify DNS and Movistar I presume.

**Comment by diegorey** [comment]
<img width="1199" alt="Screen Shot 2020-05-14 at 08 29 00" src="https://user-images.githubusercontent.com/4524865/81940271-098fd480-95bd-11ea-8bbd-79bbfbba600e.png">

**Comment by cardapfysj** [comment]
I am facing the same problem.

All of my apps deployed in Amplify are out.

Does anyone know if there is any inconsistency?

**Comment by diegorey** [comment]
Maybe has to do with some propagation issue?
https://www.whatsmydns.net/#NS/amplifyapp.com

**Comment by cardapfysj** [comment]
No, everything seems to be ok with the propagation
URL: https://prototipo.d3lyaldmsq62k1.amplifyapp.com/

**Comment by diegorey** [comment]
FYI I can't see the link you sent.

**Comment by 07Gond** [comment]
Yep, me neither.

**Comment by brustrokes** [comment]
Same problem here, all my amplify web apps works in US and Europe but not in Brazil.
It's the first time in 6 months thats something like that happened.
I already change all my productions to EC2 because of that.

**Comment by diegorey** [comment]
@swaminator What can all this be about?

**Comment by swaminator** [comment]
@diegorey @brustrokes @07Gond @cardapfysj we are actively working on a fix. Can you all please share your appids?

**Comment by diegorey** [comment]
All mi apps are down. This is the main one for me now:
"AmplifyAppId": "d1eidccxtm3b0v"

**Comment by 07Gond** [comment]
@swaminator Thanks for that.
Mine: "dcafkenry5r1s"

**Comment by brustrokes** [comment]
Thanks @swaminator 
d1oqvea6agt043
d1pqai6zizkyws

**Comment by diegorey** [comment]
Don't know if related but yesterday I updated @aws-amplify/cli to 4.19.0 and push commits.

**Comment by cardapfysj** [comment]
Thanks @swaminator 

I changed US East(Ohio) to US East(N. Virginia), deployed a new app (same branch) so I was able to get my running. But I wouldn't like to settup all my apps again.

I've tried to create a new app and using the region US East(Ohio) and I am getting the same error (for new apps)

apps:
appId: d3krtq2ap4no57
appId: d30ylowmgspppn
appId: d2rq0zlx8ozyr1
appId: d2otc9dftt6wnk
appId: d60jutd32fqp
appId: d29t02iyu971xu
appId: d2rfajyrywyawp
appId: d13a3m8kjupo00

**Comment by diegorey** [comment]
All pages work fine for me if using Internet Provider Claro (I'm in Peru). The problem only occurs with Internet Provider Movistar for me...

**Comment by swaminator** [comment]
@diegorey @brustrokes @07Gond @cardapfysj  all your apps are accessible from outside of the Sau Paulo region currently (e.g. I'm sitting in Seattle can access your apps). We have an issue we are urgently working to fix. Will update as we make changes.

**Comment by brustrokes** [comment]
Thanks @swaminator , All my apps are now accessible

**Comment by cardapfysj** [comment]
ok @swaminator, thanks. I am located in Sao Paulo, so probably I will have to wait for the fix.

Thanks.

**Comment by juandans01** [comment]
Hi! just to let you know, same problem here, from Argentina

**Comment by swaminator** [comment]
@juandans01 we don't have visibility into how your internet provide maps DNS requests. We have a fix and are testing it in beta right now.

**Comment by juandans01** [comment]
Awesome for the fix, is there any way i can check that I'm having the same issue ?
Thanks

**Comment by swaminator** [comment]
If you're having the same problem as reported here you have the same issue @juandans01

**Comment by juandans01** [comment]
Silly question haha, sorry.

**Comment by rafaelcamaram** [comment]
Still having this issue here :/

**Comment by cardapfysj** [comment]
Now it is working. Thanks @swaminator.

**Comment by 07Gond** [comment]
> Still having this issue here :/

Me too

**Comment by kahdojay** [comment]
@07Gond we're still rolling out the fix to all regions, please standby

**Comment by diegorey** [comment]
It appears to be fixed for me. Thanks @swaminator @kahdojay !!

**Comment by kahdojay** [comment]
@07Gond can you please try again

**Comment by 07Gond** [comment]
Yep. It's working now!
Thanks!

**Comment by kahdojay** [comment]
Great! Resolving this one for now, if any other apps are still experiencing this issue please reopen.

**Comment by karthik2872** [comment]
Folks US-East-1 N.Virginia region , get this error 

This main.d32wlvp146067e.amplifyapp.com page can’t be found

Simple steps followed to generate a basic react app through amplify console and github, changes to app.js are getting deployed from Github --> amplifyapp but url above is not reachable

**Comment by Athena96** [comment]
Hi @karthik2872 it appears you have no build configured in your build spec.  So you build step will essentially no-op and your deploy has nothing to deploy leading to the error you're seeing when you try to hit your app url.
Please update your build spec to something like the following, then trigger a new build.
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by jhlusko** [comment]
Still having this issue for https://master.d3bce1v0sadz4r.amplifyapp.com/

**Comment by exchangebooks-in** [comment]
https://dev5640.d37vslkboi4t5y.amplifyapp.com/ not working.
showing This site can’t be reachedThe webpage at https://dev5640.d37vslkboi4t5y.amplifyapp.com/index.html might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED

**Comment by guidocaru** [comment]
I have the same problem here. Deployment and build were ok but when i try to requiest my page it doesn't work.
link: [](https://main.dm6k4ybl3z7sh.amplifyapp.com/)
![dfsdf](https://user-images.githubusercontent.com/61260656/190357704-856724a7-1492-470b-9098-ec874d2e5e8d.PNG)

**Comment by phoenixbeats01** [comment]
Having this problem too. Build succeeds and domain connects, getting 404 on all amplify urls.
