### ISSUE TITLE
Reconnect repository - bitbucket

### ISSUE THREAD

**Issue by gaochenyue** [aws-amplify/amplify-console#666]
** Please describe which feature you have a question about? **

When click on Reconnect repository, it only allows me to connect Github, but my code is in bitbucket. can I have options to choose which I want to reconnect?

** Provide additional details**

**Comment by kahdojay** [comment]
@gaochenyue Reconnect will use the provider that was used to create the app, you can create a new app using the Bitbucket repository

**Comment by gaochenyue** [comment]
@kahdojay thanks. What if I use manual deployment first and later I want to use bitbucket?

**Comment by Joycehao19** [comment]
Hi @gaochenyue you can always create a new app if you need to change the provider. Closing the issue for now. If you have another question, please feel free to contact us.
