### ISSUE TITLE
Domain activation is Failed - CNAMEAlreadyExists

### ISSUE THREAD

**Issue by danielnewman82** [aws-amplify/amplify-console#672]
**App Id**: d2o0rxo6ojduah
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
It says "Error message: One or more of the CNAMEs you provided are already associated with a different resource." I deleted the CNAME records from my hosted zone in Route 53, and they should never have been associated with any other resources in the first place. How do I fix that?

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**

**Comment by Athena96** [comment]
Hi @danielnewman82 
These guides are helpful for common custom domain issue. If those guides can not solve your issues, please let us know.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

**Comment by danielnewman82** [comment]
Yep, I already tried those.

**Comment by Joycehao19** [comment]
Hi @danielnewman82 , it seems like your custom domain associate with a deleted app in us-east-2. could you please send an email to aws-amplify-customer@amazon.com , with the link of the issue(https://github.com/aws-amplify/amplify-console/issues/672)? We will help you from there!

**Comment by OzzieOrca** [comment]
I might have struggled with the same issue. Does https://github.com/aws-amplify/amplify-console/issues/512#issuecomment-639892355 help?

**Comment by Athena96** [comment]
Hi @OzzieOrca are you still facing this issue?

**Comment by OzzieOrca** [comment]
Nope, deleting the domain from the Cloudfront Alternate Domain Names
(CNAMEs) field fixed it for me.

**Comment by OzzieOrca** [comment]
I didn't create this issue but hopefully the post author got things working :)
