### ISSUE TITLE
Domain activation is Failed - CNAME was in use before

### ISSUE THREAD

**Issue by dudestein** [aws-amplify/amplify-console#675]
**App Id**: dn7cz6uoj1m3z
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Domain validation is failed because during the first attempt the CNAME was attached to a Cloudfront Distribution already.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
The CNAME was detached from the previous resource and is clear to be used already, but any RETRY still yields the same failure result.

**Comment by Athena96** [comment]
Hi @dudestein
These guides are helpful for common custom domain issue. If those guides can not solve your issues, please let us know.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

**Comment by Joycehao19** [comment]
Hello @dudestein , did you associate the domain to other service? If so, make sure you are not trying to reuse one of the hostnames. 

ref: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

**Comment by dudestein** [comment]
That was exactly the case. The subdomain was initially attached to a
different load balancer.
I ultimately got it to work. I'm having a hard time with the redirects, but
the domain was activated after a while.

Thank you very much!!!
