### ISSUE TITLE
amplifyPush --simple not working with dotnet

### ISSUE THREAD

**Issue by CoreyPritchard** [aws-amplify/amplify-console#676]
**Describe the bug**
I am working on setting up the console using the new [dotnet Amplify support](https://aws.amazon.com/blogs/developer/introducing-net-core-support-for-aws-amplify-backend-functions/). I have a react front-end with a dotnet serverless back-end. I setup my app with the default build settings that are generated as part of the documentation (i.e. `amplify.yml`):
```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```

However, when I go to deploy this, it fails while building the back-end:
```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-05-14T21:16:57.459Z [INFO]: 
2020-05-14T21:16:57.460Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
2020-05-14T21:16:57.745Z [INFO]: Amplify AppID found: xxxxxxxxxx. Amplify App name is: ReactAmplified
2020-05-14T21:16:57.837Z [INFO]: Backend environment dev found in Amplify Console app: ReactAmplified
2020-05-14T21:16:58.239Z [INFO]: 
2020-05-14T21:16:58.909Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-05-14T21:17:02.184Z [WARNING]: - Initializing your environment: dev
2020-05-14T21:17:03.226Z [WARNING]: ✔ Initialized provider successfully.
2020-05-14T21:17:03.363Z [INFO]: Unable to find dotnet version 3.1 on the path.
2020-05-14T21:17:03.365Z [INFO]: init failed
                                 Error: Missing required dependencies to package ReactAmplify
                                 at buildResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/build-resources.js:28:11)
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-14T21:17:03.366Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
                                    ✖ There was an error initializing your environment.
2020-05-14T21:17:03.379Z [ERROR]: !!! Build failed
2020-05-14T21:17:03.465Z [ERROR]: !!! Non-Zero Exit Code detected
2020-05-14T21:17:03.465Z [INFO]: # Starting environment caching...
2020-05-14T21:17:03.465Z [INFO]: # Environment caching completed

```

It seems to know the problem when it says `Unable to find dotnet version 3.1 on the path`, but I'm not sure the fix. Also, it seems like this should be adjusted for the default dotnet amplify template and/or added in documentation.

**To Reproduce**
1. Follow [this documentation](https://aws.amazon.com/blogs/developer/introducing-net-core-support-for-aws-amplify-backend-functions/), but instead of an Angular app, make a React app. 
2. Push to a git repository. I'm using GitLab, but I'm sure the same issue would occur with GitHub too.
3. Connect a branch for the front-end.
4. Do a build.

**Expected behavior**
I expect the back-end to build successfully with the default settings. I also expect that the default amplify template would have already had this setup successfully.

**Screenshots**
n/a

**Additional context**
In another app I have, I am able to build React without a problem. This experiment is me trying to add the dotnet backend and ultimately setup dev/prod environments. The environments seem to be setup great when testing locally, but the problem occurs when trying to setup the build in the amplify console.

**Comment by swaminator** [comment]
@CoreyPritchard  .net is not installed in the build container. Could you try adding `sudo yum install dotnet-sdk-x.x` to your amplify.yml

**Comment by CoreyPritchard** [comment]
@swaminator Thanks for looking into this for me! I added `sudo yum install dotnet-sdk-3.1`, which complained about `sudo`, saying `line 5: sudo: command not found`. So, I tried it without, and got the error `No package dotnet-sdk-3.1 available.`. 

For reference, here's my updated amplify.yml:
```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - yum install dotnet-sdk-3.1
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```

**Comment by CoreyPritchard** [comment]
I'm still having issues. Can anyone help?

**Comment by CoreyPritchard** [comment]
I finally was able to get dotnet installed with the following amplify.yml file. I'm now running into a new issue (#685) that requires a restart. 

```
version: 0.1
backend:
  phases:
    preBuild:
      commands:
        - rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
        - yum install -y dotnet-host-3.1.4
        - yum install -y dotnet-sdk-3.1
        - dotnet tool install -g Amazon.Lambda.Tools
        - dotnet tool install -g Amazon.Lambda.TestTool-3.1
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - dotnet lambda
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```

**Comment by alexkates** [comment]
I know this ticket is closed, but our team ran into this issue yesterday. We weren't big fans of changing the build script to support this, because that would require dotnet core to be installed on every build. We opted to swap in a custom docker build image. I wrote up the steps we performed to handle this here: https://github.com/aws-amplify/amplify-console/issues/685#issuecomment-685684624
