### ISSUE TITLE
SSL verification is Failed - Transfered domain from GoDaddy. Manually added 4 provided ns records and deleted the 2 existing ns records. SSL configuration passed but SSL verification failed. Using Amplify with react. 

### ISSUE THREAD

**Issue by grownanny** [aws-amplify/amplify-console#678]
**App Id**: d3tsifa5c8drqy
**Region**: us-east-1
**Step**: SSL verification
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Joycehao19** [comment]
HI @grownanny , are you able to configure your domain?

**Comment by grownanny** [comment]
Yes I got it working thanks!

**Comment by Joycehao19** [comment]
Great! Closing the issue now. If you face the same issue, feel free to reopen it.
