### ISSUE TITLE
Domain activation is Failed - Unable to set up a custom domain

### ISSUE THREAD

**Issue by neildcruz** [aws-amplify/amplify-console#679]
**App Id**: d21d0l8v98v7tf
**Region**: ap-south-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I'm unable to setup a custom domain using amplify. I was using the same domain on a different amplify project earlier but have deleted the domain from there

**Comment by Joycehao19** [comment]
Hi @neildcruz , it seems like you have already deleted this app. Do you still face this issue?

**Comment by OzzieOrca** [comment]
I might have struggled with the same issue. Does https://github.com/aws-amplify/amplify-console/issues/512#issuecomment-639892355 help?

**Comment by neildcruz** [comment]
Thanks, was able to resolve this.
