### ISSUE TITLE
Domain activation is Failed - Had it hosted manually in cloudfont before

### ISSUE THREAD

**Issue by roopeshrnair** [aws-amplify/amplify-console#681]
**App Id**: d19mtrfujrib0j
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I had my godaddy domain point to route53 and then to cloudfront. Was trying to change it to amplify and got the error

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Athena96** [comment]
Hi @roopeshrnair 
These guides are helpful for common custom domain issue. If those guides can not solve your issues, please let us know.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

And this guide shows how to use your GoDaddy Domain with an amplify app: https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-godaddy.html
