### ISSUE TITLE
SSL verification is Failed - Please re-run

### ISSUE THREAD

**Issue by ejbogantes** [aws-amplify/amplify-console#683]
**App Id**: d2khnx1r1d7mbx
**Region**: us-east-2
**Step**: SSL verification
**Status**: Failed

>**Note**: I already checked on DNS Checker and CNAMEs are working.

**Issue/question**
SSL verification is Failed.

**Error message**
Retry function didn't work, please can you re-run the SSL verification.

**Additional information**
No.

**Comment by Joycehao19** [comment]
Hi @ejbogantes , if you remove the domain and re-add it, would it work?

**Comment by Athena96** [comment]
Closing this issue, please feel free to re-open if you are still facing issues.
