### ISSUE TITLE
[Feedback]Image shows a React App and not an Angular App

### ISSUE THREAD

**Issue by CharlieMcD2** [aws-amplify/amplify-console#687]
**Page**: [`/start/getting-started/data-model/q/integration/angular`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/angular#connect-frontend-to-api)

**Feedback**:

Also after running amplify publish the site shows up with an error that is not seen locally:

![image](https://user-images.githubusercontent.com/45334569/82270917-56b8d100-9944-11ea-8738-5346f2eb8350.png)

**Comment by Athena96** [comment]
Hi @CharlieMcD2 can you try adding the 200 rewrite/redirect rule as described in the issue [here](https://github.com/aws-amplify/amplify-console/issues/489).

Let me know if you have any questions on how to add rewrite/redirect rules. Thanks!

**Comment by CharlieMcD2** [comment]
To be honest, that post is not all that helpful... at least to someone who has never created a redirect rule previously.  I still am getting the same problem after adding a redirect rule similar to the one in the following link: https://github.com/aws-amplify/amplify-js/issues/2498 and after reading a bit on: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html.  I'll keep digging but a good walkthrough on the topic would be helpful.  Also would be great if it just worked out of the box :-)

**Comment by CharlieMcD2** [comment]
My current redirect rule looks as follows: 
![image](https://user-images.githubusercontent.com/45334569/82396045-f779c000-9a1a-11ea-919f-f827e0300546.png)
but this doesn't seem to fix the access denied coming from S3.

**Comment by swaminator** [comment]
@CharlieMcD2 that's probably because your build settings are off. Can you check what your artifacts directory has in your build settings (App settings > build settings)

**Comment by CharlieMcD2** [comment]
Currently my build settings for dev are as follows: 
![image](https://user-images.githubusercontent.com/45334569/82502216-a8886500-9ac4-11ea-93ea-428c93c4e164.png)

**Comment by CharlieMcD2** [comment]
And the errors showing up in the logs are: 
![image](https://user-images.githubusercontent.com/45334569/82502786-ee91f880-9ac5-11ea-93a9-acf582621b12.png)

**Comment by swaminator** [comment]
@CharlieMcD2 those are not your build settings. Your build settings look like: https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html

**Comment by CharlieMcD2** [comment]
Just a reminder, this is an app entirely set up by following this script: https://docs.amplify.aws/start/getting-started/installation/q/integration/angular

So, if the build settings are off, then the script or commands followed did not set up the correct build settings.

I see two files mentioned in the link you provided:  package.json... which I can find, and amplify.yml, which I cannot find... is something missing in the script followed or did I miss a step in the script?

**Comment by CharlieMcD2** [comment]
I've received feedback from the AWS case listed above and AWS Support was able to recreate this issue when following the AWS Amplify CLI instructions listed in the link above.  It does seem to only occur when using Angular.  The fix is still pending... no workable work around yet.  I will post here once the fix is available or if I'm instructed in regard to a work around that alleviates the problem in the short term.

Thanks for your help @swaminator  and @Athena96.

**Comment by ganipcanot** [comment]
Closing due to age - if you are still experiencing issues please feel free to re-open.
