### ISSUE TITLE
Pointing a customer DNS to an Amplify site

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-console#689]
We are using Amplify and hosting subdomains for clients using the Amplify console. Setting up clients using subdomains like myclient.mydomain.com with our domain hosted at Route 53. All working fine.

We have new clients asking to build landing pages which link to our site. So the client would host landingpage.clientdomain.com and wants that to point to their subdomain myclient.mydomain.com on our site. The goal is to integrate our site into their branding as much as possible.

Setting up subdomains in the Amplify console seems to create a Route53 DNS entry that points to a CloudFront distribution but I don't see the a CloudFront distribution listed as one of our a CloudFront distributions.

So I have 2 questions:

1) What occurs re: DNS and CloudFront when you create a subdomain and point it to a git branch in your repository?

2) What is the best way to have an external client point to our Amplify site? We'll have to give them steps to point their DNS to our site.

Thanks.

**Comment by swaminator** [comment]
@blairtaylor 
1. Please refer to https://docs.aws.amazon.com/amplify/latest/userguide/understanding-dns-terminology-and-concepts.html
2. It depends where they are hosting their site. They would have to set up a redirect or rewrite to the amplify URL
