### ISSUE TITLE
Inconsistent behaviour between web ui and CFN / Missing CFN feature to modify build settings

### ISSUE THREAD

**Issue by jwoehrle** [aws-amplify/amplify-console#691]
I'm using amplify console to deploy an amplify backend.

When creating the Amplify app from the webui it automatically sets the amplify cli version to LATEST via the "Build image settings":

![image](https://user-images.githubusercontent.com/14852794/82450788-73244d00-9aad-11ea-8764-e22a2393f913.png)

When using cloudformation to create the app there seems to be no way of influencing the amplify version or specifying the "Live package updates".
This will lead to amplify-cli version 1.12.0 in the build container and a failing deployment with:

> CREATE_FAILED               UpdateRolesWithIDPFunction        AWS::Lambda::Function     The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 80209bdc-d0e8-4412-a3e3-add6d2c21781)

Desired behaviour:
- allow modification of build image settings via CFN
or
- set LATEST also for CFN deployment

**Comment by jwoehrle** [comment]
I've found a workaround. It seems that the Build Image Settings itself are nothing but env variables.

Setting:
`_LIVE_UPDATES='[{"pkg":"@aws-amplify/cli","type":"npm","version":"latest"}]'`

adds the setting from cloudformation

**Comment by swaminator** [comment]
@jwoehrle that is correct. Glad you were able to figure it out.
