### ISSUE TITLE
CNAME provided is already associated with a different resource

### ISSUE THREAD

**Issue by badrhombus** [aws-amplify/amplify-console#692]
**App Id**: d2lwend04neamk
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**:  Prior App Id is d1al6j15fy5a30

**Issue/question**
logs indicate that cloudfront.net references still **d1al6j15fy5a30** even though the CNAME record references app **d2lwend04neamk.cloudfront.net**

How do I get cloudfront to stop using d1al6j15fy5a30 and start using **d2lwend04neamk**?

**Comment by badrhombus** [comment]
What do I need to do to get someone to move the CloudFront distribution from where bad **d1al6j15fy5a30** to use the new **d2lwend04neamk**? I see no options on the aws site to do so without a service agreement.

**Comment by Joycehao19** [comment]
Hey @badrhombus , it looks like your app d10x66ku5711ka in Ohio(us-east-2) used this domain. You could remove it from d10x66ku5711ka and re-connect to app d2lwend04neamk.

**Comment by badrhombus** [comment]
Thanks Joyce - This is indeed what I would like to do, but my concern is that if I delete the app in us-east-2 will it remove it sufficiently so that I can connect in us-east-1?

**Comment by Athena96** [comment]
Hi @badrhombus are you still facing this issue?

**Comment by badrhombus** [comment]
I've been reluctant to move it after I got it working. I'll give it a try and disassociate the domain, delete and see how it goes. probably later today.
