### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH with Third-Party Subdomain

### ISSUE THREAD

**Issue by simpson** [aws-amplify/amplify-console#694]
App ARN: arn:aws:amplify:ap-southeast-1:252100588959:apps/d2xks58rvcvn6p
Region: Southeast 1
Step: DNS is configured through Cloudflare
Status: Unable to reach Amplify

** Please describe which feature you have a question about? **
We're building an app with Amplify, we've connected the domain and the DNS appears to be all correct, but we are getting ERR_SSL_VERSION_OR_CIPHER_MISMATCH and I have no idea why or how to fix it. I'd appreciate any insight you'd be willing to give. We are using Cloudflare, and I'm not sure if that's part of the problem.

** Provide additional details**
The domain we have mapped to Amplify is admin.designed.org

In Cloudflare Business we are using their proxy to protect our apps

RE: https://github.com/aws-amplify/amplify-console/issues/156

**Comment by Athena96** [comment]
Hi @simpson was your domain linked to an SSL certificate from a 3rd party before you tried registering it with your Amplify App?

**Comment by simpson** [comment]
@Athena96 @donkahn Here is the Cloudflare solution but it should be similar to other places! 

I'll try to be descriptive for the others with this problem. The problem is that Amplify prefixes the records with WWW, but it doesn't tell you that in the DNS settings (you should clarify that probably). So if you view the image, you need to add two additional CNAME records in Cloudflare with the www. prefix. After you do that, the Universal and Dedicated SSL options won't work. You need to purchase a Dedicated Certificate with 50 Hostnames ($10/month). When you do that you have to add ALL of the CNAMES at this step (or you have to delete and start over. After that, the acceleration proxy can be turned back on and everything should work fine. Hope this help someone else!

<img width="1289" alt="Screenshot 2020-05-21 19 01 04" src="https://user-images.githubusercontent.com/1605737/82614371-b1953700-9b95-11ea-9760-20554553a38f.png">

**Comment by kahdojay** [comment]
Thanks for sharing @simpson!
