### ISSUE TITLE
.cc domain reported as Invalid or Unavailable

### ISSUE THREAD

**Issue by danielz02** [aws-amplify/amplify-console#695]
**App Id**: arn:aws:amplify:us-east-1:561184600871:apps/d3kk5m7ah579by
**Region**: us-east-1
**Step**: Add domain
**Status**: The domain you entered is invalid or unavailable
**Note**: I'm using AWS Educate account

**Issue/question**
In the domain management panel, I tried to add my custom domain (icso.cc). However, after clicking on "Configure domain," I got an error message saying "The domain you entered is invalid or unavailable." This domain is using third-party DNS provider. I tried to move it to Route 53 but it's still not working. Thanks in advance!

**Error message**
The domain you entered is invalid or unavailable

**Comment by Athena96** [comment]
Hi @danielz02 
this [guide](https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-a-third-party-dns-provider.html) is helpful for adding custom domain from a third party. If the guide doesn't not solve your issues, please let us know. Thanks

**Comment by danielz02** [comment]
> Hi @danielz02 
> this [guide](https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-a-third-party-dns-provider.html) is helpful for adding custom domain from a third party. If the guide doesn't not solve your issues, please let us know. Thanks

Thanks! I have seen this guide but I got stuck at the the first step.

**Comment by danielz02** [comment]
I figured it out. It looks like that I can't add any custom domain with AWS Educate account. I switched to a normal account and it worked!
