### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by procket-live** [aws-amplify/amplify-console#697]
**App Id**: d2jpr8z2bbseai
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Joycehao19** [comment]
Hi @procket-live , do you still face the same issue?

**Comment by OzzieOrca** [comment]
I might have struggled with the same issue. Does https://github.com/aws-amplify/amplify-console/issues/512#issuecomment-639892355 help?

**Comment by Athena96** [comment]
Closing this issue, please feel free to re-open if you are still facing issues.
