### ISSUE TITLE
Deployment blocked

### ISSUE THREAD

**Issue by gsohn** [aws-amplify/amplify-console#698]
I'm using manual deployment, with a zip file on a S3 bucket. The deployment never ends and stay in status "deploying", blocked at 70%.

Could you tell me how to unblock my builds ? Thanks for your help

Here is my amplify id : d3ec14hvw65uy0.amplifyapp.com/

**Comment by Athena96** [comment]
Hi @gsohn sorry you're having trouble. Can you please share the aws region your app is built in?

**Comment by gsohn** [comment]
Hi @Athena96 , the application is build in eu-west-1 (Ireland). The build for the staging environment still appears in error.
