### ISSUE TITLE
Using redirects for multilingual SPA application

### ISSUE THREAD

**Issue by InternalVoiceKOT** [aws-amplify/amplify-console#700]
I'm interested in how to compose redirect rule for multilingual SPA application. I have english version which URLs begin with"/en/" and icelandic version which URLs begin with "/is/". English version is default, so root "/" should be redirected to "/en" only if requested URL doesn't start with one of predefined prefixes of other language versions.

**Comment by swaminator** [comment]
@InternalVoiceKOT please refer to: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#region-based-redirects
