### ISSUE TITLE
Move the "Redploy this version" so you don't accidently press it

### ISSUE THREAD

**Issue by cjsedwards** [aws-amplify/amplify-console#701]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/6901289/82714590-9802f680-9c4c-11ea-9f36-2d661a78b1dc.png)

![image](https://user-images.githubusercontent.com/6901289/82714544-68ec8500-9c4c-11ea-8215-162f7439bcec.png)
See the two screen grabs above, if you're scrolling through builds (clicking the right arrow frequently), you can accidently click "redeploy this version" because the buttons move around

**Describe the solution you'd like**
The "Next build" arrow button shouldn't move, and if it does, the "Redeploy this version" button should definitely not be where it used to be

**Comment by kahdojay** [comment]
Thanks for your feedback!

**Comment by cslogan-red** [comment]
Update will be GA by EOW, closing.
