### ISSUE TITLE
Unable to route client domain to Amplify application

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-console#705]
A client wishes to have our application appear as one of their subdomains.

We asked the client to add the following CNAME to their DNS settings:

CNAME 
Name=clientsubdomain
Host=oursubdomain 

oursubdomain = client.ourdomain.com - this subdomain is set up and working via the Amplify console.

When a client navigates to to the CNAME, they get the following Cloudfront error

403 ERROR
The request could not be satisfied.

Bad request. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

How should this be configured and/or debugged?

**Comment by blairtaylor** [comment]
We've also tried pointing the CNAME record directly to the cloudfront distribution. The results in a "page can’t be found" error.

**Comment by ferdingler** [comment]
hi, for future reference, you need to add your client's domain to Amplify as a custom domain in order for it to resolve properly.
