### ISSUE TITLE
Blocked in deploy status

### ISSUE THREAD

**Issue by gsohn** [aws-amplify/amplify-console#706]
My staging app is blocked with deploy status. Looks like deploy never ends. Could you help me ? Thanks

Here's my domain :
https://www.alacaza.dev

**Comment by swaminator** [comment]
@gsohn what's your appid? Also what error are you getting in deploy?

**Comment by gsohn** [comment]
My gatsby client generates 10K pages. It seems this is too much for the deployment process as it takes more than two hours to copy all files. So I deleted my amplify applications. Do you have any coming action to improve deploy process ? 

Thanks for your help

**Comment by kahdojay** [comment]
@gsohn in general yes but it's difficult to speculate what issue you're hitting without more data, if you can provide us with an example app id / region / build number and any error messages you're seeing we can better understand what's happening with your particular deploys.

**Comment by gsohn** [comment]
I don't have any log as I deleted the applications, sorry. But this happened during the deploy phase, when copying files, and generally around 25K copy. But you can close the issue as I don't use amplify any more. Thanks

**Comment by Athena96** [comment]
Closing this issue, please feel free to re-open if you are still facing issues.
