### ISSUE TITLE
SSL verification is Running - seems blocked since saturday

### ISSUE THREAD

**Issue by nordinh** [aws-amplify/amplify-console#707]
**App Id**: d1p0brm2y6prq5
**Region**: eu-west-1
**Step**: SSL verification
**Status**: Running

**Issue/question**
We registered a custom domain and applied the DNS records this saturday. However, the process seems stuck in the step "SSL Verification", message says: "We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue in our GitHub issue tracker." Could you look into it, previous times this process ran smoothless, so we guess something went wrong.

**Comment by Joycehao19** [comment]
Hi @nordinh , if you remove the domain and re-connect it, would it work?

**Comment by Athena96** [comment]
Closing this issue, please feel free to re-open if you are still facing issues.
