### ISSUE TITLE
Conflict between Angular 7 Routing and Rewrites and Redirects

### ISSUE THREAD

**Issue by pokehouse** [aws-amplify/amplify-console#708]
Hello, I have some angular 7 sites deployed with drag and drop on Amplify. I need to apply a rule in rewrites and redirects to avoid 403 errors when use Angular Routing from address bar (or with F5).
I have applyied this one:

```
{
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|woff2|ttf|map|jons)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    } 
```
But, sometimes, after a new deploy, the site won't load and this error appears:
`Uncaught SyntaxError: Unexpected token '<'  `
This error persists for some time and it occurs randomly. Sometimes, after some time, it seems to solve itself, in other cases, not.
The same code deployed on a new instance works flawlessly.
What's the problem? My application is a standard Angular 7 one.

**Comment by Joycehao19** [comment]
Hi @pokehouse , what is your build setting? It was not a common issue. Could you please try this link https://stackoverflow.com/questions/45222464/syntax-error-in-angular-app-unexpected-token

**Comment by litwicki** [comment]
Please reopen this issue if there is anything we can help with.
