### ISSUE TITLE
Redirection failing

### ISSUE THREAD

**Issue by rortuno-cbba** [aws-amplify/amplify-console#709]
**App Id**: d35aybm0j2pzux
**Region**: us-east-1
**Step**:  
**Status**: Available 

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
The configuration has been completed in both Amplify and 3rd party dns service but the redirection is not getting complete, the domain is being wrongly forwarded.
As you can see in the screen shot, there are no errors but would like to know if we are missing something. The configuration in the 3rd party domain is reported to be completed.

<img width="1101" alt="Screen Shot 2020-05-27 at 10 57 47 AM" src="https://user-images.githubusercontent.com/62607240/83037491-d6f8c980-a009-11ea-80df-b0e4732bee89.png">

**Comment by Joycehao19** [comment]
@rortuno-cbba  would you mind share your rewrites-redirects setting?

**Comment by rortuno-cbba** [comment]
<img width="1338" alt="Screen Shot 2020-06-02 at 11 03 26 AM" src="https://user-images.githubusercontent.com/62607240/83536049-beccf280-a4c0-11ea-865b-37e6c1eb54f7.png">
Please see attached.

**Comment by Joycehao19** [comment]
@rortuno-cbba could you please remove the https://atoxxxx.atoxxx.com/ redirect rule? and test if your subdomain work?
