### ISSUE TITLE
SSL verification is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Issac909** [aws-amplify/amplify-console#710]
**App Id**: d1od682vv5d96v
**Region**: us-east-1
**Step**: SSL verification
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Joycehao19** [comment]
Hi @Issac909 , what issue did you have?

**Comment by Issac909** [comment]
None anymore. I was making the mistake if looking for a repo on the wrong
server

**Comment by Joycehao19** [comment]
Glad you solve the issue. Closing the issue now, if you have same issues, feel free to reopen it!
