### ISSUE TITLE
How do I modify the Auth in an environment variable

### ISSUE THREAD

**Issue by Jn-x** [aws-amplify/amplify-console#714]
** Please describe which feature you have a question about? **
I want to modify the user pool in Amplify, but I don't know how. How can I replace the current user pool with an existing one

** Provide additional details**

**Comment by Joycehao19** [comment]
Hi @Jn-x , you could edit your backend via Amplify CLI, push the change, and rebuild your app in Amplify Console. Amplify Console doesn't support modifying Auth info via environment variable.

**Comment by Jn-x** [comment]
> @ Jn-x，您好，您可以通过Amplify CLI编辑后端，推送更改，然后在Amplify Console中重建您的应用程序。Amplify Console不支持通过环境变量修改Auth信息。

Hi, I did want to edit my application in Amplify CLI, but when I tried to use the 'Amplify update auth' command, it didn't work as I expected

What I want to say is that I already have two user pools on AWS. Can the 'amplify update auth' command allow me to replace one with the other?

**Comment by Joycehao19** [comment]
Hi @Jn-x , are you looking for switching/deleting environments via Amplify CLI?  Could you please take a look of this link: https://read.acloud.guru/multiple-serverless-environments-with-aws-amplify-344759e1be08 ?
