### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by hbnker31** [aws-amplify/amplify-console#716]
**Region**: ap-south-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company, etc.

**Issue/question**
I already had a custom domain linked to different repository, then deleted that custom domain and added it to a different repository but it failed at domain activation.

**Error message**
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by kahdojay** [comment]
@hbnker31 That error indicates that you still have DNS record(s) that are pointing to the old amplify app / cloudfront distribution and it needs to be updated to point to the new. If you've already confirmed this please share your appid and region.

**Comment by Joycehao19** [comment]
Do you still have this issue?

**Comment by OzzieOrca** [comment]
I might have struggled with the same issue. Does https://github.com/aws-amplify/amplify-console/issues/512#issuecomment-639892355 help?

**Comment by Athena96** [comment]
Closing this issue, please feel free to re-open if you are still facing issues.
