### ISSUE TITLE
Domain activation is Failed - One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by grajarv7464** [aws-amplify/amplify-console#718]
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
We are trying to add a domain to a new app in Amplify.
The SAME domain was previously used in a different app in the same Amplify account.
It will not allow us to add the domain again to point to the new app.
I have removed the domain from the account and now it will not allow us to readd.

**Error message**
Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by kahdojay** [comment]
@grajarv7464 to help us troubleshoot, how long did you wait between removal and readding? 

If it is an option and won't cause disruption for you, can you delete the custom domain in Amplify Console, delete the DNS records, and recreate after waiting 1.5h?
