### ISSUE TITLE
SSL verification is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by dahersoftware** [aws-amplify/amplify-console#72]
**App Id**: d2x22b9lss1rld
**Region**: eu-west-1
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**

It has been more then 12 hours and my domain is not active. Please help.

**Comment by dahersoftware** [comment]
It has been 2 days and no help regarding this issue. @swaminator would you please look into this as it is a high priority for me.

**Comment by dahersoftware** [comment]
@nimacks I followed the link and after deleting my domain in console app I added again. It has been more then 12 hours again after re-adding and it is still pending in verification state.
Dig and cname works fine for my domain. 

dig www.testdaher.com

; <<>> DiG 9.10.6 <<>> www.testdaher.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23561
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.testdaher.com.		IN	A

;; ANSWER SECTION:
www.testdaher.com.	3599	IN	A	217.160.0.205

;; Query time: 88 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Aug 27 21:13:08 CEST 2019
;; MSG SIZE  rcvd: 62

**Comment by dahersoftware** [comment]
@nimacks  Correct me if I am wrong. I am using route53 DNS service and I can see the CNAME record in hosted zones and I checked before my previous reply that CNAME resolution was working. But after checking it today it's not working.
I can see an entry like this in hosted zones of route53


www.testdaher.com.            | CNAME | someid.cloudfront.net          --   --   500

**Comment by dahersoftware** [comment]
@nimacks can we get on a call as this simple issue seems to delaying my deployment a lot. :(

**Comment by dahersoftware** [comment]
@nimacks but would you please try to look why it is still stuck? Would u be able to check DNS hosted zone file as i am using route53. It is kind of black box and I am feeling helpless because i can only see that I have create hosted zone entry and it has all the right records.

**Comment by dahersoftware** [comment]
@nimacks  I bought domain from third party and then used amazon route53 DNS service, I created a hosted zones and it created all the records necessary. Then i configured nameservers mentioned in NS record of hosted zones to my domain for lookup. Ping works fine and i checked 2 days ago cname was fine too.

**Comment by dahersoftware** [comment]
@nimacks I have sent an email also @aws-amplify-customer@amazon.com so please have a look.

**Comment by dahersoftware** [comment]
@nimacks  Thank you nimacks for joining the call yesterday. You were right it was a problem with my domain registration side. SSL verification is done and my domain is active now.

I am closing the issue.

**Comment by despau** [comment]
Hi, I have read all the comments and I am having the exact same issue because I did not purchase my domain from Amazon.
Anyway you could share your solution, please. I have been struggling with this for over a week now.
Thank you !

**Comment by dahersoftware** [comment]
@despau In my case error was that nameservers given by Amazon(NS records) was not configured properly into my third party domain for lookup.
