### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by haohao1331** [aws-amplify/amplify-console#723]
**App Id**: d8uyhyzk7k7q4
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I previously successfully configured my custom domain name to an amplify website. I deleted the website and wanted to use my domain name for another website. 

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Tried various trouble shooting messages in the AWS doc, waiting 6 hours but still no luck.

**Comment by Joycehao19** [comment]
Hi @haohao1331 , do you know the previous appId which you configured custom domain before?

**Comment by haohao1331** [comment]
> Hi @haohao1331 , do you know the previous appId which you configured custom domain before?

Sorry I didn't record that, is it possible to provide you the domain name and then somehow unhook all the CNAMES? Thanks!

**Comment by Joycehao19** [comment]
Hi @haohao1331 , could you please send an email to aws-amplify-customer@amazon.com <aws-amplify-customer@amazon.com> , include the link of the issue(https://github.com/aws-amplify/amplify-console/issues/723)? We will help you from there!

**Comment by Joycehao19** [comment]
Hi @haohao1331 , we just disassociated your domain. It would take some time to be updated. If you still face the issue after 6 hours, please let us know!

**Comment by Joycehao19** [comment]
Hi @haohao1331 , You domain should be able to associate with you current distribution now. Closing the ticket, if you face the same issue, please feel free to reopen the ticket.
