### ISSUE TITLE
There was an issue connecting to your repository provider (GitHub)

### ISSUE THREAD

**Issue by glenkitchen** [aws-amplify/amplify-console#724]
**Amplify console Url**
https://eu-west-1.console.aws.amazon.com/amplify/home?region=eu-west-1&code=6c9972795c4e3cd07d24#/

**Issue**
Unable to Connect to GitHub when trying to Add Repository. 
GitHub authorization is successful but then there is an *issue connecting* error message
Tried to refresh by clicking refresh button. 
Tried to reauthorize by revoking AWS Amplify as an Authorized OAuth App, on my GitHub profile,  but the issue persists.      

**Error Message**
![image](https://user-images.githubusercontent.com/9795765/83377189-20b02e00-a3d5-11ea-82fa-642ae8a0e104.png)

**Comment by kahdojay** [comment]
@glenkitchen can you share your appId? Did you wait an hour between retries?

**Comment by glenkitchen** [comment]
@kahdojay Apologies. I was trying to connect a repository provider without an app in the console.  Resolved.
