### ISSUE TITLE
Bug: 404 Rewrite Rule is Broken!

### ISSUE THREAD

**Issue by nagey** [aws-amplify/amplify-console#725]
This is something that actually seems to have cropped up recently, perhaps in how cloudfront works underneath, or perhaps related to the issue(s) with CF edge caching that seem to have recently been resolved.

The amplify [docs](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html) suggest that if you want to use a custom 404 rule, you should specify one thusly:
```
[{“source”: “/<*>”, “status”: “404”, “target”: “/404.html”, “condition”: null}]
```

If you enter it exactly as written in JSON, works fine.

*However*, if you use the UI in the console, and you think, "well, I don't want to *redirect* to /404.html, that's kinda ghetto. I'd rather **rewrite** instead", then everything breaks.

If you have this rule set as a rewrite rather than a redirect, it will render URLs, such as `/route` as 404. If you have it as the redirect, it will instead render `/route` as a 301 to `/route/` which will then, correctly, render `/route/index.html` as a 200. 

This is exceedingly frustrating, and I think would qualify as a "gotcha" that would merit pointing out in the documentation

**Comment by Joycehao19** [comment]
Hi @nagey , If you have /route/index.html , when you open /route, you should see /route/index.html as a 200. (https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#trailing-slashes-and-clean-urls) 

I tried to add `[{“source”: “/<*>”, “status”: “404”, “target”: “/404.html”, “condition”: null}]`, my browser still get /route/index.html as 200. 
Would you mind send me your appId and the branch name which 404-redirect could work?

**Comment by nagey** [comment]
> Hi @nagey , If you have /route/index.html , when you open /route, you should see /route/index.html as a 200. (https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#trailing-slashes-and-clean-urls) 
> 
> 
> 
> I tried to add `[{“source”: “/<*>”, “status”: “404”, “target”: “/404.html”, “condition”: null}]`, my browser still get /route/index.html as 200. 
> 
> Would you mind send me your appId and the branch name which 404-redirect could work?

If you go directly to the index, yes, it does 200. 

Try going just to /route though 

If the rule is status 404, it works. If it is status 404-200 (a rewrite) then it will give a 404 on /route, even though it will continue to work as expected on /route/ and on /route/index.html

**Comment by Joycehao19** [comment]
I tried both 400 and 400-200. Open myamplifyapp.com/route , they all go to myamplifyapp.com/route/index.html

Would you mind send me your appId and branch? I'd like to take look of the logs

**Comment by nagey** [comment]
App Id is d2asg66bjv0dls, branch is master

if it's possible, I want to get my 404s going to /404.html

**Comment by nagey** [comment]
(accidentally hit "close and comment" rather than comment)

**Comment by nagey** [comment]
(accidentally hit "close and comment" rather than comment)

**Comment by Joycehao19** [comment]
Hi @nagey , I can reproduce this issue. Thank you for reporting. I cut a ticket in our team backlog. We will investigate on the issue.

**Comment by swaminator** [comment]
@nagey this has been resolved.
