### ISSUE TITLE
Domain activation is Failed 

### ISSUE THREAD

**Issue by jpdentone** [aws-amplify/amplify-console#728]
App Id: d29m6go6qnx3lk
Region: us-east-1
Step: Domain activation
Status: Failed

Issue/question
Cant activate the domain

Error message
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

Additional information
I need the application in a subdomain -- subdomain.domain.me -- I setup to exclude the root domain and added the subdomain I need. there is a A record in the root domain (domain.me) which points to a cloudfront distribution.

**Comment by jpdentone** [comment]
I did a bunch of stuff and after delete the domain and re-added it is working... I noticed there was a cloudfront distribution that was using the same CNAME i needed, could that be the issue? (i deleted the distribution)

**Comment by Joycehao19** [comment]
That should be the reason. @jpdentone
