### ISSUE TITLE
Tagging resources used by Amplify

### ISSUE THREAD

**Issue by hrkhal** [aws-amplify/amplify-console#73]
We have a project set up in the Amplify console. How can we tag all of the resources used by Amplify to build and serve our web app so that we can monitor costs accordingly.

**Comment by swaminator** [comment]
We don't have a tagging view in our Console. You can use the AWS CLI to tag resources for Amplify Console: https://docs.aws.amazon.com/cli/latest/reference/amplify/tag-resource.html

**Comment by mooniker** [comment]
@swaminator @dabit3 It would be great if we could programmatically assign tags with resource creation.
