### ISSUE TITLE
Domain activation failed - custom domain with valid CNAME record 

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-console#732]
**App Id**: d2ctnb7fwe3m0u
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

We've followed the steps to as per documentation to set up a custom domain.
The client is using Route53 and has configured the correct DNS CNAME record.

Using whatsmydns we have confirmed the DNS record as per directions
https://www.whatsmydns.net/#CNAME/_56302cf9c095ed1be302ccff8df3f8ef.aquamobileswim.com

Yet the Domain activation fails.

**Comment by blairtaylor** [comment]
Hi. Could someone advise? I don't see the CloudFront distribution in our account. Is there any way to see the CloudFront distribution generated by Amplify to try to diagnose? We've spent 3 days working on this with the client and they are ready to give up on us. We previously set this up for a different client and it worked without issue.

**Comment by Joycehao19** [comment]
Hi @blairtaylor , Could you please remove and re-add the domain.  It seems like "aqxxxxxxxxswim.com" doesn't associate with any distribution. If you still face this issue, please let us know

**Comment by blairtaylor** [comment]
Deleted and re-created the custom domain. I receive the same error.

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem.

**Comment by Joycehao19** [comment]
@blairtaylor It seems like your custom domain already has a DNS record which point to another one CloudFront distribution. (ref: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions)

Can you delete the DNS records, and if it won't cause disruption, delete and recreate the custom domain?

**Comment by blairtaylor** [comment]
Thanks @Joycehao19 . The client has sent me a dump of their DNS config which is in Route53. I only see one CNAME pointing to a CloudFront distribution. I do see a number of "acm-validations" records as we tried this setup several times without success. I can send the dump privately if that helps.

**Comment by Joycehao19** [comment]
@blairtaylor when you add domain in `Domain management`, in SSL configuration stage, click `Action` -> `view DNS records` , in `3. Configure DNS provider`, there should have a line looks like `    www    CNAME    d1234567abcd.cloudfront.net`. Can you make sure if this line matches the client's record?

**Comment by blairtaylor** [comment]
@Joycehao19 We deleted and re-created the custom domain and it is working now.
