### ISSUE TITLE
"The domain you entered is invalid or unavailable" while adding custom domain 

### ISSUE THREAD

**Issue by HeinMynn** [aws-amplify/amplify-console#733]
**App Id**:arn:aws:amplify:ap-southeast-1:922599857802:apps/d10enxu4hxhc65
**Region**:ap-southease-1
**Step**: adding custom domain
**Status**: showing error 'The domain you entered is invalid or unavailable'

**Issue/question**
I deployed Gatsby app in amplify from Github Repo. It can successfully deploy and build. Then from Domain Management, I tried to add my domain (DNS managed by Cloudflare) and press configure button. Then, it keep showing the following error.

**Error message**
'The domain you entered is invalid or unavailable'

**Additional information**
I'm sure that the domain is already existed and currently running. I just want to run with subdomain.

**Comment by Joycehao19** [comment]
Hi @HeinMynn , could you please try following links? if you still have this issue, please let us know. 
https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-a-third-party-dns-provider.html
https://github.com/aws-amplify/amplify-console/issues/579
https://github.com/aws-amplify/amplify-console/issues/695

**Comment by HeinMynn** [comment]
Hi @Joycehao19 , I already tried. I got error in step 5 while I press 'configure domain' button.

**Comment by Joycehao19** [comment]
@HeinMynn Could you please share your domain with us? 
For example, if the domain is awesomedomain.com.au, you could write abcdefghijklm.com.au

**Comment by HeinMynn** [comment]
My domain is abcdef-ghijk.com

**Comment by dannypk** [comment]
Why is this closed? What was the solution? I still get that error for any kind of domain I am typing it - literally everything I put. 
On the dropdown list I get my hosted zones from route53 and when I choose them, i get the same error.

What was the solution of this?
