### ISSUE TITLE
Domain activation is Failed –  One or more of the CNAMEs already associated

### ISSUE THREAD

**Issue by Purii** [aws-amplify/amplify-console#734]
**App Id**: d23ultcrzc1rvs
**Region**: eu-central-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I want to migrate two subdomains (www. + preview.) to amplify. After adding preview. I wanted to add www. as separate Custom Domain. Amplify complained, that the domain is already used, so I deleted preview.
-> After waiting ~1.5h I tried to add www. + preview. together. But I got the same error.

Another subdomain of same TLD (api.) is already connected to CloudFront.

**Error message**

`Error message: One or more of the CNAMEs you provided are already associated with a different resource.`

**Comment by Joycehao19** [comment]
Hello @Purii , it would take some time to remove the previous settings. Could you please try after 6 hours. If you are still not able to connect your domain, please let us know.

**Comment by Purii** [comment]
Hello @Joycehao19 ! Thanks, it worked 👍
