### ISSUE TITLE
Domain activation is Failed - Activation Failed

### ISSUE THREAD

**Issue by jibudeh01** [aws-amplify/amplify-console#738]
**App Id**: dknz6km7cnvos
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
I've deleted all CNAME records on Route 53 for my domain. Should CloudFront distribution go down too?

**Comment by Joycehao19** [comment]
Hi @jibudeh01 Your domain was still associated with other CloudFront distribution. It seems like you could go to CloudFront and disassociate it. The accountid is 992xxxxxxxx9. 

For you question, I'm not sure if removing CNAME records on Rounte53 would disassociate the domain. You might find answer in https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/Welcome.html.

**Comment by OzzieOrca** [comment]
I might have struggled with the same issue. Removing it from the Alternate Domain Names
(CNAMEs) field in Cloudfront seems to be the solution. https://github.com/aws-amplify/amplify-console/issues/512#issuecomment-639892355
