### ISSUE TITLE
Cache persists after new manual deploy

### ISSUE THREAD

**Issue by TechpriestV** [aws-amplify/amplify-console#74]
**Describe the bug**
After doing a manual deploy the old code remains up -> cash is not invalidated.

**To Reproduce**
Manually upload files
Manually upload new versions of those files

**Expected behavior**
After a manual upload and deploy, chases should be invalidated and your new upload should be useable in a reasonable timeframe. 

**Additional context**
We're using a custom domain

**Sample code**
No code

**Comment by swaminator** [comment]
@TechpriestV can you please share your appid? Found in General > App Settings

**Comment by swaminator** [comment]
@TechpriestV does your app use a service worker? Did you hard refresh your browser?

**Comment by TechpriestV** [comment]
No service workes, hard refresh + different browser.
And I'm guessing this is the appId: d2ltuhmhaxxxpq

**Comment by TechpriestV** [comment]
Ireland

**Comment by nimacks** [comment]
@TechpriestV , we have not been successful in reproducing this issue. Does this happen all the time for you or is this specific to a particular app? Any other information you can provide will be very much appreciated.

**Comment by TechpriestV** [comment]
@nimacks With this specific app, there is not much more information that I can provide. I've verified that the files i'm uploading are the new version but what's served on the app is the old version.

**Comment by nimacks** [comment]
@TechpriestV, thanks for the update. We're continuing to investigate on our end. Would you mind sharing your static files with our team so we can attempt to replicate exactly what you're doing? Another alternative would be to record a screen share video and send it to aws-amplify-customer@amazon.com.

**Comment by simpson** [comment]
I am also in hot water because I can't purge files that users have explicitly requested be removed from our platform, we have deleted them in the build but the cache still exists. Is there any short term workaround for this while we find a better solution?
