### ISSUE TITLE
Custom domain error caused production outage time

### ISSUE THREAD

**Issue by ambriglia** [aws-amplify/amplify-console#745]
Hello,

We had a production outage today for our amplify application and we are trying to determine the root cause. For some reason, we had a custom domain suddenly start throwing 404 errors. Around the outage time, there were some changes with other custom domains and some unrelated redirects/rewrites, but none of those changes should have affected the specific custom domain that went down. To us, it looked like the DNS was still resolving. We ran some dig/curl commands to confirm this. We did notice, when we went to the URL in the browser and looked in the network tab, Cloudfront was returning a 404.

We have AWS tech support chat that we can share, and we have some records in CloudTrail that show the unrelated changes we were doing around outage time.

The way we were able to resolve the issue was to delete the custom domain and recreate it.

Essentially, we want to know what happened so we don't run into this issue again. AWS tech support suggested we create an issue here to determine the root cause. Currently, we are apprehensive to make any custom domain or rewrites/redirect changes until we know exactly what happened.

Please let us know if you need any other info.

Thanks.
-Anthony

**Comment by swaminator** [comment]
@ambriglia this is really hard for us to diagnose without more specifics. It appears from your comment that somehow the Route53 records got changed.

**Comment by ambriglia** [comment]
@swaminator I agree this is very hard to diagnose here as well. I was told to come here and open a ticket by AWS premium tech support. I have a whole bunch of other great information to share but most of it is sensitive that I do not feel comfortable sharing publicly. I asked the tech support if I could request a conversation with someone from the Amplify Console team but they told me that is not possible. They also did mention that they had an internal AWS ticket on your end that links this github issue with my internal AWS support case, which has more information. Let me know what we can do next. It is really important for us to determine the root cause here.

**Comment by ambriglia** [comment]
@swaminator To add more context, a coworker and myself, combed through the Cloudtrail logs on the day of the outage and did not find any changes to the Route53 DNS records at that time.

**Comment by Athena96** [comment]
Hi @ambriglia yes we do have an internal ticket for your issue and are investigating, thank you!

**Comment by ambriglia** [comment]
@Athena96 Any update?

**Comment by swaminator** [comment]
Closing this ticket as you are corresponding internally.
