### ISSUE TITLE
[request] auto select item if dropdown only has one item

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-console#746]
**Is your feature request related to a problem? Please describe.**

This happens a lot:

![image](https://user-images.githubusercontent.com/6764957/84190461-900ad980-aac9-11ea-9c78-dcfd6b8b0cb6.png)

![image](https://user-images.githubusercontent.com/6764957/84190482-9600ba80-aac9-11ea-8eae-7ce1d9e32221.png)

**Describe the solution you'd like**

we can make the Amplify Console experience a little more delightful by autofilling items that obviously only have one possible answer.

**Comment by ganipcanot** [comment]
Thanks for the suggestion - I've added a task in our backlog.

**Comment by Athena96** [comment]
Closing this as we have implemented this with the two use cases you mentioned. Please feel free to re-open if you have any other related issues.

**Comment by sw-yx** [comment]
thanks Jared!
