### ISSUE TITLE
Why does Amplify create a read/write deploy key in the github repo instead of just read-only deploy key ?

### ISSUE THREAD

**Issue by shrirupa** [aws-amplify/amplify-console#747]
I am trying to deploy our organizations public github repo using Amplify, but this was flagged as security concern as Amplify creates a SSH deploy key in repository which is read/write. Why does Amplify need a read/write deploy key ? I have been going over the documentation of Amplify and specifically says here(https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-app.html) that it will create a read-only key.

**Comment by shrirupa** [comment]
Any updates on the above issue ?

**Comment by shrirupa** [comment]
@swaminator @Joycehao19 Can anyone please look into this ? Thanks in advance.

**Comment by behrooziAWS** [comment]
Keys created after 6/24/2020 are correctly configured as read_only.  To create a new read-only key click **Reconnect Repository** under **App**->**General** and follow the instructions.  Upon completion the read-write key is no longer necessary and may be deleted.

**Comment by gwryssekk** [comment]
Issue resolved as of 6/24.  Please reopen if you are still seeing this behavior.
