### ISSUE TITLE
Domain activation is Failed

### ISSUE THREAD

**Issue by jm345** [aws-amplify/amplify-console#748]
**App Id**: d2hoek8d0rfkss
**Region**: ap-southeast-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Cannot activate domain in amplify. I have added the records generated by amplify to the dns but I am still unable to activate the domain.

**Error message**
One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by OzzieOrca** [comment]
I might have struggled with the same issue. Does https://github.com/aws-amplify/amplify-console/issues/512#issuecomment-639892355 help?

**Comment by jm345** [comment]
Thanks for responding. Ill take a look now.

**Comment by jm345** [comment]
Unfortunately I have never used CloudFront before so I dont have any prior information in there. Perhaps that is part of the problem?

**Comment by jm345** [comment]
@OzzieOrca

**Comment by OzzieOrca** [comment]
Well the error sounds like what I experienced with the domain previously attached to a Cloudfront distribution. Sounds like that's not the case though. Maybe it's used by another Amplify app? Idk how it all works. Hopefully someone from AWS or the docs can help... Sorry you're experiencing this :(

**Comment by ganipcanot** [comment]
Resolving due to age - if you still need help please re-open.
