### ISSUE TITLE
commit ID always refers to HEAD

### ISSUE THREAD

**Issue by gaochenyue** [aws-amplify/amplify-console#751]
When we deploy with AWS cli below, it does use the latest commit, but the commit ID always refers to HEAD while we know that each build uses different commit for sure. So it makes the build history useless. We can't know which commit each build was created from. Also no matter which git branch the build is on, the HEAD link always points to "https://bitbucket.org/project/branch/commits/HEAD", which is the master HEAD by default
aws amplify start-job --app-id <appid> --branch-name <branchname> --job-type RELEASE
![image](https://user-images.githubusercontent.com/9857112/84535526-f6564e80-acb9-11ea-870a-63215a812d4c.png)

**Comment by swaminator** [comment]
@gaochenyue why are you deploying a job via the CLI instead of a code commit?

**Comment by gaochenyue** [comment]
Thanks @swaminator 
Here are two reasons
1. I don't want to deploy on every commit especially for development branch. Build is not cheap. 
2. CLI is an official way to deploy in your documentation

**Comment by swaminator** [comment]
@gaochenyue I understand that but the bug you identified is long way from being prioritized given some of our other focus areas. A workaround to avoid #1: Add `[skip-cd]` to your commit message and this will automatically skip a build: https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#skip-build-for-a-commit

**Comment by gaochenyue** [comment]
Thanks @swaminator
I believe it is a critical bug because it is very important for developers to track which commit is being released.

**Comment by hentschelpatrick** [comment]
What @gaochenyue says, we are having problems with a build and always get the HEAD message, this is not helpful at all
