### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by hussainMansoor876** [aws-amplify/amplify-console#752]
**App Id**: d2f9x3ntwi2kis
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by OzzieOrca** [comment]
You don't have much context here but I might have struggled with the same issue. Does https://github.com/aws-amplify/amplify-console/issues/512#issuecomment-639892355 help?

**Comment by ganipcanot** [comment]
Resolving due to age - re-open if you are still facing the issue!
