### ISSUE TITLE
Image and site metadata assets not loading

### ISSUE THREAD

**Issue by shotesmagotes** [aws-amplify/amplify-console#754]
**App Id**: d1xq0lkga7elzc
**Region**: us-west-2
**Step**: N/A
**Status**: Available

**Issue/question**
I launched a gatsby site with images and queries from the gatsby-config.js. This works from the master branch deployment on the amplifyapp url but not for my custom domain. The assets themselves are not requested - the images do not show up on the network calls.

**Additional information**
    "gatsby": "^2.21.22",
    "gatsby-background-image": "^1.1.1",
    "gatsby-image": "^2.4.3",
    "gatsby-plugin-layout": "^1.3.4",
    "gatsby-plugin-mailchimp": "^5.1.2",
    "gatsby-plugin-material-ui": "^2.1.9",
    "gatsby-plugin-react-helmet": "^3.3.4",
    "gatsby-plugin-sharp": "^2.6.2",
    "gatsby-plugin-typography": "^2.5.1",
    "gatsby-source-filesystem": "^2.3.10",
    "gatsby-source-s3": "0.0.0",
    "gatsby-transformer-remark": "^2.8.14",
    "gatsby-transformer-sharp": "^2.5.2",

deployed amplify via cloudformation using Amplify::App, Amplify::Domain, Amplify::Branch resources.

**Comment by swaminator** [comment]
@shotesmagotes did you set up the proper redirects: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa

**Comment by Athena96** [comment]
Hi @shotesmagotes are you still facing this issue?

**Comment by shotesmagotes** [comment]
No longer facing issues- did nothing to resolve it but the image appeared after 3 days

**Comment by yuxiang-zhang** [comment]
> @shotesmagotes did you set up the proper redirects: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa

I had an issue where the image requests got back with status 200 and 304 but are not showing up. I noticed that the images were loaded in `webp` format; turns out I had to add the extension `webp` in the regex shown on that link, and it fixed it.
