### ISSUE TITLE
SSL verification is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Cosmodon** [aws-amplify/amplify-console#757]
**App Id**: dhkj2p1jb5vit
**Region**: us-east-1
**Step**: SSL verification
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I registered a domain and created a host record.  i keep getting a warning that they cannot verify ownership

**Error message**
Could not verify ownership of the domain. The status of this certificate request is "Failed". One or more domain names have failed DNS validation. Please check your domain name validation routes and try re-adding the custom domain to your app. L
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by ganipcanot** [comment]
Looks like the domain associated with this application is up and running - closing this issue.

**If you are still experiencing issues you can try following these steps:**

- Is this domain connected to a different Amplify App that you own? If so, make sure you are not trying to reuse one of the hostnames.
- If you are using www.domain.com on the other app, you cannot use www.domain.com on this app
- You can use other hostnames, like blog.domain.com
- If you had this domain successfully connected to Amplify and then recently (within the last hour) deleted it, please wait and try again.
- Check the Cloudfront console to see if you have this domain deployed to any distributions
- If you are positive no CloudFront distribution exists (including in other accounts) using this domain, and only if it would not be disruptive to any currently running services, try deleting and recreating the hosted zone
