### ISSUE TITLE
JS files download infinite loop using redirect

### ISSUE THREAD

**Issue by Galaf** [aws-amplify/amplify-console#760]
**Please describe which feature you have a question about?**

Rewrites and redirects

**Provide additional details**

I am using the current redirect:

Source address: ```</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>```
Target address: ```/index.html```
Type: ```200 (Rewrite)```

(No other redirect / rewrite)

Which is what the documentation says about SPA and what I mostly found by Googling it.
Yet for some reason, my .js files get downloaded in an infinite loop until my Chrome tab finally crashes.

My .js files are not in the root directory but in some subfolders if that helps.
My application is coded using angularjs (1.x)

Am I doing something wrong?

Thank you for your time.

**Comment by Galaf** [comment]
Any news?

**Comment by abhi7cr** [comment]
Hi @Galaf, 

Sorry for the delayed response. Could you provide the appid and region?

**Comment by Galaf** [comment]
Hi @abhi7cr 

The appid is `dj86un7jwa3et` and region is `us-east-1`

**Comment by Galaf** [comment]
It is to be noted that the issue happens once you log into the page.
Could you give me a contact address so that I send you credentials for a temporary account?

**Comment by abhi7cr** [comment]
Hi @Galaf you can send an email to aws-amplify-customer@amazon.com, including the link to this issue(#760).

**Comment by Galaf** [comment]
I sent the e-mail with test credentials.

**Comment by abhi7cr** [comment]
Hi @Galaf,

When I checked the SPA redirect rule for your app, it had an additional  **\\** before **.(**. Can you remove that, and try again?

**Current rule:**
`</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>`

**Expected rule:**
`</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>`

**Comment by Galaf** [comment]
I tried changing it, unfortunately, it did nothing.
Files still get downloaded over and over.

**Comment by Galaf** [comment]
I found the problem.
In angularjs, unless you use some tricks, the HTML templates are real HTML files that should be downloaded by the browser.

The redirect rule did not exclude html files so every template would download index.html which would in turn download my JS files again and again.

Here is the redirect rule I'm using now: `</^[^.]+$\|\.(?!(html\|css\|gif\|ico\|jpg\|js\|png\|txt\|svg\|woff\|ttf\|map\|json)$)([^.]+$)/>`

Looks fine, now.
Thanks for the help.
