### ISSUE TITLE
Adding Custom Domain doesnt work with 'www' subdomain

### ISSUE THREAD

**Issue by SamCullin** [aws-amplify/amplify-console#761]
**App Id**:
dn3nn8kj2eagn
**Region**:
ap-southeast-2
**Step**:
Domain activation
**Status**:
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
>**Note**: 
We are adding multiple domains to a single amplify app. We successfully connected 3 out of 6 but had to roll back because the core domain could not complete the process. 

**Issue/question**
The domain always failed when we tried to add the www subdomain. Without the www it would deploy fine. We could add other subdomains routing to the same or different branches. 

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by OzzieOrca** [comment]
I might have struggled with the same issue. Does https://github.com/aws-amplify/amplify-console/issues/512#issuecomment-639892355 help?

**Comment by swaminator** [comment]
@SamCullin please refer to the @OzzieOrca's solution
