### ISSUE TITLE
SSL verification is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by lakshmishettappakantha** [aws-amplify/amplify-console#766]
**App Id**: dt1wemm45dd7m
**Region**: ap-south-1
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
form passed 10 hrs its in ssl verification state
**Error message**
no error message
**Note**: Be sure to check the message for sensitive information. 

**Additional information**

**Comment by MarianGeorgeMorosac** [comment]
Same issue; stuck in SSL Configuration for a second time in 2 days, left it open overnight.
The mentioned CNAMEs are set accordingly.

**Comment by MarianGeorgeMorosac** [comment]
Any news on this?

**Comment by swaminator** [comment]
Could you try deleting and re-adding the domain? This is a time-sensitive action and sometimes if you do not do this immediately it can get stuck in pending verification.

**Comment by sujan-s** [comment]
Same for me.

Tried removing/adding multiple times, but just doesn’t work. Route53 has all the entries, but still stuck on SSL verification.

**Comment by abhi7cr** [comment]
Hi @lakshmishettappakantha, I don't see your app anymore. Did you remove it? 

@MarianGeorgeMorosac and @sujan-s , could you share the appId and region?

**Comment by lakshmishettappakantha** [comment]
Hi @abhi7cr , Yes i removed the app.
Anyway the issue was resolved after updating the DNS record.
Many Thanks

**Comment by sujan-s** [comment]
Ok, I found the issue—there was the mismatch in the `NS` records for the domain in the Hosted Zone, and Registered Domains.

I deleted the Hosted Zone for the domain, and recreated it, and it worked.

**Comment by MarianGeorgeMorosac** [comment]
Same type of mismatch for me too; the domain was transferred from a different account, the the updates had to be manually provided on the original account too.
