### ISSUE TITLE
Lambda Layer displayed ARN version not in sync with selected version

### ISSUE THREAD

**Issue by jhockett** [aws-amplify/amplify-console#768]
The copy ARN button should display the same Lambda Layer version as selected below. This happens with two total Layer versions as well.

![Screen Shot 2020-06-16 at 11 56 26 AM](https://user-images.githubusercontent.com/1815789/84817908-8c47ed00-afca-11ea-8279-877b89f72f27.png)

**Comment by swaminator** [comment]
@jhockett not sure how this is an Amplify Console issue as it appears this is an issue with the Lambda console
