### ISSUE TITLE
Verify Phase Customization

### ISSUE THREAD

**Issue by visusnet** [aws-amplify/amplify-console#77]
**Is your feature request related to a problem? Please describe.**
The verify phase's screenshots are a neat feature but its value is limited for certain types of web apps, e.g. apps that use the authentication features of Amplify or, more generally, apps that are password protected.

**Describe the solution you'd like**
It would be awesome to be able to customize the verification phase. There are a couple of possibilities:
 - Run a script in the browser before taking the screenshots. This could be used to do something like this:
```
document.onload = () => {
    document.getElementById('username').value = 'admin';
    document.getElementById('password').value = 'password';
    document.getElementById('loginForm').submit();
    someGlobalCallback(); // notify Amplify Console that screenshots can be taken
}
```
- Allow the specification of paths where screenshots can be found. This would make it possible to create screenshots during the build phase. Cypress is already supported and it is capable of creating screenshots. If there were a way to configure a path where screenshots should be stores in order to be picked up by Amplify, screenshots of any part of the application would be possible. This solution is not limited to Cypress.
- Integrate AWS Device Farm, i.e. make it possible to run custom test plans.

**Comment by swaminator** [comment]
@visusnet cool usecase! We're going to be adding support for making test artifacts available for download at build time. Would that satisfy your requirement, or would you like to run tests on the deployed site.

**Comment by visusnet** [comment]
@swaminator I don‘t want to run tests on the deployed site, no. We are starting a local web server for that purpose and let cypress do its magic. I am not sure what test artifacts you are referring to. At the moment, the screenshots that we see that were captured during the verification phase, only show a login - the one that is provided by aws-amplify-react. There is no real value for us because the heavy lifting occurs behind the login. Unfortunately, there is no way to safely browse deeper into the application because the verify step is static. We‘d love to be able to check whether our latest changes broke something behind the login. If you could make it possible, it would be very helpful.

**Comment by swaminator** [comment]
I'm saying we will be adding functionality to be able to download test artifacts such as screenshots and videos if you have (for example) Cypress tests running in your repo.

**Comment by visusnet** [comment]
@swaminator That would be great and is similar to this feature request. The difference to a more configurable verification phase is, that cypress tests run in a headless browser instead of multiple different browsers. Your planned feature fulfills many of the use cases. :) I guess, it is still worth exploring the support of a more powerful verify step.

**Comment by swaminator** [comment]
@visusnet we have launched Cypress testing: https://aws.amazon.com/about-aws/whats-new/2019/10/aws-amplify-console-offers-end-to-end-browser-based-testing-with-cypress/

**Comment by visusnet** [comment]
@swaminator Ans we are already using it for some time now. :) Thanks
