### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by aeflorezm** [aws-amplify/amplify-console#770]
**App Id**: d33ix2z64ma54m
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Note**: 

**Issue/question**
I am trying to add a custom domain managed by a third-party DNS provider. I have followed all the steps in the documentation but in the last step (the domain activation) is throwing an error. The thing is that the the third partu DNS provider takes around 2 days in creating the registration in their DNS, and when I retry it is still not successful. Is there anything that I have to do besides that? Should the DNS provider take less time so it can be successful? I would highly appreciate it.

**Error message**
One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Comment by OzzieOrca** [comment]
That error message sounds like you (or someone) had this domain configured with Cloudfront. Does https://github.com/aws-amplify/amplify-console/issues/512#issuecomment-639892355 help?

**Comment by aeflorezm** [comment]
Yes, that was very helpful.  Thank you very much and I do apologize for the long answer. The third party provider took a while and a was not sure. Thanks again for the quick reply!
