### ISSUE TITLE
CSS Styling not applying

### ISSUE THREAD

**Issue by alizain5693** [aws-amplify/amplify-console#775]
I deployed a simple react app to amplify. It works fine locally and deployment works as well, however the CSS styling only applies to some pages of the website and not others. I don't experience this issue in my local environment. Anybody know how I can resolve this?

**Comment by abhi7cr** [comment]
Hi @alizain5693,

Could you provide the appId, and region?

**Comment by Athena96** [comment]
Closing this issue, please feel free to re-open if you are still facing issues.
