### ISSUE TITLE
SSL verification is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by oelegeirnaert** [aws-amplify/amplify-console#776]
**App Id**: d2hyvve40idtc2
**Region**: eu-central-1
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
The process is still running after 8hours.

**Error message**
We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue in our GitHub issue tracker.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by abhi7cr** [comment]
Hi @oelegeirnaert,

By any chance, was the domain transferred to Route53 from elsewhere? If that's the case, you have to make sure to point the NS records in your domain registrar to the ones found in Route53, and try again.

**Comment by Athena96** [comment]
Hi @oelegeirnaert are you still facing this issue?
