### ISSUE TITLE
Domain activation is Failed - Cannot connect subdomain previously connected to CloudFront

### ISSUE THREAD

**Issue by ChrisKno** [aws-amplify/amplify-console#780]
**App Id**: d1p3q0irdty9gr
**Region**: eu-central-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I wanted to connect a subdomain (like app.DOMAIN.com) via Amplify. This subdomain was previously associated with a cloudfront distribution that served an S3 bucket. Even after removing the corresponding CNAME record in Route53 I am unable to connect that subdomain. I already created a new Amplify App, tried deleting CNAMEs again, but it doesn't work.
Help is highly appreciated, as I am currently stuck with this not working.

**Error message**
Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.

Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
Note: previously the subdomain was set up as a ALIAS CNAME record to a CloudFront Distribution

![Screenshot 2020-06-20 at 00 38 24](https://user-images.githubusercontent.com/19940156/85183994-605c8e00-b28e-11ea-9e30-73a8f836985d.png)

**Comment by abhi7cr** [comment]
Hi @ChrisKno, 

Could you try deleting the domain from the amplify app, and re-adding it (if you haven't already tried)?

**Comment by ChrisKno** [comment]
> Hi @ChrisKno,
> 
> Could you try deleting the domain from the amplify app, and re-adding it (if you haven't already tried)?

Hi @abhi7cr,

thanks for your suggestion. I tried that multiple times, in different apps. It always fails saying the CNAME is already associated with a different resource. I tested by continuing to use my old cloudfront distribution with the A ALIAS record under app.DOMAIN.com and then renaming this entry to app-test.DOMAIN.com.
So like this there is no way the CNAME app.DOMAIN.com is even in use, right (also deleted it multiple times)?

What else could I try?

**Comment by abhi7cr** [comment]
Hi @ChrisKno,

Just to understand, there is no Cloudfront distribution which has the CNAME as your domain name, and when you tried deleting the domain from the amplify app and re-adding it, you still got the same issue?

**Comment by ChrisKno** [comment]
> Hi @ChrisKno,
> 
> Just to understand, these were the steps you took:
> 
> 1. Make sure there was no Cloudfront distribution which has the CNAME as your domain name. If there was, remove it using Cloudfront console (_if the app was hosted directly using Cloudfront & S3_) or delete all the amplify apps associated with that domain, and also delete old CNAME records from Route53
> 2. You then tried creating a new amplify app, and add the domain
>    And you still got the same issue?

@abhi7cr your comment totally helped me fix it now. I was always checking that there were no CNAME entries in Route53 - unaware that within the CloudFront settings there is the option to specify a CNAME (which does not appear in Route53, which is why this is confusing...)

I removed it from both Route53 and CloudFront settings, now I was able to add the Domain.

Appreciate your help, thank you!
