### ISSUE TITLE
SSL verification is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by TanayGarg01** [aws-amplify/amplify-console#783]
**App Id**: d33q5tvkrhj7zs
**Region**: ap-south-1
**Step**: SSL verification
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by abhi7cr** [comment]
Hi @TanayGarg01 ,

Could you try to follow the guide here as see if it helps: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#custom-domain-troubleshoot-guide.  Linking to a similar issue's resolution: https://github.com/aws-amplify/amplify-console/issues/15#issuecomment-515232292
