### ISSUE TITLE
--proxy-config parameter not evaluated

### ISSUE THREAD

**Issue by tomreineke** [aws-amplify/amplify-console#795]
In my Angular 9 app I'm using a proxy configuration in package.json like so:
`"start": "ng serve --proxy-config proxy.conf.json"`
The file proxy.conf.json looks like this:
`{
  "/swp": {
    "target": "http://ec2-18-156-45-215.eu-central-1.compute.amazonaws.com:8080",
    "secure": false
  }
}`
This is to avoid X-origin issues when addressing my backend. Locally this works fine. However, when I go to https://master.d38sqv238h80s.amplifyapp.com/password-forgotten and submit the form, the request is not routed to the backend.

How can I fix this?

**Comment by tomreineke** [comment]
Locally it works because I used:
`{ "/swp": { "target": "http://localhost:8080", "secure": false } }`
With the change of the target URL to http://ec2... this doesn't work.
I guess I'm doing it wrong, and I need a gateway or load balancer before the frontend and backend to avoid CORS issues.
Do I understand that correctly?

**Comment by abhi7cr** [comment]
Hi @tomreineke,

Is the ec2 instance your api server ?

**Comment by tomreineke** [comment]
Hi @abhi7cr ,
yes, exactly.

**Comment by tomreineke** [comment]
I'm using the API gateway now for frontend and backend, which seems to work.
