### ISSUE TITLE
SSL verification is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Mario-Celso** [aws-amplify/amplify-console#798]
**App Id**: dgw8fgz9nhe80
**Region**: us-east-1
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by abhi7cr** [comment]
Hi @Mario-Celso ,

Did you recently transfer the domain to Route53 from a different provider? If so, you need to make sure the NS records in the old provider matches the NS records in Route53. 

Also, could you verify if you have a similar CNAME record in your Route53/provider. Make sure there is no **.com** or any **TLD**(Top level domain) in the CNAME record name:

![image](https://user-images.githubusercontent.com/5371802/85880628-2d842f80-b791-11ea-9e7d-8220e6c8248c.png)

Let me know if this helps.

**Comment by nimacks** [comment]
Hi @Mario-Celso, are you still having issues?

**Comment by hsspain** [comment]
Closing this ticket.  Please let us know if you have further issues.
