### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by stela-admin** [aws-amplify/amplify-console#799]
**App Id**: d7qgsjeuxqirb
**Region**: ap-northeast-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by abhi7cr** [comment]
Hi @stela-admin,

It could be the case that the CNAME was already attached to another CloudFront distribution at the time of activation. If so, can you remove the CNAME from the Alternate Domains section in CloudFront, then delete this custom domain, and re-add it?

**Comment by stela-admin** [comment]
Hi Abhishek,

Thanks for your advice, I could finish adding a custom domain successfully!

**Comment by stela-admin** [comment]
Hi Abhishek,

Thanks for your advice, I could finish adding a custom domain successfully!

Best regards

2020年6月27日(土) 1:19 Abhishek Raj <notifications@github.com>:
