### ISSUE TITLE
Domain activation is Failed - Multiple AWS services

### ISSUE THREAD

**Issue by theapurvap** [aws-amplify/amplify-console#801]
**App Id**: d2w6hc2mk0dy5b
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**

I am trying to set up 2 custom domains `www.xxx.com` and `www-beta.xxx.com` pointing to 2 different branches of my Amplify app. However the domain activation fails on the last step. My DNS provider is Google Domains and I only have 2 `CNAME` records for Amplify (for 2 subdomains pointing at 2 different branches). Other than that I have some `CNAME` and `TXT` records for other AWS services (Cognito, SES, Certificate Manager, API Gateway). I am not sure if my AWS Cognito records are interfering with the Amplify app, I assume AWS Cognito hosted UI also uses CloudFront.

**Error message**

>Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Comment by mittal11viney** [comment]
Please assist.

**Comment by abhi7cr** [comment]
Hi @theapurvap,

Thanks for reporting. I am taking a look.

**Comment by abhi7cr** [comment]
Hi @mittal11viney,

The error suggests you have your domain pointed to another CloudFront distribution. Could you try searching for your domain name in the CloudFront console, and removing it from the CNAME section of the associated CloudFront distribution?

**Comment by theapurvap** [comment]
There are no CloudFront distributions in the AWS CloudFront console. I was using one a few months back but I scrapped that a while ago.

**Comment by abhi7cr** [comment]
Hi @theapurvap,

Could you try deleting the sub-domains from the amplify app, and re-adding them one at at time?

**Comment by theapurvap** [comment]
Just to be clear, on the DNS side, all sub-domains will have the same address right? `XXXXXXX.amplifyapp.com`? Or should it be `branch.XXXXXXX.amplifyapp.com`?

**Comment by theapurvap** [comment]
Okay adding the subdomains one at a time worked. Looks like it is a bug on the AWS side. The validation fails when adding multiple subdomains all at once. The workaround is to add one subdomain and get it completely validated. Then add the rest of the subdomains.

Thanks @abhi7cr !!!

**Comment by abhi7cr** [comment]
Hi @mittal11viney,

Were you able to resolve the issue

**Comment by nimacks** [comment]
Closing, please re-open if this is still an issue.

**Comment by juanitomint** [comment]
Same issue here but one at a time isn't working form me
is still telling me that 
ALso viewDNS is grayed out
![Uploading ksnip_20200701-180242.png…]()
