### ISSUE TITLE
Env.Variables during Build for process.env

### ISSUE THREAD

**Issue by NicolasMegow** [aws-amplify/amplify-console#806]
** Please describe which feature you have a question about? **
I'm trying to deploy a Gatsby site with auth0.
That requires three variables to be accessible during build in process.env:
      domain: process.env.AUTH0_DOMAIN,
      clientID: process.env.AUTH0_CLIENTID,
      redirectUri: process.env.AUTH0_CALLBACK,
Whichever way I try to pass the variables, I get the same error (if the build succeeds) on pageload:
"Uncaught Error: domain option is required" --> which suggests that the variables weren't present.

** Provide additional details**
- tried this syntax "key: value" from here 
https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html 
--> didn't work...

- added the Env.vars under App Settings and tried this syntax "npm run build:$BUILD_ENV" from here https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html 
--> Build failed with info that such a command doesn't exist...

- tried hardcoding in the Build Settings file (added the "" to offset markdown) --> didn't work...
env:
  variables:
    "- AUTH0_DOMAIN=$AUTH0_DOMAIN"
    "- AUTH0_CLIENTID=$AUTH0_CLIENTID"
    "- AUTH0_CALLBACK=$AUTH0_CALLBACK"

- linked Env.vars like this in the build settings... 
    "- $AUTH0_DOMAIN"
    "- $AUTH0_CLIENTID"
    "- $AUTH0_CALLBACK"
triggered this during build:
2020-06-28T07:40:46.487Z [INFO]: # Retrieving environment cache...
2020-06-28T07:40:46.530Z [INFO]: # Retrieved environment cache
2020-06-28T07:41:10.806Z [INFO]: ## Processing Environment Variables
                                 # Set Environment Variable: 0
2020-06-28T07:41:10.808Z [INFO]: # Set Environment Variable: 1
                                 # Set Environment Variable: 2 
--> and resulted in a subsequent warning that '0=WhateverTheVariableValue' is "not a valid identifier"...

After going through about twenty builds, I'd really appreciate a quick hint as to where I'm making a mistake??

**Comment by abhi7cr** [comment]
Hi @NicolasMegow,

Thanks for reporting. I will take a look and get back to you. Can you give the appId and region ?

**Comment by NicolasMegow** [comment]
Hi @abhi7cr ,
sure: us-east-2 and d293hfauc7dro7.
Thanks!

**Comment by abhi7cr** [comment]
Hi @NicolasMegow,

The env variables should be added in process.env. I just tested adding some variables in the `env` section as follows:
```
version: 1
env:
  variables: 
      TEST_A: componentA
      TEST_B: componentB
      TEST_C: componentC
```
I am not sure if you are using webpack, but for my project, I am using it. I had to use the [EnviromentPlugin](https://webpack.js.org/plugins/environment-plugin/) to define these env variables in order for webpack to string-substitute these values during build time.

**webpack.config.js**
```
 plugins: [
      new webpack.EnvironmentPlugin({
       TEST_A: null,
       TEST_B: null,
       TEST_C: null
      })
  ]
```

To test this, I console logged the above variables during runtime:

```
    console.log('A', process.env.TEST_A)
    console.log('B', process.env.TEST_B)
    console.log('C', process.env.TEST_C)
```

**output from the inspect window:** 
```
tes.js:7 A componentA
test.js:8 B componentB
test.js:9 C componentC
```

**Comment by NicolasMegow** [comment]
Dear @abhi7cr, 

thanks a lot for looking into this!
Gatsby is using webpack (https://www.gatsbyjs.org/docs/add-custom-webpack-config/).
I've found away to work around env.vars in this case - but I'll definitely come to back to this as I expect to soon need it again :)
The EnvironmentPlugin and console.log would make good additions to the docs.

Really appreciate your quick and thorough help! Thanks!
Nicolas
