### ISSUE TITLE
Unable to see the deployment details in web console

### ISSUE THREAD

**Issue by hanstf** [aws-amplify/amplify-console#807]
**App Id**: d13jpjw7u1auh
**Region**: ap-southeast-1
**Step**: Done
**Status**: Done

**Issue/question**
In the aws web console -> amplify -> my application -> clicking on one of the branch ([https://ap-southeast-1.console.aws.amazon.com/amplify/home?region=ap-southeast-1#/d13jpjw7u1auh/dev/2](url)) will redirect to blank page.

<img width="871" alt="Screenshot 2020-06-29 at 2 40 45 AM" src="https://user-images.githubusercontent.com/8406334/85955564-f17be500-b9b1-11ea-882b-e4d6880efa1b.png">

I am trying to deploy a gatsby site, my deployment is succeeded but I can't access the site and it keeps on showing 502 cloudfront error. Due to the issue above, it is impossible for me to debug this. Is there any other way I can debug?

<img width="1368" alt="Screenshot 2020-06-29 at 2 42 17 AM" src="https://user-images.githubusercontent.com/8406334/85955591-27b96480-b9b2-11ea-8132-0ea8994c3d3c.png">

**Comment by abhi7cr** [comment]
Hi @hanstf,

Thanks for reporting this. Could you inspect the browser console to see if there are any errors?  I will look into what’s happening from my side.

**Comment by hanstf** [comment]
Hi @abhi7cr

It is showing this: 
<img width="1368" alt="Screenshot 2020-06-29 at 3 21 40 AM" src="https://user-images.githubusercontent.com/8406334/85956339-c7c5bc80-b9b7-11ea-9d07-ab52627d0fcd.png">

**Comment by abhi7cr** [comment]
@hanstf Looks like the amplify.yml file is invalid. Could you paste the file? I will add an item in our backlog to show the specific errors on the screen, instead of a white screen.

**Comment by hanstf** [comment]
Hi @abhi7cr 

I am using aws cdk to configure actually and it seems in a valid format
```javascript
const app = new amplify.App(this, 'App', {
      sourceCodeProvider: new amplify.CodeCommitSourceCodeProvider({ repository }),
      appName: 'loraklorek-website',
      buildSpec: codebuild.BuildSpec.fromObject({
        version: '1.0',
        frontend: {
          phases: {
            preBuild: {
              commands: [
                'npm install'
              ]
            },
            build: {
              commands: [
                'npm run build'
              ]
            }
          },
          artifacts: {
            baseDirectory: 'public',
            files: '**/*'
          },
          cache: {
            paths: 'node_modules/**/*'
          }
        }
      })
    });
```

but strangely, in the aws console, it stays as json format instead of converted to YML, is this aws-cdk issue ?
![Screenshot 2020-06-29 at 9 31 49 AM](https://user-images.githubusercontent.com/8406334/85964275-98c93e00-b9eb-11ea-9a8e-3004d2668920.png)

**Comment by ImanuelRichter** [comment]
We experienced exactly the same issue with our amplify stack that was deployed through aws-cdk 1.38.0.
It used to work and without deploying any changes we also experienced that error.
Temporary solution for us was to manually transform the json content of amplify.yml to yml using https://www.json2yaml.com/

**Comment by vbelser** [comment]
We experienced the same issue.  After inspecting the yaml and fixing syntax errors, the blank page returned to normal.  It would be nice if the Amplify Console complained about the bad yaml before getting this far.

**Comment by swaminator** [comment]
This has been fixed.
