### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by stevezhang-dstring** [aws-amplify/amplify-console#809]
**App Id**: d2im0ktc4w3apd
**Region**: ap-northeast-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by abhi7cr** [comment]
Hi @stevezhang-dstring 
The usual cause of this error is that the domain name was already attached as a CNAME in another cloudfront distribution, when the domain activation took place. Did you have this domain attached to another amplify app or directly to CloudFront? If so, you would have to delete the amplify app/ remove it from the CloudFront distribution via the CloudFront Console. Then you can delete and re-add the domain to your app.

**Comment by stevezhang-dstring** [comment]
Thanks, after deleting the cloudfront record, it works.
