### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by juserr** [aws-amplify/amplify-console#810]
**App Id**: d3b02k89dp2vqy
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by abhi7cr** [comment]
Hi @juserr,

As the error indicates, the domain name was already attached as a CNAME in another cloudfront distribution, when the domain activation took place. Did you have this domain attached to another amplify app or directly to CloudFront? If so, you would have to remove it from the CloudFront distribution via the CloudFront Console. Then you can delete and re-add the domain to your app.

**Comment by juserr** [comment]
That was it, cool! Thanks
