### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by voiladaniel** [aws-amplify/amplify-console#811]
Hello,

I have a problem with activation of a Domain in AWS Amplify.

The error message is: "Error message: One or more of the CNAMEs you provided are already associated with a different resource."

I think that the domain I am trying to use was used before in another AWS Amplify app, but right now the domain have been bought by me.

PS: I ham using only a free tier account.

**Comment by abhi7cr** [comment]
Hi @voiladaniel,

Could you try deleting and re-adding the domain to the app?

**Comment by nimacks** [comment]
@voiladaniel ,

are you still having issues?

**Comment by ganipcanot** [comment]
Resolving due to age - re-open if you are still facing the issue!
