### ISSUE TITLE
Custom domain creates CNAME for subdomain instead of A Alias

### ISSUE THREAD

**Issue by ohlr** [aws-amplify/amplify-console#812]
** Please describe which feature you have a question about? **
Adding a domain + subdomain, the subdomain record within Route 53 is of type CNAME.

I wonder if making the subdomain A ALIAS saves money.
According to https://aws.amazon.com/route53/pricing/ A Alias records are free.

**Comment by nimacks** [comment]
Hi @ohlr,

Modifying the records setup by Amplify may have unexpected results for your App. Can you provide more details on what you're trying to achieve? Are having billing issues related to Route53?

https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html
https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-amazon-route-53.html

**Comment by ohlr** [comment]
records created by amplify:
```
example.org | A | ALIAS uuid.cloudfront.net
www.example.org | CNAME | uuid.cloudfront.net
```

I wonder if 
```
example.org | A | ALIAS uuid.cloudfront.net
www.example.org | A | ALIAS uuid.cloudfront.net
```
would be better

**Comment by ganipcanot** [comment]
Resolving due to age - please re-open if you are still experiencing issues.
