### ISSUE TITLE
Inconsistent and silent DNS behavior

### ISSUE THREAD

**Issue by ohlr** [aws-amplify/amplify-console#814]
Having existing records in my route 53 for example.org and www.example.org

The root record (example.org) gets overriden by amplify console while the subdomain (www.example.org) records does not get updated.

All that happens silently.

**Comment by nimacks** [comment]
Can you provide more details on the problem you're trying to solve?

**Comment by ohlr** [comment]
well:

Say you have an existing website with follwing Route53 Setup
1. example.org A somehting
2. www.example.org Cname somehting

Now you register example.org and www.example.org through Amplify.
The 1. entry in your existing setup will be silently overriden the 2. will remain unchanged (silently)

I suspect this to be a bug rather than a question.

**Comment by Athena96** [comment]
Hi @ohlr you would need to disassociate your domain old CNAME record before attempting to add it as a custom domain for your amplify app.

**Comment by ohlr** [comment]
@Athena96 yes of course... But for the root I don't (it automatically overrides the root record) 
while for the www. I have to... This is undocumented

**Comment by ferdingler** [comment]
I wasn't able to reproduce. The issue reported is that if you have your domain managed by Route53 with the following records: 

```
example.com          A          some_ip_address
www.example.com.     CNAME      some_domain_name
```

and then you add it to Amplify as a custom domain. The A record for `example.com` will be overridden but the CNAME record for `www.example.com` will not. In my case, both records were correctly configured to point to the CloudFront distribution. 

Closing this issue.
