### ISSUE TITLE
Last Commit message incorrect?

### ISSUE THREAD

**Issue by FizzBuzz791** [aws-amplify/amplify-console#815]
The "Last Commit" message always says "This is an autogenerated message | Auto-build | Github-mybranchname".

I would have expected it to show the last commit for that branch, such as "Added feature X". Am I mistaken?

This is a screenshot of two branches connected and neither are showing the latest commit;
![image](https://user-images.githubusercontent.com/2747764/86205488-96f2ac80-bb9c-11ea-9869-216a3dced18a.png)

**Comment by nimacks** [comment]
Hi @FizzBuzz791 ,
can you provide your appId and region and we'll investigate this issue for you.

**Comment by FizzBuzz791** [comment]
Hi @nimacks - I've narrowed it down a little. It looks like it's not pulling the latest commit when you first link a branch, maybe something to do with the way the webhooks work? Subsequent commits propagate properly.

ARN: arn:aws:amplify:ap-southeast-2:157153681450:apps/dldzc7aaj7fba
Region: ap-southeast-2

Though, if the above is expected behavior, I'm happy to close.

**Comment by Athena96** [comment]
Hi @FizzBuzz791 yes, when you first link a branch (or if you redeploy a version by clicking "Redeploy this version") then the "Last Commit" text will show that message, but on subsequent commits the actual commit message should show.
