### ISSUE TITLE
Amplify Console Hosting and Route53 Weighted Policy

### ISSUE THREAD

**Issue by alexkates** [aws-amplify/amplify-console#818]
I have an AWS Amplify app deployed, with 2 custom domains (a.example.com and b.example.com). It's my understanding that these point to 2 separate CloudFront distributions. I am also using AWS Amplify's Console hosting.

I'd like to have a Route 53 weighted policy to route c.example.com to the aforementioned custom domains. Is this possible? If so, how?

**Comment by nimacks** [comment]
Hi @alexkates ,

Can you describe what problem you're trying to solve with this approach?

**Comment by alexkates** [comment]
Sure. I have two isolated environments connected to two branches in my Amplify app. Think of these environments two production environments, supported two separate customers. We are trying to drive traffic, and want to dynamically control how much traffic is routed to each environment.

**Comment by Athena96** [comment]
Hi @alexkates so if you have 2 custom domains setup, then you can create your 3rd (c.example.com) and configure a Route53 Weighted policy for it linking it to the other two domains: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html#routing-policy-weighted
