### ISSUE TITLE
Domain activation error Something went wrong

### ISSUE THREAD

**Issue by juanitomint** [aws-amplify/amplify-console#819]
**App Id**: d2899duog3x4ik
**Region**: us-east-1
**Step**: Domain activation
**Status**: error

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.
been trying to setup this for the last two days
**Issue/question**

**Error message**
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions
**Note**:
please help!
![ksnip_20200701-181730](https://user-images.githubusercontent.com/1730371/86292872-ebf7e800-bbc7-11ea-8c48-a8e4bd3a8774.png)

**Additional information**

**Comment by nimacks** [comment]
The error indicates that your domain is already configured with another distribution. Can you try to disassociate the domain before associating in the Amplify Console??

```javascript
com.amazonaws.services.cloudfront.model.CNAMEAlreadyExistsException: 
One or more aliases specified for the distribution includes an incorrectly 
configured DNS record that points to another CloudFront distribution
```

**Comment by juanitomint** [comment]
Sure... How.!? Amplify doesnt expose any means to do that nor cloudfront does in the same account

**Comment by Athena96** [comment]
You will need to update the CNAME connection the cloudfront distribution you no longer use, through Route53 / 3rd party provider.

**Comment by juanitomint** [comment]
Done that but amplify console doesnt allow me to retry either (the button doesnt work) case id 7152384391

**Comment by kahdojay** [comment]
@juanitomint Hi, based on the ns records for recargasuatgreen.personal.com.ar it looks like your domain is hosted in Route53. You'll need to go to the Route53 console and into your hosted zone settings, remove the CNAME record that is pointing recargasuatgreen.personal.com.ar to a cloudfront distribution (<someid>.cloudfront.net). [More details on that in the Route53 docs](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-editing.html).

We have a known issue with the retry button (#512), so for now, once you've removed that CNAME and waited for the TTL to expire you can delete and recreate the custom domain in Amplify Console to try again. 

Let us know if you run into any further issues with the above
