### ISSUE TITLE
Access denied error

### ISSUE THREAD

**Issue by asatvilker** [aws-amplify/amplify-console#822]
I am having troubling deploying my app. I am getting the following error:
<img width="789" alt="Screenshot 2020-07-06 at 06 11 54" src="https://user-images.githubusercontent.com/56475258/86557924-ad5b8800-bf4f-11ea-96e5-91e0e23232d4.png">

note other solutions have suggested the use of rewrites and redirects however after trying all of them nothing happens. Also I tried removing the react routing from the app as for all issues with this same error this was the cause. it should have displayed a simple blank page but i still got the same error.

if there are any suggestions on how to fix this that would be greatly appreciated.

**Comment by Athena96** [comment]
Hi @asatvilker can you try adding the following rewrite rule:

source address:
 `</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>`

target address: `/index.html`

type: `200 (Rewrite)`

**Comment by Darktofts** [comment]
I've had the same issue with my Vue app , there has been many suggestions about redirect rules I tried them all.  I did get it working by adding all the suggestions.


source address:
</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>

target address: /index.html

for 200 (rewrite) , 404 (rewrite) and 404 (redirect)

**Comment by hsspain** [comment]
Closing this ticket.  Please let us know if you have further issues.
