### ISSUE TITLE
Redirect setup for static generated + SPA sites

### ISSUE THREAD

**Issue by FelixRe0** [aws-amplify/amplify-console#823]
** Please describe which feature you have a question about? **

Rewrites and redirects

** Provide additional details**

The issue #70 should either be opened again and fixed or the [workaround](https://github.com/aws-amplify/amplify-console/issues/70#issuecomment-531711857) should be reflected in the documentation [here](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#trailing-slashes-and-clean-urls) 
I can confirm that setting `</index\.html/> => /404.html [404 Rewrite]` is resulting in the desired behavior and does not lead to the [mentioned side-effect](https://github.com/aws-amplify/amplify-console/issues/70#issuecomment-571511510) for us.

**Comment by Athena96** [comment]
Hi @FelixRe0 so you are no longer experiencing any issues with your 404 rewrite rule, is that correct?

**Comment by FelixRe0** [comment]
@Athena96 Yes that's correct. We could not identify any issue yet.

**Comment by hsspain** [comment]
Closing this ticket.  Please let us know if you have further issues.
