### ISSUE TITLE
Builds broken for 20+ hours

### ISSUE THREAD

**Issue by simpson** [aws-amplify/amplify-console#824]
Case ID 7156065351 in the AWS Support System

** Provide additional details**
Our builds have been down for almost 24 hours, the AWS Web UI states there is an issue connecting to Github but Github has no outages and reports their webhooks are working correctly. We have tried reauthorizing the repo and that wasn't successful, we have deleted the webhook and application auth in Github and established new connections and they still don't work. Also to note, the Amplify Web UI is full of errors in the Chrome Console as well.

![Screen Shot 2020-07-06 at 2 56 54 PM](https://user-images.githubusercontent.com/1605737/86629161-fbe14480-bf98-11ea-8968-859a44a6f395.png)

![Screenshot 2020-07-05 18 31 44](https://user-images.githubusercontent.com/1605737/86628967-ac027d80-bf98-11ea-9ea7-c7ae3b67fd54.png)

![Screenshot 2020-07-05 21 04 04](https://user-images.githubusercontent.com/1605737/86628968-ac027d80-bf98-11ea-9f59-626e43f66656.png)

**Comment by nimacks** [comment]
Hi @simpson, sorry to hear that you're having issues with your build. The error shown above indicates that a webhook which is required to trigger builds already exists. Can you check in github under your repository settings -> webhooks. Find the webhook associated with your app (it should have your appId as a parameter in the URL). Delete it, and then re-authenticate your app in the Amplify Console. Let us know if that works.

**Comment by simpson** [comment]
hey @nimacks someone else in the Discord recommended that earlier today, we deleted the webhook and oauth application and reinstalled both. Still no luck :(

**Comment by nimacks** [comment]
@simpson, after deleting the webhook and oauth app, are you getting the same error or something different? Also how many webhooks are associated with that repository?

**Comment by simpson** [comment]
Gave up and deleted app
