### ISSUE TITLE
Missing option to configure backend for branch autodetection?

### ISSUE THREAD

**Issue by lorengordon** [aws-amplify/amplify-console#825]
** Please describe which feature you have a question about? **

[Pattern-based feature branch deployments](https://docs.aws.amazon.com/amplify/latest/userguide/pattern-based-feature-branch-deployments.html)

** Provide additional details**

I created an amplify app and enabled branch autodetection, but the option to configure the backend is not available. This means whenever a new branch is created, the build fails because it is not linked to a backend. How can I turn this feature on for this app?

![image](https://user-images.githubusercontent.com/8457307/86665095-2dabd880-bfa4-11ea-95fe-1214046ed8fd.png)

**Comment by Athena96** [comment]
Hi @lorengordon do you have an existing backend setup for your app?

**Comment by lorengordon** [comment]
Yes, there is a backend. I'm not sure what "existing" refers to... I used amplify to create the backend.

Here is a new branch I just pushed to the repo:

![image](https://user-images.githubusercontent.com/8457307/86809088-54175580-c030-11ea-9816-fea9045cd18a.png)

And here you can see I can assign a backend manually:

![image](https://user-images.githubusercontent.com/8457307/86809180-70b38d80-c030-11ea-831e-dcac725e9df3.png)

**Comment by Athena96** [comment]
Did you have a backend environment setup before you tried to enable the pattern-based feature?
Because in the first screenshot you shared, there is no option for "Branch autodetection - backend environment" like in the docs
https://docs.aws.amazon.com/amplify/latest/userguide/pattern-based-feature-branch-deployments.html

**Comment by lorengordon** [comment]
> Because in the first screenshot you shared, there is no option for "Branch autodetection - backend environment" like in the docs

Yes, exactly, that's exactly what I'm saying. There is no option for it in our project. That's why I shared the screenshot, so you could see what I'm seeing.

> Did you have a backend environment setup before you tried to enable the pattern-based feature?

Fairly sure, yes, but it's been a long week so who knows. I definitely have disabled and re-enabled branch autodetection to try pick it up. I have also reconnected the repo. The option just is not there.

**Comment by lorengordon** [comment]
@Athena96 I went back through our slack workspace and remembered that no, we did not have the backend configured when we _first_ setup the pattern-based feature. I added the backend later. But since adding the backend, I have disabled the branch builds and re-enabled them, and reconnected the repo, several times, to no avail.

**Comment by lorengordon** [comment]
@Athena96 sorry, hate to bother you, but just wanted to follow up if this is some bug in the UI, when the project is created without a backend first? It's not critical to me, I have a workflow for the project. So if this is not something you want to investigate further then we can close this. I just hate to open issues and leave them unworked/untriaged.

**Comment by mansiva** [comment]
We're having the same issue, project was created, multiple backend environments were setup as per the amplify docs (dev, test, prod), then when enabling branch auto-detection no option to specify which backend to connect to.

Now any new branches created in git are failing to build since no backend is being defined, and strangely enough yesterday a bunch of new backend environments started to appear with strange names: arabelle, belicia, blakeley, bobbye, britt... Nobody in the team claims to have created them, so it's pretty weird.

**Comment by vic-blt** [comment]
Same issue here.
The project was initially created with a backend.
![amplify-console](https://user-images.githubusercontent.com/48869999/106908122-4c6f7a80-66ff-11eb-83d3-18b9b081fcec.png)

**Comment by vic-blt** [comment]
See my comment https://github.com/aws-amplify/amplify-console/issues/448#issuecomment-777585090
It appears that if your app's framework is set to "React" you won't have options to set a default backend either for "branch autodetection" or "previews".
You have to set your app's framework to "React - Amplify".
The only I found to do this is to deploy a fullstack amplify app from samples :
_Host web app > From fullstack samples > Authentication Starter_

**Comment by vic-blt** [comment]
I found the solution, see my new comment https://github.com/aws-amplify/amplify-console/issues/448#issuecomment-781233282

**Comment by ganipcanot** [comment]
Resolving due to age - please re-open if you are still experiencing issues.
