### ISSUE TITLE
Build number showing up in URLs - breaking links

### ISSUE THREAD

**Issue by ryanrf-ac** [aws-amplify/amplify-console#826]
Hi there,

After deploying an app using AWS amplify, the app is displaying the home page, but the links are all going to `https://<domain>/0000000029/<relative path>` where `0000000029` is the build number (#29 in this case). The correct link is show in the html from the home page, and if I manually navigate to that URI the correct object is there.
I feel like this must be a configuration I'm missing, or perhaps a redirect that should be happening. I have no redirects/ rewrite rules created, and there are no other issues associated with building or deploying.

I can download the deploy artifacts and host it locally on my machine and everything looks good, so I'm at a bit of a loss as to where the weird link is coming from. I'm thinking it's something to do with cloudfront pointing to the wrong S3 key or something.
Any help is greatly appreciated.

It may be worth mentioning I'm using Hugo (0.73) and this very well may be an issue with Hugo.

**Comment by Athena96** [comment]
Hi @ryanrf-ac can you share your appId and the region your app is in?

**Comment by ryanrf-ac** [comment]
@Athena96 Of course. My appId is d3idu9b8upbkgj and region is us-east-1.

**Comment by davetlewis-van** [comment]
@ryanrf-ac Adding a trailing slash to the links fixed it. There's an existing bug report here that pointed to the solution: https://github.com/aws-amplify/amplify-console/issues/405

**Comment by ryanrf-ac** [comment]
Awesome. Thanks @davetlewis-van!
