### ISSUE TITLE
Unable to build multiple apps in monorepo

### ISSUE THREAD

**Issue by simpson** [aws-amplify/amplify-console#827]
** Please describe which feature you have a question about? **
It was recently announced that Amplify would support a monorepo. We setup two apps, each formed with their own approot as defined in the monorepo documentation, it will only build the first app. It looks like our amplify.yaml is formed properly, but it doesn't work so we either have something wrong or the feature doesn't work yet.

We clearly type in the secondary app name, admin.website.org however after the app is created it reverts to website.org, assumingely because it is the first approot defined in the amplify.yaml

** Provide additional details**

Screencast attached.

[Screen Recording 2020-07-06 at 8.31.11 PM.zip](https://github.com/aws-amplify/amplify-console/files/4881815/Screen.Recording.2020-07-06.at.8.31.11.PM.zip)

**Comment by Athena96** [comment]
Hi @simpson I think the issue is the "." in your amplify.yml file ("appRoot: ./apps/admin-designed-org")
The dot should not be included, the paths are relative. We should call this out better in the documentation.
https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#monorepo-configuration

Let us know if you are still facing issues after you remove the "." from both of your appRoot directories. Thanks

**Comment by simpson** [comment]
@Athena96 It doesn't build without the period. To demonstrate, I removed the period and committed, created a new app and it immediately fails at build.

![Screen Shot 2020-07-07 at 6 58 50 PM](https://user-images.githubusercontent.com/1605737/86853152-f876b780-c083-11ea-9e2d-d1c004e4ee79.png)

**Comment by simpson** [comment]
@Athena96 I also tested without the slash, apps/admin-designed-org but still no dice

**Comment by Athena96** [comment]
Can you please share the folder structure of your repo, and where amplify.yml is in it.

**Comment by simpson** [comment]
![Screen Shot 2020-07-10 at 2 53 49 PM](https://user-images.githubusercontent.com/1605737/87188656-3b6f9f80-c2bd-11ea-8711-dbd55267b1ed.png)

@Athena96 We have a single amplify.yml at the root, and a folder named /apps/ which will have our clients. In our amplify.yml, if we remove the . or ./, it won't build

**Comment by simpson** [comment]
@Athena96 Any thoughts?

**Comment by azgorov** [comment]
@simpson Did you manage to make it work or you still waiting for solution?

It seems that this feature is not working at all - it always takes first appRoot entry.

**Comment by simpson** [comment]
@azgorov As far as right now, I agree that monorepo support is fundamentally broken. I'm hoping we hear back from someone at AWS, perhaps we are doing something wrong but we did follow their documentation

**Comment by simpson** [comment]
..crickets...

**Comment by azgorov** [comment]
Is this going to be fixed at all? Any news here?

**Comment by swaminator** [comment]
@simpson @azgorov apologies it took so long to get to this. We're looking into it now.

**Comment by swaminator** [comment]
@simpson @azgorov we figured out the issue. This is a design limitation with the current approach and requires you to follow a sequence of operations to get monorepos building properly.

1. Connect appA
2. Connect appB
3. After connecting *both* apps build a combined buildspec.yml. If you do step number 3 before number 2 the monorepo feature will not work.

**Comment by simpson** [comment]
@swaminator FYI, we followed these steps exactly and it still doesn't work

**Comment by victorccccc** [comment]
Hi, sorry for the inconvenience. we've updated Monorepo feature and you can specify `appRoot` via `AMPLIFY_MONOREPO_APP_ROOT` environment variable. 

Docs for reference: https://docs.aws.amazon.com/amplify/latest/userguide/monorepo-configuration.html

Feel free to reopen this if issue persists
