### ISSUE TITLE
Unable to assume specified IAM Role when deploying with AWS Amplify using GitHub

### ISSUE THREAD

**Issue by HoussemLay** [aws-amplify/amplify-console#828]
I was trying to deploy my application with AWS Amplify using github and I got this error :

2020-07-03T10:39:32.225Z [ERROR]: !!! Unable to assume specified IAM Role. Please ensure the selected IAM Role has sufficient permissions and the Trust Relationship is configured correctly.
2020-07-03T10:39:32.348Z [INFO]: # Starting environment caching...
2020-07-03T10:39:32.348Z [INFO]: # Environment caching completed
Terminating logging...

And this is the trust policy:

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "amplify.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}

**Comment by Athena96** [comment]
Hi @HoussemLay what step of the build do you get this error? (e.g. Provision, Build, Deploy,...)

**Comment by HoussemLay** [comment]
Hello, the second step : Build

**Comment by Athena96** [comment]
Do you have this IAM role setup?
https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html

**Comment by HoussemLay** [comment]
Yes, i did

**Comment by HoussemLay** [comment]
Any news ? this is urgent !

**Comment by swaminator** [comment]
@HoussemLay sorry this has taken so long to get back to you. Were you able to resolve your issue?

**Comment by HoussemLay** [comment]
Unfortunately no, the problem still persists

**Comment by swaminator** [comment]
Can you go to `App settings > General` and take a screenshot of what IAM role you have.

**Comment by HoussemLay** [comment]
<img width="347" alt="amplify" src="https://user-images.githubusercontent.com/57541651/89947686-27ed8680-dc25-11ea-972a-0adb61ab8c93.png">

**Comment by tmwlsh** [comment]
@HoussemLay, @swaminator, Any more news on this? i think i have a similar issue.

**Comment by stenfalp** [comment]
I have the same problem with CodeCommit. I have full access to my CodeCommit repository from my PC, but the Amplify Console is unable to pull the repository even using a user with AdministratorAccess.

**Comment by gaochenyue** [comment]
Same issue here. I'm deploying the sample project in HongKong

**Comment by stenfalp** [comment]
See my answer on [stackoverflow](https://stackoverflow.com/questions/65287024/permission-problem-accessing-codecommit-repository-during-build-phase).

**Comment by gaochenyue** [comment]
@stenfalp You saved my day. Thank you so much!

**Comment by gaochenyue** [comment]
@stenfalp You saved my day. Thank you so much!

**Comment by ganipcanot** [comment]
Resolving due to age - please re-open if you are still experiencing issues.
