### ISSUE TITLE
Domain activation is Failed - Unable to retry

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-console#830]
**App Id**: d2ctnb7fwe3m0u
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

After domain activation failure, retry button appears to not be working. Clicking on the button does nothing. Have tested on 2 different desktops and in both Chrome and Edge.

**Comment by Athena96** [comment]
Hi @blairtaylor did you receive an error message when the domain activation failed?

**Comment by blairtaylor** [comment]
Yes but the issue is not the error the issue is that once you correct any DNS config issues you cannot retry the activation because clicking the retry button does nothing.

**Comment by nimacks** [comment]
@blairtaylor we have released a fix for the retry button. Let us know if this is still an issue.
