### ISSUE TITLE
Custom domain failing final step

### ISSUE THREAD

**Issue by simpson** [aws-amplify/amplify-console#831]
**App Id**: arn:aws:amplify:us-east-1:252100588959:apps/d16w4ydm7nszvf
**Region**: us-east-1
**Step**: domain activation 
**Status**: failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A digicert certificate exists

**Error message**
Error message: The status of this certificate request is "Failed". One or more domain names have failed validation due to a Certificate Authority Authentication error. Learn more: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-caa.html

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by Athena96** [comment]
Hello @simpson we currently do not support 3rd party SSL certificates, because we provide/manage an ACM certificate by default for apps. We have this as a feature request though.

You will need to disconnect the digicert certificate from your domain, then add your custom domain to your app. Thanks!

**Comment by simpson** [comment]
@Athena96 I already connected the custom domain, see attached screenshot. All of our DNS is at Cloudflare and other domains work.

<img width="1720" alt="Screen Shot 2020-07-07 at 11 33 34 AM" src="https://user-images.githubusercontent.com/1605737/86805343-cc3c4600-c045-11ea-8bda-2d38f5308a66.png">

**Comment by juanitomint** [comment]
I think is the same as in 
https://github.com/aws-amplify/amplify-console/issues/819

**Comment by simpson** [comment]
@juanitomint It looks like we are both stuck on the last step, but the errors are a bit different. @Athena96 are you saying that 3rd party domains are not possible to use? We have other CNAME records that work find with Amplify apps. It also states in Amplify that 3rd party domains are possible 

![Screen Shot 2020-07-08 at 10 30 52 AM](https://user-images.githubusercontent.com/1605737/86931648-577d1080-c106-11ea-90bf-25ae7de61280.png)

**Comment by simpson** [comment]
https://github.com/aws-amplify/amplify-console/issues/200

Followed these steps and tweaked a few other things (we don’t use universal certs only dedicated) and it worked
