### ISSUE TITLE
CNAMEAlreadyExistsException

### ISSUE THREAD

**Issue by ShivamSarodia** [aws-amplify/amplify-console#834]
**App Id**: None
**Region**: us-west-2
**Step**: Domain Activation
**Status**: Failed

**Issue/question**
I created an app on AWS Amplify and connected my custom domain. I decided not to use AWS Amplify, so I then deleted the custom domain and app.

Now, I am attempting to connect that domain on AWS Cloudfront (distribution ID E37HMY0HCTDR1G). However, I am receiving the error below, even though there is no Cloudfront instance or AWS Amplify currently connected to the domain. I'd like to associate my domain with my AWS Cloudfront instance above.

**Error message**
com.amazonaws.services.cloudfront.model.CNAMEAlreadyExistsException: One or more of the CNAMEs you provided are already associated with a different resource. (Service: AmazonCloudFront; Status Code: 409; Error Code: CNAMEAlreadyExists; Request ID: f3bdcb3a-7b16-4b42-be01-7fd108716fc1; Proxy: null)

**Additional information**

**Comment by Athena96** [comment]
Hi @ShivamSarodia do you have the appId of the app that you had deleted which was attached to your custom domain?

**Comment by ShivamSarodia** [comment]
Hey @Athena96, thanks for the reply. I've actually found a workaround that'll do for my needs, so I'll close out this ticket.
