### ISSUE TITLE
Config for Authentication

### ISSUE THREAD

**Issue by MohitKS5** [aws-amplify/amplify-console#835]
**Region**: tokyo
**Step**: config

**Issue/question**
What configuration is required for the received cookies to be set on the website hosted by aws-amplify ?
When I deploy exact he same build (react) on firebase or lightsail or  EC2 and point route 53 to it, it works. But the moment I use amplify received cookies aren't set.

**Additional information**
I faced this problem with one more project a week ago and had to finally go for firebase at the end assuming I was doing something wrong. But this happens again. So I am guessing some config I need to apply ?
So I am making a request from `https://demos.thedomain.com` to `https://api.thedomain.com` with fetch options as: 
```js
fetch('https://api.thedomain.com', {
  "body": {"username":"me@asdf.in","password":"qwerty"}",
  "credentials": "same-origin",
  "method": "POST",
  "headers": {
    "Accept": "application/json",
    "Content-Type": "application/json"
  }
})
```
and the response is: 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/FHXf8.png

**Comment by Athena96** [comment]
Hi @MohitKS5 what are you expecting the response to be (from the pic you attached).
Can you also share your appId. Thanks

**Comment by MohitKS5** [comment]
The response I received is the expected response. Also I found that using "credentials": "include" is saving the cookies and I don't understand why because they both are same origin ( one is root and one is a subdomain). I am closing the issue as I no longer have the problem but if you happen to know any reason for this , I will be glad to know.
