### ISSUE TITLE
Getting 403 errors rather than 404

### ISSUE THREAD

**Issue by cecilgwilliams** [aws-amplify/amplify-console#839]
** Please describe which feature you have a question about? **

How to redirect 403 errors to 404 page.

** Provide additional details**

We are getting what appear to be 403 errors from S3: 

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>C99D79BBA91A8E9B</RequestId>
<HostId>xAi7c7L/ds+laELa0DJIrCpOcNQRRxlL8LwGYZxoQDhcLcph43+0KXlj39xYtLJxeAY2GibWJnU=</HostId>
</Error>
```

when navigating to a page that does not exist, for example: https://www.industriallogic.com/blog/category/onsite-workshop/

**Comment by Athena96** [comment]
Hi @cecilgwilliams can you please share the current Rewrite/Redirect rules you have in place for your app.

**Comment by cecilgwilliams** [comment]
[
    {
        "source": "/shop",
        "target": "elearning.industriallogic.com/gh/submit?Action=BrowseAlbumsAction",
        "status": "301",
        "condition": null
    },
    {
        "source": "/games/pp.html",
        "target": "/blog/patterns-poker/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops",
        "target": "/training/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/about",
        "target": "/",
        "status": "302",
        "condition": null
    },
    {
        "source": "/remote-coaching",
        "target": "/coaching/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/about-us",
        "target": "/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/agile-reboot/",
        "target": "/agile-reboot/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/practicing-psychological-safety/",
        "target": "/practicing-psychological-safety-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/the-user-stories-workshop/",
        "target": "/user-stories-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/modern-agile-workshop/",
        "target": "/modern-agile-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/product-discovery-strategy-workshop/",
        "target": "/product-discovery-strategy-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/product-road-mapping-prioritization-workshop/",
        "target": "/product-roadmapping-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/sustainable-product-delivery-workshop/",
        "target": "/sustainable-product-delivery-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/real-work-workshop/",
        "target": "/real-work-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/testing-and-refactoring/",
        "target": "/testing-refactoring-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/legacy-code/",
        "target": "/testing-refactoring-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/extreme-programming/",
        "target": "/testing-refactoring-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/mob-programming-workshop/",
        "target": "/mob-programming-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/behavior-driven-development/",
        "target": "/behavior-driven-development-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/agile-overview/",
        "target": "/agile-overview-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/design-patterns/",
        "target": "/design-patterns-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/evolutionary-design/",
        "target": "/evolutionary-design-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/lean-startup/",
        "target": "/product-discovery-strategy-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/lean-requirements/",
        "target": "/user-stories-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/modern-agile-planning/",
        "target": "/product-roadmapping-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/distributed-mob-programming/",
        "target": "/mob-programming-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/user-stories-in-practice/",
        "target": "/user-stories-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/continuous-deployment/",
        "target": "/continuous-deployment-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/lean-management/",
        "target": "/lean-management-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/object-oriented-design/",
        "target": "/object-oriented-design-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/agile-testing/",
        "target": "/behavior-driven-development-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/testing-and-refactoring-for-managers/",
        "target": "/technical-excellence-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "/onsite-workshops/mob-programming/",
        "target": "/mob-programming-workshop/",
        "status": "301",
        "condition": null
    },
    {
        "source": "https://blog.industriallogic.com/",
        "target": "https://www.industriallogic.com/blog/",
        "status": "301",
        "condition": null
    }
]

**Comment by Athena96** [comment]
Please try adding the following 404 redirect rule:
JSON [{“source”: “/<*>”, “status”: “404”, “target”: “/404.html”, “condition”: null}]

https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#trailing-slashes-and-clean-urls

**Comment by cecilgwilliams** [comment]
This seems to have worked. I had added the same rule before but it was conflicting with some of our pages. But after ensuring all of our urls have a trailing slash I was able to add back this rule and resolve the problem.
