### ISSUE TITLE
Redirects for ReactJS project

### ISSUE THREAD

**Issue by Zurdge** [aws-amplify/amplify-console#84]
I'm currently working on a ReactJS project and hosting it on the Amplify-console.

When the ReactJS app builds it generates various file such as -
/static/css/main.5b1bc195.chunk.css
/static/js/2.705c8e40.chunk.js
/static/js/main.b3f08268.chunk.js

For my project work work I need to setup 'Rewrites and redirects' so that the website can access these files.

My 'Rewrites and redirects'' currently look like this
`

Source address | Target address | Type | Country code
-- | -- | -- | --
/static/css/main.5b1bc195.chunk.css | /static/css/main.5b1bc195.chunk.css | 200 (Rewrite) | -
/static/js/2.705c8e40.chunk.js | /static/js/2.705c8e40.chunk.js | 200 (Rewrite) | -
/static/js/main.b3f08268.chunk.js | /static/js/main.b3f08268.chunk.js | 200 (Rewrite) | -
/<*> | /index.html | 200 (Rewrite) | -

`

Everytime i send a new build to amplify these files are regenerated and I have to reconfigure the paths.

is there a way to have amplify-console automatically handle this?

For example something like ?
`

Source address | Target address | Type | Country code
-- | -- | -- | --
/static/css/<*> | /static/css/<*> | 200 (Rewrite) | -
/static/js/<*> | /static/js/<*> | 200 (Rewrite) | -
/static/js/<*> | /static/js/<*> | 200 (Rewrite) | -
/<*> | /index.html | 200 (Rewrite) | -

`

**Comment by Zurdge** [comment]
Hi thanks for the reply, this is a bit of a jumble mishmash for me. 
I don't see how to implement this.
Does each symbol have a different function e.g. <$> does something and <!> another?
"*" is universal for "all" so I figured that out ok.



this is what you were referring to right?

</^[^.]+$\|\.(?!(css\|gif\|ico\|jpg\|js\|png\|txt\|svg\|woff\|ttf\|map\|json)$)([^.]+$)/> | /index.html | 200
-- | -- | --

**Comment by Yaroslav-F** [comment]
@Zurdge To implement this - you'll need to copy it to the Rewrites and redirects section of the Amplify Console app settings.
Hopefully [this response](https://stackoverflow.com/a/57687772/2568409) can help.

**Comment by swaminator** [comment]
@Zurdge closing this issue. If you weren't able to solve this as per @Yaroslav-F's recommendation please reopen.
