### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by nellyans** [aws-amplify/amplify-console#841]
**App Id**: di50d4y6j7wb5
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by Athena96** [comment]
Hi @nellyans  Did you have this domain attached to another amplify app or directly to CloudFront? If so, you would have to remove it from the CloudFront distribution via the CloudFront Console. Then you can delete and re-add the domain to your app.

**Comment by nellyans** [comment]
Issue solved! Removed my domain from Amplify and reconnected it. Thanks.
