### ISSUE TITLE
How to handle shared backend for two frontend apps in a monorepo? 

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-console#845]
** Please describe which feature you have a question about? **
We have a monorepo with two frontend apps but one backend shared between them. We're planning to use the new monorepo feature but we don't want to do two backend pushes on one commit, since the backend is shared. We want the backend to be pushed once, then the frontend builds run and deployed. 

Is this possible? Currently it seems like two simulataneous backend pushes will happen which I imagine will cause an error? We use amplifyPush to push the backend.

**Comment by hisham** [comment]
I see this recommendation: https://docs.amplify.aws/cli/teams/multi-frontend

But does amplify console support the amplify pull command? It seems amplifyPush is the only supported command from previous experience. 

And we would want frontend plus backend builds to be atomic. i.e. if the shared backend build fails, we don't want to deploy either frontend.

**Comment by hisham** [comment]
Hey after looking into this some more, I don't think the current monorepo feature as it stands would work for us. The ideal build process I want is the following: push backend then if backend push is successful, push our two frontends simultaneously. 

The example given here of a react and gatsby app is a bit too ideal: https://aws.amazon.com/blogs/mobile/set-up-continuous-deployment-and-hosting-for-a-monorepo-with-aws-amplify-console/. 

What I would like to see is what is the process of deploying a monorepo with multiple react or angular apps that share one backend? Isn't this the more common use case?

**Comment by simpson** [comment]
@hisham Are you able to get your two different frontend clients building separately in Amplify?

**Comment by hisham** [comment]
@simpson it is possible to have the frontend clients build separately in amplify. It's just a question of what to do with the shared backend and how to trigger the deployment of that. 

We ended up however not using the monorepo feature for now, and instead just have two master branches (master and master-app-b). One for frontend app A and the other for frontend app B. Each branch has a custom domain. Our amplify.yml checks the branch name and runs the appropriate build.

**Comment by swaminator** [comment]
@hisham @simpson please check this out: https://gist.github.com/swaminator/6270806f38048552af9ce699a568a581

**Comment by hisham** [comment]
@swaminator I took a brief look. It involves using the amplify pull command, does AWS Amplify Console support this command in a headless way?

**Comment by siegerts** [comment]
Hi @hisham, linking the documentation for headless `amplify pull` below.

https://docs.amplify.aws/cli/usage/headless#amplify-pull-parameters

Closing for now based on the Monorepo example above and since it seems that you've taken another approach for now.
