### ISSUE TITLE
If Analytics was provisioned for an Amplify project and then removed, the app fail to connect to Amplify console 

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-console#85]
**Describe the bug**
The issue is described in full here: https://github.com/aws-amplify/amplify-cli/issues/2154

Basically, if the Analytics category was added to an Amplify project, then removed, some analytics keys are left in the amplify-meta.json and backend-config.json file. The build process dictated by Amplify console seems to look for these keys, and if they are present, infers the presence of another directory of analytics files. 

When removing the "analytics" key from the JSON by hand, the build succeeds.

**Comment by jkeys-ecg-nmsu** [comment]
@nimacks I had a legacy Amplify project that I was working on. I stated in the other issue linked to in the OP that I do not know that it is a reproducible error, and that I was posting these issues pretty much solely so that anyone who encounters this error will find this on search engines.

But if you want to MANUALLY reproduce it, you can just add this key to backend-config.json:

```
"analytics" : {}
```

Amplify Console should fail to connect if that key exists. 

Again, just trying to be a good samaritan for the next poor sap working on an Amplify legacy project, not reporting something that needs triage.

**Comment by jkeys-ecg-nmsu** [comment]
@nimacks you can also add the key described in the [screenshot here](https://github.com/aws-amplify/amplify-cli/issues/2154#issuecomment-525404266) to the meta.json file. That should also prevent the build from completing.

If you add those keys and run "amplify remove analytics" you should note that the keys remain, which kills the build process.

So not sure if you consider that a bug with the CLI, with Amplify Console, or with past versions of the CLI -- but it's a problem.

**Comment by nimacks** [comment]
@jkeys-ecg-nmsu,  this seems to be an issue with the CLI. If anyone running an older version of the CLI runs into this issue, our recommended solution would be to upgrade to the latest version of the CLI where this issue is not reproducible. I really appreciate you looking out for dev community. Cheers.
