### ISSUE TITLE
SSL verification is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by PWBM-BG** [aws-amplify/amplify-console#854]
**App Id**: d3gt87dokshzc5
**Region**: us-east-2
**Step**: SSL verification
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
updated my cname record but 'retry' does not seem to do anything

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by abhi7cr** [comment]
Hi @PWBM-BG,

Could you try deleting, and re-adding the domain to your amplify app?

**Comment by PWBM-BG** [comment]
Hi Abhishek, it successfully validated the cname record!  It is verifying domain ownership now but looks like it is working so far
Thanks for the quick response
Bill
