### ISSUE TITLE
[Bug] Amplify Console not showing the right kind of storage

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-console#860]
when i have dynamodb storage added

![image](https://user-images.githubusercontent.com/6764957/87561002-a7ec0380-c6ee-11ea-8328-4ffaeb8dad34.png)

 this happens in the console:

<img width="523" alt="image(3)" src="https://user-images.githubusercontent.com/6764957/87560870-7bd08280-c6ee-11ea-8aa0-e27c248c0fe1.png">

amplify console thinks i have **file** storage added!

**Comment by kahdojay** [comment]
Thanks for reporting this, I was able to reproduce it, we'll work on a fix.

**Comment by kahdojay** [comment]
We'd changed that tab to reflect the general storage category but I forgot to update this ticket, closing
