### ISSUE TITLE
Build succeeds but Console Web Preview fails

### ISSUE THREAD

**Issue by lukehedger** [aws-amplify/amplify-console#862]
We have installed the [Amplify Console Web Preview GitHub app](https://github.com/apps/aws-amplify-eu-west-2) on a repository connected to Amplify. Amplify connects the branch automatically and the build/deployment pipeline is successful. However, the Web Preview status check fails on GitHub.

On closer inspection it seems that the Web Preview is pointing to an incorrect App ID. The correct App ID (as seen in the Console) is `d9slrnc36kbq7`. But the Web Preview is linking to `du8ludhgzm5xn`. When trying to follow the link, the Console loads with an error message of "App with id: du8ludhgzm5xn not found". The region is `eu-west-2`.

We have tried to reconnect the repository (deleting the webhook from GitHub first) and confirm the webhook is created with the correct App ID. We have also tried to uninstall and reinstall the Web Preview app but this still seems to point to the incorrect App ID.

How can we remedy this? Is it a case of destroying the Amplify App completely and starting again from scratch?

<img width="449" alt="image" src="https://user-images.githubusercontent.com/1913316/87585244-af071780-c6d6-11ea-8fc1-6ece36c9c3a5.png">

<img width="305" alt="image" src="https://user-images.githubusercontent.com/1913316/87585267-b9291600-c6d6-11ea-9d8a-e54466798c08.png">

<img width="745" alt="image" src="https://user-images.githubusercontent.com/1913316/87585293-c47c4180-c6d6-11ea-8f5d-0a58b9e872af.png">

**Comment by abhi7cr** [comment]
Hi @lukehedger 
Thanks for reporting, I will take a look, and get back to you.

**Comment by lukehedger** [comment]
@abhi7cr Did you have any luck with this one?

**Comment by abhi7cr** [comment]
Hello @lukehedger,

This is what I did to set up PR previews:

1. Connect a github repo (`main` branch) to Amplify Console
2. Enable PR previews in Amplify Console using the **Previews** tab under **App settings** (_This will install an app in Github if you have not already installed_)
3. Make a PR from `develop` to `main` in the Github repo
4. Verify that a PR build is triggered
5. Verify all checks have passed in Github PR:

![image](https://user-images.githubusercontent.com/5371802/88069662-a2dfe780-cb26-11ea-8531-1418156d1b1d.png)

6. Load the PR link successfully

In your case, I can see the same PR branches for 2 different amplify apps you have mentioned above. These two apps are under 2 different accounts, but under the same org. Looks like the PR preview Amplify app is connected to `du8ludhgzm5xn`, in addition to `d9slrnc36kbq7`. Could you verify that? And if that's the case, disconnect from one of them.

**Comment by lukehedger** [comment]
Ah thanks @abhi7cr - that was exactly the problem: the PR preview was enabled for two apps on the same repo.

**Comment by ryosukemitake** [comment]
I have the same problem currently on the region , ap-northeast1.
