### ISSUE TITLE
Getting an error - [ERR_SSL_PROTOCOL_ERROR]

### ISSUE THREAD

**Issue by vkd225** [aws-amplify/amplify-console#863]
**App Id**: d3h0tp4u7ql62r
**Region**: us-east-1
**Step**: Copied required CNAMES from route53 to google domains
**Status**: Added the domain and created an ssl certificate

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
```
www.vikash.dev sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
I added my domain and subdomain in my amplify-app but domain is not routing to the amplify app. 
It did route once but when I added the subdomain, it stopped routing and is giving me the above error.

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by abhi7cr** [comment]
Hello @vkd225, are you still facing the issue? Looks like www.vikash.dev is loading.
