### ISSUE TITLE
GitHub dependency in node modules not updating

### ISSUE THREAD

**Issue by joshkadis** [aws-amplify/amplify-console#866]
This was tricky to reproduce because I can't control the cache of `node_modules` used in the build stage but here's what I'm seeing when deploying a static site generated with Hugo.

1. My Amplify app includes a dependency on a GitHub repo, e.g. `{ "my-dep": "github:my-username/my-dep" }`
1. During the frontend prebuild phase of a deployment, a script creates a file using `my-dep` but there's a bug
1. I fix the bug in `my-dep`, test locally, all good
1. Push `my-dep` up to GitHub with a new commit for the bug fix.
1. In my Amplify app, I commit my updated `package-lock.json`
    1. `my-dep.version` has the hash of the new commit, looks good so far
1. Push and redeploy my Amplify app
1. The file created during the frontend prebuild still shows the bug that I just fixed in `my-dep`

**Comment by abhi7cr** [comment]
Hi @joshkadis,

Can you give your appId and region?

**Comment by joshkadis** [comment]
`ddl6a0e4xtrwe`, us-west-2

Thanks!

**Comment by abhi7cr** [comment]
Hi @joshkadis,

Just to narrow down the problem, could you try to remove `node_modules/**/*` from the `cache.paths` section of `amplify.yml` and redeploy?

**Comment by joshkadis** [comment]
Just did this and redeployed as the `update-deployments` branch

**Comment by joshkadis** [comment]
(sorry that took a while)

**Comment by swaminator** [comment]
@joshkadis were you able to get this resolved?
