### ISSUE TITLE
Add domain button throws error

### ISSUE THREAD

**Issue by dismantl** [aws-amplify/amplify-console#867]
**Please fill out all fields before submitting**

1. **Issue Description**
When I go to Domain management for a newly created app, then click on the "Add domain" button, the menu fails to appear and my browser console shows the following error: `main.js:81 Uncaught TypeError: Cannot read property 'branchName' of undefined`. This happens in an incognito window too, without any Chrome extensions enabled.

<img width="1379" alt="Screen Shot 2020-07-16 at 14 27 34" src="https://user-images.githubusercontent.com/2007008/87708493-d90d1800-c770-11ea-87a0-6a1f6754cd19.png">

FWIW I had previously had an Amplify app that was connected to a custom domain name, but I had already deleted that.

1. **Detailed Steps To Reproduce**
- Open app in Amplify console.
- Go to Domain management
- Click on the "Add domain" button.

1. **Copy and Paste Logs + Error Messages (remove sensitive data)**
```
main.js:81 Uncaught TypeError: Cannot read property 'branchName' of undefined
    at Function.g [as mapToProps] (main.js:81)
    at r (main.js:81)
    at Function.r.mapToProps (main.js:81)
    at r (main.js:81)
    at i (main.js:102)
    at main.js:102
    at Object.run (main.js:81)
    at d.initSelector (main.js:81)
    at new Connect(n) (main.js:81)
    at d._constructComponentWithoutOwner (main.js:102)
```

1. **Expected behavior**
I would expect to see a menu allowing me to connect a new domain name.

1. **Application Details**

    a. Please share your Amplify Console AppID, found in `App settings > General > App ARN` (e.g. `arn:aws:amplify:us-west-2:XXXXXXXXXXX:apps/APPID`) arn:aws:amplify:us-east-1:229923866965:apps/d1813okvnnfax
    
    __If the issue is related to a build, please also share:__
    
    b. The specific Branch and Build number we should investigate
    
    c. Your buildspec (*the version at the time the issue occurred*), [either from the Amplify console or amplify.yml](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html) (Be sure to remove any sensitive data)

1. **Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by ragzor** [comment]
+1 I'm getting the exact same error

**Comment by abhi7cr** [comment]
Hi @dismantl,

It looks like there is no branch connected to the app (d1813okvnnfax). Can you confirm if you have a branch for that app?

**Comment by dismantl** [comment]
@abhi7cr No, there is not currently any repo connected to the app.

**Comment by ganipcanot** [comment]
@dismantl This is the result of no branches being connected to the app.  We are currently working on a change that will give a more helpful message to users.

**Comment by ganipcanot** [comment]
This should be deployed in us-east-1 now, closing ticket for now let us know if you have any other issues!
