### ISSUE TITLE
All script imports suddenly fail for Amplify App due to Content Security Policy.

### ISSUE THREAD

**Issue by eric-feng-2011** [aws-amplify/amplify-console#871]
On Friday, I was able to successfully import React into my website using the command
```
<script src="https://unpkg.com/react@16/umd/react.development.js
```
Now the imports suddenly fail due to CSP issues.

**Comment by abhi7cr** [comment]
Hello @eric-feng-2011,

Can you share the appId and region ?

**Comment by eric-feng-2011** [comment]
Hi @abhi7cr,

Thanks for the prompt response! I restarted the project, and now the imports are working again. Still not sure why the issue popped up in the first place, but I'll reopen this issue if this situation happens again.

Thanks again!

**Comment by eric-feng-2011** [comment]
Hi @abhi7cr,

Thanks for the prompt response! I restarted the project, and now the imports are working again. Still not sure why the issue popped up in the first place, but I'll reopen this issue if this situation happens again.

Thanks again!

**Comment by abhi7cr** [comment]
I'm able to load the signin.html file for the above appId. It says: "No Cognito User Pool Configured".  Can you share a screenshot of the CSP error ?

**Comment by eric-feng-2011** [comment]
<img width="896" alt="Screen Shot 2020-07-19 at 9 17 59 PM" src="https://user-images.githubusercontent.com/31462296/87893383-551f8e00-ca05-11ea-9038-5809c1bbdfb9.png">

**Comment by abhi7cr** [comment]
Is this the URL: https://master.d31o1w426zemin.amplifyapp.com/signin.html ? I'm able to load the page without any errors. Could you do a hard refresh (Ctrl + F5) in your browser?

**Comment by eric-feng-2011** [comment]
Yeah. Mb, I should have been more clear. The page technically loads without issue, but in the web developer console, it shows that the page has errors importing various extra files such as the css files and jquery.

**Comment by abhi7cr** [comment]
Hi @eric-feng-2011, This is what I'm seeing when I load the Url (_I have highlighted the files which are causing CSP issues when you load; was able to load them with 200 response_). Could you try in a different browser to eliminate possible cache issues?

![image](https://user-images.githubusercontent.com/5371802/87894958-17b50380-c9f9-11ea-831f-a6d0b83264f8.png)

**Comment by eric-feng-2011** [comment]
Great - that resolved it! It must have been a cache issue. Thanks!
