### ISSUE TITLE
status avaible but not working

### ISSUE THREAD

**Issue by danielgonvie** [aws-amplify/amplify-console#883]
**App Id**: d39ju8p7sk2z36
**Region**: eu-west-3
**Step**: Last step
**Status**: avaible

**Issue/question**
I linked a custom domain from arsys.com but when i go to that domain it returns ERR_CONNECTION_TIMED_OUT. It shows avaible in the dashboard and completed all the steps succesfully.

**Additional information**
([url](url
![screenshot](https://user-images.githubusercontent.com/46381054/88227553-12acba00-cc6e-11ea-87ef-cedde6ee756f.JPG)
))

**Comment by ganipcanot** [comment]
I see `danielgonvie.com` associated to that appId and it looks like the site is loading.  Are you still experiencing issues?

**Comment by danielgonvie** [comment]
I changed the domain from Arsys to Route 53 and it worked at the first time. 
Seems like Arsys does not support ANAME or ALIAS field for DNS.
Solved.
