### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by kleingtm** [aws-amplify/amplify-console#885]
**App Id**: d2lm9slcimgfmd
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by ganipcanot** [comment]
I see a domain `incitery.com` which seems to load and is sitting behind basic auth.  Are you still having issues?

**Comment by ganipcanot** [comment]
Resolving due to age - re-open if you are still facing the issue!
