### ISSUE TITLE
Add GitHub branch next button greyed out (Unauthorized)

### ISSUE THREAD

**Issue by athewsey** [aws-amplify/amplify-console#887]
Possibly related to #446 - but all the discussion there is relating to GitLab specifically, and seems like this might be a different underlying cause.

I'm migrating an Amplify app from a personal fork (where it was initialized) up to a shared team repository - of which I am still the owner (and a co-owner of the org in which it lives).

Aiming to minimize disruption, I followed [this tip](https://github.com/aws-amplify/amplify-console/issues/288#issuecomment-661658770) to edit the *existing* app's repository to point to the shared one. I followed the resolution from #270 - making sure my Amplify OAuth app is granted access to the GitHub organization.

The change seems to have worked OK at first: Pushing a commit to the team repo on a branch I previously had set up on my personal repo (e.g. `develop`) triggers a build & deploy to the same Cloud environments as I previously set up.

**However**: Now I want to connect additional branches (e.g. `master`) that were not set up before. When I click the `Connect branch` button, the "Add repository branch" form doesn't populate fully (just says "Repository service provider: GitHub"). Looking in the browser console, I see an error:

```
Unhandled promise rejection Unauthorized
```

The "Next" button is orange at first, but if I click it it greys out and nothing happens.

I assume from the console error this is some kind of GitHub access permission issue? But as said above:

- I'm the owner of both the personal and the team repo
- I'm an owner of the org
- I've granted the Amplify GitHub OAuth App access to the organization

...So not sure what more I could do? Is it just a misconfiguration that Amplify can't deal with non-personal GitHub repos?

**Comment by ganipcanot** [comment]
Could you share your `appId` and `region` please?

**Comment by athewsey** [comment]
Ah, it was `d23jme8p9emnil` on `us-east-1` but I see now today that exactly the same flow works! Must have been a temporary issue
