### ISSUE TITLE
Liquid-C Not Installed

### ISSUE THREAD

**Issue by eyrobinson86** [aws-amplify/amplify-console#888]
**App Id**: None Yet
**Region**: us-east-1
**Step**: Building
**Status**: Unable to build app using Jekyll

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am receiving an error when I try to build the app. 

Liquid-c is notated in my gemfile.lock, gemfile, and _config.yml file.

**Error message**
Yikes! It looks like you don't have liquid-c or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the liquid-c gem in your Gemfile as well. The full error message from Ruby is: 'cannot load such file -- liquid-c' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!

**Comment by garyleefight** [comment]
@eyrobinson86. Thanks for the report. You can append the install command in prebuild section in buildspec.yml. We will consider add the dependency in our default image in the future.
