### ISSUE TITLE
Blank site after deploy and edit redirections rules

### ISSUE THREAD

**Issue by rimander123** [aws-amplify/amplify-console#889]
**App Id**: d3v46zijub9ubi
**Framework**: React

**Issue/question**
Blank site after deploy and edit redirections rules. (not happening on local server)
[master_site](https://master.d3v46zijub9ubi.amplifyapp.com/)

**Redirection Rules**:
![image](https://user-images.githubusercontent.com/56933781/88288883-9d62d880-ccb1-11ea-8d6b-85fb01f6f50c.png)

**Error message**
Console Error message:
![image](https://user-images.githubusercontent.com/56933781/88288425-fb42f080-ccb0-11ea-9104-5ec91a77b5c2.png)

**Additional information**
First i merged my code into master and after the auto deploy, i tested my web, noticed that i was always redirected to /index.html, then i edited redirection rules, i removed this rule:  /<*> to /index.html (redirect 404), then added /<*> to /index.html (rewrite 404), after this i checked [master_site](https://master.d3v46zijub9ubi.amplifyapp.com/) and notice that images resources where missing, i reverted mi code and waitted for the auto deploy, after that i always get a blank screen, even after reverting my code and the redirection rules.

**Comment by rimander123** [comment]
im still looking for the issue, so i reverted my branch code to alpha stage and deploy it to check, seems that the problems was when i added and removed redirect rules, even removing the redirection rules doesn't take effect, so the site can be shown because the [manifest.json](https://alpha.d3v46zijub9ubi.amplifyapp.com/manifest.json) file cant be loaded properly because of an old redirection rule that has already be removed

![image](https://user-images.githubusercontent.com/56933781/88420928-e3e52f80-cda4-11ea-8ecb-11242a818437.png)

**Comment by rimander123** [comment]
so finally i have found a way to reset the rules, is kind of tricky, but first things first.

adding this rule:
`<*> /index.html 200 (Rewrite)`

when i added this rule and then proceed to my page, all the files redirecto to index included json/img/etc requests.
this caused that the react script wasnt loaded properly, after that even when i removed the rule, the redirection rule was keep it and every file request got stuck on index

added diferent rules but no luck, until i realice that adding a redirection, load page and then remove it fixed manifest.json request.

fix /manifest.json request
* add `<*> /manifest.json  302(Redirect Temporary)`
* load page/manifest.json and see the json file correctly
* remove rule `<*> /manifest.json  302(Redirect Temporary)`
* load page/manifest.json and see the json  to confirm that this request remained fixed

then i loaded my page and realice that manifest.json are loaded successfully but images and js files got stuck aswell so i checked all my requests and redo the past steps with the other files aswell.
![image](https://user-images.githubusercontent.com/56933781/88432024-ae4a4180-cdb8-11ea-9bbf-2318047e84c6.png)

this paths where affected page/static/css/ , page/static/js/ , page/static/media/
so i redo the following steps with all that paths
* add `page/static/css/<*> page/static/css/<*>  302(Redirect Temporary)`
* load page go to Inspect element and check the request beign looped by the redirection until the page fails loading
* remove rule `page/static/css/<*> page/static/css/<*>  302(Redirect Temporary)`
* load page and check the requests now they should load correctly

then i checked the suggested rule for single web app on amplify documentation and after add this i was able to route correctly my app
`</^[^.]+$\|\.(?!(css\|gif\|ico\|jpg\|js\|png\|txt\|svg\|woff\|ttf\|map\|json)$)([^.]+$)/>   /index.html   200 (Rewrite)`

However the bug here is that not all the redirection rules can be removed, i assume that this may be related to internal aws route tables.

**Comment by litwicki** [comment]
@rimander123 Was there anything else you needed help with?

**Comment by hsspain** [comment]
Closing this ticket. Please let us know if you need further assistance.
