### ISSUE TITLE
Offer SPA redirects as a default preset

### ISSUE THREAD

**Issue by swaminator** [aws-amplify/amplify-console#89]
Posting on behalf of a customer on Twitter: https://twitter.com/erycbett/status/1163513471293485056

To set up SPA redirects require entering regex in the UI. It would be useful to have a preset selection that applies the settings automatically.

**Comment by adamaltman** [comment]
Another thing that would be useful is allowing the definition in the `amplify.yml` config file.  It's easier for developers to take care of it that way and more transparent (like with security headers).

We've forgotten to do it on our three most recent projects out of the gate.

**Comment by swaminator** [comment]
@adamaltman we are tracking that here: https://github.com/aws-amplify/amplify-console/issues/18

**Comment by kahdojay** [comment]
We've added a feature whereby Amplify Console will automatically add the [SPA redirects](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa) for React, Angular, Vue, Vuepress, or Gatsby. It should reach all regions by the end of the week.
