### ISSUE TITLE
SSL verification is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by anthonycmain** [aws-amplify/amplify-console#894]
**App Id**: df53bmrf7e6ui
**Region**: eu-west-2
**Step**: SSL verification
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Verification fails but without any guidance as to why

https://hecoira.thedistance.co.uk

I believe the CNAMES are set up correctly, I cant find anywhere to check what they should be though

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by garyleefight** [comment]
Hi, if you are not using route53 as domain provider. You have to copy the ssl cname certs to your domain provider.

**Comment by anthonycmain** [comment]
This was done, but I can't confirm as the cknse doesn't display them it
just displays an erroe

**Comment by anthonycmain** [comment]
There has been no resolution to this issue yet? I have no details to fix it in the console?

**Comment by garyleefight** [comment]
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html

**Comment by anthonycmain** [comment]
I've been through this but not getting anywhere as the console doesn't advise me what exactly is wrong. See the attached.

![Screenshot 2020-08-17 at 09 52 38](https://user-images.githubusercontent.com/950131/90377570-10246100-e070-11ea-9ac9-fde769b23692.png)

**Comment by sbaden** [comment]
What if you're using Route 53 and it's still not working? Mine errors on SSL configuration.

**Comment by ganipcanot** [comment]
Looks like the domain associated with this appId `df53bmrf7e6ui` is up and running.  Resolving this ticket for now.

**If you are still experiencing issues you can try following these steps:**

- Is this domain connected to a different Amplify App that you own? If so, make sure you are not trying to reuse one of the hostnames.
- If you are using www.domain.com on the other app, you cannot use www.domain.com on this app
- You can use other hostnames, like blog.domain.com
- If you had this domain successfully connected to Amplify and then recently (within the last hour) deleted it, please wait and try again.
- Check the Cloudfront console to see if you have this domain deployed to any distributions
- If you are positive no CloudFront distribution exists (including in other accounts) using this domain, and only if it would not be disruptive to any currently running services, try deleting and recreating the hosted zone
