### ISSUE TITLE
Hugo deployment succeeds on AWS Amplify but results in access denied XML file?

### ISSUE THREAD

**Issue by IveGotNorto** [aws-amplify/amplify-console#895]
** Please describe which feature you have a question about? **
Hugo deployment succeeds on AWS Amplify but results in access denied xml file?

** Provide additional details**
I'm using a custom docker image ([see here](https://hub.docker.com/r/woodfordb/hugo-amplify/tags)) to deploy my Hugo application. I had to create this to support the extended Hugo version that I'm using for my website. Once the website is built I go to the generated link and see an access denied template.

The provision, build, test and deploy all pass on the amplify web interface. To the eye, the output of all steps looks correct.
The only route-redirect is the default that has been loaded with the creation of the project.

**Comment by ganipcanot** [comment]
Could you share your `appId` and `region` so we can further investigate the issue?

**Comment by IveGotNorto** [comment]
@ganipcanot I just pulled down a simple Hugo application with the same result. Here is the 
- ARN: arn:aws:amplify:us-east-2:676262005434:apps/d24u8c05e1s7q0
- Region: US-East (Ohio)

**Comment by garyleefight** [comment]
Amplify is trying to search index.html in your build artifacts. Looks like your build artifact doesn't contain index.html. Besides, we only support static website hosting for now. Looks like the example you are using is trying to start a server. 
https://github.com/gohugoio/hugoBasicExample

**Comment by garyleefight** [comment]
https://github.com/swaminator/hugo-example This is an example for hugo
