### ISSUE TITLE
Issue with Access control in AWS Amplify Console

### ISSUE THREAD

**Issue by jhonangelmireles** [aws-amplify/amplify-console#896]
** Please describe which feature you have a question about? **
Access Control in the AWS Amplify Console seems to be broken

** Provide additional details**
1.- Access control passwords were configured previously for existing GitHub master and dev branches (No global password)  Result: OK
2.- Updated the master branch to "Publicly viewable" Result: No OK
      Other attempts:
-  Even after re-deploying the master branch the password was not removed.
- Enabling a Global password, then disabling it and then setting "Publicly viewable" to the master branch and "Restricted - password required" for the dev one. Didn't work either. 
- The documentation does not clarify if it takes a particular amount of time to update such passwords. https://docs.aws.amazon.com/amplify/latest/userguide/access-control.html

PD: Issue seem to be related to https://github.com/aws-amplify/amplify-console/issues/171 but such issue is closed. So I opened this one.

**Comment by garyleefight** [comment]
Hi @jhonangelmireles. So basically the issue is you can't disable the access control right now. Can you share the appId and region with us. We will investigate your issue.

**Comment by spdiamstu** [comment]
I have this same issue. Enabled password and when I remove it still enforces it.

**Comment by sriramreddyrao** [comment]
I am still facing this issue. Even after changing the branch access to "publicly viewable", username & password is being enforced.

**Comment by sriramreddyrao** [comment]
@spdiamstu If you are using Next.js - SSR framework, rebuilding should work.

**Comment by mawhtin** [comment]
+1 This issue is back. Any fixes?
