### ISSUE TITLE
How to implement a temporary landing page? (and more)

### ISSUE THREAD

**Issue by ernestostifano** [aws-amplify/amplify-console#897]
Hi everyone!

I was wondering if there is a way to setup a temporary landing page in an Amplify project without having to create a new Amplify project and/or manually modify DNS records.

### Use Case
My first Amplify project started with a temporary landing page repository (like those static pages you see when a server is going under maintenance). This was the master branch. Then, the real website started growing on a development branch. Both branches were connected to the Amplify console. The master branch with the static temporary landing page was available through the root domain (EX: domain.com) and the development branch was reachable through a protected subdomain (EX: dev.domain.com).

Everything looked great! The idea was to eventually rebase the development branch onto the production one (master), to make the real website publicly available and to keep the static temporary page on a new different branch to be used in the future whenever it could be needed. Here everything started to go down an ugly path.

- To keep two totally different branches in a repository (one for the website and one for the static temporary landing page) was not ideal.
- To create a new Amplify App for the landing page (eventually in a different repository) was also not ideal (DNS records would have to be managed manually because otherwise there would be domain conflicts between the two apps). Using redirects would require to have the static landing page available under some other domain/sub-domain.

### Questioning Monorepo Support
I found the new added support for monorepos, but it still makes little sense to me. What is the idea of supporting monorepos if then the Amplify console will manage only one package at a time, like if it was a normal repository? I though it would have addressed issues like https://github.com/aws-amplify/amplify-js/discussions/5724 or my current issue. Wouldn't be the ideal monorepo support to have a single Amplify directory in the root of the repository (a single backend) and make each package a different frontend sharing that single backend?

**It is insane and unnecessary to have an amplify project (`amplify init/pull`) inside each package. When you have a monorepo, usually you have all the development tools setup in the mororepo root (that is part of the whole monorepo idea). You have to constantly change the current working directory to execute Amplify commands on each package and your other monorepo commands/scripts.**

Please, please think about this.

**Comment by swaminator** [comment]
@ernestostifano sorry for the late response. Couple of points: 

1. What was the problem with keeping two totally different branches in a single repository?
2. To share the same backend across amplify apps: https://gist.github.com/swaminator/6270806f38048552af9ce699a568a581
