### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by khelawan** [aws-amplify/amplify-console#899]
**App Id**: d2rvnbbpk8cw8c
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by garyleefight** [comment]
Hi! Looks like you attached the domains to another app (dm87yvma0atbm) in us-east-1. Please delete that one first and retry.
