### ISSUE TITLE
Improve deployment times for large sites

### ISSUE THREAD

**Issue by swaminator** [aws-amplify/amplify-console#90]
REF: https://twitter.com/jonlowforever/status/1166902193993084930

On a site with 5000 pages Amplify build speed is really fast (much faster than Netlify/Render etc). However uploads are quite slow in comparison (13 mins to upload 10,000 static files total). Is there anyway to config static file uploading to be faster? To give you guys some context, it's a @gatsbyjs site with almost 5000 pages, so it generates nearly 10K static files. Total deploy time is around 25 mins on Amplify, but file uploading/processing is more than half of this.

**Comment by jonlow** [comment]
As a comparison, on Render, the uploads only took 3 mins (vs 13 mins). My guess is the difference in speed has to do with what "processing" is happening during upload. Perhaps Render simply upload the files blindly without any processing in place? 

I've spoken to engineers at Netlify (who have a similar issue with deployment times on large sites), and they were able to list some processing tasks that happened during uploads (checking for forms, checking mixed http/s content). 

I'm assuming that amplify has similar processing tasks. Ideally, anything that slows down uploads should be configurable, so the user can chose what features they want to ignore for faster deployments.

**Comment by swaminator** [comment]
@jonlow we redesigned our deployment service to be much faster. Closing this issue.
