### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by abeandre** [aws-amplify/amplify-console#901]
**App Id**: d3g7w66oil1mif
**Region**: ca-central-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
It wasn't able to validate the domain because of the CNAME.
I had configured it before. So I was trying to use Route53 to do some tests. I deleted the domain I had set and when I try to recreate it the issue starts to say I have a CloudFront set. Because I cannot see anything on CloudFront (because it was created automatically by the Amplify, I guess) I cannot manually delete it to make the setup.

**Error message**
One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Comment by garyleefight** [comment]
Didn't see your cname attached to any distribution. Can you simply retry?

**Comment by abeandre** [comment]
Sorry but I try to retry and still have the problem. I cannot see in any
place on AWS the old setup so I can remove it. There is anything I can do?
