### ISSUE TITLE
can't deploy my app with the aws-amplify console

### ISSUE THREAD

**Issue by yehonadav** [aws-amplify/amplify-console#902]
i suddenly start getting this error in the build stage, after cloning
![image](https://user-images.githubusercontent.com/35917238/88514188-4a12c200-cff2-11ea-932e-fb9614e7f7ec.png)
can't figure out how to fix this

**Comment by garyleefight** [comment]
Can you give us more info about your apps. Such as app arn(which can be found on app settings) and the region?

**Comment by yehonadav** [comment]
i succeeded in deploying by removing the backend environment
not sure about its purpose when deploying using github webhook
the console force you to choose or create a backend but i think its not configured.
hope this might help others =)
