### ISSUE TITLE
Domain activation is Failed - CNAMEs already associated with a different resource

### ISSUE THREAD

**Issue by dijekstra** [aws-amplify/amplify-console#906]
**App Id**: d38cb4ecs85p06
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
I am trying to add domain rockpaperscissors.ai to the amplify app. I have removed previsou CNAME entries from the domain. Domain is hosted on DynaDot. However, when I click the **Retry** button, nothing happens.

Please note that the I previously had created an SSL certificate for rockpaperscissors.ai on CloudFront distribution E1VHJNZLNXB05C

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**
![image](https://user-images.githubusercontent.com/10850831/88622773-f5884900-d0bc-11ea-9b68-bc26166d9b02.png)

**Comment by garyleefight** [comment]
Hi, this error means you have attached the domain or sub domains to another distribution. 
You have to first detach the conflict domains under your personal account(or exclude root domain in Amplify console).

The distribution id is E1VHJNZLNXB05C and the account id is 63xxxxxx92
