### ISSUE TITLE
SSL verification is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by skinofstars** [aws-amplify/amplify-console#907]
**App Id**: d2midqolhewr3o
**Region**: eu-central-1
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by garyleefight** [comment]
Hi, Cloudfront needs to verify you are they owner for the domain. So you have to ensure the ACM SSL certs generated by Amplify console(a CNAME records) is either in your route53 hostzone or pasted to your domain provider.

**Comment by skinofstars** [comment]
@garyleefight Thanks. We're using route53. This has worked automatically for three other Amplify projects. Just this one is stuck.

**Comment by skinofstars** [comment]
Sorry, I address your response. Two CNAMEs have been created, one for the sub-domain to the Cloudfront dist, and another for ACM validation.

I've tried tracing through to see if I can find the cert attached to the Cloudfront dist, but I've just found that weirdly Amplify dists aren't listed in Cloudfront. Is that intentional? Is there a way to enable that?

**Comment by garyleefight** [comment]
Hi, checked once again. Looks like your cname is deploying to Cloudfront distribution now. Amplify managed Cloudfront distribution on behalf of you. So you won't be able to see it now.

**Comment by skinofstars** [comment]
I have removed and readded the custom domain. It now works, so I will close this issue.

That said, I'm still curious as to why the Amplify Cloudfront distributions aren't showing up in the Cloudfront console. Any ideas appreciated. Thanks.
