### ISSUE TITLE
Master branch won't build after develop branch builds successfully

### ISSUE THREAD

**Issue by simpson** [aws-amplify/amplify-console#909]
** Please describe which feature you have a question about? **
App ARN
arn:aws:amplify:us-east-1:252100588959:apps/d1327f1jszjder

** Provide additional details**
When we commit to our develop branch the build completes successfully, when we merge to master it doesn't build.
![Screen Shot 2020-07-28 at 6 52 05 PM](https://user-images.githubusercontent.com/1605737/88730167-7b2ee780-d103-11ea-8edd-207ebb396bce.png)

**Comment by garyleefight** [comment]
Can you share more details? Was the build trigger and failed or the build wasn't triggered? Thanks

**Comment by simpson** [comment]
@garyleefight Unsure as you can't actually click and access this group to see why it failed. I believe it is saying there is no change, which is goofy since you can see the develop branch successfully built and was then merged to master.
![Screen Shot 2020-07-29 at 7 26 58 PM](https://user-images.githubusercontent.com/1605737/88863786-a7189e80-d1d1-11ea-8222-a963b183453b.png)

**Comment by garyleefight** [comment]
Checked the log message. 
Cancelling build because no changes found for appRoot apps/designed-org
So looks like the build failed because we didn't detect any change under you mono repo root

**Comment by simpson** [comment]
That doesn't make any sense. Why would the develop branch work? Monorepo support is completely broken...

**Comment by kahdojay** [comment]
Hey @simpson just want to sanity check, when you diff the two most recent commits on master for that job, do you see expected changes? I know it's probably not this but just want to rule it out while we look into it.

**Comment by simpson** [comment]
@kahdojay Yes, we see the changes that have built on the staging branch successfully. Is it ok for me to add you to the repo?

**Comment by FaitAccompli** [comment]
Hi @simpson , @kahdojay  were you guys able to solve this issue? 

My problem currently is of that nature. I can deploy successfully to my develop branch but when I try to deploy on master it has a build issue on the frontend but this doesn't exist when building on my develop branch.

**Comment by simpson** [comment]
how many PRs do you have open?

**Comment by FaitAccompli** [comment]
Hi @simpson, I haven't opened any pull requests. I was just wondering if this a amplify console issue since I am not getting the frontend build error when I deploy on a different branch. Any nudge to the right direction would be of great help! 

![image](https://user-images.githubusercontent.com/15321518/111239039-4f7d5500-8633-11eb-8a41-1f2ae66d1831.png)

**Comment by victorccccc** [comment]
Hi, sorry for the inconvenience. We've updated Monorepo feature and you can specify `appRoot` via `AMPLIFY_MONOREPO_APP_ROOT` environment variable.  Your build should work as expected.

Docs for reference: https://docs.aws.amazon.com/amplify/latest/userguide/monorepo-configuration.html

Feel free to reopen this if issue persists. Thanks!
