### ISSUE TITLE
403 error on static css and images

### ISSUE THREAD

**Issue by awsGruher** [aws-amplify/amplify-console#910]
Hello,

** Please describe which feature you have a question about? **
I have created an Amplify application with plain JS through CloudFormation by connecting it to my private Git repository. My build commands are:

- npm install
- npm run build
- cp -r src/assets dist
- cp -r src/css dist

The last two commands copy my static assets and css into the build folder (dist). When I run the app locally using "npx serve dist" or "npm start", it works just fine. However, when I deploy the application through Amplify, I'm getting 403 errors on my css and assets files: "Failed to load resource: the server responded with a status of 403 ()."

** Provide additional details**
ARN: arn:aws:amplify:us-west-2:971684222125:apps/d175f7mxaylo6n
Region: us-west-2

Any assistance would be much appreciated!

**Comment by garyleefight** [comment]
https://d175f7mxaylo6n.amplifyapp.com/assets/wand.png I can access to your assets. Do you still have the issue?

**Comment by awsGruher** [comment]
![Screen Shot 2020-07-29 at 1 45 16 PM](https://user-images.githubusercontent.com/67933695/88851562-c566a600-d1a1-11ea-958e-72b866678da6.png)

Yeah I am still getting the 403 error. When I click on that link you sent, I am also getting a 404 error.

**Comment by garyleefight** [comment]
You need to remove the trailing slash. 
/assets/wand.png -> /assets/wand.png 
/assets/wand.png/ -> /assets/wand.png/index.html

**Comment by awsGruher** [comment]
Could you clarify that a little bit? I don't see any differences in the left and the right for that top example. Here is how I am referencing my images and css files:

![Screen Shot 2020-07-29 at 1 53 14 PM](https://user-images.githubusercontent.com/67933695/88852254-df54b880-d1a2-11ea-8e1d-d3bedbc74b38.png)

![Screen Shot 2020-07-29 at 1 54 08 PM](https://user-images.githubusercontent.com/67933695/88852336-fc898700-d1a2-11ea-92ef-6fbcdd9049f7.png)

**Comment by garyleefight** [comment]
https://master.d175f7mxaylo6n.amplifyapp.com/assets/wand.png

**Comment by garyleefight** [comment]
https://master.d175f7mxaylo6n.amplifyapp.com Looks good to me. I can see the wand image and fireball gif without issue

**Comment by awsGruher** [comment]
That is weird. I am on VPN but I tried without and I'm still getting that issue. This is what I see when I click on the wand.png link you sent.

![Screen Shot 2020-07-29 at 1 56 45 PM](https://user-images.githubusercontent.com/67933695/88852598-59853d00-d1a3-11ea-87a3-3a8cdf6eb2ac.png)

**Comment by awsGruher** [comment]
Able to see it on my phone... interesting

**Comment by garyleefight** [comment]
I'll mark it as a bug for now. Worth to dig more, thanks for the report

**Comment by awsGruher** [comment]
Thanks Gary! Appreciate the help

**Comment by awsGruher** [comment]
Okay slight update. I can see it on Safari both on and off VPN. Just can't with Chrome for some reason.

**Comment by awsGruher** [comment]
Firefox working as well
