### ISSUE TITLE
Build Not Being Triggered When Deploying Through CloudFormation

### ISSUE THREAD

**Issue by awsGruher** [aws-amplify/amplify-console#911]
Hello!

** Please describe which feature you have a question about? **
This is more of a general question. When I launch my Amplify app through CloudFormation, the build does not happen automatically. In the console, it says that my build is queued and to click the button if my app does not build within one minute. I have tried waiting and the app never builds. I would like this build to happen automatically when my app is created in CloudFormation. In my template, I have "EnableAutoBuild" in my branch but I believe that is just for repo updates. 

** Provide additional details**
ARN: varies (launching through CloudFormation)

I might be missing a property in CloudFormation but I cannot figure it out from the docs. Any help would be much appreciated!

**Comment by garyleefight** [comment]
You have to manually start the job or do a push to your Git Provider. Cloudformation only creates app/branch resources. 
EnableAutoBuild is just for repo updates. So you have to manually call api to start a new job.

**Comment by awsGruher** [comment]
Is this API available through the AWS SDK? I'd like to automate this ideally

**Comment by garyleefight** [comment]
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Amplify.html#startJob-property

**Comment by awsGruher** [comment]
Awesome. Thanks! That should get me there. Closing for now
