### ISSUE TITLE
Show commands executed in CI

### ISSUE THREAD

**Issue by tobiasfeil** [aws-amplify/amplify-console#913]
In Gitlab CI, you can see the commands being executed (aka each line of your build script), not just the output that these commands producs. They're highlighted in green.

As far as I'm aware, the Amplify console only shows the output of scripts. Would it be possible to show and highlight the input like in Gitlab? That would make it easier to understand what's going on.

**Comment by garyleefight** [comment]
Thanks for the feedback. I will add it to our backlogs
