### ISSUE TITLE
Backend environment details page missing categories: interactions and predictions

### ISSUE THREAD

**Issue by gsans** [aws-amplify/amplify-console#916]
**Is your feature request related to a problem? Please describe.**
I was looking into the backend environment details page and realised it was missing the interactions and predictions categories. These are the options shown currently

<img width="1210" alt="Screenshot 2020-07-30 at 15 30 05" src="https://user-images.githubusercontent.com/4660316/89037870-32f80b00-d337-11ea-8a29-87d7eedb3f76.png">

Categories: auth, api, storage, analytics and functions.

Currently missing: 
- Interactions 
- Predictions

**Describe the solution you'd like**
The missing categories should also appear.

**Additional context**
NA

**Comment by garyleefight** [comment]
Thanks for the report. Will add to our backlogs

**Comment by gsans** [comment]
Any reason why this issue has been closed?
