### ISSUE TITLE
Domain activation is Failed - Cannot add to Amplify Console

### ISSUE THREAD

**Issue by kewp** [aws-amplify/amplify-console#918]
**App Id**: d5q45l9aa0l9t
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Cannot add domain to amplify console under Domain Management.
I've added the domain to Route 53.
The CNAME and A records gets added automatically (so the Route 53 setup should be fine).
But since everything is automatic I can't do anything else except
delete the DNS records and try again (which didn't work).

Note: I do not have the domain under CloudFront, as suggested.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource. 

**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by kiat-huang** [comment]
Same problem for me.

**Comment by ganipcanot** [comment]
Some references:
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error
https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

These guides are helpful for getting started with custom domains, for existing domains there are number of steps that will need to be completed (as outlined in the docs above) depending on your current hosting and DNS providers.

A CNAME alias (mydomain.com, sub.mydomain.com) can only be associated with a single CloudFront distribution at a time, if you receive this error then the domain is already associated with another CF distribution (either within the same AWS account, or potentially in a different account) and must be disassociated from the previous distribution before the distribution created for you by Amplify Console will work, the docs help outline how to do this (and you may need to check more than one account if you or your organization owns multiple accounts)

Additionally, if you manage your domain through Route53, make sure to clean up any hosted zone CNAME or ALIAS records that point to the old distribution. After completing the above, I would remove the domain from Amplify Console and start the flow over.

- Is this domain connected to a different Amplify App that you own? If so, make sure you are not trying to reuse one of the hostnames.
- If you are using www.domain.com on the other app, you cannot use www.domain.com on this app
- You can use other hostnames, like blog.domain.com
- If you had this domain successfully connected to Amplify and then recently (within the last hour) deleted it, please wait and try again.
- Check the Cloudfront console to see if you have this domain deployed to any distributions
- If you are positive no CloudFront distribution exists (including in other accounts) using this domain, and only if it would not be disruptive to any currently running services, try deleting and recreating the hosted zone

**Comment by nimacks** [comment]
@kewp is this still an issue for you?

**Comment by kewp** [comment]
Hey @nimacks I can't tell, I opened this 3 months ago. I must have found a work-around. Can't even remember what I was doing... happy to close this unless @kiat-huang you have more details?
