### ISSUE TITLE
Access denied error (after rewrite added)

### ISSUE THREAD

**Issue by TCastelein** [aws-amplify/amplify-console#919]
I have the same issues as some other people. I am getting an Access Denied response:

```
 This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>*</RequestId>
<HostId>
*
</HostId>
</Error>
```

Before you ask. Yes i did add the rewrite rule proposed in https://github.com/aws-amplify/amplify-console/issues/822#issuecomment-654959795

**Comment by TCastelein** [comment]
Sorry little more information.
It is a Vue app made with Nuxt
Added github continuous deployment

**Comment by TCastelein** [comment]
So found the problem.. I had the wrong `baseDirectory` it was `/` but should be `dist` my bad!

**Comment by khushal87** [comment]
I am facing the same issue. Can you help? @TCastelein

**Comment by TCastelein** [comment]
@khushal87 
Check if you build `baseDirectory` is correct https://github.com/aws-amplify/amplify-console/issues/955#issuecomment-672161808

If problem still persists try https://github.com/aws-amplify/amplify-console/issues/822#issuecomment-654959795

**Comment by khushal87** [comment]
@TCastelein Thanks alot changing the build directory actually worked
I change it from _build_ to __build_ and it works like charm. Thanks :)
