### ISSUE TITLE
5 Custom Domain Limit

### ISSUE THREAD

**Issue by alexkates** [aws-amplify/amplify-console#927]
** Please describe which feature you have a question about? **
We have been trying to figure out a way to work around the hard limitation of 5 custom domains per Amplify app. It's been suggested to us that we simply connect a 2nd Amplify application to the same code repository. 

Is this really that straight forward? 
Is there any documentation on this?
Are there any downsides to doing something like this? 
How do builds and deploys across multiple apps?

Also, I was hoping you could share more details technically around the limit of 5. Is there some limitation in CloudFront that is causing Amplify to have this? The number seems a bit arbitrary and is a bit low to be a hard limit.

Thanks in advance!

** Provide additional details**
Related AWS Support Case: https://console.aws.amazon.com/support/home?region=us-east-2#/case/?displayId=7212456411&language=en

**Comment by kahdojay** [comment]
Hi @alexkates, if you connect a repo branch to two Amplify apps, pushes to the branch will then trigger a build in each app, so as long as the two apps have the same settings you should be able to treat them as the same, however only one of them would be able to receive traffic for the root domain. (You'll need to go through the custom domain setup for both, one with root and one without).

Unfortunately we can't share too many internal details on the limit but we will be making the limits more configurable (though we can't share a timeline yet).

Let me know if you aren't able to try the above.

**Comment by alexkates** [comment]
What if we don't intend on connect the same repo branch? Can we have 5 branches connected to app 1, and 5 different branches connected to app 2, using this soloy to bypass the 5 custom domain limit?

**Comment by hsspain** [comment]
@alexkates Yes, that will work.

**Comment by alexkates** [comment]
Thanks... I'll give that a shot.
