### ISSUE TITLE
Domain activation is Failed -Removed CNames in cloud front - Now website is throwing 403 Error

### ISSUE THREAD

**Issue by goalsdoor** [aws-amplify/amplify-console#928]
**App Id**: du6spkvi4zbcz
**Region**: ap-south-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
As per the new documentation , i have removed CNAME's since im getting domain activation failed error  
![image](https://user-images.githubusercontent.com/59289557/89313304-f52c1700-d695-11ea-9ddc-479716b02bf0.png)

**Error message**
1) Now website is not accessible, getting 403 error.  Before removing CNAMES it was working fine.
![image](https://user-images.githubusercontent.com/59289557/89312859-661eff00-d695-11ea-898d-a23f6b030ebe.png)

2) Still domain activation is failed in Amplify
![image](https://user-images.githubusercontent.com/59289557/89313515-358b9500-d696-11ea-8cec-567035f8023b.png)

**Additional information**
Pls suggest. thanks in advance

**Comment by AlanMauricioC** [comment]
did you delete the cnames in route 53 and in your cloudfront?

**Comment by kahdojay** [comment]
@goalsdoor just so I understand, are you migrating from an existing cloudfront distribution that you manage to Amplify Console?

Are you able to delete the custom domain, wait 15m and try again?

**Comment by jaivinodha** [comment]
> did you delete the cnames in route 53 and in your cloudfront?

I have deleted CNAME's only in Cloud front . did not remove in Route 53

**Comment by goalsdoor** [comment]
> did you delete the cnames in route 53 and in your cloudfront?

I have delete CNAME's only in cloudfront . Did not touch route 53

**Comment by AlanMauricioC** [comment]
you need to remove them from route 53, well the old CNAMEs that pointed to your old cloudfront project

**Comment by goalsdoor** [comment]
> you need to remove them from route 53, well, the old CNAMEs that pointed to your old cloudfront project

Its gives me a warning. is this normal ? shall i proceed deleting?
![image](https://user-images.githubusercontent.com/59289557/89323317-1e06d900-d6a3-11ea-9409-738978b655ed.png)

**Comment by AlanMauricioC** [comment]
yep, that's the normal, you can make this record again if you need

**Comment by goalsdoor** [comment]
> yep, that's the normal, you can make this record again if you need

Thank you. ill let you know the result in an hour :)

**Comment by goalsdoor** [comment]
Hi.. My site is still down.. throwing same error

**Comment by goalsdoor** [comment]
> @goalsdoor just so I understand, are you migrating from an existing cloudfront distribution that you manage to Amplify Console?
> 
> Are you able to delete the custom domain, wait 15m and try again?

Hi, sorry i have missed to see your comment.. yes you are right

**Comment by goalsdoor** [comment]
any updates ?

**Comment by AlanMauricioC** [comment]
Did you retried to get the domain activation? With the cnames of your old cloudfront deleted, and with out the rule 53 cnames?
Because it's supposed that if you don't have any cnames (addresses) in your route 53 that point to that route (domain,  subdomain), you should have a 404 as response, because there's no one pointing to that page

**Comment by AlanMauricioC** [comment]
> Did you retried to get the domain activation? With the cnames of your old cloudfront deleted, and with out the rule 53 cnames?
> Because it's supposed that if you don't have any cnames (addresses) in your route 53 that point to that route (domain,  subdomain), you should have a 404 as response, because there's no one pointing to that page 

And you need to wait like 10mins not one hour, at least that's how much time I wait to see changes

**Comment by goalsdoor** [comment]
Yes i tried activating the domain in AWS Amplify but its keep on failing, and my couldfront CNAME's are empty also i have deleted the CNAME record in route 53.
![image](https://user-images.githubusercontent.com/59289557/89499836-4cd59a00-d7de-11ea-8316-6ab1e4317518.png)

Its is Retry in progress status more than an hour and after that its getting failed 
Please look into it

**Comment by AlanMauricioC** [comment]
you also need to delete tose **A** routes that point to your cloudfront

> 
> 
> Yes i tried activating the domain in AWS Amplify but its keep on failing, and my couldfront CNAME's are empty also i have deleted the CNAME record in route 53.
> ![image](https://user-images.githubusercontent.com/59289557/89499836-4cd59a00-d7de-11ea-8316-6ab1e4317518.png)
> 
> Its Retry in progress status more than an hour and after that its getting failed
> Please look into it

**Comment by goalsdoor** [comment]
Even After deleting A records , im getting THIS SITE CANT BE REACHED error :(

**Comment by goalsdoor** [comment]
Issue Solved :
1) In the cloud front disable and delete your configuration. You do not need this
2) Delete your cloudfronts in you Route 53. You should have only **NS** and **SOA** types delete remaining stuffs
3) Delete the api your project using the command amplify remove api if you have any
4) Delete the amplify folder in your project
5) In the VS terminal , **amplify int** and followed by **amplify add api** if you have any and **amplify push**
6) Once your app is successful in amplify , it is automatically creating cloud front records in the Route 53. Now there will be of types **CNAME, NS, SOA, A, A** 
7) I believe you do not need any cloud front configuration for Amplify.
8) It has started working for me . Thanks :)
