### ISSUE TITLE
User controlled deploy when auto build is off

### ISSUE THREAD

**Issue by dmudro** [aws-amplify/amplify-console#929]
[Disabling automatic builds](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#disable-automatic-builds) is straight forward and it works:

![image](https://user-images.githubusercontent.com/1648143/89334647-21946300-d697-11ea-83f2-e10646ce7dd2.png)

The question is how to trigger the build process for such branches with auto-build off?

Typically I would like to keep manual control for production environment as opposed to relying on repo changes captured by Amplify Console and letting it push to prod automatically. I do that for feature and dev branches but not for master. 

I envision a _build now_ button which would do the same as auto deploy. The closest thing I've found is the _redeploy this version_ button in build history but that does not fetch latest git repo.

I understand the environments are tight to GitFlow and at the same time I do want to keep manual control over master to production.

**Comment by dmudro** [comment]
Answering my own question... I think the easiest way is to use [webhooks](https://docs.aws.amazon.com/amplify/latest/userguide/webhooks.html).

One can wrap a custom deploy script around the curl command etc.

**Comment by kahdojay** [comment]
Hi @dmudro that is correct, resolving this one for now, let us know if you have any issues getting that going
