### ISSUE TITLE
[anybody home?] Domain activation is Failed - Blocking redirect setup

### ISSUE THREAD

**Issue by jknapp25** [aws-amplify/amplify-console#931]
**App Id**: d4mj1ixh7pviq
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
My website with custom domain is up on AWS Amplify. I am now trying to configure my redirects so that I can route my SPA using Reach Router. The flavors of redirects I have tried without success are:

- 200 rewrite in ["Redirects for Single Page Web Apps (SPA)"](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html)
- previous original & target address w/ 302 Redirect permanent
- previous original & target address w/ 302 Redirect temporary
- previous original & target address w/ 404 Rewrite
- previous original & target address w/ 404 Redirect
- also tried each of the previous but placed above the OOTB custom domain -> www redirect

Amplify is telling me one or more of my CNAME's is already in use. And failing custom domain setup on stage 3: "Domain activation". This is confusing because like I mentioned above, my website is available at my custom domain and I can even push new changes that show up after CD.

Can someone help me troubleshoot this issue so that domain activation succeeds and I can configure my redirects properly?

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource. 

**Additional information**

Yes, I've clicked the "Retry" button a billion times.

<img width="1077" alt="Screen Shot 2020-08-04 at 7 56 51 PM" src="https://user-images.githubusercontent.com/3934326/89367129-2227fc00-d68d-11ea-8e31-1e887cf21546.png">

**Comment by kahdojay** [comment]
@jknapp25 thanks for reporting, we have an issue with the retry button (#512) so the only way to retry for now is to delete the custom domain, wait a few minutes and recreate.

Just making sure that the 200 rewrite you mentioned you tried was the 200 rewrite rule mentioned [under the section "Redirects for Single Page Web Apps (SPA)" in the docs](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa)?

Regardless, setting up redirects/rewrites is a different process than setting up the custom domain. It looks like you successfully setup www.yourdomain.com as well as the alias record to redirect your apex to www, it looks like something might have happened on our end that's causing that Domain Activation error to show so we'll investigate that. You can likely ignore the Domain Activation error or if it's not too disruptive, delete the custom domain, wait at least 10 minutes, and recreate it.

Let us know if the SPA rewrite suggestion above doesn't help.

**Comment by jknapp25** [comment]
I deleted custom domain, waited 30min, then re-added. Domain activation failed again.

**Comment by kahdojay** [comment]
@jknapp25 I just noticed you already have an Amplify app in us-east-2 using the domain which is what's causing the exception.

**Comment by jknapp25** [comment]
Really? I only see one app in the Amplify console...

**Comment by jknapp25** [comment]
@kahdojay are you still available to help on this issue?

**Comment by hsspain** [comment]
@jknapp25 I believe you may be looking in us-east-1, but the other Amplify app is in us-east-2.  Change your region and let us know if you see the app there.

**Comment by jknapp25** [comment]
YES!!! Removing the domain on the app located on us-east-2 worked! Thank you so much!

**Comment by jknapp25** [comment]
And now my client side routing is working as well!
