### ISSUE TITLE
Domain activation is Failed after deleting CloudFront CNAMEs

### ISSUE THREAD

**Issue by joshkadis** [aws-amplify/amplify-console#933]
**App Id**: ddl6a0e4xtrwe
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
My custom domain passes the SSL Creation and SSL Configuration steps and fails on the Domain Activation step. I've retried multiple times and continue to get this error message even after deleting CNAMEs in CloudFront, waiting 6 hours, and so on. 

**Error message**
_In the Amplify console_: Error message: One or more of the CNAMEs you provided are already associated with a different resource.

_In the browser_: This server could not prove that it is hackshackers.com; its security certificate is from *.cloudfront.net. 

**Additional information**
I have monkeyed around with branch settings for the custom domain to make sure that the domain is attached to `master` and making sure that `master` is the production branch in Amplify.

**Comment by joshkadis** [comment]
I deleted the custom domain in the Amplify console and started over. It's passed the SSL creation step and has been waiting on the SSL configuration step for a few hours but at least it hasn't failed yet. 🤷

**Comment by joshkadis** [comment]
Pointed DNS to Route53, which worked.

@litwicki Looking at the issues here, it seems like a lot of people are having similar issues to mine. Maybe it would be better just to require that any custom domain on Amplify be managed on Route53. That's my unsolicited opinion 😜

**Comment by sankojunagendra** [comment]
My question is related to the same topic. But can anyone please tell me the place where cName is stored when we deploy an application using github from amplify console.Because there are no distrbutions in my Cloudfront
