### ISSUE TITLE
SSL configuration is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by zeclorn** [aws-amplify/amplify-console#935]
**App Id**: d6c6zriy4dula
**Region**: us-east-1
**Step**: SSL configuration
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by ganipcanot** [comment]
Have you tried deleting and re-adding the domain?  Also have you gone through this troubleshooting guide? https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

**Comment by hsspain** [comment]
I am going to close out this issue.  If you are still having problems, feel free to reach out again.
