### ISSUE TITLE
Stuck in SSL configuration for couple of hours

### ISSUE THREAD

**Issue by icodeguru** [aws-amplify/amplify-console#937]
**App Id**: dbstekpan9z1y 
**Region**: us-east-1
**Step**:  Add new domain under domain management
**Status**:  stuck in SSL configuration

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Stuck in SSL configuration under domain management for a couple of hours

![image](https://user-images.githubusercontent.com/69017158/89489874-c70e1a80-d7ee-11ea-9d43-7442c389a28d.png)

**Comment by lightninglife** [comment]
Have exact issue!

App Id: d2ayv1nn47gnry
Region: us-east-1
Step: Add new domain under domain management
Status: stuck in SSL configuration

<img width="1228" alt="Screen Shot 2020-08-06 at 3 20 24 AM" src="https://user-images.githubusercontent.com/23303708/89502994-e9bf1580-d793-11ea-889c-af4a89065831.png">

**Comment by kahdojay** [comment]
Hi, if you're not using Route53 you need to configure your DNS settings since we don't have any ability to manage them for you. This is the SSL step where you need to setup the CNAME to prove domain ownership. Please see the docs for more details:

https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-a-third-party-dns-provider.html

**Comment by lightninglife** [comment]
Hi Don,

Thank you for your reply. But I purchased domain using Route53. It is still
stuck until now.

Best Regards,
Paul

**Comment by icodeguru** [comment]
I have purchased domain via Route53 and it is not 3rd party managed domain

**Comment by kahdojay** [comment]
ok, Route53 should have setup ns/soa records for you then and the ns record values should match the authoritative ns values shown in the registered domains page. Were any alterations made to the records or to the hosted zone? When I lookup ns records for codeguru.io it looks like it does not resolve in the US.

https://dnschecker.org/#NS/codeguru.io

If the Route53 hosted zone with proper ns records are in place for the domain, custom domain creation should work. (may have to delete and recreate to retry)

**Comment by icodeguru** [comment]
Thanks for the inputs mate. I have deleted hosted zone and created it and updated registered domain page with ns records in my hosted zone and that helped me pass ssl configuration stage; however, no I am stuck in domain activation stage. is there a way to know why it failed in domain activation stage on amplify console. The following the screenshot for the current issue I am facing similar to others 

<img width="963" alt="image" src="https://user-images.githubusercontent.com/69017158/89635426-4d5b5700-d8ea-11ea-830c-ebf6951683d3.png">

**Comment by icodeguru** [comment]
Thanks for the help mate I am closing this ticket since ssl configuration issue is resolved
