### ISSUE TITLE
Domain activation is Failed - Do not activate

### ISSUE THREAD

**Issue by joaovescudero** [aws-amplify/amplify-console#940]
**App Id**: djfapravcaapo
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
The domain didnt acitvate,

**Error message**
One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions 

**Additional information**
I've removed everything from route 53 and cloudfront.
I deleted an old amplify with the same cname, but its still online on the domain.

**Comment by nimacks** [comment]
@joaovescudero is this still an issue for you?

**Comment by brnmye** [comment]
We are going to close out this issue, but please feel free to re-open if you still need help.
