### ISSUE TITLE
Data got wiped out

### ISSUE THREAD

**Issue by Galaf** [aws-amplify/amplify-console#942]
** Please describe which feature you have a question about? **

This morning, I woke up to an empty Amplify.
My app still exists but all pages are empty and I get the "Connect to a repository" screen.

I don't want to go through the trouble of having to retry to configure build, configure domain, etc.
Whatever happened between yesterday and today, can you restore my configuration?

My app id is dj86un7jwa3et

**Comment by ganipcanot** [comment]
@Galaf Could you also share the region for your appId?  It looks like it's in `us-east-1` is that correct?

**Comment by ganipcanot** [comment]
I noticed that you have `enableBranchAutoDeletion` set to `true` for your application.

I also noticed that right now you have no branches attached to your application.

Did you recently delete any branches in your git repository?  If you did, that would have triggered that branch to be deleted in Amplify.

Here is the reference documentation for `enableBranchAutoDeletion`: https://docs.aws.amazon.com/amplify/latest/APIReference/API_App.html

**Comment by Galaf** [comment]
Ok... So I created a fake branch and it did came back right now.
Region is `us-east-1` indeed.
I usually close branches once I'm done reviewing them and they're good to go.

This morning, when I looked, the branch I wanted to review was not available so I got the "Get started" screen for some reason.
Maybe build failed for one reason or another and thus, it did not show anything?
Could you pull the logs and tell what happened, maybe?

Because of https://github.com/aws-amplify/amplify-console/issues/115 I tried to get the number of branches on Amplify as small as possible but maybe I should have `master` always on in order to avoid this issue. What's the recommendation here?

Thanks.

**Comment by ganipcanot** [comment]
You can adjust this (`enableBranchAutoDeletion`) setting here if you prefer to keep the branches around:

![image](https://user-images.githubusercontent.com/21091073/89672532-a949bf80-d899-11ea-9ce6-0bca2337718a.png)

**Comment by Galaf** [comment]
I didn't want to keep useless branches opened because of #115 
Next time, I'll try to redeploy to see if it changes anything.

I'll close that ticket.
Thanks for the help.
