### ISSUE TITLE
Build notifications support with AWS Chatbot

### ISSUE THREAD

**Issue by askulkarni2** [aws-amplify/amplify-console#943]
**Is your feature request related to a problem? Please describe.**
[AWS Chatbot](https://docs.aws.amazon.com/chatbot/latest/adminguide/related-services.html) offers a convenient way to publish build notifications to Slack from AWS Developer Tools, AWS CloudFormation and others and is an approved Slack application for our organization. However, it does not currently support Amplify builds. I see the following error in CloudWatch Logs.

```json
Event received is not supported (see https://docs.aws.amazon.com/chatbot/latest/adminguide/related-services.html ): 
{
    "subscribeUrl": null,
    "type": "Notification",
    "signatureVersion": "1",
    "signature": "fUiwL20YlWZBs1U81vvuAvvzUrQrF0xM2OtBg2UjDo3/YqCIpa/ZEBTMny8hla8Rr5z2SPWSep/W8Id2sSadcxhzFv3EsZ+uNQAfgextxLVr/d5kv5rtBSLI6iQAFbLxWyTVT+SzrTqPrAJF9BzNpM6cCH7h+cFA+aNzfKwLGlefBbzS+T/iwTc8Qt/CZWi3zTS+O86MCMLeaf0ezTQm5Q0ljt0DvGIz5qH/A1dZiGqqA8MuAphoY0r4QSnEQYGoLwMyJBclJNd/MWseIGxoFelOdoSnPvIQzlhUYua/8xVhKUTC3p1seXj6GpAedbzoVWPevmt7U/S2V6uOCthWUg==",
    "topicArn": "arn:aws:sns:us-west-2:XXXXXXXXXXXX:amplify-d1ywkiq91ymgkd_AMPLIBRANCHSENTINEL",
    "signingCertUrl": "https://sns.us-west-2.amazonaws.com/SimpleNotificationService-a86cb10b4e1f29c941702d737128f7b6.pem",
    "messageId": "01661a60-7a0a-511a-ab2a-4dc6be296397",
    "message": "Build notification from the AWS Amplify Console for app: https://master.d1ywkiq91ymgkd.amplifyapp.com/. Your build status is STARTED. Go to https://console.aws.amazon.com/amplify/home?region=us-west-2#d1ywkiq91ymgkd/master/19 to view details on your build. ",
    "subject": null,
    "unsubscribeUrl": "https://sns.us-west-2.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-west-2:XXXXXXXXXXXX:amplify-d1ywkiq91ymgkd_AMPLIBRANCHSENTINEL:***REDACTED***",
    "timestamp": "2020-08-07T02:52:19.481Z",
    "token": null
}
```

**Describe the solution you'd like**
Amplify already creates an SNS topic for pushing email notifications. The SNS topic could be used as a notification source for Chatbot as well once its supported.

**Comment by ganipcanot** [comment]
Thanks for the suggestion - I'll label this as a new feature request and get it into our backlog.

**Comment by lukehedger** [comment]
@ganipcanot Do you have a rough timeline of when this could be implemented? 🙏

**Comment by YOEL311** [comment]
Great feature
Is there an estimated time to add it?

**Comment by birsi** [comment]
👍 on this feature request. any updates here would be highly appreciated.

**Comment by VED-StuartMorris** [comment]
Also tried to implement the same and got to the exact same point.

**Comment by birsi** [comment]
Any plan to tackle this one this year? In the backlog since August 2020. Would be super awesome to get this feature <3 :)

**Comment by jimmyn** [comment]
Yes, I also really need this feature, AWS Chatbot notifications for codebuld are great!

**Comment by paulcookie** [comment]
joining the wait...

**Comment by jimmyn** [comment]
Maybe someone can share a workaround?

**Comment by swaminator** [comment]
Closing this in favor of #271.

**Comment by Derrickbowen** [comment]
I was able to set up an Event Grid rule that got this more or less working. I then added the Chatbot as a subscription to the SNS topic. The transformed event is able to be read by the chatbot, but it's not super pretty. If someone could find better documentation for what inputs the ChatBot looks for, this could be improved.

Event Pattern:
```
{
  "detail": {
    "appId": ["<<my amplify app id>>"],
    "jobStatus": ["SUCCEED", "FAILED", "STARTED"]
  },
  "detail-type": ["Amplify Deployment Status Change"],
  "source": ["aws.amplify"]
}
```

Target:
SNS Topic

Input Transformer:
```
{"account":"$.account","appId":"$.detail.appId","branch":"$.detail.branchName","detail-type":"$.detail-type","id":"$.id","jobId":"$.detail.jobId","region":"$.region","resources":"$.resources","source":"$.source","status":"$.detail.jobStatus","time":"$.time","version":"$.version"}
```

```
{
	"version": <version>,
	"id": <id>,
	"detail-type": "<status> build status from the AWS Amplify Console for app: https://<branch>.<appId>.amplifyapp.com/. Go to https://console.aws.amazon.com/amplify/home?region=<region>#<appId>/<branch>/<jobId> to view details on your build. ",
	"detail": "<status> build status from the AWS Amplify Console for app: https://<branch>.<appId>.amplifyapp.com/. Go to https://console.aws.amazon.com/amplify/home?region=<region>#<appId>/<branch>/<jobId> to view details on your build. ",
	"source": <source>,
	"account": <account>,
	"time": <time>,
	"region": <region>,
	"resources": <resources>
}
```
