### ISSUE TITLE
Recurring Custom Domain Creation Issue

### ISSUE THREAD

**Issue by lightninglife** [aws-amplify/amplify-console#946]
**App Id**: d2ayv1nn47gnry
**Region**: us-east-1
**Step**: Add new domain under domain management
**Status**: stuck in SSL configuration

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Stuck in SSL configuration under domain management for a couple of days

**Error message**

<img width="1257" alt="Screen Shot 2020-08-07 at 8 01 04 AM" src="https://user-images.githubusercontent.com/23303708/89643612-2a965780-d884-11ea-821e-3867956a4c52.png">

**Additional Information*
I purchased the domain name via Route53 and SOA and NS for domain name both were created correctly.

**Comment by ganipcanot** [comment]
Just as a starting point - I'm assuming you went through this? https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

**Comment by lightninglife** [comment]
> 
> 
> Just as a starting point - I'm assuming you went through this? https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

Yeap. I did go through almost all troubleshooting tips. It didn't work for me. I'm still stuck at SSL configuration currently.

**Comment by hsspain** [comment]
@lightninglife It looks like this domain is associated with another CloudFront distribution. Did you happen to have used it with another AWS service?
