### ISSUE TITLE
Build remains in Pending state since 5-6 hours

### ISSUE THREAD

**Issue by arvind1988** [aws-amplify/amplify-console#947]
Build remains in Pending state since hour.

**Comment by kahdojay** [comment]
@arvind1988 are you able to build locally? If you could fill in our [issue template](https://github.com/aws-amplify/amplify-console/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) if you believe there's a bug, it will help us investigate:

**Comment by arvind1988** [comment]
It got fixed automatically
