### ISSUE TITLE
Unable to get past "Provisioning" step for any Ohio application

### ISSUE THREAD

**Issue by nucat176** [aws-amplify/amplify-console#948]
<img width="611" alt="Screen Shot 2020-08-08 at 2 36 07 PM" src="https://user-images.githubusercontent.com/19193192/89718473-c357d080-d973-11ea-8e6d-f32f1475f111.png">

App ID: d2nrk2jnhh6rx0
Region: Ohio only (can deploy fine in Oregon)

What can I do to get past this? This is for a production app which needs to be updated ASAP.

**Comment by nucat176** [comment]
<img width="545" alt="Screen Shot 2020-08-08 at 5 11 30 PM" src="https://user-images.githubusercontent.com/19193192/89720665-88609780-d989-11ea-9c68-813ed406391c.png">

**Comment by nucat176** [comment]
I've attached another screenshot - not sure if it's relevant or not

**Comment by nhc-motosumo** [comment]
We had the same issue on our app (in the `eu-west-1` region). Our project build is stuck in Provisioning, and I can find no indications of what is going wrong. We contacted AWS Support, and they recommended we bring it here. App id is `dm197t2mo7xbv`. Please reach out if you need more details.

**Comment by kahdojay** [comment]
@nucat176 @nhc-motosumo I see your most recent builds/deploys were successful. Can you share the branch name and specific build number where your build got stuck on provisioning?

**Comment by nucat176** [comment]
@kahdojay thanks for the reply here. Our most recent builds on the affected apps are still failing. The branch name is "master" (although "staging" appears broken as well) and the most recent build number is 42

**Comment by nhc-motosumo** [comment]
> Can you share the branch name and specific build number where your build got stuck on provisioning?

Thanks for the response! For us, it is Build 13, in branch `develop`, of app `dm197t2mo7xbv`. I do not think we have seen a successful build for days (another branch seems affected by #936). Only an older `master` build was successful. There may be errors on our side, but I cannot figure out how to debug this.

**Comment by nucat176** [comment]
<img width="1753" alt="Screen Shot 2020-08-10 at 1 28 45 PM" src="https://user-images.githubusercontent.com/19193192/89817244-b0243c80-dafc-11ea-9a51-c1129a7e2d98.png">

**Comment by swaminator** [comment]
@nucat176 @nhc-motosumo we are looking into it with high priority.

**Comment by nucat176** [comment]
@swaminator great, thanks so much. Is it officially a bug on the AWS side?

**Comment by kahdojay** [comment]
@nucat176 Can you give it another try in us-east-2?

**Comment by nucat176** [comment]
@kahdojay no good on my end

**Comment by nucat176** [comment]
![Screen Shot 2020-08-10 at 5 59 04 PM](https://user-images.githubusercontent.com/19193192/89839384-6fd7b500-db22-11ea-83e3-1c9647e5a42b.png)

**Comment by kahdojay** [comment]
@nucat176 It looks like there was an issue with the verification / screenshot step for your app causing some builds to get stuck. We addressed the screenshot issue in us-east-2 but the stuck builds were causing you to reach the concurrent job limit. We've updated the status of those builds so your next attempt should go through, can you give it another try?

**Comment by nhc-motosumo** [comment]
Our builds seem to work now. Thanks for the investigation!

Question, though: If we ever hit the concurrency limit again, is there a way for us to see that, and maybe take action? E.g. effectively killing a stuck build?

**Comment by behrooziAWS** [comment]
@nhc-motosumo The concurrency limit is currently 6.  If you look at the screenshot nucat176 posted above, in the upper right there are arrows and a cancel button.  You should be able to navigate to the specific build and cancel.
