### ISSUE TITLE
Access Denied - This XML file does not appear to have any style information associated with it. The document tree is shown below

### ISSUE THREAD

**Issue by jaivinodha** [aws-amplify/amplify-console#955]
Error:
Access Denied - This XML file does not appear to have any style information associated with it. The document tree is shown below
![image](https://user-images.githubusercontent.com/69211611/89883152-65322400-dbe5-11ea-9501-db4576409d15.png)
![image](https://user-images.githubusercontent.com/69211611/89883162-695e4180-dbe5-11ea-8783-7a4e3c767311.png)

Source:
https://www.youtube.com/watch?v=DHLZAzdT44Y

**Comment by swaminator** [comment]
@jaivinodha can you see if your baseDirectory is set corretly: https://github.com/aws-amplify/amplify-console/issues/919#issuecomment-667543106

**Comment by jaivinodha** [comment]
I have solved this issue by changing the base directory in the build configuration. 
For React,
![image](https://user-images.githubusercontent.com/69211611/89933683-0d1f1000-dc2d-11ea-9275-160e920f47ee.png)

By default , baseDirectory: / , i changed it to baseDirectory: /build
then makes some changes in your project , do a commit in github 
The Amplify console will generate the build automatically  and your project will run without any errors 
You do not need to add any Redirects and Rewrites for this .

**Comment by jaivinodha** [comment]
> @jaivinodha can you see if your baseDirectory is set correctly: [#919 (comment)](https://github.com/aws-amplify/amplify-console/issues/919#issuecomment-667543106)

Thank you 👍
