### ISSUE TITLE
How can I disconnect repository of the existing app?

### ISSUE THREAD

**Issue by sanodo** [aws-amplify/amplify-console#956]
** Please describe which feature you have a question about? **
I'm trying to disconnect the current repository from the amplify project. No matter what I try it's still connected. The reason being I need to switch to manual deployment.

** Provide additional details**
Things I've tried
- remove hosting through the CLI
- remove branches manually through the console

We have a running API deployed so deleting the app and creating a new one isn't really an option

**Comment by behrooziAWS** [comment]
Did you try disconnect branch?

https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#disable-automatic-builds

**Comment by behrooziAWS** [comment]
I spoke with a teammate about this and understand the question better now.  There is currently no way to migrate to a manual build if you start an app with a repo.  The only workaround is to create a new app that is a manual build and consume the api in the existing app from your frontend if you can't migrate the api over.

**Comment by Stvad** [comment]
Is there an issue to track adding this?

**Comment by icozma** [comment]
> Is there an issue to track adding this?

It seems to work from console:   App settings: General   
Branches    then    Actions

**Comment by Stvad** [comment]
@icozma I only see "disconnect branch" which is different from being able to switch to manual build & deploy

**Comment by ryanhightower** [comment]
@swaminator why was this issue closed? This is still a problem and really annoying. We tried connecting a repo to do CI/CD, but we are seeing problems with Amplify's build process when trying to use Auth and Cognito. So we tried to switch back to manual deploy, only to find it's not possible. This is a huge inconvenience for us and causing serious delays in our development schedule.

**Comment by joe-kong** [comment]
If you start from the Amplify Console's home page and connect your project's code repository (by clicking Connect app button), the frontend environment is created for your project once the workflow successfully completes. After setting up hosting in the Amplify Console, you cannot run the amplify hosting add command from your local installation of the Amplify CLI. To disable hosting, please visit the Amplify Console and disconnect the branch from the App settings > General page.

**Comment by joe-kong** [comment]
If you start from the Amplify Console's home page and connect your project's code repository (by clicking Connect app button), the frontend environment is created for your project once the workflow successfully completes. After setting up hosting in the Amplify Console, you cannot run the amplify hosting add command from your local installation of the Amplify CLI. To disable hosting, please visit the Amplify Console and disconnect the branch from the App settings > General page.

**Comment by fgiopp** [comment]
You just need to disconnect ALL branches before changing type of hosting.
