### ISSUE TITLE
Problem cloning repository in AWS-amplify from codeCommit

### ISSUE THREAD

**Issue by linfiesto** [aws-amplify/amplify-console#958]
Hi,

When cloning repository during the build process of amplify it says 

2020-08-12T02:37:14.776Z [ERROR]: !!! Unable to assume specified IAM Role. Please ensure the selected IAM Role has sufficient permissions and the Trust Relationship is configured correctly.
2020-08-12T02:37:14.907Z [INFO]: # Starting environment caching...
2020-08-12T02:37:14.908Z [INFO]: # Environment caching completed
Terminating logging...

I never had problem with this in my other client's AWS account. I did the standard AWS amplify-backend-console role found here. [https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html] And I made sure my IAM user has AdministratorAccess.

![image](https://user-images.githubusercontent.com/4402009/89969738-beec2a00-dc89-11ea-9e2f-db27d7dacecb.png)

**Comment by behrooziAWS** [comment]
Can you provide your app id and region so we can review the roles?  I'm assuming you created the app and role in the customers account?

**Comment by linfiesto** [comment]
App ARN : arn:aws:amplify:ap-southeast-2:432753647527:apps/d2usi1y6ntza0t
Region : ap-southeast-2

I'm assuming you created the app and role in the customers account?
Yes, I created the app using amplify console and service role in the customer's AWS account, he has provided an account with an AdministratorAccess

**Comment by linfiesto** [comment]
@behrooziAWS 

> Can you provide your app id and region so we can review the roles? I'm assuming you created the app and role in the customers account?

App ID : d2usi1y6ntza0t
Region : ap-southeast-2

I'm assuming you created the app and role in the customers account?
Yes, I created the app using amplify console and service role in the customer's AWS account, he has provided an account with an AdministratorAccess

**Comment by linfiesto** [comment]
SOLVED: To those who may have experience similar problem just check your IAM > Access management > Account settings. Make sure you're STS permission is active for that region, in my case Asia pacific (Sydney) was inactive which was causing the error.

![image](https://user-images.githubusercontent.com/4402009/91108896-d7a60800-e6ab-11ea-9fe5-a0c7445e9271.png)

**Comment by ralph-tice** [comment]
@linfiesto i wouldn't mark this solved until the error message is fixed 
![image](https://user-images.githubusercontent.com/2474730/103382264-3688ed00-4aa3-11eb-8c89-de681f7483f8.png)

this error should suggest users check this STS setting for the region they're operating in

**Comment by linfiesto** [comment]
@ralph-tice the error message is fixed when I checked the appropriate region in the IAM STS settings. See my comment above.

**Comment by ralph-tice** [comment]
The error message should tell the user to check the approprate region in the IAM STS settings, not force them to guess to look there.  See my original comment and this one.

Instead of:
```...click "Re-authenticate app" in General Settings...```

try:
```...Check that IAM STS is regionally enabled<link to IAM > Access management > Account settings>, then click "Re-authenticate app" in General Settings...```
