### ISSUE TITLE
SSL configuration is Running - Domain ownership check stalled

### ISSUE THREAD

**Issue by brad07** [aws-amplify/amplify-console#959]
**App Id**: d21vce5yp2y418
**Region**: ap-southeast-2
**Step**: SSL configuration
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Domain ownership check in Amplify isn't progressing. CNAME record has been confirmed but no progress.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by behrooziAWS** [comment]
This process can sometimes take up to 24 hours to complete, is this still an issue for you?

**Comment by brad07** [comment]
Yes it has been quite a few days now. 

It says that it failed and that I should retry. I've now retried multiple times with no success even though I can see the CNAME record is available in our DNS when using a third-party DNS lookup tool.

**Comment by hsspain** [comment]
@brad07 I have verified that there is a custom domain on that app which has been verified and live. Is this regarding a separate custom domain? Are you still having this issue?

**Comment by brad07** [comment]
We finally got it to complete the activation process.

Thanks
