### ISSUE TITLE
What VPC do the build instances run in - or what IP range are they on?

### ISSUE THREAD

**Issue by tscole** [aws-amplify/amplify-console#960]
** Please describe which feature you have a question about? **
Automated Builds

** Provide additional details**
I am having issues with builds as my app connects to an RDS instance in order to populate data at build time. The RDS instance is set to be publicly accessible but so far the only way I can allow the build instance to connect to it is to allow all connections in the security group rules. I'd rather not have things that open. Is there a way I can allow the build instances to access the RDS database - e.g. using an IP range / VPC / etc - but not open it up to everywhere?

**Comment by behrooziAWS** [comment]
Since how we build and the associated ip ranges can change, you likely want to pursue using iam to access your RDS instance: https://aws.amazon.com/premiumsupport/knowledge-center/users-connect-rds-iam/
