### ISSUE TITLE
Build appears to hang in "deploy" phase

### ISSUE THREAD

**Issue by tscole** [aws-amplify/amplify-console#961]
App ID: dxk3ongyqntym
Region: eu-west-1

I am trying to build and deploy a gridsome site with tens of thousands of files. Provision and build steps complete in the console without problems but the Deploy stage appears to hang. I have tried a couple of times and each time the log stops showing output after approx 16,400 lines (files copied) and it appears the process never completes.

**Comment by cslogan-red** [comment]
Hi there, please see the more recent comments on #115 for more information on this issue and a technical explanation, this is currently our top priority and we are providing updates in that thread as testing progresses this month, closing this as a duplicate.

**Comment by tscole** [comment]
Sorry - but are you sure this is a duplicate of #115 ? The comments on that thread seem to be about total files in the repo. My issue is with total files generated by the Build stage not the contents of the repo...

**Comment by cslogan-red** [comment]
Positive :) #115 revolves around the total number of built and deployed (hosted) files in an app, which doesn't necessarily corelate (but can, depending on your framework) to the number of files in your repo. This issue will be resolved w/ the release of #115 , follow that thread for updates, thx!
