### ISSUE TITLE
CNAME records not yet configured- domain activation

### ISSUE THREAD

**Issue by asatvilker** [aws-amplify/amplify-console#965]
**App Id**: d1djbarh3iptp7   
**Region**: eu-west-2
**Step**: Domain activation
**Status**: "The required CNAME records are not yet configured for the below subdomains.
Click "Actions > View DNS Records" and configure the required CNAME records with your DNS provider: www.adamsatvilker.com"

**Issue/question**
I am currently stuck at the step mentioned above, with the above status message shown. I followed the steps amplify console user guide to setup a custom domain for **goDaddy**. it appeared to be successful and i went through the SSL creation and SSL configuration steps with no issues. however now I am getting this message and nothing is happening. I tried troubleshooting it by using the console user guide. 
as it is saying the **CNAME is not configured**, i went on whatsmydns.net to check and it is showing that it is **resolving correctly**

if you could please help me get my domain working that would be greatly appreciated.

**Error message**
"The required CNAME records are not yet configured for the below subdomains.
Click "Actions > View DNS Records" and configure the required CNAME records with your DNS provider: www.adamsatvilker.com"

**Additional information**
![image](https://user-images.githubusercontent.com/56475258/90197104-90736980-ddc5-11ea-8adf-4ab3003733b6.png)

**Comment by anubnair** [comment]
I am facing the same issue. Can you help to resolve?

**Comment by asatvilker** [comment]
So I presume you are using GoDaddy? if so, follow the instructions in the screenshot above. when you view the record. copy it and where you initially created your CNAME record in goDaddy change the value part to the value you copied. then save and wait a while (potentially even 24hrs) it should then work

**Comment by anubnair** [comment]
Its been more than 24hrs. i am still waiting for it,

**Comment by sapasaa** [comment]
hi there, did you fix it?

**Comment by anubnair** [comment]
not yet for me!

**Comment by asatvilker** [comment]
If your stuck on the same page i was in that screenshot, and ur domain is with goDaddy then the steps I mentioned above should work. Remember when you click actions > view dns records. The value it shows for the CNAME has to be put in the current CNAME record you have already put in from the step before. So ur updating a current dns record not creating a new one. Maybe try starting from the start? Could be an issue recognising the dns record so try deleting the domain and all CNAME records you created in your goDaddy, then start the process again and follow the steps i mentioned when you get to the point in the screenshot?
Hope this helps, apologies if it doesn’t, only thing i can think of since there’s no actual error its a case of it being incomplete or appearing incomplete to aws?

**Comment by sapasaa** [comment]
Yep! deleted all DNS records that I made and started again.

**Comment by anubnair** [comment]
My issue got resolved.

1) Make sure that you added CNAME  provided by aws to your 3rd party DNS provider properly 
2) You need to create and  add the NS recreated by route 53 to DNS provider

**Comment by varunmehta1986** [comment]
I am getting the same issue as well. Although my website is running fine.

@anubnair, I tried to follow 2nd point you mentioned and updated the NS at GoDaddy. Now GoDaddy says "We can't display your DNS information because your nameservers aren't managed by us." and on AWS Amplify Domain Management I see its still stuck on Domain Activation

**Comment by anubnair** [comment]
1) Create hosted zone (for domain/subdomain) in aws
2)You need SSL certification. Say your website is xyz.com you can request SSL certificate for *.xyz.com in that way this is a certificate for main and the subdomains
3) After that, go to hostedzone, fetch the "NS" created by aws and add to go daddy. (still website is not up yet)...
3) Once you do everything, go to amplfy app, created custom domain, choose the route 53 hosted zone. Then it will show the appropriate CNAME. We need to add that to godaddy

Thats all :)

**Comment by Aryaman19** [comment]
Go to the actions (in the image which you have shown - at the top right corner) . Then follow step 4 given in this documentation (https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-godaddy.html).

1. Go to actions(in image which you have shown , there is one action button) and then go to View DNS Records.
2. Copy whatever(like xxxxxxx.cloudfront.net) is written after CNAME.
3. Go to your GoDaddy account and add the cname with www host name and value of points will be the one which you have copied.

P.S- If you are creating hosted zones on amazon route53, then you don't have to configure your dns records in goDaddy , Just add nameservers in there and then follow this documentation https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-amazon-route-53.html

**Comment by brnmye** [comment]
Refer to our documentation to troubleshoot domain setup.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error
Let us know if you're still facing issues.

**Comment by alnoor** [comment]
I am looking for a solution to the same problem. I registered a site using route 53. www.myroute53site.com. i started with a static web site and and it worked fine. myroute53.com displayed my hello world. I moved on to amplify. moved test code to github and using amplify got to the point where i get the following 
The required CNAME records are not yet configured for the below subdomains.
Click "Actions > View DNS Records" and configure the required CNAME records with your DNS provider
 
my provider is route53  - is there somewhere i can look to find out how to fix this - thanks in advance

**Comment by brnmye** [comment]
We are going to close out this issue, but please feel free to re-open if you still need help.

**Comment by remybroun** [comment]
I am having the same issue as @edonadei.

**Comment by emacaz** [comment]
Hi everyone, I'm having the same issue, I've tried making the same settings that I've seen here but it hadn't work yet. My DNS provider is Wordpress. Could somebody help me with it? Thank you!!!

**Comment by petrovi4** [comment]
I have the same problem. Moreover, the domain is purchased from GoDaddy, the NS of the AWS server is configured there, and the correct CNAMEs are configured in AWS Route 53. I.e. all settings are done in Route 53 of AWS itself. And still I see this message about "The required CNAME records are not yet configured for the below subdomains"

**Comment by barbaroreyes** [comment]
hi there. same here
