### ISSUE TITLE
Access denied error - only for certain routes

### ISSUE THREAD

**Issue by asatvilker** [aws-amplify/amplify-console#966]
**app info**
-app id: d1djbarh3iptp7
-region: eu-west-2

hi, i am currently getting the following error **however only for a specific route**. the home **/** and **/blog** routes are working fine however when i got to **blog/title-of-blog**  i am getting the following error. note I have added a redirect which works however this just redirects me to index.html which is a blank html page. the contents of that page is not loading so the redirect solution is not what i'm looking for. i need to fix this route so it works like the others

![image](https://user-images.githubusercontent.com/56475258/90211782-9713d800-dde9-11ea-842d-76591aa1073a.png)

**additional info**
-react app
-create react app
-routes are created using react-router

if you could please help me get this route working that would be greatly appreciated, thank you

**Comment by AlexSCorey** [comment]
I'm getting this same error for the root route

**Comment by hsspain** [comment]
@asatvilker @AlexSCorey Please try setting up a SPA redirect rule detailed here: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa

**Comment by asatvilker** [comment]
Unfortunately that spa redirect rule isn’t the solution. Very weirdly when I tried to use it, it works in the sense i don’t get an access denied error however all my css files seem to be missing and all the styling of every page is gone? I cannot explain the reason behind this. However, i added my own redirect rules which solved the issue.

I simply added a rule for: /blog/<*>, destination: index.html, type:200(rewrite) and it worked as expected. If its a particular page you are getting this error for I recommend you try adding this rule. The <*> just means any name (if the address is dynamic). Hope this helps

And if you experienced the issue of the styling of your site being messed up after using the spa rule, don’t forget to clear your browser data before you try the redirect rule I suggested above. (If not the browser will load the recently cached version of your site so it will appear as if its made no difference and the styling is still missing) this had me confused for a while ahaha

**Comment by litwicki** [comment]
@AlexSCorey @asatvilker This can also happen if your build directory is not set correctly. For example if your frontend is built to `build` your buildspec will need to point to that or you will see this error. 

For more info: https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#yml-specification-syntax

```  artifacts:
    baseDirectory: build
    files:
      - '**/*'

**Comment by siegerts** [comment]
Closing this for now based on the `baseDirectory` suggestion above.  Also, I've opened a PR to add this to the troubleshooting FAQ. Please reopen if this pops up again.

https://github.com/aws-amplify/amplify-console/pull/1740
