### ISSUE TITLE
After making a bad change to build YML file, I can't view my project in the console dashboard. 

### ISSUE THREAD

**Issue by thevarunraja** [aws-amplify/amplify-console#969]
I think I have made a change to the build YML file(which might be invalid). Now I can't view my dashboard, which means I can't fix my bad build YML file as well. I am seeing the error in the browser console. 

<img width="1680" alt="Screen Shot 2020-08-15 at 10 59 16 PM" src="https://user-images.githubusercontent.com/17805098/90325619-f853bc80-df4b-11ea-9f41-31a3c74f826b.png">

**Comment by cslogan-red** [comment]
@thevarunraja this appears to be a bug on our end and a fix will be rolling out shortly, in the meantime, you can use the AWS CLI along with our [updateApp API](https://docs.aws.amazon.com/amplify/latest/APIReference/API_UpdateApp.html#API_UpdateApp_RequestSyntax) to issue a new buildSpec with valid content consisting of [one applications array with at least a single appRoot](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html) as it appears this app was setup as a monorepo app.

**Comment by cslogan-red** [comment]
Fix is rolling and will be GA by 8/24.

**Comment by Athena96** [comment]
Hello all, thank you for your patience. We have deployed a fix for this, so it should no longer be an issue. Feel free to re-open this ticket if you continue to face this or related issues. Thank you!
