### ISSUE TITLE
Deleting Amplify project does not remove associated stacks from CloudFormation

### ISSUE THREAD

**Issue by nealdeters** [aws-amplify/amplify-console#974]
** Please describe which feature you have a question about? **
When deleting an Amplify project from CLI or from the Amplify Console

I've created a couple of tests projects using Amplify. There were a couple of instances where things didn't go so smoothly during the building of these projects, so I decided to delete them using the Amplify Console delete action. This seemed to remove the project from the Amplify Console, however in looking at CloudFormation, I still see associated stacks were not removed. I've gone through and manually deleted them, but it was my assumption that these stacks would be deleted as well since the overall project was deleted.

**Comment by swaminator** [comment]
@nealdeters currently you have to use the Amplify CLI to delete the backend stack. We will be enabling that workflow from the console in the coming months.

**Comment by nealdeters** [comment]
@swaminator so just to clarify, the Delete App button in the Amplify console will remove all associated stacks as well in the coming months? But currently the correct way is to delete via the CLI and that should remove all associated stacks? 

![Screen Shot 2020-08-19 at 9 03 09 AM](https://user-images.githubusercontent.com/3708718/90644969-ffecbd00-e1fa-11ea-9392-637c30b3bd3d.png)

If that's the case, why is the Delete App button even there right now in the Amplify console?

**Comment by swaminator** [comment]
@nealdeters if you have frontend branches those are deleted. This is a point in time thing and will be resolved soon.

**Comment by skanjo** [comment]
I work with Neal on the same project and wanted to add a little bit more to this issue report.

We recently noticed that deleting the root CF for an Amplify application deployment does not delete the backend environment. Instead the backend environment is orphaned with no way to delete from command line or from AWS Console.

I did find a workaround to delete the orphaned backend environment. Delete the S3 deployment bucket and then from the command line create a new environment and push the application to that enviromment. Once the deployment completes successfully then switch to another environment at the command line and then delete the desired environment from the command line which then removes all resources including the once orphaned backend environment.

**Comment by eduardohki** [comment]
I found the same issue while testing Amplify Console deployments via CDK.

To remove the orphaned environments, I had to go to CloudFormation and delete the Stacks myself to clean the resources + delete the s3 buckets manually.

**Comment by SalahAdDin** [comment]
I did work for me right now.

**Comment by PanadeEdu** [comment]
How is this closed? 
I just encountered this exact problem and are now left with lots of orphanized services.

**Comment by tobiasfeil** [comment]
When I delete a stack (that was created by `amplify init`) in CloudFormation, it still shows up in the Amplify dashboard and can't be deleted. This is highly undesirable. As a user, I would like to be able to assume that whenever I delete a stack in CFN, everything associated with it disappears.

**Comment by GonrasK** [comment]
Is there any update on this one? Lots of orphanized services here as well.
