### ISSUE TITLE
Domain activation is Failed - Unable to link react-app with custom domain

### ISSUE THREAD

**Issue by elainepeilingchong** [aws-amplify/amplify-console#975]
**App Id**: dm0s9svozuhgj
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Unable to activate the domain, have linked it with one of the account but the account is closed now and would like to link to another one. Did remove the old one before closing and update the DNS record.

**Issue/question**
Would like to make the react app link with the custom-domain but unable to do that 

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by cslogan-red** [comment]
Hi @elainepeilingchong, sorry to hear that, I do still see another app tied to an active account consuming this domain, you'll need to create a case with customer support and they will validate ownership of the domain and we can then help you from there: https://console.aws.amazon.com/support/home

In the future, if you ever decide to close an AWS account that still has Amplify app(s) with custom domain(s), make sure to delete the Amplify app(s) before closing the account, as this will ensure the custom domain distributions are properly removed, thanks!

**Comment by elainepeilingchong** [comment]
hi @cslogan-red thank you for helping!! As I am under Basic plan, so I cannot create a technical case, would you mind to let me know which account is linking to it? I have tried to find but no luck for it. I believe I can remove it easily after I have more details about it

**Comment by cslogan-red** [comment]
Sorry, I'm unable to confirm any of that information here, you can raise a billing/account support case w/ even the basic plan and would explain your scenario, they can help confirm ownership of your accounts and domain - thanks!

**Comment by elainepeilingchong** [comment]
okay no problem. Thanks!

**Comment by hsspain** [comment]
Closing this issue. Please feel free to reach back out if you still need help.
