### ISSUE TITLE
Domain activation is Failed - distribution includes an incorrectly configured DNS record error

### ISSUE THREAD

**Issue by teemuniiranen** [aws-amplify/amplify-console#976]
**App Id**: d1dxm5ell5n4xd & dtsnuk3sgyg34
**Region**: eu-central-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Domain activation fails stating that there is an incorrectly configured DNS record. Both are using the same domain, root disabled and different sub domains. There is also one CloudFront distribution outside Amplify that is using www subdomain. There should not be any overlapping because all three distributions use different sub domains.

Also Actions -> View DNS Records link is disable so it is impossible to check anymore that what records should be. Host command on my laptop resolves to cloudfront domain name that was instructed in the start of the process.

**Error message**
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Additional information**
DNS resolves to right distributions. Both where first stuck in the domain verification first because DNS change took too long. I deleted the domains and recreated. This created new cloudfront domain names so I changed these in DNS. Now we are in this situation.

It would be nice to see also CloudFront distributions created by Amplify in AWS Console. It makes things hard to debug.

Also UI is not refreshing. After I press retry button status is changed to "Retry in progress". After I refresh the page in my browser the status changes to failed.

**Comment by teemuniiranen** [comment]
Any progress?

**Comment by teemuniiranen** [comment]
@cslogan-red It is soon two weeks since placing this issue.

**Comment by cslogan-red** [comment]
@teemuniiranen our customer on-call this week will take a look at this for you, as of now I see two custom domain CF distributions (one for each app Id you provided) and each is configured for the same domain root, I'm not seeing any ADN's (prefixes) configured on either distribution, so these are conflicting w/ each other.

I would delete both of the custom domains you added to the Console and add each back, one at a time to each app, making sure to select "exclude root" as you indicated and provide one sub-domain at a time, waiting for DNS validation to succeed before adding the second sub-domain in the other app. If you're still having issues @gwryssekk is our customer on-call this week and will be able to take a look further w/ you, thanks!

**Comment by teemuniiranen** [comment]
@cslogan-red ok, these are conflicting each other even "exclude root" has been selected. I try again one at a time. Thank you!

**Comment by teemuniiranen** [comment]
@gwryssekk I deleted the domain from both application. Subdomain is configured now only on dtsnuk3sgyg34 with "exclude root" option but Domain activation part fails with the same error. Host name is resolving to correct cloudfront domain name.

**Comment by teemuniiranen** [comment]
@gwryssekk I retried in the console just but I got the same error. Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Comment by teemuniiranen** [comment]
@cslogan-red & @gwryssekk have you checked what might be the issue? Thanks!

**Comment by teemuniiranen** [comment]
@cslogan-red & @gwryssekk it is now 3 weeks since opening the issue. Integration with 3rd party DNS shouldn't be this hard. This is holding us from production roll out.

**Comment by teemuniiranen** [comment]
@nimacks I saw your response in https://github.com/aws-amplify/amplify-console/issues/1033. Sounds like similar issue here also.

**Comment by teemuniiranen** [comment]
@cslogan-red, @gwryssekk: it is now full month since placing the ticket. We are still waiting for the production domains. Any news?

**Comment by cslogan-red** [comment]
@teemuniiranen unfortunately I can only confirm that CloudFront returns this error when your domain's DNS records are associated w/ another resource, see the following.

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/#:~:text=Short%20description,associated%20with%20another%20CloudFront%20distribution.

The last time you attempted to connect this subdomain, I see that we successfully created the CF distribution for the custom domain, but the attempt to update that distribution with your specific sub-domain (alias) is resulting in the CNAMEAlreadyExists exception from CloudFront - we simply relay that message in our Console, and have no control over CloudFront's behavior in validating your specific sub-domain.

Looking at whatsmydns.net for your root domain, www, and the new sub-domain you're attempting to add, it looks like multiple DNS providers are being used for different parts of this domain; which is not a configuration we recommend, and is not something under Amplify Console's control or that we can help configure.

**Comment by teemuniiranen** [comment]
@cslogan-red thank you for your response! Could it be that this is happening because the root domain (or naked domain name) has an A record to a static IP address which redirects to www sub domain? Www is an alias for other CloudFront distribution that is provisioned outside Amplify. Could it be that this root domain still is somehow affecting even you don't use it and tick the "exlude root". Is there still some validation checks? If so why? Shouldn't be enough to check just the actual sub domain that you are trying to configure for the application?

**Comment by teemuniiranen** [comment]
We removed the A record for the root from the DNS and retry from the Amplify console tomorrow.

**Comment by teemuniiranen** [comment]
@cslogan-red same thing still. There is only one DNS provider used but I think that root level A record to static IP misled you.

Is that retry even working? You see "retry in progress" when you press retry button but it's never finished. If I refresh the page I get the same error. Now we have only www in place in other non-amplify created CloudFront distribution and root A record pointing to localhost.

**Comment by teemuniiranen** [comment]
Ok retry is not working. Now after removing the root A record redirect AND recreating the domain settings it is working for the first application. We continue with the second.

**Comment by ganipcanot** [comment]
Sounds like you got a handle on it - if you are still having issues please re-open this ticket.
