### ISSUE TITLE
AWS Amplify App custom domain registration error

### ISSUE THREAD

**Issue by nagacheruvu** [aws-amplify/amplify-console#979]
**App Id**: d3ldgeq2sl75h1
**Region**: us-east-1
**Step**: SSL Verification
**Status**: stuck in pending state

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.
SSL Verification & domain validation is failing for AWS amplify with go daddy domain after switching DNS server to Route 53

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by nagacheruvu** [comment]
In order to verify domain ownership, configure the following CNAME record associated with your domain and verify that the CNAME record exists in your Domain Name Server (DNS) file.

**Comment by nimacks** [comment]
@nagacheruvu is this still an issue?

**Comment by dimeloper** [comment]
@nimacks probably yes, my amplify build is stuck on this step too. CNAME record is in place since a few days.

**Comment by nagacheruvu** [comment]
You can close it...issue resolved

**Comment by kim00425** [comment]
@nagacheruvu how did you solve it? i have face on that issue.
