### ISSUE TITLE
Domain activation is Failed - Domain activation continues to fail

### ISSUE THREAD

**Issue by bmyrtil** [aws-amplify/amplify-console#981]
**App Id**: d2nup1jy5x4e3l
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Receiving the following error on domain activation. We have verified the DNS record and checked it against https://www.whatsmydns.net/ but still cant activate the domain

**Error message**
One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem.

**Comment by cslogan-red** [comment]
Your domain is already associated with another CloudFront distribution in another AWS account, you can [contact support](https://console.aws.amazon.com/support/cases#/create) if you wish to establish ownership of this account.
