### ISSUE TITLE
Angular production builds stall

### ISSUE THREAD

**Issue by pdashford** [aws-amplify/amplify-console#982]
just recently when doing an angular prod build on Amplify the build just stalls, I don't get any meaningfull information from the build logs. There must be something happening but can't get any more detailed information.

last line of build is;

  chunk {36} 36-es5.c95e7b073ecf8e594a6e.js () 22.1 kB  [rendered]
                                 chunk {scripts} scripts.1a6721b3b5e5b52260dc.js (scripts) 630 kB [entry] [rendered]

**Comment by gwryssekk** [comment]
No response since 2020-08-21.  Closing for now.  Please reopen if this is still an issue.
