### ISSUE TITLE
Random Redirect Issue on Certain Branches in Amplify Project

### ISSUE THREAD

**Issue by kylegwalsh** [aws-amplify/amplify-console#983]
**Please fill out all fields before submitting**

1. **Issue Description**

We seem to be encountering some strange behavior when working with a few of our AWS Amplify branches. On some branches, we are seeing a random number pre-pended to the URL path ONLY IF the path provided does not have a trailing slash. What's very strange about this bug is that it does not occur on other branches (even though they use the same redirect rules).

For our framework, we are using React + Gatsby (Javascript / Typescript) to build our website.

Here are our redirect rules.

Redirect Rules:
[
  {
    "source": "/checkout/<*>",
    "target": "/checkout/index.html",
    "status": "200",
    "condition": null
  },
  {
    "source": "</index\\\\\\\\.html/>",
    "target": "/404.html",
    "status": "404-200",
    "condition": null
  },
  {
    "source": "/kit/",
    "target": "/products/kit/",
    "status": "301",
    "condition": null
  },
  {
    "source": "/products/",
    "target": "/products/kit/",
    "status": "301",
    "condition": null
  }
]

The first two redirect rules in the list are the main redirect rules that influence the Gatsby redirects. The first rule is meant to allow the checkout route to be managed by a single file (like a small SPA). The second rule is meant to show our 404 template when a route is found that does not correspond to our actual pages. If I had to guess, the second rule may be the culprit (but it works perfectly on our master branch).

It would make sense that a redirect rule would cause the issue. I'm just not sure why it only affects certain branches.

1. **Detailed Steps To Reproduce**

Try the following URLs:

**master Branch** - Scenario 1 (Works correctly)
Entered URL: https://offer.selecttv.com/products/kit
Redirected URL: https://offer.selecttv.com/products/kit/

**master Branch** - Scenario 2 (Works correctly)
Entered URL: https://offer.selecttv.com/products/kit/
Redirected URL: https://offer.selecttv.com/products/kit/

**test/master** Branch - Scenario 1 (DOES NOT WORK CORRECTLY)
Entered URL: https://new.offer.selecttv.com/products/kit
Redirected URL: https://new.offer.selecttv.com/0000000008/products/kit/

**test/master** Branch - Scenario 2 (Works correctly)
Entered URL: https://new.offer.selecttv.com/products/kit/
Redirected URL: https://new.offer.selecttv.com/products/kit/ (edited)

1. **Expected behavior**

The strange number should not be injected in the URL during a redirect.

1. **Application Details**

    a. Please share your Amplify Console AppID, found in `App settings > General > App ARN` (e.g. `arn:aws:amplify:us-west-2:XXXXXXXXXXX:apps/APPID`)

**d22vd8i9nndi7q**
    
    b. The specific Branch and Build number we should investigate
    
**master** (working correctly)
**test/master** (not working correctly)

    c. Your buildspec (*the version at the time the issue occurred*), [either from the Amplify console or amplify.yml](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html) (Be sure to remove any sensitive data)

**version: 0.2**

**Comment by cslogan-red** [comment]
Please see the back in forth in #70: `</index\.html/> => /404.html` is proper format for this particular issue.

**Comment by kylegwalsh** [comment]
I'm actually using that exact format in the amplify console for the 404: `</index\.html/> => /404.html`

I pulled this list of redirect rules from the JSON in the console and it must escape the forward slash. Therefore, I believe this issue should be reopened.
