### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by theseanodell** [aws-amplify/amplify-console#99]
**App Id**: d379kw2zyx8wnk
**Region**: us-west-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Domain Activation Failed

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
DNS was not originally with Route53. Moved domain registrar from Google Domains to Route53 and setup DNS.

**Comment by nimacks** [comment]
Hi @theseanodell, can you please verify your AppId again?

**Comment by theseanodell** [comment]
Are you looking for the AppARN?

**Comment by nimacks** [comment]
@theseanodell, I'm unable to locate the app with appId : d379kw2zyx8wnk. Just wanted confirmation that the app still exists and the Id is correct.

**Comment by theseanodell** [comment]
@nimacks sorry, i rebuilt to do some testing. https://master.dqitj0na0tptz.amplifyapp.com 
is the new app.

**Comment by nimacks** [comment]
ah ha! Perfect. thanks for the update. I'll look into this now.

**Comment by nimacks** [comment]
Hi @theseanodell , you already have an app with id `dtl99hsttpzhe ` configured to your custom domain. If you would like to set the app with id `dqitj0na0tptz` to use this domain, you'll need to detach your custom domain from the first one.

**Comment by theseanodell** [comment]
While that may seem to be the case, I do not have an app ID setup for this domain in my account.

I have doubled checked the GUI and see nothing.

Should I check via CLI?

**Comment by theseanodell** [comment]
Found the issue. Thanks for working through this.
