### ISSUE TITLE
Build gets stuck both when trying to deploy manually and when using auto-build from github repository

### ISSUE THREAD

**Issue by judygab** [aws-amplify/amplify-console#992]
I tried connecting my app to my github repository, initially it was able to deploy empty react repo. When I added amplify to my project, build was failing because it was not able to find 'aws-exports.js' file since it was git ignored. Than I updated my build setting to include '- amplifyPush --simple' for the backend, hoping that it would solve the error, but provisioning step took couple of hours, so I tried to deploy build zip file manually and that's also taking a long time. Is there anything else that I can try?

**Comment by swaminator** [comment]
@judygab sorry to hear the challenges you're dealing with. Can you share your AppID? Found in app settings > general

**Comment by judygab** [comment]
> @judygab sorry to hear the challenges you're dealing with. Can you share your AppID? Found in app settings > general

@swaminator sure! I believe this is the one 'd3a2ok9za0no6w' or do you need App ARN?

**Comment by ganipcanot** [comment]
Resolving due to age - please re-open if you are still experiencing issues.
