### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by ofek-rusaev** [aws-amplify/amplify-console#994]
**App Id**: d26jpnccdxqdem
**Region**: eu-west-1
**Step**: Domain activation
**Status**: Failed

**Issue/question**
In my Amplify console I had one app that was connected to my custom domain, after few weeks it has disappeared from my console, so I have created and re-connected my git ripo to the new app and tried to set again my own customized domain.
I've deleted the CNAME's of the first app from my DNS in GoDaddy doamin settings.
After setting up again the SSL configuration, with the CNAME's of the new app that was created, I keep receiving that Domain activation failed due to "One or more of the CNAMEs you provided are already associated with a different resource."
However, as I can't see my fisrt app in my console, I have no way of solving this.
Please advice.

**Error message**
"One or more of the CNAMEs you provided are already associated with a different resource."

**Additional information**
Attached screenshots of the error received and the only app that I am able to access on my console.

<img width="960" alt="01" src="https://user-images.githubusercontent.com/53981912/90976814-f9d34500-e548-11ea-8dd0-eabec9bd056c.png">
<img width="960" alt="02" src="https://user-images.githubusercontent.com/53981912/90976821-0061bc80-e549-11ea-9d3a-67cd8802bc8b.png">

**Comment by hsspain** [comment]
@ofek-rusaev

It looks like your domain is associated with an app in the us-east-1 region. Can you switch to that region and see if your app exists there?

**Comment by ofek-rusaev** [comment]
Yes it's there, sorry didn't realize the region effects my display.
Thanks for you help! 🥇
