### ISSUE TITLE
Does Country Code support wildcard?

### ISSUE THREAD

**Issue by yuyokk** [aws-amplify/amplify-console#995]
Hi Team,

I need to limit application to some countries only so my question is whether `Country Code` supports wildcard?

Please let me know if this code makes sense - redirecting all countries to `not-supported-region.html` and US to `index.html`.

```json
[
    {
        "source": "<*>",
        "target": "/index.html",
        "status": "200",
        "condition": "<US>"
    },
    {
        "source": "<*>",
        "target": "/not-supported-region.html",
        "status": "200",
        "condition": "<*>"
    }
]
```

Thank you 🙏

**Comment by hsspain** [comment]
The redirects will be executed from top down, therefore if the US country code condition matches first, it will use that redirect, all others will use the next redirect.

We do not support wildcard county codes, but they will not be necessary based on your needs.

https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html

**Comment by yuyokk** [comment]
> We do not support wildcard county codes, but they will not be necessary based on your needs.

oh empty value is equal to `*`!

Thanks for reply
