### ISSUE TITLE
SSL Cert expired despite being hosted on amplify

### ISSUE THREAD

**Issue by ehawk61** [aws-amplify/amplify-console#996]
**App Id**: arn:aws:amplify:us-east-2:446001775534:apps/d33fregj5h7efy
**Region**: us-east-2
**Step**: Completed, Expiration of SSL Cert
**Status**: Site Triggers browser to display a warning of security issue instead of going to the site

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
My Certs have expired for the two domains I have with AWS amplify but it is not clear how to refresh them. The documentation indicates that they are refreshed on their own provided things are hosted on AWS Amplify, which they are

**Error message**
Error message from a browser visiting the site:

> Warning: Potential Security Risk Ahead
> Firefox detected an issue and did not continue to <redacted>. The website is either misconfigured or your computer clock is set to the wrong time.
>
> It’s likely the website’s certificate is expired, which prevents Firefox from connecting securely. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.
>
> What can you do about it?
>
> The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by swaminator** [comment]
@ehawk61 we are looking into this. When did you add your initial domains?

**Comment by ehawk61** [comment]
I believe it was July of 2019

**Comment by hsspain** [comment]
@ehawk61 Please try removing the custom domains from your app, re-verify the DNS records, then re-add the domains. We are determining the root cause of the issue, but this should provide an immediate fix while we investigate.

**Comment by ehawk61** [comment]
For clarity, what do you mean by re-verifying the DNS records? Is that something I need to do or is done in the creation of the domain in the app?

**Comment by hsspain** [comment]
You just need to ensure that the CNAME DNS records match what the Amplify Console is displaying for that custom domain. If they match, then no action is necessary.

**Comment by hsspain** [comment]
@ehawk61 When an SSL certificate is renewed our systems first verify that the CNAME records still match the verification records you set when first associating your custom domain.

In this instance, the records did not match or were not found so the certificate did not renew. If you re-add them, you should again have a valid SSL certificate. Please let us know if this works for you.

**Comment by ehawk61** [comment]
Working on the first domain, found in the DNS record that the CNAME record provided in the amplify creation process was not listed in the domain previously. Added the CNAME record provided by the amplify SSL configuration step to the DNS record.

**Comment by ehawk61** [comment]
@hsspain The SSL configuration process is stalled after waiting 48 hours. Can you assist?

**Comment by ehawk61** [comment]
Got a failure messaging saying the CNAME verification was not in my Route53 DNS record, double-checked the record and it exists. Retrying the SSL configuration process.

**Comment by hsspain** [comment]
@ehawk61 I will look at this right now.

**Comment by hsspain** [comment]
@ehawk61 It looks like the validation timed out on the new certification. You will need to update your CNAME verification records when you remove/add a custom domain.  Please try again today and we will keep an eye on it for you as well.

**Comment by ehawk61** [comment]
Removed the CNAME record in AWS Route53 and restarted the SSL verification

**Comment by hsspain** [comment]
@ehawk61 Can you remove the custom domain, re-add the domain, then verify that the CNAME records are correct in Route 53?  Retrying the process may not work in this case.

**Comment by ehawk61** [comment]
Removed, re-added and verified the CNAME records match both in Route53 and Google Domains.

**Comment by ehawk61** [comment]
First domain cleared. Did the above steps for the 2nd domain, currently waiting for SSL Configuration

**Comment by ehawk61** [comment]
Issue resolved. Closing issue.

**Comment by ffxsam** [comment]
Just ran into this today (SSL cert expired with no warning). There really needs to be a warning email about this!

@swaminator

**Comment by iocuydi** [comment]
Ran into this issue today. Have had several domains hosted on amplify for over a year. One of them randomly expired today, the rest (hosted for longer than the expired one) did not? There should definitely be a warning for this, switching to netlify asap

**Comment by kptac** [comment]
Ran into the same issue! Had to remove and add domain again to fix the problem! App ID: d3jafph357pom3

This is horrible from Amplify - we had a lot of customers calling in!

**Comment by gallivangames** [comment]
same issue, redoing amplify now.  I am using the AWS cert management tool but it's not coordinating them across amplify.  it also never alerted me or sent me an email that there was an issue.
