### ISSUE TITLE
SSL configuration is Failed - using transfer domain from Wix

### ISSUE THREAD

**Issue by gdelvalle99** [aws-amplify/amplify-console#999]
**App Id**: d3079s06rtmw2g
**Region**: us-east-2
**Step**: SSL configuration
**Status**: Failed

**Issue/question**
I want to use a custom domain on an AWS Amplify app. I transferred the domain from Wix, created a hosted zone and also added the new name servers. SSL configuration keeps failing, and whenever I click "retry", it says that it's restarting the verification process for the domain.

**Error message**
There is no error message. It simply says "Something went wrong".

**Additional information**
CNAME is also displayed right after the error message.

**Comment by hsspain** [comment]
@gdelvalle99 We are looking into this now. Did you transfer the domain to Route 53?

**Comment by gdelvalle99** [comment]
Yeah, I did.

**Comment by hsspain** [comment]
@gdelvalle99 It appears that the DNS checks are failing for your domain. Can you ensure that the CNAME records are being set properly in your name server?

**Comment by gdelvalle99** [comment]
What should I look for? I have 6 records: 3 CNAME records, one SOA record, one NS record and one A record. One of the CNAME records corresponds to the same CNAME that Amplify shows me. Should I delete the other that doesn't match?

**Comment by hsspain** [comment]
It will be a CNAME record that looks something like: 

randomtoken.domain.com. CNAME randomtoken.random.acm-validations.aws.

The exact record will be displayed in the custom domain settings screen.

**Comment by gdelvalle99** [comment]
The CNAME records match. Is there a specific setting that it should have?

**Comment by hsspain** [comment]
@gdelvalle99 Sometimes, DNS records take some time to propagate (up to 24 hours). Please retry and let us know if it is still failing after that time.

**Comment by gdelvalle99** [comment]
@hsspain I retried the process this morning but it still fails. I am wondering if the issue might be with the console instead. Whenever I click retry, it perpetually stays there for hours without any indication that the process is happening. When I refresh the page or open up the console on another browser, it says that the process failed.

**Comment by hsspain** [comment]
@gdelvalle99 Please remove the custom domain from the Amplify app and re-add it. Because this is a Route 53 domain now, it goes through a different verification path.  Let us know if that resolves the issue.

**Comment by gdelvalle99** [comment]
I did and now it works. Thanks for all the help!

**Comment by hsspain** [comment]
You are welcome.
